Repository RobotLocomotion/drake, pull requests merged in 2018-07, with the labels that each got.

#9076 MBP contact results output port.
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/contact_info.cc
  multibody/multibody_tree/multibody_plant/contact_info.h
  multibody/multibody_tree/multibody_plant/contact_results.cc
  multibody/multibody_tree/multibody_plant/contact_results.h
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/box.sdf
  multibody/multibody_tree/multibody_plant/test/box_test.cc
Labels: priority: high, team: dynamics, type: feature request

#9085 Update externals to latest commits
  multibody/multibody_tree/parsing/scene_graph_parser_detail.cc
  tools/workspace/fcl/repository.bzl
  tools/workspace/ignition_math/package.BUILD.bazel
  tools/workspace/ignition_math/repository.bzl
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/lcm/repository.bzl
  tools/workspace/sdformat/package.BUILD.bazel
  tools/workspace/sdformat/repository.bzl
Labels: priority: low

#8973 [Multilane] Adds Builder::Connect to support lane-to-lane Connections
  automotive/maliput/multilane/BUILD.bazel
  automotive/maliput/multilane/builder.cc
  automotive/maliput/multilane/builder.h
  automotive/maliput/multilane/connection.cc
  automotive/maliput/multilane/cubic_polynomial.cc
  automotive/maliput/multilane/cubic_polynomial.h
  automotive/maliput/multilane/test/multilane_builder_test.cc
  automotive/maliput/multilane/test/multilane_connection_test.cc
  automotive/maliput/multilane/test/multilane_loader_test.cc
  automotive/maliput/multilane/test/multilane_road_curve_accuracy_test.cc
  automotive/maliput/multilane/test_utilities/multilane_types_compare.cc
  automotive/maliput/multilane/test_utilities/multilane_types_compare.h
Labels: status: curate commits before merging

#9044 Adding in torsional springs to RigidBodyTree
  multibody/BUILD.bazel
  multibody/joints/BUILD.bazel
  multibody/joints/drake_joint.h
  multibody/joints/drake_joint_impl.h
  multibody/joints/fixed_axis_one_dof_joint.h
  multibody/joints/fixed_joint.h
  multibody/joints/quaternion_ball_joint.h
  multibody/joints/quaternion_floating_joint.h
  multibody/joints/roll_pitch_yaw_floating_joint.h
  multibody/joints/test/joint_test.cc
  multibody/rigid_body.h
  multibody/rigid_body_tree.cc
  multibody/rigid_body_tree.h
  multibody/test/rigid_body_tree/rigid_body_tree_spring_test.cc
Labels: status: curate commits before merging

#9098 Implements getter methods for fixed poses
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/body.h
  multibody/multibody_tree/fixed_offset_frame.h
  multibody/multibody_tree/frame.h
  multibody/multibody_tree/test/frames_test.cc
Labels: priority: backlog, priority: high, team: dynamics

#9110 Update SHA for styleguide
  tools/workspace/styleguide/repository.bzl
Labels: configuration: bazel, team: kitware

#9112 Add MBP's ContactResults to LCM system
  examples/simple_gripper/BUILD.bazel
  examples/simple_gripper/README.md
  examples/simple_gripper/simple_gripper.cc
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/contact_results_to_lcm.cc
  multibody/multibody_tree/multibody_plant/contact_results_to_lcm.h
  multibody/multibody_tree/multibody_plant/test/contact_results_to_lcm_test.cc
Labels: priority: high, type: feature request

#9111 Joint limits in MBP
  multibody/multibody_tree/joints/joint.h
  multibody/multibody_tree/joints/prismatic_joint.h
  multibody/multibody_tree/joints/revolute_joint.h
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/joint_limits_test.cc
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc
Labels: priority: high, team: dynamics, type: feature request

#9115 Defaults collision geometry to be invisible.
  examples/simple_gripper/simple_gripper.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
Labels: team: dynamics

#9116 Defaults friction coefficients to 1.0 when reading from an SDF file
  multibody/multibody_tree/parsing/BUILD.bazel
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.h
  multibody/multibody_tree/parsing/scene_graph_parser_detail.cc
  multibody/multibody_tree/parsing/sdf_parser_common.h
  multibody/multibody_tree/parsing/test/links_with_visuals_and_collisions.sdf
  multibody/multibody_tree/parsing/test/multibody_plant_sdf_parser_test.cc
Labels: priority: high, team: dynamics, type: feature request

#8951 Adds continuous extension support at integrator's level
  systems/analysis/BUILD.bazel
  systems/analysis/continuous_extension.h
  systems/analysis/dense_output.h
  systems/analysis/hermitian_dense_output.h
  systems/analysis/integrator_base.h
  systems/analysis/stepwise_dense_output.h
  systems/analysis/test/hermitian_continuous_extension_test.cc
  systems/analysis/test/hermitian_dense_output_test.cc
  systems/analysis/test/runge_kutta2_integrator_test.cc
  systems/analysis/test/runge_kutta3_integrator_test.cc
Labels: status: curate commits before merging

#9140 Add Jeremy's change to return the result of execution.
  tools/workspace/execute.bzl
Labels: status: do not merge

#9142 Remove leftover references to input port "descriptors"
  automotive/automotive_simulator.cc
  automotive/bicycle_car.h
  automotive/car_vis_applicator.h
  automotive/test/bicycle_car_test.cc
  automotive/test/car_vis_applicator_test.cc
  automotive/test/idm_controller_test.cc
  automotive/test/mobil_planner_test.cc
  automotive/test/pure_pursuit_controller_test.cc
  automotive/test/simple_car_test.cc
  bindings/pydrake/systems/rendering_py.cc
  bindings/pydrake/systems/test/rendering_test.py
  examples/particles/test/particle_test.cc
  examples/particles/test/utilities_test.cc
  examples/valkyrie/actuator_effort_to_rigid_body_plant_input_converter.h
  examples/valkyrie/robot_state_encoder.h
  manipulation/schunk_wsg/schunk_wsg_plain_controller.h
  multibody/rigid_body_plant/rigid_body_plant.h
  systems/framework/diagram.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/vector_system_test.cc
  systems/primitives/test/adder_test.cc
  systems/primitives/test/first_order_low_pass_filter_test.cc
  systems/primitives/test/integrator_test.cc
  systems/rendering/pose_aggregator.cc
  systems/rendering/pose_aggregator.h
  systems/rendering/test/pose_aggregator_test.cc
  systems/sensors/accelerometer.h
  systems/sensors/depth_sensor.h
  systems/sensors/depth_sensor_to_lcm_point_cloud_message.h
  systems/sensors/gyroscope.h
  systems/sensors/image_to_lcm_image_array_t.h
  systems/sensors/rgbd_camera.h
Labels: team: dynamics, team: software core, type: cleanup

#9141 Implements a spring-damper force element for MBP.
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/linear_spring_damper.cc
  multibody/multibody_tree/linear_spring_damper.h
  multibody/multibody_tree/test/linear_spring_damper_test.cc
Labels: priority: high, team: dynamics, type: feature request

#9126 Make Gurobi retry downloading license
  solvers/BUILD.bazel
  solvers/gurobi_solver.cc
  solvers/gurobi_solver.h
  solvers/no_gurobi.cc
  solvers/test/gurobi_solver_test.cc
Labels: status: curate commits before merging

#9090 [Multilane] Loader to support lane-to-lane connections.
  automotive/maliput/multilane/loader.cc
  automotive/maliput/multilane/test/multilane_loader_test.cc
  automotive/maliput/multilane/test_utilities/multilane_types_compare.cc
  automotive/maliput/multilane/test_utilities/multilane_types_compare.h
Labels: status: curate commits before merging

#9157 Transform point cloud
  perception/BUILD.bazel
  perception/test/transform_point_cloud_test.cc
  perception/transform_point_cloud.cc
  perception/transform_point_cloud.h
Labels: status: curate commits before merging

#8972 Clutter generator
  examples/kuka_iiwa_arm/models/objects/open_top_box.urdf
  manipulation/scene_generation/BUILD.bazel
  manipulation/scene_generation/random_clutter_demo.cc
  manipulation/scene_generation/random_clutter_generator.cc
  manipulation/scene_generation/random_clutter_generator.h
  manipulation/scene_generation/simulate_plant_to_rest.cc
  manipulation/scene_generation/simulate_plant_to_rest.h
  manipulation/scene_generation/test/test_random_clutter_to_rest.cc
  multibody/ik_options.h
Labels: priority: high, team: manipulation

#8939 Add RgbdRendererOSPRay
  multibody/shapes/visual_element.cc
  multibody/shapes/visual_element.h
  systems/sensors/BUILD.bazel
  systems/sensors/rgbd_camera.cc
  systems/sensors/rgbd_camera.h
  systems/sensors/rgbd_renderer_ospray.cc
  systems/sensors/rgbd_renderer_ospray.h
  systems/sensors/test/models/background.jpg
  systems/sensors/test/models/meshes/box.json
  systems/sensors/test/models/meshes/box2.obj
  systems/sensors/test/rgbd_renderer_ospray_test.cc
  tools/install/libdrake/BUILD.bazel
  tools/workspace/vtk/repository.bzl
Labels: status: curate commits before merging

#9168 List of welded bodies in MBT
  multibody/multibody_tree/multibody_tree_topology.h
  multibody/multibody_tree/test/multibody_tree_creation_test.cc
Labels: priority: high, team: dynamics

#9174 Add TSan Suppressions for libc, libembree3 and libtbb
  tools/dynamic_analysis/tsan.supp
Labels: priority: high, type: sanitizer-tsan

#9169 A unit test for a spring-mass system with damping in MBP.
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/test/spring_mass_system_test.cc
Labels: team: dynamics

#9188 Add check for minimum supported Bazel version
  CMakeLists.txt
  WORKSPACE
  tools/workspace/bazel_skylib/BUILD.bazel
  tools/workspace/bazel_skylib/repository.bzl
  tools/workspace/default.bzl
Labels: team: kitware

#9190 Disable support for multiple Python versions for a library on MacOS
  tools/install/install.py.in
Labels: priority: emergency

#9197 Minor cleanup of pkg_config.bzl
  tools/workspace/pkg_config.bzl
Labels: team: kitware, type: cleanup

#9173 Adds MultilaneOnRamp generator to automotive simulator.
  automotive/BUILD.bazel
  automotive/automotive_demo.cc
  automotive/multilane_onramp_merge.cc
  automotive/multilane_onramp_merge.h
  automotive/test/multilane_onramp_merge_test.cc
Labels: status: curate commits before merging
