Repository RobotLocomotion/drake, pull requests merged in 2018-03, with the labels that each got.

#8206 MBT getters refactor
  examples/multibody/acrobot/acrobot_plant.cc
  examples/multibody/pendulum/pendulum_plant.cc
  manipulation/planner/differential_inverse_kinematics.cc
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  multibody/benchmarks/acrobot/make_acrobot_plant.cc
  multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h
  multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.cc
  multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.h
  multibody/multibody_tree/acceleration_kinematics_cache.h
  multibody/multibody_tree/articulated_body_inertia_cache.h
  multibody/multibody_tree/body.cc
  multibody/multibody_tree/body.h
  multibody/multibody_tree/body_node.h
  multibody/multibody_tree/fixed_offset_frame.cc
  multibody/multibody_tree/frame.h
  multibody/multibody_tree/joints/joint.h
  multibody/multibody_tree/joints/revolute_joint.cc
  multibody/multibody_tree/joints/revolute_joint.h
  multibody/multibody_tree/joints/test/revolute_joint_test.cc
  multibody/multibody_tree/mobilizer.h
  multibody/multibody_tree/mobilizer_impl.h
  multibody/multibody_tree/multibody_forces.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/multibody_tree_context.h
  multibody/multibody_tree/multibody_tree_element.h
  multibody/multibody_tree/multibody_tree_topology.h
  multibody/multibody_tree/position_kinematics_cache.h
  multibody/multibody_tree/quaternion_floating_mobilizer.cc
  multibody/multibody_tree/revolute_mobilizer.cc
  multibody/multibody_tree/revolute_mobilizer.h
  multibody/multibody_tree/rigid_body.h
  multibody/multibody_tree/space_xyz_mobilizer.cc
  multibody/multibody_tree/test/articulated_body_algorithm_test.cc
  multibody/multibody_tree/test/floating_body_plant.cc
  multibody/multibody_tree/test/floating_body_test.cc
  multibody/multibody_tree/test/frames_test.cc
  multibody/multibody_tree/test/free_rotating_body_plant.cc
  multibody/multibody_tree/test/multibody_forces_test.cc
  multibody/multibody_tree/test/multibody_tree_creation_test.cc
  multibody/multibody_tree/test/multibody_tree_test.cc
  multibody/multibody_tree/test/rigid_body_test.cc
  multibody/multibody_tree/test/tree_from_joints_test.cc
  multibody/multibody_tree/test/tree_from_mobilizers_test.cc
  multibody/multibody_tree/uniform_gravity_field_element.cc
  multibody/multibody_tree/velocity_kinematics_cache.h
Labels: team: dynamics, type: cleanup

#8188 Add CPack configuration for building Debian packages, etc.
  CMakeLists.txt
  tools/install/install.py.in
  tools/install/libdrake/VERSION.TXT.in
Labels: team: kitware, type: installation and distribution

#8215 Remove MATLAB mathematical_program_test and dead MATLAB code
  matlab/BUILD.bazel
  matlab/CMakeLists.txt
  matlab/CPPLINT.cfg
  matlab/addpath_drake.m
  matlab/addpath_drake.m.in
  matlab/addpath_drake_install.m
  matlab/call_matlab_client.cc
  matlab/cmake/packages.cmake
  matlab/mex_util.cc
  matlab/mex_util.h
  matlab/test/CMakeLists.txt
  matlab/test/call_matlab_test.rpc
  matlab/test/mathematical_program_test.m
Labels: configuration: cmake, configuration: matlab

#8222 Move bot_core_lcm_encode_decode into its own file
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/dev/box_rotation/BUILD.bazel
  examples/kuka_iiwa_arm/dev/pick_and_place/BUILD.bazel
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_planner.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_demo.cc
  examples/kuka_iiwa_arm/pick_and_place/BUILD.bazel
  examples/kuka_iiwa_arm/pick_and_place/world_state.cc
  examples/valkyrie/BUILD.bazel
  examples/valkyrie/robot_state_decoder.cc
  examples/valkyrie/robot_state_encoder.cc
  manipulation/util/BUILD.bazel
  manipulation/util/bot_core_lcm_encode_decode.cc
  manipulation/util/bot_core_lcm_encode_decode.h
  manipulation/util/robot_state_msg_translator.cc
  manipulation/util/robot_state_msg_translator.h
  manipulation/util/test/bot_core_lcm_encode_decode_test.cc
  manipulation/util/test/robot_state_msg_translator_test.cc
  multibody/rigid_body_plant/test/drake_visualizer_test.cc
  multibody/rigid_body_plant/test/viewer_draw_translator_test.cc
  systems/controllers/BUILD.bazel
  systems/controllers/InstantaneousQPController.cpp
  systems/controllers/plan_eval/manipulator_move_end_effector_plan.cc
  systems/controllers/plan_eval/test/manipulator_plan_test.cc
  systems/controllers/qp_inverse_dynamics/BUILD.bazel
  systems/robotInterfaces/BUILD.bazel
  systems/robotInterfaces/QPLocomotionPlan.cpp
  util/BUILD.bazel
  util/lcmUtil.h
Labels: priority: low

#8228 Fix python version on macOS
  doc/python_bindings.rst
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs_user_environment.sh
Labels: configuration: mac

#8234 Ensure brew update is called before brew bundle
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
Labels: configuration: mac

#8147 Multibody actuators
  multibody/benchmarks/acrobot/make_acrobot_plant.cc
  multibody/benchmarks/acrobot/make_acrobot_plant.h
  multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.cc
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/joint_actuator.cc
  multibody/multibody_tree/joint_actuator.h
  multibody/multibody_tree/joints/revolute_joint.h
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/multibody_tree_indexes.h
  multibody/multibody_tree/multibody_tree_topology.h
  multibody/multibody_tree/rigid_body.h
  multibody/multibody_tree/test/multibody_tree_test.cc
Labels: team: dynamics, type: feature request

#8145 Adds the machinery for MBP to talk with GS.
  examples/multibody/acrobot/BUILD.bazel
  examples/multibody/acrobot/acrobot_plant.cc
  examples/multibody/acrobot/acrobot_plant.h
  examples/multibody/acrobot/acrobot_state.named_vector
  examples/multibody/acrobot/passive_simulation.cc
  multibody/benchmarks/acrobot/make_acrobot_plant.cc
  multibody/benchmarks/acrobot/make_acrobot_plant.h
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.cc
Labels: team: dynamics

#8249 Remove if block from snopt BUILD file
  tools/workspace/snopt/package.BUILD.bazel
Labels: team: kitware

#8250 Print warning and do not fail if MATLAB version cannot be determined
  matlab/cmake/packages.cmake
Labels: priority: high, team: kitware

#8223 Use --strict_system_includes for bazel
  tools/bazel.rc
Labels: priority: low

#8276 Fix Wshadow warnings from GCC (automotive)
  automotive/maliput/multilane/road_geometry.cc
  automotive/maliput/multilane/test/multilane_loader_test.cc
Labels: priority: low

#8280 Repair some broken bazel user manual URLs in documentation
  doc/bazel.rst
Labels: priority: low

#8286 Give lyapunov_test a longer timeout for valgrind
  systems/analysis/BUILD.bazel
Labels: priority: high

#8284 Fix Wshadow warnings from GCC (shapes)
  multibody/collision/element.cc
  multibody/shapes/geometry.cc
  multibody/shapes/visual_element.cc
  multibody/shapes/visual_element.h
Labels: priority: low

#8277 Fix Wshadow warnings from GCC (trajectories)
  common/trajectories/exponential_plus_piecewise_polynomial.cc
  common/trajectories/piecewise_function.cc
  common/trajectories/piecewise_function.h
  common/trajectories/piecewise_polynomial.cc
  common/trajectories/qp_spline/spline_information.cc
Labels: priority: low

#8283 Fix Wshadow warnings from GCC (joints)
  multibody/joints/drake_joint.cc
  multibody/joints/drake_joint.h
  multibody/joints/fixed_axis_one_dof_joint.h
  multibody/joints/quaternion_ball_joint.cc
  multibody/joints/quaternion_floating_joint.cc
  multibody/joints/roll_pitch_yaw_floating_joint.cc
Labels: priority: low

#8292 Updates pendulum passive simulation to use MBP
  examples/multibody/pendulum/BUILD.bazel
  examples/multibody/pendulum/passive_simulation.cc
  examples/multibody/pendulum/pendulum_plant.cc
  examples/multibody/pendulum/pendulum_plant.h
  multibody/benchmarks/pendulum/BUILD.bazel
  multibody/benchmarks/pendulum/make_pendulum_plant.cc
  multibody/benchmarks/pendulum/make_pendulum_plant.h
Labels: team: dynamics

#8290 Use /usr/bin/env python2.7 in shebang for python scripts and add linting
  common/test/cpplint_wrapper.py
  doc/code_style_guide.rst
  doc/doxygen.py
  tools/clion/bazel_wrapper
  tools/dev/add_cpplint.py
  tools/dev/check_missing_sources.sh
  tools/dynamic_analysis/kcov.sh
  tools/install/install.bzl
  tools/install/install.py.in
  tools/install/libdrake/build_components_refresh.py
  tools/lint/clang_format_includes.py
  tools/lint/drakelint.py
  tools/workspace/bullet/package-create-cps.py
  tools/workspace/cmake_configure_file.py
  tools/workspace/eigen/package-create-cps.py
  tools/workspace/fmt/package-create-cps.py
  tools/workspace/ignition_math/package-create-cps.py
  tools/workspace/ignition_rndf/package-create-cps.py
  tools/workspace/lcm/package-create-cps.py
  tools/workspace/optitrack_driver/optitrack_client
  tools/workspace/spdlog/package-create-cps.py
Labels: team: kitware

#7851 Update drake-visualizer and vtk pre-compiled binaries
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/16.04/binary_distribution/packages.txt
  setup/ubuntu/16.04/source_distribution/packages.txt
  systems/sensors/rgbd_renderer_vtk.cc
  tools/dynamic_analysis/valgrind.supp
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/vtk/repository.bzl
Labels: team: kitware

#8294 Linearize MBP pendulum model
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
Labels: team: dynamics

#8296 SpatialVector supports symbolic::Expression
  multibody/multibody_tree/math/BUILD.bazel
  multibody/multibody_tree/math/spatial_acceleration.cc
  multibody/multibody_tree/math/spatial_force.cc
  multibody/multibody_tree/math/spatial_vector.h
  multibody/multibody_tree/math/spatial_velocity.cc
  multibody/multibody_tree/math/test/spatial_algebra_test.cc
Labels: team: dynamics, type: feature request

#8305 Fix Wdeprecated warnings in misc places
  common/trig_poly.h
  examples/kuka_iiwa_arm/dev/pick_and_place/state_machine_system.cc
  manipulation/planner/robot_plan_interpolator.cc
  systems/framework/test/value_test.cc
Labels: priority: low

#8303 Fix Wdeprecated warnings in multibody
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_plant.cc
  geometry/geometry_visualization.cc
  multibody/BUILD.bazel
  multibody/collision/bullet_model.cc
  multibody/collision/bullet_model.h
  multibody/collision/fcl_model.cc
  multibody/rigid_body_frame.cc
  multibody/rigid_body_frame.h
  multibody/rigid_body_plant/rigid_body_plant_bridge.cc
  multibody/rigid_body_tree.cc
  multibody/shapes/geometry.cc
  multibody/shapes/geometry.h
  multibody/shapes/visual_element.h
  multibody/test/rigid_body_frame_test.cc
  systems/rendering/drake_visualizer_client.cc
  systems/sensors/rgbd_renderer_vtk.cc
Labels: priority: low

#8308 Ensure shared libraries have SONAME set
  tools/skylark/drake_cc.bzl
  tools/workspace/bullet/package.BUILD.bazel
  tools/workspace/ignition_math/package.BUILD.bazel
  tools/workspace/ignition_rndf/package.BUILD.bazel
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/osqp/package.BUILD.bazel
  tools/workspace/pycps/repository.bzl
  tools/workspace/scs/package.BUILD.bazel
Labels: team: kitware

#8317 Docs on shift operation and composition of accelerations.
  multibody/multibody_tree/math/spatial_acceleration.h
  multibody/multibody_tree/math/spatial_force.h
  multibody/multibody_tree/math/spatial_velocity.h
Labels: team: dynamics

#8279 Fix Wshadow warnings from GCC (systems)
  systems/controllers/dynamic_programming.cc
  systems/controllers/dynamic_programming.h
  systems/primitives/time_varying_data.cc
  systems/primitives/time_varying_data.h
Labels: priority: low

#8227 Adds low-level Cache components to ContextBase
  systems/framework/BUILD.bazel
  systems/framework/cache.cc
  systems/framework/cache.h
  systems/framework/context_base.cc
  systems/framework/context_base.h
  systems/framework/dependency_tracker.cc
  systems/framework/dependency_tracker.h
  systems/framework/framework_common.h
  systems/framework/leaf_context.h
  systems/framework/test/cache_test.cc
  systems/framework/test/dependency_tracker_test.cc
Labels: team: dynamics, team: software core, type: feature request

#8332 Use /usr/local/opt/python@2/bin/{python|pip}2.7 on macOS
  doc/python_bindings.rst
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs_user_environment.sh
Labels: configuration: mac, team: kitware

#8340 Follow PEP 394 now that Homebrew (supposedly) does
  bindings/pydrake/test/all_install_test.py
  bindings/pydrake/test/common_install_test.py
  common/test/cpplint_wrapper.py
  common/test/resource_tool_installed_test.py
  doc/code_style_guide.rst
  doc/doxygen.py
  doc/python_bindings.rst
  examples/kuka_iiwa_arm/test/iiwa_wsg_simulation_installed_test.py
  examples/kuka_iiwa_arm/test/kuka_plan_runner_installed_test.py
  examples/kuka_iiwa_arm/test/kuka_simulation_installed_test.py
  lcmtypes/test/drake-lcm-spy_install_test.py
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs_user_environment.sh
  tools/clion/bazel_wrapper
  tools/dev/add_cpplint.py
  tools/install/install.bzl
  tools/install/install.py.in
  tools/install/install_test_helper.py
  tools/install/libdrake/build_components_refresh.py
  tools/lint/clang_format_includes.py
  tools/lint/drakelint.py
  tools/workspace/bullet/package-create-cps.py
  tools/workspace/cmake_configure_file.py
  tools/workspace/eigen/package-create-cps.py
  tools/workspace/fmt/package-create-cps.py
  tools/workspace/ignition_math/package-create-cps.py
  tools/workspace/ignition_rndf/package-create-cps.py
  tools/workspace/lcm/package-create-cps.py
  tools/workspace/lcm/test/lcm-gen_install_test.py
  tools/workspace/optitrack_driver/optitrack_client
  tools/workspace/python/repository.bzl
  tools/workspace/spdlog/package-create-cps.py
Labels: configuration: python, team: kitware

#8325 Switch back to VTK 8.0.1
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/16.04/binary_distribution/packages.txt
  setup/ubuntu/16.04/source_distribution/packages.txt
  systems/sensors/rgbd_renderer_vtk.cc
  tools/workspace/drake_visualizer/drake_visualizer.py
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/vtk/repository.bzl
Labels: team: kitware

#8341 Install links of links instead of copying the file it points to.
  tools/install/install.py.in
  tools/workspace/snopt/package.BUILD.bazel
Labels: priority: high

#8366 Correct test timeouts with ASan
  tools/dynamic_analysis/bazel.rc
Labels: type: build cop

#8367 Pin Mac's lxml to 4.1.1
  setup/mac/binary_distribution/requirements.txt
Labels: type: build cop

#8353 Use CMake build directory for output_user_root where possible
  CMakeLists.txt
  tools/cc_toolchain/bazel.rc.in
Labels: team: kitware

#8379 Set --output_base instead of --output_user_root
  CMakeLists.txt
  tools/cc_toolchain/bazel.rc.in
Labels: team: kitware

#8371 MBT defaults bodies to be free
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/test/floating_body_plant.cc
  multibody/multibody_tree/test/floating_body_plant.h
  multibody/multibody_tree/test/floating_body_test.cc
  multibody/multibody_tree/test/multibody_tree_creation_test.cc
Labels: team: dynamics

#8376 Fix various --incompatible_* errors
  tools/install/install.bzl
  tools/skylark/drake_runfiles_binary.bzl
  tools/vector_gen/vector_gen.bzl
  tools/workspace/cmake_configure_file.bzl
  tools/workspace/generate_export_header.bzl
  tools/workspace/generate_include_header.bzl
  tools/workspace/lcm/lcm.bzl
Labels: team: kitware

#8365 MBP acrobot with LQR controller example
  examples/multibody/acrobot/BUILD.bazel
  examples/multibody/acrobot/run_lqr.cc
  multibody/benchmarks/acrobot/make_acrobot_plant.h
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
Labels: team: dynamics

#8383 Fix incompatible usage of depset union in lcm.bzl
  tools/workspace/lcm/lcm.bzl
Labels: team: kitware

#8399 Update optitrack-driver commit
  tools/workspace/optitrack_driver/repository.bzl
Labels: team: kitware

#8416 Fix MathematicalProgram linking problems
  solvers/BUILD.bazel
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/mathematical_program_api.cc
Labels: priority: emergency

#8426 Tidy some stale //drake labels
  examples/bouncing_ball/BUILD.bazel
  manipulation/dev/BUILD.bazel
  multibody/BUILD.bazel
  multibody/benchmarks/acrobot/BUILD.bazel
  multibody/benchmarks/chaotic_babyboot/MG/BUILD.bazel
  multibody/benchmarks/free_body/BUILD.bazel
  multibody/benchmarks/kuka_iiwa_robot/BUILD.bazel
  multibody/benchmarks/kuka_iiwa_robot/MG/BUILD.bazel
  multibody/benchmarks/mass_damper_spring/BUILD.bazel
  multibody/benchmarks/pendulum/BUILD.bazel
  multibody/collision/BUILD.bazel
  multibody/constraint/BUILD.bazel
  multibody/dev/BUILD.bazel
  multibody/joints/BUILD.bazel
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/math/BUILD.bazel
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/test_utilities/BUILD.bazel
  multibody/parsers/BUILD.bazel
  multibody/parsing/BUILD.bazel
  multibody/rigid_body_plant/BUILD.bazel
  multibody/shapes/BUILD.bazel
  solvers/BUILD.bazel
  systems/analysis/BUILD.bazel
  systems/analysis/test_utilities/BUILD.bazel
  systems/framework/BUILD.bazel
  systems/framework/test_utilities/BUILD.bazel
Labels: priority: low

#8429 Ensure libdrake_dreal.so is writable before calling patchelf
  tools/workspace/dreal/repository.bzl
Labels: team: kitware

#8431 Make Element be explicit about using the global-namespace RigidBody
  multibody/collision/element.cc
  multibody/collision/element.h
Labels: team: dynamics, type: bug

#8451 Prune leftover lcmtypes C bindings code
  tools/workspace/lcm/lcm.bzl
Labels: team: kitware, type: cleanup

#8453 Add unzip to source distribution install_prereqs script
  setup/ubuntu/16.04/source_distribution/packages.txt
Labels: team: kitware

#8449 Remove unused @gthread target
  tools/workspace/default.bzl
  tools/workspace/gthread/BUILD.bazel
  tools/workspace/gthread/repository.bzl
Labels: team: kitware, type: cleanup

#8455 Use python2 to search for NumPy
  tools/workspace/numpy/repository.bzl
Labels: team: kitware, type: cleanup

#8384 Add '--verify' flag to kcov
  tools/dynamic_analysis/kcov.sh
Labels: team: kitware

#8342 Disable 'schunk_wsg_lift_test' for coverage builds
  examples/schunk_wsg/BUILD.bazel
Labels: team: kitware

#8459 Change name of generated BUILD files to BUILD.bazel
  tools/install/install.bzl
  tools/install/install_test.py
  tools/workspace/boost/repository.bzl
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/expat/repository.bzl
  tools/workspace/gflags/repository.bzl
  tools/workspace/gurobi/repository.bzl
  tools/workspace/mosek/repository.bzl
  tools/workspace/numpy/repository.bzl
  tools/workspace/os.bzl
  tools/workspace/pkg_config.BUILD.tpl
  tools/workspace/pkg_config.bzl
  tools/workspace/python/repository.bzl
  tools/workspace/vtk/repository.bzl
  tools/workspace/which.bzl
  tools/workspace/zlib/repository.bzl
Labels: team: kitware, type: cleanup

#8462 Cosmetic changes from caching branch
  systems/analysis/test_utilities/test/controlled_spring_mass_system_test.cc
  systems/framework/diagram.h
  systems/framework/diagram_builder.h
  systems/framework/diagram_context.h
  systems/framework/input_port_descriptor.h
  systems/framework/system.h
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/primitives/random_source.cc
Labels: team: dynamics, type: cleanup

#8461 Don't re-lint the add_test_rule test binary
  tools/skylark/drake_cc.bzl
Labels: priority: low, status: do not merge

#8450 Better handle LCM message publication time
  automotive/automotive_simulator.cc
  examples/valkyrie/test/valkyrie_ik_test.cc
  lcm/drake_lcm.cc
  lcm/drake_lcm.h
  lcm/drake_lcm_interface.h
  lcm/drake_lcm_log.cc
  lcm/drake_lcm_log.h
  lcm/drake_mock_lcm.cc
  lcm/drake_mock_lcm.h
  lcm/test/drake_mock_lcm_test.cc
  manipulation/util/simple_tree_visualizer.cc
  perception/estimators/dev/test/articulated_icp_test.cc
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_publisher_system.h
  systems/lcm/test/lcm_publisher_system_test.cc
Labels: priority: low

#8464 Increase kcov timeouts
  tools/dynamic_analysis/bazel.rc
Labels: team: kitware

#8471 Add and use drake::temp_directory function instead of using /tmp
  automotive/BUILD.bazel
  automotive/automotive_simulator.cc
  bindings/pydrake/common_py.cc
  bindings/pydrake/test/common_test.py
  common/BUILD.bazel
  common/proto/BUILD.bazel
  common/proto/call_matlab.cc
  common/proto/call_python.cc
  common/proto/call_python_client.py
  common/proto/test/call_python_full_test.sh
  common/temp_directory.cc
  common/temp_directory.h
  common/test/temp_directory_test.cc
  matlab/call_matlab_client.cc
  solvers/BUILD.bazel
  solvers/test/snopt_solver_test.cc
  tools/install/libdrake/build_components.bzl
Labels: team: kitware

#8478 Fix language in comments regarding spruce
  automotive/maliput/utility/test/generate_obj_test.cc
  automotive/maliput/utility/test/generate_urdf_test.cc
Labels: team: kitware

#8488 Remove 6996.bzl
  solvers/BUILD.bazel
  systems/analysis/BUILD.bazel
  tools/skylark/6996.bzl
  tools/skylark/drake_cc.bzl
  tools/skylark/drake_java.bzl
  tools/skylark/drake_proto.bzl
  tools/skylark/drake_py.bzl
  tools/skylark/pybind.bzl
Labels: priority: low
