Repository RobotLocomotion/drake, pull requests merged in 2018-06, with the labels that each got.

#8931 Disable print_host_settings_test; it fails on macOS
  common/BUILD.bazel
Labels: priority: emergency

#7055 Integrates soft constraints into drake in a better manner...
  multibody/constraint/constraint_doxygen.h
  multibody/constraint/constraint_problem_data.h
  multibody/constraint/constraint_solver.h
  multibody/constraint/images/colliding-boxes.png
  systems/analysis/integrator_base.h
Labels: type: documentation

#8945 Disable SolveLorentzConeConstraint test
  solvers/test/dreal_solver_test.cc
Labels: priority: emergency, type: build cop

#8971 Contact Queries Refactor
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
Labels: priority: high, team: dynamics, type: cleanup

#8925 Implicit Stribeck solver
  multibody/multibody_tree/implicit_stribeck/BUILD.bazel
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h
  multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test.cc
Labels: priority: high, team: dynamics

#8941 Implicit Stribeck limiter
  multibody/multibody_tree/implicit_stribeck/BUILD.bazel
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h
  multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test.cc
Labels: priority: high, team: dynamics

#8985 workspace: Add support for bionic as a detected platform
  tools/workspace/os.bzl
Labels: priority: low

#8980 workspace: Update osqp to latest
  tools/workspace/osqp/package.BUILD.bazel
  tools/workspace/osqp/repository.bzl
Labels: priority: low

#8984 Refactoring in the Implicit Stribeck solver internals
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h
Labels: priority: high, team: dynamics, type: cleanup

#8992 Updates simple gripper example README after fixing 7874
  examples/simple_gripper/README.md
Labels: priority: high, team: dynamics, type: bug

#8989 plan_eval: Add manipulator_move_end_effector_plan to the build
  systems/controllers/plan_eval/BUILD.bazel
  systems/controllers/plan_eval/manipulator_move_end_effector_plan.cc
  systems/controllers/plan_eval/test/manipulator_plan_test.cc
Labels: priority: low

#8993 analysis: Add missing drake_copyable annotation
  systems/analysis/semi_explicit_euler_integrator.h
Labels: priority: low

#9002 Revert "Add Relative Distance Constraint to RigidBodyTree"
  multibody/BUILD.bazel
  multibody/rigid_body_distance_constraint.cc
  multibody/rigid_body_distance_constraint.h
  multibody/rigid_body_tree.cc
  multibody/rigid_body_tree.h
  multibody/test/rigid_body_distance_constraint_test.cc
  multibody/test/rigid_body_tree/rigid_body_tree_constraint_test.cc
Labels: priority: high, type: build cop

#8999 common: Always provide fmt from text_logging.h
  automotive/maliput/utility/BUILD.bazel
  bindings/pydrake/BUILD.bazel
  common/BUILD.bazel
  common/text_logging.h
  examples/pendulum/BUILD.bazel
  examples/simple_gripper/BUILD.bazel
  math/BUILD.bazel
  systems/framework/BUILD.bazel
Labels: priority: low

#9006 Fixes link in the documentation
  multibody/multibody_doxygen.h
Labels: team: dynamics, type: bug, type: documentation

#9004 manipulation/util: Preserve env for show_model_test
  manipulation/util/test/show_model_test.py
Labels: priority: low

#9000 tools: Remove deprecated vector_gen default values
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/named_vector.proto
Labels: priority: low

#9003 Add underlying S3 bucket as a mirror for dreal download
  tools/workspace/dreal/repository.bzl
Labels: team: kitware

#9005 Complete upgrade of supported Bazel version to 0.14.1
  CMakeLists.txt
  doc/developers.rst
  setup/ubuntu/18.04/source_distribution/install_prereqs.sh
Labels: team: kitware

#8995 Incorporates limiter into the Implicit Stribeck solver
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h
  multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test.cc
Labels: priority: high, team: dynamics

#9012 tools: Add missing add_lint_tests call
  tools/install/BUILD.bazel
  tools/install/install.bzl
Labels: priority: low

#9007 Implements AutoDiff tester for ImplicitStribeckSolver Jacobian.
  multibody/multibody_tree/implicit_stribeck/BUILD.bazel
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h
  multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test.cc
  multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h
Labels: priority: high, team: dynamics

#8676 [Multilane] Adds continuity constraints into the loader
  automotive/maliput/multilane/builder.cc
  automotive/maliput/multilane/builder.h
  automotive/maliput/multilane/connection.cc
  automotive/maliput/multilane/connection.h
  automotive/maliput/multilane/loader.cc
  automotive/maliput/multilane/test/multilane_builder_test.cc
  automotive/maliput/multilane/test/multilane_connection_test.cc
  automotive/maliput/multilane/test/multilane_loader_test.cc
  automotive/maliput/multilane/test_utilities/multilane_types_compare.cc
  automotive/maliput/multilane/test_utilities/multilane_types_compare.h
Labels: status: curate commits before merging

#9024 Update VTK packages to fix CMake issue
  tools/workspace/vtk/repository.bzl
Labels: configuration: linux, team: kitware

#8920 Brings in System-side OutputPort changes in preparation for caching
  systems/framework/BUILD.bazel
  systems/framework/cache.cc
  systems/framework/cache.h
  systems/framework/cache_entry.cc
  systems/framework/cache_entry.h
  systems/framework/context_base.cc
  systems/framework/context_base.h
  systems/framework/diagram.h
  systems/framework/diagram_output_port.h
  systems/framework/framework_common.h
  systems/framework/leaf_output_port.h
  systems/framework/leaf_system.h
  systems/framework/output_port.h
  systems/framework/output_port_base.cc
  systems/framework/output_port_base.h
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/output_port_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/value_test.cc
  systems/framework/test/vector_system_test.cc
  systems/framework/value.h
Labels: status: curate commits before merging

#9030 symbolic: Allow for EIGEN_INITIALIZE_MATRICES_BY_ZERO
  common/symbolic_formula.h
  common/symbolic_monomial.h
  common/symbolic_polynomial.h
  common/symbolic_variable.h
  common/test/symbolic_formula_test.cc
  common/test/symbolic_monomial_test.cc
  common/test/symbolic_polynomial_test.cc
  common/test/symbolic_variable_test.cc
Labels: priority: low

#8986 Add ModelInstance to MultibodyTree
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/body.h
  multibody/multibody_tree/body_node.h
  multibody/multibody_tree/force_element.h
  multibody/multibody_tree/frame.h
  multibody/multibody_tree/frame_base.h
  multibody/multibody_tree/joint_actuator.cc
  multibody/multibody_tree/joint_actuator.h
  multibody/multibody_tree/joints/joint.h
  multibody/multibody_tree/mobilizer.h
  multibody/multibody_tree/model_instance.cc
  multibody/multibody_tree/model_instance.h
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/multibody_tree_element.h
  multibody/multibody_tree/multibody_tree_indexes.h
  multibody/multibody_tree/rigid_body.cc
  multibody/multibody_tree/rigid_body.h
  multibody/multibody_tree/test/model_instance_test.cc
  multibody/multibody_tree/test/multibody_tree_test.cc
  multibody/multibody_tree/uniform_gravity_field_element.cc
Labels: priority: high

#9034 Move matplotlib and tk to binary distribution prerequisities scripts and add pydot
  setup/mac/binary_distribution/requirements.txt
  setup/mac/source_distribution/requirements.txt
  setup/ubuntu/16.04/binary_distribution/packages.txt
  setup/ubuntu/16.04/source_distribution/packages.txt
  setup/ubuntu/18.04/binary_distribution/packages.txt
  setup/ubuntu/18.04/source_distribution/packages.txt
Labels: team: kitware

#9031 Two-way coupled scheme for normal forces
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h
  multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test.cc
  multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test_util.h
Labels: priority: high, team: dynamics

#9035 Added separate C and C++ rules for Gurobi
  multibody/BUILD.bazel
  multibody/approximate_ik.cc
  solvers/BUILD.bazel
  solvers/gurobi_qp.h
  solvers/gurobi_solver.cc
  tools/install/libdrake/BUILD.bazel
  tools/workspace/gurobi/package-macos.BUILD.bazel.in
  tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in
Labels: status: curate commits before merging

#9043 Incorporates the Implicit Stribeck solver in MBP
  examples/multibody/inclined_plane/inclined_plane_run_dynamics.cc
  examples/simple_gripper/simple_gripper.cc
  multibody/benchmarks/inclined_plane/make_inclined_plane_plant.cc
  multibody/benchmarks/inclined_plane/make_inclined_plane_plant.h
  multibody/multibody_tree/implicit_stribeck/BUILD.bazel
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.cc
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc
Labels: priority: high, team: dynamics

#9041 Add per-model-instance input/output ports to MultibodyPlant
  multibody/multibody_tree/model_instance.h
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/parsing/BUILD.bazel
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.h
  multibody/multibody_tree/parsing/test/multibody_plant_sdf_parser_test.cc
Labels: priority: high

#9046 Joint damping
  examples/multibody/pendulum/passive_simulation.cc
  multibody/benchmarks/pendulum/make_pendulum_plant.cc
  multibody/benchmarks/pendulum/make_pendulum_plant.h
  multibody/multibody_tree/joints/joint.h
  multibody/multibody_tree/joints/prismatic_joint.cc
  multibody/multibody_tree/joints/prismatic_joint.h
  multibody/multibody_tree/joints/revolute_joint.cc
  multibody/multibody_tree/joints/revolute_joint.h
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc
  multibody/multibody_tree/parsing/test/multibody_plant_sdf_parser_test.cc
  multibody/multibody_tree/parsing/test/negative_damping_joint.sdf
Labels: priority: high, team: dynamics

#9052 Disable monolithic_pick_and_place_system_test
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel
Labels: priority: emergency

#9053 MBP generalized contact forces output port
  multibody/multibody_tree/implicit_stribeck/implicit_stribeck_solver.h
  multibody/multibody_tree/implicit_stribeck/test/implicit_stribeck_solver_test.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
Labels: priority: high, team: dynamics

#9058 Fixes bug when the state is discrete
  examples/multibody/acrobot/run_lqr.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
Labels: priority: high, team: dynamics, type: bug

#9066 Update Mac CROSSTOOL for Bazel 0.15.0 compatibility
  tools/cc_toolchain/CROSSTOOL
Labels: configuration: mac, team: kitware

#9070 Introduce penetrating pair order invariant guarantee
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/query_object.h
  geometry/test/proximity_engine_test.cc
Labels: priority: high
