Repository RobotLocomotion/drake, pull requests merged in 2018-02, with the labels that each got.

#8017 Fix //drake label names in examples/...
  examples/BUILD.bazel
  examples/acrobot/BUILD.bazel
  examples/atlas/BUILD.bazel
  examples/bead_on_a_wire/BUILD.bazel
  examples/bouncing_ball/BUILD.bazel
  examples/contact_model/BUILD.bazel
  examples/cubic_polynomial/BUILD.bazel
  examples/double_pendulum/BUILD.bazel
  examples/geometry_world/BUILD.bazel
  examples/humanoid_controller/BUILD.bazel
  examples/humanoid_controller/dev/BUILD.bazel
  examples/kinova_jaco_arm/BUILD.bazel
  examples/multibody/acrobot/BUILD.bazel
  examples/multibody/pendulum/BUILD.bazel
  examples/particles/BUILD.bazel
  examples/pendulum/BUILD.bazel
  examples/pr2/BUILD.bazel
  examples/qp_inverse_dynamics/BUILD.bazel
  examples/quadrotor/BUILD.bazel
  examples/rod2d/BUILD.bazel
  examples/schunk_wsg/BUILD.bazel
  examples/valkyrie/BUILD.bazel
  examples/van_der_pol/BUILD.bazel
  examples/zmp/BUILD.bazel
Labels: priority: low

#8020 Remove mention of pylint
  doc/code_style_guide.rst
Labels: priority: low

#8009 MBT Jacobian tests
  multibody/benchmarks/kuka_iiwa_robot/BUILD.bazel
  multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h
  multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_jacobian_test.cc
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/test/multibody_tree_test.cc
Labels: team: dynamics, type: feature request

#8044 Use header-only fmt
  tools/install/libdrake/drake.cps
  tools/workspace/fmt/package-create-cps.py
  tools/workspace/fmt/package.BUILD.bazel
  tools/workspace/spdlog/package-create-cps.py
Labels: team: kitware

#8052 Increase test size for dynamic_programming_test
  systems/controllers/BUILD.bazel
Labels: priority: high

#8040 Specify axis of revolution in unit inertia factory for solid cylinder
  multibody/multibody_tree/test/unit_inertia_test.cc
  multibody/multibody_tree/unit_inertia.h
Labels: team: dynamics, type: feature request

#8064 SpatialVector unary minus operator
  multibody/multibody_tree/math/spatial_vector.h
  multibody/multibody_tree/math/test/spatial_algebra_test.cc
Labels: team: dynamics

#8079 Update supported versions of Bazel and CMake on macOS
  CMakeLists.txt
  doc/developers.rst
Labels: team: kitware

#8083 Fix //drake label names in systems/...
  systems/controllers/BUILD.bazel
  systems/controllers/plan_eval/BUILD.bazel
  systems/controllers/qp_inverse_dynamics/BUILD.bazel
  systems/estimators/BUILD.bazel
  systems/estimators/dev/BUILD.bazel
  systems/lcm/BUILD.bazel
  systems/plants/spring_mass_system/BUILD.bazel
  systems/primitives/BUILD.bazel
  systems/rendering/BUILD.bazel
  systems/robotInterfaces/BUILD.bazel
  systems/sensors/BUILD.bazel
  systems/trajectory_optimization/BUILD.bazel
Labels: priority: low

#8086 Remove traffic_light dev code
  automotive/dev/BUILD.bazel
  automotive/dev/test/traffic_light_test.cc
  automotive/dev/traffic_light.cc
  automotive/dev/traffic_light.h
Labels: priority: low

#8108 Add more examples to never_destroyed
  common/never_destroyed.h
  common/test/never_destroyed_test.cc
Labels: priority: low

#7905 Use static library for SDFormat and do not install
  tools/install/libdrake/BUILD.bazel
  tools/workspace/generate_export_header.bzl
  tools/workspace/sdformat/package-create-cps.py
  tools/workspace/sdformat/package.BUILD.bazel
Labels: team: kitware, type: installation and distribution

#8106 More install_prereqs refactoring
  setup/BUILD.bazel
  setup/mac/install_prereqs.sh
  setup/mac/source_distribution/Brewfile
  setup/mac/source_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs_user_environment.sh
  setup/mac/source_distribution/requirements.txt
  setup/ubuntu/16.04/binary_distribution/install_prereqs.sh
  setup/ubuntu/16.04/binary_distribution/packages.txt
  setup/ubuntu/16.04/install_prereqs.sh
  setup/ubuntu/16.04/source_distribution/install_prereqs.sh
  setup/ubuntu/16.04/source_distribution/packages.txt
Labels: team: kitware

#8026 MBT Geometric Jacobian for frame spatial velocity
  multibody/benchmarks/kuka_iiwa_robot/MG/BUILD.bazel
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/test/multibody_tree_test.cc
  multibody/multibody_tree/test_utilities/spatial_kinematics.h
Labels: team: dynamics, type: feature request

#8132 Do not create empty.cc files on macOS
  tools/workspace/boost/repository.bzl
  tools/workspace/expat/repository.bzl
  tools/workspace/gurobi/repository.bzl
  tools/workspace/mosek/repository.bzl
  tools/workspace/vtk/repository.bzl
  tools/workspace/zlib/repository.bzl
Labels: configuration: mac, team: kitware, type: cleanup

#8136 Set visibility to hidden for libf2c
  tools/workspace/snopt/package.BUILD.bazel
Labels: team: kitware

#8050 Extract just DependencyTracker-related changes from caching
  systems/framework/BUILD.bazel
  systems/framework/cache.cc
  systems/framework/cache.h
  systems/framework/context_base.cc
  systems/framework/context_base.h
  systems/framework/dependency_tracker.cc
  systems/framework/dependency_tracker.h
  systems/framework/diagram.h
  systems/framework/framework_common.h
  systems/framework/system.h
  systems/framework/test/dependency_tracker_test.cc
  tools/install/libdrake/build_components.bzl
Labels: team: dynamics, team: software core, type: feature request

#8139 Fix shebang linting to use @drake for tools
  tools/lint/python_lint.bzl
Labels: priority: high

#8138 Promoted timestepping status on main drake wiki page...
  doc/index.rst
Labels: status: do not review

#8122 adding a MBT version of the differential inverse kinematics.
  manipulation/planner/BUILD.bazel
  manipulation/planner/differential_inverse_kinematics.cc
  manipulation/planner/differential_inverse_kinematics.h
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  multibody/multibody_tree/multibody_tree.cc
Labels: status: curate commits before merging

#8134 Strip installed executables and libraries on macOS
  tools/install/install.py.in
Labels: team: kitware, type: installation and distribution

#8146 Use quoted includes for pybind11
  bindings/pydrake/autodiff_types_pybind.h
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/common_py.cc
  bindings/pydrake/examples/acrobot_py.cc
  bindings/pydrake/examples/pendulum_py.cc
  bindings/pydrake/maliput/api_py.cc
  bindings/pydrake/maliput/dragway_py.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/parsers_py.cc
  bindings/pydrake/multibody/rigid_body_plant_py.cc
  bindings/pydrake/multibody/rigid_body_tree_py.cc
  bindings/pydrake/multibody/shapes_py.cc
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/solvers/gurobi_py.cc
  bindings/pydrake/solvers/ik_py.cc
  bindings/pydrake/solvers/ipopt_py.cc
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/mosek_py.cc
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/symbolic_types_pybind.h
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/framework_py.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/rendering_py.cc
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/test_util_py.cc
  bindings/pydrake/test/odr_test_module_py.cc
  bindings/pydrake/util/cpp_param_pybind.cc
  bindings/pydrake/util/cpp_param_pybind.h
  bindings/pydrake/util/cpp_template_pybind.h
  bindings/pydrake/util/drake_optional_pybind.h
  bindings/pydrake/util/eigen_geometry_py.cc
  bindings/pydrake/util/eigen_geometry_pybind.h
  bindings/pydrake/util/eigen_pybind.h
  bindings/pydrake/util/test/cpp_param_pybind_test.cc
  bindings/pydrake/util/test/cpp_template_pybind_test.cc
  bindings/pydrake/util/test/eigen_geometry_test_util_py.cc
  bindings/pydrake/util/test/type_safe_index_pybind_test.cc
  bindings/pydrake/util/type_safe_index_pybind.h
Labels: configuration: python, team: kitware

#8157 Update dreal version to 4.18.02.4
  setup/ubuntu/16.04/binary_distribution/packages.txt
  tools/workspace/dreal/repository.bzl
Labels: team: kitware

#8135 Implements quaternion mobilizer for free bodies.
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/mobilizer_impl.cc
  multibody/multibody_tree/mobilizer_impl.h
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/quaternion_floating_mobilizer.cc
  multibody/multibody_tree/quaternion_floating_mobilizer.h
  multibody/multibody_tree/test/floating_body_plant.cc
  multibody/multibody_tree/test/floating_body_plant.h
  multibody/multibody_tree/test/floating_body_test.cc
Labels: team: dynamics, type: feature request

#7964 Enable freetype in godotengine; bump to v3.0
  tools/workspace/default.bzl
  tools/workspace/freetype2/BUILD.bazel
  tools/workspace/freetype2/repository.bzl
  tools/workspace/godotengine/package.BUILD.bazel
  tools/workspace/godotengine/repository.bzl
Labels: priority: low

#8172 Remove //drake prefix from build_components.bzl
  tools/install/libdrake/build_components.bzl
Labels: priority: low

#7974 Add freetype to macOS install_prereqs
  setup/mac/source_distribution/Brewfile
Labels: configuration: mac, priority: low

#8176 Disable a test case that fails under valgrind
  multibody/multibody_tree/test/floating_body_test.cc
Labels: priority: emergency

#8153 Prefix library names of vendored external shared libraries
  tools/workspace/bullet/package-create-cps.py
  tools/workspace/bullet/package.BUILD.bazel
  tools/workspace/ignition_math/package-create-cps.py
  tools/workspace/ignition_math/package.BUILD.bazel
  tools/workspace/ignition_rndf/package-create-cps.py
  tools/workspace/ignition_rndf/package.BUILD.bazel
  tools/workspace/lcm/package-create-cps.py
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/osqp/package.BUILD.bazel
  tools/workspace/scs/package.BUILD.bazel
Labels: team: kitware

#8151 Use quoted includes for lcm and external lcmtypes
  examples/kuka_iiwa_arm/dev/box_rotation/box_rotation_demo.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_demo.cc
  examples/kuka_iiwa_arm/kuka_plan_runner.cc
  examples/kuka_iiwa_arm/move_iiwa_ee.cc
  lcm/lcm_receive_thread.h
  multibody/rigid_body_plant/viewer_draw_translator.cc
  perception/estimators/dev/test/test_util.h
  systems/controllers/InstantaneousQPController.cpp
  systems/estimators/dev/pose_estimation_test.cc
  systems/lcm/lcmt_drake_signal_translator.cc
  systems/lcm/test/lcm_driven_loop_test.cc
  systems/robotInterfaces/QPLocomotionPlan.h
Labels: team: kitware

#8182 macOS-focused tweaks to pkg_config_repository
  tools/workspace/pkg_config.bzl
Labels: team: kitware

#8183 Fix warnings about redefinition of _FORTIFY_SOURCE on macOS
  tools/cc_toolchain/CROSSTOOL
Labels: configuration: mac, team: kitware

#8192 Fixes to QuaternionFreeMobilizer
  multibody/multibody_tree/quaternion_floating_mobilizer.cc
  multibody/multibody_tree/test/floating_body_plant.h
  multibody/multibody_tree/test/floating_body_test.cc
Labels: team: dynamics, type: bug
