Repository RobotLocomotion/drake, pull requests merged in 2018-09, with the labels that each got.

#9362 symbolic: Specialize std::numeric_limits
  common/symbolic_expression.cc
  common/symbolic_expression.h
  common/test/symbolic_expression_test.cc
Labels: priority: high

#9361 symbolic: Add Formula(bool) constructor
  common/symbolic_formula.h
  common/test/symbolic_formula_test.cc
Labels: priority: high

#9349 math: Remove symbolic specialization of orthonormal projection
  math/rotation_matrix.h
  math/test/rotation_matrix_test.cc
Labels: priority: low

#9356 Add iiwa polytope collision sdf
  manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf
Labels: priority: high

#9345 py multibody: Add test for joint welding
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
  multibody/benchmarks/free_body/free_body.h
  multibody/multibody_tree/joints/revolute_joint.cc
  multibody/multibody_tree/joints/revolute_joint.h
  multibody/multibody_tree/joints/weld_joint.cc
  multibody/multibody_tree/joints/weld_joint.h
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/test/model_instance_test.cc
Labels: priority: high

#9385 Update VTK to fix issue with multiple contexts on Linux
  tools/workspace/vtk/repository.bzl
Labels: configuration: linux, team: kitware

#9319 Implements MBT::CalcGravityGeneralizedForces()
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
Labels: priority: high, team: dynamics, type: feature request

#9387 Introduces alternative API for inverse dynamics
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/test/tree_from_joints_test.cc
Labels: priority: high, team: dynamics, type: feature request

#9372 Multibody ik
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/angle_between_vectors_constraint.cc
  multibody/inverse_kinematics/angle_between_vectors_constraint.h
  multibody/inverse_kinematics/gaze_target_constraint.cc
  multibody/inverse_kinematics/gaze_target_constraint.h
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/kinematic_constraint_utilities.cc
  multibody/inverse_kinematics/kinematic_constraint_utilities.h
  multibody/inverse_kinematics/orientation_constraint.cc
  multibody/inverse_kinematics/orientation_constraint.h
  multibody/inverse_kinematics/position_constraint.cc
  multibody/inverse_kinematics/position_constraint.h
  multibody/inverse_kinematics/test/angle_between_vectors_constraint_test.cc
  multibody/inverse_kinematics/test/gaze_target_constraint_test.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h
  multibody/inverse_kinematics/test/orientation_constraint_test.cc
  multibody/inverse_kinematics/test/position_constraint_test.cc
  tools/install/libdrake/build_components.bzl
Labels: priority: high

#9388 Implements method to obtain the state vector for a multibody model.
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
Labels: priority: high, team: dynamics, type: feature request

#9378 Bump externals to latest releases
  tools/workspace/fcl/repository.bzl
  tools/workspace/ignition_math/package.BUILD.bazel
  tools/workspace/ignition_math/repository.bzl
  tools/workspace/json/repository.bzl
  tools/workspace/lcm/repository.bzl
  tools/workspace/spdlog/repository.bzl
Labels: priority: low

#9383 Provides public API to access state indexes
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
  multibody/multibody_tree/joint_actuator.cc
  multibody/multibody_tree/joint_actuator.h
  multibody/multibody_tree/joints/joint.h
  multibody/multibody_tree/joints/prismatic_joint.h
  multibody/multibody_tree/joints/revolute_joint.h
  multibody/multibody_tree/joints/test/prismatic_joint_test.cc
  multibody/multibody_tree/joints/test/revolute_joint_test.cc
  multibody/multibody_tree/joints/test/weld_joint_test.cc
  multibody/multibody_tree/joints/weld_joint.h
  multibody/multibody_tree/mobilizer.h
  multibody/multibody_tree/model_instance.cc
  multibody/multibody_tree/model_instance.h
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.h
Labels: priority: high, team: dynamics, type: feature request

#9337 Adds AddVisualization() sugar to cut down on boilerplate
  bindings/pydrake/examples/multibody/cart_pole_passive_simulation.py
  bindings/pydrake/geometry_py.cc
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/contact_model/bowling_ball.cc
  examples/contact_model/sliding_bricks.cc
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
  examples/multibody/acrobot/passive_simulation.cc
  examples/multibody/acrobot/run_lqr.cc
  examples/multibody/bouncing_ball/bouncing_ball_run_dynamics.cc
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
  examples/multibody/inclined_plane/inclined_plane_run_dynamics.cc
  examples/multibody/pendulum/passive_simulation.cc
  examples/pendulum/energy_shaping_simulation.cc
  examples/pendulum/lqr_simulation.cc
  examples/pendulum/passive_simulation.cc
  examples/pendulum/trajectory_optimization_simulation.cc
  examples/scene_graph/bouncing_ball_run_dynamics.cc
  examples/scene_graph/solar_system_run_dynamics.cc
  examples/simple_gripper/simple_gripper.cc
  geometry/geometry_visualization.cc
  geometry/geometry_visualization.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
Labels: team: dynamics, type: feature request

#9405 Multibody ik binding
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/all.py
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/multibody/test/two_bodies.sdf
  bindings/pydrake/test/all_test.py
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/orientation_constraint.h
Labels: priority: high

#9342 Modifies maliput_railcar_test to use multilane instead of monolane.
  automotive/BUILD.bazel
  automotive/test/maliput_railcar_test.cc
Labels: status: curate commits before merging

#9414 Get joint limits
  multibody/multibody_tree/joints/joint.h
  multibody/multibody_tree/joints/prismatic_joint.cc
  multibody/multibody_tree/joints/prismatic_joint.h
  multibody/multibody_tree/joints/revolute_joint.cc
  multibody/multibody_tree/joints/revolute_joint.h
  multibody/multibody_tree/joints/test/prismatic_joint_test.cc
  multibody/multibody_tree/joints/test/revolute_joint_test.cc
  multibody/multibody_tree/joints/test/weld_joint_test.cc
  multibody/multibody_tree/joints/weld_joint.h
Labels: team: dynamics, type: feature request

#9419 Python bindings for state access
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
Labels: priority: high, team: dynamics

#9420 Refactors model() --> tree(). Deprecates model().
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/multibody/bouncing_ball/bouncing_ball_run_dynamics.cc
  examples/multibody/cart_pole/test/cart_pole_test.cc
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
  examples/multibody/cylinder_with_multicontact/test/make_cylinder_plant_test.cc
  examples/multibody/inclined_plane/inclined_plane_run_dynamics.cc
  examples/simple_gripper/simple_gripper.cc
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/multibody_tree/multibody_plant/contact_results_to_lcm.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/box_test.cc
  multibody/multibody_tree/multibody_plant/test/inclined_plane_test.cc
  multibody/multibody_tree/multibody_plant/test/joint_limits_test.cc
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/parsing/test/multibody_plant_sdf_parser_test.cc
  multibody/multibody_tree/test/floating_body_plant.cc
  multibody/multibody_tree/test/floating_body_test.cc
  systems/controllers/inverse_dynamics.cc
  systems/controllers/test/inverse_dynamics_controller_test.cc
  systems/controllers/test/inverse_dynamics_test.cc
  systems/controllers/test_utilities/compute_torque.h
Labels: team: dynamics, type: feature request

#9426 Removes deprecated uses of model()
  multibody/inverse_kinematics/inverse_kinematics.cc
Labels: priority: high

#9406 Adds optional argument for naming input ports
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/drawing_graphviz_example.py
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  geometry/scene_graph.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_tree.h
  systems/framework/diagram.h
  systems/framework/diagram_builder.h
  systems/framework/input_port.h
  systems/framework/input_port_base.cc
  systems/framework/input_port_base.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/test/diagram_builder_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_test.cc
  systems/primitives/signal_logger.cc
  systems/primitives/test/random_source_test.cc
  systems/sensors/beam_model.cc
Labels: status: curate commits before merging

#9432 Revert "py multibody: Bind `AddFrame`"
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
Labels: priority: high, type: build cop

#9407 Support https viewing of MathJax rendered formulae
  doc/Doxyfile_CXX.in
Labels: team: kitware

#9431 Add frame Abar and Bbar to OrientationConstraint.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/orientation_constraint.cc
  multibody/inverse_kinematics/orientation_constraint.h
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/orientation_constraint_test.cc
Labels: priority: high

#9424 Inverse dynamics Python bindings
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/test/controllers_test.py
Labels: priority: high, team: dynamics, type: feature request

#9384 Symbolic uninterpreted_function takes a vector of expressions instead of a set of variables
  common/symbolic_expression.cc
  common/symbolic_expression.h
  common/symbolic_expression_cell.cc
  common/symbolic_expression_cell.h
  common/test/symbolic_expansion_test.cc
  common/test/symbolic_expression_test.cc
  common/test/symbolic_substitution_test.cc
  solvers/test/dreal_solver_test.cc
Labels: team: software core

#9403 Nuke internal LcmInitSystem by enhancing LcmPublisher
  geometry/geometry_visualization.cc
  geometry/geometry_visualization.h
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/lcm_publisher_system.h
  systems/lcm/test/lcm_publisher_system_test.cc
Labels: team: interfaces, type: feature request

#9434 Implements MBP::WeldFrames()
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
  bindings/pydrake/systems/test/controllers_test.py
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
  manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/joint_limits_test.cc
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.h
  systems/controllers/test/inverse_dynamics_controller_test.cc
  systems/controllers/test/inverse_dynamics_test.cc
Labels: priority: medium, team: dynamics, type: feature request

#9440 add python bindings for MBT.SetFreeBodyPoseOrThrow
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
Labels: priority: high

#9435 Updates kuka demo to use MBP ID controller.
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
Labels: priority: backlog, team: dynamics

#9436 framework: Add symbolic formulation of SystemConstraint
  systems/framework/BUILD.bazel
  systems/framework/system.h
  systems/framework/system_constraint.h
  systems/framework/system_symbolic_inspector.cc
  systems/framework/test/system_symbolic_inspector_test.cc
Labels: priority: low

#9449 snopt: Improve error message when SNOPT_PATH is unset
  tools/workspace/snopt/repository.bzl
Labels: priority: low

#9448 clion: Add more and consolidate macOS tips
  doc/clion.rst
Labels: priority: low, type: documentation

#9326 kcov: disable all lint tests; update docs
  doc/bazel.rst
  doc/building_kcov.rst
  tools/dynamic_analysis/bazel.rc
  tools/dynamic_analysis/kcov.sh
Labels: priority: low

#9460 primitives: Repair Doxygen keyword nit
  systems/primitives/linear_system.h
Labels: priority: low

#9136 Review and finalize the cache design document
  attic/multibody/collision/collision_filter_doxygen.h
  bindings/pydrake/pydrake_pybind.h
  common/doxygen_cxx.h
  doc/doxygen.h
  multibody/constraint/constraint_doxygen.h
  multibody/multibody_doxygen.h
  solvers/mathematical_program.h
  systems/framework/cache_doxygen.h
  systems/framework/context.h
  systems/framework/context_base.h
  systems/framework/images/system_context_cache.png
  systems/framework/images/system_context_cache.svg
  systems/framework/leaf_system.h
  systems/framework/system_scalar_conversion_doxygen.h
  systems/systems.h
Labels: team: dynamics, team: software core, type: documentation

#9474 automotive: Remove car_sim_lcm
  automotive/BUILD.bazel
  automotive/README.md
  automotive/car_sim_lcm.cc
  automotive/car_sim_lcm_common.cc
  automotive/car_sim_lcm_common.h
  automotive/models/BUILD.bazel
  automotive/models/speed_bump/speed_bump.sdf
  automotive/models/speed_bump/speed_bump.yaml
Labels: priority: low

#9478 Toward macOS Mojave support
  attic/multibody/rigid_body_plant/rigid_body_plant.cc
  tools/workspace/expat/repository.bzl
  tools/workspace/os.bzl
  tools/workspace/zlib/repository.bzl
Labels: team: kitware

#9513 Fixes SDF parser so that default joint limits are plus/minus infinity.
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc
  multibody/multibody_tree/parsing/test/multibody_plant_sdf_parser_test.cc
Labels: team: dynamics, type: bug

#9521 framework: Add missing #include statement
  systems/framework/BUILD.bazel
  systems/framework/scalar_conversion_traits.cc
  systems/framework/scalar_conversion_traits.h
Labels: priority: high

#9515 Meta-workaround for regex dotall on Mac LLVM 10.0.0
  bindings/pydrake/util/test/cpp_template_pybind_test.cc
Labels: status: curate commits before merging

#9524 Number of positions/velocities for MBT contexts with discrete state
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree_context.h
Labels: priority: high, team: dynamics, type: bug

#9529 Fix a bug in manipulator_joint_space_controller (exporting the wrong output)
  examples/qp_inverse_dynamics/manipulator_joint_space_controller.cc
Labels: priority: medium, type: bug

#9459 Name output ports
  bindings/pydrake/systems/drawing_graphviz_example.py
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  examples/pendulum/pendulum_plant.cc
  examples/pendulum/pendulum_plant.h
  geometry/scene_graph.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  systems/framework/diagram.h
  systems/framework/diagram_builder.h
  systems/framework/diagram_output_port.h
  systems/framework/framework_common.h
  systems/framework/input_port.h
  systems/framework/input_port_base.cc
  systems/framework/input_port_base.h
  systems/framework/leaf_output_port.h
  systems/framework/leaf_system.h
  systems/framework/output_port.h
  systems/framework/output_port_base.cc
  systems/framework/output_port_base.h
  systems/framework/system.h
  systems/framework/system_base.h
  systems/framework/test/diagram_builder_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/output_port_test.cc
  systems/framework/test/system_symbolic_inspector_test.cc
  systems/framework/test/system_test.cc
  systems/primitives/adder.cc
  systems/primitives/signal_logger.cc
  systems/primitives/test/random_source_test.cc
  systems/sensors/beam_model.cc
Labels: priority: high

#9510 Extract documentation for pydrake APIs from C++ headers
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/test/documentation_pybind_test.py
  bindings/pydrake/test/documentation_pybind_usage_test.cc
  setup/ubuntu/16.04/source_distribution/packages.txt
  setup/ubuntu/18.04/source_distribution/packages.txt
  third_party/BUILD.bazel
  third_party/com_github_pybind_pybind11/LICENSE
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/lint/drakelint.py
  tools/skylark/pybind.bzl
  tools/workspace/clang_cindex_python3/BUILD.bazel
  tools/workspace/clang_cindex_python3/package.BUILD.bazel
  tools/workspace/clang_cindex_python3/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pybind11/run_mkdoc_with_python3.py
  tools/workspace/python3/BUILD.bazel
  tools/workspace/python3/repository.bzl
Labels: configuration: python, priority: high, type: documentation
