Repository RobotLocomotion/drake, pull requests merged in 2018-12, with the labels that each got.

#10131 solvers: Resolve link error when SCS is disabled
  solvers/no_scs.cc
Labels: priority: high

#10130 workspace: Update gtest to latest release
  common/test/drake_cc_googletest_main_test.py
  tools/workspace/gtest/repository.bzl
Labels: priority: low, status: do not merge

#10053 Allow manipulation_station to use custom iiwa and wsg models.
  bindings/pydrake/examples/manipulation_station_py.cc
  bindings/pydrake/examples/test/manipulation_station_test.py
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/end_effector_teleop.py
  examples/manipulation_station/joint_teleop.py
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station.h
  examples/manipulation_station/mock_station_simulation.cc
  examples/manipulation_station/print_station_context.py
  examples/manipulation_station/proof_of_life.cc
  examples/manipulation_station/test/manipulation_station_test.cc
Labels: status: curate commits before merging

#10089 Use variant for kUseDefaultName
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  systems/framework/diagram_builder.h
  systems/framework/framework_common.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/system_base.h
Labels: priority: low, status: do not merge

#10136 Permit multiple discrete state groups and model vectors for each
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  systems/framework/discrete_values.h
  systems/framework/leaf_system.h
  systems/framework/test/discrete_values_test.cc
  systems/framework/test/leaf_system_test.cc
Labels: priority: high, team: dynamics, type: feature request

#10145 multibody: Remove parsing-related compat headers
  attic/multibody/parsers/BUILD.bazel
  attic/multibody/parsers/parser_path_utils.h
  attic/multibody/parsers/sdf_parser.cc
  attic/multibody/parsers/urdf_parser.cc
  multibody/multibody_tree/parsing/BUILD.bazel
  multibody/parsing/BUILD.bazel
Labels: priority: medium, status: do not merge

#10150 tools: Don't force -Werror when compiling Drake as an external
  tools/BUILD.bazel
  tools/cc_toolchain/bazel.rc
  tools/lint/library_lint.bzl
  tools/skylark/drake_cc.bzl
Labels: priority: high, status: do not merge

#10151 Remove spurous 'template' keywords
  attic/systems/controllers/qp_inverse_dynamics/robot_kinematic_state_translator_system.h
  automotive/idm_controller.cc
  automotive/mobil_planner.cc
  geometry/dev/scene_graph.cc
  geometry/scene_graph.cc
  multibody/multibody_tree/linear_spring_damper.cc
  systems/primitives/zero_order_hold-inl.h
Labels: priority: high, status: do not merge

#10152 common: Fix drake_variant for C++17
  common/drake_optional.h
  common/drake_variant.h
Labels: priority: high

#10146 pydrake/multibody: Deprecate old parsing methods
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
  bindings/pydrake/examples/multibody/cart_pole_passive_simulation.py
  bindings/pydrake/examples/test/manipulation_station_test.py
  bindings/pydrake/manipulation/test/planner_test.py
  bindings/pydrake/manipulation/test/simple_ui_test.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/parsers.py
  bindings/pydrake/multibody/parsers_py.cc
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/multibody/test/multibody_tree_test.py
  bindings/pydrake/multibody/test/parsing_test.py
  bindings/pydrake/parsers.py
  bindings/pydrake/rbtree.py
  bindings/pydrake/systems/drawing_graphviz_example.py
  bindings/pydrake/systems/test/controllers_test.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
  bindings/pydrake/systems/test/rendering_test.py
  bindings/pydrake/test/all_test.py
  bindings/pydrake/test/backwards_compatability_test.py
  examples/manipulation_station/end_effector_teleop.py
  examples/manipulation_station/joint_teleop.py
  manipulation/util/geometry_inspector.py
Labels: priority: medium

#10141 Consolidate Ubuntu prerequisite install scripts and cleanup associated Dockerfiles
  .dockerignore
  CMakeLists.txt
  doc/docker.rst
  doc/ubuntu.rst
  setup/BUILD.bazel
  setup/docker/Dockerfile.ubuntu16.04.nvidia
  setup/docker/Dockerfile.ubuntu16.04.opensource
  setup/ubuntu/16.04/install_prereqs.sh
  setup/ubuntu/18.04/Dockerfile
  setup/ubuntu/18.04/binary_distribution/install_prereqs.sh
  setup/ubuntu/18.04/install_prereqs.sh
  setup/ubuntu/18.04/source_distribution/install_prereqs.sh
  setup/ubuntu/binary_distribution/install_prereqs.sh
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/binary_distribution/packages-xenial.txt
  setup/ubuntu/docker/bionic/Dockerfile
  setup/ubuntu/docker/entrypoint.sh
  setup/ubuntu/docker/xenial/Dockerfile
  setup/ubuntu/docker/xenial/Dockerfile.nvidia-cuda-8.0-devel-ubuntu16.04
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-xenial.txt
  tools/lint/test/util_test.py
Labels: priority: high, team: kitware, type: installation and distribution

#10163 Fix strip_prefix when installing install_prereqs
  setup/BUILD.bazel
Labels: priority: high, team: kitware, type: bug, type: installation and distribution

#10134 Extend public API to provide ability to assign roles.
  geometry/BUILD.bazel
  geometry/geometry_instance.h
  geometry/geometry_roles.h
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/internal_geometry.cc
  geometry/internal_geometry.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/scene_graph_inspector.h
  geometry/test/geometry_state_test.cc
  geometry/test/geometry_visualization_test.cc
Labels: priority: high, team: dynamics

#10104 pydrake: Simplify debugging instructions to use `gdbserver`
  bindings/pydrake/pydrake_pybind.h
Labels: configuration: python, priority: low

#10170 pydrake doc: Add blurb on naming conventions
  bindings/pydrake/pydrake_pybind.h
Labels: priority: low

#10173 geometry/dev: Avoid exhausting RenderLabel resources
  examples/manipulation_station/test/manipulation_station_test.cc
  geometry/dev/geometry_state.cc
Labels: priority: high

#10160 multibody: Move multibody_tree/multibody_plant to plant
  bindings/pydrake/multibody/multibody_tree_py.cc
  multibody/multibody_tree/implicit_stribeck/BUILD.bazel
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/plant/BUILD.bazel
  multibody/plant/contact_info.cc
  multibody/plant/contact_info.h
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/contact_results_to_lcm.h
  multibody/plant/coulomb_friction.cc
  multibody/plant/coulomb_friction.h
  multibody/plant/implicit_stribeck_solver.cc
  multibody/plant/implicit_stribeck_solver.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/box.sdf
  multibody/plant/test/box_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/coulomb_friction_test.cc
  multibody/plant/test/implicit_stribeck_solver_test.cc
  multibody/plant/test/implicit_stribeck_solver_test_util.h
  multibody/plant/test/inclined_plane_test.cc
  multibody/plant/test/joint_limits_test.cc
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/split_pendulum.sdf
  multibody/plant/test/spring_mass_system_test.cc
Labels: priority: medium, status: do not merge

#10166 multibody/parsing: Move helpers to detail namespace
  attic/multibody/parsers/sdf_parser.cc
  attic/multibody/parsers/urdf_parser.cc
  multibody/parsing/package_map.cc
  multibody/parsing/parser.cc
  multibody/parsing/parser_common.h
  multibody/parsing/parser_path_utils.cc
  multibody/parsing/parser_path_utils.h
  multibody/parsing/scene_graph_parser_detail.cc
  multibody/parsing/scene_graph_parser_detail.h
  multibody/parsing/sdf_parser.cc
  multibody/parsing/sdf_parser.h
  multibody/parsing/sdf_parser_common.cc
  multibody/parsing/sdf_parser_common.h
  multibody/parsing/test/acrobot_parser_test.cc
  multibody/parsing/test/common_parser_test.cc
  multibody/parsing/test/parser_path_utils_test.cc
  multibody/parsing/test/scene_graph_parser_detail_test.cc
  multibody/parsing/test/sdf_parser_test.cc
  multibody/parsing/test/test_loaders.cc
  multibody/parsing/test/test_loaders.h
  multibody/parsing/test/tinyxml_util_test.cc
  multibody/parsing/test/urdf_geometry_test.cc
  multibody/parsing/test/urdf_parser_test.cc
  multibody/parsing/tinyxml_util.cc
  multibody/parsing/tinyxml_util.h
  multibody/parsing/urdf_geometry.cc
  multibody/parsing/urdf_geometry.h
  multibody/parsing/urdf_parser.cc
  multibody/parsing/urdf_parser.h
Labels: priority: low, status: do not merge

#10168 call_python: Add documentation example
  common/proto/call_python_client.py
  common/proto/test/call_python_server_test.cc
  common/proto/test/call_python_test.py
Labels: priority: low

#10172 bazelrc: Prevent LCM messages from leaking out of tests
  automotive/test/steering_command_driver_test.py
  systems/lcm/test/lcm_driven_loop_test.cc
  tools/bazel.rc
Labels: priority: low

#10183 Add support for CMAKE_COLOR_MAKEFILE in CMake build
  CMakeLists.txt
Labels: team: kitware

#10187 multibody/parsing: Rename files for detail namespace
  attic/multibody/parsers/BUILD.bazel
  attic/multibody/parsers/sdf_parser.cc
  attic/multibody/parsers/urdf_parser.cc
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_ignition.cc
  multibody/parsing/detail_ignition.h
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/detail_path_utils.h
  multibody/parsing/detail_scene_graph.cc
  multibody/parsing/detail_scene_graph.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_sdf_parser.h
  multibody/parsing/detail_tinyxml.cc
  multibody/parsing/detail_tinyxml.h
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/parser.cc
  multibody/parsing/sdf_parser.h
  multibody/parsing/test/common_parser_test.cc
  multibody/parsing/test/detail_path_utils_test.cc
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_tinyxml_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/test_loaders.cc
  multibody/parsing/urdf_parser.h
Labels: priority: low, status: do not merge

#10165 Modify multibody code to use geometry-role-based interface
  examples/multibody/bouncing_ball/make_bouncing_ball_plant.cc
  examples/multibody/cylinder_with_multicontact/make_cylinder_plant.cc
  examples/simple_gripper/simple_gripper.cc
  geometry/dev/geometry_state.cc
  multibody/benchmarks/inclined_plane/make_inclined_plane_plant.cc
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_scene_graph.cc
  multibody/parsing/detail_scene_graph.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: high

#10191 cupboard: Make quotes consistent, remove unicode quote
  examples/manipulation_station/models/cupboard.sdf
Labels: priority: low

#10103 install, cmake: Enable not stripping symbols for debug
  CMakeLists.txt
  doc/python_bindings.rst
  tools/install/BUILD.bazel
  tools/install/dummy/BUILD.bazel
  tools/install/dummy/README.md
  tools/install/dummy/dummy.cc
  tools/install/dummy/dummy.h
  tools/install/dummy/dummy.py
  tools/install/install.py.in
  tools/install/libdrake/build_components_refresh.py
  tools/install/test/install_meta_test.py
Labels: configuration: cmake, configuration: python, priority: low

#10192 solvers: Use C++ storage idioms in SnoptSolver
  solvers/snopt_solver.cc
Labels: priority: low, status: do not merge

#10206 Useful API to compute frame kinematics
  multibody/plant/BUILD.bazel
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/body.h
  multibody/tree/frame.h
Labels: team: dynamics, type: feature request

#10217 multibody: Move test_utilities package up a level
  multibody/benchmarks/kuka_iiwa_robot/BUILD.bazel
  multibody/benchmarks/kuka_iiwa_robot/MG/BUILD.bazel
  multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h
  multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h
  multibody/test_utilities/BUILD.bazel
  multibody/test_utilities/spatial_kinematics.h
Labels: priority: medium

#10198 tools: Run build_components_refresh
  tools/install/libdrake/build_components.bzl
Labels: priority: low

#10222 attic: Move RBT rgbd_camera,rgbd_renderer to attic
  attic/manipulation/sensors/BUILD.bazel
  attic/systems/sensors/BUILD.bazel
  attic/systems/sensors/depth_shaders.h
  attic/systems/sensors/rgbd_camera.cc
  attic/systems/sensors/rgbd_camera.h
  attic/systems/sensors/rgbd_camera_publish_lcm_example.cc
  attic/systems/sensors/rgbd_renderer.cc
  attic/systems/sensors/rgbd_renderer.h
  attic/systems/sensors/rgbd_renderer_ospray.cc
  attic/systems/sensors/rgbd_renderer_ospray.h
  attic/systems/sensors/rgbd_renderer_vtk.cc
  attic/systems/sensors/rgbd_renderer_vtk.h
  attic/systems/sensors/test/rgbd_camera_test.cc
  attic/systems/sensors/test/rgbd_renderer_ospray_test.cc
  attic/systems/sensors/test/rgbd_renderer_test_util.h
  attic/systems/sensors/test/rgbd_renderer_vtk_test.cc
  systems/sensors/BUILD.bazel
Labels: priority: low, status: curate commits before merging, status: do not merge

#10208 MathematicalProgram can add new sdsos or dsos polynomials
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
  solvers/test/scaled_diagonally_dominant_matrix_test.cc
  solvers/test/sos_constraint_test.cc
Labels: team: manipulation

#10237 attic: Move RBT inverse_dynamics test_utilities to attic
  attic/systems/controllers/BUILD.bazel
  attic/systems/controllers/test/rbt_compute_torque.h
  attic/systems/controllers/test/rbt_inverse_dynamics_controller_test.cc
  attic/systems/controllers/test/rbt_inverse_dynamics_test.cc
  systems/controllers/test_utilities/BUILD.bazel
  systems/controllers/test_utilities/compute_torque.h
Labels: priority: low, status: do not merge

#10261 Copy R_AbarA and R_BbarB in multibody::OrientationConstraint ctor.
  multibody/inverse_kinematics/orientation_constraint.h
  multibody/inverse_kinematics/test/orientation_constraint_test.cc
Labels: priority: high, team: manipulation, type: bug

#10219 Implements MakeActuationMatrix()
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: team: dynamics, type: feature request

#10262 Do not compile ospray binaries with -ffast-math enabled
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/vtk/ospray_no_fast_math.patch
  tools/workspace/vtk/repository.bzl
Labels: team: kitware

#10268 Restrict cone_half_angle to [0, pi/2] in GazeTargetConstraint ctor.
  multibody/inverse_kinematics/gaze_target_constraint.cc
  multibody/inverse_kinematics/gaze_target_constraint.h
  multibody/inverse_kinematics/test/gaze_target_constraint_test.cc
Labels: priority: high, team: manipulation, type: bug

#10102 discrete_derivative: Make implementation explanation more general
  systems/primitives/discrete_derivative.h
Labels: priority: low, type: documentation

#10215 API to apply body forces
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
  multibody/plant/BUILD.bazel
  multibody/plant/test/external_forces_test.cc
  multibody/tree/body.h
  multibody/tree/multibody_forces.cc
  multibody/tree/multibody_forces.h
Labels: team: dynamics, type: feature request

#10279 Split out denormalized-number test and prevent valgrind from running on it
  systems/analysis/BUILD.bazel
  systems/analysis/test/simulator_denorm_test.cc
  systems/analysis/test/simulator_test.cc
Labels: priority: emergency, type: build cop

#10178 Fixes numerical precision issues in Maliput's OBJ generation
  automotive/maliput/utility/generate_obj.cc
  automotive/maliput/utility/test/data/HighlightedSegments.obj
  automotive/maliput/utility/test/generate_obj_test.cc
Labels: type: bug

#10285 pydrake/common: Enable clang-format everywhere
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/cpp_template_pybind.h
  bindings/pydrake/common/test/cpp_template_pybind_test.cc
  bindings/pydrake/common/type_pack.h
  bindings/pydrake/common/wrap_function.h
  bindings/pydrake/common/wrap_pybind.h
Labels: priority: low

#10250 perception, sensors: Improve support for 16U depth images
  bindings/pydrake/common/cpp_param_pybind.cc
  bindings/pydrake/perception_py.cc
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/test/perception_test.py
  perception/depth_image_to_point_cloud.cc
  perception/depth_image_to_point_cloud.h
  perception/test/depth_image_to_point_cloud_test.cc
  systems/sensors/BUILD.bazel
  systems/sensors/camera_info.h
  systems/sensors/image.h
  systems/sensors/pixel_types.cc
  systems/sensors/pixel_types.h
Labels: priority: high, status: do not merge

#10292 doc: Clarify the jenkins login step
  doc/jenkins.rst
Labels: priority: low

#10287 multibody: Remove implicit_stribeck namespace
  multibody/plant/implicit_stribeck_solver.cc
  multibody/plant/implicit_stribeck_solver.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/implicit_stribeck_solver_test.cc
  multibody/plant/test/implicit_stribeck_solver_test_util.h
Labels: priority: low

#10256 Nonlinear program example refactor
  solvers/BUILD.bazel
  solvers/gurobi_solver.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/linear_program_examples.cc
  solvers/test/linear_program_examples.h
  solvers/test/linear_system_solver_test.cc
  solvers/test/mathematical_program_test_util.cc
  solvers/test/mathematical_program_test_util.h
  solvers/test/mixed_integer_optimization_test.cc
  solvers/test/nonlinear_program_test.cc
  solvers/test/optimization_examples.cc
  solvers/test/optimization_examples.h
  solvers/test/quadratic_program_examples.cc
  solvers/test/quadratic_program_examples.h
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/semidefinite_program_examples.cc
Labels: priority: low
