Repository RobotLocomotion/drake, pull requests merged in 2018-05, with the labels that each got.

#8623 Untangle context from system, remove input_port_evaluator_interface
  perception/dev/feedforward_neural_network.cc
  systems/controllers/BUILD.bazel
  systems/framework/BUILD.bazel
  systems/framework/context.h
  systems/framework/diagram.h
  systems/framework/diagram_context.h
  systems/framework/framework_common.h
  systems/framework/input_port_descriptor.h
  systems/framework/input_port_evaluator_interface.cc
  systems/framework/input_port_evaluator_interface.h
  systems/framework/input_port_value.h
  systems/framework/leaf_context.h
  systems/framework/output_port.cc
  systems/framework/output_port.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/system_base_test.cc
  systems/framework/test/system_test.cc
  tools/install/libdrake/build_components.bzl
Labels: type: cleanup

#8749 Geometric Jacobian for the world fix
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/test/multibody_tree_test.cc
Labels: team: dynamics, type: bug

#8755 Introduce a tolerance in rotational symmetry test for PurePursuit
  automotive/test/pure_pursuit_test.cc
Labels: priority: high, type: build cop

#8744 SceneGraph SDF parsing
  multibody/multibody_tree/parsing/BUILD.bazel
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc
  multibody/multibody_tree/parsing/scene_graph_parser_detail.cc
  multibody/multibody_tree/parsing/scene_graph_parser_detail.h
  multibody/multibody_tree/parsing/sdf_parser_common.cc
  multibody/multibody_tree/parsing/sdf_parser_common.h
  multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc
Labels: team: dynamics, type: feature request

#8758 Implements an MBT prismatic joint
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/joints/prismatic_joint.cc
  multibody/multibody_tree/joints/prismatic_joint.h
  multibody/multibody_tree/joints/test/prismatic_joint_test.cc
  multibody/multibody_tree/prismatic_mobilizer.cc
  multibody/multibody_tree/prismatic_mobilizer.h
  multibody/multibody_tree/test/prismatic_mobilizer_test.cc
Labels: team: dynamics, type: feature request

#8766 split mixed_integer_rotation_constraint_test
  solvers/BUILD.bazel
  solvers/test/mixed_integer_rotation_constraint_corner_test.cc
  solvers/test/mixed_integer_rotation_constraint_test.cc
Labels: priority: emergency

#8775 MBP cart pole example
  examples/multibody/cart_pole/BUILD.bazel
  examples/multibody/cart_pole/box_2x1.obj
  examples/multibody/cart_pole/cart_pole.sdf
  examples/multibody/cart_pole/cart_pole_params.named_vector
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  examples/multibody/cart_pole/test/cart_pole_test.cc
  multibody/multibody_tree/joints/prismatic_joint.h
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc
Labels: team: dynamics, type: feature request

#8788 Update LCM
  tools/workspace/lcm/lcm.bzl
  tools/workspace/lcm/repository.bzl
Labels: configuration: bazel, team: kitware

#8813 Add //multibody/multibody_tree/parsing rollup library
  multibody/multibody_tree/parsing/BUILD.bazel
  tools/install/libdrake/build_components.bzl
Labels: priority: low

#8800 Updates MBP SDF parser to parse boxes for SG.
  examples/multibody/cart_pole/BUILD.bazel
  examples/multibody/cart_pole/box_2x1.obj
  examples/multibody/cart_pole/cart_pole.sdf
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  multibody/multibody_tree/parsing/scene_graph_parser_detail.cc
  multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc
Labels: priority: high, team: dynamics, type: feature request

#8789 Update to VTK 8.1 and latest Director and add packages for Bionic
  setup/mac/binary_distribution/Brewfile
  systems/sensors/rgbd_renderer_vtk.cc
  tools/workspace/drake_visualizer/drake_visualizer.py
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/vtk/repository.bzl
Labels: team: kitware

#8799 Parse joints actuation for MBP.
  examples/multibody/acrobot/BUILD.bazel
  examples/multibody/acrobot/run_lqr.cc
  examples/multibody/cart_pole/cart_pole.sdf
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  examples/multibody/cart_pole/test/cart_pole_test.cc
  multibody/benchmarks/acrobot/BUILD.bazel
  multibody/benchmarks/acrobot/acrobot.sdf
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc
  multibody/multibody_tree/parsing/test/multibody_plant_sdf_parser_test.cc
Labels: priority: high

#8824 Pass stdout back from execute_and_return
  tools/workspace/execute.bzl
Labels: priority: low

#8817 MBP weld joint
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/joints/test/weld_joint_test.cc
  multibody/multibody_tree/joints/weld_joint.cc
  multibody/multibody_tree/joints/weld_joint.h
  multibody/multibody_tree/mobilizer_impl.cc
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_plant/test/split_pendulum.sdf
  multibody/multibody_tree/multibody_tree_topology.h
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc
  multibody/multibody_tree/test/multibody_tree_test.cc
  multibody/multibody_tree/test/weld_mobilizer_test.cc
  multibody/multibody_tree/weld_mobilizer.cc
  multibody/multibody_tree/weld_mobilizer.h
Labels: priority: high, team: dynamics

#8830 Remove mathematical_program dependency on dReal
  solvers/BUILD.bazel
Labels: priority: low

#8823 Implements example on parameter derivatives
  examples/pendulum/BUILD.bazel
  examples/pendulum/pendulum_parameters_derivatives.cc
  examples/pendulum/pendulum_plant.h
Labels: team: dynamics

#8842 Updates sdformat repo
  tools/workspace/sdformat/repository.bzl
Labels: priority: high, team: dynamics, type: feature request

#8833 Tidy up some scalar conversion declarations and documentation.
  automotive/test/trajectory_agent_test.cc
  automotive/trajectory_agent.cc
  automotive/trajectory_agent.h
  examples/acrobot/acrobot_plant.cc
  examples/acrobot/acrobot_plant.h
  examples/bouncing_ball/bouncing_ball.cc
  examples/bouncing_ball/bouncing_ball.h
  examples/bouncing_ball/test/bouncing_ball_test.cc
  systems/framework/scalar_conversion_traits.h
Labels: priority: low

#8828 SDF parsing of meshes for visuals
  multibody/multibody_tree/parsing/scene_graph_parser_detail.cc
  multibody/multibody_tree/parsing/test/scene_graph_parser_detail_test.cc
Labels: priority: high, team: dynamics

#8849 Make the from_binary page slightly less scary
  doc/from_binary.rst
Labels: priority: low, type: documentation

#8838 Fix to joint poses in SDF parsing
  examples/multibody/cart_pole/cart_pole.sdf
  multibody/benchmarks/acrobot/acrobot.sdf
  multibody/multibody_tree/multibody_plant/test/split_pendulum.sdf
  multibody/multibody_tree/parsing/multibody_plant_sdf_parser.cc
Labels: priority: high, team: dynamics, type: bug

#8839 AgentTrajectory/TrajectoryAgent -> Trajectory/TrajectoryFollower
  automotive/BUILD.bazel
  automotive/test/trajectory_follower_test.cc
  automotive/test/trajectory_test.cc
  automotive/trajectory.cc
  automotive/trajectory.h
  automotive/trajectory_follower.cc
  automotive/trajectory_follower.h
Labels: status: curate commits before merging

#8857 Pull DiagramOutputPort into its own file and untangle from Diagram.
  systems/framework/BUILD.bazel
  systems/framework/diagram.cc
  systems/framework/diagram.h
  systems/framework/diagram_output_port.cc
  systems/framework/diagram_output_port.h
  systems/framework/leaf_output_port.h
  systems/framework/output_port.h
Labels: type: cleanup

#8865 Mark generated named vectors final
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/test/goal/sample.h
  tools/vector_gen/test/goal/sample_translator.h
Labels: priority: low

#8872 Defer SNOPT_PATH unpacking errors until build time
  tools/workspace/snopt/package-error.BUILD.bazel
  tools/workspace/snopt/repository.bzl
Labels: priority: low

#8867 Make Doxygen fast again
  doc/Doxyfile_CXX.in
  doc/doxygen.py
Labels: priority: low

#8880 Use shards for multilane_road_curve_accuracy_test.
  automotive/maliput/multilane/BUILD.bazel
Labels: priority: emergency

#8879 Implements time stepping in MBP
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  multibody/benchmarks/acrobot/acrobot.sdf
  multibody/multibody_tree/mobilizer_impl.h
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree_context.cc
  multibody/multibody_tree/multibody_tree_context.h
  multibody/multibody_tree/quaternion_floating_mobilizer.cc
  multibody/multibody_tree/space_xyz_mobilizer.cc
Labels: priority: high, team: dynamics, type: feature request

#8892 Add fmt dependency to drake_shared_library
  tools/install/libdrake/BUILD.bazel
Labels: priority: high

#8873 Simple gripper demo
  examples/simple_gripper/BUILD.bazel
  examples/simple_gripper/README.md
  examples/simple_gripper/simple_gripper.cc
  examples/simple_gripper/simple_gripper.sdf
  examples/simple_gripper/simple_mug.sdf
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
Labels: priority: high, team: dynamics, type: bug

#8888 MBP contact Jacobians
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
Labels: priority: high, team: dynamics

#8889 Add common/pointer_cast utilities
  common/BUILD.bazel
  common/pointer_cast.cc
  common/pointer_cast.h
  common/test/pointer_cast_test.cc
  systems/framework/BUILD.bazel
  systems/framework/context.h
  systems/framework/diagram.h
  systems/framework/diagram_continuous_state.h
  systems/framework/diagram_discrete_values.h
  systems/framework/event_collection.h
  systems/framework/leaf_system.h
  systems/framework/output_port_value.h
  systems/framework/system.h
  systems/framework/test/diagram_context_test.cc
  systems/framework/test_utilities/BUILD.bazel
  systems/framework/test_utilities/my_vector.h
Labels: priority: low

#8894 Add BasicVector initializer_list constructor
  systems/framework/basic_vector.h
  systems/framework/test/basic_vector_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/output_port_value_test.cc
  systems/framework/test/subvector_test.cc
  systems/sensors/accelerometer_output.cc
  systems/sensors/depth_sensor_output.cc
  systems/sensors/gyroscope_output.cc
Labels: priority: low

#8862 Begin to deprecate FixInputPort overload taking a unique_ptr
  bindings/pydrake/systems/framework_py_semantics.cc
  systems/framework/context.h
Labels: priority: low

#8868 Update OSQP build flags
  examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc
  manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14.xacro
  manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  solvers/test/optimization_examples.cc
  solvers/test/osqp_solver_test.cc
  tools/workspace/osqp/package.BUILD.bazel
Labels: priority: low

#8905 Prefer to use FixInputPort initializer_list overload
  systems/framework/system.h
  systems/framework/system_scalar_conversion_doxygen.h
  systems/framework/system_symbolic_inspector.cc
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/fixed_input_port_value_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_scalar_conversion_doxygen_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/vector_system_test.cc
Labels: priority: low
