Repository RobotLocomotion/drake, pull requests merged in 2018-10, with the labels that each got.

#9556 Fix "—batch mode is deprecated" warning emitted by FindBazel
  cmake/modules/FindBazel.cmake
Labels: configuration: cmake, team: kitware, type: cleanup

#9483 Update supported Clang to 6.0 and add support for Bionic and Mojave
  CMakeLists.txt
  doc/bazel.rst
  doc/developers.rst
  doc/faq.rst
  doc/from_source.rst
  doc/mac.rst
  doc/ubuntu.rst
  doc/ubuntu_xenial.rst
  setup/ubuntu/16.04/binary_distribution/packages.txt
  setup/ubuntu/16.04/source_distribution/packages.txt
  setup/ubuntu/18.04/binary_distribution/packages.txt
  setup/ubuntu/18.04/source_distribution/install_prereqs.sh
  setup/ubuntu/18.04/source_distribution/packages.txt
  tools/dynamic_analysis/bazel.rc
  tools/lint/clang_format.py
  tools/workspace/cc/repository.bzl
  tools/workspace/expat/repository.bzl
  tools/workspace/os.bzl
  tools/workspace/pybind11/run_mkdoc_with_python3.py
  tools/workspace/vtk/repository.bzl
  tools/workspace/zlib/repository.bzl
Labels: team: kitware

#9563 Add apt-get remove lldb-4.0 to install_prereqs to fix conflict
  setup/ubuntu/16.04/source_distribution/install_prereqs.sh
Labels: team: kitware

#9562 Fix typo caught by ubsan
  multibody/multibody_tree/test/frames_test.cc
Labels: type: build cop

#9542 pybind doc: Simplify dependency for doc generation; test `mkdoc.py`
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/documentation_pybind_test.cc
  bindings/pydrake/test/documentation_pybind_test.py
  examples/allegro_hand/BUILD.bazel
  lcmtypes/BUILD.bazel
  multibody/multibody_tree/parsing/BUILD.bazel
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/install/libdrake/BUILD.bazel
  tools/skylark/pybind.bzl
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pybind11/test/sample_header.h
  tools/workspace/pybind11/test/sample_header_documentation.expected.h
  tools/workspace/pybind11/test/sample_header_documentation_cc_test.cc
  tools/workspace/pybind11/test/sample_header_documentation_py_test.py
Labels: configuration: python, priority: high

#9565 multibody_tree: Restore `CreateDefaultContext`
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/test/multibody_tree_test.cc
Labels: priority: emergency

#9550 Allow mkdoc.py to be run from drake as a bazel external
  tools/workspace/pybind11/run_mkdoc_with_python3.py
Labels: priority: high

#9576 buildifier: Prefer our own mirror
  tools/workspace/mirrors.bzl
Labels: priority: high

#9571 Add documentation to pydrake.multibody.* modules
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/benchmarks_py.cc
  bindings/pydrake/multibody/collision_py.cc
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/joints_py.cc
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/parsers_py.cc
  bindings/pydrake/multibody/rigid_body_plant_py.cc
  bindings/pydrake/multibody/rigid_body_py.cc
  bindings/pydrake/multibody/rigid_body_tree_py.cc
  bindings/pydrake/multibody/shapes_py.cc
  bindings/pydrake/util/BUILD.bazel
  bindings/pydrake/util/type_safe_index_pybind.h
Labels: configuration: python, priority: high, type: documentation

#9593 Partial cleanup of pure Python documentation to match Google Style Guide
  bindings/pydrake/all.py
  bindings/pydrake/examples/__init__.py
  bindings/pydrake/examples/multibody/__init__.py
  bindings/pydrake/examples/multibody/cart_pole_passive_simulation.py
  bindings/pydrake/forwarddiff.py
  bindings/pydrake/systems/drawing.py
  bindings/pydrake/systems/lcm.py
  bindings/pydrake/systems/scalar_conversion.py
  bindings/pydrake/util/compatibility.py
  bindings/pydrake/util/containers.py
  bindings/pydrake/util/cpp_const.py
  bindings/pydrake/util/cpp_param.py
  bindings/pydrake/util/cpp_template.py
  bindings/pydrake/util/deprecation.py
Labels: configuration: python, team: kitware

#9595 More cleanup of pure Python documentation
  bindings/pydrake/all.py
  bindings/pydrake/systems/scalar_conversion.py
  bindings/pydrake/util/cpp_template.py
Labels: configuration: python, team: kitware, type: documentation

#9606 pydrake doc: Use `constexpr auto&` for nesting aliases
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/examples/acrobot_py.cc
  bindings/pydrake/examples/compass_gait_py.cc
  bindings/pydrake/examples/pendulum_py.cc
  bindings/pydrake/examples/rimless_wheel_py.cc
  bindings/pydrake/examples/van_der_pol_py.cc
  bindings/pydrake/maliput/api_py.cc
  bindings/pydrake/maliput/dragway_py.cc
  bindings/pydrake/manipulation/planner_py.cc
  bindings/pydrake/multibody/benchmarks_py.cc
  bindings/pydrake/multibody/collision_py.cc
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/joints_py.cc
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/parsers_py.cc
  bindings/pydrake/multibody/rigid_body_plant_py.cc
  bindings/pydrake/multibody/rigid_body_py.cc
  bindings/pydrake/multibody/rigid_body_tree_py.cc
  bindings/pydrake/multibody/shapes_py.cc
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/solvers/gurobi_py.cc
  bindings/pydrake/solvers/ik_py.cc
  bindings/pydrake/solvers/ipopt_py.cc
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/mosek_py.cc
  bindings/pydrake/solvers/osqp_py.cc
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/rendering_py.cc
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/trajectory_optimization_py.cc
Labels: priority: low

#9592 Adding bindings for several MultibodyTree getters
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
Labels: status: curate commits before merging

#9597 Method to compute Jacobian bias
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/test/multibody_tree_test.cc
Labels: priority: high, team: dynamics, type: feature request

#9596 Adds initial version of the "manipulation station" example.
  bindings/pydrake/geometry_py.cc
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/README.md
  examples/manipulation_station/proof_of_life.cc
  examples/manipulation_station/station_simulation.cc
  examples/manipulation_station/station_simulation.h
  examples/manipulation_station/test/station_simulation_test.cc
  geometry/geometry_visualization.cc
  geometry/geometry_visualization.h
  systems/controllers/inverse_dynamics_controller.cc
Labels: team: manipulation

#9631 pydrake cpp_template: Ensure `DefineTemplateClassWithDefault` is backwards-compatible
  bindings/pydrake/util/cpp_template_pybind.h
Labels: priority: high

#9627 Prepare systems/sensors for movement
  systems/sensors/color_palette.h
  systems/sensors/rgbd_renderer.cc
  systems/sensors/rgbd_renderer.h
  systems/sensors/rgbd_renderer_ospray.cc
  systems/sensors/rgbd_renderer_vtk.cc
Labels: priority: high, team: dynamics

#9455 Implements methods to compute selector matrices
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
Labels: priority: backlog, status: curate commits before merging, team: dynamics, type: feature request

#9638 framework: Improve error for missing abstract input model_value
  systems/framework/leaf_system.h
  systems/framework/test/leaf_system_test.cc
Labels: priority: medium

#9652 Render __init__ docstrings in pydrake Sphinx documentation
  bindings/pydrake/doc/conf.py
Labels: configuration: python, team: kitware, type: documentation

#9642 Method to compute bias for frame geometric Jacobians
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/test/multibody_tree_test.cc
Labels: priority: high, team: dynamics, type: feature request

#9639 Updates Allegro hand code to use MBT selector matrices.
  examples/allegro_hand/allegro_common.cc
  examples/allegro_hand/allegro_common.h
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
Labels: team: dynamics

#9637 vector_gen: Add fluent setters (aka "with"ers)
  systems/framework/BUILD.bazel
  systems/framework/basic_vector.h
  systems/framework/test/basic_vector_test.cc
  systems/framework/test_utilities/my_vector.h
  systems/lcm/BUILD.bazel
  tools/vector_gen/BUILD.bazel
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/test/goal/lcmt_sample_t.lcm
  tools/vector_gen/test/goal/sample.cc
  tools/vector_gen/test/goal/sample.h
  tools/vector_gen/test/goal/sample_translator.cc
  tools/vector_gen/test/goal/sample_translator.h
  tools/vector_gen/test/lcm_vector_gen_test.sh
  tools/vector_gen/test/sample_test.cc
Labels: priority: medium

#9667 bind ConnectLcmScope
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/lcm_test.py
Labels: priority: low

#9672 geometry/dev: Work around CI errors
  geometry/dev/BUILD.bazel
  geometry/dev/render/render_engine_vtk.h
Labels: priority: emergency

#9671 Add required abstract geomery input model values
  automotive/idm_controller.cc
  automotive/mobil_planner.cc
  examples/scene_graph/BUILD.bazel
  examples/scene_graph/bouncing_ball_plant.cc
  examples/scene_graph/bouncing_ball_run_dynamics.cc
  examples/scene_graph/dev/BUILD.bazel
  examples/scene_graph/dev/bouncing_ball_plant.cc
  examples/scene_graph/dev/bouncing_ball_run_dynamics.cc
  examples/scene_graph/dev/solar_system_run_dynamics.cc
  examples/scene_graph/solar_system_run_dynamics.cc
  geometry/dev/query_object.h
  geometry/dev/scene_graph.cc
  geometry/frame_kinematics_vector.cc
  geometry/frame_kinematics_vector.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/frame_kinematics_vector_test.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  systems/rendering/pose_aggregator.cc
  systems/rendering/pose_bundle.h
  systems/rendering/pose_bundle_to_draw_message.cc
  systems/sensors/dev/rgbd_camera.cc
  systems/sensors/optitrack_sender.cc
Labels: priority: low

#9670 Add required abstract input model values
  automotive/pure_pursuit_controller.cc
  examples/acrobot/BUILD.bazel
  examples/acrobot/acrobot_lcm.cc
  examples/acrobot/run_lqr.cc
  examples/acrobot/run_lqr_w_estimator.cc
  examples/acrobot/run_passive.cc
  examples/acrobot/run_plant_w_lcm.cc
  examples/acrobot/run_swing_up.cc
  examples/acrobot/spong_controller_w_lcm.cc
  examples/allegro_hand/allegro_lcm.cc
  examples/humanoid_controller/humanoid_plan_eval_system.cc
  examples/humanoid_controller/humanoid_status_translator_system.cc
  examples/kinova_jaco_arm/jaco_lcm.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/state_machine_system.cc
  examples/kuka_iiwa_arm/iiwa_lcm.cc
  examples/valkyrie/robot_command_to_desired_effort_converter.cc
  examples/valkyrie/robot_state_decoder.cc
  examples/valkyrie/robot_state_encoder.cc
  examples/valkyrie/valkyrie_pd_ff_controller.cc
  manipulation/perception/optitrack_pose_extractor.cc
  manipulation/perception/pose_smoother.cc
  manipulation/planner/robot_plan_interpolator.cc
  manipulation/schunk_wsg/schunk_wsg_lcm.cc
  manipulation/util/frame_pose_tracker.cc
  perception/depth_image_to_point_cloud.cc
  perception/point_cloud.h
  perception/rigid_body_point_cloud_filter.cc
  perception/transform_point_cloud.cc
  systems/controllers/plan_eval/plan_eval_base_system.cc
  systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics_system.cc
  systems/controllers/qp_inverse_dynamics/qp_output_translator_system.cc
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/test/lcm_driven_loop_test.cc
  systems/lcm/test/lcm_log_playback_test.cc
Labels: priority: low

#9674 geometry/dev: Work around CI errors
  examples/scene_graph/dev/BUILD.bazel
Labels: priority: emergency

#9663 Convex in examples/scene_graph/solar_system. Fixed ProximityEngine to copy fcl::Convex.
  examples/scene_graph/cuboctahedron.obj
  examples/scene_graph/solar_system.cc
  examples/scene_graph/solar_system.h
  geometry/proximity_engine.cc
  geometry/shape_specification.h
  geometry/test/proximity_engine_test.cc
Labels: status: curate commits before merging

#9678 More documentation and markup fixes
  attic/multibody/rigid_body_plant/contact_detail.h
  attic/multibody/rigid_body_plant/contact_force.h
  attic/multibody/rigid_body_plant/contact_info.h
  attic/multibody/rigid_body_plant/contact_resultant_force_calculator.h
  attic/multibody/rigid_body_plant/contact_results.h
  attic/multibody/rigid_body_plant/point_contact_detail.h
  attic/multibody/rigid_body_plant/rigid_body_plant_bridge.h
  attic/multibody/rigid_body_tree.h
  automotive/maliput/dragway/lane.h
  common/trajectories/piecewise_polynomial.h
  common/trajectories/piecewise_quaternion.h
  examples/compass_gait/compass_gait.h
  examples/rod2d/rod2d.h
  examples/scene_graph/dev/solar_system.h
  examples/scene_graph/solar_system.h
  geometry/dev/geometry_context.h
  geometry/dev/geometry_state.h
  geometry/dev/proximity_engine.h
  geometry/dev/query_object.h
  geometry/dev/scene_graph.h
  geometry/frame_kinematics_vector.h
  geometry/geometry_context.h
  geometry/geometry_state.h
  geometry/proximity_engine.h
  geometry/query_object.h
  geometry/scene_graph.h
  geometry/shape_specification.h
  manipulation/scene_generation/simulate_plant_to_rest.h
  manipulation/util/moving_average_filter.h
  manipulation/util/robot_state_msg_translator.h
  manipulation/util/trajectory_utils.h
  math/roll_pitch_yaw.h
  math/rotation_matrix.h
  multibody/multibody_tree/body_node.h
  multibody/multibody_tree/multibody_plant/contact_info.h
  multibody/multibody_tree/multibody_plant/contact_results.h
  multibody/multibody_tree/multibody_plant/contact_results_to_lcm.h
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/spatial_inertia.h
  solvers/branch_and_bound.h
  solvers/cost.h
  solvers/mathematical_program.h
  solvers/mixed_integer_rotation_constraint.h
  solvers/system_identification.h
  systems/analysis/implicit_euler_integrator.h
  systems/analysis/integrator_base.h
  systems/analysis/runge_kutta3_integrator.h
  systems/controllers/dynamic_programming.h
  systems/controllers/inverse_dynamics.h
  systems/controllers/inverse_dynamics_controller.h
  systems/controllers/pid_controller.h
  systems/framework/diagram_output_port.h
  systems/framework/leaf_output_port.h
  systems/framework/output_port.h
  systems/primitives/linear_system.h
  systems/stochastic_systems.h
  systems/trajectory_optimization/generalized_constraint_force_evaluator.h
Labels: team: kitware, type: documentation

#9686 memcheck also falls victim to nvidia driver issues
  examples/scene_graph/dev/BUILD.bazel
Labels: priority: emergency

#9685 Miscellaneous documentation fixes
  attic/multibody/collision/bullet_model.h
  attic/multibody/rigid_body.h
  attic/multibody/rigid_body_plant/compliant_material.h
  attic/multibody/rigid_body_plant/contact_force.h
  attic/multibody/rigid_body_plant/rigid_body_plant_bridge.h
  common/copyable_unique_ptr.h
  common/symbolic_formula_cell.h
  common/symbolic_rational_function.h
  common/type_safe_index.h
  examples/kuka_iiwa_arm/pick_and_place/action.h
  examples/rod2d/rod2d.h
  examples/scene_graph/solar_system.h
  geometry/dev/geometry_roles.h
  geometry/dev/geometry_visualization.h
  geometry/dev/render/render_label.h
  geometry/dev/scene_graph.h
  geometry/dev/scene_graph_inspector.h
  geometry/geometry_frame.h
  geometry/geometry_instance.h
  geometry/geometry_set.h
  geometry/geometry_visualization.h
  geometry/scene_graph.h
  geometry/scene_graph_inspector.h
  geometry/shape_specification.h
  manipulation/schunk_wsg/schunk_wsg_plain_controller.h
  manipulation/sensors/xtion.h
  multibody/benchmarks/acrobot/acrobot.h
  multibody/constraint/constraint_doxygen.h
  multibody/multibody_tree/body_node.h
  multibody/multibody_tree/multibody_plant/contact_info.h
  multibody/multibody_tree/multibody_plant/contact_results_to_lcm.h
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/multibody_tree_topology.h
  multibody/multibody_tree/rotational_inertia.h
  multibody/multibody_tree/spatial_inertia.h
  perception/point_cloud.h
  solvers/mathematical_program.h
  solvers/mixed_integer_rotation_constraint.h
  systems/analysis/integrator_base.h
  systems/framework/cache_doxygen.h
  systems/framework/context.h
  systems/framework/system.h
  systems/lcm/connect_lcm_scope.h
  systems/sensors/camera_info.h
  systems/sensors/depth_sensor.h
Labels: team: kitware, type: documentation

#9617 Update miscellaneous components for Python3 compatibility
  automotive/automotive_demo.py
  automotive/steering_command_driver.py
  bindings/pydrake/doc/serve_sphinx.py
  common/proto/call_python_client.py
  common/test/drake_cc_googletest_main_test.py
  common/test/resource_tool_test.py
  doc/doxygen.py
  doc/serve_sphinx.py
  lcmtypes/test/drake-lcm-spy_install_test.py
  manipulation/util/meshlab_to_sdf.py
  multibody/rigid_body_plant/visualization/contact_viz.py
  tools/clion/BUILD.bazel
  tools/clion/bazel_wrapper
  tools/clion/test/bazel_wrapper_test.py
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/build_components_refresh.py
  tools/vector_gen/lcm_vector_gen.py
  tools/workspace/lcm/package.BUILD.bazel
Labels: priority: low

#9687 Revert a portion of "Add required abstract geomery input model values"
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
Labels: priority: emergency

#9664 Capability to set the pose of a free body in a local reference frame.
  examples/simple_gripper/BUILD.bazel
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
  multibody/multibody_tree/multibody_plant/multibody_plant.h
  multibody/multibody_tree/multibody_plant/test/multibody_plant_test.cc
  multibody/multibody_tree/multibody_tree_topology.h
  multibody/multibody_tree/test/multibody_tree_creation_test.cc
Labels: priority: medium, team: dynamics, type: feature request

#9695 Disable tsan for 'spong_controller_w_lcm_test'
  examples/acrobot/BUILD.bazel
Labels: type: build cop

#9696 Transpose documentation in rigid_body_constraint
  attic/multibody/rigid_body_constraint.h
Labels: team: kitware, type: documentation

#9701 Miscellaneous documentation fixes
  attic/multibody/kinematics_cache.h
  attic/multibody/rigid_body_plant/kinematics_results.h
  automotive/curve2.h
  automotive/maliput/api/lane.h
  automotive/maliput/multilane/cubic_polynomial.h
  common/drake_bool_deprecated.h
  common/proto/call_matlab.h
  common/reset_after_move.h
  common/reset_on_copy.h
  common/symbolic_variables.h
  common/trig_poly.h
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_system.h
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_plant.h
  geometry/dev/query_object.h
  geometry/frame_kinematics_vector.h
  geometry/query_object.h
  manipulation/scene_generation/random_clutter_generator.h
  math/rigid_transform.h
  multibody/inverse_kinematics/inverse_kinematics.h
  solvers/indeterminate.h
  solvers/mathematical_program.h
  solvers/non_convex_optimization_util.h
  systems/analysis/integrator_base.h
  systems/controllers/linear_model_predictive_controller.h
  systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics_common.h
  systems/framework/event.h
  systems/framework/test_utilities/my_vector.h
  systems/sensors/depth_sensor.h
  systems/sensors/depth_shaders.h
  systems/sensors/test/accelerometer_test/accelerometer_example_diagram.h
  systems/trajectory_optimization/direct_collocation.h
Labels: configuration: python, team: kitware

#9698 Add MultibodyPlant URDF parser
  examples/kuka_iiwa_arm/controlled_kuka/BUILD.bazel
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
  multibody/benchmarks/acrobot/acrobot.urdf
  multibody/multibody_tree/parsing/BUILD.bazel
  multibody/multibody_tree/parsing/multibody_plant_urdf_parser.cc
  multibody/multibody_tree/parsing/multibody_plant_urdf_parser.h
  multibody/multibody_tree/parsing/test/acrobot_parser_test.cc
  multibody/multibody_tree/parsing/test/common_parser_test.cc
  multibody/multibody_tree/parsing/test/links_with_visuals_and_collisions.urdf
  multibody/multibody_tree/parsing/test/multibody_plant_urdf_parser_test.cc
  multibody/multibody_tree/parsing/test/test_loaders.cc
  multibody/multibody_tree/parsing/test/test_loaders.h
Labels: priority: medium

#9533 Discrete derivative
  systems/primitives/BUILD.bazel
  systems/primitives/discrete_derivative.cc
  systems/primitives/discrete_derivative.h
  systems/primitives/test/discrete_derivative_test.cc
Labels: priority: high, team: dynamics

#9748 multibody: Use modern (rpy, xyz) -> isometry conversion
  attic/multibody/parsers/sdf_parser.cc
  attic/multibody/parsers/test/rbt_sdf_parser_test.cc
  multibody/multibody_tree/parsing/test/multibody_plant_sdf_parser_test.cc
Labels: priority: low

#9752 Increase test timeouts for frequently timed out tests
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/systems/BUILD.bazel
  examples/acrobot/BUILD.bazel
  tools/skylark/drake_py.bzl
Labels: priority: high

#9770 Partial revert of #9756, avoiding duplicate library warning for `lcm.so`
  bindings/pydrake/doc/pydrake.systems.lcm.rst
  bindings/pydrake/doc/refresh_doc_modules.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/lcm.py
  bindings/pydrake/systems/lcm_py.cc
Labels: priority: emergency

#9615 Clean up shebangs, Update lint to run under Python3
  bindings/pydrake/test/all_install_test.py
  bindings/pydrake/test/common_install_test.py
  common/test/cpplint_wrapper.py
  common/test/cpplint_wrapper_test.py
  common/test/resource_tool_installed_test.py
  doc/clion.rst
  doc/code_style_guide.rst
  examples/kuka_iiwa_arm/test/iiwa_wsg_simulation_installed_test.py
  examples/kuka_iiwa_arm/test/kuka_plan_runner_installed_test.py
  examples/kuka_iiwa_arm/test/kuka_simulation_installed_test.py
  lcmtypes/test/drake-lcm-spy_install_test.py
  systems/sensors/visualization/show_images.py
  tools/install/install_test.py
  tools/install/install_test_helper.py
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/test/snopt_visibility_install_test.py
  tools/lint/buildifier.py
  tools/lint/bzlcodestyle.py
  tools/lint/clang_format_includes.py
  tools/lint/drakelint.py
  tools/lint/formatter.py
  tools/lint/test/buildifier_test.py
  tools/workspace/cmake_configure_file.py
  tools/workspace/eigen/package-create-cps.py
  tools/workspace/fmt/package-create-cps.py
  tools/workspace/ignition_math/package-create-cps.py
  tools/workspace/ignition_rndf/package-create-cps.py
  tools/workspace/lcm/package-create-cps.py
  tools/workspace/lcm/test/lcm-gen_install_test.py
  tools/workspace/pybind11/package-create-cps.py
  tools/workspace/spdlog/package-create-cps.py
  tools/workspace/styleguide/repository.bzl
Labels: priority: medium

#9743 Add sugar constructors for RigidTransform, update with Sean's comments in previous PR.
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
Labels: priority: medium

#9760 Split the command receiver part of the WSG LCM from the trajectory generator
  manipulation/schunk_wsg/BUILD.bazel
  manipulation/schunk_wsg/schunk_wsg_controller.cc
  manipulation/schunk_wsg/schunk_wsg_lcm.cc
  manipulation/schunk_wsg/schunk_wsg_lcm.h
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator.h
  manipulation/schunk_wsg/test/schunk_wsg_controller_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_lcm_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_trajectory_generator_test.cc
Labels: priority: high

#9785 lint: Add missing lint coverage; fix problems
  automotive/test/box_car_vis_test.cc
  automotive/test/car_vis_applicator_test.cc
  automotive/test/prius_vis_test.cc
  examples/allegro_hand/BUILD.bazel
  examples/allegro_hand/allegro_lcm.cc
  examples/allegro_hand/allegro_lcm.h
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/allegro_hand/test/allegro_lcm_test.cc
  manipulation/scene_generation/BUILD.bazel
  manipulation/scene_generation/test/test_random_clutter_to_rest.cc
  solvers/BUILD.bazel
  systems/sensors/godot_renderer/dev/BUILD.bazel
  tools/dev/add_cpplint.py
Labels: priority: backlog

#9780 Minor cleanup
  math/rigid_transform.h
  multibody/benchmarks/acrobot/acrobot.cc
Labels: status: curate commits before merging

#9784 multibody/parsing: Remove test coverage TODO
  multibody/multibody_tree/parsing/parser_path_utils.cc
Labels: priority: backlog

#9793 geometry: Make the QueryObject constructor public
  examples/scene_graph/bouncing_ball_plant.cc
  examples/scene_graph/dev/bouncing_ball_plant.cc
  geometry/dev/query_object.h
  geometry/dev/scene_graph.cc
  geometry/dev/scene_graph.h
  geometry/query_object.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  multibody/multibody_tree/multibody_plant/multibody_plant.cc
Labels: priority: medium

#9795 doxygen: Fix breakage from #9615 (removal of executable bits)
  doc/doxygen.py
Labels: priority: emergency

#9736 Caches H_PB_W. Enables caching for simple_gripper.cc
  examples/simple_gripper/simple_gripper.cc
  multibody/multibody_tree/multibody_tree.cc
  multibody/multibody_tree/multibody_tree.h
  multibody/multibody_tree/multibody_tree_system.cc
  multibody/multibody_tree/multibody_tree_system.h
Labels: team: dynamics, type: feature request

#9769 lint: Enable build/pragma_once errors
  CPPLINT.cfg
  attic/multibody/parsers/package_map.h
  attic/multibody/parsers/parser_path_utils.h
  common/BUILD.bazel
  common/test/cpplint_wrapper_test.py
  multibody/benchmarks/kuka_iiwa_robot/MG/CPPLINT.cfg
  systems/framework/output_port_value.h
  tools/workspace/styleguide/package.BUILD.bazel
  tools/workspace/styleguide/repository.bzl
Labels: priority: low

#9799 attic: Remove bazel fowarding aliaes for multibody
  multibody/collision/BUILD.bazel
  multibody/collision/README.md
  multibody/joints/BUILD.bazel
  multibody/joints/README.md
  multibody/parsers/BUILD.bazel
  multibody/parsers/README.md
  multibody/rigid_body_plant/BUILD.bazel
  multibody/rigid_body_plant/README.md
  multibody/rigid_body_plant/warning.bzl
  multibody/shapes/BUILD.bazel
  multibody/shapes/README.md
  tools/bazel.rc
Labels: priority: low

#9676 framework: Diagnose bad FixInputPort values
  systems/framework/BUILD.bazel
  systems/framework/context_base.cc
  systems/framework/context_base.h
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/test/cache_entry_test.cc
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/fixed_input_port_value_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_base_test.cc
Labels: priority: medium

#9763 clang: Add Werror=absolute-value checking
  tools/skylark/drake_cc.bzl
Labels: priority: low

#9807 framework: Work around gcc-7 bug
  systems/framework/system.h
Labels: priority: emergency

#9804 solvers: Rename snopt_solver_f2c to make room for others
  solvers/BUILD.bazel
  solvers/snopt_solver_f2c.cc
Labels: priority: high

#9800 multibody/parsing: Remove entire package of dead code
  examples/double_pendulum/BUILD.bazel
  examples/double_pendulum/frame_cache.cc
  examples/double_pendulum/frame_cache.h
  examples/double_pendulum/sdf_helpers.cc
  examples/double_pendulum/test/frame_cache_test.cc
  multibody/parsing/BUILD.bazel
  multibody/parsing/sdf_joint.h
  multibody/parsing/sdf_link.h
  multibody/parsing/sdf_model.h
  multibody/parsing/sdf_parser.cc
  multibody/parsing/sdf_parser.h
  multibody/parsing/sdf_spec.h
  multibody/parsing/test/models/LICENSE
  multibody/parsing/test/models/double_pendulum.sdf
  multibody/parsing/test/sdf_parser_test.cc
  tools/install/libdrake/build_components.bzl
Labels: priority: low

#9755 Add Doxygen 1.8.13 configuration options and reduce size of generated docs
  doc/BUILD.bazel
  doc/Doxyfile_CXX.in
  doc/DoxygenLayout.xml
  doc/conf.py
  doc/doxygen.py
  doc/footer.html
  doc/images/favicon.ico
Labels: team: kitware, type: documentation

#9816 geometry: Add a cube constructor for Box
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/test/shape_specification_test.cc
Labels: priority: low

#9653 drake_visualizer: Enable --use_builtin_scripts
  multibody/rigid_body_plant/visualization/contact_viz.py
  multibody/rigid_body_plant/visualization/show_frames.py
  multibody/rigid_body_plant/visualization/show_time.py
  systems/sensors/visualization/show_images.py
  tools/BUILD.bazel
  tools/__init__.py
  tools/workspace/BUILD.bazel
  tools/workspace/__init__.py
  tools/workspace/drake_visualizer/BUILD.bazel
  tools/workspace/drake_visualizer/__init__.py
  tools/workspace/drake_visualizer/drake_visualizer.py
  tools/workspace/drake_visualizer/plugin/BUILD.bazel
  tools/workspace/drake_visualizer/plugin/README.md
  tools/workspace/drake_visualizer/plugin/__init__.py
  tools/workspace/drake_visualizer/plugin/show_contact.py
  tools/workspace/drake_visualizer/plugin/show_frame.py
  tools/workspace/drake_visualizer/plugin/show_image.py
  tools/workspace/drake_visualizer/plugin/show_time.py
  tools/workspace/drake_visualizer/plugin/use_builtin_scripts.py
Labels: priority: medium

#9792 framework: Deprecate abstract inputs without model values
  bindings/pydrake/systems/framework_py_systems.cc
  systems/framework/diagram.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_symbolic_inspector_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/vector_system_test.cc
Labels: priority: medium

#9786 Mathematical program result
  solvers/BUILD.bazel
  solvers/mathematical_program_result.cc
  solvers/mathematical_program_result.h
  solvers/mosek_solver.cc
  solvers/mosek_solver.h
  solvers/no_mosek.cc
  solvers/test/mathematical_program_result_test.cc
  solvers/test/mosek_solver_test.cc
Labels: priority: high

#9789 adds iiwa7 models.
  manipulation/models/iiwa_description/LICENSE.TXT
  manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf
  manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf
  manipulation/models/iiwa_description/iiwa7/link_0.obj
  manipulation/models/iiwa_description/iiwa7/link_1.obj
  manipulation/models/iiwa_description/iiwa7/link_2.obj
  manipulation/models/iiwa_description/iiwa7/link_3.obj
  manipulation/models/iiwa_description/iiwa7/link_4.obj
  manipulation/models/iiwa_description/iiwa7/link_5.obj
  manipulation/models/iiwa_description/iiwa7/link_6.obj
  manipulation/models/iiwa_description/iiwa7/link_7.obj
Labels: status: curate commits before merging

#9831 Tidy up some install-related build rules
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/controlled_kuka/BUILD.bazel
  examples/kuka_iiwa_arm/dev/box_rotation/BUILD.bazel
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel
  examples/kuka_iiwa_arm/dev/pick_and_place/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_world/BUILD.bazel
  examples/kuka_iiwa_arm/pick_and_place/BUILD.bazel
  examples/manipulation_station/BUILD.bazel
  geometry/dev/render/shaders/BUILD.bazel
  manipulation/dev/BUILD.bazel
  manipulation/scene_generation/BUILD.bazel
  perception/estimators/dev/BUILD.bazel
  systems/estimators/dev/BUILD.bazel
  systems/sensors/godot_renderer/dev/BUILD.bazel
  tools/install/libdrake/BUILD.bazel
  tools/skylark/pybind.bzl
  tools/vector_gen/BUILD.bazel
Labels: priority: high

#9832 Resolves mosek valgrind suppression message
  tools/dynamic_analysis/valgrind.supp
Labels: priority: high

#9830 libdrake: Install code from dev folders
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/build_components_refresh.py
  tools/lint/install_lint.bzl
Labels: priority: high

#9838 libdrake: Don't install Drake's lcmtypes twice
  tools/install/libdrake/BUILD.bazel
  tools/skylark/drake_cc.bzl
Labels: priority: low

#9805 More improvements and fixes to mkdoc.py
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/workspace/pybind11/test/sample_header.h
  tools/workspace/pybind11/test/sample_header_documentation.expected.h
Labels: team: kitware, type: documentation

#9841 build: Remove drake.bzl forwarder
  examples/BUILD.bazel
  examples/acrobot/BUILD.bazel
  examples/allegro_hand/BUILD.bazel
  examples/allegro_hand/joint_control/BUILD.bazel
  examples/atlas/BUILD.bazel
  examples/bead_on_a_wire/BUILD.bazel
  examples/bouncing_ball/BUILD.bazel
  examples/compass_gait/BUILD.bazel
  examples/contact_model/BUILD.bazel
  examples/cubic_polynomial/BUILD.bazel
  examples/double_pendulum/BUILD.bazel
  examples/humanoid_controller/BUILD.bazel
  examples/humanoid_controller/dev/BUILD.bazel
  examples/kinova_jaco_arm/BUILD.bazel
  examples/multibody/acrobot/BUILD.bazel
  examples/multibody/bouncing_ball/BUILD.bazel
  examples/multibody/cart_pole/BUILD.bazel
  examples/multibody/cylinder_with_multicontact/BUILD.bazel
  examples/multibody/inclined_plane/BUILD.bazel
  examples/multibody/pendulum/BUILD.bazel
  examples/particles/BUILD.bazel
  examples/pendulum/BUILD.bazel
  examples/pr2/BUILD.bazel
  examples/qp_inverse_dynamics/BUILD.bazel
  examples/quadrotor/BUILD.bazel
  examples/rimless_wheel/BUILD.bazel
  examples/rod2d/BUILD.bazel
  examples/scene_graph/BUILD.bazel
  examples/scene_graph/dev/BUILD.bazel
  examples/schunk_wsg/BUILD.bazel
  examples/simple_gripper/BUILD.bazel
  examples/valkyrie/BUILD.bazel
  examples/van_der_pol/BUILD.bazel
  examples/zmp/BUILD.bazel
  manipulation/models/allegro_hand_description/BUILD.bazel
  manipulation/models/iiwa_description/BUILD.bazel
  manipulation/models/jaco_description/BUILD.bazel
  manipulation/models/wsg_50_description/BUILD.bazel
  multibody/benchmarks/chaotic_babyboot/MG/BUILD.bazel
  multibody/benchmarks/kuka_iiwa_robot/MG/BUILD.bazel
  multibody/multibody_tree/test_utilities/BUILD.bazel
  tools/drake.bzl
Labels: priority: backlog

#9849 Import legacy .bazelrc file for Bazel 0.19 and above
  .bazelrc
Labels: priority: high, team: kitware

#9850 Update supported Bazel / CMake versions on Mac
  doc/developers.rst
Labels: configuration: mac, team: kitware, type: documentation

#9839 libdrake: Document indirectly-installed components
  attic/multibody/BUILD.bazel
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/build_components_refresh.py
Labels: priority: low

#9851 Adds documentation to the current implementation of DiffIK.
  manipulation/planner/differential_inverse_kinematics.cc
  manipulation/planner/differential_inverse_kinematics.h
Labels: priority: medium, team: manipulation, type: cleanup

#9845 skylark: Prefer `@drake//tools/skylark` over `//tools/skylark`
  attic/multibody/BUILD.bazel
  attic/multibody/dev/BUILD.bazel
  bindings/BUILD.bazel
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/doc/BUILD.bazel
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/examples/multibody/BUILD.bazel
  bindings/pydrake/maliput/BUILD.bazel
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/third_party/BUILD.bazel
  bindings/pydrake/util/BUILD.bazel
  common/proto/BUILD.bazel
  examples/cubic_polynomial/BUILD.bazel
  examples/humanoid_controller/BUILD.bazel
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/manipulation_station/BUILD.bazel
  examples/qp_inverse_dynamics/BUILD.bazel
  lcm/BUILD.bazel
  lcmtypes/BUILD.bazel
  manipulation/dev/BUILD.bazel
  multibody/inverse_kinematics/BUILD.bazel
  solvers/BUILD.bazel
  systems/controllers/plan_eval/BUILD.bazel
  systems/controllers/qp_inverse_dynamics/BUILD.bazel
  systems/estimators/dev/BUILD.bazel
  tools/BUILD.bazel
  tools/install/BUILD.bazel
  tools/lint/bazel_lint.bzl
  tools/lint/cpplint.bzl
  tools/lint/install_lint.bzl
  tools/lint/library_lint.bzl
  tools/lint/python_lint.bzl
  tools/skylark/drake_proto.bzl
  tools/skylark/pybind.bzl
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/python/BUILD.bazel
Labels: priority: low

#9844 automotive: Remove unused models
  attic/multibody/test/rigid_body_tree/rigid_body_tree_clone_test.cc
  automotive/models/prius/prius_rear_wheel_drive.urdf
  automotive/models/prius/prius_with_lidar.sdf
Labels: priority: backlog

#9810 examples: Stop LCM thread before destroying its receivers
  examples/acrobot/BUILD.bazel
  examples/acrobot/run_plant_w_lcm.cc
  examples/acrobot/spong_controller_w_lcm.cc
  examples/acrobot/test/acrobot_lcm_msg_generator.cc
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/double_pendulum/BUILD.bazel
  examples/double_pendulum/double_pendulum_demo.cc
  examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/test/monolithic_pick_and_place_system_test.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_simulator.cc
  examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/particles/uniformly_accelerated_particle.cc
  examples/pr2/pr2_passive_simulation.cc
  examples/schunk_wsg/schunk_wsg_simulation.cc
  examples/valkyrie/valkyrie_simulation.cc
  lcm/drake_lcm.cc
Labels: priority: low

#9860 pydrake: Begin to enforce clang-format
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/automotive_py.cc
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/perception_py.cc
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/autodiffutils_test_util_py.cc
  bindings/pydrake/test/odr_test_module_py.cc
  bindings/pydrake/trajectories_py.cc
  tools/lint/BUILD.bazel
  tools/lint/clang_format_lint.py
  tools/lint/cpplint.bzl
  tools/lint/lint.bzl
Labels: priority: low

#9864 ubuntu: Upgrade to Bazel 0.18
  .bazelrc
  .gitignore
  CMakeLists.txt
  WORKSPACE
  doc/developers.rst
  setup/ubuntu/16.04/source_distribution/install_prereqs.sh
  setup/ubuntu/18.04/source_distribution/install_prereqs.sh
Labels: priority: high

#9872 manipulation_station: Ensure appropriate test tags are used
  examples/manipulation_station/BUILD.bazel
Labels: priority: high

#9884 pydrake/solvers: Enforce clang-format idempotence
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/gurobi_py.cc
  bindings/pydrake/solvers/ik_py.cc
  bindings/pydrake/solvers/ipopt_py.cc
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/mosek_py.cc
  bindings/pydrake/solvers/osqp_py.cc
Labels: priority: medium
