Repository RobotLocomotion/drake, pull requests merged in 2019-09, with the labels that each got.

#11978 Remove deprecated methods (2019-09-01)
  bindings/pydrake/examples/manipulation_station_py.cc
  examples/manipulation_station/manipulation_station.h
  geometry/geometry_visualization.cc
  geometry/geometry_visualization.h
  multibody/plant/multibody_plant.h
  solvers/BUILD.bazel
  solvers/solver_result.h
  systems/primitives/BUILD.bazel
  systems/primitives/piecewise_polynomial_affine_system.h
  systems/primitives/piecewise_polynomial_linear_system.h
Labels: priority: low, status: single reviewer ok

#12001 plant: Repair "Hydroelastic contact surface visualization" link error
  multibody/plant/contact_results.h
  multibody/plant/test/box_test.cc
Labels: priority: emergency, status: single reviewer ok

#11967 [geometry] Convert VolumeMesh to SurfaceMesh.
  geometry/proximity/BUILD.bazel
  geometry/proximity/make_box_mesh.h
  geometry/proximity/sorted_triplet.cc
  geometry/proximity/sorted_triplet.h
  geometry/proximity/test/make_box_mesh_test.cc
  geometry/proximity/test/sorted_triplet_test.cc
  geometry/proximity/test/volume_to_surface_mesh_test.cc
  geometry/proximity/volume_to_surface_mesh.h
Labels: status: squashing now

#12006 Add doc for pydrake.symbolic.Expression and pydrake.symbolic.Monomial
  bindings/pydrake/symbolic_py.cc
Labels: status: single reviewer ok

#11995 common: Promote find_runfiles to public
  common/find_resource.cc
  common/find_runfiles.cc
  common/find_runfiles.h
  common/find_runfiles_stub.cc
  common/test/find_runfiles_fail_test.cc
  common/test/find_runfiles_stub_test.cc
  common/test/find_runfiles_test.cc
Labels: priority: low

#11694 MathematicalProgram tutorial
  tutorials/BUILD.bazel
  tutorials/README.md
  tutorials/mathematical_program.ipynb
  tutorials/solver_parameters.ipynb
Labels: status: squashing now

#12004 Fix setup scripts for various Homebrew changes/removals
  doc/bazel.rst
  doc/developers.rst
  doc/getting_help.rst
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/requirements.txt
Labels: configuration: mac, configuration: python, priority: high, status: commits are properly curated, status: single reviewer ok, team: kitware, type: build cop

#12008 Deprecate Simulator::StepTo()
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/analysis_py.cc
  examples/atlas/atlas_run_dynamics.cc
  examples/multibody/inclined_plane_with_body/inclined_plane_with_body.cc
  systems/analysis/simulator.h
Labels: priority: low

#12015 Fix include statements in drake_throw_test.cc
  common/test/drake_throw_test.cc
Labels: status: single reviewer ok

#12017 Add python binding for MathematicalProgram::AddIndeterminates() and AddDecisionVariables()
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: status: single reviewer ok

#12018 Improves convergence speed of implicit Euler.
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/test/implicit_euler_integrator_test.cc
Labels: status: squashing now

#12014 workspace: Update externals to latest
  common/text_logging.h
  tools/install/libdrake/BUILD.bazel
  tools/workspace/BUILD.bazel
  tools/workspace/buildifier/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/fmt/package.BUILD.bazel
  tools/workspace/fmt/repository.bzl
  tools/workspace/ignition_math/package.BUILD.bazel
  tools/workspace/ignition_math/repository.bzl
  tools/workspace/ignition_rndf/BUILD.bazel
  tools/workspace/ignition_rndf/package-create-cps.py
  tools/workspace/ignition_rndf/package.BUILD.bazel
  tools/workspace/ignition_rndf/repository.bzl
  tools/workspace/meshcat/repository.bzl
  tools/workspace/stx/repository.bzl
Labels: priority: low, status: commits are properly curated

#12023 fix the link of the mathematical program tutorial.
  doc/index.rst
Labels: status: single reviewer ok

#12024 workspace: Remove unused ignition_rndf (drake.cps)
  tools/install/libdrake/drake.cps
Labels: configuration: cmake, priority: emergency, status: single reviewer ok

#11986 Mesh vs. Halfspace intersection
  geometry/proximity/BUILD.bazel
  geometry/proximity/mesh_half_space_intersection.h
  geometry/proximity/surface_mesh.h
  geometry/proximity/test/mesh_half_space_intersection_test.cc
Labels: status: squashing now

#12026 workspace: Add mirroring json for buildifier
  tools/workspace/buildifier/package.BUILD.bazel
  tools/workspace/buildifier/repository.bzl
Labels: priority: medium

#12037 setup: Make our package requirements available downstream
  setup/BUILD.bazel
Labels: priority: high

#12039 Clean up geometry::internal doxygen contents
  geometry/proximity/test/distance_to_point_with_gradient_test.cc
  geometry/proximity/test/proximity_utilities_test.cc
Labels: status: single reviewer ok

#12030 pid_controller: Reorder inheritance order to workaround pydrake errors
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/test/controllers_test.py
  examples/kuka_iiwa_arm/kuka_torque_controller.h
  examples/qp_inverse_dynamics/manipulator_joint_space_controller.h
  manipulation/schunk_wsg/schunk_wsg_plain_controller.h
  systems/controllers/inverse_dynamics_controller.h
  systems/controllers/pid_controller.h
Labels: status: single reviewer ok

#11987 Remove deprecated overload of AddForceElement
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: priority: low, status: commits are properly curated

#12029 Mesh/half space public interface
  geometry/proximity/BUILD.bazel
  geometry/proximity/mesh_half_space_intersection.h
  geometry/proximity/mesh_intersection.h
  geometry/proximity/test/mesh_half_space_intersection_test.cc
Labels: status: squashing now

#12054 workspace: Update fcl to latest commit
  tools/workspace/fcl/repository.bzl
Labels: status: single reviewer ok

#12051 Add new constructors of MultipleShooting which accept placeholders
  solvers/decision_variable.h
  systems/trajectory_optimization/multiple_shooting.cc
  systems/trajectory_optimization/multiple_shooting.h
  systems/trajectory_optimization/sequential_expression_manager.cc
  systems/trajectory_optimization/sequential_expression_manager.h
  systems/trajectory_optimization/test/multiple_shooting_test.cc
  systems/trajectory_optimization/test/sequential_expression_manager_test.cc
Labels: status: commits are properly curated

#12047 workspace: Update qdldl and osqp to latest release
  solvers/osqp_solver.cc
  tools/workspace/cmake_configure_file.bzl
  tools/workspace/cmake_configure_file.py
  tools/workspace/osqp/package.BUILD.bazel
  tools/workspace/osqp/repository.bzl
  tools/workspace/qdldl/README.md
  tools/workspace/qdldl/package.BUILD.bazel
  tools/workspace/qdldl/repository.bzl
Labels: priority: medium

#12060 fix: one version of the graphviz output for diagrams wasn't using port names
  systems/framework/diagram.h
  systems/framework/test/diagram_test.cc
Labels: status: single reviewer ok

#12056 Trampoline SolverInterface in python binding.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: status: squashing now

#12062 doc: Improve SNOPT citations and credits
  doc/from_binary.rst
  solvers/mathematical_program_doxygen.h
Labels: priority: medium

#12065 #12064 FIX: Gravity generalized forces must ignore velocity terms.
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree.h
  multibody/tree/uniform_gravity_field_element.cc
Labels: priority: high, team: dynamics, type: bug

#12050 Caches generalized accelerations
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: team: dynamics

#11983 Gripper brick constraint helper
  examples/planar_gripper/brick_static_equilibrium_constraint.cc
  examples/planar_gripper/gripper_brick.cc
  examples/planar_gripper/gripper_brick.h
  examples/planar_gripper/gripper_brick_planning_constraint_helper.cc
  examples/planar_gripper/gripper_brick_planning_constraint_helper.h
  examples/planar_gripper/test/gripper_brick_planning_constraint_helper_test.cc
Labels: status: squashing now

#12072 setup: Add suitesparse as a new dependency
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/binary_distribution/packages-xenial.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-xenial.txt
Labels: priority: medium

#12074 doc: Suggest Bionic as our preference (not Xenial)
  doc/from_source.rst
Labels: priority: low, status: single reviewer ok

#12071 workspace: Add suitesparse for osqp and scs
  tools/workspace/default.bzl
  tools/workspace/osqp/package.BUILD.bazel
  tools/workspace/scs/package.BUILD.bazel
  tools/workspace/scs/private.h.diff
  tools/workspace/scs/repository.bzl
  tools/workspace/suitesparse/BUILD.bazel
  tools/workspace/suitesparse/package.BUILD.bazel
  tools/workspace/suitesparse/repository.bzl
Labels: priority: medium

#12081 mkdoc: Enable the developer to specify docstring names
  bindings/pydrake/pydrake_doxygen.h
  bindings/pydrake/systems/controllers_py.cc
  doc/Doxyfile_CXX.in
  systems/controllers/pid_controlled_system.h
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/workspace/pybind11/test/sample_header.h
  tools/workspace/pybind11/test/sample_header_documentation.expected.h
Labels: priority: medium

#12089 update camera extrinsics in manipulation station class setup
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/test/manipulation_station_test.cc
Labels: status: single reviewer ok

#12082 Add utility for mapping Shape type to shape *name*
  geometry/proximity/BUILD.bazel
  geometry/proximity/proximity_utilities.cc
  geometry/proximity/proximity_utilities.h
  geometry/proximity/test/proximity_utilities_test.cc
Labels: priority: high, team: dynamics

#12085 Handle AutoDiffXd for contact surface between rigid and soft meshes
  geometry/proximity/BUILD.bazel
  geometry/proximity/mesh_intersection.cc
  geometry/proximity/mesh_intersection.h
  geometry/proximity/test/mesh_intersection_test.cc
Labels: priority: high, team: dynamics

#12083 Make sphere mesh from radius and characteristic length
  geometry/proximity/BUILD.bazel
  geometry/proximity/make_sphere_mesh.h
  geometry/proximity/test/make_sphere_mesh_test.cc
  multibody/hydroelastics/BUILD.bazel
  multibody/hydroelastics/hydroelastic_field_sphere.h
  multibody/hydroelastics/test/contact_surface_from_level_set_test.cc
Labels: priority: high, status: squashing now, team: dynamics

#12092 Suppress "self-assign-overloaded" warnings for Apple LLVM >= 10.0.1
  bindings/pydrake/symbolic_py.cc
Labels: status: single reviewer ok

#12090 draw body frames in meshcat visualizer
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
Labels: status: squashing now

#12096 Contact surface bug
  multibody/hydroelastics/contact_surface_from_level_set.h
  multibody/hydroelastics/hydroelastic_engine.cc
  multibody/hydroelastics/test/hydroelastic_engine_test.cc
  multibody/hydroelastics/test/sphere_vs_plane.sdf
Labels: team: dynamics

#12094 Hydroelastics produces accelerations
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: team: dynamics

#12084 workspace: Update scs to latest release
  solvers/test/scs_solver_test.cc
  tools/workspace/osqp/package.BUILD.bazel
  tools/workspace/qdldl/README.md
  tools/workspace/qdldl/package.BUILD.bazel
  tools/workspace/scs/package.BUILD.bazel
  tools/workspace/scs/private.c.diff
  tools/workspace/scs/private.h.diff
  tools/workspace/scs/repository.bzl
  tools/workspace/suitesparse/package.BUILD.bazel
  tools/workspace/suitesparse/repository.bzl
Labels: priority: medium

#12099 Renames existing callbacks into consistent naming convention
  geometry/proximity/BUILD.bazel
  geometry/proximity/distance_to_point_callback.h
  geometry/proximity/distance_to_point_with_gradient.cc
  geometry/proximity/distance_to_shape_callback.h
  geometry/proximity/find_collision_candidates_callback.cc
  geometry/proximity/find_collision_candidates_callback.h
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/distance_to_point_callback_test.cc
  geometry/proximity/test/find_collision_candidates_callback_test.cc
  geometry/proximity_engine.cc
Labels: priority: low, team: dynamics

#12067 Adds ContactResults for continuous MBP. Fixes #10529.
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/box_test.cc
Labels: team: dynamics, type: bug, type: feature request

#12095 pybind11: Use workaround for false cache hits for overloads
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok

#12103 Removes leftover dead code from #11928.
  multibody/plant/multibody_plant.h
Labels: team: dynamics, type: cleanup

#12105 Revert "pybind11: Use workaround for false cache hits for overloads"
  tools/workspace/pybind11/repository.bzl
Labels: priority: emergency, status: single reviewer ok

#12098 workspace: Remove snopt support for upstream BUILD files
  tools/workspace/snopt/repository.bzl
Labels: priority: low

#12041 Refactor pypi_archive and generate JSON repository metadata and update semantic_version to latest version
  tools/workspace/pypi.bzl
  tools/workspace/semantic_version/repository.bzl
Labels: status: commits are properly curated, team: kitware

#12070 [MBP] Allow discrete updates on empty worlds
  multibody/plant/implicit_stribeck_solver.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/implicit_stribeck_solver_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: team: dynamics, type: bug

#12093 [geometry] Minimum viable product - ComputeContactSurfaces
  examples/scene_graph/BUILD.bazel
  examples/scene_graph/simple_contact_surface_vis.cc
  geometry/BUILD.bazel
  geometry/geometry_state.h
  geometry/proximity/BUILD.bazel
  geometry/proximity/hydroelastic_callback.h
  geometry/proximity/test/hydroelastic_callback_test.cc
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/query_object.h
Labels: status: squashing now

#11924 Implements cylinder mesh generator for hydroelastics.
  geometry/proximity/BUILD.bazel
  geometry/proximity/make_cylinder_mesh.h
  geometry/proximity/test/make_cylinder_mesh_test.cc
Labels: priority: high, status: squashing now

#12106 Add drake::filesystem via new ghc::filesystem dependency
  common/BUILD.bazel
  common/filesystem.cc
  common/filesystem.h
  common/find_loaded_library.cc
  common/find_resource.cc
  common/find_runfiles.cc
  common/test/filesystem_test.cc
  common/test/find_runfiles_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/ghc_filesystem/BUILD.bazel
  tools/workspace/ghc_filesystem/package.BUILD.bazel
  tools/workspace/ghc_filesystem/repository.bzl
Labels: priority: low

#12116 filesystem: Ignore deprecations in ghc::filesystem
  common/filesystem.cc
  common/filesystem.h
Labels: priority: emergency, status: single reviewer ok

#12101 [geometry] Add face_normal() to SurfaceMesh, and fix centroid() after TransformVertices().
  geometry/proximity/surface_mesh.h
  geometry/proximity/test/surface_mesh_test.cc
Labels: status: squashing now

#12117 common: Port from spruce to filesystem
  common/BUILD.bazel
  common/drake_path.cc
  common/proto/BUILD.bazel
  common/proto/rpc_pipe_temp_directory.cc
  common/temp_directory.cc
  common/test/find_resource_test.cc
  common/test/temp_directory_test.cc
Labels: priority: low, status: single reviewer ok
