Repository RobotLocomotion/drake, pull requests merged in 2019-02, with the labels that each got.

#10545 Deprecate and remove all uses of DRAKE_ABORT
  automotive/maliput/api/road_geometry.cc
  automotive/maliput/geometry_base/lane.cc
  automotive/maliput/geometry_base/test_utilities/mock_geometry.cc
  automotive/maliput/multilane/builder.cc
  automotive/maliput/multilane/builder.h
  automotive/maliput/multilane/connection.cc
  automotive/maliput/multilane/lane.cc
  automotive/maliput/multilane/loader.cc
  automotive/maliput/rndf/builder.cc
  automotive/maliput/rndf/lane.cc
  automotive/maliput/rndf/road_geometry.cc
  automotive/maliput/rndf/road_geometry.h
  automotive/maliput/rndf/spline_lane.cc
  automotive/maliput/simplerulebook/simple_rulebook.cc
  automotive/maliput/utility/yaml_to_obj.cc
  automotive/road_path.cc
  bindings/pydrake/multibody/plant_py.cc
  common/drake_assert.h
  common/symbolic_expression_visitor.h
  common/symbolic_formula_visitor.h
  common/symbolic_variable.cc
  common/test/drake_assert_test.cc
  common/test/symbolic_simplification_test.cc
  examples/bouncing_ball/test/bouncing_ball_test.cc
  examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc
  examples/rod2d/rod2d-inl.h
  manipulation/planner/differential_inverse_kinematics.cc
  multibody/parsing/detail_scene_graph.cc
  multibody/tree/multibody_tree.cc
  solvers/branch_and_bound.cc
  solvers/create_constraint.cc
  solvers/solver_type_converter.cc
  solvers/test/solver_type_converter_test.cc
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/simulator.h
  systems/framework/event_collection.h
  systems/framework/system.h
  systems/framework/system_scalar_converter.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/output_port_test.cc
  systems/framework/test/system_test.cc
  systems/framework/witness_function.h
Labels: priority: low

#10560 solvers: Don't gratuitously promote to double to AutoDiffXd
  solvers/constraint.h
Labels: priority: backlog

#10512 doc python: Add tip on installing to `virtualenv` environment
  doc/python_bindings.rst
  setup/mac/binary_distribution/requirements.txt
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/binary_distribution/packages-xenial.txt
Labels: priority: low

#9368 py mathematical_program: Cleanup and enable non-everything testing
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/gurobi_py.cc
  bindings/pydrake/solvers/ipopt_py.cc
  bindings/pydrake/solvers/mosek_py.cc
  bindings/pydrake/solvers/osqp_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: priority: low

#10573 workspace: Add report for new upstream releases
  setup/ubuntu/source_distribution/packages-bionic.txt
  tools/workspace/BUILD.bazel
  tools/workspace/README.md
  tools/workspace/default.bzl
  tools/workspace/github3_py/BUILD.bazel
  tools/workspace/github3_py/package.BUILD.bazel
  tools/workspace/github3_py/repository.bzl
  tools/workspace/new_release.py
  tools/workspace/uritemplate_py/BUILD.bazel
  tools/workspace/uritemplate_py/package.BUILD.bazel
  tools/workspace/uritemplate_py/repository.bzl
Labels: priority: low

#10530 [geometry] Fix geometry removal bug - geometry with no proximity role
  geometry/geometry_state.cc
  geometry/test/geometry_state_test.cc
Labels: priority: medium, team: dynamics, type: bug

#10538 pydrake: Bind LCM contact results, inverse dynamics controllers, and sine.
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
Labels: status: curate commits before merging

#10575 workspace: Update externals to latest releases
  tools/workspace/bullet/repository.bzl
  tools/workspace/json/repository.bzl
  tools/workspace/meshcat/repository.bzl
  tools/workspace/osqp/repository.bzl
Labels: priority: low, status: do not merge

#10585 Remove caveat about lack of Python 3 in binary packages
  doc/python_bindings.rst
Labels: configuration: python, team: kitware, type: documentation, type: installation and distribution

#10586 docker: Fix entrypoint path
  setup/ubuntu/docker/bionic/Dockerfile
  setup/ubuntu/docker/xenial/Dockerfile
  setup/ubuntu/docker/xenial/Dockerfile.nvidia-cuda-8.0-devel-ubuntu16.04
Labels: priority: low

#10591 examples: Remove box_rotation and pick_and_place
  examples/kuka_iiwa_arm/dev/BUILD.bazel
  examples/kuka_iiwa_arm/dev/box_rotation/BUILD.bazel
  examples/kuka_iiwa_arm/dev/box_rotation/README.md
  examples/kuka_iiwa_arm/dev/box_rotation/box_rotation_demo.cc
  examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_diagram_factory.cc
  examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_diagram_factory.h
  examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc
  examples/kuka_iiwa_arm/dev/box_rotation/iiwa_dual_box_rot.pmd
  examples/kuka_iiwa_arm/dev/box_rotation/models/README.md
  examples/kuka_iiwa_arm/dev/box_rotation/models/box.urdf
  examples/kuka_iiwa_arm/dev/box_rotation/models/dual_iiwa14_primitive_cylinder_collision_only.urdf
  examples/kuka_iiwa_arm/dev/box_rotation/models/dual_iiwa14_primitive_cylinder_visual_collision.urdf
  examples/kuka_iiwa_arm/dev/box_rotation/models/dual_iiwa14_primitive_sphere_collision_only.urdf
  examples/kuka_iiwa_arm/dev/box_rotation/models/dual_iiwa14_primitive_sphere_visual_collision.urdf
  examples/kuka_iiwa_arm/dev/box_rotation/models/dual_iiwa14_visual_only.urdf
  examples/kuka_iiwa_arm/dev/box_rotation/models/large_extra_heavy_duty_table_surface_only_collision.sdf
  examples/kuka_iiwa_arm/dev/box_rotation/robot_keyframes.txt
  examples/kuka_iiwa_arm/dev/box_rotation/run_procman.sh
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/BUILD.bazel
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/README.md
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_system.cc
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_system.h
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/test/monolithic_pick_and_place_system_test.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/BUILD.bazel
  examples/kuka_iiwa_arm/dev/pick_and_place/README.md
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_planner.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_simulator.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_planner.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_planner.h
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_plant.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_plant.h
  examples/kuka_iiwa_arm/dev/pick_and_place/multi-process-simulation.pmd
  examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_demo.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_simulation_helpers.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/pick_and_place_simulation_helpers.h
  examples/kuka_iiwa_arm/dev/pick_and_place/state_machine_system.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/state_machine_system.h
  examples/kuka_iiwa_arm/pick_and_place/BUILD.bazel
  examples/kuka_iiwa_arm/pick_and_place/action.cc
  examples/kuka_iiwa_arm/pick_and_place/action.h
  examples/kuka_iiwa_arm/pick_and_place/configuration/dual_iiwa.pick_and_place_configuration
  examples/kuka_iiwa_arm/pick_and_place/configuration/single_iiwa.pick_and_place_configuration
  examples/kuka_iiwa_arm/pick_and_place/configuration/yellow_posts.pick_and_place_configuration
  examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.h
  examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration.proto
  examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration_parsing.cc
  examples/kuka_iiwa_arm/pick_and_place/pick_and_place_configuration_parsing.h
  examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.cc
  examples/kuka_iiwa_arm/pick_and_place/pick_and_place_state_machine.h
  examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_configuration_parsing_test.cc
  examples/kuka_iiwa_arm/pick_and_place/test/pick_and_place_state_machine_test.cc
  examples/kuka_iiwa_arm/pick_and_place/test/world_state_test.cc
  examples/kuka_iiwa_arm/pick_and_place/world_state.cc
  examples/kuka_iiwa_arm/pick_and_place/world_state.h
Labels: priority: medium

#10576 workspace: Update dreal,fmt,spdlog to latest release
  common/test/drake_cc_googletest_main_test.py
  common/test/text_logging_test.cc
  common/text_logging.cc
  common/text_logging.h
  solvers/unrevised_lemke_solver.cc
  tools/workspace/dreal/repository.bzl
  tools/workspace/dreal/versions.bzl
  tools/workspace/fmt/repository.bzl
  tools/workspace/spdlog/repository.bzl
Labels: priority: high

#10584 manipulation: Rewrite and test kuka_iiwa LCM systems
  common/text_logging.h
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_controller.cc
  examples/kuka_iiwa_arm/iiwa_world/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/kuka_iiwa_arm/lcm_plan_interpolator.cc
  examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  examples/manipulation_station/mock_station_simulation.cc
  manipulation/kuka_iiwa/BUILD.bazel
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.h
  manipulation/kuka_iiwa/iiwa_command_sender.cc
  manipulation/kuka_iiwa/iiwa_command_sender.h
  manipulation/kuka_iiwa/iiwa_status_receiver.cc
  manipulation/kuka_iiwa/iiwa_status_receiver.h
  manipulation/kuka_iiwa/iiwa_status_sender.cc
  manipulation/kuka_iiwa/iiwa_status_sender.h
  manipulation/kuka_iiwa/internal_iiwa_command_translator.h
  manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
  manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc
  manipulation/kuka_iiwa/test/iiwa_status_receiver_test.cc
  manipulation/kuka_iiwa/test/iiwa_status_sender_test.cc
Labels: priority: medium

#10612 doc: Add priority guidelines for PRs, update for issues
  doc/developers.rst
  doc/issues.rst
Labels: priority: low

#10630 Move codegen group under technical_notes
  common/symbolic_codegen.h
Labels: priority: low, team: manipulation

#10623 pydrake: Add OutputPort.EvalBasicVector
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: priority: high

#10541 python_lint: Make `ignore` argument more explicit
  tools/lint/BUILD.bazel
  tools/lint/python_lint.bzl
  tools/lint/test/python_lint_ignore_example.py
Labels: priority: low

#10634 solvers: Break Program-Solver circular dependency
  bindings/pydrake/solvers/gurobi_py.cc
  bindings/pydrake/solvers/ipopt_py.cc
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/mosek_py.cc
  bindings/pydrake/solvers/osqp_py.cc
  solvers/BUILD.bazel
  solvers/branch_and_bound.cc
  solvers/choose_best_solver.cc
  solvers/choose_best_solver.h
  solvers/dreal_solver.h
  solvers/equality_constrained_qp_solver.h
  solvers/gurobi_solver.h
  solvers/ipopt_solver.h
  solvers/linear_system_solver.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/mathematical_program_api.cc
  solvers/mathematical_program_deprecated.cc
  solvers/mathematical_program_solver_interface.cc
  solvers/moby_lcp_solver.h
  solvers/mosek_solver.h
  solvers/nlopt_solver.h
  solvers/osqp_solver.h
  solvers/scs_solver.h
  solvers/snopt_solver.h
  solvers/solve.cc
  solvers/solver_id.h
  solvers/solver_interface.cc
  solvers/solver_interface.h
  solvers/solver_result.h
  solvers/test/add_solver_util.h
  solvers/test/choose_best_solver_test.cc
  solvers/test/mathematical_program_test_util.cc
  solvers/test/mathematical_program_test_util.h
  solvers/test/mixed_integer_optimization_test.cc
  solvers/test/nonlinear_program_test.cc
  solvers/test/optimization_examples.cc
  solvers/test/optimization_examples.h
  solvers/test/quadratic_program_examples.cc
  solvers/test/quadratic_program_examples.h
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/second_order_cone_program_examples.h
  solvers/test/semidefinite_program_examples.cc
  solvers/test/semidefinite_program_examples.h
  solvers/unrevised_lemke_solver.h
Labels: priority: high

#10652 py mp: Do not test lorentz cone constraint with SNOPT
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/all.py
  bindings/pydrake/solvers/snopt_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: priority: high, type: build cop

#10439 multibody/plant: Compile for symbolic::Expression scalar
  multibody/plant/BUILD.bazel
  multibody/plant/contact_info.cc
  multibody/plant/contact_info.h
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/contact_results_to_lcm.h
  multibody/plant/coulomb_friction.h
  multibody/plant/implicit_stribeck_solver.cc
  multibody/plant/implicit_stribeck_solver.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_symbolic_test.cc
  multibody/plant/test/spring_mass_system_test.cc
  multibody/tree/linear_spring_damper.cc
Labels: priority: low

#10655 Remove the director-based iiwa examples.
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/README.md
  examples/kuka_iiwa_arm/director_config.json
  examples/kuka_iiwa_arm/director_config_dual.json
  examples/kuka_iiwa_arm/director_ik_app.py
  examples/kuka_iiwa_arm/kuka_iiwa_fp.csv
  examples/kuka_iiwa_arm/kuka_iiwa_fp_dual.csv
  examples/kuka_iiwa_arm/kuka_iiwa_signal_scope.py
  examples/kuka_iiwa_arm/kuka_iiwa_state_translator.py
  examples/kuka_iiwa_arm/kuka_sim.pmd
  examples/kuka_iiwa_arm/kuka_sim_dual.pmd
  examples/kuka_iiwa_arm/stored_poses.json
  examples/kuka_iiwa_arm/stored_poses_dual.json
Labels: priority: low

#10659 workspace: Use newer Doxygen on Ubuntu
  doc/BUILD.bazel
  doc/Doxyfile_CXX.in
  doc/documentation_instructions.rst
  doc/doxygen.py
  doc/doxygen_main.py
  doc/footer.html
  tools/workspace/default.bzl
  tools/workspace/doxygen/BUILD.bazel
  tools/workspace/doxygen/package.BUILD.bazel
  tools/workspace/doxygen/repository.bzl
  tools/workspace/mirrors.bzl
Labels: priority: medium

#10635 solvers: Add SolverBase helper class
  solvers/BUILD.bazel
  solvers/equality_constrained_qp_solver.cc
  solvers/equality_constrained_qp_solver.h
  solvers/mathematical_program_result.cc
  solvers/mathematical_program_result.h
  solvers/program_attribute.cc
  solvers/program_attribute.h
  solvers/solver_base.cc
  solvers/solver_base.h
  solvers/test/equality_constrained_qp_solver_test.cc
  solvers/test/program_attribute_test.cc
  solvers/test/solver_base_test.cc
Labels: priority: medium

#10649 common: Remove all dynamic_casts from Value<T>
  common/value.h
Labels: priority: low

#10640 Add open_browser flag to meshcat argparse
  bindings/pydrake/systems/meshcat_visualizer.py
  examples/manipulation_station/end_effector_teleop.py
  examples/manipulation_station/joint_teleop.py
Labels: status: curate commits before merging

#10662 pendulum: Print dynamics using MultibodyPlant
  examples/pendulum/BUILD.bazel
  examples/pendulum/print_symbolic_dynamics.cc
  examples/pendulum/test/PendulumWithFriction.urdf
  examples/pendulum/test/p1.urdf
  examples/pendulum/test/p10.urdf
  examples/pendulum/test/p11.urdf
  examples/pendulum/test/p12.urdf
  examples/pendulum/test/p2.urdf
  examples/pendulum/test/p3.urdf
  examples/pendulum/test/p4.urdf
  examples/pendulum/test/p5.urdf
  examples/pendulum/test/p6.urdf
  examples/pendulum/test/p7.urdf
  examples/pendulum/test/p8.urdf
  examples/pendulum/test/p9.urdf
  multibody/plant/multibody_plant.h
Labels: priority: backlog

#10677 Update documentation to reflect drake-external-examples repository name
  doc/downstream_testing.rst
  doc/from_binary.rst
  doc/getting_help.rst
Labels: team: kitware, type: documentation

#10673 solvers: Port MosekSolver and GurobiSolver to SolverBase
  solvers/BUILD.bazel
  solvers/gurobi_solver.cc
  solvers/gurobi_solver.h
  solvers/gurobi_solver_common.cc
  solvers/mosek_solver.cc
  solvers/mosek_solver.h
  solvers/mosek_solver_common.cc
  solvers/no_gurobi.cc
  solvers/no_mosek.cc
  solvers/solver_base.h
Labels: priority: high, status: do not merge

#10670 Update more code to use InputPort::Eval
  automotive/bicycle_car.cc
  automotive/driving_command_mux.cc
  automotive/dynamic_bicycle_car.h
  geometry/dev/scene_graph.cc
  geometry/scene_graph.cc
  multibody/inverse_kinematics/minimum_distance_constraint.cc
  multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/multibody_plant_test.cc
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/test/diagram_builder_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_scalar_converter_test.cc
  systems/framework/test/system_symbolic_inspector_test.cc
  systems/lcm/translator_system.h
  systems/primitives/test/random_source_test.cc
  systems/sensors/dev/rgbd_camera.h
Labels: priority: low

#10671 Updates computation of Nplus(q) for non-unit quaternions.
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/quaternion_floating_mobilizer.cc
  multibody/tree/quaternion_floating_mobilizer.h
Labels: team: dynamics, type: bug

#10672 solvers: Port most back-ends to use SolverBase
  solvers/BUILD.bazel
  solvers/dreal_solver.cc
  solvers/dreal_solver.h
  solvers/dreal_solver_common.cc
  solvers/equality_constrained_qp_solver.h
  solvers/gurobi_solver.h
  solvers/ipopt_solver.cc
  solvers/ipopt_solver.h
  solvers/ipopt_solver_common.cc
  solvers/linear_system_solver.cc
  solvers/linear_system_solver.h
  solvers/moby_lcp_solver.cc
  solvers/moby_lcp_solver.h
  solvers/mosek_solver.h
  solvers/nlopt_solver.cc
  solvers/nlopt_solver.h
  solvers/nlopt_solver_common.cc
  solvers/no_ipopt.cc
  solvers/no_nlopt.cc
  solvers/no_osqp.cc
  solvers/no_scs.cc
  solvers/no_snopt.cc
  solvers/osqp_solver.cc
  solvers/osqp_solver.h
  solvers/osqp_solver_common.cc
  solvers/scs_solver.cc
  solvers/scs_solver.h
  solvers/scs_solver_common.cc
  solvers/snopt_solver.cc
  solvers/snopt_solver.h
  solvers/snopt_solver_common.cc
  solvers/snopt_solver_f2c.cc
  solvers/unrevised_lemke_solver.cc
  solvers/unrevised_lemke_solver.h
Labels: priority: high

#10682 solvers: Use const-Solve in branch_and_bound
  solvers/BUILD.bazel
  solvers/branch_and_bound.cc
  solvers/branch_and_bound.h
  solvers/test/branch_and_bound_test.cc
Labels: priority: low

#10668 manipulation: Use new Eval sugars
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/iiwa_command_sender.cc
  manipulation/kuka_iiwa/iiwa_status_receiver.cc
  manipulation/kuka_iiwa/iiwa_status_sender.cc
  manipulation/kuka_iiwa/iiwa_status_sender.h
  manipulation/perception/optitrack_pose_extractor.cc
  manipulation/perception/pose_smoother.cc
  manipulation/schunk_wsg/schunk_wsg_lcm.cc
  manipulation/schunk_wsg/schunk_wsg_position_controller.cc
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc
  manipulation/schunk_wsg/test/schunk_wsg_lcm_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
Labels: priority: low

#10687 framework: Add deps to soften deprecation of :value
  systems/framework/BUILD.bazel
  systems/framework/value.h
Labels: priority: high

#10683 solvers: Port most in-package uses to const-Solve
  solvers/BUILD.bazel
  solvers/mixed_integer_rotation_constraint_internal.cc
  solvers/system_identification.cc
  solvers/test/complementary_problem_test.cc
  solvers/test/dreal_solver_test.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/ipopt_solver_test.cc
  solvers/test/mixed_integer_optimization_util_test.cc
  solvers/test/mixed_integer_rotation_constraint_corner_test.cc
  solvers/test/mixed_integer_rotation_constraint_limit_test.cc
  solvers/test/mixed_integer_rotation_constraint_test.cc
  solvers/test/non_convex_optimization_util_test.cc
  solvers/test/optimization_examples.cc
  solvers/test/osqp_solver_test.cc
  solvers/test/plot_feasible_rotation_matrices.cc
  solvers/test/scs_solver_test.cc
  solvers/test/snopt_solver_test.cc
  solvers/test/sos_constraint_test.cc
Labels: priority: low

#10601 Add an optional RGB image input port to DepthImageToPointCloud
  bindings/pydrake/perception_py.cc
  bindings/pydrake/test/perception_test.py
  perception/depth_image_to_point_cloud.cc
  perception/depth_image_to_point_cloud.h
  perception/test/depth_image_to_point_cloud_test.cc
Labels: status: curate commits before merging

#10628 Use DejaVu Sans fonts for Doxygen and pydrake Sphinx documentation
  bindings/pydrake/doc/BUILD.bazel
  bindings/pydrake/doc/_static/css/custom.css
  bindings/pydrake/doc/conf.py
  bindings/pydrake/doc/pydrake_sphinx_extension.py
  doc/Doxyfile_CXX.in
  doc/doxygen_extra.css
  setup/mac/source_distribution/Brewfile
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-xenial.txt
Labels: team: kitware, type: documentation

#10663 Remove deprecated methods (2019-02)
  bindings/pydrake/multibody/multibody_tree_py.cc
  math/quaternion.h
  math/rotation_matrix.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/rotational_inertia.h
  multibody/tree/spatial_inertia.h
  multibody/tree/unit_inertia.h
  systems/framework/context.h
  systems/framework/diagram.h
  systems/framework/parameters.h
  systems/framework/system_base.h
  systems/primitives/discrete_derivative.h
  systems/sensors/BUILD.bazel
Labels: priority: backlog

#10699 solvers: Tidy up the SolverDetails APIs
  solvers/gurobi_solver.cc
  solvers/gurobi_solver.h
  solvers/ipopt_solver.h
  solvers/mathematical_program_result.cc
  solvers/mathematical_program_result.h
  solvers/mosek_solver.h
  solvers/nlopt_solver.h
  solvers/osqp_solver.h
  solvers/scs_solver.h
  solvers/snopt_solver.h
  solvers/test/gurobi_solver_test.cc
  solvers/test/ipopt_solver_test.cc
  solvers/test/mathematical_program_result_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/nlopt_solver_test.cc
  solvers/test/osqp_solver_test.cc
  solvers/test/scs_solver_test.cc
  solvers/test/snopt_solver_test.cc
Labels: priority: high, status: do not merge

#10698 systems: Refactor PortBase to use out-of-line error reporting
  systems/framework/port_base.h
Labels: priority: low

#10697 common: Add kDrakeAssertIsArmed globals
  common/drake_assert.h
  common/test/drake_assert_test.cc
  common/test/pointer_cast_test.cc
  common/test_utilities/BUILD.bazel
  common/test_utilities/expect_throws_message.h
  geometry/test/frame_kinematics_vector_test.cc
  geometry/test/identifier_test.cc
  math/rotation_matrix.h
  math/test/rigid_transform_test.cc
  math/test/roll_pitch_yaw_test.cc
  math/test/rotation_matrix_test.cc
  multibody/tree/test/rotational_inertia_test.cc
  systems/framework/test/cache_entry_test.cc
  systems/framework/test/cache_test.cc
  systems/framework/test/output_port_test.cc
Labels: priority: medium

#10696 solvers: Add bindings related to const-Solve
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/osqp_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  bindings/pydrake/solvers/test/osqp_solver_test.py
Labels: priority: medium

#10705 geometry: Visualization should not depend on Gurobi
  geometry/BUILD.bazel
  manipulation/models/ycb/BUILD.bazel
  multibody/inverse_kinematics/BUILD.bazel
  systems/lcm/BUILD.bazel
Labels: priority: low

#10706 Improve Doxygen for InputPort, OutputPort, deprecation, inline
  doc/Doxyfile_CXX.in
  systems/framework/diagram_output_port.h
  systems/framework/input_port.h
  systems/framework/input_port_base.h
  systems/framework/leaf_output_port.h
  systems/framework/output_port.h
  systems/framework/output_port_base.h
  systems/framework/port_base.h
Labels: priority: low, type: documentation

#10711 primitives: Optimize pass_through for inlining
  systems/primitives/BUILD.bazel
  systems/primitives/pass_through.h
Labels: priority: medium

#10709 planner, attic/manipulation: Port to const-Solve
  attic/manipulation/dev/quasistatic_system.cc
  attic/manipulation/dev/quasistatic_system.h
  manipulation/planner/differential_inverse_kinematics.cc
Labels: priority: high

#10707 primitives: Tidy up some access modifiers
  systems/primitives/barycentric_system.h
  systems/primitives/constant_value_source.h
  systems/primitives/constant_vector_source.h
  systems/primitives/discrete_derivative.h
  systems/primitives/first_order_low_pass_filter.h
  systems/primitives/gain.h
  systems/primitives/integrator.cc
  systems/primitives/integrator.h
  systems/primitives/pass_through.h
  systems/primitives/piecewise_polynomial_affine_system.h
  systems/primitives/piecewise_polynomial_linear_system.h
  systems/primitives/random_source.h
  systems/primitives/saturation.h
  systems/primitives/signal_logger.h
  systems/primitives/sine.h
  systems/primitives/test/piecewise_linear_affine_test.h
  systems/primitives/trajectory_source.h
  systems/primitives/wrap_to_system.h
  systems/primitives/zero_order_hold.h
Labels: priority: low, status: do not merge

#10420 Remove calling prog solve
  attic/multibody/BUILD.bazel
  attic/multibody/inverse_kinematics_backend.cc
  attic/multibody/inverse_kinematics_trajectory_backend.cc
  attic/perception/estimators/dev/BUILD.bazel
  attic/perception/estimators/dev/test/articulated_icp_test.cc
  attic/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc
  attic/systems/estimators/dev/BUILD.bazel
  attic/systems/estimators/dev/pose_estimation_test.cc
  automotive/BUILD.bazel
  automotive/test/trajectory_optimization_test.cc
  bindings/pydrake/systems/trajectory_optimization_py.cc
  examples/acrobot/BUILD.bazel
  examples/acrobot/test/run_swing_up_traj_optimization.cc
  examples/cubic_polynomial/BUILD.bazel
  examples/cubic_polynomial/backward_reachability.cc
  examples/cubic_polynomial/region_of_attraction.cc
  examples/pendulum/BUILD.bazel
  examples/pendulum/trajectory_optimization_simulation.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  solvers/mixed_integer_rotation_constraint_internal.cc
  solvers/test/mixed_integer_rotation_constraint_corner_test.cc
  solvers/test/mixed_integer_rotation_constraint_test.cc
  solvers/test/plot_feasible_rotation_matrices.cc
  solvers/test/sos_constraint_test.cc
  systems/controllers/BUILD.bazel
  systems/controllers/linear_model_predictive_controller.cc
  systems/trajectory_optimization/BUILD.bazel
  systems/trajectory_optimization/direct_collocation.cc
  systems/trajectory_optimization/direct_collocation.h
  systems/trajectory_optimization/direct_transcription.cc
  systems/trajectory_optimization/direct_transcription.h
  systems/trajectory_optimization/multiple_shooting.cc
  systems/trajectory_optimization/multiple_shooting.h
  systems/trajectory_optimization/test/direct_collocation_test.cc
  systems/trajectory_optimization/test/direct_transcription_test.cc
  systems/trajectory_optimization/test/multiple_shooting_test.cc
Labels: priority: high, status: curate commits before merging

#10710 Add support for snopt_f2c and snopt_fortran Bazel configurations to CMake build
  CMakeLists.txt
Labels: configuration: cmake, team: kitware

#10708 primitives: Stop using OutputPort::Calc
  systems/framework/test/single_output_vector_source_test.cc
  systems/framework/test/vector_system_test.cc
  systems/primitives/linear_system.cc
  systems/primitives/test/adder_test.cc
  systems/primitives/test/affine_linear_test.h
  systems/primitives/test/affine_system_test.cc
  systems/primitives/test/barycentric_system_test.cc
  systems/primitives/test/constant_value_source_test.cc
  systems/primitives/test/constant_vector_source_test.cc
  systems/primitives/test/demultiplexer_test.cc
  systems/primitives/test/first_order_low_pass_filter_test.cc
  systems/primitives/test/gain_scalartype_test.cc
  systems/primitives/test/gain_test.cc
  systems/primitives/test/integrator_test.cc
  systems/primitives/test/linear_system_test.cc
  systems/primitives/test/matrix_gain_test.cc
  systems/primitives/test/multiplexer_test.cc
  systems/primitives/test/pass_through_scalartype_test.cc
  systems/primitives/test/pass_through_test.cc
  systems/primitives/test/piecewise_polynomial_affine_system_test.cc
  systems/primitives/test/piecewise_polynomial_linear_system_test.cc
  systems/primitives/test/random_source_test.cc
  systems/primitives/test/saturation_test.cc
  systems/primitives/test/sine_test.cc
  systems/primitives/test/trajectory_source_test.cc
  systems/primitives/test/wrap_to_system_test.cc
  systems/primitives/test/zero_order_hold_test.cc
Labels: priority: low, status: do not merge

#10712 common: Twain Value<T> definitions for readability
  common/value.cc
  common/value.h
Labels: priority: medium, status: do not merge

#10681 solvers: Deprecate the mutable Solve() APIs
  attic/multibody/dev/BUILD.bazel
  attic/multibody/global_inverse_kinematics.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/gurobi_solver_test.py
  bindings/pydrake/solvers/test/ipopt_solver_test.py
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  bindings/pydrake/solvers/test/mosek_solver_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/test/trajectory_optimization_test.py
  bindings/pydrake/systems/trajectory_optimization_py.cc
  common/drake_assert.h
  manipulation/kuka_iiwa/internal_iiwa_command_translator.h
  manipulation/schunk_wsg/gen/schunk_wsg_command.h
  manipulation/schunk_wsg/schunk_wsg_lcm.h
  solvers/BUILD.bazel
  solvers/dreal_solver.cc
  solvers/gurobi_solver.cc
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/mathematical_program_deprecated.cc
  solvers/mathematical_program_result.cc
  solvers/mathematical_program_result.h
  solvers/solver_base.cc
  solvers/solver_result.cc
  solvers/solver_result.h
  solvers/test/mathematical_program_result_test.cc
  solvers/test/mathematical_program_test.cc
  solvers/test/solver_base_test.cc
  systems/framework/value.h
  systems/trajectory_optimization/direct_collocation.cc
  systems/trajectory_optimization/direct_collocation.h
  systems/trajectory_optimization/direct_transcription.cc
  systems/trajectory_optimization/direct_transcription.h
  systems/trajectory_optimization/multiple_shooting.cc
  systems/trajectory_optimization/multiple_shooting.h
Labels: priority: medium

#10718 common: Add internal::TypeHash<T>
  common/BUILD.bazel
  common/hash.cc
  common/hash.h
  common/test/value_test.cc
  common/value.h
Labels: priority: medium, status: do not merge

#10733 pydrake/multibody: Tune up IK constraint tests
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
Labels: priority: emergency

#10732 Adds the ability to introspect collision candidates
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/scene_graph_inspector.h
  geometry/test/geometry_state_test.cc
  geometry/test/scene_graph_inspector_test.cc
Labels: priority: high, team: dynamics, type: feature request

#10740 workspace: Bump ccd to latest upstream commit
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/test/proximity_engine_test.cc
  tools/workspace/ccd/repository.bzl
Labels: priority: high, team: dynamics

#10760 Add python bindings for quadrotor example
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/doc/gen_sphinx.py
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/examples/quadrotor_py.cc
  bindings/pydrake/examples/test/quadrotor_test.py
  examples/quadrotor/quadrotor_plant.cc
  examples/quadrotor/quadrotor_plant.h
  examples/quadrotor/test/quadrotor_dynamics_test.cc
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/build_components_refresh.py
Labels: priority: high, team: russ

#10757 framework: Widen Context::SetFrom to work for any scalars
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/custom_test.py
  systems/framework/BUILD.bazel
  systems/framework/abstract_values.cc
  systems/framework/abstract_values.h
  systems/framework/context.h
  systems/framework/continuous_state.h
  systems/framework/discrete_values.h
  systems/framework/parameters.h
  systems/framework/scalar_conversion_traits.h
  systems/framework/state.h
  systems/framework/test/continuous_state_test.cc
  systems/framework/test/discrete_values_test.cc
  systems/framework/test/parameters_test.cc
Labels: priority: high, status: do not merge

#10762 framework: Deprecate CopyFrom in lieu of SetFrom
  automotive/maliput_railcar.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/custom_test.py
  examples/bouncing_ball/bouncing_ball.h
  examples/humanoid_controller/test/humanoid_plan_eval_system_test.cc
  examples/kinova_jaco_arm/test/jaco_lcm_test.cc
  examples/qp_inverse_dynamics/test/manipulator_joint_space_controller_test.cc
  systems/analysis/simulator.h
  systems/framework/abstract_values.h
  systems/framework/continuous_state.h
  systems/framework/diagram.h
  systems/framework/discrete_values.h
  systems/framework/leaf_system.h
  systems/framework/state.h
  systems/framework/system.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/lcm/lcm_driven_loop.cc
  systems/lcm/test/lcm_subscriber_system_test.cc
Labels: priority: backlog, status: do not merge

#10765 pydrake: De-boilerplate deprecation unit tests
  bindings/pydrake/common/test_utilities/BUILD.bazel
  bindings/pydrake/common/test_utilities/__init__.py
  bindings/pydrake/common/test_utilities/deprecation.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/test/ipopt_solver_test.py
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/trajectory_optimization_test.py
Labels: priority: low, status: do not merge

#10773 symbolic: ExtractDoubleOrThrow(NAN) should be NAN
  common/symbolic_expression.cc
  common/test/symbolic_expression_test.cc
Labels: priority: backlog, status: do not merge

#10632 Mouse + keyboard teleop for manipulation station
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/differential_ik.py
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
Labels: status: curate commits before merging

#10781 Deprecate and remove all uses of DRAKE_ABORT_MSG
  attic/manipulation/dev/quasistatic_system.cc
  attic/manipulation/util/robot_state_msg_translator.cc
  attic/multibody/collision/drake_collision.cc
  attic/multibody/collision/fcl_model.cc
  attic/multibody/collision/test/model_test.cc
  attic/multibody/collision/unusable_model.cc
  attic/multibody/rigid_body.h
  attic/multibody/rigid_body_plant/viewer_draw_translator.cc
  attic/systems/sensors/rgbd_renderer_ospray.cc
  attic/systems/sensors/rgbd_renderer_vtk.cc
  automotive/maliput/multilane/builder.h
  automotive/maliput/simplerulebook/simple_rulebook.cc
  automotive/maliput_railcar.cc
  common/drake_assert.h
  common/symbolic_expression_visitor.h
  common/test/drake_assert_test.cc
  examples/bead_on_a_wire/bead_on_a_wire-inl.h
  examples/double_pendulum/sdf_helpers.cc
  examples/kuka_iiwa_arm/iiwa_controller.cc
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/mock_station_simulation.cc
  examples/manipulation_station/proof_of_life.cc
  examples/rod2d/rod2d-inl.h
  geometry/dev/render/render_engine_vtk.cc
  geometry/internal_geometry.cc
  geometry/proximity_engine.cc
  geometry/test/proximity_engine_test.cc
  multibody/plant/multibody_plant.cc
  multibody/tree/joint.h
  solvers/mixed_integer_optimization_util.cc
  solvers/moby_lcp_solver.cc
  solvers/unrevised_lemke_solver.cc
  systems/analysis/implicit_euler_integrator-inl.h
  systems/framework/input_port_base.cc
  systems/framework/port_base.cc
  systems/framework/system.h
  systems/primitives/first_order_low_pass_filter.cc
  systems/primitives/linear_system.cc
  systems/primitives/random_source.cc
  systems/rendering/pose_aggregator.cc
  systems/rendering/pose_aggregator.h
  systems/sensors/image_to_lcm_image_array_t.cc
  systems/sensors/image_writer.cc
Labels: priority: low

#10684 Parse nonlinear SystemConstraint symbolically
  systems/optimization/BUILD.bazel
  systems/optimization/system_constraint_adapter.cc
  systems/optimization/system_constraint_adapter.h
  systems/optimization/system_constraint_wrapper.cc
  systems/optimization/test/system_constraint_adapter_test.cc
  systems/optimization/test/system_optimization_test_util.h
Labels: status: curate commits before merging

#10766 solvers: Add MathematicalProgram::UpdateInitialGuess
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: priority: medium
