Repository RobotLocomotion/drake, pull requests merged in 2019-10, with the labels that each got.

#12120 workspace: Add new archive types to new_release report
  tools/workspace/new_release.py
Labels: priority: low, status: single reviewer ok

#12088 Euler radau reconcile
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/implicit_euler_integrator.h
  systems/analysis/radau_integrator.h
  systems/analysis/test/implicit_euler_integrator_test.cc
  systems/analysis/test/radau_integrator_test.cc
  systems/analysis/test_utilities/BUILD.bazel
  systems/analysis/test_utilities/implicit_integrator_test.h
Labels: status: squashing now

#12131 py sensors: Make CameraInfo support pickling
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
Labels: status: single reviewer ok

#12126 Switch to python3 version of the optitrack client
  tools/workspace/optitrack_driver/optitrack_client
  tools/workspace/optitrack_driver/repository.bzl
Labels: status: single reviewer ok

#12114 Reframe mesh creation with "resolution hint"
  geometry/proximity/make_box_mesh.h
  geometry/proximity/make_sphere_mesh.h
Labels: priority: low, team: dynamics

#12123 [MBP] Implements joint reaction forces output port
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: priority: high, team: dynamics, type: feature request

#12132 [MBP] TAMSI unit test for worlds with anchored geometry and zero DoFs
  multibody/plant/BUILD.bazel
  multibody/plant/test/multibody_plant_tamsi_test.cc
Labels: team: dynamics

#12133 Work around incompatibilities between Eigen <= 3.3.7 and Apple LLVM 11.0.0
  tools/macos.bazelrc
Labels: configuration: mac, team: kitware

#12139 Add missing #include <thread> throughout
  attic/perception/estimators/dev/test/articulated_icp_test.cc
  examples/acrobot/run_plant_w_lcm.cc
  examples/acrobot/test/acrobot_lcm_msg_generator.cc
Labels: priority: medium, status: single reviewer ok

#12138 Remove macOS Python 2 support, part 1
  doc/developers.rst
  doc/python_bindings.rst
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/binary_distribution/requirements-py2.txt
  setup/mac/binary_distribution/requirements.txt
  setup/mac/source_distribution/install_prereqs.sh
  setup/mac/source_distribution/requirements.txt
  tools/macos.bazelrc
  tools/workspace/python/repository.bzl
  tools/workspace/u_msgpack_python/repository.bzl
Labels: configuration: mac, team: kitware

#12135 Improve Jacobian documentation per issue #12119
  multibody/plant/multibody_plant.h
Labels: priority: medium, status: squashing now, team: dynamics, type: documentation

#12142 solvers: Deprecate mathematical_program_lite label
  attic/manipulation/dev/BUILD.bazel
  attic/multibody/BUILD.bazel
  attic/multibody/rigid_body_plant/BUILD.bazel
  attic/perception/estimators/dev/BUILD.bazel
  attic/systems/controllers/qp_inverse_dynamics/BUILD.bazel
  attic/systems/estimators/dev/BUILD.bazel
  examples/cubic_polynomial/BUILD.bazel
  examples/planar_gripper/BUILD.bazel
  examples/rod2d/BUILD.bazel
  manipulation/planner/BUILD.bazel
  multibody/inverse_kinematics/BUILD.bazel
  multibody/optimization/BUILD.bazel
  solvers/BUILD.bazel
  systems/analysis/BUILD.bazel
  systems/controllers/BUILD.bazel
  systems/trajectory_optimization/BUILD.bazel
Labels: priority: low, status: single reviewer ok

#12145 pydrake: Remove deprecated attic-module aliases
  bindings/pydrake/attic/BUILD.bazel
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/test/all_test.py
Labels: priority: low, status: single reviewer ok

#12149 solvers: Avoid deprecated mathematical_program_lite label
  solvers/BUILD.bazel
Labels: priority: medium, status: single reviewer ok

#12147 Install requirements-py2.txt
  setup/BUILD.bazel
Labels: priority: high, status: single reviewer ok, team: kitware, type: build cop

#12148 Do not error when building on macOS Catalina
  tools/workspace/os.bzl
  tools/workspace/python/repository.bzl
Labels: configuration: mac, status: single reviewer ok, type: build cop

#12150 Set incompatible_remove_legacy_whole_archive to false
  tools/bazel.rc
Labels: configuration: bazel, status: single reviewer ok, team: kitware

#12144 Remove deprecated methods (2019-10-01)
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_primitives_extra.py
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  manipulation/util/geometry_inspector.py
  multibody/plant/contact_results.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/box_test.cc
  multibody/plant/test/multibody_plant_test.cc
  systems/primitives/random_source.h
Labels: priority: low, status: single reviewer ok

#12152 Refresh build_components.bzl
  tools/install/libdrake/build_components.bzl
Labels: priority: low, status: single reviewer ok, team: kitware, type: installation and distribution

#12155 Fix numpy_repository for python3-only builds
  tools/workspace/numpy/repository.bzl
  tools/workspace/python/repository.bzl
Labels: configuration: python, priority: high

#12156 Reformat multi-line `@throws` for doxygen
  geometry/geometry_properties.h
  geometry/geometry_state.h
  geometry/scene_graph.h
Labels: priority: medium

#12159 multibody: Remove deprecated attic aliases
  multibody/BUILD.bazel
Labels: priority: low, status: single reviewer ok

#12143 attic: Remove deprecated plan_eval and qp_id
  attic/multibody/rigid_body_tree_alias_groups.cc
  attic/multibody/rigid_body_tree_alias_groups.h
  attic/systems/controllers/plan_eval/BUILD.bazel
  attic/systems/controllers/plan_eval/README.md
  attic/systems/controllers/plan_eval/generic_plan.cc
  attic/systems/controllers/plan_eval/generic_plan.h
  attic/systems/controllers/plan_eval/manipulator_move_end_effector_plan.cc
  attic/systems/controllers/plan_eval/manipulator_move_end_effector_plan.h
  attic/systems/controllers/plan_eval/plan_eval_base_system.cc
  attic/systems/controllers/plan_eval/plan_eval_base_system.h
  attic/systems/controllers/plan_eval/test/generic_plan_test.cc
  attic/systems/controllers/plan_eval/test/manipulator_plan_test.cc
  attic/systems/controllers/plan_eval/test/test_common.h
  attic/systems/controllers/qp_inverse_dynamics/BUILD.bazel
  attic/systems/controllers/qp_inverse_dynamics/README.md
  attic/systems/controllers/qp_inverse_dynamics/deprecated.h
  attic/systems/controllers/qp_inverse_dynamics/id_controller_config.proto
  attic/systems/controllers/qp_inverse_dynamics/lcm_utils.cc
  attic/systems/controllers/qp_inverse_dynamics/lcm_utils.h
  attic/systems/controllers/qp_inverse_dynamics/param_parser.cc
  attic/systems/controllers/qp_inverse_dynamics/param_parser.h
  attic/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.cc
  attic/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics.h
  attic/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics_common.cc
  attic/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics_common.h
  attic/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics_system.cc
  attic/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics_system.h
  attic/systems/controllers/qp_inverse_dynamics/qp_output_translator_system.cc
  attic/systems/controllers/qp_inverse_dynamics/qp_output_translator_system.h
  attic/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.cc
  attic/systems/controllers/qp_inverse_dynamics/robot_kinematic_state.h
  attic/systems/controllers/qp_inverse_dynamics/robot_kinematic_state_translator_system.cc
  attic/systems/controllers/qp_inverse_dynamics/robot_kinematic_state_translator_system.h
  attic/systems/controllers/qp_inverse_dynamics/test/iiwa.alias_groups
  attic/systems/controllers/qp_inverse_dynamics/test/iiwa.id_controller_config
  attic/systems/controllers/qp_inverse_dynamics/test/iiwa_inverse_dynamics_test.cc
  attic/systems/controllers/qp_inverse_dynamics/test/lcm_utils_test.cc
  attic/systems/controllers/qp_inverse_dynamics/test/param_parser_test.cc
  attic/systems/controllers/qp_inverse_dynamics/test/params.alias_groups
  attic/systems/controllers/qp_inverse_dynamics/test/params.id_controller_config
  attic/systems/controllers/qp_inverse_dynamics/test/qp_inverse_dynamics_system_test.cc
  attic/systems/controllers/qp_inverse_dynamics/test/qp_output_translator_system_test.cc
  attic/systems/controllers/qp_inverse_dynamics/test/valkyrie.alias_groups
  attic/systems/controllers/qp_inverse_dynamics/test/valkyrie.id_controller_config
  attic/systems/controllers/qp_inverse_dynamics/test/valkyrie_balancing_test.cc
  examples/qp_inverse_dynamics/BUILD.bazel
  examples/qp_inverse_dynamics/README.md
  examples/qp_inverse_dynamics/manipulator_joint_space_controller.cc
  examples/qp_inverse_dynamics/manipulator_joint_space_controller.h
  examples/qp_inverse_dynamics/manipulator_move_joint_plan_eval_system.cc
  examples/qp_inverse_dynamics/manipulator_move_joint_plan_eval_system.h
  examples/qp_inverse_dynamics/test/manipulator_joint_space_controller_test.cc
  tools/install/libdrake/build_components.bzl
Labels: priority: low, status: single reviewer ok

#12160 examples: Switch iiwa deps to manipulation library
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  examples/manipulation_station/mock_station_simulation.cc
  manipulation/planner/BUILD.bazel
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  tools/install/libdrake/build_components.bzl
Labels: priority: low, status: single reviewer ok

#12161 multibody: Remove uses of spruce
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/package_map.cc
  multibody/parsing/parser.cc
  multibody/parsing/test/detail_path_utils_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/package_map_test.cc
  multibody/parsing/test/parser_test.cc
Labels: priority: low

#12157 Step 1 to remove deprecated Jacobian methods 2019-10-01, per issue #12154
  multibody/plant/multibody_plant.h
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: priority: medium, team: dynamics, type: cleanup

#12179 attic: Remove uses of spruce
  attic/manipulation/util/BUILD.bazel
  attic/manipulation/util/world_sim_tree_builder.cc
  attic/multibody/parsers/BUILD.bazel
  attic/multibody/parsers/test/parsers_frames_test/parsers_frames_test.cc
  attic/multibody/parsers/test/urdf_parser_test.cc
  attic/multibody/shapes/BUILD.bazel
  attic/multibody/shapes/geometry.cc
Labels: priority: low, status: single reviewer ok

#12109 Hooked up hydroelastic contact results.
  examples/multibody/rolling_sphere/BUILD.bazel
  examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
  geometry/query_results/contact_surface.h
  multibody/plant/BUILD.bazel
  multibody/plant/contact_model_doxygen.h
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
Labels: status: squashing now

#12177 Add python binding for functions in SceneGraphInspector.
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/test/geometry_test.py
  geometry/scene_graph_inspector.h
Labels: status: squashing now

#12180 sensors: Remove uses of spruce
  systems/sensors/BUILD.bazel
  systems/sensors/image_writer.cc
  systems/sensors/image_writer.h
  systems/sensors/test/image_writer_test.cc
Labels: priority: low

#12170 examples: Deprecate all valkyrie code
  examples/valkyrie/BUILD.bazel
  examples/valkyrie/README.md
  examples/valkyrie/actuator_effort_to_rigid_body_plant_input_converter.h
  examples/valkyrie/robot_command_to_desired_effort_converter.h
  examples/valkyrie/robot_state_decoder.h
  examples/valkyrie/robot_state_encoder.h
  examples/valkyrie/valkyrie_constants.h
  examples/valkyrie/valkyrie_pd_ff_controller.h
  examples/valkyrie/valkyrie_simulator.h
Labels: priority: low

#12185 bind functions in geometry::Shape
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
Labels: status: single reviewer ok, status: squashing now

#12171 Step 2 to remove deprecated Jacobian methods per issue #12154
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/multibody_tree_test.cc
Labels: priority: medium, status: commits are properly curated, status: squashing now, team: dynamics, type: cleanup

#12182 workspace: Deprecate @spruce
  tools/workspace/BUILD.bazel
  tools/workspace/spruce/package.BUILD.bazel
Labels: priority: low

#12189 pydrake: Remove deprecated attic-module aliases
  bindings/pydrake/attic/test/attic_forwarding_test.py
Labels: priority: low, status: single reviewer ok

#12162 Activates continuous contact force outputs for MBP.
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/inclined_plane_test.cc
Labels: status: squashing now

#12194 Add Catalina support and drop High Sierra support
  CMakeLists.txt
  doc/developers.rst
  doc/getting_help.rst
  doc/jenkins.rst
  setup/mac/binary_distribution/requirements-py2.txt
  setup/mac/source_distribution/Brewfile
  tools/macos.bazelrc
  tools/workspace/os.bzl
  tools/workspace/python/repository.bzl
Labels: team: kitware

#12115 Adds a test for ensuring that the Euler integrator matches the Radau1 implementation.
  systems/analysis/radau_integrator.h
  systems/analysis/test/radau_integrator_test.cc
Labels: status: squashing now

#12195 Install and use find-module for TinyXML2
  BUILD.bazel
  tools/install/cmake/BUILD.bazel
  tools/install/cmake/FindTinyXML2.cmake
  tools/install/libdrake/drake.cps
  tools/workspace/ignition_math/package-create-cps.py
  tools/workspace/ignition_math/package.BUILD.bazel
Labels: status: commits are properly curated, team: kitware, type: installation and distribution

#12181 py systems: Remove deprecated protected aliases
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  examples/manipulation_station/end_effector_teleop_sliders.py
Labels: priority: low, status: single reviewer ok

#12184 [geometry] Add resolution_hint parameter for MakeCylinderVolumeMesh.
  geometry/proximity/BUILD.bazel
  geometry/proximity/make_cylinder_mesh.h
  geometry/proximity/test/make_cylinder_mesh_test.cc
Labels: status: squashing now

#12205 Install and use find-module for GFlags
  tools/install/cmake/BUILD.bazel
  tools/install/cmake/FindGFlags.cmake
  tools/install/libdrake/drake.cps
Labels: status: commits are properly curated, team: kitware, type: installation and distribution

#12206 workspace: Specify type for download_and_extract
  tools/workspace/bitbucket.bzl
  tools/workspace/doxygen/repository.bzl
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/github.bzl
  tools/workspace/pypi.bzl
  tools/workspace/vtk/repository.bzl
Labels: priority: medium

#12209 add functions binding for RigidBody
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok

#12215 doc: Improve error message for broken symlinks
  doc/doxygen_main.py
Labels: priority: low, status: single reviewer ok

#12216 Guard creation of gflags::gflags_* targets
  tools/install/cmake/FindGFlags.cmake
Labels: team: kitware, type: installation and distribution

#12212 [geometry] Add MakeCylinderSurfaceMesh().
  geometry/proximity/BUILD.bazel
  geometry/proximity/make_cylinder_mesh.h
  geometry/proximity/test/make_cylinder_mesh_test.cc
Labels: status: squashing now

#12200 Extracting penetration as point pair into its own callback
  geometry/proximity/BUILD.bazel
  geometry/proximity/penetration_as_point_pair_callback.cc
  geometry/proximity/penetration_as_point_pair_callback.h
  geometry/proximity/proximity_utilities.h
  geometry/proximity/test/penetration_as_point_pair_callback_test.cc
  geometry/proximity_engine.cc
  geometry/test/proximity_engine_test.cc
Labels: team: dynamics

#12219 bind coulomb friction
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok, status: squashing now

#12217 State change norm nan check
  systems/analysis/BUILD.bazel
  systems/analysis/implicit_integrator.h
  systems/analysis/integrator_base.h
  systems/analysis/test/integrator_base_test.cc
Labels: status: squashing now

#12190 Add hydroelastic specification to proximity properties
  examples/scene_graph/simple_contact_surface_vis.cc
  geometry/BUILD.bazel
  geometry/geometry_state.h
  geometry/proximity/BUILD.bazel
  geometry/proximity/hydroelastic_callback.h
  geometry/proximity/test/hydroelastic_callback_test.cc
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/proximity_properties.cc
  geometry/proximity_properties.h
  geometry/test/proximity_properties_test.cc
Labels: priority: medium, team: dynamics

#12192 Remove methods/language for GeometricJacobian, AnalyticJacobian.
  manipulation/planner/differential_inverse_kinematics.h
  multibody/constraint/constraint_doxygen.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/tree/body_node.h
  multibody/tree/body_node_impl.h
  multibody/tree/mobilizer.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.cc
  multibody/tree/multibody_tree_system.h
  multibody/tree/test/multibody_tree_test.cc
Labels: priority: medium, status: squashing now, team: dynamics, type: cleanup, type: documentation

#12225 Collection of spelling corrections
  geometry/proximity/mesh_intersection.h
  geometry/proximity/penetration_as_point_pair_callback.cc
  geometry/query_object.h
  geometry/render/render_engine_ospray.cc
Labels: status: single reviewer ok

#12146 Change Python shebangs to point to python3, etc.
  doc/code_style_guide.rst
  doc/doxygen.py
  manipulation/util/convert_to_visualize_collisions.py
  tools/clion/bazel_wrapper
  tools/clion/test/bazel_wrapper_test.py
  tools/dev/add_cpplint.py
  tools/install/install.bzl
  tools/install/install.py.in
  tools/install/libdrake/build_components_refresh.py
  tools/lint/drakelint.py
  tools/ubuntu-xenial.bazelrc
Labels: status: commits are properly curated, team: kitware

#12220 proto: Deprecate common/proto/protobuf.h
  attic/multibody/BUILD.bazel
  common/proto/BUILD.bazel
  common/proto/protobuf.h
  common/proto/test/protobuf_test.cc
Labels: priority: low, status: single reviewer ok

#12224 Fix compiler identification for Bazel 1.1.0 on macOS
  common/test/drake_assert_test_compile_variants.sh
  tools/cc_toolchain/print_host_settings.sh
  tools/workspace/cc/repository.bzl
  tools/workspace/execute.bzl
Labels: configuration: mac, priority: high, status: commits are properly curated, team: kitware

#12124 Update recommended bazel version to 1.1
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: status: single reviewer ok, team: kitware

#12102 Hydroelastic pressure visualization
  examples/scene_graph/simple_contact_surface_vis.cc
  lcmtypes/lcmt_hydroelastic_contact_surface_tri_for_viz.lcm
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  tools/workspace/drake_visualizer/plugin/BUILD.bazel
  tools/workspace/drake_visualizer/plugin/show_hydroelastic_contact.py
  tools/workspace/drake_visualizer/plugin/show_hydroelastic_contact_surface.py
  tools/workspace/drake_visualizer/plugin/show_point_pair_contact.py
  tools/workspace/drake_visualizer/plugin/use_builtin_scripts.py
Labels: status: squashing now

#12208 Add install test checking generated drake-config.cmake
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/test/find_package_drake_install_test.py
Labels: team: kitware, type: installation and distribution

#12229 Add python binding for CalcJacobianAngular/TranslationalVelocity
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/test/autodiffutils_test.py
Labels: status: single reviewer ok, status: squashing now

#12232 Bind IK context, bind evaluator gradient sparsity.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: status: single reviewer ok, status: squashing now

#12223 Adds the Dormand-Prince (RK45) integrator.
  systems/analysis/BUILD.bazel
  systems/analysis/bogacki_shampine3_integrator.h
  systems/analysis/runge_kutta2_integrator.h
  systems/analysis/runge_kutta3_integrator.h
  systems/analysis/runge_kutta5_integrator.cc
  systems/analysis/runge_kutta5_integrator.h
  systems/analysis/test/bogacki_shampine3_integrator_test.cc
  systems/analysis/test/explicit_euler_integrator_test.cc
  systems/analysis/test/runge_kutta2_integrator_test.cc
  systems/analysis/test/runge_kutta3_integrator_test.cc
  systems/analysis/test/runge_kutta5_integrator_test.cc
  systems/analysis/test/semi_explicit_euler_integrator_test.cc
  systems/analysis/test_utilities/BUILD.bazel
  systems/analysis/test_utilities/generic_integrator_test.h
  systems/analysis/test_utilities/quartic_scalar_system.h
  systems/analysis/test_utilities/quintic_scalar_system.h
Labels: status: squashing now

#12241 kuka: Disable controlled_kuka_multibody_demo under kcov
  examples/kuka_iiwa_arm/controlled_kuka/BUILD.bazel
Labels: status: single reviewer ok

#12238 Remove support for Ubuntu 16.04 (Xenial)
  CMakeLists.txt
  doc/bazel.rst
  doc/developers.rst
  doc/docker.rst
  doc/from_binary.rst
  doc/getting_help.rst
  doc/python_bindings.rst
  doc/ubuntu.rst
  setup/BUILD.bazel
  setup/ubuntu/binary_distribution/install_prereqs.sh
  setup/ubuntu/binary_distribution/packages-xenial.txt
  setup/ubuntu/docker/xenial/Dockerfile
  setup/ubuntu/docker/xenial/Dockerfile.nvidia-cuda-7.5-devel-ubuntu16.04
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/packages-xenial.txt
  tools/install/cmake/BUILD.bazel
  tools/install/cmake/FindGFlags.cmake
  tools/install/libdrake/drake.cps
  tools/ubuntu-xenial.bazelrc
  tools/workspace/BUILD.bazel
  tools/workspace/README.md
  tools/workspace/cc/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/doxygen/Dockerfile
  tools/workspace/doxygen/build_binaries_with_docker
  tools/workspace/doxygen/repository.bzl
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/gflags/repository.bzl
  tools/workspace/ibex/repository.bzl
  tools/workspace/meshcat_python/package.BUILD.bazel
  tools/workspace/os.bzl
  tools/workspace/python/repository.bzl
  tools/workspace/u_msgpack_python/BUILD.bazel
  tools/workspace/u_msgpack_python/repository.bzl
  tools/workspace/vtk/Dockerfile
  tools/workspace/vtk/build_binaries_with_docker
  tools/workspace/vtk/repository.bzl
Labels: team: kitware

#12239 Update minimum required Bazel to 1.1, minimum required CMake to 3.10
  CMakeLists.txt
  WORKSPACE
  third_party/BUILD.bazel
  third_party/com_kitware_gitlab_cmake_cmake/3.10/Copyright.txt
  third_party/com_kitware_gitlab_cmake_cmake/3.10/Modules/FindProtobuf.cmake
  third_party/com_kitware_gitlab_cmake_cmake/3.10/vendor.txt
  tools/install/libdrake/drake.cps
  tools/install/libdrake/test/find_package_drake_install_test.py
  tools/workspace/BUILD.bazel
  tools/workspace/find_protobuf_cmake/BUILD.bazel
Labels: team: kitware

#12228 vector_gen: Add support for yaml input files
  tools/vector_gen/BUILD.bazel
  tools/vector_gen/attic/BUILD.bazel
  tools/vector_gen/attic/README.md
  tools/vector_gen/attic/test/lcm_vector_gen_test.sh
  tools/vector_gen/attic/test/sample.named_vector
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/test/sample_named_vector.yaml
  tools/vector_gen/vector_gen.bzl
Labels: priority: backlog

#12237 Add GetMyContextFromRoot() methods for subsystems.
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  systems/framework/context_base.h
  systems/framework/diagram.h
  systems/framework/framework_common.h
  systems/framework/system.h
  systems/framework/test/diagram_test.cc
Labels: team: dynamics

#12240 Remove support for C++14 and require C++17
  .clang-format
  CMakeLists.txt
  attic/multibody/rigid_body_tree_alias_groups.cc
  bindings/pydrake/.clang-format
  cmake/bazel.rc.in
  common/drake_optional.h
  common/hash.cc
  common/random.cc
  common/test/drake_assert_test_compile_variants.sh
  common/trajectories/piecewise_trajectory.h
  common/value.h
  doc/developers.rst
  manipulation/planner/robot_plan_interpolator.cc
  math/roll_pitch_yaw.cc
  solvers/mathematical_program.cc
  systems/framework/test/diagram_builder_test.cc
  systems/framework/test/vector_system_test.cc
  systems/rendering/frame_velocity.cc
  systems/rendering/pose_vector.cc
  systems/sensors/image.cc
  systems/sensors/image.h
  systems/sensors/pixel_types.cc
  tools/cc_toolchain/bazel.rc
  tools/install/libdrake/drake.cps
  tools/workspace/cc/repository.bzl
  tools/workspace/pycps/repository.bzl
Labels: team: kitware

#12226 mbp, sdformat: Remember link initial poses
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table_surface_only_collision.sdf
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: status: squashing now

#12244 vector_gen: Use yaml.safe_load
  tools/vector_gen/lcm_vector_gen.py
Labels: priority: high, status: single reviewer ok

#12243 Remove support for Python 2 except Director
  CMakeLists.txt
  bindings/pydrake/common/containers.py
  bindings/pydrake/systems/test/lcm_test.py
  common/test/cpplint_wrapper.py
  common/test_utilities/drake_py_unittest_main.py
  doc/bazel.rst
  doc/developers.rst
  doc/getting_help.rst
  doc/python_bindings.rst
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/bazel.rc
  tools/clion/test/bazel_wrapper_test.py
  tools/install/install_test_helper.py
  tools/jupyter/BUILD.bazel
  tools/jupyter/jupyter_py.bzl
  tools/jupyter/test/failing_notebook_test.py
  tools/jupyter/test/jupyter_notebook_test.py
  tools/lint/drakelint.py
  tools/skylark/pybind.bzl
  tools/ubuntu-bionic.bazelrc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/numpy/repository.bzl
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pybind11/run_mkdoc_with_python3.py
  tools/workspace/python/check_bazel_python.py
  tools/workspace/python/repository.bzl
  tools/workspace/python3/BUILD.bazel
  tools/workspace/python3/repository.bzl
Labels: status: squashing now, team: kitware

#12246 Remove usage of stx in favor of C++17 std::optional and std::variant
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/drake_optional_pybind.h
  bindings/pydrake/common/drake_variant_pybind.h
  bindings/pydrake/common/test/drake_variant_pybind_test.cc
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/examples/manipulation_station_py.cc
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/planner_py.cc
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/trajectory_optimization_py.cc
  common/BUILD.bazel
  common/drake_optional.h
  common/drake_variant.h
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake.cps
  tools/workspace/BUILD.bazel
  tools/workspace/stx/BUILD.bazel
  tools/workspace/stx/LICENSE
  tools/workspace/stx/package.BUILD.bazel
  tools/workspace/stx/package.cps
Labels: team: kitware

#12248 Remove most usage of six
  bindings/pydrake/__init__.py
  bindings/pydrake/common/cpp_const.py
  bindings/pydrake/common/cpp_template.py
  bindings/pydrake/common/test/cpp_template_test.py
  bindings/pydrake/common/test/deprecation_test.py
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/common/test/module_test.py
  bindings/pydrake/common/test_utilities/pickle_compare.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/test/math_test.py
  bindings/pydrake/test/mock_torch/torch.py
  bindings/pydrake/test/rtld_global_warning_test.py
  bindings/pydrake/test/symbolic_test.py
  common/proto/call_python_client.py
  common/test/cpplint_wrapper.py
  common/test/cpplint_wrapper_test.py
  doc/doxygen_main.py
  doc/sphinx_base.py
  tools/clion/test/bazel_wrapper_test.py
  tools/install/cpsutils.py
  tools/lint/drakelint.py
  tools/lint/formatter.py
  tools/workspace/new_release.py
Labels: status: single reviewer ok, team: kitware, type: cleanup

#12261 common: Factor text_logging string constants out of gflags
  common/text_logging.cc
  common/text_logging.h
  common/text_logging_gflags.h
Labels: priority: medium

#12250 Fix drake::drake-common-text-logging-gflags target
  tools/install/libdrake/drake.cps
  tools/install/libdrake/test/find_package_drake_install_test.py
Labels: team: kitware

#12260 Update CLion/Bazel version numbers
  doc/clion.rst
Labels: priority: high, status: single reviewer ok, team: dynamics, type: documentation

#12259 Fix mobilizer::SetRotationMatrix() to take RotationMatrix argument (not Matrix3).
  multibody/plant/test/floating_body_test.cc
  multibody/tree/quaternion_floating_mobilizer.cc
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/space_xyz_mobilizer.cc
  multibody/tree/space_xyz_mobilizer.h
  multibody/tree/test/quaternion_floating_mobilizer_test.cc
  multibody/tree/test/space_xyz_mobilizer_test.cc
Labels: priority: medium, status: squashing now, team: dynamics, type: performance

#12268 workspace: Update sdformat to latest release 8.4.0
  tools/workspace/sdformat/package.BUILD.bazel
  tools/workspace/sdformat/repository.bzl
Labels: priority: low

#12271 Use std::optional instead of drake::optional in attic and bindings
  attic/manipulation/planner/test/rbt_differential_inverse_kinematics_test.cc
  attic/manipulation/scene_generation/random_clutter_generator.cc
  attic/manipulation/scene_generation/random_clutter_generator.h
  attic/multibody/rigid_body_plant/compliant_material.h
  attic/multibody/rigid_body_plant/rigid_body_plant.h
  attic/systems/sensors/rgbd_camera.cc
  attic/systems/sensors/rgbd_renderer.cc
  attic/systems/sensors/rgbd_renderer.h
  attic/systems/sensors/rgbd_renderer_ospray.cc
  attic/systems/sensors/rgbd_renderer_ospray.h
  attic/systems/sensors/rgbd_renderer_vtk.cc
  attic/systems/sensors/rgbd_renderer_vtk.h
  bindings/pydrake/examples/manipulation_station_py.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/primitives_py.cc
Labels: status: single reviewer ok, team: kitware, type: cleanup

#12275 Use std::optional instead of drake::optional in perception
  perception/depth_image_to_point_cloud.cc
  perception/depth_image_to_point_cloud.h
  perception/test/depth_image_to_point_cloud_test.cc
Labels: status: single reviewer ok, team: kitware, type: cleanup

#12274 Use std::optional instead of drake::optional in multibody
  multibody/benchmarks/acrobot/make_acrobot_plant.cc
  multibody/benchmarks/inclined_plane/inclined_plane_plant.cc
  multibody/benchmarks/inclined_plane/inclined_plane_plant.h
  multibody/benchmarks/pendulum/make_pendulum_plant.cc
  multibody/hydroelastics/hydroelastic_engine.cc
  multibody/hydroelastics/hydroelastic_engine.h
  multibody/hydroelastics/test/hydroelastic_engine_test.cc
  multibody/optimization/test/optimization_with_contact_utilities.h
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/package_map.cc
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/inclined_plane_test.cc
  multibody/plant/test/joint_limits_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/spring_mass_system_test.cc
  multibody/tree/fixed_offset_frame.cc
  multibody/tree/fixed_offset_frame.h
  multibody/tree/frame.h
  multibody/tree/mobilizer_impl.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.h
  multibody/tree/test/linear_spring_damper_test.cc
  multibody/tree/test/multibody_forces_test.cc
  multibody/tree/test/multibody_tree_creation_test.cc
  multibody/tree/test/multibody_tree_test.cc
  multibody/tree/test/prismatic_joint_test.cc
  multibody/tree/test/revolute_joint_test.cc
  multibody/tree/test/revolute_spring_test.cc
  multibody/tree/test/weld_joint_test.cc
Labels: status: single reviewer ok, team: kitware, type: cleanup

#12280 Add missing C++17 header to clang-format configuration
  .clang-format
  bindings/pydrake/.clang-format
Labels: status: single reviewer ok, team: kitware

#12272 Use std::optional instead of drake::optional in common and examples
  common/drake_path.cc
  common/drake_path.h
  common/find_loaded_library.cc
  common/find_loaded_library.h
  common/find_resource.cc
  common/find_resource.h
  common/hash.h
  common/symbolic_simplification.cc
  common/test/find_loaded_library_test.cc
  common/test/find_resource_test.cc
  common/test/hash_test.cc
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_read_archive.h
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station.h
  examples/manipulation_station/proof_of_life.cc
  examples/multibody/inclined_plane_with_body/inclined_plane_with_body.cc
  examples/planar_gripper/planar_gripper_simulation.cc
  examples/van_der_pol/van_der_pol.cc
Labels: status: single reviewer ok, status: squashing now, team: kitware, type: cleanup

#12279 Do not use -Wno-unused-lambda-capture with GCC
  tools/skylark/pybind.bzl
Labels: status: single reviewer ok, team: kitware

#12284 Remove unncessary namespace qualifier for SystemTypeTag values
  attic/multibody/rigid_body_plant/rigid_body_plant.cc
  examples/acrobot/acrobot_plant.cc
  examples/bouncing_ball/bouncing_ball.h
  examples/compass_gait/compass_gait.cc
  examples/pendulum/pendulum_plant.cc
  examples/quadrotor/quadrotor_plant.cc
  examples/rimless_wheel/rimless_wheel.cc
  examples/van_der_pol/van_der_pol.cc
  geometry/scene_graph.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree_system.cc
  systems/analysis/test_utilities/discontinuous_spring_mass_damper_system.h
  systems/analysis/test_utilities/spring_mass_damper_system.h
  systems/analysis/test_utilities/stateless_system.h
  systems/controllers/pid_controller.cc
  systems/controllers/test/linear_model_predictive_controller_test.cc
  systems/framework/diagram.h
  systems/framework/system_scalar_conversion_doxygen.h
  systems/framework/test/diagram_builder_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/single_output_vector_source_test.cc
  systems/framework/test/vector_system_test.cc
  systems/plants/spring_mass_system/spring_mass_system.cc
  systems/primitives/adder.cc
  systems/primitives/affine_system.cc
  systems/primitives/constant_value_source.h
  systems/primitives/constant_vector_source.cc
  systems/primitives/demultiplexer.cc
  systems/primitives/discrete_derivative.cc
  systems/primitives/discrete_time_delay.cc
  systems/primitives/first_order_low_pass_filter.cc
  systems/primitives/gain.h
  systems/primitives/integrator.cc
  systems/primitives/linear_system.cc
  systems/primitives/matrix_gain.cc
  systems/primitives/multiplexer.cc
  systems/primitives/pass_through.h
  systems/primitives/port_switch.cc
  systems/primitives/signal_logger.cc
  systems/primitives/sine.h
  systems/primitives/symbolic_vector_system.cc
  systems/primitives/test/linear_system_test.cc
  systems/primitives/trajectory_affine_system.h
  systems/primitives/trajectory_linear_system.h
  systems/primitives/zero_order_hold.h
  systems/rendering/pose_aggregator.cc
  systems/rendering/render_pose_to_geometry_pose.cc
  systems/sensors/rotary_encoders.cc
Labels: priority: low, status: single reviewer ok

#12278 Deprecate drake_optional.h header
  common/BUILD.bazel
  common/drake_optional.h
Labels: team: kitware, type: cleanup

#12286 Revert "Ramp up anti-aliasing in the VTK color image"
  geometry/render/render_engine_vtk.cc
  geometry/render/render_engine_vtk.h
  geometry/render/render_engine_vtk_factory.h
  geometry/render/test/render_engine_vtk_test.cc
Labels: status: single reviewer ok

#12282 Deprecate drake_variant.h header
  common/BUILD.bazel
  common/drake_variant.h
Labels: team: kitware, type: cleanup

#12291 attic: Deprecate robotInterfaces and some of controllers
  attic/manipulation/dev/BUILD.bazel
  attic/systems/controllers/BUILD.bazel
  attic/systems/controllers/InstantaneousQPController.h
  attic/systems/controllers/QPCommon.h
  attic/systems/controllers/README.md
  attic/systems/controllers/controlUtil.h
  attic/systems/controllers/polynomial_encode_decode.h
  attic/systems/controllers/side.h
  attic/systems/controllers/yaml_util.h
  attic/systems/controllers/zmpUtil.h
  attic/systems/robotInterfaces/BUILD.bazel
  attic/systems/robotInterfaces/BodyMotionData.h
  attic/systems/robotInterfaces/QPLocomotionPlan.h
  attic/systems/robotInterfaces/README.md
  attic/systems/robotInterfaces/atlasUtil.h
  attic/systems/robotInterfaces/convex_hull.h
  attic/systems/robotInterfaces/verify_subtype_sizes.h
Labels: priority: low

#12292 attic: Deprecate perception
  attic/perception/BUILD.bazel
  attic/perception/README.md
  attic/perception/estimators/dev/BUILD.bazel
  attic/perception/estimators/dev/README.md
  attic/perception/estimators/dev/articulated_icp.h
  attic/perception/estimators/dev/pose_closed_form.h
  attic/perception/estimators/dev/scene.h
  attic/perception/rigid_body_point_cloud_filter.h
  attic/perception/transform_point_cloud.h
Labels: priority: low

#12249 Adds the resultant force from the hydroelastic model to the reporting data.
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm
  multibody/plant/BUILD.bazel
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/hydroelastic_quadrature_point_data.h
  multibody/plant/hydroelastic_traction_calculator.cc
  multibody/plant/hydroelastic_traction_calculator.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/hydroelastic_traction_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: status: squashing now
