Repository RobotLocomotion/drake, pull requests merged in 2019-01, with the labels that each got.

#10305 bazelrc: Add platform-specific --action_env=PATH
  tools/macos.bazelrc
  tools/ubuntu-bionic.bazelrc
  tools/ubuntu-xenial.bazelrc
  tools/workspace/execute.bzl
Labels: priority: high

#10282 manipulation: Add differential_inverse_kinematics tests using MBP
  attic/manipulation/planner/BUILD.bazel
  attic/manipulation/planner/test/rbt_differential_inverse_kinematics_test.cc
  manipulation/planner/BUILD.bazel
  manipulation/planner/test/differential_inverse_kinematics_test.cc
Labels: priority: medium, status: curate commits before merging, status: do not merge

#10330 Match output of CMake for install of stripped binaries and allow strip and install_name_tool to be specified
  CMakeLists.txt
  tools/install/install.py.in
  tools/install/test/install_meta_test.py
Labels: team: kitware, type: installation and distribution

#10263 Update and clean up SceneGraphInspector
  geometry/BUILD.bazel
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/scene_graph_inspector.h
  geometry/test/geometry_state_test.cc
  geometry/test/scene_graph_inspector_test.cc
Labels: priority: low, team: dynamics, type: cleanup

#10342 framework: Add OutputPort EvalEigenVector sugar
  systems/framework/output_port.h
  systems/framework/test/output_port_test.cc
Labels: priority: medium

#10344 Update geometry utilities
  geometry/BUILD.bazel
  geometry/dev/geometry_state.cc
  geometry/geometry_instance.cc
  geometry/geometry_state.cc
  geometry/proximity_engine.cc
  geometry/test/utilities_test.cc
  geometry/utilities.cc
  geometry/utilities.h
Labels: priority: high, team: dynamics

#9675 solar_system: Disambiguate frames for planets
  examples/scene_graph/solar_system.cc
  examples/scene_graph/solar_system.h
Labels: priority: low

#10355 setup: Upgrade to Bazel 0.21.0
  doc/clion.rst
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: priority: low, status: do not merge

#10362 common: Enable polynomial_test case
  common/test/polynomial_test.cc
Labels: priority: backlog, status: do not merge

#10356 logging: Allow the user access to the default sink
  common/test/text_logging_test.cc
  common/text_logging.cc
  common/text_logging.h
Labels: priority: low, status: do not merge

#10359 systems/lcm: Use model value for publisher input
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/test/custom_drake_signal_translator.h
  systems/lcm/test/lcm_publisher_system_test.cc
  systems/lcm/test/lcm_subscriber_system_test.cc
Labels: priority: low, status: do not merge

#10366 ipopt: Turn off the advertising banner
  solvers/ipopt_solver.cc
Labels: priority: backlog, status: do not merge

#10363 workspace/lcm: Disable all compiler warnings
  tools/workspace/lcm/package.BUILD.bazel
Labels: priority: low, status: do not merge

#10371 tools: Disable clang_format_lint on macOS by default
  tools/macos.bazelrc
Labels: priority: high

#10350 Add a macro to declare explicit template instantiation.
  common/default_scalars.h
  systems/framework/basic_vector.cc
  systems/framework/basic_vector.h
  systems/framework/context.cc
  systems/framework/context.h
  systems/framework/continuous_state.cc
  systems/framework/continuous_state.h
  systems/framework/diagram.cc
  systems/framework/diagram.h
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
  systems/framework/diagram_context.cc
  systems/framework/diagram_context.h
  systems/framework/diagram_continuous_state.cc
  systems/framework/diagram_continuous_state.h
  systems/framework/diagram_discrete_values.cc
  systems/framework/diagram_discrete_values.h
  systems/framework/diagram_output_port.cc
  systems/framework/diagram_output_port.h
  systems/framework/discrete_values.cc
  systems/framework/discrete_values.h
  systems/framework/event.h
  systems/framework/event_collection.cc
  systems/framework/event_collection.h
  systems/framework/input_port.cc
  systems/framework/input_port.h
  systems/framework/leaf_context.cc
  systems/framework/leaf_context.h
  systems/framework/leaf_output_port.cc
  systems/framework/leaf_output_port.h
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/output_port.cc
  systems/framework/output_port.h
  systems/framework/parameters.cc
  systems/framework/parameters.h
  systems/framework/single_output_vector_source.cc
  systems/framework/single_output_vector_source.h
  systems/framework/state.cc
  systems/framework/state.h
  systems/framework/subvector.cc
  systems/framework/subvector.h
  systems/framework/supervector.cc
  systems/framework/supervector.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_constraint.cc
  systems/framework/system_constraint.h
  systems/framework/system_output.h
  systems/framework/vector_base.cc
  systems/framework/vector_base.h
  systems/framework/vector_system.cc
  systems/framework/vector_system.h
  systems/framework/witness_function.h
Labels: priority: low

#10347 Add Python 3 dependencies for Mac
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/binary_distribution/requirements.txt
  setup/mac/source_distribution/install_prereqs.sh
Labels: configuration: mac

#10374 framework: Consolidate SystemConstraint construction
  automotive/simple_car.cc
  examples/van_der_pol/van_der_pol.cc
  systems/framework/diagram.h
  systems/framework/leaf_system.h
  systems/framework/system_constraint.cc
  systems/framework/system_constraint.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_constraint_test.cc
  systems/framework/test/system_symbolic_inspector_test.cc
  systems/framework/test/system_test.cc
  systems/sensors/beam_model.cc
Labels: priority: high, status: do not merge

#10364 multibody: Add default value for gravity vector
  bindings/pydrake/examples/multibody/cart_pole_passive_simulation.py
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/test/multibody_tree_test.py
  bindings/pydrake/systems/drawing_graphviz_example.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  examples/multibody/acrobot/run_lqr.cc
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  examples/simple_gripper/simple_gripper.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/test/multibody_tree_creation_test.cc
  multibody/tree/uniform_gravity_field_element.cc
  multibody/tree/uniform_gravity_field_element.h
Labels: priority: low, status: do not merge

#10377 Add support for Python 3 in CMake build
  CMakeLists.txt
  doc/developers.rst
  doc/python_bindings.rst
  tools/workspace/pybind11/package-create-cps.py
  tools/workspace/python/repository.bzl
Labels: team: kitware

#10378 Add Python 3 on Mac to support matrix
  doc/developers.rst
  doc/python_bindings.rst
  tools/workspace/python/repository.bzl
Labels: team: kitware

#10386 Use clang-format from llvm@6 formula
  setup/mac/source_distribution/Brewfile
  tools/lint/clang_format.py
  tools/macos.bazelrc
Labels: configuration: mac, team: kitware

#10357 common: Move //systems/framework:value here
  attic/manipulation/sensors/xtion.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/framework_py_values.cc
  common/BUILD.bazel
  common/test/value_test.cc
  common/value.cc
  common/value.h
  multibody/plant/test/contact_results_to_lcm_test.cc
  solvers/BUILD.bazel
  solvers/mathematical_program_result.cc
  solvers/mathematical_program_result.h
  solvers/test/mathematical_program_result_test.cc
  systems/framework/BUILD.bazel
  systems/framework/framework_common.h
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/value.cc
Labels: priority: backlog

#10398 Fix typo in name of RelWithDebInfo configuration and check CMAKE_BUILD_TYPE is in list of supported build types
  CMakeLists.txt
Labels: configuration: cmake, team: kitware, type: cleanup

#10399 Remove test_ik_pointwise and mark tests that use IPOPT and cause issues on macOS flaky
  attic/multibody/BUILD.bazel
  attic/multibody/test/test_ik_pointwise.cc
  examples/acrobot/BUILD.bazel
  examples/pendulum/BUILD.bazel
  examples/valkyrie/BUILD.bazel
Labels: type: build cop

#10390 issue template: Simplify. Move info to "Getting Help"
  .github/issue_template.md
  doc/getting_help.rst
Labels: priority: low

#10400 Miscellaneous cleanup of CMakeLists.txt
  CMakeLists.txt
Labels: configuration: cmake, team: kitware, type: cleanup

#10401 framework: Relocate a Constraint TODO
  systems/framework/system_constraint.h
  tools/vector_gen/lcm_vector_gen.py
Labels: priority: low, status: do not merge

#10395 Fix installed drake-visualizer on Mac
  tools/workspace/drake_visualizer/repository.bzl
Labels: configuration: mac, team: kitware

#10412 py symbolic: Filter updated warning message for == comparison
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/test/symbolic_test.py
  common/test_utilities/drake_py_unittest_main.py
Labels: priority: high, type: build cop

#10415 Suppress numerous compiler warnings when using sanitizers on Mac
  tools/macos.bazelrc
Labels: configuration: mac, team: kitware

#10404 framework: Hoist the constraint calc typedef to top-level
  examples/van_der_pol/van_der_pol.cc
  systems/framework/BUILD.bazel
  systems/framework/diagram.h
  systems/framework/framework_common.h
  systems/framework/leaf_system.h
  systems/framework/system_constraint.h
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_constraint_test.cc
  systems/framework/test/system_test.cc
  systems/sensors/beam_model.cc
Labels: priority: low, status: do not merge

#10341 Lcm publisher system fixup (addresses issue #10176)
  attic/manipulation/sensors/xtion.cc
  attic/systems/sensors/rgbd_camera_publish_lcm_example.cc
  automotive/test/automotive_simulator_test.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/lcm_test.py
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc
  examples/kuka_iiwa_arm/dev/monolithic_pick_and_place/monolithic_pick_and_place_demo.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_planner.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_simulator.cc
  examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  examples/manipulation_station/mock_station_simulation.cc
  examples/manipulation_station/proof_of_life.cc
  examples/rod2d/rod2d_sim.cc
  examples/scene_graph/dev/bouncing_ball_run_dynamics.cc
  examples/schunk_wsg/schunk_wsg_simulation.cc
  examples/valkyrie/valkyrie_simulator.h
  geometry/dev/geometry_visualization.cc
  geometry/geometry_visualization.cc
  multibody/plant/contact_results_to_lcm.cc
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/lcm_publisher_system.h
  systems/lcm/test/lcm_publisher_system_test.cc
  systems/sensors/lcm_image_array_receive_example.cc
Labels: team: dynamics

#10418 bazel: Add docs on running with cmdline flags
  doc/bazel.rst
Labels: priority: low

#10416 Remove Python dependencies from drake.cps
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake.cps
Labels: configuration: cmake, team: kitware

#10429 systems/lcm: Enable discrete updates with abstract output
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/dev/box_rotation/iiwa_box_simulation.cc
  examples/kuka_iiwa_arm/dev/pick_and_place/lcm_pick_and_place_simulator.cc
  examples/kuka_iiwa_arm/iiwa_lcm.cc
  examples/kuka_iiwa_arm/iiwa_lcm.h
  examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/manipulation_station/mock_station_simulation.cc
  examples/schunk_wsg/schunk_wsg_simulation.cc
  manipulation/schunk_wsg/BUILD.bazel
  manipulation/schunk_wsg/gen/schunk_wsg_command.cc
  manipulation/schunk_wsg/gen/schunk_wsg_command.h
  manipulation/schunk_wsg/schunk_wsg_command.named_vector
  manipulation/schunk_wsg/schunk_wsg_lcm.cc
  manipulation/schunk_wsg/schunk_wsg_lcm.h
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/test/lcm_subscriber_system_test.cc
Labels: priority: medium, status: do not merge

#10431 doc: Add platform_reviewer_checklist
  doc/developers.rst
  doc/issues.rst
  doc/platform_reviewer_checklist.rst
Labels: priority: low, status: do not merge

#10432 primitives: Stop using -inl.h pattern
  systems/primitives/constant_value_source-inl.h
  systems/primitives/constant_value_source.cc
  systems/primitives/constant_value_source.h
  systems/primitives/gain-inl.h
  systems/primitives/gain.cc
  systems/primitives/gain.h
  systems/primitives/pass_through-inl.h
  systems/primitives/pass_through.cc
  systems/primitives/pass_through.h
  systems/primitives/sine-inl.h
  systems/primitives/sine.cc
  systems/primitives/sine.h
  systems/primitives/test/gain_scalartype_test.cc
  systems/primitives/test/pass_through_scalartype_test.cc
  systems/primitives/zero_order_hold-inl.h
  systems/primitives/zero_order_hold.cc
  systems/primitives/zero_order_hold.h
Labels: priority: low, status: do not merge

#10394 framework: Add ExternalSystemConstraint to a System
  systems/framework/BUILD.bazel
  systems/framework/system.h
  systems/framework/system_constraint.h
  systems/framework/test/system_constraint_test.cc
Labels: priority: high

#10462 Fix various misspellings in comments
  attic/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc
  attic/manipulation/dev/quasistatic_system.cc
  attic/manipulation/planner/robot_plan_interpolator.h
  attic/multibody/test/rigid_body_tree/anchored_geometry_test.cc
  attic/perception/rigid_body_point_cloud_filter.h
  automotive/maliput/rndf/builder.cc
  automotive/test/idm_controller_test.cc
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/multibody/test/multibody_tree_test.py
  bindings/pydrake/multibody/test/parsing_test.py
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/meshcat_visualizer.py
  doc/doxygen.h
  examples/allegro_hand/allegro_common.cc
  examples/allegro_hand/allegro_common.h
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/allegro_hand/joint_control/run_twisting_mug.cc
  examples/humanoid_controller/humanoid_status.cc
  examples/manipulation_station/end_effector_teleop.py
  examples/multibody/cylinder_with_multicontact/BUILD.bazel
  geometry/dev/test/geometry_state_test.cc
  geometry/test/geometry_state_test.cc
  manipulation/perception/pose_smoother.cc
  multibody/plant/implicit_stribeck_solver.h
  multibody/plant/test/multibody_plant_test.cc
  solvers/mosek_solver.cc
  solvers/solver_options.h
  systems/analysis/simulator.h
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_constraint_test.cc
  systems/primitives/signal_logger.h
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/install/libdrake/build_components_refresh.py
  tools/skylark/test_tags.bzl
Labels: team: kitware, type: cleanup

#10417 [geometry] Clean up/extend GeometrySet API
  geometry/BUILD.bazel
  geometry/dev/BUILD.bazel
  geometry/dev/geometry_state.cc
  geometry/geometry_set.h
  geometry/geometry_state.cc
  geometry/test/geometry_set_test.cc
  geometry/test_utilities/BUILD.bazel
  geometry/test_utilities/geometry_set_tester.h
  multibody/plant/BUILD.bazel
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: low, team: dynamics, type: feature request

#10430 workspace/snopt: Downgrade to SNOPT 7.4
  doc/bazel.rst
  tools/workspace/snopt/repository.bzl
Labels: priority: low

#10472 py systems lcm: Ensure module is not reimported
  bindings/pydrake/systems/lcm_py.cc
Labels: priority: emergency

#10477 doc: Mention that we only support amd64 for Ubuntu
  doc/developers.rst
Labels: priority: low, status: do not merge, type: documentation

#10478 Check system processor in CMake build
  CMakeLists.txt
Labels: configuration: cmake, priority: low, team: kitware

#10459 Ensure CMake RelWithDebInfo and MinSizeRel configurations behave as expected
  CMakeLists.txt
  cmake/bazel.rc.in
Labels: configuration: cmake, team: kitware

#10480 common: Add drake_copyable support for separate definition
  common/drake_copyable.h
  doc/Doxyfile_CXX.in
  systems/framework/event.h
  systems/framework/event_collection.cc
  systems/framework/system_output.cc
  systems/framework/system_output.h
Labels: priority: medium, status: do not merge

#10485 systems/lcm: Allow fixed-size messages to be smaller than promised
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/test/lcm_subscriber_system_test.cc
Labels: priority: high

#10458 Remove DoPublish() overloads from Drake
  attic/multibody/rigid_body_plant/drake_visualizer.cc
  attic/multibody/rigid_body_plant/drake_visualizer.h
  attic/multibody/rigid_body_plant/frame_visualizer.cc
  attic/multibody/rigid_body_plant/frame_visualizer.h
  attic/systems/sensors/test/accelerometer_test/accelerometer_test_logger.cc
  attic/systems/sensors/test/accelerometer_test/accelerometer_test_logger.h
  systems/analysis/test/simulator_test.cc
  systems/analysis/test_utilities/logistic_system.h
  systems/analysis/test_utilities/my_spring_mass_system.h
  systems/analysis/test_utilities/stateless_system.h
  systems/lcm/test/lcm_log_playback_test.cc
Labels: priority: medium, team: dynamics, type: cleanup

#10494 analysis: lint fixup
  systems/analysis/test_utilities/my_spring_mass_system.h
Labels: priority: emergency

#10499 systems/lcm: Don't read past vector bounds with undersized messages
  systems/lcm/lcm_subscriber_system.cc
Labels: priority: high

#10510 multibody: Move helper into test_utilities
  multibody/benchmarks/free_body/BUILD.bazel
  multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc
  multibody/test_utilities/BUILD.bazel
  multibody/test_utilities/floating_body_plant.cc
  multibody/test_utilities/floating_body_plant.h
  multibody/tree/BUILD.bazel
  multibody/tree/test/floating_body_test.cc
Labels: priority: medium

#10525 py sensors: Fix latent Python 3 errors
  bindings/pydrake/attic/systems/sensors_py.cc
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/systems/sensors_py.cc
Labels: configuration: python, priority: high, type: build cop

#10511 multibody: Move floating_body_test from tree to plant
  multibody/plant/BUILD.bazel
  multibody/plant/test/floating_body_test.cc
  multibody/tree/BUILD.bazel
Labels: priority: medium, status: do not merge

#10514 systems/lcm: Deprecate Translator patterns entirely
  attic/multibody/rigid_body_plant/test/viewer_draw_translator_test.cc
  attic/multibody/rigid_body_plant/viewer_draw_translator.cc
  attic/multibody/rigid_body_plant/viewer_draw_translator.h
  attic/perception/estimators/dev/test/articulated_icp_test.cc
  attic/systems/sensors/BUILD.bazel
  attic/systems/sensors/rgbd_camera_publish_lcm_example.cc
  automotive/BUILD.bazel
  automotive/automotive_simulator.cc
  automotive/test/automotive_simulator_test.cc
  bindings/pydrake/systems/lcm_py.cc
  examples/valkyrie/test/valkyrie_ik_test.cc
  lcm/translator_base.h
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/lcm_publisher_system.h
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/lcm_translator_dictionary.h
  systems/lcm/test/lcm_publisher_system_test.cc
  systems/lcm/test/lcm_subscriber_system_test.cc
  systems/lcm/test/lcm_translator_dictionary_test.cc
  systems/lcm/translator_system.h
  systems/rendering/BUILD.bazel
  systems/rendering/pose_stamped_t_pose_vector_translator.h
  tools/vector_gen/BUILD.bazel
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/test/goal/sample_translator.h
Labels: priority: medium, status: do not merge

#10522 snopt: Fix two data races
  solvers/snopt_solver.cc
  solvers/test/snopt_solver_test.cc
  tools/workspace/snopt/fortran-macos.bzl
  tools/workspace/snopt/fortran-ubuntu.bzl
  tools/workspace/snopt/repository.bzl
  tools/workspace/snopt/snopt-openmp.patch
Labels: priority: low

#10540 snopt: Silence warnings on macOS
  solvers/snopt_solver.cc
Labels: priority: medium, status: do not merge

#10544 snopt: Add unit test for redundant cost calculations
  solvers/test/snopt_solver_test.cc
Labels: priority: low

#10543 doc: Mention --config snopt_fortran and related
  doc/bazel.rst
Labels: priority: low

#10535 multibody/tree: Compile for symbolic::Expression
  common/symbolic_expression.h
  multibody/tree/acceleration_kinematics_cache.cc
  multibody/tree/acceleration_kinematics_cache.h
  multibody/tree/articulated_body_inertia_cache.cc
  multibody/tree/articulated_body_inertia_cache.h
  multibody/tree/body.cc
  multibody/tree/body.h
  multibody/tree/body_node_impl.cc
  multibody/tree/fixed_offset_frame.cc
  multibody/tree/fixed_offset_frame.h
  multibody/tree/force_element.h
  multibody/tree/frame.h
  multibody/tree/joint.h
  multibody/tree/joint_actuator.cc
  multibody/tree/joint_actuator.h
  multibody/tree/linear_spring_damper.cc
  multibody/tree/linear_spring_damper.h
  multibody/tree/mobilizer.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.cc
  multibody/tree/multibody_tree_system.h
  multibody/tree/position_kinematics_cache.cc
  multibody/tree/position_kinematics_cache.h
  multibody/tree/prismatic_joint.cc
  multibody/tree/prismatic_joint.h
  multibody/tree/prismatic_mobilizer.cc
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/quaternion_floating_mobilizer.cc
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_joint.h
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/rigid_body.cc
  multibody/tree/rigid_body.h
  multibody/tree/space_xyz_mobilizer.cc
  multibody/tree/space_xyz_mobilizer.h
  multibody/tree/test/articulated_body_algorithm_test.cc
  multibody/tree/test/free_rotating_body_plant.cc
  multibody/tree/test/multibody_tree_creation_test.cc
  multibody/tree/test/multibody_tree_test.cc
  multibody/tree/uniform_gravity_field_element.cc
  multibody/tree/uniform_gravity_field_element.h
  multibody/tree/velocity_kinematics_cache.cc
  multibody/tree/velocity_kinematics_cache.h
  multibody/tree/weld_joint.cc
  multibody/tree/weld_joint.h
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: priority: medium

#10515 Quiet logging noise when using messages
  geometry/geometry_state.cc
  geometry/proximity_engine.cc
  geometry/shape_specification.cc
  geometry/test/geometry_state_test.cc
  geometry/test/proximity_engine_test.cc
Labels: priority: low, team: dynamics, type: cleanup
