Repository RobotLocomotion/drake, pull requests merged in 2019-04, with the labels that each got.

#11067 Remove deprecated methods (2019-04)
  attic/systems/controllers/qp_inverse_dynamics/test/qp_inverse_dynamics_system_test.cc
  automotive/automotive_simulator.cc
  bindings/pydrake/multibody/tree_py.cc
  common/drake_deprecated.h
  examples/humanoid_controller/test/humanoid_plan_eval_system_test.cc
  examples/manipulation_station/manipulation_station.h
  examples/valkyrie/test/robot_command_to_desired_effort_converter_test.cc
  examples/valkyrie/test/robot_state_encoder_decoder_test.cc
  geometry/geometry_set.h
  geometry/geometry_state.cc
  geometry/test_utilities/geometry_set_tester.h
  multibody/tree/joint.h
  systems/framework/system_constraint.h
  systems/framework/test/diagram_test.cc
  systems/primitives/constant_value_source.h
Labels: priority: backlog

#11056 framework: Add doxygen figure to explain cache trackers
  doc/Doxyfile_CXX.in
  systems/framework/cache_doxygen.h
  systems/framework/images/cache_doxygen_trackers.dot
Labels: priority: medium

#11107 workspace: Update externals to latest releases
  tools/workspace/ignition_math/package.BUILD.bazel
  tools/workspace/ignition_math/repository.bzl
  tools/workspace/json/repository.bzl
  tools/workspace/sdformat/package.BUILD.bazel
  tools/workspace/sdformat/repository.bzl
Labels: priority: backlog, status: do not merge

#11106 workspace: Bump meshcat to latest commits
  tools/workspace/meshcat/repository.bzl
  tools/workspace/meshcat_python/repository.bzl
Labels: priority: backlog, status: do not merge

#10935 systems/lcm: Add LcmInterfaceSystem
  automotive/automotive_demo.cc
  automotive/automotive_simulator.cc
  automotive/automotive_simulator.h
  automotive/test/automotive_simulator_test.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/test/lcm_test.py
  lcm/drake_lcm.h
  lcm/lcm_receive_thread.h
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_interface_system.cc
  systems/lcm/lcm_interface_system.h
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/test/connect_lcm_scope_test.cc
  systems/lcm/test/lcm_interface_system_test.cc
  systems/lcm/test/lcm_publisher_system_test.cc
  systems/lcm/test/lcm_subscriber_system_test.cc
  systems/sensors/BUILD.bazel
  systems/sensors/lcm_image_array_receive_example.cc
Labels: priority: medium

#11121 systems/lcm: Disable lcm_interface_system_test for now
  systems/lcm/BUILD.bazel
Labels: priority: emergency

#11126 Add instructions for dealing with drake-external-examples failures to the build cop playbook
  doc/buildcop.rst
Labels: team: kitware, type: documentation

#11122 systems/lcm: Re-enable lcm_interface_system_test
  systems/lcm/BUILD.bazel
  systems/lcm/test/lcm_interface_system_test.cc
Labels: priority: high

#11123 Add Substitute functions for symbolic matrix
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic_expression.h
  common/test/symbolic_substitution_test.cc
Labels: priority: low, team: russ

#11113 Add System methods for selective state updates after an event
  systems/analysis/simulator.h
  systems/framework/diagram.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/system_test.cc
Labels: team: dynamics, type: performance

#11124 examples: Port to LcmInterfaceSystem
  attic/multibody/rigid_body_plant/test/drake_visualizer_test.cc
  attic/multibody/rigid_body_plant/test/frame_visualizer_test.cc
  examples/acrobot/run_plant_w_lcm.cc
  examples/acrobot/spong_controller_w_lcm.cc
  examples/acrobot/test/acrobot_lcm_msg_generator.cc
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/double_pendulum/double_pendulum_demo.cc
  examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/particles/uniformly_accelerated_particle.cc
  examples/pr2/pr2_passive_simulation.cc
  examples/schunk_wsg/schunk_wsg_simulation.cc
  examples/valkyrie/test/valkyrie_simulation_test.cc
  examples/valkyrie/valkyrie_pd_ff_controller.cc
  examples/valkyrie/valkyrie_simulation.cc
  examples/valkyrie/valkyrie_simulator.h
Labels: priority: medium, status: do not merge

#11127 systems/lcm: Deprecate CopyLatestMessageInto
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/lcm_test.py
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/test/lcm_subscriber_system_test.cc
Labels: priority: low, status: do not merge

#11135 Revert "check if the constraint lower bound is no larger than the upper bound"
  multibody/inverse_kinematics/test/angle_between_vectors_constraint_test.cc
  solvers/constraint.h
  solvers/test/mathematical_program_test.cc
Labels: priority: emergency, type: bug, type: build cop

#11125 Selectively copy only the state for event-handling leaf subsystems
  systems/framework/diagram.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/test/diagram_test.cc
Labels: priority: high, team: dynamics, type: performance

#11131 mkdoc: Parse DRAKE_DEPRECATED into the pydrake doc
  bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/pydrake_doxygen.h
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/trajectory_optimization_py.cc
  systems/trajectory_optimization/multiple_shooting.h
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/workspace/pybind11/test/sample_header.h
  tools/workspace/pybind11/test/sample_header_documentation.expected.h
Labels: priority: medium

#11140 tsan: Suppress lcm_memq false positive
  tools/dynamic_analysis/tsan.supp
Labels: priority: emergency

#11145 Adds "freeze cache" capability to Context
  systems/framework/BUILD.bazel
  systems/framework/cache.h
  systems/framework/context_base.h
  systems/framework/framework_common.h
  systems/framework/test/cache_test.cc
Labels: priority: high, team: dynamics, type: feature request

#11119 manipulation_station: Use LcmInterfaceSystem
  bindings/pydrake/systems/meshcat_visualizer.py
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  examples/manipulation_station/mock_station_simulation.cc
  examples/manipulation_station/test/manipulation_station_hardware_interface_test.cc
Labels: priority: medium

#11165 Update to Bazel 0.24 recommended, Bazel 0.23 minimum
  CMakeLists.txt
  WORKSPACE
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: team: kitware

#10933 Visual test (only) of motion for uniform-density block on inclined plane.
  examples/multibody/inclined_plane/inclined_plane_run_dynamics.cc
  examples/multibody/inclined_plane_with_body/BUILD.bazel
  examples/multibody/inclined_plane_with_body/README.md
  examples/multibody/inclined_plane_with_body/inclined_plane_with_body.cc
  multibody/benchmarks/inclined_plane/BUILD.bazel
  multibody/benchmarks/inclined_plane/inclined_plane_plant.cc
  multibody/benchmarks/inclined_plane/inclined_plane_plant.h
  multibody/benchmarks/inclined_plane/make_inclined_plane_plant.cc
  multibody/benchmarks/inclined_plane/make_inclined_plane_plant.h
  multibody/plant/test/inclined_plane_test.cc
Labels: priority: high, team: dynamics, type: question

#11174 Make MemcpyMovable move-constructible
  common/test_utilities/test/is_memcpy_movable_test.cc
Labels: team: manipulation

#11158 systems/lcm: Deprecate MakeFixedSize
  examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/manipulation_station/mock_station_simulation.cc
  examples/schunk_wsg/schunk_wsg_simulation.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.h
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/test/lcm_subscriber_system_test.cc
Labels: priority: medium, status: do not merge

#11175 pydrake: Add lcm.Subscriber implementation
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/_lcm_extra.py
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/test/lcm_test.py
  lcm/drake_lcm_interface.h
Labels: priority: medium, status: curate commits before merging

#11147 Exponential cone constraint
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  solvers/constraint.cc
  solvers/constraint.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/program_attribute.cc
  solvers/program_attribute.h
  solvers/test/constraint_test.cc
  solvers/test/mathematical_program_test.cc
Labels: priority: medium

#11162 manipulation_station: Initialize q0 from robot in teleop --hardware
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
  examples/manipulation_station/joint_teleop.py
Labels: priority: low

#11183 For Issue#11064: Deprecate use of Isometry3 in WeldFrames(), SetFreeBodyPoseInWorldFrame(), SetFreeBodyPoseInAnchoredFrame()
  bindings/pydrake/examples/test/manipulation_station_test.py
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: low

#11186 Python bindings for witness functions
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  systems/framework/leaf_system.h
  systems/framework/test/leaf_system_test.cc
  systems/framework/witness_function.h
Labels: priority: high

#11204 Tag maliput::RoadNetwork::road_geometry() return reference as internal
  bindings/pydrake/maliput/api_py.cc
Labels: type: bug

#11206 examples: Stop using deprecated IIWA "command_message" port
  examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/manipulation_station/mock_station_simulation.cc
Labels: priority: low, status: do not merge

#11190 framework: Move feedthrough query to SystemBase
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
  systems/framework/system.h
  systems/framework/system_base.h
  systems/framework/test/cache_entry_test.cc
  systems/framework/test/system_base_test.cc
Labels: priority: high

#11199 Scs exponential cone
  solvers/BUILD.bazel
  solvers/scs_solver.cc
  solvers/scs_solver_common.cc
  solvers/test/exponential_cone_program_examples.cc
  solvers/test/exponential_cone_program_examples.h
  solvers/test/scs_solver_test.cc
Labels: priority: medium

#11178 Add --build_test_only to entries in dynamic analysis bazel.rc
  tools/dynamic_analysis/bazel.rc
Labels: priority: low, team: kitware

#11166 lcm: Deprecate many APIs
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/test/lcm_test.py
  lcm/BUILD.bazel
  lcm/drake_lcm.cc
  lcm/drake_lcm.h
  lcm/drake_mock_lcm.cc
  lcm/drake_mock_lcm.h
  lcm/lcm_receive_thread.h
  lcm/test/drake_lcm_test.cc
  lcm/test/drake_lcm_thread_test.cc
  systems/lcm/lcm_driven_loop.cc
  systems/lcm/test/lcm_publisher_system_test.cc
Labels: priority: low

#11177 Remove system name from MeshcatPointCloudVisualizer
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
Labels: priority: medium, status: curate commits before merging

#11220 MathematicalProgram maximizes log determinant.
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/exponential_cone_program_examples.cc
  solvers/test/exponential_cone_program_examples.h
  solvers/test/scs_solver_test.cc
Labels: priority: medium

#11235 drakelint: Report missing EOF more directly
  tools/lint/drakelint.py
  tools/lint/formatter.py
  tools/lint/test/formatter_test.py
Labels: priority: low, status: do not merge

#11241 acrobot: Move initial guess for swing up away from straight down
  examples/acrobot/test/run_swing_up_traj_optimization.cc
Labels: priority: emergency

#11226 RotationMatrix::ToQuaternion supports symbolic
  math/rotation_matrix.h
  math/test/rotation_matrix_test.cc
Labels: priority: medium

#11212 framework: Improve error message for algebraic loops
  systems/framework/diagram_builder.cc
  systems/framework/test/diagram_builder_test.cc
Labels: priority: medium

#11197 Replaces pointer versions of get_integrator() and get_mutable_integrator()...
  attic/manipulation/dev/quasistatic_iiwa_pick_and_place_demo.cc
  attic/manipulation/dev/test/rod2d_time_stepping.cc
  attic/manipulation/scene_generation/simulate_plant_to_rest.cc
  attic/systems/sensors/test/accelerometer_test/accelerometer_test.cc
  automotive/automotive_simulator.cc
  automotive/maliput/multilane/road_curve.cc
  examples/acrobot/run_lqr_w_estimator.cc
  examples/bouncing_ball/test/bouncing_ball_test.cc
  examples/contact_model/rigid_gripper.cc
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
  examples/manipulation_station/differential_ik.py
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/multibody/inclined_plane_with_body/inclined_plane_with_body.cc
  examples/quadrotor/run_quadrotor_lqr.cc
  examples/rod2d/rod2d_sim.cc
  examples/scene_graph/bouncing_ball_run_dynamics.cc
  examples/scene_graph/dev/bouncing_ball_run_dynamics.cc
  examples/scene_graph/dev/solar_system_run_dynamics.cc
  examples/scene_graph/solar_system_run_dynamics.cc
  multibody/plant/test/inclined_plane_test.cc
  multibody/plant/test/spring_mass_system_test.cc
  systems/analysis/BUILD.bazel
  systems/analysis/antiderivative_function.h
  systems/analysis/initial_value_problem.h
  systems/analysis/scalar_initial_value_problem.h
  systems/analysis/simulator.h
  systems/analysis/test/antiderivative_function_test.cc
  systems/analysis/test/initial_value_problem_test.cc
  systems/analysis/test/scalar_initial_value_problem_test.cc
  systems/analysis/test/simulator_test.cc
  systems/primitives/test/signal_logger_test.cc
Labels: team: dynamics

#11238 pydrake doc: Add explicit guideline for use of `py::arg`
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/pydrake_doxygen.h
Labels: priority: low

#11251 Hot fix to address sanitizer failures
  geometry/proximity/test/distance_to_point_test.cc
Labels: priority: emergency, team: dynamics, type: bug, type: sanitizer-asan

#11198 Make RigidTransform easy to use with Eigen::Translation3 in C++ (not Python).
  examples/manipulation_station/test/manipulation_station_test.cc
  geometry/test/proximity_engine_test.cc
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
  multibody/tree/test/weld_joint_test.cc
Labels: priority: medium, team: dynamics

#11249 Add test on the gradient for point to box/sphere signed distance query.
  geometry/proximity/distance_to_point.h
  geometry/proximity/distance_to_point_with_gradient.cc
  geometry/proximity/test/distance_to_point_test.cc
  geometry/query_results/signed_distance_to_point.h
  geometry/query_results/signed_distance_to_point_with_gradient.h
  geometry/test/proximity_engine_test.cc
Labels: priority: high

#11182 Implicit Euler Integrator refactor
  systems/analysis/BUILD.bazel
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/implicit_euler_integrator.h
  systems/analysis/implicit_integrator.cc
  systems/analysis/implicit_integrator.h
Labels: team: dynamics, type: cleanup

#11237 pydrake doc: Add example of using scoped aliases for abbreviation
  bindings/pydrake/attic/multibody/rigid_body_plant_py.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/manipulation/planner_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/pydrake_doxygen.h
  bindings/pydrake/systems/sensors_py.cc
Labels: priority: low

#11244 pendulum: Split PendulumGeometry from PendulumPlant
  examples/pendulum/BUILD.bazel
  examples/pendulum/energy_shaping_simulation.cc
  examples/pendulum/lqr_simulation.cc
  examples/pendulum/passive_simulation.cc
  examples/pendulum/pendulum_geometry.cc
  examples/pendulum/pendulum_geometry.h
  examples/pendulum/pendulum_plant.cc
  examples/pendulum/pendulum_plant.h
  examples/pendulum/test/pendulum_geometry_test.cc
  examples/pendulum/trajectory_optimization_simulation.cc
Labels: priority: medium

#11270 reviewable: Update commit count interlocks and automotive policy
  automotive/README.md
  doc/developers.rst
  doc/reviewable.rst
Labels: priority: medium

#11265 py mbp: Bind minimal but relevant spatial force API
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/math/spatial_force.h
  multibody/plant/test/external_forces_test.cc
  multibody/tree/body.h
Labels: status: commits are properly curated

#11262 common: Add find_runfiles
  common/BUILD.bazel
  common/find_loaded_library.cc
  common/find_runfiles.cc
  common/find_runfiles.h
  common/test/find_runfiles_fail_test.cc
  common/test/find_runfiles_subprocess_test.py
  common/test/find_runfiles_test.cc
Labels: priority: high

#11278 find_runfiles_test: Handle python3 str vs bytes
  common/test/find_runfiles_subprocess_test.py
Labels: priority: emergency, status: single reviewer ok

#11271 framework: Add conservative cache dependency on z
  systems/framework/cache_doxygen.h
  systems/framework/context_base.cc
  systems/framework/images/cache_doxygen_trackers.dot
  systems/framework/test/dependency_tracker_test.cc
  systems/framework/test/leaf_context_test.cc
Labels: priority: low, status: do not merge

#11201 framework: Use LeafOutputPort declared feedthrough
  automotive/maliput_railcar.cc
  automotive/maliput_railcar.h
  examples/pendulum/pendulum_plant.cc
  examples/quadrotor/quadrotor_plant.cc
  examples/quadrotor/quadrotor_plant.h
  examples/scene_graph/bouncing_ball_plant.cc
  examples/scene_graph/bouncing_ball_plant.h
  examples/scene_graph/dev/bouncing_ball_plant.cc
  examples/scene_graph/dev/bouncing_ball_plant.h
  examples/scene_graph/dev/solar_system.cc
  examples/scene_graph/dev/solar_system.h
  examples/scene_graph/solar_system.cc
  examples/scene_graph/solar_system.h
  systems/controllers/test/linear_model_predictive_controller_test.cc
  systems/controllers/test/pid_controlled_system_test.cc
  systems/estimators/luenberger_observer.cc
  systems/estimators/luenberger_observer.h
  systems/framework/leaf_system.h
  systems/framework/test/leaf_system_test.cc
  systems/primitives/discrete_derivative.cc
  systems/primitives/discrete_derivative.h
  systems/primitives/discrete_time_delay.cc
  systems/primitives/discrete_time_delay.h
  systems/primitives/test/discrete_derivative_test.cc
  systems/primitives/zero_order_hold.h
Labels: priority: medium, status: do not merge

#11280 GetJointByName: better error message for wrong joint type.
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree.h
Labels: priority: medium, team: dynamics, type: bug

#11274 iiwa_controller: Stop using lcm_driven_loop
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_controller.cc
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  lcm/drake_lcm_interface.cc
  lcm/drake_lcm_interface.h
  lcm/test/drake_lcm_interface_test.cc
Labels: priority: low, status: do not merge

#11284 examples/humanoid_controller: Deprecate the whole package
  examples/humanoid_controller/BUILD.bazel
  examples/humanoid_controller/README.md
Labels: priority: low

#11282 compute numerical gradient
  math/BUILD.bazel
  math/compute_numerical_gradient.h
  math/test/compute_numerical_gradient_test.cc
Labels: status: commits are properly curated

#11261 common: Use find_runfiles in find_resource
  attic/multibody/parsers/BUILD.bazel
  attic/multibody/parsers/test/urdf_parser_test.cc
  bindings/pydrake/test/common_install_test.py
  common/BUILD.bazel
  common/find_resource.cc
  common/find_resource.h
  common/find_resource_deprecated.cc
  common/test/find_resource_test.cc
  common/test/resource_tool_test.py
  multibody/parsing/BUILD.bazel
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  tools/install/install_test.py
Labels: priority: high

#11281 systems/lcm: Deprecate lcm_driven_loop
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/lcm_test.py
  examples/humanoid_controller/BUILD.bazel
  examples/kinova_jaco_arm/BUILD.bazel
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_driven_loop.cc
  systems/lcm/lcm_driven_loop.h
Labels: priority: medium

#11299 multibody: Use Calc prereqs, not DoHasDirectFeedthrough
  attic/multibody/rigid_body_plant/rigid_body_plant.cc
  attic/multibody/rigid_body_plant/rigid_body_plant.h
  attic/multibody/rigid_body_plant/rigid_body_plant_bridge.h
  attic/multibody/rigid_body_plant/test/rigid_body_plant_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: high

#11306 systems: Stop overriding DoHasDirectFeedthrough
  bindings/pydrake/systems/framework_py_systems.cc
  systems/framework/diagram.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/vector_system_test.cc
  systems/framework/vector_system.h
  systems/primitives/pass_through.h
  systems/primitives/symbolic_vector_system.cc
  systems/primitives/symbolic_vector_system.h
  systems/primitives/test/symbolic_vector_system_test.cc
Labels: priority: medium

#11309 Polishes docstring of maliput/base/intersection.h
  automotive/maliput/base/intersection.h
Labels: status: single reviewer ok

#10901 Fixes the error estimator in the RK3 integrator.
  automotive/maliput/multilane/road_curve.cc
  examples/bouncing_ball/bouncing_ball.h
  examples/bouncing_ball/test/bouncing_ball_test.cc
  examples/rimless_wheel/test/rimless_wheel_test.cc
  multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc
  multibody/plant/test/floating_body_test.cc
  multibody/tree/test/free_rotating_body_test.cc
  systems/analysis/integrator_base.h
  systems/analysis/runge_kutta3_integrator-inl.h
  systems/analysis/test/runge_kutta2_integrator_test.cc
  systems/analysis/test/runge_kutta3_integrator_test.cc
  systems/analysis/test_utilities/explicit_error_controlled_integrator_test.h
  systems/primitives/test/signal_logger_test.cc
Labels: status: squashing now

#11310 common: Deprecate find_resource on a directory
  common/find_resource.cc
  common/test/find_resource_test.cc
  common/test/resource_tool_installed_test.py
Labels: priority: high

#11305 geometry: Stop overriding DoHasDirectFeedthrough
  geometry/dev/scene_graph.h
  geometry/dev/test/scene_graph_test.cc
  geometry/scene_graph.h
  geometry/test/scene_graph_test.cc
  systems/rendering/multibody_position_to_geometry_pose.h
  systems/rendering/render_pose_to_geometry_pose.h
  systems/rendering/test/render_pose_to_geometry_pose_test.cc
Labels: priority: medium

#11314 doc: Use `\sum` instead of incorrect control sequence `\Sum`
  systems/controllers/linear_model_predictive_controller.h
  systems/trajectory_optimization/test/direct_transcription_test.cc
Labels: status: single reviewer ok

#11289 LorentzCone and RotatedLorentzCone stores sparse A.
  solvers/constraint.cc
  solvers/constraint.h
  solvers/gurobi_solver.cc
  solvers/mosek_solver.cc
  solvers/scs_solver.cc
Labels: status: squashing now

#11298 systems: Deprecate DoHasDirectFeedthrough
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
Labels: priority: low

#11313 py autodiff: Ensure pow() takes double exponents
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/test/autodiffutils_test.py
Labels: status: single reviewer ok

#11302 geometry: Make FrameKinematicsVector less ceremonial
  attic/manipulation/util/frame_pose_tracker.cc
  attic/multibody/rigid_body_plant/rigid_body_plant_bridge.cc
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  examples/pendulum/pendulum_geometry.cc
  examples/quadrotor/quadrotor_plant.cc
  examples/scene_graph/bouncing_ball_plant.cc
  examples/scene_graph/bouncing_ball_plant.h
  examples/scene_graph/dev/bouncing_ball_plant.cc
  examples/scene_graph/dev/bouncing_ball_plant.h
  examples/scene_graph/dev/solar_system.cc
  examples/scene_graph/solar_system.cc
  geometry/BUILD.bazel
  geometry/dev/geometry_state.cc
  geometry/dev/geometry_state.h
  geometry/dev/scene_graph.cc
  geometry/dev/test/geometry_state_test.cc
  geometry/dev/test/scene_graph_test.cc
  geometry/frame_kinematics_vector.cc
  geometry/frame_kinematics_vector.h
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/frame_kinematics_vector_test.cc
  geometry/test/geometry_state_test.cc
  geometry/test/scene_graph_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/multibody_plant_test.cc
  systems/rendering/render_pose_to_geometry_pose.cc
  systems/rendering/test/multibody_position_to_geometry_pose_test.cc
  systems/rendering/test/render_pose_to_geometry_pose_test.cc
  systems/sensors/test/optitrack_sender_test.cc
Labels: priority: low, status: do not merge

#11322 Removes meaningless const from Maliput APIs
  automotive/maliput/api/branch_point.h
  automotive/maliput/api/intersection.h
  automotive/maliput/api/junction.h
  automotive/maliput/api/lane.h
  automotive/maliput/api/road_geometry.h
  automotive/maliput/api/rules/phase_provider.h
  automotive/maliput/api/rules/traffic_lights.h
  automotive/maliput/api/segment.h
  automotive/maliput/api/test/mock.cc
  automotive/maliput/base/intersection.cc
  automotive/maliput/base/intersection.h
  automotive/maliput/dragway/branch_point.h
  automotive/maliput/dragway/junction.h
  automotive/maliput/dragway/lane.h
  automotive/maliput/dragway/road_geometry.h
  automotive/maliput/dragway/segment.h
  automotive/maliput/geometry_base/branch_point.cc
  automotive/maliput/geometry_base/branch_point.h
  automotive/maliput/geometry_base/junction.h
  automotive/maliput/geometry_base/lane.cc
  automotive/maliput/geometry_base/lane.h
  automotive/maliput/geometry_base/road_geometry.h
  automotive/maliput/geometry_base/segment.h
  automotive/maliput/multilane/branch_point.h
  automotive/maliput/multilane/junction.h
  automotive/maliput/multilane/lane.h
  automotive/maliput/multilane/road_geometry.h
  automotive/maliput/multilane/segment.h
  automotive/maliput/rndf/branch_point.h
  automotive/maliput/rndf/junction.h
  automotive/maliput/rndf/lane.h
  automotive/maliput/rndf/road_geometry.h
  automotive/maliput/rndf/segment.h
Labels: status: single reviewer ok

#11325 mkdoc: Don't discard docs of deprecated overloads
  bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/workspace/pybind11/test/sample_header.h
  tools/workspace/pybind11/test/sample_header_documentation.expected.h
Labels: priority: high

#11328 install: Run build_components_refresh
  multibody/optimization/BUILD.bazel
  tools/install/libdrake/build_components.bzl
Labels: priority: low, status: single reviewer ok

#11216 Add the abstract RenderEngine
  geometry/BUILD.bazel
  geometry/render/BUILD.bazel
  geometry/render/render_engine.cc
  geometry/render/render_engine.h
  geometry/render/test/render_engine_test.cc
  geometry/utilities.h
Labels: priority: medium

#11330 Remove template keywords within ContactWrenchEvaluator::ComposeVariableValues definition
  multibody/optimization/contact_wrench_evaluator.h
Labels: priority: high, status: single reviewer ok, team: kitware

#11332 Applies clang-format to rules_test_utilities.h
  automotive/maliput/api/test_utilities/rules_test_utilities.h
Labels: status: single reviewer ok

#11323 Deprecate MBP::get_continuous_state_output_port()
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
  examples/manipulation_station/manipulation_station.cc
  examples/multibody/acrobot/run_lqr.cc
  manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/applied_generalized_force_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: status: single reviewer ok, team: dynamics, type: cleanup

#11257 Welded bodies
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/topology/BUILD.bazel
  multibody/topology/multibody_graph.cc
  multibody/topology/multibody_graph.h
  multibody/topology/test/multibody_graph_test.cc
  multibody/tree/joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/revolute_joint.h
  multibody/tree/test/prismatic_joint_test.cc
  multibody/tree/test/revolute_joint_test.cc
  multibody/tree/test/weld_joint_test.cc
  multibody/tree/weld_joint.h
Labels: priority: medium, status: commits are properly curated, team: dynamics, type: feature request

#11308 Enhance RigidTransform class so operator* can multiply n position vectors
  math/BUILD.bazel
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
Labels: priority: high, status: squashing now, team: dynamics, type: bug

#11335 Remove deprecated `pydrake.util` module
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/all.py
  bindings/pydrake/util/BUILD.bazel
  bindings/pydrake/util/__init__.py
  bindings/pydrake/util/all.py
  bindings/pydrake/util/build_macros.bzl
  bindings/pydrake/util/test/alias_cc_test.cc
  bindings/pydrake/util/test/alias_py_test.py
  examples/manipulation_station/end_effector_teleop_sliders.py
  examples/manipulation_station/joint_teleop.py
Labels: status: single reviewer ok

#11338 Converted IntegrateWithFixedStepToTime(.) to return false rather than
  systems/analysis/BUILD.bazel
  systems/analysis/integrator_base.h
  systems/analysis/test/explicit_euler_integrator_test.cc
  systems/analysis/test/implicit_euler_integrator_test.cc
  systems/analysis/test/runge_kutta2_integrator_test.cc
  systems/analysis/test/runge_kutta3_integrator_test.cc
  systems/analysis/test_utilities/explicit_error_controlled_integrator_test.h
Labels: status: single reviewer ok, status: squashing now

#11336 find_resource: When DRAKE_RESOURCE_ROOT is invalid, only warn
  common/find_resource.cc
  common/test/resource_tool_installed_test.py
Labels: priority: high, status: do not merge

#11334 Mass matrix computation ignores velocity terms.
  examples/multibody/cart_pole/BUILD.bazel
  examples/multibody/cart_pole/test/cart_pole_test.cc
  multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h
  multibody/math/spatial_acceleration.h
  multibody/plant/multibody_plant.cc
  multibody/tree/body_node.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/tree_from_joints_test.cc
  multibody/tree/test/tree_from_mobilizers_test.cc
  multibody/tree/uniform_gravity_field_element.cc
Labels: team: dynamics

#11350 doc: Explain how to message jenkins bot via reviewable
  doc/BUILD.bazel
  doc/images/jenkins_bot_reviewable_comment.png
  doc/jenkins.rst
Labels: priority: low, status: single reviewer ok

#11344 mbp: Ensure that all API entry points for adding joints registers topology
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.h
Labels: priority: emergency

#11352 fix a few typos and remove a print to stdout in python bindings
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/test/math_overloads_test_utilities.py
Labels: status: single reviewer ok

#11355 workspace: Update fcl to latest commit
  tools/workspace/fcl/repository.bzl
Labels: priority: medium, status: do not merge, status: single reviewer ok
