Repository RobotLocomotion/drake, pull requests merged in 2019-07, with the labels that each got.

#11750 Add strip_path_prefix and other sanitizer options
  tools/dynamic_analysis/asan.sh
  tools/dynamic_analysis/bazel.rc
  tools/dynamic_analysis/lsan.sh
  tools/dynamic_analysis/msan.sh
  tools/dynamic_analysis/tsan.sh
  tools/dynamic_analysis/ubsan.sh
Labels: status: single reviewer ok, team: kitware

#11760 Exclude some slow running tests from asan and/or valgrind
  examples/schunk_wsg/BUILD.bazel
  solvers/BUILD.bazel
  systems/analysis/BUILD.bazel
Labels: status: single reviewer ok, team: kitware

#11757 Remove deprecated methods (2019-07)
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  common/test/value_test.cc
  common/value.h
  doc/bazel.rst
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/kuka_iiwa_arm/iiwa_lcm.h
  geometry/geometry_frame.h
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.h
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  math/rigid_transform.h
  multibody/plant/multibody_plant.h
  multibody/tree/fixed_offset_frame.h
  multibody/tree/weld_joint.h
  solvers/solver_base.cc
  solvers/solver_base.h
  solvers/solver_interface.h
  systems/framework/context.h
  systems/framework/context_base.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/system_base.h
  systems/framework/system_output.h
Labels: priority: medium, status: single reviewer ok

#11759 workspace: Update externals to new releases
  tools/workspace/fcl/repository.bzl
  tools/workspace/lcm/repository.bzl
  tools/workspace/optitrack_driver/repository.bzl
Labels: priority: low, status: single reviewer ok

#11761 Increase tolerance for SosConstraintTest.AddSosConstraintUnivariate2
  solvers/test/sos_constraint_test.cc
Labels: team: kitware, type: build cop

#11766 Improve RotationMatrix::operator* to handle generic 3 x n matrices
  math/rigid_transform.h
  math/rotation_matrix.h
  math/test/rotation_matrix_test.cc
  multibody/tree/multibody_tree.cc
Labels: status: squashing now, team: dynamics

#11770 doc: Repair clang-format path for macOS
  doc/code_style_tools.rst
Labels: priority: low, status: single reviewer ok, type: documentation

#11612 [geometry] Compute ContactSurface between soft and rigid geometries.
  geometry/proximity/BUILD.bazel
  geometry/proximity/mesh_field.h
  geometry/proximity/mesh_field_linear.h
  geometry/proximity/mesh_intersection.cc
  geometry/proximity/mesh_intersection.h
  geometry/proximity/surface_mesh.h
  geometry/proximity/test/contact_surface_test.cc
  geometry/proximity/test/mesh_field_test.cc
  geometry/proximity/test/mesh_intersection_test.cc
  geometry/proximity/test/surface_mesh_test.cc
  geometry/proximity/test/volume_mesh_test.cc
  geometry/proximity/volume_mesh.h
  geometry/proximity/volume_mesh_field.h
  geometry/query_results/BUILD.bazel
  geometry/query_results/contact_surface.h
Labels: status: squashing now

#11777 Added some topology info to SurfaceMesh.
  geometry/proximity/surface_mesh.h
  geometry/proximity/test/surface_mesh_test.cc
Labels: status: squashing now

#11737 Hydroelastic MBP dependency extraction.
  multibody/plant/BUILD.bazel
  multibody/plant/hydroelastic_traction_calculator.cc
  multibody/plant/hydroelastic_traction_calculator.h
  multibody/plant/test/hydroelastic_traction_test.cc
Labels: status: squashing now

#11773 Provide rigorous mathematical definition of inertia tensor/dyadic/matrix (address issue #5765)
  multibody/tree/rotational_inertia.h
Labels: status: single reviewer ok, status: squashing now, team: dynamics

#11774 Remove drake_RESOURCE_ROOT from drake.cps
  tools/install/libdrake/drake.cps
Labels: configuration: cmake, status: single reviewer ok, team: kitware, type: installation and distribution

#11755 Mosek supports exponential cone.
  solvers/BUILD.bazel
  solvers/mosek_solver.cc
  solvers/mosek_solver_common.cc
  solvers/test/mosek_solver_test.cc
Labels: status: squashing now

#11782 snopt: Completely disable test use of "Print file" under ASan
  solvers/test/snopt_solver_test.cc
Labels: priority: high, status: single reviewer ok

#11778 Add tags disabling dynamic analysis when disable_in_compilation_mode_dbg is set
  examples/schunk_wsg/BUILD.bazel
  systems/analysis/BUILD.bazel
  tools/skylark/drake_cc.bzl
Labels: team: kitware

#11787 Connect inertia dyadic to angular momentum, kinetic energy, moment of forces.
  multibody/tree/rotational_inertia.h
Labels: priority: low, status: single reviewer ok, team: dynamics, type: documentation

#11788 systems: Remove unnecessary uses of death tests
  automotive/maliput/rndf/test/spline_helpers_test.cc
  multibody/tree/test/tree_from_mobilizers_test.cc
  systems/framework/test_utilities/BUILD.bazel
  systems/framework/test_utilities/my_vector.h
  systems/framework/test_utilities/test/my_vector_test.cc
  systems/primitives/BUILD.bazel
  systems/primitives/affine_system.cc
  systems/primitives/gain.h
  systems/primitives/sine.h
  systems/primitives/test/affine_system_test.cc
  systems/primitives/test/gain_test.cc
  systems/primitives/test/sine_test.cc
Labels: priority: low, status: single reviewer ok

#11776 Move sparsity pattern from constraint to evaluator.
  solvers/constraint.cc
  solvers/constraint.h
  solvers/evaluator_base.cc
  solvers/evaluator_base.h
  solvers/test/constraint_test.cc
  solvers/test/evaluator_base_test.cc
Labels: status: squashing now

#11738 Rename one of the two variants of CalcFrameGeometricJacobianExpressedInWorld()
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: status: squashing now, team: dynamics

#11789 geometry: Remove unnecessary death tests
  geometry/BUILD.bazel
  geometry/identifier.h
  geometry/proximity/mesh_intersection.h
  geometry/proximity/test/mesh_intersection_test.cc
  geometry/test/identifier_test.cc
Labels: priority: backlog

#11784 Added simple method to convert vertices to Barycentric coordinates.
  geometry/proximity/mesh_field.h
  geometry/proximity/mesh_field_linear.h
  geometry/proximity/test/mesh_field_linear_test.cc
  geometry/proximity/test/mesh_field_test.cc
Labels: status: squashing now

#11793 vector_gen: Add Serialize
  tools/vector_gen/BUILD.bazel
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/test/goal/sample.h
  tools/vector_gen/test/sample_test.cc
  tools/vector_gen/vector_gen.bzl
Labels: priority: high

#11792 Spong parameters
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/examples/acrobot_py.cc
  bindings/pydrake/examples/test/acrobot_test.py
  examples/acrobot/BUILD.bazel
  examples/acrobot/spong_controller.cc
  examples/acrobot/spong_controller.h
  examples/acrobot/spong_controller_params.named_vector
  tools/install/libdrake/build_components.bzl
Labels: priority: high, status: commits are properly curated

#11798 Add python3-scipy to setup script
  setup/ubuntu/binary_distribution/packages-bionic.txt
Labels: status: single reviewer ok, team: kitware, type: installation and distribution

#11794 Update recommended Bazel version to 0.28
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: status: single reviewer ok

#11795 Hydroelastic multibody fields
  geometry/query_results/contact_surface.h
  multibody/plant/hydroelastic_traction_calculator.cc
  multibody/plant/hydroelastic_traction_calculator.h
  multibody/plant/test/hydroelastic_traction_test.cc
Labels: status: squashing now

#11783 pydrake trajectory: Add more bindings for PiecewisePolynomial
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/all.py
  bindings/pydrake/common/test_utilities/BUILD.bazel
  bindings/pydrake/common/test_utilities/numpy_compare.py
  bindings/pydrake/polynomial_py.cc
  bindings/pydrake/polynomial_types_pybind.h
  bindings/pydrake/test/polynomial_test.py
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
Labels: status: squashing now

#11752 Add new method CalcRelativeRotationMatrix() for efficiency and ease-of use.
  math/rotation_matrix.h
  multibody/inverse_kinematics/angle_between_vectors_constraint.cc
  multibody/inverse_kinematics/orientation_constraint.cc
  multibody/inverse_kinematics/test/angle_between_vectors_constraint_test.cc
  multibody/inverse_kinematics/test/orientation_constraint_test.cc
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/tree_from_mobilizers_test.cc
Labels: status: squashing now, team: dynamics

#11806 Deprecate `drake::SpatialForce`
  attic/multibody/rigid_body_plant/contact_force.h
  attic/multibody/rigid_body_plant/test/compliant_contact_model_test.cc
  attic/multibody/rigid_body_plant/test/compute_contact_result_test.cc
  attic/multibody/rigid_body_plant/test/contact_force_formula_test.cc
  attic/multibody/rigid_body_plant/test/contact_resultant_force_test.cc
  common/eigen_types.h
  examples/valkyrie/robot_state_encoder.cc
  examples/valkyrie/robot_state_encoder.h
  examples/valkyrie/test/robot_state_encoder_decoder_test.cc
  multibody/triangle_quadrature/BUILD.bazel
  multibody/triangle_quadrature/triangle_quadrature.cc
Labels: priority: low

#11810 pydrake: Add missing py_reference_internal to SignalLogger.data().
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
Labels: status: squashing now

#11804 Added hydroelastic contact info.
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/meshcat_visualizer.py
  multibody/plant/BUILD.bazel
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/hydroelastic_contact_info.cc
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/hydroelastic_traction_calculator.h
  multibody/plant/point_pair_contact_info.cc
  multibody/plant/point_pair_contact_info.h
  multibody/plant/test/box_test.cc
  multibody/plant/test/hydroelastic_traction_test.cc
Labels: status: squashing now

#11808 Remove RotationMatrix.linear(), change Matrix3 to RotationMatrix, lose some Isometry."
  examples/double_pendulum/sdf_helpers.cc
  examples/scene_graph/dev/solar_system.cc
  examples/scene_graph/solar_system.cc
  examples/valkyrie/robot_state_encoder.cc
  examples/valkyrie/test/robot_state_encoder_decoder_test.cc
  manipulation/planner/differential_inverse_kinematics.cc
  multibody/inverse_kinematics/angle_between_vectors_constraint.cc
  multibody/inverse_kinematics/orientation_constraint.cc
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/frame.h
  multibody/tree/mobilizer.h
  multibody/tree/rigid_body.h
  multibody/tree/uniform_gravity_field_element.cc
Labels: priority: medium, status: squashing now, team: dynamics

#11791 Shallow clone snopt git repo when branch or tag is specified
  CMakeLists.txt
  WORKSPACE
  tools/workspace/snopt/repository.bzl
Labels: team: kitware

#11811 plant: Repair broken contact_results method
  multibody/plant/contact_results.h
  multibody/plant/test/box_test.cc
Labels: priority: emergency, status: single reviewer ok

#11809 Add methods that streamline RigidTransform::set_rotation().
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
Labels: priority: medium, status: squashing now, team: dynamics

#11812 Fixes normal direction for level set vs. rigid case
  multibody/hydroelastics/hydroelastic_engine.cc
  multibody/hydroelastics/test/hydroelastic_engine_test.cc
Labels: team: dynamics, type: bug

#11816 Improve code towards rotation matrix and rigid transform
  examples/scene_graph/dev/solar_system.cc
  examples/scene_graph/solar_system.cc
  geometry/proximity/test/distance_to_point_with_gradient_test.cc
  manipulation/perception/test/optitrack_pose_extractor_test.cc
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  manipulation/util/test/bot_core_lcm_encode_decode_test.cc
  systems/controllers/setpoint.h
  systems/controllers/test/setpoint_test.cc
Labels: priority: medium, status: squashing now, team: dynamics

#11825 Python bindings for mainstream geometry render artifacts
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  bindings/pydrake/test/geometry_test.py
Labels: team: dynamics

#11821 Fix a bug in Accelerometer
  attic/systems/sensors/accelerometer.cc
  attic/systems/sensors/accelerometer.h
  attic/systems/sensors/test/accelerometer_test/accelerometer_test.cc
Labels: status: squashing now

#11824 MBP "visual" geometry has both illustration and perception roles
  geometry/test_utilities/dummy_render_engine.h
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: team: dynamics

#11772 Sliding friction complementarity constraint
  multibody/optimization/BUILD.bazel
  multibody/optimization/sliding_friction_complementarity_constraint.cc
  multibody/optimization/sliding_friction_complementarity_constraint.h
  multibody/optimization/test/optimization_with_contact_utilities.cc
  multibody/optimization/test/optimization_with_contact_utilities.h
  multibody/optimization/test/sliding_friction_complementarity_constraint_test.cc
Labels: status: squashing now

#11833 Fix docstring in trajectories_py.cc
  bindings/pydrake/trajectories_py.cc
  common/trajectories/piecewise_polynomial.h
Labels: status: single reviewer ok, team: kitware

#11743 Update to use unrestricted event handler
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/test/lcm_subscriber_system_test.cc
Labels: priority: low

#11828 Improve differential_inverse_kinematics with RotationMatrix and RigidTransform
  attic/manipulation/planner/rbt_differential_inverse_kinematics.cc
  manipulation/planner/differential_inverse_kinematics.cc
  manipulation/planner/differential_inverse_kinematics.h
  manipulation/planner/test/differential_inverse_kinematics_test.cc
Labels: priority: medium, status: squashing now, team: dynamics

#11834 framework: Add test for polymorphic port types
  systems/framework/BUILD.bazel
  systems/framework/test/diagram_builder_test.cc
Labels: priority: low, status: single reviewer ok

#11820 Allow adding render engine after registering geometry
  geometry/geometry_state.cc
  geometry/internal_geometry.cc
  geometry/internal_geometry.h
  geometry/render/render_engine.cc
  geometry/render/render_engine.h
  geometry/scene_graph.h
  geometry/test/geometry_state_test.cc
  geometry/test/internal_geometry_test.cc
  geometry/test/scene_graph_test.cc
Labels: status: commits are properly curated

#11832 Gripper brick system
  examples/planar_gripper/BUILD.bazel
  examples/planar_gripper/README.md
  examples/planar_gripper/gripper_brick.cc
  examples/planar_gripper/gripper_brick.h
  examples/planar_gripper/planar_brick.sdf
  examples/planar_gripper/planar_gripper.sdf
  examples/planar_gripper/planar_gripper.xacro
  examples/planar_gripper/planar_gripper_common.h
  examples/planar_gripper/test/gripper_brick_test.cc
Labels: status: squashing now

#11837 Add constraint for midpoint integration
  systems/trajectory_optimization/BUILD.bazel
  systems/trajectory_optimization/integration_constraint.cc
  systems/trajectory_optimization/integration_constraint.h
  systems/trajectory_optimization/test/integration_constraint_test.cc
Labels: status: squashing now

#11849 py multibody: Remove deprecated `multibody_tree` module
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/examples/multibody/BUILD.bazel
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/systems/BUILD.bazel
  multibody/tree/multibody_tree_indexes.h
  third_party/com_github_pybind_pybind11/mkdoc.py
Labels: status: single reviewer ok

#11853 styleguide: Bump to latest commit
  common/test/drake_assert_test.cc
  common/test_utilities/test/limit_malloc_test.cc
  tools/workspace/styleguide/repository.bzl
Labels: priority: low, status: single reviewer ok

#11835 Add methods for sequential variables to MultipleShooting
  bindings/pydrake/systems/test/trajectory_optimization_test.py
  bindings/pydrake/systems/trajectory_optimization_py.cc
  systems/trajectory_optimization/multiple_shooting.cc
  systems/trajectory_optimization/multiple_shooting.h
  systems/trajectory_optimization/sequential_expression_manager.cc
  systems/trajectory_optimization/sequential_expression_manager.h
  systems/trajectory_optimization/test/multiple_shooting_test.cc
  systems/trajectory_optimization/test/sequential_expression_manager_test.cc
Labels: status: squashing now

#11836 Start deprecating CalcFrameGeometricJacobianExpressedInWorld()
  manipulation/planner/differential_inverse_kinematics.cc
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/external_forces_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/multibody_tree_test.cc
  perception/depth_image_to_point_cloud.cc
Labels: priority: medium, status: squashing now, team: dynamics

#11858 geometry: Delete stale test comment
  geometry/render/test/render_engine_vtk_test.cc
Labels: status: single reviewer ok

#11848 Corrects pose smoother test for the usage of normalized quaternions
  manipulation/perception/pose_smoother.cc
  manipulation/perception/test/pose_smoother_test.cc
Labels: priority: high, team: dynamics

#11860 Example to clarify vector multiply and product of inertia convention
  multibody/tree/rotational_inertia.h
Labels: priority: low, status: single reviewer ok, team: dynamics, type: documentation

#11846 math: Clarify RigidTransform method deprecation date
  bindings/pydrake/math_py.cc
  math/rigid_transform.h
Labels: priority: low

#11769 Update jaco examples
  examples/kinova_jaco_arm/BUILD.bazel
  examples/kinova_jaco_arm/README.md
  examples/kinova_jaco_arm/jaco_common.cc
  examples/kinova_jaco_arm/jaco_common.h
  examples/kinova_jaco_arm/jaco_simulation.cc
  examples/kinova_jaco_arm/move_jaco_ee.cc
  examples/kinova_jaco_arm/run_controlled_jaco_demo.cc
  examples/kinova_jaco_arm/run_passive_jaco_demo.cc
  examples/kinova_jaco_arm/run_setpose_jaco_demo.cc
  manipulation/models/jaco_description/urdf/j2s7s300.urdf
Labels: status: commits are properly curated

#11845 Clean up MultipleShooting bindings and docs
  bindings/pydrake/systems/test/trajectory_optimization_test.py
  bindings/pydrake/systems/trajectory_optimization_py.cc
  systems/trajectory_optimization/multiple_shooting.h
Labels: status: single reviewer ok

#11871 Update CLion instructions
  .bazelproject
  doc/clion.rst
Labels: priority: high, status: single reviewer ok, team: dynamics

#11867 render_engine_vtk_test: Get rid of abuse of label colors
  geometry/render/test/render_engine_vtk_test.cc
Labels: priority: low, status: single reviewer ok
