Repository RobotLocomotion/drake, pull requests merged in 2019-05, with the labels that each got.

#11359 systems/lcm: Deprecate LcmAndVectorBaseTranslator
  systems/lcm/BUILD.bazel
  systems/lcm/connect_lcm_scope.cc
  systems/lcm/connect_lcm_scope.h
  systems/lcm/lcm_and_vector_base_translator.h
  systems/lcm/lcmt_drake_signal_translator.h
Labels: priority: low, status: single reviewer ok

#11361 pydrake: Restore the attic forwarding shims
  bindings/pydrake/attic/BUILD.bazel
  bindings/pydrake/attic/test/attic_forwarding_test.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/all.py
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/all.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_controllers_extra.py
  bindings/pydrake/systems/_sensors_extra.py
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/sensors_py.cc
Labels: priority: high, status: single reviewer ok

#11360 framework: Avoid non-determinism in algebraic loop detection
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
Labels: priority: high, status: single reviewer ok, type: build cop

#11329 Nuke macOS instructions for setting up CLion that break the build
  doc/clion.rst
Labels: configuration: mac, team: kitware, type: documentation

#11357 Update support matrix with full Mojave support
  doc/developers.rst
Labels: configuration: mac, team: kitware, type: documentation

#11340 signal_logger: Support scalar conversion
  systems/primitives/BUILD.bazel
  systems/primitives/signal_logger.cc
  systems/primitives/signal_logger.h
  systems/primitives/test/signal_logger_test.cc
Labels: priority: low

#11333 Refactors code from ImplicitEulerIntegrator into ImplicitIntegrator.
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/implicit_euler_integrator.h
  systems/analysis/implicit_integrator.h
Labels: status: squashing now

#11366 Fix formatting of support matrix
  doc/developers.rst
Labels: priority: low, status: single reviewer ok, team: kitware, type: documentation

#11369 runfiles: Fix argv0 handling on macOS
  common/find_runfiles.cc
Labels: configuration: mac, priority: high, status: single reviewer ok

#11356 Caching of inverse dynamics terms.
  examples/multibody/cart_pole/test/cart_pole_test.cc
  multibody/tree/body_node.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.cc
  multibody/tree/multibody_tree_system.h
Labels: status: commits are properly curated, team: dynamics, type: feature request

#11367 Migrate to new Bazel Python version API
  tools/workspace/pybind11/BUILD.bazel
Labels: configuration: bazel, configuration: python, priority: high, team: kitware, type: build cop

#11364 multibody/parsing: Support direct add of package.xml
  multibody/parsing/package_map.cc
  multibody/parsing/package_map.h
  multibody/parsing/test/package_map_test.cc
Labels: priority: low

#11345 solvers::Constraint accept sparsity pattern. Snopt uses this sparsity pattern
  solvers/constraint.cc
  solvers/constraint.h
  solvers/snopt_solver.cc
  solvers/snopt_solver_f2c.cc
  solvers/test/constraint_test.cc
  solvers/test/nonlinear_program_test.cc
  solvers/test/optimization_examples.cc
  solvers/test/optimization_examples.h
Labels: status: squashing now

#11327 quadrotor: Split QuadrotorGeometry from QuadrotorPlant
  bindings/pydrake/examples/quadrotor_py.cc
  bindings/pydrake/examples/test/quadrotor_test.py
  examples/pendulum/BUILD.bazel
  examples/pendulum/pendulum_geometry.cc
  examples/pendulum/pendulum_geometry.h
  examples/quadrotor/BUILD.bazel
  examples/quadrotor/quadrotor_geometry.cc
  examples/quadrotor/quadrotor_geometry.h
  examples/quadrotor/quadrotor_plant.cc
  examples/quadrotor/quadrotor_plant.h
  examples/quadrotor/run_quadrotor_lqr.cc
  examples/quadrotor/test/quadrotor_geometry_test.cc
  tools/install/libdrake/build_components.bzl
Labels: priority: low

#11377 Fix //tools/cc_toolchain:capture_cc for Bazel 0.25
  common/test/drake_assert_test_compile_variants.sh
  tools/cc_toolchain/BUILD.bazel
Labels: configuration: bazel, priority: high, status: single reviewer ok, team: kitware, type: build cop

#11371 Fix an ASan issue in cost_test.cc
  solvers/test/cost_test.cc
Labels: team: kitware, type: sanitizer-asan

#11388 Fix implicit instantiation of undefined template std::array from libc++
  geometry/query_results/surface_mesh.h
Labels: configuration: mac, priority: emergency, status: single reviewer ok, type: build cop

#11375 Migrate to new CcInfo, JavaInfo, and PyInfo Starlark APIs
  tools/install/install.bzl
  tools/skylark/pybind.bzl
Labels: configuration: bazel, priority: high, team: kitware, type: build cop, type: installation and distribution

#11393 pydrake: Remove unused imports
  bindings/pydrake/multibody/test/plant_test.py
Labels: priority: low, status: single reviewer ok

#11390 multibody/parsing: Stop using Isometry3
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_tinyxml_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
Labels: priority: low, status: do not merge, status: single reviewer ok

#11379 Autodiff support for the pairwise signed distance query
  geometry/geometry_state.h
  geometry/proximity/BUILD.bazel
  geometry/proximity/collision_filter_legacy.h
  geometry/proximity/distance_to_shape.h
  geometry/proximity/proximity_utilities.cc
  geometry/proximity/proximity_utilities.h
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/query_object.cc
  geometry/query_object.h
  geometry/query_results/signed_distance_pair.h
  geometry/test/proximity_engine_test.cc
  multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
  multibody/optimization/static_equilibrium_constraint.cc
  multibody/optimization/test/static_equilibrium_constraint_test.cc
Labels: status: squashing now

#11370 Performs a more robust zero-update check in implicit Euler integration.
  systems/analysis/BUILD.bazel
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/implicit_integrator.h
  systems/analysis/integrator_base.h
  systems/analysis/test/implicit_euler_integrator_test.cc
  systems/analysis/test/implicit_integrator_test.cc
  systems/analysis/test_utilities/robertson_system.h
Labels: status: squashing now

#11383 py systems: Split and hoist general header utilities
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/attic/multibody/BUILD.bazel
  bindings/pydrake/attic/multibody/rigid_body_plant_py.cc
  bindings/pydrake/automotive_py.cc
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/default_scalars_pybind.h
  bindings/pydrake/common/value_pybind.h
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/perception_py.cc
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/osqp_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/rendering_py.cc
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/systems_pybind.h
  bindings/pydrake/systems/test/test_util_py.cc
Labels: status: commits are properly curated

#11381 Mathprog maximizes geometric mean
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/gurobi_solver_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/scs_solver_test.cc
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/second_order_cone_program_examples.h
Labels: status: squashing now

#11399 Do not return struct from starlark rule implementation functions
  tools/workspace/cmake_configure_file.bzl
  tools/workspace/lcm/lcm.bzl
Labels: status: single reviewer ok

#11406 Replace usage of deprecated Starlark java provider with JavaInfo provider
  tools/install/install.bzl
  tools/skylark/drake_java.bzl
Labels: status: single reviewer ok

#11386 py: Add `numpy_compare` testing utilities
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/numpy_compare_test.py
  bindings/pydrake/common/test_utilities/BUILD.bazel
  bindings/pydrake/common/test_utilities/numpy_compare.py
  bindings/pydrake/pydrake_doxygen.h
  bindings/pydrake/test/algebra_test_util.py
  bindings/pydrake/test/autodiffutils_test.py
  bindings/pydrake/test/symbolic_test.py
Labels: status: commits are properly curated

#11395 Fix ASan problems in pose_aggregator_test.cc and normalize_vector.h
  math/normalize_vector.h
  systems/rendering/test/pose_aggregator_test.cc
Labels: priority: high, status: squashing now, team: kitware, type: sanitizer-asan

#11407 increase the tolerance on a scs_solver_test a little bit to make it pass on Mac CI.
  solvers/test/scs_solver_test.cc
  tools/dynamic_analysis/valgrind.supp
Labels: priority: high, status: squashing now

#11382 py eigen: Expose default scalars
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/common/test/numpy_compare_test.py
  bindings/pydrake/common/test_utilities/numpy_compare.py
Labels: status: commits are properly curated

#11398 Atlas passive sim.
  examples/atlas/BUILD.bazel
  examples/atlas/atlas_run_dynamics.cc
Labels: team: dynamics, type: feature request

#11416 add missing bindings for State<T> abstract values.
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: priority: high

#11420 Revert "add missing bindings for State<T> abstract values. "
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok

#11426 pydrake: Bind DependencyTicket accessors
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  systems/framework/system_base.h
Labels: priority: high, status: do not merge, status: single reviewer ok

#11427 Re-apply "add missing bindings for State<T> abstract values"
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: priority: medium, status: commits are properly curated

#11430 pydrake: Add bindings for Output prerequisites_of_calc
  bindings/pydrake/systems/framework_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
Labels: priority: high, status: single reviewer ok

#11428 solvers: Improve test latency via shards
  solvers/BUILD.bazel
  solvers/test/rotation_constraint_test.cc
Labels: priority: low, status: do not merge

#11348 Improve free body test for Evan's new integrator
  multibody/benchmarks/free_body/free_body.cc
  multibody/benchmarks/free_body/free_body.h
  multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc
Labels: priority: medium, status: squashing now, team: dynamics

#11440 add bindings for CalcDiscreteVariableUpdates.
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
Labels: priority: high, team: russ

#11434 workspace: Add missing snopt toolchain dependency
  tools/workspace/snopt/fortran-ubuntu.bzl
Labels: priority: high

#11443 valgrind: Consolidate and broaden some MOSEK suppressions
  tools/dynamic_analysis/valgrind.supp
Labels: priority: high, status: do not merge, type: build cop

#11442 Standardize comment style in minimum_distance_constraint.h.
  multibody/inverse_kinematics/minimum_distance_constraint.h
Labels: status: single reviewer ok

#11411 NLopt/IPOPT/SNOPT all handle cost/constraint with zero-size gradient.
  solvers/ipopt_solver.cc
  solvers/nlopt_solver.cc
  solvers/snopt_solver.cc
  solvers/snopt_solver_f2c.cc
  solvers/test/nonlinear_program_test.cc
  solvers/test/optimization_examples.cc
  solvers/test/optimization_examples.h
Labels: status: squashing now

#11400 Static equilibrium problem
  multibody/optimization/BUILD.bazel
  multibody/optimization/contact_wrench.h
  multibody/optimization/contact_wrench_evaluator.h
  multibody/optimization/static_equilibrium_constraint.cc
  multibody/optimization/static_equilibrium_problem.cc
  multibody/optimization/static_equilibrium_problem.h
  multibody/optimization/static_friction_cone_complementarity_constraint.cc
  multibody/optimization/static_friction_cone_complementarity_constraint.h
  multibody/optimization/test/optimization_with_contact_utilities.cc
  multibody/optimization/test/optimization_with_contact_utilities.h
  multibody/optimization/test/static_equilibrium_constraint_test.cc
  multibody/optimization/test/static_equilibrium_problem_test.cc
  multibody/optimization/test/static_friction_cone_complementarity_constraint_test.cc
Labels: status: squashing now

#11447 add bindings for AllocateDiscreteVariables
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
Labels: status: single reviewer ok

#11451 Correct usage of MatrixBase::head and ::tail
  multibody/optimization/contact_wrench_evaluator.h
Labels: priority: emergency, type: build cop

#11331 Adds label images to the RenderEngine
  geometry/render/BUILD.bazel
  geometry/render/render_engine.cc
  geometry/render/render_engine.h
  geometry/render/render_label.h
  geometry/render/test/render_engine_test.cc
  geometry/render/test/render_label_test.cc
  geometry/test_utilities/BUILD.bazel
  geometry/test_utilities/dummy_render_engine.h
Labels: status: squashing now

#11414 Removes more Isometry3. Adds operator*(RotationMatrix, SpatialVector).
  manipulation/planner/differential_inverse_kinematics.cc
  multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h
  multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.cc
  multibody/math/BUILD.bazel
  multibody/math/spatial_vector.h
  multibody/math/test/spatial_algebra_test.cc
  multibody/plant/test/external_forces_test.cc
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/inclined_plane_test.cc
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/body.h
  multibody/tree/body_node.h
  multibody/tree/frame.h
  multibody/tree/test/multibody_tree_test.cc
Labels: priority: medium, status: squashing now, team: dynamics, type: cleanup

#11269 Upgrade supported Gurobi version to 8.0.1
  CMakeLists.txt
  attic/multibody/approximate_ik.cc
  cmake/modules/FindGurobi.cmake
  doc/bazel.rst
  solvers/gurobi_solver.cc
  solvers/gurobi_solver.h
  solvers/solver_options.h
  solvers/test/mixed_integer_optimization_test.cc
  tools/dynamic_analysis/tsan.supp
  tools/workspace/gurobi/package-macos.BUILD.bazel.in
  tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in
  tools/workspace/gurobi/repository.bzl
Labels: team: kitware

#11460 Update buildcop playback about when to restart Mac nightly builds
  doc/buildcop.rst
Labels: team: kitware, type: continuous integration, type: documentation

#11444 Update to Bazel 0.25.2 recommended
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: configuration: bazel, team: kitware

#11459 add meshcat support to geometry inspector
  manipulation/util/geometry_inspector.py
Labels: priority: medium

#11465 Update drake-visualizer binary for Mac
  tools/workspace/drake_visualizer/repository.bzl
Labels: configuration: mac, priority: high, team: kitware

#11431 Contact modeling docs.
  multibody/plant/contact_model_doxygen.h
  multibody/plant/images/README.md
  multibody/plant/images/ideal_stiction.png
  multibody/plant/images/ideal_stiction.py
  multibody/plant/images/simple_contact.png
  multibody/plant/images/simple_contact.svg
  multibody/plant/images/stiction.py
  multibody/plant/images/stribeck.png
  multibody/plant/implicit_stribeck_solver.h
  multibody/plant/multibody_plant.h
Labels: priority: high, status: squashing now, team: dynamics, type: documentation, type: feature request

#11415 Adds missing call to AddAppliedExternalSpatialForces().
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/test/externally_applied_spatial_force_test.cc
Labels: priority: high, status: squashing now, team: dynamics, type: bug

#11464 Introduces API for the introspection of floating bodies.
  examples/atlas/atlas_run_dynamics.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_introspection_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/body.h
  multibody/tree/mobilizer.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree_topology.h
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/space_xyz_mobilizer.h
  multibody/tree/test/free_rotating_body_plant.h
  multibody/tree/test/free_rotating_body_test.cc
Labels: status: squashing now, team: dynamics, type: feature request

#11468 [proximity] Add support for signed distance to halfspace
  geometry/proximity/distance_to_point.h
  geometry/proximity/distance_to_shape.h
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/distance_to_point_test.cc
  geometry/proximity/test/distance_to_point_with_gradient_test.cc
  geometry/test/proximity_engine_test.cc
Labels: team: dynamics

#11479 Require at least bazel 0.25
  CMakeLists.txt
  WORKSPACE
Labels: configuration: bazel, team: kitware

#11472 adds hip torque to the compass gait.
  bindings/pydrake/examples/test/compass_gait_test.py
  examples/compass_gait/compass_gait.cc
  examples/compass_gait/compass_gait.h
  examples/compass_gait/simulate.cc
  examples/compass_gait/test/compass_gait_test.cc
Labels: priority: medium

#11483 Add flag_hack_label to semantics struct in clion environment and update documentation
  doc/clion.rst
  tools/clion/aspect.bzl
Labels: priority: high, team: kitware

#11471 Deprecate CalcRelativeFrameGeometricJacobian for CalcJacobianSpatialVelocity
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/multibody_tree_test.cc
Labels: priority: high, status: squashing now, team: dynamics

#11461 MinimumDistanceConstraint: Non-zero gradients at minimum distance.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/minimum_distance_constraint.cc
  multibody/inverse_kinematics/minimum_distance_constraint.h
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
Labels: status: squashing now

#11506 inverse_kinematics: Don't depend on particular solvers
  multibody/inverse_kinematics/BUILD.bazel
Labels: priority: high, status: single reviewer ok

#11499 Re-order context python bindings to match context.h
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: priority: medium

#11500 framework: Improve VectorSystem feedthrough documentation
  systems/framework/vector_system.h
Labels: priority: low, status: single reviewer ok

#11510 Add remaining bindings to Context
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok

#11504 Bring in CSDP build file
  solvers/BUILD.bazel
  solvers/csdp_solver.cc
  solvers/csdp_solver.h
  solvers/csdp_solver_common.cc
  solvers/csdp_solver_internal.h
  solvers/no_csdp.cc
  tools/BUILD.bazel
  tools/workspace/BUILD.bazel
  tools/workspace/csdp/BUILD.bazel
  tools/workspace/csdp/package.BUILD.bazel
  tools/workspace/csdp/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/github.bzl
Labels: status: squashing now

#11511 add python bindings for GetUniquePeriodicDiscreteUpdateAttribute
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok

#11512 common: Do not depend on math
  common/BUILD.bazel
  common/symbolic_formula.h
  common/symbolic_formula_cell.cc
  common/symbolic_formula_cell.h
  common/test/symbolic_formula_test.cc
  solvers/BUILD.bazel
Labels: priority: low

#11508 bugfix - Signed distance queries with a zero threshold lose results
  geometry/proximity/distance_to_point.h
  geometry/proximity/distance_to_shape.h
  geometry/test/proximity_engine_test.cc
Labels: team: dynamics, type: bug

#11515 Move MakeDrakeVisualizerProperties
  attic/multibody/rigid_body_plant/BUILD.bazel
  attic/multibody/rigid_body_plant/rigid_body_plant_bridge.cc
  automotive/automotive_simulator.cc
  examples/pendulum/BUILD.bazel
  examples/pendulum/pendulum_geometry.cc
  examples/scene_graph/BUILD.bazel
  examples/scene_graph/solar_system.cc
  geometry/dev/geometry_visualization.cc
  geometry/dev/geometry_visualization.h
  geometry/dev/test/geometry_visualization_test.cc
  geometry/geometry_roles.cc
  geometry/geometry_roles.h
  geometry/geometry_visualization.cc
  geometry/geometry_visualization.h
  geometry/test/geometry_visualization_test.cc
  manipulation/models/ycb/BUILD.bazel
  multibody/optimization/BUILD.bazel
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_urdf_geometry.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
Labels: priority: high

#11491 Build with -O0 for AddressSanitizer and LeakSanitizer
  tools/dynamic_analysis/bazel.rc
Labels: team: kitware

#11477 [render] Implementation of VTK-based RenderEngine (take 2)
  geometry/render/BUILD.bazel
  geometry/render/render_engine_vtk.cc
  geometry/render/render_engine_vtk.h
  geometry/render/render_engine_vtk_factory.cc
  geometry/render/render_engine_vtk_factory.h
  geometry/render/shaders/BUILD.bazel
  geometry/render/shaders/depth_shaders.h
  systems/sensors/BUILD.bazel
  systems/sensors/vtk_util.cc
  systems/sensors/vtk_util.h
Labels: priority: high, status: squashing now, team: dynamics

#11495 CalcBiasForPointsGeometryJacobianExpressedInWorld() -> CalcBiasForJacobianTranslationalVelocity()
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/multibody_tree_test.cc
Labels: priority: medium, status: squashing now, team: dynamics

#11509 Remove isometry from SpatialKinematicsPVA class.
  multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.cc
  multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc
  multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_inverse_dynamics_test.cc
  multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_kinematics_test.cc
  multibody/test_utilities/BUILD.bazel
  multibody/test_utilities/spatial_kinematics.h
Labels: status: squashing now, team: dynamics

#11516 Statically link osqp and qldl libraries and set visibility to hidden
  tools/workspace/osqp/package.BUILD.bazel
  tools/workspace/qdldl/package.BUILD.bazel
Labels: status: single reviewer ok, team: kitware

#11528 Do not use BLAS vendored with SNOPT/F2C
  tools/workspace/snopt/package.BUILD.bazel
Labels: team: kitware

#11526 Rewords message in CalcPointPairPenetrations() for MBP<AutoDiffXd>
  multibody/plant/multibody_plant.cc
Labels: team: dynamics, type: feature request

#11401 Add a default gravity field to MBP
  bindings/pydrake/examples/multibody/cart_pole_passive_simulation.py
  bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/systems/drawing_graphviz_example.py
  bindings/pydrake/systems/test/controllers_test.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/atlas/atlas_run_dynamics.cc
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  examples/multibody/acrobot/run_lqr.cc
  examples/multibody/bouncing_ball/make_bouncing_ball_plant.cc
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  examples/multibody/cart_pole/test/cart_pole_test.cc
  examples/multibody/cylinder_with_multicontact/make_cylinder_plant.cc
  examples/pendulum/print_symbolic_dynamics.cc
  examples/simple_gripper/simple_gripper.cc
  multibody/benchmarks/acrobot/make_acrobot_plant.cc
  multibody/benchmarks/inclined_plane/inclined_plane_plant.cc
  multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.cc
  multibody/benchmarks/pendulum/make_pendulum_plant.cc
  multibody/optimization/test/optimization_with_contact_utilities.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/applied_generalized_force_test.cc
  multibody/plant/test/box_test.cc
  multibody/plant/test/externally_applied_spatial_force_test.cc
  multibody/plant/test/joint_limits_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/test_utilities/floating_body_plant.cc
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/multibody_tree_creation_test.cc
  multibody/tree/test/tree_from_joints_test.cc
  multibody/tree/test/tree_from_mobilizers_test.cc
  multibody/tree/uniform_gravity_field_element.h
  systems/controllers/test/inverse_dynamics_test.cc
  systems/trajectory_optimization/test/direct_transcription_test.cc
Labels: status: commits are properly curated

#11533 Round up deprecation dates to first of the month
  bindings/pydrake/math_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
  geometry/geometry_frame.h
  math/rigid_transform.h
  multibody/plant/multibody_plant.h
  multibody/tree/fixed_offset_frame.h
  multibody/tree/weld_joint.h
  setup/mac/binary_distribution/install_prereqs.sh
  systems/framework/leaf_system.h
Labels: priority: low, status: single reviewer ok

#11530 Various docker-related fixes
  .dockerignore
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-xenial.txt
Labels: configuration: docker, status: commits are properly curated, team: kitware

#11505 Do not use BLAS vendored with SNOPT/Fortran
  tools/workspace/snopt/fortran-macos.bzl
  tools/workspace/snopt/fortran-ubuntu.bzl
  tools/workspace/snopt/package.BUILD.bazel
Labels: team: kitware

#11529 Fixes AddForceElement deprecation message
  bindings/pydrake/multibody/plant_py.cc
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree.h
Labels: status: single reviewer ok, team: dynamics, type: documentation

#11518 [render] Add the unit tests for RenderEngineVtk
  geometry/render/BUILD.bazel
  geometry/render/test/render_engine_vtk_test.cc
Labels: status: squashing now

#11525 Move generic code from MinDistConstraint to MinimumValueConstraint.
  doc/doxygen_extra.css
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/minimum_distance_constraint.cc
  multibody/inverse_kinematics/minimum_distance_constraint.h
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h
  multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
  solvers/BUILD.bazel
  solvers/minimum_value_constraint.cc
  solvers/minimum_value_constraint.h
  solvers/test/minimum_value_constraint_test.cc
  solvers/test_utilities/BUILD.bazel
  solvers/test_utilities/check_constraint_eval_nonsymbolic.cc
  solvers/test_utilities/check_constraint_eval_nonsymbolic.h
Labels: status: squashing now

#11547 switch to new solvers::Solve interface for global IK.
  attic/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc
  attic/multibody/dev/test/global_inverse_kinematics_feasible_posture_test.cc
  attic/multibody/dev/test/global_inverse_kinematics_reachable_test.cc
  attic/multibody/dev/test/global_inverse_kinematics_test.cc
  attic/multibody/dev/test/global_inverse_kinematics_test_util.cc
  attic/multibody/dev/test/global_inverse_kinematics_test_util.h
  attic/multibody/global_inverse_kinematics.cc
  attic/multibody/global_inverse_kinematics.h
Labels: priority: high

#11548 Add script for mirroring source archives to S3
  setup/mac/source_distribution/requirements.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  tools/workspace/BUILD.bazel
  tools/workspace/mirror_to_s3.py
Labels: team: kitware, type: continuous integration
