Repository RobotLocomotion/drake, pull requests merged in 2019-12, with the labels that each got.

#12425 Use ByteSizeLong instead of ByteSize for Protobuf 3.11.0 or above
  common/proto/call_python.cc
Labels: priority: high, type: build cop

#12427 Reordering the definitions and declarations in symbolic_expression.h
  common/symbolic_expression.h
Labels: status: single reviewer ok

#12428 Updates the documentation on the use of accuracy in the Context.
  systems/framework/context.h
Labels: status: single reviewer ok, team: dynamics, type: documentation

#12431 Remove deprecated methods (2019-12-01)
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/test/math_test.py
  common/proto/call_python.cc
  common/proto/call_python.h
  geometry/proximity/surface_mesh.h
  geometry/query_results/contact_surface.h
  geometry/shape_specification.h
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
Labels: priority: low, status: single reviewer ok

#12426 workspace: Update externals to latest
  common/text_logging.h
  tools/workspace/fmt/package-create-cps.py
  tools/workspace/fmt/package.BUILD.bazel
  tools/workspace/fmt/repository.bzl
  tools/workspace/ghc_filesystem/repository.bzl
  tools/workspace/octomap/BUILD.bazel
  tools/workspace/octomap/do_not_use_random_shuffle.patch
  tools/workspace/octomap/repository.bzl
Labels: priority: low, status: commits are properly curated, status: single reviewer ok

#12437 tutorials: Remove last cells from notebooks
  tutorials/dynamical_systems.ipynb
  tutorials/mathematical_program.ipynb
  tutorials/mathematical_program_multibody_plant.ipynb
  tutorials/rendering_multibody_plant.ipynb
  tutorials/solver_parameters.ipynb
Labels: status: single reviewer ok

#12447 Revert "workspace: Upgrade lcm to latest commit"
  tools/workspace/lcm/repository.bzl
Labels: priority: high, status: single reviewer ok

#12439 Add the lcm utility for planar manipuland.
  examples/planar_gripper/BUILD.bazel
  examples/planar_gripper/planar_manipuland_lcm.cc
  examples/planar_gripper/planar_manipuland_lcm.h
  examples/planar_gripper/test/planar_manipuland_lcm_test.cc
  lcmtypes/BUILD.bazel
  lcmtypes/lcmt_planar_manipuland_status.lcm
Labels: status: squashing now

#12442 proto: Use lcm encoding (not protobuf) for call_python
  common/proto/BUILD.bazel
  common/proto/call_python.cc
  common/proto/call_python.h
  common/proto/call_python_client.py
  common/proto/python_remote_message.proto
  lcmtypes/BUILD.bazel
  lcmtypes/lcmt_call_python.lcm
  lcmtypes/lcmt_call_python_data.lcm
Labels: priority: low

#12444 Fixes negative real time factors in Drake visualizer.
  tools/workspace/drake_visualizer/plugin/show_time.py
Labels: status: single reviewer ok

#12451 lcm: Add acceptance test to rule out IP address crosstalk
  lcm/test/drake_lcm_test.cc
Labels: priority: medium

#12412 Implements ABA forward dynamics.
  common/eigen_types.h
  multibody/math/spatial_force.h
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/acceleration_kinematics_cache.h
  multibody/tree/articulated_body_force_bias_cache.cc
  multibody/tree/articulated_body_force_bias_cache.h
  multibody/tree/articulated_body_inertia.h
  multibody/tree/articulated_body_inertia_cache.h
  multibody/tree/body_node.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.cc
  multibody/tree/multibody_tree_system.h
  multibody/tree/test/articulated_body_algorithm_test.cc
Labels: team: dynamics, type: feature request

#12458 Pass --no-lock to brew bundle
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
Labels: team: kitware

#12436 Adds missing operators to SpatialVector
  multibody/math/spatial_acceleration.h
  multibody/math/spatial_force.h
  multibody/math/spatial_momentum.h
  multibody/math/spatial_vector.h
  multibody/math/spatial_velocity.h
  multibody/math/test/spatial_algebra_test.cc
Labels: team: dynamics, type: feature request

#12457 workspace: Upgrade lcm to latest commit
  tools/workspace/lcm/repository.bzl
Labels: priority: low, status: single reviewer ok

#12450 workspace: Remove unused protobuf (but not libprotobuf)
  BUILD.bazel
  attic/multibody/BUILD.bazel
  attic/multibody/alias_groups.proto
  attic/multibody/rigid_body_tree_alias_groups.h
  common/proto/BUILD.bazel
  setup/ubuntu/source_distribution/packages-bionic.txt
  third_party/BUILD.bazel
  third_party/com_github_google_protobuf/LICENSE
  third_party/com_github_google_protobuf/README.md
  third_party/com_github_google_protobuf/protobuf-ubsan-fixup.h
  third_party/com_github_google_protobuf/protobuf.bzl
  tools/lint/cpplint.bzl
  tools/skylark/BUILD.bazel
  tools/skylark/drake_proto.bzl
  tools/skylark/drake_proto_ubsan_fix.py
  tools/vector_gen/BUILD.bazel
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/named_vector.proto
  tools/vector_gen/named_vector_pb2.py
  tools/workspace/com_google_protobuf/BUILD.bazel
  tools/workspace/com_google_protobuf/package.BUILD.bazel
  tools/workspace/com_google_protobuf/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/libprotobuf/repository.bzl
  tools/workspace/protoc/BUILD.bazel
  tools/workspace/protoc/repository.bzl
Labels: priority: medium

#12462 Make effective use of SpatialAcceleration's addition operators
  multibody/tree/body_node.h
Labels: status: single reviewer ok, team: dynamics, type: cleanup

#12452 'Fix' sphinx to get __init__ documentation.
  bindings/pydrake/doc/pydrake_sphinx_extension.py
Labels: status: single reviewer ok, status: squashing now

#12461 Move jupyter notebook and ipywidgets to binary prerequisite install
  setup/mac/binary_distribution/requirements.txt
  setup/mac/source_distribution/requirements.txt
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
Labels: status: single reviewer ok

#12465 gitattributes: Update for modern bazel spellings
  .gitattributes
Labels: priority: medium, status: single reviewer ok

#12377 Define and use a toolchain for Python and use rules_python for build rules
  BUILD.bazel
  CMakeLists.txt
  WORKSPACE
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/solvers/BUILD.bazel
  cmake/bazel.rc.in
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/planar_gripper/BUILD.bazel
  tools/BUILD.bazel
  tools/bazel.rc
  tools/external_data/bazel_external_data/BUILD.bazel
  tools/external_data/external_data.bzl
  tools/install/BUILD.bazel
  tools/install/dummy/BUILD.bazel
  tools/install/install.bzl
  tools/lint/python_lint.bzl
  tools/macos.bazelrc
  tools/py_toolchain/BUILD.bazel
  tools/py_toolchain/interpreter_paths.bzl
  tools/skylark/BUILD.bazel
  tools/skylark/alias.bzl
  tools/skylark/drake_py.bzl
  tools/skylark/py.bzl
  tools/skylark/pybind.bzl
  tools/ubuntu-bionic.bazelrc
  tools/workspace/BUILD.bazel
  tools/workspace/clang_cindex_python3/package.BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/drake_visualizer/BUILD.bazel
  tools/workspace/drake_visualizer/plugin/BUILD.bazel
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/github3_py/package.BUILD.bazel
  tools/workspace/godotengine/package.BUILD.bazel
  tools/workspace/lcm/lcm.bzl
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/meshcat_python/package.BUILD.bazel
  tools/workspace/meshcat_python/repository.bzl
  tools/workspace/numpy/repository.bzl
  tools/workspace/optitrack_driver/repository.bzl
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pycodestyle/package.BUILD.bazel
  tools/workspace/pycps/package.BUILD.bazel
  tools/workspace/pypi.bzl
  tools/workspace/python/BUILD.bazel
  tools/workspace/python/check_bazel_python.py
  tools/workspace/python/repository.bzl
  tools/workspace/rules_python/BUILD.bazel
  tools/workspace/rules_python/repository.bzl
  tools/workspace/semantic_version/package.BUILD.bazel
  tools/workspace/styleguide/package.BUILD.bazel
  tools/workspace/uritemplate_py/package.BUILD.bazel
  tutorials/BUILD.bazel
Labels: configuration: python, status: commits are properly curated, team: kitware

#12467 Un-pin sphinx for OSX
  bindings/pydrake/doc/pydrake_sphinx_extension.py
  setup/mac/source_distribution/requirements.txt
Labels: configuration: mac, status: single reviewer ok, team: kitware

#12463 Reverses the surface normal convention in ContactSurface.
  geometry/query_results/contact_surface.h
  multibody/hydroelastics/contact_surface_from_level_set.h
  multibody/hydroelastics/test/contact_surface_from_level_set_test.cc
  multibody/plant/hydroelastic_traction_calculator.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
Labels: status: squashing now

#12481 pydrake mbp: Add bindings for RevoluteSpring
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok

#12486 Reverts #11560
  bindings/pydrake/manipulation/simple_ui.py
Labels: status: single reviewer ok

#12488 Revert "Adding drake contact material properties to sdf/urdf parsing"
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/scene_graph/simple_contact_surface_vis.cc
  geometry/geometry_roles.h
  geometry/proximity_properties.cc
  geometry/proximity_properties.h
  geometry/test/proximity_properties_test.cc
  multibody/parsing/detail_scene_graph.cc
  multibody/parsing/detail_scene_graph.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok, type: address-leak-sanitizer, type: build cop

#12402 install: Add drake_bazel_installed support
  BUILD.bazel
  tools/install/bazel/BUILD.bazel
  tools/install/bazel/README.md
  tools/install/bazel/drake.BUILD.bazel
  tools/install/bazel/drake__bindings__pydrake.BUILD.bazel
  tools/install/bazel/drake__common.BUILD.bazel
  tools/install/bazel/drake__examples.BUILD.bazel
  tools/install/bazel/drake__manipulation.BUILD.bazel
  tools/install/bazel/generate_installed_files_manifest.bzl
  tools/install/bazel/repo_gen.py
  tools/install/bazel/repo_template.bzl
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/install/install.bzl
Labels: priority: low

#12477 tools: Add relnotes helper tool
  tools/dev/BUILD.bazel
  tools/dev/relnotes.py
Labels: priority: medium

#12487 workspace: Upgrade fmt to latest release 6.1.2
  common/text_logging.h
  tools/workspace/fmt/repository.bzl
Labels: priority: medium, status: single reviewer ok

#12492 install: Disable drake_bazel_installed test on macOS
  tools/install/bazel/test/drake_bazel_installed_test.py
Labels: configuration: mac, priority: emergency, status: single reviewer ok

#12491 Updated parsing of hydroelastic properties
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/scene_graph/simple_contact_surface_vis.cc
  geometry/geometry_roles.h
  geometry/proximity_properties.cc
  geometry/proximity_properties.h
  geometry/test/proximity_properties_test.cc
  multibody/parsing/detail_scene_graph.cc
  multibody/parsing/detail_scene_graph.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok, status: squashing now

#12474 doc: Add release notes v0.13.0
  doc/release_notes/release_notes.rst
  doc/release_notes/v0.13.0.rst
Labels: priority: high, status: single reviewer ok

#12494 Fixing Mac CI failure.
  examples/planar_gripper/planar_gripper_common.cc
Labels: status: single reviewer ok

#12499 More helpful message on joint limit support in MBP
  multibody/plant/multibody_plant.cc
Labels: status: single reviewer ok

#12472 Add Dockerfile for Binder
  .binder/.dockerignore
  .binder/Dockerfile
  .binder/README.md
  .binder/binder-entrypoint
  doc/index.rst
  tools/install/dockerhub/README.md
  tutorials/README.md
  tutorials/dynamical_systems.ipynb
  tutorials/mathematical_program.ipynb
  tutorials/mathematical_program_multibody_plant.ipynb
  tutorials/rendering_multibody_plant.ipynb
Labels: team: kitware

#12504 manipulation, multibody, perception: Change context.FixInputPort() to port.FixValue()
  manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
  manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc
  manipulation/kuka_iiwa/test/iiwa_status_receiver_test.cc
  manipulation/kuka_iiwa/test/iiwa_status_sender_test.cc
  manipulation/perception/test/optitrack_pose_extractor_test.cc
  manipulation/perception/test/pose_smoother_test.cc
  manipulation/planner/test/robot_plan_interpolator_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_controller_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_lcm_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_trajectory_generator_test.cc
  multibody/constraint/test/constraint_solver_test.cc
  multibody/plant/test/box_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/joint_limits_test.cc
  multibody/plant/test/multibody_plant_symbolic_test.cc
  multibody/plant/test/multibody_plant_test.cc
  perception/test/depth_image_to_point_cloud_test.cc
Labels: status: commits are properly curated, status: single reviewer ok

#12510 Fix Binder Dockerfile for Docker versions before 19.03
  .binder/Dockerfile
Labels: priority: high, status: single reviewer ok, team: kitware

#12495 Parse the collision filter group for urdfs
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/urdf_parser_test/collision_filter_group_parsing_test.urdf
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: team: dynamics

#12513 Add binding for RegisterRgbdSensor in manipulation station.
  bindings/pydrake/examples/manipulation_station_py.cc
Labels: status: single reviewer ok
