Repository RobotLocomotion/drake, pull requests merged in 2019-08, with the labels that each got.

#11840 lcm: Remove deprecated methods (2019-08)
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/test/lcm_test.py
  lcm/BUILD.bazel
  lcm/drake_lcm.cc
  lcm/drake_lcm.h
  lcm/lcm_receive_thread.cc
  lcm/lcm_receive_thread.h
  lcm/test/drake_lcm_thread_test.cc
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_and_vector_base_translator.cc
  systems/lcm/lcm_and_vector_base_translator.h
  systems/lcm/lcm_driven_loop.cc
  systems/lcm/lcm_driven_loop.h
  systems/lcm/lcmt_drake_signal_translator.cc
  systems/lcm/lcmt_drake_signal_translator.h
  systems/lcm/test/lcm_driven_loop_test.cc
Labels: priority: low, status: single reviewer ok

#11841 common: Remove deprecated methods (2019-08)
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/test/all_test.py
  common/BUILD.bazel
  common/find_resource.cc
  common/find_resource.h
  common/find_resource_deprecated.cc
  common/resource_tool.cc
  common/test/find_resource_test.cc
  common/test/resource_tool_installed_test.py
Labels: priority: low, status: single reviewer ok

#11842 systems: Remove deprecated methods (2019-08)
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/systems_pybind.h
  bindings/pydrake/systems/test/custom_test.py
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/test/leaf_system_test.cc
Labels: priority: low

#11843 multibody: Remove deprecated methods (2019-08)
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/test/geometry_test.py
  geometry/frame_kinematics_vector.cc
  geometry/frame_kinematics_vector.h
  geometry/test/frame_kinematics_vector_test.cc
  multibody/math/spatial_vector.h
  multibody/math/test/spatial_algebra_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: priority: low, status: single reviewer ok

#11887 Remove deprecated lines from prerequisites install script for macOS
  setup/mac/binary_distribution/install_prereqs.sh
Labels: configuration: mac, status: single reviewer ok, team: kitware

#11882 workspace: Update externals to latest
  tools/workspace/fcl/BUILD.bazel
  tools/workspace/fcl/package.BUILD.bazel
  tools/workspace/fcl/repository.bzl
  tools/workspace/fcl/version-from-xml.sed
  tools/workspace/json/repository.bzl
  tools/workspace/meshcat/repository.bzl
  tools/workspace/pycps/repository.bzl
Labels: priority: low, status: commits are properly curated

#11886 snopt: Use gfortran mode by default, not f2c
  doc/bazel.rst
  solvers/BUILD.bazel
  solvers/snopt_solver_f2c.cc
Labels: priority: medium

#11869 Stripping out Isometry3 from geometry/
  attic/manipulation/util/frame_pose_tracker.cc
  attic/multibody/rigid_body_plant/rigid_body_plant_bridge.cc
  bindings/pydrake/test/geometry_test.py
  examples/contact_model/bowling_ball.cc
  examples/pendulum/pendulum_geometry.cc
  examples/planar_gripper/gripper_brick.cc
  examples/quadrotor/quadrotor_geometry.cc
  examples/scene_graph/bouncing_ball_plant.cc
  examples/scene_graph/solar_system.cc
  examples/scene_graph/solar_system.h
  geometry/BUILD.bazel
  geometry/frame_kinematics_vector.cc
  geometry/frame_kinematics_vector.h
  geometry/geometry_instance.cc
  geometry/geometry_instance.h
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/geometry_visualization.cc
  geometry/internal_geometry.cc
  geometry/internal_geometry.h
  geometry/proximity/distance_to_point.h
  geometry/proximity/distance_to_shape.h
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/distance_to_point_test.cc
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/query_object.cc
  geometry/query_object.h
  geometry/render/render_engine.h
  geometry/scene_graph.cc
  geometry/scene_graph_inspector.h
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/test/frame_kinematics_vector_test.cc
  geometry/test/geometry_instance_test.cc
  geometry/test/geometry_state_test.cc
  geometry/test/geometry_visualization_test.cc
  geometry/test/proximity_engine_test.cc
  geometry/test/query_object_test.cc
  geometry/test/scene_graph_inspector_test.cc
  geometry/test/scene_graph_test.cc
  geometry/test/shape_specification_test.cc
  geometry/test/utilities_test.cc
  geometry/utilities.h
  multibody/inverse_kinematics/distance_constraint.cc
  multibody/inverse_kinematics/minimum_distance_constraint.cc
  multibody/optimization/manipulator_equation_constraint.cc
  multibody/optimization/sliding_friction_complementarity_constraint.cc
  multibody/optimization/static_equilibrium_constraint.cc
  multibody/optimization/static_equilibrium_problem.cc
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/plant/test/multibody_plant_test.cc
  systems/rendering/render_pose_to_geometry_pose.cc
  systems/sensors/test/optitrack_sender_test.cc
Labels: status: squashing now

#11889 Revert "snopt: Use gfortran mode by default, not f2c"
  doc/bazel.rst
  solvers/BUILD.bazel
  solvers/snopt_solver_f2c.cc
Labels: priority: emergency, status: single reviewer ok

#11892 parsing: Fix asan error in unit test
  multibody/parsing/test/detail_scene_graph_test.cc
Labels: priority: emergency, status: single reviewer ok, type: address-leak-sanitizer

#11866 pydrake: Add `ParamInit` and add a focused test for `pydrake_pybind`
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/manipulation/planner_py.cc
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  bindings/pydrake/systems/trajectory_optimization_py.cc
  bindings/pydrake/test/_pydrake_pybind_test_extra.py
  bindings/pydrake/test/geometry_test.py
  bindings/pydrake/test/pydrake_pybind_test.cc
  tools/skylark/pybind.bzl
Labels: status: commits are properly curated

#11893 gfortran: Ensure caching respects compiler binary
  tools/workspace/gfortran/repository.bzl
Labels: priority: high

#11891 snopt: Use gfortran mode by default, not f2c
  doc/bazel.rst
  solvers/BUILD.bazel
  solvers/snopt_solver_f2c.cc
Labels: priority: medium, status: single reviewer ok

#11879 rgbd_sensor: Support setting separate properties for color and depth
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  systems/sensors/rgbd_sensor.cc
  systems/sensors/rgbd_sensor.h
  systems/sensors/test/rgbd_sensor_test.cc
Labels: status: commits are properly curated

#11900 Remove MATLAB support
  CMakeLists.txt
  cmake/bazel.rc.in
  common/README.md
  doc/buildcop.rst
  doc/code_style_guide.rst
  doc/developers.rst
  doc/from_source.rst
  doc/index.rst
  doc/matlab_bindings.rst
  matlab/BUILD.bazel
  matlab/CMakeLists.txt
  matlab/addpath_drake.m
  matlab/call_matlab_client.cc
  matlab/cmake/flags.cmake
  matlab/cmake/functions.cmake
  matlab/cmake/packages.cmake
  matlab/test/CMakeLists.txt
  matlab/test/call_matlab_test.rpc
  third_party/com_kitware_gitlab_cmake_cmake/3.10/Modules/FindMatlab.cmake
  third_party/com_kitware_gitlab_cmake_cmake/3.10/Modules/MatlabTestsRedirect.cmake
  tools/install/install.py.in
  tools/lint/clang_format_includes.py
  tools/skylark/drake_cc.bzl
Labels: configuration: matlab, team: kitware

#11877 Brick static equilibrium constraint
  examples/planar_gripper/BUILD.bazel
  examples/planar_gripper/brick_static_equilibrium_constraint.cc
  examples/planar_gripper/brick_static_equilibrium_constraint.h
  examples/planar_gripper/gripper_brick.cc
  examples/planar_gripper/gripper_brick.h
  examples/planar_gripper/gripper_brick_planning_constraint_helper.cc
  examples/planar_gripper/gripper_brick_planning_constraint_helper.h
  examples/planar_gripper/test/brick_static_equilibrium_constraint_test.cc
  examples/planar_gripper/test/gripper_brick_planning_constraint_helper_test.cc
  examples/planar_gripper/test/gripper_brick_test.cc
Labels: status: squashing now

#11905 py systems: Remove 2019-06-01 deprecations
  bindings/pydrake/attic/BUILD.bazel
  bindings/pydrake/attic/test/attic_forwarding_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_controllers_extra.py
  bindings/pydrake/systems/_sensors_extra.py
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/sensors_py.cc
Labels: status: single reviewer ok

#11899 skylark: disable_in_compilation_mode_dbg checks lint
  examples/schunk_wsg/test/schunk_wsg_lift_test.cc
  tools/skylark/drake_cc.bzl
Labels: priority: low

#11903 rigid_transform: Add Matrix4 construction
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
  common/test_utilities/expect_throws_message.h
  math/rigid_transform.h
  math/rotation_matrix.h
  math/test/rigid_transform_test.cc
  math/test/rotation_matrix_test.cc
Labels: status: commits are properly curated

#11862 Migrate pose_smoother_cc towards RigidTransform
  manipulation/perception/pose_smoother.cc
Labels: priority: low, status: squashing now, team: dynamics

#11909 Remove MATLAB-specific code from call_matlab
  common/proto/BUILD.bazel
  common/proto/call_matlab.cc
  common/proto/call_matlab.h
  common/proto/call_python.cc
  common/proto/test/call_matlab_test.cc
Labels: status: single reviewer ok, team: kitware, type: cleanup

#10811 doc: Add instructions for adding model artifacts
  doc/developers.rst
  doc/model_version_control.rst
Labels: priority: low, status: squashing now

#11911 doc: Fix formatting for link to old MATLAB tag
  doc/from_source.rst
Labels: configuration: matlab, status: single reviewer ok

#11754 Adds error control to the Radau integrator.
  systems/analysis/BUILD.bazel
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/implicit_integrator.h
  systems/analysis/integrator_base.h
  systems/analysis/radau_integrator.h
  systems/analysis/test/radau_integrator_test.cc
  systems/analysis/test_utilities/quadratic_scalar_system.h
Labels: status: squashing now

#11915 Add a link to Zhaoyuan Gu's Drake tutorial to gallery page
  doc/gallery.rst
Labels: priority: high, team: dynamics, type: documentation

#11912 Use ipopt from homebrew-core
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/install_prereqs.sh
  tools/workspace/ipopt/repository.bzl
Labels: configuration: mac, status: single reviewer ok, team: kitware

#11919 Do not classify clang warnings as errors during CMake build
  CTestCustom.cmake.in
Labels: team: kitware, type: continuous integration

#11927 Update credits.rst
  doc/credits.rst
Labels: status: single reviewer ok

#11930 doxygen: Provide better errors for bad arguments
  doc/documentation_instructions.rst
  doc/doxygen_main.py
Labels: priority: low

#11940 Do not include dreal/dreal.h in dreal_solver.h
  solvers/dreal_solver.cc
  solvers/dreal_solver.h
  solvers/test/dreal_solver_test.cc
Labels: priority: high

#11929 py math, eigen_geometry: Address follow-up comments
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/test/math_test.py
Labels: priority: low

#11942 Add no_dreal configuration to make the dReal solver optional
  solvers/BUILD.bazel
  solvers/no_dreal.cc
  solvers/test/dreal_solver_test.cc
  tools/BUILD.bazel
  tools/install/libdrake/BUILD.bazel
  tools/workspace/BUILD.bazel
Labels: priority: high, status: commits are properly curated, team: kitware

#11945 Fixes for various no_{solver} configurations
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/test/nlopt_solver_test.py
  bindings/pydrake/solvers/test/scs_solver_test.py
  solvers/test/mathematical_program_result_test.cc
  solvers/test/scs_solver_test.cc
Labels: team: kitware

#11943 Use alpha value from diffuse color specification
  geometry/render/render_engine_vtk.cc
  geometry/render/render_engine_vtk_factory.h
  geometry/render/test/render_engine_vtk_test.cc
Labels: status: squashing now

#11922 Create new RigidTransform constructors for 3x4 matrix, 4x4 matrix, and related Eigen expressions.
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
  math/test/rotation_matrix_test.cc
Labels: priority: medium, status: squashing now, team: dynamics

#11934 Contact surface pose change
  geometry/proximity/mesh_intersection.h
  geometry/proximity/surface_mesh.h
  geometry/proximity/test/contact_surface_test.cc
  geometry/proximity/test/mesh_intersection_test.cc
  geometry/query_results/contact_surface.h
  multibody/hydroelastics/hydroelastic_engine.cc
  multibody/hydroelastics/hydroelastic_engine.h
  multibody/hydroelastics/test/hydroelastic_engine_test.cc
  multibody/plant/hydroelastic_traction_calculator.cc
  multibody/plant/hydroelastic_traction_calculator.h
  multibody/plant/test/hydroelastic_traction_test.cc
Labels: status: squashing now

#11972 snopt: Silence build warnings
  tools/workspace/snopt/fortran-ubuntu.bzl
  tools/workspace/snopt/package.BUILD.bazel
Labels: priority: low, status: commits are properly curated

#11976 py math: Support pickling
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/common/cpp_template.py
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/test/cpp_template_test.py
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/doc/pydrake_sphinx_extension.py
  bindings/pydrake/math_py.cc
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/systems/scalar_conversion.py
  bindings/pydrake/test/autodiffutils_test.py
  bindings/pydrake/test/math_test.py
Labels: status: commits are properly curated

#11985 Install jupyter from pip on macOS
  setup/mac/source_distribution/Brewfile
  setup/mac/source_distribution/requirements.txt
Labels: configuration: mac, team: kitware

#11981 common: Provide a stub for find_runfiles
  common/BUILD.bazel
  common/find_runfiles_stub.cc
  common/test/find_runfiles_stub_test.cc
Labels: priority: low

#11950 pybind11: Merge latest upstream
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok

#11989 py: Add test utilities for checking pickle-ability
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/test/cpp_template_test.py
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/common/test_utilities/BUILD.bazel
  bindings/pydrake/common/test_utilities/pickle_compare.py
  bindings/pydrake/test/autodiffutils_test.py
  bindings/pydrake/test/math_test.py
Labels: status: single reviewer ok

#11988 Update recommended bazel version to 0.29
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: status: single reviewer ok, team: kitware

#11994 Remove ospray test from thread sanitizer -- it uses TBB
  geometry/render/BUILD.bazel
Labels: priority: high, status: single reviewer ok, type: build cop, type: thread-sanitizer

#11971 pydrake doc: Add style guide for `keep_alive` comments
  bindings/pydrake/attic/multibody/rigid_body_plant_py.cc
  bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
  bindings/pydrake/attic/systems/controllers_py.cc
  bindings/pydrake/attic/systems/sensors_py.cc
  bindings/pydrake/automotive_py.cc
  bindings/pydrake/examples/acrobot_py.cc
  bindings/pydrake/examples/quadrotor_py.cc
  bindings/pydrake/maliput/api_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/pydrake_doxygen.h
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/sensors_py.cc
Labels: status: commits are properly curated

#11901 Hydroelastic contact surface visualization
  attic/multibody/rigid_body_plant/BUILD.bazel
  attic/multibody/rigid_body_plant/contact_results_to_lcm.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
  examples/valkyrie/BUILD.bazel
  geometry/proximity/mesh_field.h
  geometry/proximity/test/contact_surface_test.cc
  geometry/proximity/test/mesh_intersection_test.cc
  geometry/query_results/contact_surface.h
  lcmtypes/BUILD.bazel
  lcmtypes/lcmt_contact_results_for_viz.lcm
  lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm
  lcmtypes/lcmt_hydroelastic_contact_surface_tri_for_viz.lcm
  lcmtypes/lcmt_point_pair_contact_info_for_viz.lcm
  multibody/hydroelastics/test/hydroelastic_engine_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/contact_results_to_lcm.h
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/hydroelastic_traction_calculator.cc
  multibody/plant/hydroelastic_traction_calculator.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/box_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/hydroelastic_traction_test.cc
  tools/workspace/drake_visualizer/plugin/BUILD.bazel
  tools/workspace/drake_visualizer/plugin/show_hydroelastic_contact_surface.py
  tools/workspace/drake_visualizer/plugin/show_point_pair_contact.py
  tools/workspace/drake_visualizer/plugin/show_time.py
  tools/workspace/drake_visualizer/plugin/use_builtin_scripts.py
Labels: status: squashing now

#11980 render: Mark OSPRay test as flaky
  geometry/render/BUILD.bazel
Labels: status: squashing now

#11953 Collapse call_matlab into call_python
  common/proto/BUILD.bazel
  common/proto/call_matlab.cc
  common/proto/call_matlab.h
  common/proto/call_python.cc
  common/proto/call_python.h
  common/proto/call_python_client.py
  common/proto/matlab_rpc.proto
  common/proto/python_remote_message.proto
Labels: configuration: matlab, configuration: python, team: kitware
