Repository RobotLocomotion/drake, pull requests merged in 2019-03, with the labels that each got.

#10771 manipulation: Remove deprecated IIWA and WSG LCM ports
  examples/kuka_iiwa_arm/iiwa_lcm.h
  manipulation/kuka_iiwa/BUILD.bazel
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.h
  manipulation/kuka_iiwa/internal_iiwa_command_translator.cc
  manipulation/kuka_iiwa/internal_iiwa_command_translator.h
  manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
  manipulation/schunk_wsg/BUILD.bazel
  manipulation/schunk_wsg/gen/schunk_wsg_command.cc
  manipulation/schunk_wsg/gen/schunk_wsg_command.h
  manipulation/schunk_wsg/schunk_wsg_controller.cc
  manipulation/schunk_wsg/schunk_wsg_controller.h
  manipulation/schunk_wsg/schunk_wsg_lcm.cc
  manipulation/schunk_wsg/schunk_wsg_lcm.h
Labels: priority: backlog, status: ready to merge

#10768 Remove deprecated methods (2019-03)
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/multibody_tree_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/test/all_test.py
  examples/multibody/bouncing_ball/bouncing_ball_run_dynamics.cc
  lcmtypes/BUILD.bazel
  manipulation/planner/differential_inverse_kinematics.cc
  manipulation/planner/differential_inverse_kinematics.h
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
  multibody/multibody_tree/BUILD.bazel
  multibody/multibody_tree/implicit_stribeck/BUILD.bazel
  multibody/multibody_tree/joints/BUILD.bazel
  multibody/multibody_tree/math/BUILD.bazel
  multibody/multibody_tree/multibody_plant/BUILD.bazel
  multibody/multibody_tree/parsing/BUILD.bazel
  multibody/parsing/BUILD.bazel
  multibody/parsing/package_map.h
  multibody/parsing/parser.h
  multibody/parsing/sdf_parser.h
  multibody/parsing/urdf_parser.h
  multibody/plant/contact_info.h
  multibody/plant/contact_results.h
  multibody/plant/contact_results_to_lcm.h
  multibody/plant/coulomb_friction.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/rigid_body_plant/visualization/README
  multibody/rigid_body_plant/visualization/contact_viz.py
  multibody/rigid_body_plant/visualization/show_frames.py
  multibody/rigid_body_plant/visualization/show_time.py
  multibody/tree/acceleration_kinematics_cache.h
  multibody/tree/articulated_body_inertia_cache.h
  multibody/tree/mobilizer.h
  multibody/tree/mobilizer_impl.h
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_indexes.h
  multibody/tree/multibody_tree_system.h
  multibody/tree/multibody_tree_topology.h
  multibody/tree/position_kinematics_cache.h
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/revolute_mobilizer.h
  multibody/tree/space_xyz_mobilizer.h
  multibody/tree/test/frames_test.cc
  multibody/tree/velocity_kinematics_cache.h
  multibody/tree/weld_mobilizer.h
  systems/controllers/inverse_dynamics.cc
  systems/controllers/inverse_dynamics.h
  systems/controllers/inverse_dynamics_controller.h
  systems/sensors/visualization/BUILD.bazel
  systems/sensors/visualization/show_images.py
  tools/install/libdrake/build_components.bzl
  tools/lint/python_lint.bzl
  tools/workspace/drake_visualizer/plugin/__init__.py
Labels: priority: backlog, status: ready to merge

#10794 common: Restrict which RandomGenerator APIs we promise
  common/BUILD.bazel
  common/random.cc
  common/random.h
  common/test/random_test.cc
Labels: priority: low, status: ready to merge

#10793 framework: Swap template params of MyVector<T,N>
  common/test/value_test.cc
  systems/framework/test/basic_vector_test.cc
  systems/framework/test/continuous_state_test.cc
  systems/framework/test/input_port_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/output_port_test.cc
  systems/framework/test/system_output_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/userscalar_acceptance_test.cc
  systems/framework/test_utilities/my_vector.h
  systems/lcm/test/custom_drake_signal_translator.h
  systems/primitives/test/multiplexer_test.cc
Labels: priority: backlog, status: do not merge

#10790 Add date to DRAKE_DEPRECATED macro
  attic/multibody/joints/drake_joint.h
  attic/multibody/joints/fixed_axis_one_dof_joint.h
  attic/multibody/joints/fixed_joint.h
  attic/multibody/joints/quaternion_ball_joint.h
  attic/multibody/joints/quaternion_floating_joint.h
  attic/multibody/joints/roll_pitch_yaw_floating_joint.h
  attic/multibody/kinematics_cache.h
  attic/multibody/parsers/urdf_parser.h
  attic/multibody/rigid_body.h
  attic/multibody/rigid_body_tree.h
  attic/systems/controllers/rbt_inverse_dynamics.h
  attic/systems/controllers/rbt_inverse_dynamics_controller.h
  bindings/pydrake/common/test/deprecation_example/cc_module_py.cc
  common/BUILD.bazel
  common/drake_deprecated.h
  common/drake_path.h
  common/test/drake_deprecated_test.cc
  doc/Doxyfile_CXX.in
  examples/manipulation_station/manipulation_station.h
  geometry/geometry_set.h
  lcm/translator_base.h
  manipulation/kuka_iiwa/iiwa_command_receiver.h
  manipulation/kuka_iiwa/iiwa_command_sender.h
  manipulation/kuka_iiwa/iiwa_status_receiver.h
  manipulation/kuka_iiwa/iiwa_status_sender.h
  multibody/tree/joint.h
  solvers/binding.h
  solvers/mathematical_program.h
  solvers/mathematical_program_result.h
  solvers/solver_interface.h
  solvers/solver_result.h
  systems/framework/abstract_values.h
  systems/framework/continuous_state.h
  systems/framework/discrete_values.h
  systems/framework/output_port.h
  systems/framework/state.h
  systems/framework/system_constraint.h
  systems/framework/value.h
  systems/lcm/lcm_publisher_system.h
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/lcm_translator_dictionary.h
  systems/lcm/translator_system.h
  systems/primitives/constant_value_source.h
  systems/rendering/pose_stamped_t_pose_vector_translator.h
  systems/trajectory_optimization/direct_collocation.h
  systems/trajectory_optimization/direct_transcription.h
  systems/trajectory_optimization/multiple_shooting.h
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/test/goal/sample_translator.h
Labels: priority: medium

#10800 common: Add constexpr to RandomGenerator min/max
  common/random.h
Labels: configuration: mac, priority: emergency

#10772 setup: Upgrade to Bazel 0.23
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: priority: low

#10650 common: Add LimitMalloc utility
  common/test_utilities/BUILD.bazel
  common/test_utilities/limit_malloc.cc
  common/test_utilities/limit_malloc.h
  common/test_utilities/test/limit_malloc_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/test/external_forces_test.cc
Labels: configuration: linux, priority: low, status: ready to merge

#10812 Disable limit_malloc integration with asan
  common/test_utilities/BUILD.bazel
  multibody/plant/BUILD.bazel
  multibody/plant/test/external_forces_test.cc
Labels: priority: emergency

#10799 common: Add TypeHasher test for non-type templates
  common/test/value_test.cc
  common/value.h
Labels: priority: medium, status: do not merge

#10638 Fix caching problems in integrators
  examples/simple_gripper/simple_gripper.cc
  multibody/plant/test/floating_body_test.cc
  systems/analysis/explicit_euler_integrator.h
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/implicit_euler_integrator.h
  systems/analysis/integrator_base.h
  systems/analysis/runge_kutta2_integrator.h
  systems/analysis/runge_kutta3_integrator-inl.h
  systems/analysis/runge_kutta3_integrator.h
  systems/analysis/semi_explicit_euler_integrator.h
  systems/analysis/test/explicit_euler_integrator_test.cc
  systems/analysis/test/implicit_euler_integrator_test.cc
  systems/analysis/test/runge_kutta2_integrator_test.cc
  systems/analysis/test/runge_kutta3_integrator_test.cc
  systems/analysis/test/semi_explicit_euler_integrator_test.cc
  systems/framework/context.h
  systems/framework/context_base.cc
  systems/framework/context_base.h
  systems/framework/system_base.h
  systems/framework/test/dependency_tracker_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/subvector_test.cc
  systems/framework/vector_base.h
Labels: priority: medium, type: bug, type: cleanup

#10819 framework: Prefer EigenPtr to mutable EigenRef
  systems/analysis/runge_kutta3_integrator-inl.h
  systems/framework/basic_vector.h
  systems/framework/test/basic_vector_test.cc
  systems/framework/test/subvector_test.cc
  systems/framework/vector_base.h
Labels: priority: low

#10717 Add scripts for building Doxygen binaries with Docker
  tools/workspace/doxygen/Dockerfile
  tools/workspace/doxygen/build_binaries_with_docker
Labels: team: kitware

#10821 common: Mark limit_malloc_test as no_tsan and no_memcheck
  common/test_utilities/BUILD.bazel
Labels: priority: emergency

#10830 common: Re-enable limit_malloc sanitizer tests
  common/test_utilities/BUILD.bazel
  common/test_utilities/limit_malloc.cc
Labels: priority: low

#10836 multibody: Use LimitMalloc utility
  multibody/plant/BUILD.bazel
  multibody/plant/test/external_forces_test.cc
Labels: status: do not merge

#10783 Cache contact computations.
  examples/manipulation_station/test/manipulation_station_test.cc
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
  multibody/plant/BUILD.bazel
  multibody/plant/contact_jacobians.cc
  multibody/plant/contact_jacobians.h
  multibody/plant/implicit_stribeck_solver_results.cc
  multibody/plant/implicit_stribeck_solver_results.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/box_test.cc
  multibody/plant/test/inclined_plane_test.cc
Labels: priority: high, team: dynamics

#10727 common: Use type hashing to make Value be snake_case
  bindings/pydrake/systems/framework_py_values.cc
  common/test/value_test.cc
  common/value.cc
  common/value.h
  geometry/dev/scene_graph.cc
  geometry/dev/test/geometry_properties_test.cc
  geometry/scene_graph.cc
Labels: priority: medium, status: do not merge

#10855 Update to new Value APIs (other than //systems/...)
  attic/manipulation/planner/robot_plan_interpolator.cc
  attic/manipulation/util/test/frame_pose_tracker_test.cc
  attic/multibody/rigid_body_plant/contact_results_to_lcm.cc
  attic/multibody/rigid_body_plant/test/compute_contact_result_test.cc
  attic/multibody/rigid_body_plant/test/contact_force_formula_test.cc
  attic/multibody/rigid_body_plant/test/rigid_body_plant_test.cc
  attic/perception/test/rigid_body_point_cloud_filter_test.cc
  attic/perception/test/transform_point_cloud_test.cc
  attic/systems/controllers/plan_eval/manipulator_move_end_effector_plan.cc
  attic/systems/controllers/plan_eval/plan_eval_base_system.h
  attic/systems/controllers/qp_inverse_dynamics/qp_inverse_dynamics_system.cc
  attic/systems/controllers/qp_inverse_dynamics/test/qp_inverse_dynamics_system_test.cc
  attic/systems/sensors/test/depth_sensor_to_lcm_point_cloud_message_test.cc
  attic/systems/sensors/test/rgbd_camera_test.cc
  automotive/automotive_simulator.cc
  automotive/maliput_railcar.cc
  automotive/test/mobil_planner_test.cc
  examples/acrobot/acrobot_lcm.cc
  examples/allegro_hand/allegro_lcm.cc
  examples/allegro_hand/test/allegro_lcm_test.cc
  examples/compass_gait/test/compass_gait_test.cc
  examples/humanoid_controller/dev/humanoid_manipulation_plan.cc
  examples/humanoid_controller/test/atlas_command_translator_system_test.cc
  examples/humanoid_controller/test/humanoid_plan_eval_system_test.cc
  examples/humanoid_controller/valkyrie_balancing_demo.cc
  examples/kinova_jaco_arm/jaco_controller.cc
  examples/kinova_jaco_arm/jaco_lcm.cc
  examples/kinova_jaco_arm/test/jaco_lcm_test.cc
  examples/kuka_iiwa_arm/iiwa_controller.cc
  examples/qp_inverse_dynamics/test/manipulator_joint_space_controller_test.cc
  examples/scene_graph/bouncing_ball_plant.cc
  examples/scene_graph/dev/bouncing_ball_plant.cc
  examples/schunk_wsg/test/schunk_wsg_lift_test.cc
  examples/valkyrie/robot_state_decoder.cc
  examples/valkyrie/robot_state_encoder.cc
  examples/valkyrie/test/robot_state_encoder_decoder_test.cc
  geometry/dev/geometry_properties.h
  geometry/dev/scene_graph.cc
  geometry/dev/test/geometry_properties_test.cc
  geometry/geometry_properties.h
  geometry/scene_graph.cc
  geometry/test/geometry_properties_test.cc
  manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
  manipulation/kuka_iiwa/test/iiwa_status_receiver_test.cc
  manipulation/perception/test/optitrack_pose_extractor_test.cc
  manipulation/perception/test/pose_smoother_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree_system.cc
  perception/test/depth_image_to_point_cloud_test.cc
  solvers/mathematical_program_result.h
Labels: priority: low, status: ready to merge

#10854 Add comments explaining tricky use of cache entries in integrators
  systems/analysis/explicit_euler_integrator.h
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/runge_kutta2_integrator.h
  systems/analysis/runge_kutta3_integrator-inl.h
  systems/analysis/semi_explicit_euler_integrator.h
Labels: priority: low, team: dynamics, type: documentation

#10823 geometry: API for normal direction from pairwise signed distances.
  bindings/pydrake/geometry_py.cc
  geometry/proximity_engine.cc
  geometry/query_results/signed_distance_pair.h
Labels: priority: high, team: dynamics, type: feature request

#10865 framework: Allow for zero-sized ports, state, etc.
  systems/framework/leaf_system.h
  systems/framework/test/leaf_system_test.cc
Labels: priority: high, status: do not merge

#10861 Remove redundant comments about default_scalars
  attic/multibody/rigid_body_plant/compliant_contact_model.cc
  attic/multibody/rigid_body_plant/contact_detail.cc
  attic/multibody/rigid_body_plant/contact_force.cc
  attic/multibody/rigid_body_plant/contact_info.cc
  attic/multibody/rigid_body_plant/contact_resultant_force_calculator.cc
  attic/multibody/rigid_body_plant/contact_results.cc
  attic/multibody/rigid_body_plant/kinematics_results.cc
  attic/multibody/rigid_body_plant/point_contact_detail.cc
  attic/multibody/rigid_body_plant/rigid_body_plant.cc
  automotive/dynamic_bicycle_car.cc
  math/rigid_transform.cc
  multibody/plant/contact_info.cc
  multibody/plant/contact_jacobians.cc
  multibody/plant/contact_results.cc
  multibody/plant/externally_applied_spatial_force.cc
  multibody/plant/implicit_stribeck_solver_results.cc
  solvers/unrevised_lemke_solver.cc
Labels: priority: low, status: do not merge

#10853 systems: Update to new Value APIs
  systems/controllers/test/dynamic_programming_test.cc
  systems/framework/cache.h
  systems/framework/cache_entry.h
  systems/framework/context.h
  systems/framework/fixed_input_port_value.h
  systems/framework/leaf_system.h
  systems/framework/model_values.h
  systems/framework/parameters.h
  systems/framework/port_base.h
  systems/framework/state.h
  systems/framework/system.h
  systems/framework/system_base.h
  systems/framework/system_output.h
  systems/framework/test/cache_entry_test.cc
  systems/framework/test/cache_test.cc
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/fixed_input_port_value_test.cc
  systems/framework/test/input_port_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/model_values_test.cc
  systems/framework/test/output_port_test.cc
  systems/framework/test/parameters_test.cc
  systems/framework/test/system_output_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test_utilities/test/my_vector_test.cc
  systems/lcm/lcm_driven_loop.h
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/serializer.h
  systems/lcm/test/lcm_driven_loop_test.cc
  systems/lcm/test/lcm_subscriber_system_test.cc
  systems/lcm/test/serializer_test.cc
  systems/rendering/render_pose_to_geometry_pose.cc
  systems/rendering/test/pose_aggregator_test.cc
  systems/rendering/test/pose_bundle_to_draw_message_test.cc
  systems/sensors/image_to_lcm_image_array_t.cc
  systems/sensors/test/image_to_lcm_image_array_t_test.cc
  systems/sensors/test/lcm_image_array_to_images_test.cc
  systems/sensors/test/optitrack_sender_test.cc
Labels: priority: low, status: do not merge

#10875 Revert "Cache contact computations. (#10783)"
  examples/manipulation_station/test/manipulation_station_test.cc
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
  multibody/plant/BUILD.bazel
  multibody/plant/contact_jacobians.cc
  multibody/plant/contact_jacobians.h
  multibody/plant/implicit_stribeck_solver_results.cc
  multibody/plant/implicit_stribeck_solver_results.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/box_test.cc
  multibody/plant/test/inclined_plane_test.cc
Labels: priority: high

#10838 Separate out value --> abstract value policy as an internal:: class
  systems/framework/BUILD.bazel
  systems/framework/test/value_to_abstract_value_test.cc
  systems/framework/value_to_abstract_value.h
Labels: priority: medium

#10870 common/yaml: Copy files from TRI's Anzu repository
  common/yaml/dev/BUILD.bazel
  common/yaml/dev/test/yaml_read_archive_test.cc
  common/yaml/dev/visitor.h
  common/yaml/dev/yaml_read_archive.cc
  common/yaml/dev/yaml_read_archive.h
  tools/install/libdrake/build_components.bzl
Labels: priority: medium

#10678 common: Deprecate old Value APIs
  common/value.h
  multibody/plant/test/box_test.cc
  multibody/plant/test/inclined_plane_test.cc
Labels: priority: low

#10852 Corrected a comment about monomial bases
  solvers/mathematical_program.h
Labels: status: curate commits before merging, team: manipulation

#10884 add support for plotting ellipses from their quadratic form.
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/all.py
  bindings/pydrake/drawing.py
  bindings/pydrake/math_py.cc
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/drawing_test.py
  bindings/pydrake/test/math_test.py
  bindings/pydrake/test/symbolic_test.py
Labels: priority: medium

#10889 Cache contact computations
  examples/manipulation_station/test/manipulation_station_test.cc
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
  multibody/plant/BUILD.bazel
  multibody/plant/contact_jacobians.cc
  multibody/plant/contact_jacobians.h
  multibody/plant/implicit_stribeck_solver_results.cc
  multibody/plant/implicit_stribeck_solver_results.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/box_test.cc
  multibody/plant/test/inclined_plane_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: high, team: dynamics, type: bug

#10923 solvers: Add fortran/f2c/unavailable to SNOPT name
  solvers/snopt_solver_common.cc
  solvers/test/snopt_solver_test.cc
Labels: priority: low

#10926 common: Add DRAKE_NODISCARD
  common/BUILD.bazel
  common/drake_nodiscard.h
  common/test/drake_nodiscard_test.cc
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/test/goal/sample.h
Labels: priority: medium

#10920 Signed distance with halfspace - replace segfault with message
  geometry/proximity_engine.cc
  geometry/test/proximity_engine_test.cc
Labels: priority: high, team: dynamics, type: bug

#10929 Use DRAKE_NODISCARD on bare-pointer Clone methods
  common/test/copyable_unique_ptr_test.cc
  common/test/drake_nodiscard_test.cc
  common/test/is_cloneable_test.cc
  examples/humanoid_controller/humanoid_status.h
  systems/framework/basic_vector.h
  systems/framework/event.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/value_checker_test.cc
  systems/framework/test_utilities/my_vector.h
  systems/lcm/test/translator_test.cc
  systems/plants/spring_mass_system/spring_mass_system.h
  systems/rendering/frame_velocity.h
  systems/rendering/pose_vector.h
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/test/goal/sample.h
Labels: priority: backlog

#10928 multibody/plant: Resolve code review defects
  multibody/plant/BUILD.bazel
  multibody/plant/contact_jacobians.cc
  multibody/plant/implicit_stribeck_solver_results.cc
  multibody/plant/implicit_stribeck_solver_results.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: priority: low

#10936 systems/lcm: Reduce spurious dependencies
  examples/compass_gait/BUILD.bazel
  examples/rimless_wheel/BUILD.bazel
  examples/valkyrie/BUILD.bazel
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_publisher_system.cc
Labels: priority: backlog

#10904 Clean up and modernize the ZeroOrderHold implementation
  systems/primitives/BUILD.bazel
  systems/primitives/test/zero_order_hold_test.cc
  systems/primitives/zero_order_hold.h
Labels: priority: medium, team: dynamics, type: cleanup

#10919 common: Move and polish yaml_read_archive out of dev
  common/yaml/BUILD.bazel
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_read_archive.cc
  common/yaml/yaml_read_archive.h
Labels: priority: medium

#10947 Correct the DRAKE_EXPECT_THROWS_IF_ARMED documentation
  common/test_utilities/expect_throws_message.h
Labels: priority: low, team: dynamics, type: documentation

#10952 pydrake: Disable cpplint warnings subsumed by clang-format
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/CPPLINT.cfg
  bindings/pydrake/attic/BUILD.bazel
  bindings/pydrake/attic/multibody/BUILD.bazel
  bindings/pydrake/attic/solvers/BUILD.bazel
  bindings/pydrake/attic/systems/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test_utilities/BUILD.bazel
  bindings/pydrake/doc/BUILD.bazel
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/examples/multibody/BUILD.bazel
  bindings/pydrake/maliput/BUILD.bazel
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/pydrake.bzl
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/third_party/BUILD.bazel
  bindings/pydrake/util/BUILD.bazel
  tools/lint/cpplint.bzl
Labels: priority: backlog

#10759 Add FixValue method to InputPort
  systems/framework/BUILD.bazel
  systems/framework/input_port.h
  systems/framework/test/input_port_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/value_to_abstract_value_test.cc
  systems/framework/value_to_abstract_value.h
Labels: priority: medium

#10945 pydrake: Add InputPort.FixValue bindings
  bindings/pydrake/attic/systems/controllers_py.cc
  bindings/pydrake/attic/systems/sensors_py.cc
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/systems_pybind.h
  bindings/pydrake/systems/test/general_test.py
  systems/framework/value_to_abstract_value.h
Labels: priority: high

#10961 Warn if Anaconda is installed when running install_prereqs
  doc/python_bindings.rst
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs_user_environment.sh
  setup/ubuntu/16.04/install_prereqs.sh
  setup/ubuntu/18.04/install_prereqs.sh
  setup/ubuntu/binary_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: configuration: python, team: kitware, type: installation and distribution

#10969 test_utilities: Teach drake_py_unittest where the source lives
  common/test_utilities/drake_py_unittest_main.py
  manipulation/util/BUILD.bazel
  tools/install/install.bzl
  tools/install/install_test.py
  tools/skylark/drake_py.bzl
Labels: priority: low, status: do not merge

#10858 Update geometry/dev to allow user-defined renderers
  bindings/pydrake/examples/manipulation_station_py.cc
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station.h
  examples/manipulation_station/test/manipulation_station_test.cc
  examples/scene_graph/dev/bouncing_ball_run_dynamics.cc
  geometry/dev/BUILD.bazel
  geometry/dev/geometry_state.cc
  geometry/dev/geometry_state.h
  geometry/dev/internal_geometry.cc
  geometry/dev/internal_geometry.h
  geometry/dev/proximity_engine.cc
  geometry/dev/render/BUILD.bazel
  geometry/dev/render/camera_properties.h
  geometry/dev/render/fidelity.h
  geometry/dev/render/render_engine.cc
  geometry/dev/render/render_engine.h
  geometry/dev/render/render_engine_vtk.cc
  geometry/dev/render/render_engine_vtk.h
  geometry/dev/render/test/render_engine_vtk_test.cc
  geometry/dev/scene_graph.cc
  geometry/dev/scene_graph.h
  geometry/dev/test/geometry_state_test.cc
  geometry/dev/test/query_object_test.cc
  geometry/proximity_engine.cc
  geometry/shape_specification.h
  systems/sensors/BUILD.bazel
Labels: priority: high, team: dynamics

#10968 framework: Advocate for operator[] over GetAtIndex/SetAtIndex
  bindings/pydrake/systems/framework_py_values.cc
  systems/framework/basic_vector.h
  systems/framework/leaf_system.h
  systems/framework/subvector.h
  systems/framework/supervector.h
  systems/framework/test/basic_vector_test.cc
  systems/framework/test/continuous_state_test.cc
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/discrete_values_test.cc
  systems/framework/test/fixed_input_port_value_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/parameters_test.cc
  systems/framework/test/subvector_test.cc
  systems/framework/test/system_constraint_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/vector_system_test.cc
  systems/framework/test_utilities/test/my_vector_test.cc
  systems/framework/vector_base.h
Labels: priority: backlog

#10970 framework: Destroy Diagram's Systems in reverse order
  systems/framework/diagram.h
  systems/framework/diagram_builder.h
  systems/framework/test/diagram_builder_test.cc
Labels: priority: medium, status: do not merge

#10954 common/yaml: Mark public and add to Drake install
  common/yaml/BUILD.bazel
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/drake.cps
Labels: priority: medium, status: do not merge

#10963 Clean up drake front page
  CMakeLists.txt
  doc/BUILD.bazel
  doc/design.rst
  doc/developers.rst
  doc/gallery.rst
  doc/images/logo_w_text.jpg
  doc/images/mathematical_program.svg
  doc/images/mathematical_program.tex
  doc/images/systems.svg
  doc/images/systems.tex
  doc/index.rst
  doc/index_images.rst
  doc/models.rst
  doc/video_tutorials.rst
Labels: priority: high

#10814 common: TypeHasher handles non-type template parameters
  common/test/value_test.cc
  common/value.cc
  common/value.h
  systems/sensors/image.h
Labels: priority: low, status: do not merge

#10997 manipulation_station: Declare differential_ik srcs
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/differential_ik.py
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
Labels: priority: low, status: do not merge

#10931 Add .row() and .col() methods to RotationMatrix class (with tests)
  math/rotation_matrix.h
  math/test/rotation_matrix_test.cc
Labels: priority: medium, team: dynamics, type: feature request

#11000 Disable rgbd_renderer_ospray_test under ThreadSanitizer
  attic/systems/sensors/BUILD.bazel
Labels: priority: high, team: kitware, type: build cop, type: sanitizer-tsan

#10995 Some steps towards making System/Context APIs consistent
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/systems/test/primitives_test.py
  systems/analysis/implicit_euler_integrator-inl.h
  systems/analysis/initial_value_problem-inl.h
  systems/analysis/integrator_base.h
  systems/analysis/lyapunov.cc
  systems/analysis/simulator.h
  systems/analysis/test/explicit_euler_integrator_test.cc
  systems/analysis/test/implicit_euler_integrator_test.cc
  systems/analysis/test/runge_kutta2_integrator_test.cc
  systems/analysis/test/semi_explicit_euler_integrator_test.cc
  systems/analysis/test/simulator_test.cc
  systems/analysis/test_utilities/explicit_error_controlled_integrator_test.h
  systems/framework/context.h
  systems/framework/context_base.cc
  systems/framework/context_base.h
  systems/framework/diagram.h
  systems/framework/diagram_builder.h
  systems/framework/diagram_context.h
  systems/framework/leaf_context.h
  systems/framework/leaf_system.h
  systems/framework/single_output_vector_source.h
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/system_output.h
  systems/framework/system_symbolic_inspector.cc
  systems/framework/system_symbolic_inspector.h
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/input_port_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/output_port_test.cc
  systems/framework/test/single_output_vector_source_test.cc
  systems/framework/test/system_constraint_test.cc
  systems/framework/test/system_symbolic_inspector_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/userscalar_acceptance_test.cc
  systems/framework/test/vector_system_test.cc
  systems/framework/vector_system.h
Labels: priority: medium, type: cleanup

#10951 Maliput: Adds DirectionUsageRule to RoadRulebook
  automotive/maliput/api/basic_id_index.cc
  automotive/maliput/api/basic_id_index.h
  automotive/maliput/api/road_geometry.h
  automotive/maliput/api/road_network.cc
  automotive/maliput/api/road_network.h
  automotive/maliput/api/rules/road_rulebook.h
  automotive/maliput/api/test/mock.cc
  automotive/maliput/api/test/mock.h
  automotive/maliput/api/test/road_network_test.cc
  automotive/maliput/api/test/rules_right_of_way_test.cc
  automotive/maliput/api/test/rules_road_rulebook_test.cc
  automotive/maliput/base/simple_rulebook.cc
  automotive/maliput/base/simple_rulebook.h
  automotive/maliput/base/test/simple_rulebook_test.cc
Labels: team: automotive

#10999 Remove the "before context allocation" requirement from SceneGraph
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/scene_graph_test.cc
Labels: priority: low, team: dynamics, type: cleanup

#11026 Respond to issue #11020: Document why RigidTransform is an improvement over Eigen::Isometry?
  math/rigid_transform.h
Labels: priority: medium, team: dynamics, type: documentation

#10975 Stop promoting zero sized derivatives.
  automotive/test/idm_controller_test.cc
  common/BUILD.bazel
  common/autodiffxd.h
  common/test/autodiffxd_atan2_test.cc
  common/test/autodiffxd_test.h
Labels: priority: high, team: dynamics, type: bug

#11016 README: De-duplicate from `docs`
  README.md
Labels: priority: low, type: cleanup

#11032 doc: Make front page logo not use a hyperlink; fix the width
  doc/index.rst
  doc/index_images.rst
Labels: priority: low

#11036 tools: Enable Werror=unused-result
  tools/skylark/drake_cc.bzl
Labels: priority: medium

#11048 libdrake: Clarify build_components comment
  tools/install/libdrake/build_components.bzl
Labels: priority: backlog, status: do not merge

#11028 Avoid double-counting for cached derivative evals in integrators
  systems/analysis/integrator_base.h
  systems/analysis/test/simulator_test.cc
  systems/framework/system.h
  systems/framework/test/system_test.cc
Labels: priority: medium, team: dynamics, type: bug, type: feature request

#11049 Permit late addition of prerequisites to already-declared cache entries
  systems/framework/cache_entry.h
  systems/framework/system_base.h
  systems/framework/test/cache_entry_test.cc
Labels: priority: medium, team: dynamics, type: feature request, type: performance

#11040 [DSIM-1823] - add basic vector operations to GeoPositionT class
  automotive/maliput/api/lane_data.h
  automotive/maliput/api/test/lane_data_test.cc
Labels: team: automotive

#11062 Make Drake's notation documentation easier to find
  doc/doxygen.h
  multibody/constraint/constraint_doxygen.h
  multibody/multibody_doxygen.h
  systems/analysis/simulator.h
Labels: priority: low, team: dynamics, type: documentation

#10979 Enable caching by default
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
  systems/controllers/inverse_dynamics.cc
  systems/framework/diagram.h
  systems/framework/leaf_system.h
Labels: priority: medium, type: performance

#11066 Update versions of CLion and Bazel Plugin.
  doc/clion.rst
Labels: status: curate commits before merging

#11041 lcm: Add new APIs and discourage use of threads
  attic/manipulation/dev/remote_tree_viewer_wrapper.cc
  bindings/pydrake/lcm_py.cc
  lcm/BUILD.bazel
  lcm/drake_lcm.cc
  lcm/drake_lcm.h
  lcm/drake_lcm_interface.cc
  lcm/drake_lcm_interface.h
  lcm/drake_lcm_log.cc
  lcm/drake_lcm_log.h
  lcm/drake_mock_lcm.cc
  lcm/drake_mock_lcm.h
  lcm/lcm_receive_thread.cc
  lcm/lcm_receive_thread.h
  lcm/test/drake_lcm_interface_test.cc
  lcm/test/drake_lcm_test.cc
  lcm/test/drake_lcm_thread_test.cc
  lcm/test/drake_mock_lcm_test.cc
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/test/lcm_publisher_system_test.cc
Labels: priority: medium

#11077 Replace context.set_time() -> SetTime(), set_accuracy() -> SetAccuracy()
  attic/manipulation/planner/test/robot_plan_interpolator_test.cc
  attic/manipulation/scene_generation/simulate_plant_to_rest.cc
  attic/systems/controllers/qp_inverse_dynamics/test/qp_output_translator_system_test.cc
  automotive/test/maliput_railcar_test.cc
  bindings/pydrake/attic/multibody/test/rigid_body_plant_test.py
  bindings/pydrake/examples/test/compass_gait_test.py
  bindings/pydrake/examples/test/rimless_wheel_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  examples/bouncing_ball/test/bouncing_ball_test.cc
  examples/compass_gait/simulate.cc
  examples/humanoid_controller/test/atlas_command_translator_system_test.cc
  examples/humanoid_controller/test/humanoid_plan_eval_system_test.cc
  examples/humanoid_controller/valkyrie_balancing_demo.cc
  examples/kinova_jaco_arm/jaco_controller.cc
  examples/kuka_iiwa_arm/iiwa_controller.cc
  examples/multibody/acrobot/run_lqr.cc
  examples/qp_inverse_dynamics/test/manipulator_joint_space_controller_test.cc
  examples/rimless_wheel/simulate.cc
  examples/rimless_wheel/test/rimless_wheel_test.cc
  manipulation/perception/test/pose_smoother_test.cc
  multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc
  multibody/plant/test/joint_limits_test.cc
  systems/controllers/dynamic_programming.cc
  systems/framework/context.h
  systems/framework/system_symbolic_inspector.cc
  systems/lcm/test/lcm_driven_loop_test.cc
  systems/lcm/test/lcm_log_playback_test.cc
  systems/lcm/test/lcm_publisher_system_test.cc
  systems/lcm/test/translator_test.cc
  systems/optimization/system_constraint_adapter.cc
  systems/optimization/test/system_constraint_adapter_test.cc
  systems/plants/spring_mass_system/test/spring_mass_system_test.cc
  systems/primitives/test/affine_system_test.cc
  systems/primitives/test/piecewise_polynomial_affine_system_test.cc
  systems/primitives/test/piecewise_polynomial_linear_system_test.cc
  systems/primitives/test/sine_test.cc
  systems/primitives/test/symbolic_vector_system_test.cc
  systems/primitives/test/trajectory_source_test.cc
  systems/primitives/test/zero_order_hold_test.cc
  systems/sensors/test/image_writer_test.cc
  systems/trajectory_optimization/direct_transcription.cc
Labels: priority: low, team: dynamics, type: cleanup

#11069 Implements binding to add a gravity field
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree.h
Labels: team: dynamics, type: bug

#10885 Lyapunov equations
  doc/credits.rst
  math/BUILD.bazel
  math/continuous_lyapunov_equation.cc
  math/continuous_lyapunov_equation.h
  math/discrete_lyapunov_equation.cc
  math/discrete_lyapunov_equation.h
  math/test/continuous_lyapunov_equation_test.cc
  math/test/discrete_lyapunov_equation_test.cc
Labels: status: curate commits before merging
