Repository RobotLocomotion/drake, pull requests merged in 2020-10, with the labels that each got.

#14135 Integrate SimulatorConfig into existing configuration code
  bindings/pydrake/systems/analysis_py.cc
  systems/analysis/BUILD.bazel
  systems/analysis/simulator_config_functions.cc
  systems/analysis/simulator_config_functions.h
  systems/analysis/simulator_flags.cc
  systems/analysis/simulator_flags.h
  systems/analysis/simulator_gflags.cc
  systems/analysis/test/simulator_config_functions_test.cc
  systems/analysis/test/simulator_flags_test.cc
Labels: status: squashing now

#14128 Remove deprecated code (2020-10)
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/geometry_test.py
  bindings/pydrake/test/math_test.py
  manipulation/util/BUILD.bazel
  manipulation/util/bot_core_lcm_encode_decode.cc
  manipulation/util/bot_core_lcm_encode_decode.h
  manipulation/util/test/bot_core_lcm_encode_decode_test.cc
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
Labels: priority: low, status: single reviewer ok

#14149 simulator: Squelch deprecation warning when building.
  systems/analysis/BUILD.bazel
Labels: status: single reviewer ok

#14146 cassie_bench: Separate autodiff malloc counts from benchmark timing
  examples/multibody/cassie_benchmark/test/cassie_bench.cc
Labels: status: single reviewer ok

#14147 workspace: Upgrade libsdformat to latest release 9.3.0
  multibody/parsing/test/detail_sdf_parser_test.cc
  tools/workspace/sdformat/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14152 workspace: Upgrade buildifier to latest release 3.5.0
  tools/workspace/buildifier/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14153 workspace: Upgrade spdlog to latest release 1.8.1
  tools/workspace/spdlog/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#13593 Test to check AutoDiff and vector differentiation in a non-world frame (for issue #13562).
  multibody/plant/BUILD.bazel
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/multibody_plant_kinematics_test.cc
  multibody/test_utilities/BUILD.bazel
  multibody/test_utilities/spatial_derivative.h
Labels: component: multibody plant, priority: medium, status: squashing now, team: dynamics, type: cleanup

#14154 workspace: Upgrade googlebenchmark to latest release
  tools/workspace/googlebenchmark/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14159 Make compatible with Eigen-3.3.8
  systems/framework/system_constraint.h
Labels: status: single reviewer ok

#14148 workspace: Upgrade ignition_math to latest release 6.6.0
  tools/workspace/ignition_math/package.BUILD.bazel
  tools/workspace/ignition_math/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#13916 Code and test for spatial momentum of a plant or subset of bodies.
  multibody/math/spatial_momentum.h
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_momentum_energy_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: component: multibody plant, priority: medium, status: squashing now, team: dynamics, type: design

#14155 build: Wcpp warnings to errors
  tools/skylark/drake_cc.bzl
Labels: component: build system

#14126 Versatile error message for gimbal-lock singularity (helps debug bushings).
  math/roll_pitch_yaw.cc
  math/roll_pitch_yaw.h
  math/test/roll_pitch_yaw_test.cc
  multibody/tree/linear_bushing_roll_pitch_yaw.cc
  multibody/tree/linear_bushing_roll_pitch_yaw.h
  multibody/tree/test/linear_bushing_roll_pitch_yaw_test.cc
Labels: component: multibody plant, priority: medium, status: squashing now, team: dynamics, type: cleanup

#14163 Revert "build: Wcpp warnings to errors"
  tools/skylark/drake_cc.bzl
Labels: priority: emergency, status: single reviewer ok

#14164 manipulation_station: add package.xml
  examples/manipulation_station/models/package.xml
  manipulation/models/ycb/package.xml
Labels: status: commits are properly curated, status: single reviewer ok

#14166 py multibody: add bindings for floating base accessors
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok

#14161 workspace: Upgrade rules_python to latest release 0.0.3
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/rules_python/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14170 doc: Add snapshot of current release playbook
  doc/developers.rst
  doc/release_playbook.rst
Labels: priority: medium, status: single reviewer ok

#14162 Update the Drake credits list
  doc/credits.rst
Labels: priority: low, status: single reviewer ok, status: squashing now, type: documentation

#14179 Add (unused) attribute to snopt rule
  tools/workspace/snopt/repository.bzl
Labels: component: build system, priority: emergency, status: single reviewer ok

#14182 Fix unit_quaternion_constraint_test failure on CI
  multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc
Labels: priority: emergency, status: single reviewer ok

#14169 Use doxygen 1.8.15 on Mac
  setup/mac/source_distribution/Brewfile-doc-only
  tools/workspace/doxygen/repository.bzl
Labels: component: build system, team: kitware

#14184 [geometry] Removing the now unused contact_surface_from_level_set functionality
  multibody/hydroelastics/BUILD.bazel
  multibody/hydroelastics/contact_surface_from_level_set.h
  multibody/hydroelastics/test/contact_surface_from_level_set_test.cc
Labels: status: single reviewer ok

#14185 [sensors] Deprecate the old `foo_sensor.h` to become `foo.h`
  systems/sensors/BUILD.bazel
  systems/sensors/accelerometer.cc
  systems/sensors/accelerometer.h
  systems/sensors/accelerometer_sensor.h
  systems/sensors/gyroscope.cc
  systems/sensors/gyroscope.h
  systems/sensors/gyroscope_sensor.h
  systems/sensors/test/accelerometer_test.cc
  systems/sensors/test/gyroscope_test.cc
Labels: status: commits are properly curated, status: single reviewer ok

#14186 doc: Clarify policy on dev directories
  doc/directory_structure.rst
Labels: priority: low

#14188 multibody: Deprecate dead code
  multibody/math/spatial_vector.h
Labels: priority: low, status: single reviewer ok

#14194 pydrake: Remove the recently-added ShiftInPlace bindings
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
  bindings/pydrake/multibody/test/plant_test.py
Labels: priority: medium, status: single reviewer ok

#14187 Fix pydrake's bindings coverage report
  tools/skylark/pybind.bzl
  tools/workspace/pybind11/BUILD.bazel
Labels: priority: low, status: single reviewer ok

#14193 pydrake: Bind some missing multibody math-related items
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: priority: low, status: single reviewer ok

#14192 pydrake: Bind some missing multibody plant-related items
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  bindings/pydrake/multibody/test/plant_test.py
  multibody/parsing/package_map.cc
  multibody/parsing/package_map.h
Labels: priority: low, status: single reviewer ok

#14195 pydrake: Bind some missing multibody tree-related items
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/tree/planar_joint.h
Labels: priority: low, status: single reviewer ok

#14174 Convert #warnings to errors
  systems/analysis/BUILD.bazel
  tools/skylark/drake_cc.bzl
Labels: component: build system

#14213 Add isoparametric element for FEM.
  multibody/fem/dev/BUILD.bazel
  multibody/fem/dev/isoparametric_element.cc
  multibody/fem/dev/isoparametric_element.h
  multibody/fem/dev/linear_simplex_element.cc
  multibody/fem/dev/linear_simplex_element.h
  multibody/fem/dev/quadrature.h
  multibody/fem/dev/test/isoparametric_element_test.cc
  multibody/fem/dev/test/linear_simplex_element_test.cc
Labels: status: squashing now

#14221 Tidy up build system nits
  geometry/proximity/BUILD.bazel
  multibody/parsing/BUILD.bazel
  tools/install/libdrake/build_components.bzl
Labels: priority: high, status: single reviewer ok

#14217 workspace: Upgrade styleguide latest commit
  tools/workspace/styleguide/repository.bzl
Labels: priority: low, status: single reviewer ok

#14219 Add stl2obj to deal with robot stl meshes
  examples/pr2/BUILD.bazel
  examples/pr2/models/pr2_description/meshes/base_v0/base.obj
  examples/pr2/models/pr2_description/meshes/base_v0/base_L.obj
  examples/pr2/models/pr2_description/meshes/base_v0/caster.obj
  examples/pr2/models/pr2_description/meshes/base_v0/caster_L.obj
  examples/pr2/models/pr2_description/meshes/base_v0/pr2_wheel.obj
  examples/pr2/models/pr2_description/meshes/base_v0/wheel.obj
  examples/pr2/models/pr2_description/meshes/forearm_v0/forearm.obj
  examples/pr2/models/pr2_description/meshes/forearm_v0/wrist_flex.obj
  examples/pr2/models/pr2_description/meshes/forearm_v0/wrist_roll.obj
  examples/pr2/models/pr2_description/meshes/forearm_v0/wrist_roll_L.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/finger_tip_l.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/finger_tip_pad2_l.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/finger_tip_pad2_r.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/finger_tip_r.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/gripper_palm.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/l_finger.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/l_finger_tip.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/l_floating.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/upper_finger_l.obj
  examples/pr2/models/pr2_description/meshes/gripper_v0/upper_finger_r.obj
  examples/pr2/models/pr2_description/meshes/head_v0/head_pan.obj
  examples/pr2/models/pr2_description/meshes/head_v0/head_pan_L.obj
  examples/pr2/models/pr2_description/meshes/head_v0/head_tilt.obj
  examples/pr2/models/pr2_description/meshes/head_v0/head_tilt_L.obj
  examples/pr2/models/pr2_description/meshes/shoulder_v0/shoulder_lift.obj
  examples/pr2/models/pr2_description/meshes/shoulder_v0/shoulder_pan.obj
  examples/pr2/models/pr2_description/meshes/shoulder_v0/shoulder_yaw.obj
  examples/pr2/models/pr2_description/meshes/shoulder_v0/upper_arm_roll.obj
  examples/pr2/models/pr2_description/meshes/shoulder_v0/upper_arm_roll_L.obj
  examples/pr2/models/pr2_description/meshes/tilting_laser_v0/hok_tilt.obj
  examples/pr2/models/pr2_description/meshes/tilting_laser_v0/tilting_hokuyo.obj
  examples/pr2/models/pr2_description/meshes/tilting_laser_v0/tilting_hokuyo_L.obj
  examples/pr2/models/pr2_description/meshes/torso_v0/torso.obj
  examples/pr2/models/pr2_description/meshes/torso_v0/torso_lift.obj
  examples/pr2/models/pr2_description/meshes/torso_v0/torso_lift_L.obj
  examples/pr2/models/pr2_description/meshes/upper_arm_v0/elbow_flex.obj
  examples/pr2/models/pr2_description/meshes/upper_arm_v0/forearm_roll.obj
  examples/pr2/models/pr2_description/meshes/upper_arm_v0/forearm_roll_L.obj
  examples/pr2/models/pr2_description/meshes/upper_arm_v0/upper_arm.obj
  manipulation/util/BUILD.bazel
  manipulation/util/stl2obj.cc
  tools/workspace/vtk/repository.bzl
Labels: priority: low

#14222 Bind a constructor for symbolic::Monomial
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_monomial_test.py
  bindings/pydrake/test/symbolic_test.py
Labels: status: single reviewer ok

#14232 examples: Fix the list of absent examples
  examples/README-MATLAB.md
Labels: priority: low, status: single reviewer ok

#14240 autodiff, cassie_bench: Retire some TODOs.
  common/autodiffxd.h
  examples/multibody/cassie_benchmark/test/cassie_bench.cc
Labels: status: single reviewer ok

#14233 py geometry_test: Fix existing flake8 defects
  bindings/pydrake/test/geometry_test.py
Labels: priority: low, status: single reviewer ok

#14244 add minimum pybind to query hydroelastic_contact_info from ContactResults
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/hydroelastic.sdf
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: squashing now

#14208 doc: Add release notes v0.24.0
  doc/release_notes/release_notes.rst
  doc/release_notes/v0.24.0.rst
  doc/release_playbook.rst
  tools/dev/relnotes.py
Labels: priority: high, status: single reviewer ok

#14249 pydrake.multibody: add binding for CalcCenterOfMassPosition taking model instances
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: priority: low, status: single reviewer ok, team: dynamics

#14253 geometry: Fix QueryObject doc typo
  geometry/query_object.h
Labels: priority: low, status: single reviewer ok

#14256 gl_renderer: Fix stub factory for macOS build
  geometry/render/gl_renderer/BUILD.bazel
  geometry/render/gl_renderer/no_render_engine_gl_factory.cc
Labels: priority: emergency, status: single reviewer ok, status: squashing now

#14257 pydrake.multibody: add missing bindings for joint accessors
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok

#14252 Use package instead of relative path for allegro model files
  manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf
  manipulation/models/allegro_hand_description/sdf/allegro_hand_description_right.sdf
  manipulation/models/allegro_hand_description/urdf/allegro_hand_description_left.urdf
  manipulation/models/allegro_hand_description/urdf/allegro_hand_description_right.urdf
  manipulation/util/show_model.py
Labels: priority: low

#14259 add (almost all) missing py scenegraph inspector bindings
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  geometry/scene_graph_inspector.h
Labels: status: single reviewer ok
