Repository RobotLocomotion/drake, pull requests merged in 2020-03, with the labels that each got.

#12781 Remove deprecated code 2020-03-01
  bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
  bindings/pydrake/attic/multibody/test/rigid_body_tree_test.py
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  common/test/text_logging_test.cc
  common/text_logging.h
  geometry/shape_specification.h
  geometry/test/shape_specification_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/multibody_tree_element.h
  multibody/tree/test/multibody_tree_element_test.cc
Labels: priority: low, status: single reviewer ok

#12794 bind kinetic and potential energy system method in python
  bindings/pydrake/examples/acrobot_py.cc
  bindings/pydrake/examples/test/acrobot_test.py
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
  examples/pendulum/pendulum_plant.cc
  examples/pendulum/pendulum_plant.h
Labels: status: single reviewer ok

#12795 doc: Remove attic classes from Doxygen
  doc/Doxyfile_CXX.in
Labels: priority: low

#12796 Clean up Doxygen to prune junk from overview pages
  bindings/pydrake/common/wrap_pybind.h
  common/eigen_autodiff_limits.h
  common/symbolic_expression.h
  doc/Doxyfile_CXX.in
  examples/bouncing_ball/bouncing_ball.cc
  examples/bouncing_ball/bouncing_ball.h
  examples/bouncing_ball/test/bouncing_ball_test.cc
  geometry/render/render_label.h
  multibody/benchmarks/free_body/free_body.cc
  multibody/benchmarks/free_body/free_body.h
  multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc
  solvers/csdp_solver_internal.h
  systems/rendering/pose_aggregator.h
Labels: priority: low

#12801 Stream sorted pair
  common/sorted_pair.h
  common/test/sorted_pair_test.cc
Labels: status: single reviewer ok

#12800 workspace: Upgrade styleguide latest commit
  tools/workspace/styleguide/repository.bzl
Labels: priority: low, status: single reviewer ok

#12799 workspace: Upgrade ghc_filesystem to latest release 1.3.0
  tools/workspace/ghc_filesystem/package.BUILD.bazel
  tools/workspace/ghc_filesystem/repository.bzl
Labels: priority: low, status: single reviewer ok

#12792 framework: Remove the ability to override allocation methods
  attic/multibody/rigid_body_plant/rigid_body_plant.cc
  attic/multibody/rigid_body_plant/rigid_body_plant.h
  examples/rod2d/rod2d.cc
  examples/rod2d/rod2d.h
  manipulation/planner/robot_plan_interpolator.cc
  manipulation/planner/robot_plan_interpolator.h
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator.h
  systems/framework/diagram.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/vector_system_test.cc
Labels: priority: medium

#12780 workspace: Use system Eigen, not downloaded bitbucket tag
  common/BUILD.bazel
  common/autodiff.h
  common/eigen_autodiff_limits.h
  tools/dynamic_analysis/ubsan.supp
  tools/install/libdrake/drake.cps
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/eigen/BUILD.bazel
  tools/workspace/eigen/package-create-cps.py
  tools/workspace/eigen/package.BUILD.bazel
  tools/workspace/eigen/repository.bzl
  tools/workspace/new_release.py
Labels: priority: low

#12797 primitives: Relocate header file code to cc files
  math/barycentric.h
  systems/primitives/BUILD.bazel
  systems/primitives/barycentric_system.cc
  systems/primitives/barycentric_system.h
  systems/primitives/constant_value_source.cc
  systems/primitives/constant_value_source.h
  systems/primitives/gain.cc
  systems/primitives/gain.h
  systems/primitives/pass_through.cc
  systems/primitives/pass_through.h
  systems/primitives/sine.cc
  systems/primitives/sine.h
  systems/primitives/test/gain_scalartype_test.cc
  systems/primitives/test/pass_through_scalartype_test.cc
  systems/primitives/trajectory_affine_system.cc
  systems/primitives/trajectory_affine_system.h
  systems/primitives/trajectory_linear_system.cc
  systems/primitives/trajectory_linear_system.h
  systems/primitives/zero_order_hold.cc
  systems/primitives/zero_order_hold.h
Labels: priority: low, status: commits are properly curated

#12803 Allow specific cache entries to be initially disabled
  bindings/pydrake/systems/framework_py_systems.cc
  systems/framework/cache_entry.h
  systems/framework/leaf_output_port.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/test/cache_entry_test.cc
  systems/framework/test/input_port_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/output_port_test.cc
  systems/framework/test/system_test.cc
Labels: priority: low, team: dynamics, type: feature request

#12776 styleguide: Bump to latest commit
  tools/workspace/styleguide/BUILD.bazel
  tools/workspace/styleguide/package.BUILD.bazel
  tools/workspace/styleguide/repository.bzl
Labels: team: kitware

#12040 Pybind11 coverage
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/systems/BUILD.bazel
  third_party/BUILD.bazel
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/skylark/pybind.bzl
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pybind11/README.md
  tools/workspace/pybind11/__init__.py
  tools/workspace/pybind11/generate_pybind_coverage.py
  tools/workspace/pybind11/libclang_setup.py
  tools/workspace/pybind11/pybind_coverage_libclang_parser.py
  tools/workspace/pybind11/pybind_coverage_xml_parser.py
  tools/workspace/pybind11/test/generate_pybind_coverage_test.py
  tools/workspace/pybind11/test/sample_header.h
  tools/workspace/pybind11/test/sample_header_class_coverage_expected.csv
  tools/workspace/pybind11/test/sample_header_documentation.expected.h
  tools/workspace/pybind11/test/sample_header_documentation_pybind_expected.xml
  tools/workspace/pybind11/test/sample_header_file_coverage_expected.csv
  tools/workspace/pybind11/test/sample_header_py.cc
Labels: team: kitware

#12818 Remove unused code from mkdoc.py
  third_party/com_github_pybind_pybind11/mkdoc.py
Labels: priority: high, type: build cop

#12630 framework: Systems reject ContinuousState that they did not create
  bindings/pydrake/systems/test/test_util_py.cc
  systems/framework/BUILD.bazel
  systems/framework/context.h
  systems/framework/context_base.h
  systems/framework/continuous_state.h
  systems/framework/diagram.h
  systems/framework/diagram_context.h
  systems/framework/diagram_continuous_state.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/system_base.h
  systems/framework/test/continuous_state_test.cc
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_test.cc
Labels: priority: low

#12822 Add no_kcov to cpplint_unittest
  tools/workspace/styleguide/BUILD.bazel
Labels: priority: high, status: single reviewer ok, type: build cop

#12809 SpatialInertia support for massless bodies.
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: priority: medium, team: dynamics

#12826 workspace: Remove godotengine
  systems/sensors/godot_renderer/dev/BUILD.bazel
  systems/sensors/godot_renderer/dev/README.md
  systems/sensors/godot_renderer/dev/dummy_macos.cc
  systems/sensors/godot_renderer/dev/dummy_ubuntu.cc
  tools/workspace/default.bzl
  tools/workspace/godotengine/BUILD.bazel
  tools/workspace/godotengine/main_build_gles3_headers.py
  tools/workspace/godotengine/main_make_binders.py
  tools/workspace/godotengine/main_update_version.py
  tools/workspace/godotengine/package.BUILD.bazel
  tools/workspace/godotengine/repository.bzl
  tools/workspace/new_release.py
Labels: priority: low, status: single reviewer ok

#12742 Improve the simple_gripper example to make it possible to test more integrators
  examples/simple_gripper/BUILD.bazel
  examples/simple_gripper/simple_gripper.cc
  systems/analysis/BUILD.bazel
  systems/analysis/simulator_gflags.cc
  systems/analysis/simulator_gflags.h
  systems/analysis/simulator_print_stats.cc
  systems/analysis/simulator_print_stats.h
Labels: status: squashing now

#12823 framework: Remove support for user-defined scalars
  common/default_scalars.h
  systems/framework/BUILD.bazel
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/test/system_constraint_test.cc
  systems/framework/test/system_scalar_converter_test.cc
  systems/framework/test/userscalar_acceptance_test.cc
Labels: priority: medium

#12834 Removes stereographic projection derivation
  doc/derivations/stereographic.pdf
  doc/derivations/stereographic.texp
  solvers/mathematical_program_doxygen.h
Labels: status: single reviewer ok

#12837 workspace: Add new_release reporting for some missed items
  tools/workspace/metadata.py
Labels: priority: medium, status: single reviewer ok

#12764 Implements Composite Body Algorithm to compute the mass matrix
  multibody/math/spatial_force.h
  multibody/math/test/spatial_algebra_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_mass_matrix_test.cc
  multibody/tree/body_node.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: team: dynamics, type: feature request, type: performance

#12838 Update to use CBA in MBP::CalcTamsiResults()
  multibody/plant/multibody_plant.cc
Labels: status: single reviewer ok, team: dynamics, type: performance

#12829 [geometry] Some cosmetic clean up
  geometry/proximity/bounding_volume_hierarchy.cc
  geometry/proximity/bounding_volume_hierarchy.h
  geometry/proximity/mesh_intersection.h
  geometry/proximity/test/mesh_intersection_test.cc
Labels: status: single reviewer ok

#12816 leaf_system: Split code between h and cc
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
Labels: priority: medium, status: commits are properly curated, status: do not merge, status: single reviewer ok

#12830 yaml: Fix accidentally quadratic parsing
  common/yaml/BUILD.bazel
  common/yaml/test/yaml_performance_test.cc
  common/yaml/yaml_read_archive.cc
  common/yaml/yaml_read_archive.h
Labels: priority: medium

#12836 workspace: Update buildifier to latest release 2.0.0
  tools/workspace/buildifier/repository.bzl
Labels: priority: low, status: single reviewer ok

#12845 doc: Note that GCC 7.5 is now Ubuntu's default compiler
  CMakeLists.txt
  bindings/pydrake/autodiff_types_pybind.h
  doc/bazel.rst
  doc/developers.rst
  doc/getting_help.rst
Labels: priority: high

#12808 Release notes v0.16.0
  doc/release_notes/release_notes.rst
  doc/release_notes/v0.16.0.rst
Labels: status: squashing now

#12850 Build and lint fixes for the OpenGL render engine
  geometry/render/gl_renderer/BUILD.bazel
  geometry/render/gl_renderer/render_engine_gl.cc
Labels: status: single reviewer ok

#12852 diagram: Split code between h and cc
  systems/framework/diagram.cc
  systems/framework/diagram.h
Labels: priority: low, status: commits are properly curated, status: single reviewer ok

#12856 Release notes v0.16.1
  doc/release_notes/release_notes.rst
  doc/release_notes/v0.12.0.rst
  doc/release_notes/v0.13.0.rst
  doc/release_notes/v0.14.0.rst
  doc/release_notes/v0.15.0.rst
  doc/release_notes/v0.16.0.rst
  doc/release_notes/v0.16.1.rst
Labels: priority: high

#12806 Documents conventions in HydroelasticContactInfo
  multibody/plant/hydroelastic_contact_info.h
Labels: priority: low, team: dynamics, type: documentation

#12865 bind CopyToVector for ContinuousState
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok

#12860 Add documentation for alternate bvh heuristics
  geometry/proximity/bounding_volume_hierarchy.cc
Labels: status: single reviewer ok

#12874 test_utilities: Promote deprecations to errors in pydrake unit tests
  bindings/pydrake/systems/test/general_test.py
  common/test_utilities/drake_py_unittest_main.py
Labels: priority: high

#12871 [parsing] Add unit test to cover Parser's automatic search for packages
  multibody/parsing/package_map.cc
  multibody/parsing/test/parser_test.cc
Labels: team: dynamics

#12872 InverseKinematics allows ignoring joint limits in the constructor.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
Labels: status: squashing now

#12883 pydrake multibody: Add bindings for MultibodyPlant output ports
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok

#12885 Add MakeSolver to mathematical program tutorial.
  tutorials/mathematical_program.ipynb
Labels: status: single reviewer ok, status: squashing now

#12879 Fix ABI::IsPhysicallyValid() to avoid false negatives.
  multibody/plant/BUILD.bazel
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/tree/articulated_body_inertia.h
Labels: team: dynamics, type: bug

#12899 Hotfix for #12898
  systems/analysis/test/region_of_attraction_test.cc
Labels: priority: high, status: single reviewer ok

#12905 Use dReal 4.20.03.4
  tools/workspace/dreal/repository.bzl
Labels: status: single reviewer ok

#12787 pybind11 docs: Monkey patch sphinx to get custom sorted docs
  bindings/pydrake/doc/LICENSE.TXT
  bindings/pydrake/doc/conf.py
  bindings/pydrake/doc/pydrake_sphinx_extension.py
  bindings/pydrake/doc/sphinx.LICENSE.txt
Labels: team: kitware

#12896 Add PointToPointDistanceConstraint.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/point_to_point_distance_constraint.cc
  multibody/inverse_kinematics/point_to_point_distance_constraint.h
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
  multibody/inverse_kinematics/test/point_to_point_distance_constraint_test.cc
Labels: status: squashing now

#12891 framework: Update internal for ValidateContext rename
  geometry/geometry_state.h
  multibody/plant/multibody_plant.h
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/plant/test/multibody_plant_jacobians_test.cc
  systems/framework/cache_entry.cc
  systems/framework/framework_common.h
  systems/framework/input_port.h
  systems/framework/output_port.h
  systems/framework/system_base.h
  systems/framework/test/system_base_test.cc
Labels: priority: high, status: do not merge

#12902 Add MathematicalProgram::Reparse
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic_polynomial.cc
  common/symbolic_polynomial.h
  common/test/symbolic_polynomial_test.cc
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
  systems/analysis/region_of_attraction.cc
Labels: status: commits are properly curated

#12906 framework: OutputPort should not depend on SystemBase
  systems/framework/BUILD.bazel
  systems/framework/diagram.cc
  systems/framework/diagram_output_port.h
  systems/framework/input_port.h
  systems/framework/leaf_output_port.h
  systems/framework/output_port.h
  systems/framework/port_base.cc
  systems/framework/port_base.h
  systems/framework/system_base.h
  systems/framework/test/input_port_test.cc
  systems/framework/test/output_port_test.cc
Labels: priority: low, status: single reviewer ok

#12910 Revert "pybind11 docs: Monkey patch sphinx to get custom sorted docs (#12787)
  bindings/pydrake/doc/LICENSE.TXT
  bindings/pydrake/doc/conf.py
  bindings/pydrake/doc/pydrake_sphinx_extension.py
  bindings/pydrake/doc/sphinx.LICENSE.txt
Labels: status: single reviewer ok

#12894 framework: Break WitnessFunction dependency cycle
  systems/framework/BUILD.bazel
  systems/framework/input_port.h
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/output_port.h
  systems/framework/witness_function.cc
  systems/framework/witness_function.h
Labels: priority: medium

#12913 system: Split code between h and cc
  systems/framework/system.cc
  systems/framework/system.h
Labels: priority: medium, status: commits are properly curated, status: single reviewer ok

#12908 analysis: Add default_scalars annotations where still absent
  systems/analysis/BUILD.bazel
  systems/analysis/antiderivative_function.cc
  systems/analysis/antiderivative_function.h
  systems/analysis/bogacki_shampine3_integrator.h
  systems/analysis/dense_output.cc
  systems/analysis/dense_output.h
  systems/analysis/explicit_euler_integrator.cc
  systems/analysis/explicit_euler_integrator.h
  systems/analysis/hermitian_dense_output.cc
  systems/analysis/hermitian_dense_output.h
  systems/analysis/implicit_euler_integrator.cc
  systems/analysis/implicit_integrator.cc
  systems/analysis/integrator_base.cc
  systems/analysis/radau_integrator.cc
  systems/analysis/runge_kutta2_integrator.cc
  systems/analysis/runge_kutta2_integrator.h
  systems/analysis/scalar_dense_output.cc
  systems/analysis/scalar_dense_output.h
  systems/analysis/scalar_view_dense_output.cc
  systems/analysis/scalar_view_dense_output.h
  systems/analysis/semi_explicit_euler_integrator.cc
  systems/analysis/semi_explicit_euler_integrator.h
  systems/analysis/stepwise_dense_output.cc
  systems/analysis/stepwise_dense_output.h
  systems/analysis/velocity_implicit_euler_integrator.cc
  systems/analysis/velocity_implicit_euler_integrator.h
Labels: priority: medium

#12914 snopt: Tidy up storage declaration
  solvers/snopt_solver.cc
Labels: priority: low, status: single reviewer ok

#12915 Improve args and doc for pyplot_visualizer
  bindings/pydrake/systems/pyplot_visualizer.py
Labels: status: single reviewer ok

#12919 analysis: Enable symbolic expressions in dense_output family
  systems/analysis/dense_output.cc
  systems/analysis/dense_output.h
  systems/analysis/hermitian_dense_output.cc
  systems/analysis/hermitian_dense_output.h
  systems/analysis/scalar_dense_output.cc
  systems/analysis/scalar_dense_output.h
  systems/analysis/scalar_view_dense_output.cc
  systems/analysis/scalar_view_dense_output.h
  systems/analysis/stepwise_dense_output.cc
  systems/analysis/stepwise_dense_output.h
Labels: priority: medium, status: single reviewer ok

#12920 pydrake simulator: Bind simulator realtime rate accessors
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok

#12916 Add dual solution to OsqpSolverDetails.
  bindings/pydrake/solvers/osqp_py.cc
  bindings/pydrake/solvers/test/osqp_solver_test.py
  solvers/osqp_solver.cc
  solvers/osqp_solver.h
  solvers/test/osqp_solver_test.cc
Labels: status: single reviewer ok, status: squashing now

#12921 pybind11 docs: Fix sphinx patch for versions > 1.6.7
  bindings/pydrake/doc/LICENSE.TXT
  bindings/pydrake/doc/conf.py
  bindings/pydrake/doc/pydrake_sphinx_extension.py
  bindings/pydrake/doc/sphinx.LICENSE.txt
Labels: status: commits are properly curated, status: single reviewer ok

#12918 Adds pyplot to geometry_inspector
  manipulation/util/geometry_inspector.py
  manipulation/util/test/geometry_inspector_test.py
Labels: status: single reviewer ok

#12909 [geometry] Utility for adding polygon to contact surface handles degeneracies
  geometry/proximity/BUILD.bazel
  geometry/proximity/contact_surface_utility.cc
  geometry/proximity/contact_surface_utility.h
  geometry/proximity/test/contact_surface_utility_test.cc
Labels: status: squashing now, team: dynamics, type: feature request

#12922 analysis: adds support for symbolic expression to integrators
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  systems/analysis/explicit_euler_integrator.cc
  systems/analysis/explicit_euler_integrator.h
  systems/analysis/integrator_base.cc
  systems/analysis/integrator_base.h
  systems/analysis/runge_kutta2_integrator.cc
  systems/analysis/runge_kutta2_integrator.h
  systems/analysis/test/explicit_euler_integrator_test.cc
  systems/analysis/test/runge_kutta2_integrator_test.cc
Labels: status: commits are properly curated

#12884 add DrakeSolverOption
  solvers/BUILD.bazel
  solvers/common_solver_option.cc
  solvers/common_solver_option.h
  solvers/solver_options.cc
  solvers/solver_options.h
  solvers/test/solver_options_test.cc
Labels: status: squashing now

#12932 Move HydroelasticFallbackCacheData out of MultibodyPlant
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok

#12924 yaml: Add read support for merge keys
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_read_archive.cc
  common/yaml/yaml_read_archive.h
Labels: priority: high

#12931 Rename `InitialValueProblem::SpecifiedValues` to `ODEContext`
  multibody/tree/test/door_hinge_test.cc
  systems/analysis/antiderivative_function.h
  systems/analysis/initial_value_problem.cc
  systems/analysis/initial_value_problem.h
  systems/analysis/scalar_initial_value_problem.h
  systems/analysis/test/antiderivative_function_test.cc
  systems/analysis/test/initial_value_problem_test.cc
  systems/analysis/test/scalar_initial_value_problem_test.cc
Labels: status: single reviewer ok

#12933 Add and use symbolic::IsAffine
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic_expression.cc
  common/symbolic_expression.h
  common/test/symbolic_expression_matrix_test.cc
  solvers/create_constraint.cc
  systems/framework/system_symbolic_inspector.cc
  systems/trajectory_optimization/direct_transcription.cc
Labels: status: commits are properly curated

#12939 trajectories: rename knots to samples
  attic/multibody/rigid_body_plant/drake_visualizer.cc
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/piecewise_polynomial.cc
  common/trajectories/piecewise_polynomial.h
  common/trajectories/piecewise_quaternion.h
  common/trajectories/test/piecewise_polynomial_generation_test.cc
  common/trajectories/test/piecewise_polynomial_test.cc
  common/trajectories/test/piecewise_quaternion_test.cc
  examples/kuka_iiwa_arm/iiwa_world/multi_arm_with_gripper_demo.cc
  examples/kuka_iiwa_arm/kuka_plan_runner.cc
  examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc
  manipulation/planner/robot_plan_interpolator.cc
  manipulation/util/test/trajectory_utils_test.cc
  manipulation/util/trajectory_utils.h
  systems/analysis/hermitian_dense_output.h
  systems/analysis/test/hermitian_dense_output_test.cc
  systems/controllers/test/zmp_test_util.cc
  systems/trajectory_optimization/direct_collocation.cc
  systems/trajectory_optimization/direct_collocation.h
  systems/trajectory_optimization/direct_transcription.cc
  systems/trajectory_optimization/direct_transcription.h
  systems/trajectory_optimization/multiple_shooting.h
  systems/trajectory_optimization/test/direct_collocation_test.cc
Labels: priority: high, status: commits are properly curated

#12943 add /.vscode/ to .gitignore
  .gitignore
Labels: status: single reviewer ok

#12945 tools: Disable container_overflow checks under asan
  tools/dynamic_analysis/asan.sh
Labels: priority: high, status: single reviewer ok

#12948 cleanup: use typename T in polynomial classes
  bindings/pydrake/polynomial_py.cc
  common/polynomial.cc
  common/polynomial.h
  common/test/polynomial_test.cc
  common/test_utilities/random_polynomial_matrix.h
  common/trajectories/piecewise_polynomial.cc
  common/trajectories/piecewise_polynomial.h
  common/trajectories/test/piecewise_polynomial_generation_test.cc
  common/trajectories/test/piecewise_polynomial_test.cc
  common/trajectories/test/random_piecewise_polynomial.h
  common/trig_poly.h
  solvers/system_identification.h
Labels: status: single reviewer ok

#12935 [geometry] update mesh-half space intersection for full hydroleastic compatibility
  geometry/proximity/BUILD.bazel
  geometry/proximity/mesh_half_space_intersection.cc
  geometry/proximity/mesh_half_space_intersection.h
  geometry/proximity/test/mesh_half_space_intersection_test.cc
Labels: status: squashing now

#12940 pydrake examples: Bind missing functions for pendulum example
  bindings/pydrake/examples/pendulum_py.cc
  bindings/pydrake/examples/test/pendulum_test.py
Labels: status: single reviewer ok

#12895 Add missing energy and power overrides to MBP
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.h
  multibody/plant/test/energy_and_power_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.h
  multibody/tree/test/linear_spring_damper_test.cc
  multibody/tree/test/multibody_tree_test.cc
Labels: priority: high, team: dynamics, type: bug

#12953 Move MBP::HydroelasticContactInfoAndBodySpatialForces into internal
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok

#12956 ignore /.vscode instead of /.vscode/
  .gitignore
Labels: status: single reviewer ok

#12963 gl_renderer: Disable opengl_context_test under memcheck
  geometry/render/gl_renderer/BUILD.bazel
Labels: priority: high, status: single reviewer ok

#12960 py multibody: Move door_hinge notebook to avoid import errors
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/examples/door_hinge_inspector.ipynb
  multibody/tree/door_hinge.h
Labels: priority: high, status: single reviewer ok

#12760 Add Error Control to Velocity-Implicit Euler Integrator, third PR of #12528
  systems/analysis/test_utilities/implicit_integrator_test.h
  systems/analysis/velocity_implicit_euler_integrator.cc
  systems/analysis/velocity_implicit_euler_integrator.h
Labels: status: squashing now

#12957 trajectories: construct HermitianDenseOutput from PiecewisePolynomial
  systems/analysis/hermitian_dense_output.h
  systems/analysis/test/hermitian_dense_output_test.cc
Labels: status: single reviewer ok

#12964 gl_renderer: Refactor for better stack traces
  geometry/render/gl_renderer/opengl_context.cc
Labels: priority: medium, status: single reviewer ok

#12955 Use System energy and power methods to remove some DoorHinge test TODOs.
  multibody/tree/test/door_hinge_test.cc
Labels: priority: low, team: dynamics, type: cleanup

#12958 jupyter_py: Add workaround / notes for common ZMQError flake on CI
  tools/jupyter/BUILD.bazel
  tools/jupyter/jupyter_bazel.py
  tools/jupyter/jupyter_py.bzl
Labels: status: single reviewer ok

#12961 visualizer: add ConnectPlanarSceneGraphVisualizer
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
Labels: status: single reviewer ok

#12968 Change system.h comment style to the more-compact form
  systems/framework/system.h
Labels: priority: low, status: single reviewer ok
