Repository RobotLocomotion/drake, pull requests merged in 2020-02, with the labels that each got.

#12658 Fix show logic in pyplot visualizer
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/pyplot_visualizer.py
  tutorials/pyplot_animation_multibody_plant.ipynb
Labels: status: single reviewer ok

#12663 examples: Remove controlled_kuka
  examples/kuka_iiwa_arm/controlled_kuka/BUILD.bazel
  examples/kuka_iiwa_arm/controlled_kuka/README.md
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_demo.cc
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_trajectory.cc
  examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_trajectory.h
Labels: priority: medium, status: single reviewer ok

#12666 attic: Remove deprecated remove_tree_viewer_wrapper
  attic/manipulation/dev/BUILD.bazel
  attic/manipulation/dev/README.md
  attic/manipulation/dev/remote_tree_viewer_wrapper.cc
  attic/manipulation/dev/remote_tree_viewer_wrapper.h
  attic/manipulation/dev/test/remote_tree_viewer_wrapper_demo.cc
  tools/install/libdrake/build_components.bzl
  tools/workspace/json/BUILD.bazel
  tools/workspace/json/package.BUILD.bazel
  tools/workspace/json/stub.cc
Labels: priority: medium, status: single reviewer ok

#12667 workspace: Upgrade lcm to latest commit
  tools/workspace/lcm/repository.bzl
Labels: priority: low, status: single reviewer ok

#12665 attic: Remove deprecated xtion sensor and its URDF models
  attic/manipulation/sensors/BUILD.bazel
  attic/manipulation/sensors/README.md
  attic/manipulation/sensors/xtion.cc
  attic/manipulation/sensors/xtion.h
  manipulation/models/BUILD.bazel
  manipulation/models/xtion_description/BUILD.bazel
  manipulation/models/xtion_description/meshes/xtion.obj
  manipulation/models/xtion_description/model.config
  manipulation/models/xtion_description/package.xml
  manipulation/models/xtion_description/urdf/xtion.urdf
  manipulation/models/xtion_description/urdf/xtion_wsg_fixture.urdf
  tools/install/libdrake/build_components.bzl
Labels: priority: medium, status: single reviewer ok

#12668 workspace: Upgrade meshcat_python to latest commit
  tools/workspace/meshcat_python/repository.bzl
Labels: priority: low, status: single reviewer ok

#12659 Add linear program tutorial.
  tutorials/BUILD.bazel
  tutorials/linear_program.ipynb
  tutorials/mathematical_program.ipynb
Labels: status: squashing now

#12676 workspace: Remove visibility annotation on json stub
  tools/workspace/json/package.BUILD.bazel
Labels: priority: emergency, status: single reviewer ok

#12675 py manipulation_station: Add missing class docstrings
  bindings/pydrake/examples/manipulation_station_py.cc
Labels: status: single reviewer ok

#12679 attic: Deprecate manipulation/util
  attic/manipulation/util/BUILD.bazel
  attic/manipulation/util/README.md
  attic/manipulation/util/robot_state_msg_translator.h
  attic/manipulation/util/sim_diagram_builder.h
  attic/manipulation/util/world_sim_tree_builder.h
  examples/allegro_hand/BUILD.bazel
  examples/allegro_hand/test/allegro_lcm_test.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc
Labels: priority: medium

#12681 workspace: Remove deprecated spruce
  third_party/BUILD.bazel
  third_party/josephdavisco_spruce/LICENSE
  third_party/josephdavisco_spruce/spruce.cc
  third_party/josephdavisco_spruce/spruce.hh
  tools/workspace/default.bzl
  tools/workspace/spruce/BUILD.bazel
  tools/workspace/spruce/package.BUILD.bazel
  tools/workspace/spruce/repository.bzl
Labels: priority: low, status: single reviewer ok

#12682 common: Remove deprecated drake_optional and drake_variant
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/drake_optional_pybind.h
  bindings/pydrake/common/drake_variant_pybind.h
  common/BUILD.bazel
  common/drake_optional.h
  common/drake_variant.h
  common/test/drake_optional_test.cc
  common/test/drake_variant_test.cc
  tools/workspace/default.bzl
  tools/workspace/stx/BUILD.bazel
  tools/workspace/stx/package.BUILD.bazel
  tools/workspace/stx/repository.bzl
Labels: priority: low, status: single reviewer ok

#12669 workspace: Upgrade spdlog to latest release 1.5.0
  tools/workspace/spdlog/repository.bzl
Labels: priority: low, status: single reviewer ok

#12685 Remove deprecated code (2020-02)
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.h
  solvers/no_snopt.cc
  solvers/snopt_solver.cc
  solvers/snopt_solver.h
Labels: priority: low, status: single reviewer ok

#12686 common: Hide filesystem.h from downstreams
  common/BUILD.bazel
Labels: priority: low, status: single reviewer ok

#12684 vector_gen: Switch all sources to yaml format
  examples/acrobot/BUILD.bazel
  examples/acrobot/acrobot_input.named_vector
  examples/acrobot/acrobot_input_named_vector.yaml
  examples/acrobot/acrobot_params.named_vector
  examples/acrobot/acrobot_params_named_vector.yaml
  examples/acrobot/acrobot_plant.h
  examples/acrobot/acrobot_state.named_vector
  examples/acrobot/acrobot_state_named_vector.yaml
  examples/acrobot/spong_controller_params.named_vector
  examples/acrobot/spong_controller_params_named_vector.yaml
  examples/compass_gait/BUILD.bazel
  examples/compass_gait/compass_gait_continuous_state.named_vector
  examples/compass_gait/compass_gait_continuous_state_named_vector.yaml
  examples/compass_gait/compass_gait_params.named_vector
  examples/compass_gait/compass_gait_params_named_vector.yaml
  examples/multibody/cart_pole/BUILD.bazel
  examples/multibody/cart_pole/cart_pole.sdf
  examples/multibody/cart_pole/cart_pole_params.named_vector
  examples/multibody/cart_pole/cart_pole_params_named_vector.yaml
  examples/multibody/cart_pole/test/cart_pole_test.cc
  examples/pendulum/BUILD.bazel
  examples/pendulum/pendulum_input.named_vector
  examples/pendulum/pendulum_input_named_vector.yaml
  examples/pendulum/pendulum_params.named_vector
  examples/pendulum/pendulum_params_named_vector.yaml
  examples/pendulum/pendulum_state.named_vector
  examples/pendulum/pendulum_state_named_vector.yaml
  examples/rimless_wheel/BUILD.bazel
  examples/rimless_wheel/rimless_wheel_continuous_state.named_vector
  examples/rimless_wheel/rimless_wheel_continuous_state_named_vector.yaml
  examples/rimless_wheel/rimless_wheel_params.named_vector
  examples/rimless_wheel/rimless_wheel_params_named_vector.yaml
  examples/rod2d/BUILD.bazel
  examples/rod2d/rod2d_state_vector.named_vector
  examples/rod2d/rod2d_state_vector_named_vector.yaml
  examples/scene_graph/BUILD.bazel
  examples/scene_graph/bouncing_ball_vector.named_vector
  examples/scene_graph/bouncing_ball_vector_named_vector.yaml
  manipulation/schunk_wsg/BUILD.bazel
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator_state_vector.named_vector
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator_state_vector_named_vector.yaml
  systems/sensors/BUILD.bazel
  systems/sensors/beam_model_params.named_vector
  systems/sensors/beam_model_params_named_vector.yaml
Labels: priority: low, status: commits are properly curated, status: do not merge

#12691 roll_pitch_yaw.h: add missing ` in doxygen
  math/roll_pitch_yaw.h
Labels: status: single reviewer ok

#12680 common: Remove deprecated text_logging_gflags
  bindings/pydrake/BUILD.bazel
  common/BUILD.bazel
  common/text_logging_gflags.h
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/drake.cps
  tools/install/libdrake/test/find_package_drake_install_test.py
Labels: priority: low

#12692 doc: Platform reviewers should merge PRs
  doc/code_review_checklist.rst
  doc/developers.rst
  doc/platform_reviewer_checklist.rst
  doc/reviewable.rst
Labels: priority: low

#12689 workspace: Remove all dependencies on protobuf
  common/proto/BUILD.bazel
  common/proto/protobuf.cc
  common/proto/protobuf.h
  common/proto/test/protobuf_test.cc
  common/proto/test/test_string.txt
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/install_prereqs.sh
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake.cps
  tools/vector_gen/BUILD.bazel
  tools/vector_gen/attic/BUILD.bazel
  tools/vector_gen/attic/README.md
  tools/vector_gen/attic/test/lcm_vector_gen_test.sh
  tools/vector_gen/attic/test/sample.named_vector
  tools/vector_gen/lcm_vector_gen.py
  tools/vector_gen/named_vector_pb2.py
  tools/vector_gen/vector_gen.bzl
  tools/workspace/default.bzl
  tools/workspace/libprotobuf/BUILD.bazel
  tools/workspace/libprotobuf/repository.bzl
Labels: priority: low

#12695 doc: macOS pre-merge validation should prefer Catalina
  doc/code_review_checklist.rst
  doc/jenkins.rst
Labels: priority: low

#12696 workspace: Update buildifier to latest release 1.0.0
  tools/skylark/pathutils.bzl
  tools/workspace/buildifier/repository.bzl
  tools/workspace/os.bzl
Labels: priority: low, status: single reviewer ok

#12693 print solvers::Binding.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/BUILD.bazel
  solvers/binding.h
  solvers/constraint.cc
  solvers/constraint.h
  solvers/cost.cc
  solvers/cost.h
  solvers/evaluator_base.cc
  solvers/evaluator_base.h
  solvers/test/binding_test.cc
  solvers/test/constraint_test.cc
  solvers/test/cost_test.cc
  solvers/test/evaluator_base_test.cc
Labels: status: squashing now

#12683 Improve rotation matrix methods in Frame and MultibodyTree.
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/frame_kinematics_test.cc
  multibody/tree/body.h
  multibody/tree/body_node.h
  multibody/tree/fixed_offset_frame.h
  multibody/tree/frame.h
  multibody/tree/multibody_tree.cc
  multibody/tree/position_kinematics_cache.h
  multibody/tree/test/frames_test.cc
  multibody/tree/test/multibody_tree_test.cc
  multibody/tree/uniform_gravity_field_element.cc
Labels: priority: medium, status: squashing now, team: dynamics, type: performance

#12694 [workspace] Update to current FCL (pre fcl 0.6.0)
  tools/workspace/fcl/package.BUILD.bazel
  tools/workspace/fcl/repository.bzl
Labels: status: single reviewer ok

#12700 Print out added linear cost and constraint in the tutorial.
  tutorials/linear_program.ipynb
Labels: status: single reviewer ok

#12705 Add missing stdlib include statements
  examples/manipulation_station/manipulation_station.h
  examples/planar_gripper/gripper_brick.h
  geometry/proximity/hydroelastic_internal.h
  geometry/proximity/make_sphere_mesh.h
  geometry/render/render_engine_ospray.cc
  geometry/render/render_engine_ospray_factory.h
  geometry/render/render_engine_vtk.cc
  geometry/render/render_engine_vtk_factory.h
  lcm/drake_lcm.h
  lcm/drake_lcm_log.h
  multibody/benchmarks/acrobot/make_acrobot_plant.cc
  multibody/optimization/test/optimization_with_contact_utilities.h
  multibody/parsing/detail_common.h
  multibody/parsing/detail_scene_graph.cc
  multibody/parsing/detail_sdf_parser.cc
  multibody/tree/fixed_offset_frame.h
  multibody/tree/frame.h
  multibody/tree/mobilizer_impl.h
  perception/depth_image_to_point_cloud.h
  solvers/evaluator_base.h
  solvers/ipopt_solver.cc
  solvers/mathematical_program_result.h
  solvers/mixed_integer_rotation_constraint.h
  solvers/mixed_integer_rotation_constraint_internal.cc
  solvers/mosek_solver.cc
  solvers/snopt_solver.cc
  solvers/solve.h
  solvers/solver_base.h
  solvers/solver_interface.h
  solvers/test/mathematical_program_test_util.h
  solvers/test/optimization_examples.h
  solvers/test/quadratic_program_examples.cc
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/semidefinite_program_examples.cc
  systems/framework/diagram_builder.h
  systems/framework/diagram_context.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/system_base.h
  systems/framework/vector_system.h
  systems/lcm/lcm_interface_system.h
  systems/primitives/linear_system.h
  systems/primitives/random_source.cc
  systems/trajectory_optimization/direct_collocation.h
  systems/trajectory_optimization/direct_transcription.cc
  systems/trajectory_optimization/direct_transcription.h
  systems/trajectory_optimization/multiple_shooting.h
Labels: priority: high, status: single reviewer ok

#12711 doc: Remove allowance for the inl.h pattern
  doc/code_style_guide.rst
  doc/cxx_inl.rst
Labels: priority: low, status: single reviewer ok

#12707 examples: Remove standalone schunk_wsg
  examples/schunk_wsg/BUILD.bazel
  examples/schunk_wsg/schunk_wsg_simulation.cc
  examples/schunk_wsg/simulated_schunk_wsg_system.cc
  examples/schunk_wsg/simulated_schunk_wsg_system.h
  examples/schunk_wsg/test/schunk_wsg_lift_test.cc
  examples/schunk_wsg/test/simulated_schunk_wsg_system_test.cc
  examples/schunk_wsg/test/test_lifter.sdf
Labels: priority: low

#12715 examples: Rewrite particles to use SceneGraph for visualization
  examples/BUILD.bazel
  examples/particles/BUILD.bazel
  examples/particles/README.md
  examples/particles/docs/uniformly_accelerated_particle_diagram.png
  examples/particles/models/particle.sdf
  examples/particles/particle.h
  examples/particles/particle_geometry.cc
  examples/particles/particle_geometry.h
  examples/particles/test/utilities_test.cc
  examples/particles/uniformly_accelerated_particle.cc
  examples/particles/utilities.cc
  examples/particles/utilities.h
Labels: priority: low

#12717 styleguide: Bump to latest commit
  tools/workspace/styleguide/repository.bzl
Labels: priority: medium, status: single reviewer ok

#12721 acrobot: Remove spurious deps from BUILD
  examples/acrobot/BUILD.bazel
Labels: priority: low, status: single reviewer ok

#12725 examples: Remove double_pendulum
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/test/double_pendulum.sdf
  bindings/pydrake/multibody/test/double_pendulum.sdf.LICENSE
  bindings/pydrake/multibody/test/plant_test.py
  examples/BUILD.bazel
  examples/double_pendulum/BUILD.bazel
  examples/double_pendulum/README.md
  examples/double_pendulum/double_pendulum_demo.cc
  examples/double_pendulum/frame_cache.cc
  examples/double_pendulum/frame_cache.h
  examples/double_pendulum/models/test.sdf
  examples/double_pendulum/sdf_helpers.cc
  examples/double_pendulum/sdf_helpers.h
  examples/double_pendulum/test/frame_cache_test.cc
  examples/double_pendulum/test/rigid_body_types_compare.cc
  examples/double_pendulum/test/rigid_body_types_compare.h
  examples/double_pendulum/test/sdf_helpers_test.cc
Labels: priority: low

#12723 pendulum: Update urdf_dynamics_test to use MultibodyPlant
  examples/pendulum/BUILD.bazel
  examples/pendulum/test/urdf_dynamics_test.cc
Labels: priority: low

#12708 examples: Remove pr2_passive_simulation
  bindings/pydrake/attic/multibody/test/parsers_test.py
  examples/pr2/BUILD.bazel
  examples/pr2/README.md
  examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf
  examples/pr2/pr2_passive_simulation.cc
  examples/pr2/test/load_pr2_simplified_test.cc
Labels: priority: low, status: do not merge, status: squashing now

#12728 Gets rid of accidental heap allocation within CalcArticulatedBodyForceBiasCache()
  multibody/tree/multibody_tree.cc
Labels: team: dynamics, type: performance

#12718 pybind: Refactor / correct bindings' code
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
Labels: status: single reviewer ok

#12727 pydrake doc: Use separate attic/documentation_pybind.h
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/attic/BUILD.bazel
  bindings/pydrake/attic/multibody/BUILD.bazel
  bindings/pydrake/attic/multibody/collision_py.cc
  bindings/pydrake/attic/multibody/joints_py.cc
  bindings/pydrake/attic/multibody/rigid_body_plant_py.cc
  bindings/pydrake/attic/multibody/rigid_body_py.cc
  bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
  bindings/pydrake/attic/multibody/shapes_py.cc
  bindings/pydrake/attic/solvers/BUILD.bazel
  bindings/pydrake/attic/solvers/ik_py.cc
  bindings/pydrake/attic/systems/BUILD.bazel
  bindings/pydrake/attic/systems/controllers_py.cc
  bindings/pydrake/attic/systems/sensors_py.cc
  bindings/pydrake/pydrake_doxygen.h
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/install/libdrake/BUILD.bazel
  tools/skylark/pybind.bzl
Labels: status: commits are properly curated

#12731 quadrotor: Split plant unit test into its own file
  examples/quadrotor/BUILD.bazel
  examples/quadrotor/test/quadrotor_dynamics_test.cc
  examples/quadrotor/test/quadrotor_plant_test.cc
Labels: priority: high, status: single reviewer ok

#12605 Add missing load of py_library rule in drake_bazel_installed
  tools/install/bazel/drake.BUILD.bazel
  tools/install/bazel/test/drake_bazel_installed_test.py
Labels: configuration: bazel, team: kitware, type: installation and distribution

#12729 Update minimum and recommended Bazel versions to 2.0 and 2.1 respectively
  CMakeLists.txt
  WORKSPACE
  doc/developers.rst
  setup/mac/binary_distribution/Brewfile
  setup/mac/source_distribution/Brewfile
  setup/mac/source_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
  tools/bazel.rc
Labels: team: kitware

#12735 Remove extern template work-arounds for GCC 6.3
  common/drake_copyable.h
  geometry/proximity/volume_mesh.h
  multibody/plant/contact_results.h
  multibody/plant/coulomb_friction.h
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/point_pair_contact_info.h
  multibody/tree/acceleration_kinematics_cache.h
  multibody/tree/articulated_body_inertia.h
  multibody/tree/articulated_body_inertia_cache.h
  multibody/tree/multibody_forces.h
  multibody/tree/position_kinematics_cache.h
  multibody/tree/rotational_inertia.h
  multibody/tree/spatial_inertia.h
  multibody/tree/unit_inertia.h
  multibody/tree/velocity_kinematics_cache.h
  systems/framework/basic_vector.h
  systems/framework/context.h
  systems/framework/event.h
  systems/framework/leaf_output_port.h
  systems/framework/output_port.h
  systems/framework/single_output_vector_source.h
  systems/framework/system.h
  systems/framework/system_output.h
Labels: priority: low, status: do not merge, status: single reviewer ok

#12710 examples: Remove uses of inl.h pattern
  examples/bead_on_a_wire/BUILD.bazel
  examples/bead_on_a_wire/bead_on_a_wire-inl.h
  examples/bead_on_a_wire/bead_on_a_wire.cc
  examples/bead_on_a_wire/bead_on_a_wire.h
  examples/rod2d/BUILD.bazel
  examples/rod2d/rod2d-inl.h
  examples/rod2d/rod2d.cc
  examples/rod2d/rod2d.h
Labels: priority: low, status: do not merge

#12734 allegro_hand: Use correct timestep and add regression test
  examples/allegro_hand/joint_control/BUILD.bazel
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/allegro_hand/joint_control/run_twisting_mug.cc
  examples/allegro_hand/joint_control/test/run_twisting_mug_test.py
Labels: priority: low

#12737 add pybind11/eigen.h to pydrake/solvers
  bindings/pydrake/solvers/gurobi_py.cc
  bindings/pydrake/solvers/ipopt_py.cc
  bindings/pydrake/solvers/mosek_py.cc
  bindings/pydrake/solvers/nlopt_py.cc
  bindings/pydrake/solvers/osqp_py.cc
  bindings/pydrake/solvers/scs_py.cc
  bindings/pydrake/solvers/snopt_py.cc
  bindings/pydrake/solvers/test/ipopt_solver_test.py
  bindings/pydrake/solvers/test/osqp_solver_test.py
  bindings/pydrake/solvers/test/scs_solver_test.py
  bindings/pydrake/solvers/test/snopt_solver_test.py
Labels: status: single reviewer ok

#12741 Add Rick, Damrong, Bel, and me to the Credits
  doc/credits.rst
Labels: status: single reviewer ok

#12733 geometry_visualization: Add Python test of publishing
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/geometry_test.py
  geometry/test/geometry_visualization_test.cc
Labels: status: single reviewer ok

#12740 Move Velocity-Implicit Euler Integrator Implementation from H to CC file and enable it in simulator_gflags.
  systems/analysis/BUILD.bazel
  systems/analysis/simulator_gflags.cc
  systems/analysis/velocity_implicit_euler_integrator.cc
  systems/analysis/velocity_implicit_euler_integrator.h
Labels: status: squashing now

#12720 compute the time derivative of signed distance between a pair of geometries
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h
  multibody/plant/BUILD.bazel
  multibody/plant/calc_distance_and_time_derivative.cc
  multibody/plant/calc_distance_and_time_derivative.h
  multibody/plant/test/calc_distance_and_time_derivative_test.cc
Labels: status: squashing now

#12732 Add a MultibodyPlant version of ConstraintRelaxingIk
  attic/manipulation/planner/BUILD.bazel
  attic/manipulation/planner/constraint_relaxing_ik_rbt.cc
  attic/manipulation/planner/constraint_relaxing_ik_rbt.h
  attic/manipulation/planner/test/constraint_relaxing_ik_rbt_test.cc
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_common.cc
  examples/kuka_iiwa_arm/iiwa_common.h
  examples/kuka_iiwa_arm/iiwa_lcm.h
  examples/kuka_iiwa_arm/kuka_plan_runner.cc
  examples/kuka_iiwa_arm/move_iiwa_ee.cc
  manipulation/planner/BUILD.bazel
  manipulation/planner/constraint_relaxing_ik.cc
  manipulation/planner/constraint_relaxing_ik.h
  manipulation/planner/test/constraint_relaxing_ik_test.cc
Labels: status: commits are properly curated

#12761 render riccati equation properly in CARE doc
  math/continuous_algebraic_riccati_equation.h
  math/discrete_algebraic_riccati_equation.h
Labels: status: single reviewer ok

#12743 lint: Remove unused *.imp file
  tools/lint/include-what-you-use.imp
Labels: priority: low, status: single reviewer ok

#12758 Fix catastrophic cancellation in point mass unit inertias.
  multibody/tree/rotational_inertia.h
  multibody/tree/test/unit_inertia_test.cc
Labels: team: dynamics, type: bug

#12750 Refactors MBT::CalcArticulatedBodyForceBiasCache()
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/tree/BUILD.bazel
  multibody/tree/articulated_body_force_bias_cache.cc
  multibody/tree/articulated_body_force_cache.cc
  multibody/tree/articulated_body_force_cache.h
  multibody/tree/body_node.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: status: single reviewer ok, team: dynamics, type: cleanup

#12726 quadrotor: Port dynamics demo to MultibodyPlant
  examples/quadrotor/BUILD.bazel
  examples/quadrotor/README.md
  examples/quadrotor/run_quadrotor_dynamics.cc
  examples/quadrotor/test/quadrotor_dynamics_test.cc
  examples/quadrotor/warehouse.sdf
Labels: priority: low

#12765 styleguide: Update sha to use cpplint changes
  tools/workspace/styleguide/repository.bzl
Labels: status: single reviewer ok

#12701 Fixes declared state and parameter counts for Diagram
  systems/framework/diagram.h
  systems/framework/leaf_system.h
  systems/framework/system.h
  systems/framework/system_base.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/system_test.cc
Labels: priority: low

#12766 multibody: Improve error message for invalid spatial inertia
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: priority: low

#12774 Link to nightly release notebooks on Binder rather than those on master
  .binder/Dockerfile
  .binder/README.md
  doc/index.rst
  tutorials/README.md
Labels: configuration: python, status: commits are properly curated, team: kitware, type: documentation

#12768 IWYU: Include initializer_list when it's used
  common/nice_type_name.cc
  geometry/geometry_set.h
  solvers/equality_constrained_qp_solver.cc
  solvers/linear_system_solver.cc
  solvers/sdpa_free_format.cc
  systems/framework/vector_base.h
Labels: status: single reviewer ok

#12762 Upgrade Drake's FCL to v0.6.1
  tools/workspace/fcl/repository.bzl
Labels: status: single reviewer ok

#12784 setup: Add eigen as a binary dependency
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-bionic.txt
Labels: priority: medium

#12744 Add a tutorial on nonlinear programming.
  tutorials/BUILD.bazel
  tutorials/mathematical_program.ipynb
  tutorials/nonlinear_program.ipynb
Labels: status: squashing now
