Repository RobotLocomotion/drake, pull requests merged in 2020-08, with the labels that each got.

#13781 Remove spdlog warning
  bindings/pydrake/common/text_logging_pybind.cc
Labels: status: single reviewer ok

#13798 math: Declare explicit class instantiations for SO(3) and SE(3)
  math/rigid_transform.cc
  math/rigid_transform.h
  math/roll_pitch_yaw.h
  math/rotation_matrix.cc
  math/rotation_matrix.h
Labels: status: single reviewer ok

#13786 workspace: Upgrade models to latest commit
  tools/workspace/models/repository.bzl
Labels: priority: low, status: single reviewer ok

#13787 workspace: Upgrade fcl to latest commit
  tools/workspace/fcl/repository.bzl
Labels: priority: low, status: single reviewer ok

#13785 Remove deprecated code (2020-08)
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/polynomial_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/framework.py
  bindings/pydrake/systems/framework_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  bindings/pydrake/systems/test/general_test.py
  common/polynomial.h
  common/test/polynomial_test.cc
  common/trajectories/piecewise_polynomial.h
  setup/mac/source_distribution/install_prereqs.sh
  solvers/solve.h
  systems/analysis/simulator.h
  tools/workspace/bitbucket.bzl
  tools/workspace/default.bzl
  tools/workspace/mirrors.bzl
  tools/workspace/tinydir/BUILD.bazel
  tools/workspace/tinydir/package.BUILD.bazel
  tools/workspace/tinydir/repository.bzl
  tools/workspace/tinydir/stub.cc
Labels: priority: low, status: single reviewer ok

#13788 workspace: Upgrade fmt to latest release 7.0.2
  common/text_logging.h
  tools/workspace/fmt/repository.bzl
Labels: priority: low, status: single reviewer ok

#13789 workspace: Upgrade scs to latest release 2.1.2
  tools/workspace/scs/package.BUILD.bazel
  tools/workspace/scs/private.c.diff
  tools/workspace/scs/private.h.diff
  tools/workspace/scs/repository.bzl
Labels: priority: low, status: single reviewer ok

#13790 workspace: Upgrade ros_xacro to latest release 1.13.6
  tools/workspace/ros_xacro/package.BUILD.bazel
  tools/workspace/ros_xacro/repository.bzl
Labels: priority: low, status: single reviewer ok

#13791 workspace: Upgrade buildifier to latest release 3.4.0
  tools/workspace/buildifier/repository.bzl
Labels: priority: low, status: single reviewer ok

#13801 workspace: Update pybind11 fork with cherry-pick from upstream
  bindings/pydrake/systems/test/custom_test.py
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok

#13752 Fix specialized QuadraticCost Eval with AutoDiff scalar.
  solvers/cost.cc
  solvers/test/cost_test.cc
Labels: status: single reviewer ok

#13699 yaml: Add SubtractDefaults to YamlWriteArchive
  common/yaml/BUILD.bazel
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/test/yaml_write_archive_defaults_test.cc
  common/yaml/test/yaml_write_archive_test.cc
  common/yaml/yaml_write_archive.cc
  common/yaml/yaml_write_archive.h
Labels: priority: medium

#13802 Fix format in TAMSIs exception message
  multibody/plant/multibody_plant.cc
Labels: component: multibody plant, status: single reviewer ok, type: bug, type: cleanup

#13806 Bump meshcat_python SHA to get generalized "start server" methods.
  bindings/pydrake/test/all_test.py
  tools/workspace/meshcat_python/repository.bzl
Labels: status: single reviewer ok

#12236 doc: Update code style guide for Python 3 and docstrings
  doc/code_style_guide.rst
  tools/workspace/styleguide/repository.bzl
Labels: priority: low

#13805 Add NOLINT markers to overly-wide non-markdown tables
  geometry/benchmarking/mesh_intersection_benchmark.cc
  geometry/benchmarking/render_benchmark.cc
  systems/analysis/runge_kutta5_integrator.cc
  systems/analysis/runge_kutta5_integrator.h
Labels: priority: low, status: single reviewer ok

#13811 Prefer triple-quote for C++ multi-line string literals
  common/schema/dev/test/stochastic_test.cc
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/test/yaml_write_archive_defaults_test.cc
  common/yaml/test/yaml_write_archive_test.cc
  geometry/render/gl_renderer/render_engine_gl.cc
  geometry/render/gl_renderer/test/shader_program_test.cc
  geometry/render/gl_renderer/test/shape_meshes_test.cc
  geometry/render/shaders/depth_shaders.h
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  systems/framework/system_html.cc
  tools/vector_gen/test/sample_test.cc
Labels: priority: low

#13730 py deprecation: Require YYYY-MM-DD to be present in message
  bindings/pydrake/common/cpp_template.py
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/common/deprecation_pybind.h
  bindings/pydrake/common/test/cpp_template_test.py
  bindings/pydrake/common/test/deprecation_example/__init__.py
  bindings/pydrake/common/test/deprecation_example/cc_module_py.cc
  bindings/pydrake/common/test/deprecation_test.py
  bindings/pydrake/math_py.cc
Labels: status: squashing now

#13807 gl_renderer: Do not install private headers
  geometry/render/gl_renderer/BUILD.bazel
  geometry/render/gl_renderer/defs.bzl
Labels: priority: low

#13804 workspace: Upgrade styleguide latest commit
  tools/workspace/styleguide/repository.bzl
Labels: priority: low, status: single reviewer ok

#13810 py eigen_geometry: Bind Quaternion.slerp
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/test/eigen_geometry_test.py
  math/quaternion.h
Labels: status: commits are properly curated

#13813 pydrake multibody: Add bindings for PlanarJoint
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok

#13814 parsing: Add support for parsing SDF and URDF from strings
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/detail_path_utils.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_sdf_parser.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/test/detail_path_utils_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/parser_test.cc
Labels: priority: high

#13821 solvers: Add GetKnownSolvers
  solvers/choose_best_solver.cc
  solvers/choose_best_solver.h
  solvers/test/choose_best_solver_test.cc
Labels: priority: low

#13822 schema: Incorporate some Anzu nit fixes
  common/schema/dev/stochastic.cc
  common/schema/dev/stochastic.h
  common/schema/dev/test/stochastic_test.cc
Labels: priority: low, status: single reviewer ok

#13796 Add PolynomialBasisElement class, and an implementation of ChebyshevBasisElement
  common/BUILD.bazel
  common/symbolic.h
  common/symbolic_chebyshev_basis_element.cc
  common/symbolic_chebyshev_basis_element.h
  common/symbolic_chebyshev_polynomial.cc
  common/symbolic_chebyshev_polynomial.h
  common/symbolic_polynomial_basis_element.cc
  common/symbolic_polynomial_basis_element.h
  common/test/symbolic_chebyshev_basis_element_test.cc
  common/test/symbolic_polynomial_basis_element_test.cc
Labels: status: squashing now

#13753 Prune unwanted dependencies and reorganize
  doc/bazel.rst
  doc/jenkins.rst
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/requirements.txt
  setup/mac/install_prereqs.sh
  setup/mac/source_distribution/Brewfile
  setup/mac/source_distribution/Brewfile-maintainer-only
  setup/mac/source_distribution/install_prereqs.sh
  setup/mac/source_distribution/requirements-maintainer-only.txt
  setup/mac/source_distribution/requirements-test-only.txt
  setup/ubuntu/binary_distribution/install_prereqs.sh
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/packages-bionic-maintainer-only.txt
  setup/ubuntu/source_distribution/packages-bionic-test-only.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal-maintainer-only.txt
  setup/ubuntu/source_distribution/packages-focal-test-only.txt
  setup/ubuntu/source_distribution/packages-focal.txt
Labels: priority: medium, team: kitware

#13823 schema: Copy rotation,transform from Anzu
  common/schema/dev/BUILD.bazel
  common/schema/dev/rotation.cc
  common/schema/dev/rotation.h
  common/schema/dev/test/rotation_test.cc
  common/schema/dev/test/transform_test.cc
  common/schema/dev/transform.cc
  common/schema/dev/transform.h
Labels: priority: medium, status: commits are properly curated

#13827 setup: Export all of the package list txt files
  setup/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok

#13826 bindings: Bind pydrake.multibody.Parser.AddModelFromString
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
Labels: priority: medium, status: single reviewer ok

#13830 setup: Really export the package list text files
  setup/BUILD.bazel
Labels: priority: medium, status: single reviewer ok

#13831 examples: Deprecate IRB140 and big_robot_toy models
  examples/irb140/README.md
  examples/kuka_iiwa_arm/models/objects/README.md
Labels: priority: low

#13839 framework: Extract DiagramState into its own file
  systems/framework/BUILD.bazel
  systems/framework/diagram_context.cc
  systems/framework/diagram_context.h
  systems/framework/diagram_state.cc
  systems/framework/diagram_state.h
Labels: priority: medium, status: commits are properly curated, status: do not merge, status: single reviewer ok

#13837 Fix documentation for CalcJacobianSpatialVelocity() and also kill PR# 12804.
  multibody/plant/multibody_plant.h
Labels: component: multibody plant, priority: medium, status: single reviewer ok, team: dynamics, type: documentation

#13842 framework: Split context code between h and cc
  systems/framework/context.cc
  systems/framework/context.h
  systems/framework/diagram_context.cc
  systems/framework/diagram_context.h
  systems/framework/event_collection.h
  systems/framework/leaf_context.cc
  systems/framework/leaf_context.h
Labels: priority: medium, status: commits are properly curated, status: single reviewer ok

#12938 Clarify documentation of symbolic::isnan
  common/symbolic_expression.h
  common/symbolic_formula.h
Labels: status: single reviewer ok

#13847 Fix doc string in show_model.py
  manipulation/util/show_model.py
Labels: status: single reviewer ok

#13848 Pass kwargs through MeshcatVisualizer to meshcat.Visualizer
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
Labels: status: single reviewer ok

#13764 Replace drake-visualizer with warning script on prebuilt Docker images
  tools/install/dockerhub/bionic/Dockerfile
  tools/install/dockerhub/focal/Dockerfile
Labels: component: distribution, priority: medium, team: kitware

#13850 parsing: Disable $HOME/.sdformat/sdformat.log
  tools/workspace/sdformat/no-console-file.patch
  tools/workspace/sdformat/repository.bzl
Labels: priority: low

#13852 context: Add cross-reference to cache design docs
  systems/framework/context.h
Labels: status: single reviewer ok

#13845 Add ToExpression to ChebyshevBasisElement.
  common/symbolic_chebyshev_basis_element.cc
  common/symbolic_chebyshev_basis_element.h
  common/symbolic_polynomial_basis_element.cc
  common/symbolic_polynomial_basis_element.h
  common/test/symbolic_chebyshev_basis_element_test.cc
  common/test/symbolic_polynomial_basis_element_test.cc
Labels: status: squashing now

#13855 Remove redundant generalized_acceleration cache from MultibodyPlant
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree_system.h
Labels: component: multibody plant, priority: high, team: dynamics

#13844 framework: Split state code between h and cc
  systems/framework/BUILD.bazel
  systems/framework/continuous_state.cc
  systems/framework/continuous_state.h
  systems/framework/diagram_continuous_state.cc
  systems/framework/diagram_continuous_state.h
  systems/framework/diagram_state.cc
  systems/framework/diagram_state.h
  systems/framework/state.cc
  systems/framework/state.h
Labels: priority: medium, status: commits are properly curated, status: single reviewer ok

#13865 cassie_benchmark: Fix nightly build break
  examples/multibody/cassie_benchmark/BUILD.bazel
Labels: status: single reviewer ok

#13856 Add more constructors and EvaluatePartial to ChebyshevBasisElement.
  common/BUILD.bazel
  common/symbolic_chebyshev_basis_element.cc
  common/symbolic_chebyshev_basis_element.h
  common/symbolic_polynomial_basis_element.cc
  common/symbolic_polynomial_basis_element.h
  common/test/symbolic_chebyshev_basis_element_test.cc
  common/test/symbolic_polynomial_basis_element_test.cc
Labels: status: squashing now

#13866 framework: Relocate diagram_builder method bodies to cc file
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
Labels: priority: low, status: single reviewer ok

#13868 bindings: Fix ConnectDrakeVisualizer keep_alive behavior
  bindings/pydrake/geometry_py.cc
Labels: status: single reviewer ok

#13881 bind `LeafOutputPort::disable_caching_by_default`
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/jupyter_widgets.py
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok

#13879 Name ports and add @system documentation for InverseDynamicsController
  systems/controllers/inverse_dynamics_controller.cc
  systems/controllers/inverse_dynamics_controller.h
Labels: status: single reviewer ok

#13773 Implement Frame::CalcSpatialAccelerationInWorld()
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/frame_kinematics_test.cc
  multibody/tree/body.h
  multibody/tree/frame.h
Labels: component: multibody plant, priority: medium, status: squashing now, team: dynamics, type: design

#13825 Release notes v0.22.0
  doc/release_notes/release_notes.rst
  doc/release_notes/v0.20.0.rst
  doc/release_notes/v0.22.0.rst
Labels: status: single reviewer ok, status: squashing now

#13887 Remove spurious uses of the inline keyword
  common/autodiff_overloads.h
  common/copyable_unique_ptr.h
  common/identifier.h
  multibody/math/spatial_vector.h
  multibody/tree/rotational_inertia.h
  multibody/tree/spatial_inertia.h
  perception/point_cloud.h
  perception/point_cloud_flags.h
  systems/controllers/setpoint.h
  systems/primitives/symbolic_vector_system.cc
Labels: priority: low, status: single reviewer ok

#13892 differential_inverse_kinematics: Fix docstring formatting
  manipulation/planner/differential_inverse_kinematics.h
Labels: status: single reviewer ok

#13896 framework: remove redundant get_input_port() and get_output_port()
  systems/framework/vector_system.h
Labels: status: single reviewer ok

#13894 examples: remove redundant get_input_port() and get_output_port()
  examples/pendulum/pendulum_plant.cc
  examples/pendulum/pendulum_plant.h
Labels: status: single reviewer ok

#13901 Revert "Add jupyter widget version of JointSliders (#13884)"
  bindings/pydrake/manipulation/simple_ui.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/jupyter_widgets.py
  bindings/pydrake/multibody/jupyter_widgets_examples.ipynb
Labels: priority: emergency, status: single reviewer ok

#13900 yaml: Change allow_yaml_with_no_cpp's default to false
  common/yaml/yaml_read_archive.cc
  common/yaml/yaml_read_archive.h
Labels: priority: low

#13899 Model Directives mechanism for scene assembly.
  common/schema/dev/BUILD.bazel
  common/schema/dev/rotation.h
  multibody/parsing/dev/BUILD.bazel
  multibody/parsing/dev/README.md
  multibody/parsing/dev/model_directives.h
  multibody/parsing/dev/process_model_directives.cc
  multibody/parsing/dev/process_model_directives.h
  multibody/parsing/dev/test/model_directives_test.cc
  multibody/parsing/dev/test/process_model_directives_test.cc
  multibody/parsing/dev/test/process_model_directives_test/add_backreference.yaml
  multibody/parsing/dev/test/process_model_directives_test/add_scoped_mid.yaml
  multibody/parsing/dev/test/process_model_directives_test/add_scoped_sub.yaml
  multibody/parsing/dev/test/process_model_directives_test/add_scoped_top.yaml
  multibody/parsing/dev/test/process_model_directives_test/circle.png
  multibody/parsing/dev/test/process_model_directives_test/package.xml
  multibody/parsing/dev/test/process_model_directives_test/simple_model.sdf
Labels: priority: low

#13906 Add a build rule and a final newline for identify_compiler
  tools/workspace/cc/BUILD.bazel
  tools/workspace/cc/identify_compiler.cc
Labels: component: build system, priority: low, status: single reviewer ok

#13898 primitives: remove redundant get_input_port() and get_output_port()
  systems/lcm/lcm_publisher_system.h
  systems/lcm/lcm_subscriber_system.h
  systems/plants/spring_mass_system/spring_mass_system.cc
  systems/plants/spring_mass_system/spring_mass_system.h
  systems/primitives/adder.h
  systems/primitives/discrete_derivative.cc
  systems/primitives/discrete_derivative.h
  systems/primitives/discrete_time_delay.cc
  systems/primitives/discrete_time_delay.h
  systems/primitives/pass_through.cc
  systems/primitives/pass_through.h
  systems/primitives/port_switch.h
  systems/primitives/saturation.cc
  systems/primitives/saturation.h
  systems/primitives/signal_logger.cc
  systems/primitives/signal_logger.h
  systems/primitives/symbolic_vector_system.cc
  systems/primitives/symbolic_vector_system.h
  systems/primitives/zero_order_hold.cc
  systems/primitives/zero_order_hold.h
Labels: status: single reviewer ok

#13909 cassie_bench: Record compiler name and version
  examples/multibody/cassie_benchmark/BUILD.bazel
  examples/multibody/cassie_benchmark/record_results.sh
  tools/workspace/cc/BUILD.bazel
Labels: status: single reviewer ok

#13913 cassie_bench: Force static linking
  examples/multibody/cassie_benchmark/BUILD.bazel
Labels: status: single reviewer ok

#13914 cassie bench: Fix blunder in benchmark configuration
  examples/multibody/cassie_benchmark/record_results.sh
Labels: status: single reviewer ok

#13912 examples: Stop depending on region of attraction, etc.
  examples/allegro_hand/BUILD.bazel
  examples/bead_on_a_wire/BUILD.bazel
  examples/bouncing_ball/BUILD.bazel
  examples/fibonacci/BUILD.bazel
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/rod2d/BUILD.bazel
  multibody/benchmarks/free_body/BUILD.bazel
Labels: priority: low, status: single reviewer ok

#13838 Consolidate code for both bias and regular (unbias) spatial accelerations.
  multibody/tree/frame.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/frames_test.cc
Labels: component: multibody plant, priority: medium, status: squashing now, team: dynamics, type: feature request

#13908 multibody: Support parsing massless bodies
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: status: squashing now

#13927 Fix a mac build error introduced in #13908
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: status: single reviewer ok

#13929 Add doxygen group for multibody systems
  multibody/plant/propeller.h
  systems/systems.h
Labels: status: single reviewer ok

#13932 Fix limit_malloc_test on macOS
  common/test_utilities/test/limit_malloc_test.cc
Labels: priority: emergency, status: single reviewer ok

#13911 Implements a LinearOperator class to be used by contact solvers.
  multibody/solvers/BUILD.bazel
  multibody/solvers/linear_operator.cc
  multibody/solvers/linear_operator.h
  multibody/solvers/sparse_linear_operator.cc
  multibody/solvers/sparse_linear_operator.h
  multibody/solvers/test/linear_operator_test.cc
  multibody/solvers/test/sparse_linear_operator_test.cc
Labels: team: dynamics

#13935 Fix limit_malloc_test on valgrind
  common/test_utilities/test/limit_malloc_test.cc
Labels: priority: high, status: single reviewer ok

#13928 Reduce heap allocation in CalcMassMatrix()
  examples/multibody/cassie_benchmark/test/cassie_bench.cc
  multibody/tree/body_node.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.cc
  multibody/tree/multibody_tree_system.h
Labels: component: multibody plant, priority: medium, team: dynamics, type: cleanup, type: performance

#13941 Adds missing import for jupyter widgets
  bindings/pydrake/systems/jupyter_widgets.py
Labels: status: single reviewer ok

#13937 schema: Add Doxygen for stochastic, rotation, translation
  common/schema/dev/rotation.h
  common/schema/dev/stochastic.h
  common/schema/dev/transform.h
Labels: priority: medium

#13933 Eliminate remaining heap use from CalcMassMatrix()
  examples/multibody/cassie_benchmark/test/cassie_bench.cc
  multibody/math/BUILD.bazel
  multibody/math/spatial_force.h
  multibody/math/test/spatial_algebra_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/spatial_inertia.h
Labels: component: multibody plant, team: dynamics, type: performance

#13948 schema: Rename gaussian std to stddev
  common/schema/dev/stochastic.cc
  common/schema/dev/stochastic.h
  common/schema/dev/test/stochastic_test.cc
Labels: priority: high

#13947 schema: Use 'class' not 'struct' for more complex types
  common/schema/dev/rotation.h
  common/schema/dev/stochastic.cc
  common/schema/dev/stochastic.h
  common/schema/dev/transform.h
Labels: priority: high

#13943 schema: Move stochastic out of dev
  common/schema/BUILD.bazel
  common/schema/dev/BUILD.bazel
  common/schema/dev/rotation.h
  common/schema/dev/transform.h
  common/schema/stochastic.cc
  common/schema/stochastic.h
  common/schema/test/stochastic_test.cc
  examples/acrobot/dev/BUILD.bazel
  examples/acrobot/dev/spong_sim.cc
  tools/install/libdrake/build_components.bzl
Labels: priority: high, status: single reviewer ok

#13953 Fix fixed-joint CalcMassMatrix() bug introduced in PR #13933.
  examples/multibody/cassie_benchmark/test/cassie_bench.cc
  multibody/plant/BUILD.bazel
  multibody/plant/test/atlas_with_fixed_joints.urdf
  multibody/plant/test/multibody_plant_mass_matrix_test.cc
  multibody/tree/multibody_tree.cc
Labels: component: multibody plant, priority: emergency, team: dynamics, type: bug

#13952 Explicitly set font-family for all monospaced HTML elements
  bindings/pydrake/doc/_static/css/custom.css
  doc/doxygen_extra.css
Labels: component: distribution, priority: high, team: kitware, type: documentation

#13967 workspace: Upgrade ros_xacro to latest release 1.13.8
  tools/workspace/ros_xacro/repository.bzl
Labels: priority: low, status: single reviewer ok

#13969 workspace: Upgrade bazel_skylib to latest release 1.0.3
  tools/workspace/bazel_skylib/repository.bzl
Labels: priority: low, status: single reviewer ok

#13951 Revise Debug-mode cache value validation to avoid heap allocation.
  common/test_utilities/limit_malloc.cc
  common/test_utilities/test/limit_malloc_test.cc
  examples/multibody/cassie_benchmark/test/cassie_bench.cc
  systems/framework/cache_entry.cc
  systems/framework/cache_entry.h
  systems/framework/diagram_output_port.h
  systems/framework/leaf_output_port.cc
  systems/framework/leaf_output_port.h
  systems/framework/output_port.cc
  systems/framework/output_port.h
  systems/framework/test/output_port_test.cc
Labels: component: system framework, priority: medium, team: dynamics, type: cleanup

#13949 schema: Move rotation and transform out of dev
  common/schema/BUILD.bazel
  common/schema/dev/BUILD.bazel
  common/schema/rotation.cc
  common/schema/rotation.h
  common/schema/stochastic.h
  common/schema/test/rotation_test.cc
  common/schema/test/stochastic_test.cc
  common/schema/test/transform_test.cc
  common/schema/transform.cc
  common/schema/transform.h
  multibody/parsing/dev/BUILD.bazel
  multibody/parsing/dev/model_directives.h
  multibody/parsing/dev/process_model_directives.cc
Labels: priority: high, status: single reviewer ok

#13940 Generic polynomial
  common/BUILD.bazel
  common/symbolic.h
  common/symbolic_generic_polynomial.cc
  common/symbolic_generic_polynomial.h
  common/symbolic_polynomial.h
  common/test/symbolic_generic_polynomial_test.cc
  common/test_utilities/symbolic_test_util.h
Labels: status: squashing now
