Repository RobotLocomotion/drake, pull requests merged in 2020-09, with the labels that each got.

#13966 workspace: Upgrade ghc_filesystem to latest release 1.3.4
  tools/workspace/ghc_filesystem/repository.bzl
Labels: priority: low, status: single reviewer ok

#13968 workspace: Upgrade fmt to latest release 7.0.3
  common/text_logging.h
  tools/workspace/fmt/repository.bzl
Labels: priority: low, status: single reviewer ok

#13939 Remove deprecated code (2020-09)
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/_plant_extra.py
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/rendering_py.cc
  bindings/pydrake/systems/test/rendering_test.py
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.h
  manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
  manipulation/schunk_wsg/schunk_wsg_position_controller.cc
  manipulation/schunk_wsg/schunk_wsg_position_controller.h
  multibody/plant/multibody_plant.h
  solvers/BUILD.bazel
  solvers/solve.cc
  solvers/solve.h
  solvers/solver_base.cc
  solvers/solver_base.h
  solvers/test/solve_test.cc
  solvers/test/solver_base_deprecated_test.cc
  systems/estimators/luenberger_observer.cc
  systems/estimators/luenberger_observer.h
  systems/estimators/test/luenberger_observer_test.cc
  systems/rendering/pose_bundle.cc
  systems/rendering/pose_bundle.h
  systems/rendering/pose_vector.cc
  systems/rendering/pose_vector.h
  systems/rendering/test/pose_bundle_to_draw_message_test.cc
  systems/rendering/test/pose_vector_test.cc
  tools/workspace/default.bzl
  tools/workspace/octomap/BUILD.bazel
  tools/workspace/octomap/package.BUILD.bazel
  tools/workspace/octomap/repository.bzl
  tools/workspace/octomap/stub.cc
  tools/workspace/ruby/BUILD.bazel
  tools/workspace/ruby/repository.bzl
Labels: priority: low

#13965 workspace: Upgrade fcl to latest commit
  tools/workspace/fcl/repository.bzl
Labels: priority: low, status: single reviewer ok

#13981 framework: Deprecate kAutoSize
  bindings/pydrake/systems/framework_py_semantics.cc
  systems/framework/framework_common.h
  systems/framework/input_port_base.h
  systems/framework/output_port.cc
  systems/framework/port_base.cc
  systems/framework/port_base.h
Labels: priority: low, status: single reviewer ok

#13982 pydrake: Copy and adapt yaml utilities from Anzu
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/yaml_test.py
  bindings/pydrake/common/yaml.py
Labels: priority: medium, status: commits are properly curated

#13959 Add SpatialMomentum to documentation for multibody_quantities_html.
  multibody/multibody_doxygen.h
Labels: component: multibody plant, priority: low, status: single reviewer ok, status: squashing now, team: dynamics, type: documentation

#13955 tools: Improve relnotes tooling
  doc/release_notes/template.txt
  tools/dev/relnotes.py
Labels: priority: low

#13996 pydrake.primitives: add binding for new PassThrough constructor
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
Labels: status: single reviewer ok

#13993 pydrake math: Add bindings for random rotations
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
Labels: status: single reviewer ok

#13986 workspace: Deprecate now-unused bullet,freetype2
  tools/dynamic_analysis/ubsan.supp
  tools/workspace/BUILD.bazel
  tools/workspace/bullet/BUILD.bazel
  tools/workspace/bullet/package.BUILD.bazel
  tools/workspace/bullet/stub.cc
  tools/workspace/freetype2/repository.bzl
Labels: priority: low

#13979 Update references to binder release URL
  doc/index.rst
  doc/installation.rst
  tutorials/README.md
Labels: team: kitware

#13991 Tidy up nits on schema classes
  common/name_value.h
  common/schema/rotation.h
  common/schema/stochastic.cc
  common/schema/stochastic.h
  common/schema/test/rotation_test.cc
  common/schema/test/stochastic_test.cc
  common/schema/test/transform_test.cc
  common/schema/transform.h
Labels: priority: low

#13997 pydrake multibody: Add bindings for CalcJacobianCenterOfMassTranslationalVelocity and CalcBiasCenterOfMassTranslationalAcceleration
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok

#13984 Separate out dependencies related to documentation generation
  setup/BUILD.bazel
  setup/mac/install_prereqs.sh
  setup/mac/source_distribution/Brewfile
  setup/mac/source_distribution/Brewfile-doc-only
  setup/mac/source_distribution/install_prereqs.sh
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/packages-bionic-doc-only.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal-doc-only.txt
  setup/ubuntu/source_distribution/packages-focal.txt
Labels: status: commits are properly curated, team: kitware

#13962 Use a faster inertia matrix rotation method
  multibody/tree/rotational_inertia.h
Labels: component: multibody plant, team: dynamics, type: performance

#14005 setup: Upgrade recommended Bazel version to 3.5
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: priority: low, status: single reviewer ok

#14007 Reformat .clang-tidy
  .clang-tidy
Labels: status: single reviewer ok

#14009 pydrake: Bind TrajectoryAffineSystem
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
Labels: status: single reviewer ok, status: squashing now

#14008 systems: Fix #14006
  systems/primitives/affine_system.cc
  systems/primitives/test/affine_system_test.cc
Labels: priority: high

#14010 [pydrake] Enable GeometryProperty copy construction in pydrake
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
Labels: status: single reviewer ok

#14014 pydrake: Add bindings for common.schema
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/all.py
  bindings/pydrake/common/schema_py.cc
  bindings/pydrake/common/test/schema_test.py
  bindings/pydrake/test/all_test.py
  common/schema/transform.cc
  common/schema/transform.h
Labels: priority: low, status: single reviewer ok

#14015 py sensors: Ensure keep_alive for Image[].data is honored
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
Labels: status: single reviewer ok

#14025 jupyter: more robust fail fast when running as non-interactive kernel
  bindings/pydrake/common/jupyter.py
Labels: status: single reviewer ok

#14027 jupyter_widgets: Make testing instructions more explicit
  bindings/pydrake/systems/jupyter_widgets.py
Labels: status: single reviewer ok

#14028 workspace: Update pybind11 fork to latest commit
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok

#14001 [render] Adds Capsule and Ellipse to RenderEngineGl
  geometry/render/gl_renderer/render_engine_gl.cc
  geometry/render/gl_renderer/render_engine_gl.h
  geometry/render/gl_renderer/shape_meshes.cc
  geometry/render/gl_renderer/shape_meshes.h
  geometry/render/gl_renderer/test/render_engine_gl_test.cc
  geometry/render/gl_renderer/test/shape_meshes_test.cc
Labels: component: geometry perception, priority: low, team: dynamics, type: feature request

#14042 Remove invalid geometry from the jaco model
  manipulation/models/jaco_description/urdf/j2n6s300.urdf
  manipulation/models/jaco_description/urdf/j2n6s300_col.urdf
Labels: status: single reviewer ok

#14040 limit_malloc: Disarm under valgrind
  common/test_utilities/limit_malloc.cc
  common/test_utilities/limit_malloc.h
  tools/dynamic_analysis/drd.sh
  tools/dynamic_analysis/helgrind.sh
  tools/dynamic_analysis/valgrind.sh
Labels: priority: emergency, status: single reviewer ok

#14046 Revert "workspace: Update pybind11 fork to latest commit"
  tools/workspace/pybind11/repository.bzl
Labels: priority: emergency, status: single reviewer ok

#14048 Restore "workspace: Update pybind11 fork to latest commit"
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok

#14049 pydrake: Move {start,end}_time() to Trajectory
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
Labels: status: single reviewer ok

#13961 Add .png schematic to show Parent/Child bodies and joint M/F frames.
  multibody/plant/images/BodyParentChildJoint.png
  multibody/plant/images/BodyParentChildJoint.txt
  multibody/plant/images/BodyParentChildJointCM.png
  multibody/plant/images/BodyParentChildJointCM.txt
  multibody/plant/multibody_plant.h
  multibody/tree/joint.h
  multibody/tree/multibody_tree.h
Labels: component: multibody plant, priority: medium, status: squashing now, team: dynamics, type: documentation

#13956 Release notes v0.23.0
  doc/release_notes/release_notes.rst
  doc/release_notes/v0.23.0.rst
  tools/dev/relnotes.py
Labels: status: single reviewer ok

#14057 meshcat: replace use of deprecated .matrix()
  bindings/pydrake/systems/meshcat_visualizer.py
Labels: status: single reviewer ok

#14035 [render] Add normal computation for parsed/generated meshes
  geometry/render/gl_renderer/BUILD.bazel
  geometry/render/gl_renderer/render_engine_gl.cc
  geometry/render/gl_renderer/render_engine_gl.h
  geometry/render/gl_renderer/shape_meshes.cc
  geometry/render/gl_renderer/shape_meshes.h
  geometry/render/gl_renderer/test/shape_meshes_test.cc
  systems/sensors/test/models/meshes/box.obj
Labels: component: geometry perception, priority: medium, team: dynamics

#14060 Fix typo in doxygen comment argument name
  systems/lcm/lcm_publisher_system.h
Labels: status: single reviewer ok

#14061 doc: Fix typo in v0.23 release notes
  doc/release_notes/v0.23.0.rst
Labels: status: single reviewer ok

#14065 Add documentation to Binding.GetNumElements()
  solvers/binding.h
Labels: status: single reviewer ok

#14069 Refactors TamsiContactResults --> ContactSolverResults
  multibody/plant/BUILD.bazel
  multibody/plant/contact_solver_results.cc
  multibody/plant/contact_solver_results.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/tamsi_solver_results.cc
Labels: component: multibody plant, status: single reviewer ok, team: dynamics

#14066 framework: Add DiagramBuilder::GetSystems
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
  systems/framework/test/diagram_builder_test.cc
Labels: priority: low

#13921 Bring global_inverse_kinematics out from attic.
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/global_inverse_kinematics.cc
  multibody/inverse_kinematics/global_inverse_kinematics.h
  multibody/inverse_kinematics/test/global_inverse_kinematics_collision_avoidance_test.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_feasible_posture_test.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.h
Labels: status: squashing now

#14062 lcm: Add publish_period option to ConnectLcmScope
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/lcm_test.py
  systems/lcm/BUILD.bazel
  systems/lcm/connect_lcm_scope.cc
  systems/lcm/connect_lcm_scope.h
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/lcm_publisher_system.h
  systems/lcm/test/connect_lcm_scope_test.cc
Labels: priority: medium

#14070 py mpb: Add bindings for LinearBushingRollPitchYaw
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok

#14072 py mbp: Fix missing runtime module import
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/test/all_each_import_test.py
Labels: status: commits are properly curated

#14063 workspace: Upgrade fcl to latest commit
  tools/workspace/fcl/repository.bzl
Labels: component: geometry proximity, status: single reviewer ok

#14074 setup: Fix typo in Ubuntu maintainer-only code
  setup/ubuntu/binary_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: priority: low

#13958 Introduce the ContactSolver interface and wire it up to MultibodyPlant.
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/contact_solver.cc
  multibody/contact_solvers/contact_solver.h
  multibody/contact_solvers/contact_solver_results.cc
  multibody/contact_solvers/contact_solver_results.h
  multibody/contact_solvers/contact_solver_utils.h
  multibody/contact_solvers/linear_operator.cc
  multibody/contact_solvers/linear_operator.h
  multibody/contact_solvers/point_contact_data.cc
  multibody/contact_solvers/point_contact_data.h
  multibody/contact_solvers/sparse_linear_operator.cc
  multibody/contact_solvers/sparse_linear_operator.h
  multibody/contact_solvers/system_dynamics_data.cc
  multibody/contact_solvers/system_dynamics_data.h
  multibody/contact_solvers/test/contact_solver_test.cc
  multibody/contact_solvers/test/linear_operator_test.cc
  multibody/contact_solvers/test/multibody_sim_driver.cc
  multibody/contact_solvers/test/multibody_sim_driver.h
  multibody/contact_solvers/test/particle_with_infinite_inertia.sdf
  multibody/contact_solvers/test/sparse_linear_operator_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/contact_jacobians.h
  multibody/plant/contact_solver_results.cc
  multibody/plant/discrete_contact_pair.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/solvers/BUILD.bazel
  multibody/solvers/sparse_linear_operator.cc
Labels: team: dynamics

#14076 yaml: Bugfix in std::optional handling
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_read_archive.h
Labels: status: squashing now

#14083 Use dreal-4.20.09.1
  tools/workspace/dreal/repository.bzl
Labels: status: single reviewer ok

#14053 Add operator +, -, * to GenericPolynomial
  common/symbolic_generic_polynomial.cc
  common/symbolic_generic_polynomial.h
  common/test/symbolic_generic_polynomial_test.cc
  common/test_utilities/symbolic_test_util.h
Labels: status: squashing now

#14091 Disable range-loop-analysis warnings for Clang 10 and Apple Clang 12
  tools/skylark/drake_cc.bzl
  tools/workspace/cc/repository.bzl
Labels: component: build system, configuration: mac, team: kitware

#14095 jupyter_widgets: add missing display import
  bindings/pydrake/multibody/jupyter_widgets.py
Labels: status: single reviewer ok

#14099 math: Deprecate expmap.h
  math/BUILD.bazel
  math/expmap.h
Labels: priority: low

#14089 parsing: Don't warn when re-discovering the same package.xml
  multibody/parsing/package_map.cc
  multibody/parsing/package_map.h
  multibody/parsing/test/package_map_test.cc
Labels: priority: low

#14088 Improve inlining for EigenPtr and RotationalInertia::ReExpress
  common/eigen_types.h
  common/symbolic_decompose.cc
  common/test/eigen_types_test.cc
  examples/acrobot/acrobot_plant.cc
  examples/mass_spring_cloth/cloth_spring_model.cc
  examples/mass_spring_cloth/cloth_spring_model.h
  math/barycentric.cc
  math/barycentric.h
  multibody/math/spatial_force.h
  multibody/plant/multibody_plant.h
  multibody/plant/tamsi_solver.cc
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/tree/model_instance.cc
  multibody/tree/rotational_inertia.h
Labels: component: multibody plant, priority: low, status: single reviewer ok, team: dynamics, type: performance

#14098 py mbp: Bind operators for SpatialVector, shifting for velocity and force
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
Labels: status: single reviewer ok

#14104 py mbp: Allow SpatialVector's to be pickled
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
Labels: status: single reviewer ok

#14092 vector_gen: Clarify which macros are to be used outside of Drake
  lcmtypes/BUILD.bazel
  tools/vector_gen/BUILD.bazel
  tools/vector_gen/vector_gen.bzl
Labels: priority: low

#14094 Fix range-loop-analysis warnings
  examples/manipulation_station/manipulation_station.cc
  geometry/geometry_visualization.cc
  geometry/proximity/test/obb_test.cc
  geometry/proximity/test/volume_to_surface_mesh_test.cc
  geometry/render/render_engine.h
  geometry/render/test/render_engine_test.cc
  geometry/scene_graph.cc
  geometry/test/geometry_state_test.cc
  multibody/contact_solvers/test/multibody_sim_driver.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: component: build system, priority: low, team: kitware

#14105 common: Don't defect use of TypeSafeIndex or Identifier references
  common/identifier.h
  common/type_safe_index.h
Labels: priority: medium, status: single reviewer ok

#14100 Add hash and divide to GenericPolynomial.
  common/symbolic_generic_polynomial.cc
  common/symbolic_generic_polynomial.h
  common/test/symbolic_generic_polynomial_test.cc
Labels: status: squashing now

#14108 py mbp: Expose ContactModel enumeration and accessor/mutators
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok

#14111 py mbp: Bind RotationalInertia and UnitInertia's ReExpress
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok

#14101 framework: Regularize VectorBase bounds checking
  systems/framework/BUILD.bazel
  systems/framework/basic_vector.h
  systems/framework/subvector.h
  systems/framework/supervector.h
  systems/framework/test/basic_vector_test.cc
  systems/framework/test/continuous_state_test.cc
  systems/framework/test/subvector_test.cc
  systems/framework/test/supervector_test.cc
  systems/framework/vector_base.h
Labels: priority: low

#14115 cassie_bench: Catch up on audodiff allocation improvements
  examples/multibody/cassie_benchmark/test/cassie_bench.cc
Labels: status: single reviewer ok

#14116 Deprecate the numpy repository
  tools/py_toolchain/BUILD.bazel
  tools/workspace/numpy/BUILD.bazel
  tools/workspace/numpy/repository.bzl
  tools/workspace/numpy/stub.cc
  tools/workspace/pybind11/package.BUILD.bazel
Labels: team: kitware

#14103 Initial port of simulator configuration helpers
  systems/analysis/BUILD.bazel
  systems/analysis/simulator_config.cc
  systems/analysis/simulator_config.h
  systems/analysis/simulator_config_functions.cc
  systems/analysis/simulator_config_functions.h
  systems/analysis/test/simulator_config_functions_test.cc
Labels: status: commits are properly curated

#14119 add pybind for AddLorentzConeConstraint.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.h
Labels: status: single reviewer ok

#14117 multibody: Use spatial_algebra.h as the sole header for the package
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/systems/rendering_py.cc
  examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
  manipulation/planner/differential_inverse_kinematics.h
  multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h
  multibody/math/BUILD.bazel
  multibody/math/spatial_acceleration.cc
  multibody/math/spatial_acceleration.h
  multibody/math/spatial_algebra.cc
  multibody/math/spatial_algebra.h
  multibody/math/spatial_force.cc
  multibody/math/spatial_force.h
  multibody/math/spatial_momentum.cc
  multibody/math/spatial_momentum.h
  multibody/math/spatial_vector.h
  multibody/math/spatial_velocity.cc
  multibody/math/spatial_velocity.h
  multibody/math/test/spatial_algebra_test.cc
  multibody/optimization/contact_wrench.h
  multibody/plant/BUILD.bazel
  multibody/plant/externally_applied_spatial_force.h
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/hydroelastic_traction_calculator.h
  multibody/test_utilities/spatial_kinematics.h
  multibody/tree/BUILD.bazel
  multibody/tree/acceleration_kinematics_cache.h
  multibody/tree/articulated_body_force_cache.h
  multibody/tree/force_element.h
  multibody/tree/frame.h
  multibody/tree/mobilizer.h
  multibody/tree/multibody_forces.h
  multibody/tree/velocity_kinematics_cache.h
  multibody/triangle_quadrature/BUILD.bazel
  multibody/triangle_quadrature/triangle_quadrature.cc
  systems/controllers/test/inverse_dynamics_test.cc
  systems/rendering/BUILD.bazel
  systems/rendering/frame_velocity.h
  systems/sensors/accelerometer.cc
  systems/sensors/gyroscope.cc
Labels: priority: low

#14122 Update solve matrix doxygen, CSDP supports socp.
  solvers/mathematical_program_doxygen.h
Labels: status: single reviewer ok

#14120 Add python binding for AddRotatedLorentzConeConstraint.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.h
Labels: status: single reviewer ok

#14125 analysis: Break simulator_test dependency on MultibodyPlant
  systems/analysis/BUILD.bazel
Labels: priority: low, status: single reviewer ok

#14130 jupyter: better description for joints with multiple positions (but just one joint name)
  bindings/pydrake/multibody/jupyter_widgets.py
Labels: status: single reviewer ok

#14131 meshcat: add option to set contact cylinder radius
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
Labels: status: single reviewer ok

#14134 jaco: Add and test for package.xml
  manipulation/models/jaco_description/package.xml
  manipulation/models/jaco_description/urdf/test/jaco_arm_test.cc
  multibody/parsing/package_map.cc
Labels: status: commits are properly curated

#14139 multibody: add binding for GetFloatingBaseBodies
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok

#14110 [geometry] Remove the non-BVH interface for rigid-soft mesh intersection
  geometry/benchmarking/README.md
  geometry/benchmarking/mesh_intersection_benchmark.cc
  geometry/proximity/bvh.cc
  geometry/proximity/bvh.h
  geometry/proximity/mesh_intersection.cc
  geometry/proximity/mesh_intersection.h
  geometry/proximity/obb.cc
  geometry/proximity/obb.h
  geometry/proximity/test/bvh_test.cc
  geometry/proximity/test/mesh_intersection_test.cc
  geometry/proximity/test/mesh_to_vtk_test.cc
Labels: component: geometry proximity, priority: medium, team: dynamics, type: cleanup

#14038 "Model directives" scene assembly DSL
  multibody/parsing/BUILD.bazel
  multibody/parsing/README_model_directives.md
  multibody/parsing/dev/BUILD.bazel
  multibody/parsing/dev/README.md
  multibody/parsing/dev/process_model_directives.h
  multibody/parsing/model_directives.h
  multibody/parsing/process_model_directives.cc
  multibody/parsing/process_model_directives.h
  multibody/parsing/scoped_names.cc
  multibody/parsing/scoped_names.h
  multibody/parsing/test/model_directives_test.cc
  multibody/parsing/test/package_map_test.cc
  multibody/parsing/test/process_model_directives_test.cc
  multibody/parsing/test/process_model_directives_test/add_backreference.yaml
  multibody/parsing/test/process_model_directives_test/add_scoped_mid.yaml
  multibody/parsing/test/process_model_directives_test/add_scoped_sub.yaml
  multibody/parsing/test/process_model_directives_test/add_scoped_top.yaml
  multibody/parsing/test/process_model_directives_test/circle.png
  multibody/parsing/test/process_model_directives_test/package.xml
  multibody/parsing/test/process_model_directives_test/simple_model.sdf
Labels: component: multibody plant, status: commits are properly curated

#14144 Add pydrake bindings for model directives.
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  multibody/parsing/BUILD.bazel
Labels: status: single reviewer ok

#14137 Adds parameters for FixedOffsetFrame
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/fixed_offset_frame.h
Labels: component: multibody plant, team: dynamics

#14143 schema: Remove rotation_rpy_deg backwards compatibility
  common/schema/test/transform_test.cc
  common/schema/transform.h
Labels: priority: low, status: single reviewer ok
