Repository RobotLocomotion/drake, pull requests merged in 2020-07, with the labels that each got.

#13610 trajectories: Remove deprecated methods 2020-07-01
  bindings/pydrake/trajectories_py.cc
  common/polynomial.h
  common/symbolic_expression.h
  common/test/polynomial_test.cc
  common/test/symbolic_expression_test.cc
  common/test/trig_poly_test.cc
  common/trajectories/piecewise_polynomial.h
  common/trajectories/piecewise_quaternion.h
  common/trig_poly.h
  systems/analysis/antiderivative_function.h
  systems/analysis/initial_value_problem.h
  systems/analysis/scalar_initial_value_problem.h
Labels: priority: low, status: single reviewer ok

#13612 examples: Remove deprecated methods 2020-07-01
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_common.cc
  examples/kuka_iiwa_arm/iiwa_common.h
Labels: priority: low, status: single reviewer ok

#13611 tools: Remove deprecated version support 2020-07-01
  CMakeLists.txt
  setup/mac/source_distribution/install_prereqs.sh
  tools/workspace/cc/repository.bzl
Labels: priority: low

#13622 workspace: Upgrade lcm to latest commit
  tools/workspace/lcm/repository.bzl
Labels: priority: low, status: single reviewer ok

#13620 workspace: Update buildifier to latest release 3.3.0
  tools/workspace/buildifier/repository.bzl
Labels: priority: low, status: single reviewer ok

#13623 workspace: Upgrade googlebenchmark to latest release
  tools/workspace/googlebenchmark/repository.bzl
Labels: priority: low, status: single reviewer ok

#13621 workspace: Upgrade fcl to latest commit
  tools/workspace/fcl/repository.bzl
Labels: priority: low, status: single reviewer ok

#13616 [render] Move RenderEngineGl out of dev into master
  geometry/render/gl_renderer/BUILD.bazel
  geometry/render/gl_renderer/buffer_dim.h
  geometry/render/gl_renderer/dev/BUILD.bazel
  geometry/render/gl_renderer/dev/render_engine_gl.cc
  geometry/render/gl_renderer/dev/render_engine_gl.h
  geometry/render/gl_renderer/dev/test/render_engine_gl_test.cc
  geometry/render/gl_renderer/render_engine_gl.cc
  geometry/render/gl_renderer/render_engine_gl.h
  geometry/render/gl_renderer/render_engine_gl_factory.h
  geometry/render/gl_renderer/test/buffer_dim_test.cc
  geometry/render/gl_renderer/test/render_engine_gl_test.cc
Labels: status: single reviewer ok, status: squashing now

#13629 Patch Mac CI - switch render_engine_gl_test to be ubuntu only
  geometry/render/gl_renderer/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok

#13615 Implement BeamModel's scalar conversion constructor
  systems/sensors/BUILD.bazel
  systems/sensors/beam_model.cc
  systems/sensors/beam_model.h
  systems/sensors/test/beam_model_test.cc
Labels: component: system framework, type: bug

#13557 [render] Add base infrastructure for declaring full camera intrinsics
  bindings/pydrake/systems/sensors_py.cc
  geometry/render/BUILD.bazel
  geometry/render/render_camera.cc
  geometry/render/render_camera.h
  geometry/render/test/render_camera_test.cc
  systems/sensors/camera_info.h
  systems/sensors/rgbd_sensor.cc
  systems/sensors/rgbd_sensor.h
  systems/sensors/test/camera_info_test.cc
  systems/sensors/test/rgbd_sensor_test.cc
Labels: component: geometry illustration, priority: high

#13600 SdpaFreeFormat can remove free variables.
  bindings/pydrake/solvers/all.py
  bindings/pydrake/solvers/sdpa_free_format_py.cc
  bindings/pydrake/test/all_test.py
  solvers/BUILD.bazel
  solvers/csdp_solver.cc
  solvers/csdp_solver.h
  solvers/csdp_solver_common.cc
  solvers/csdp_solver_internal.cc
  solvers/csdp_solver_internal.h
  solvers/sdpa_free_format.cc
  solvers/sdpa_free_format.h
  solvers/test/csdp_solver_internal_test.cc
  solvers/test/csdp_solver_test.cc
  solvers/test/sdpa_free_format_test.cc
Labels: status: squashing now

#13634 Fix Mac CI - exact comparison fails in camera_info_test
  systems/sensors/test/camera_info_test.cc
Labels: priority: emergency, status: single reviewer ok

#13587 Enable CalcBiasTranslationalAcceleration for non-world measured-in frames.
  multibody/plant/multibody_plant.h
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/linear_bushing_roll_pitch_yaw.cc
  multibody/tree/linear_bushing_roll_pitch_yaw.h
  multibody/tree/multibody_tree.cc
  multibody/tree/test/multibody_tree_test.cc
Labels: component: multibody plant, priority: high, status: squashing now, team: dynamics, type: feature request

#13632 Add ConnectMeshcatVisualizer
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
Labels: status: single reviewer ok

#13640 remove outdated tex in doc folder.
  doc/aerodynamics.texp
  doc/cartesian2cylindrical.svg
  doc/doc_cartesian2cylindrical.pdf
  doc/doc_cartesian2cylindrical.tex
  doc/ik.tex
Labels: status: single reviewer ok

#13643 Pass animation arguments through to meshcat.
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
Labels: status: single reviewer ok

#13633 Link to nlopt_cxx on Focal and do not use pkg-config
  tools/workspace/nlopt/package-macos.BUILD.bazel
  tools/workspace/nlopt/package-ubuntu-18.04.BUILD.bazel
  tools/workspace/nlopt/package-ubuntu-20.04.BUILD.bazel
  tools/workspace/nlopt/repository.bzl
Labels: component: build system, priority: high, team: kitware

#13645 Fixed method comment for CalcBiasCenterOfMassTranslationalAcceleration
  multibody/plant/multibody_plant.h
Labels: component: multibody plant, priority: medium, status: single reviewer ok, team: dynamics, type: documentation

#13652 Remove old TODO comments as CalcBiasAcceleration issues were addressed.
  multibody/plant/multibody_plant.h
Labels: component: multibody plant, priority: low, status: single reviewer ok, team: dynamics, type: cleanup

#13656 Add missing tools relating to LLVM 9
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal.txt
Labels: component: build system, priority: low, status: single reviewer ok, team: kitware

#13598 [geometry] IllustrationProperties can be updated after parsing
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  geometry/geometry_properties.cc
  geometry/geometry_properties.h
  geometry/geometry_state.cc
  geometry/internal_geometry.h
  geometry/proximity/test/hydroelastic_internal_test.cc
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/geometry_properties_test.cc
  geometry/test/geometry_state_test.cc
  geometry/test/internal_geometry_test.cc
  geometry/test/proximity_properties_test.cc
Labels: status: commits are properly curated

#13658 Tidy up documentation for TypeSafeIndex
  common/type_safe_index.h
  geometry/proximity/distance_to_shape_callback.h
  multibody/parsing/detail_scene_graph.h
  multibody/parsing/detail_urdf_geometry.h
  multibody/plant/test/multibody_plant_test.cc
Labels: status: single reviewer ok, team: dynamics, type: documentation

#13660 doc: Modernize advice regarding PYTHONPATH
  doc/python_bindings.rst
Labels: component: distribution, priority: medium, team: kitware, type: documentation

#13637 MathematicalProgram add even and odd polynomial
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  common/symbolic_monomial_util.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/sos_constraint_test.cc
Labels: component: mathematical program, status: squashing now, team: manipulation, type: feature request

#13653 Fix binding for CalcJacobianTranslationalVelocity output matrix not sized correctly
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: squashing now

#13668 Remove TODOs related to python@3.8 formula
  setup/mac/binary_distribution/Brewfile
  tools/install/install_test_helper.py
Labels: component: build system, status: single reviewer ok, team: kitware

#13667 workspace: Upgrade spdlog and fmt
  common/text_logging.h
  tools/workspace/fmt/repository.bzl
  tools/workspace/spdlog/repository.bzl
Labels: status: single reviewer ok, status: squashing now

#13651 Split mkdoc comment processing to its own module
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pybind11/mkdoc_comment.py
  tools/workspace/pybind11/test/mkdoc_comment_test.py
  tools/workspace/pybind11/test/mkdoc_test.py
  tools/workspace/pybind11/test/sample_header.h
  tools/workspace/pybind11/test/sample_header_documentation.expected.h
  tools/workspace/pybind11/test/sample_header_documentation_py_test.py
Labels: status: single reviewer ok

#13650 Upgrade to Clang 9 on Bionic
  CMakeLists.txt
  doc/bazel.rst
  doc/developers.rst
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  tools/dynamic_analysis/asan.sh
  tools/dynamic_analysis/bazel.rc
  tools/dynamic_analysis/drd.sh
  tools/dynamic_analysis/helgrind.sh
  tools/dynamic_analysis/lsan.sh
  tools/dynamic_analysis/tsan.sh
  tools/dynamic_analysis/ubsan.sh
  tools/dynamic_analysis/valgrind.sh
  tools/workspace/cc/repository.bzl
Labels: component: build system, priority: medium, status: do not merge, status: single reviewer ok, team: kitware

#13638 Python bindings for CalcBiasSpatialAcceleration, CalcBiasTranslationalAcceleration
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: squashing now

#13677 Join list of platform reviewers
  doc/developers.rst
Labels: status: single reviewer ok

#13659 [render] Implement RenderImageLabel in RenderEngineGl
  geometry/render/gl_renderer/BUILD.bazel
  geometry/render/gl_renderer/opengl_geometry.h
  geometry/render/gl_renderer/render_engine_gl.cc
  geometry/render/gl_renderer/render_engine_gl.h
  geometry/render/gl_renderer/shader_program.cc
  geometry/render/gl_renderer/shader_program.h
  geometry/render/gl_renderer/test/opengl_geometry_test.cc
  geometry/render/gl_renderer/test/render_engine_gl_test.cc
  geometry/render/gl_renderer/test/shader_program_test.cc
Labels: status: squashing now

#13676 Bug fix on workspace allocation by TAMSI.
  multibody/plant/tamsi_solver.h
  multibody/plant/test/tamsi_solver_test.cc
  multibody/plant/test/tamsi_solver_test_util.h
Labels: team: dynamics, type: bug

#13630 Use penalty method contact parameters stored in SceneGraph
  geometry/proximity_properties.cc
  geometry/proximity_properties.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: status: squashing now

#13679 yaml: Correctly write out empty sub-structs
  common/yaml/test/yaml_write_archive_test.cc
  common/yaml/yaml_write_archive.h
Labels: priority: high

#13685 Fix CI failure on csdp_solver_test.
  solvers/test/csdp_solver_test.cc
Labels: priority: emergency, status: single reviewer ok

#13687 CsdpSolver only warn once.
  solvers/csdp_solver.cc
  solvers/sdpa_free_format.cc
Labels: status: single reviewer ok

#13680 Change Doxygen comments to normal ones (#12843).
  geometry/benchmarking/mesh_intersection_benchmark.cc
  geometry/benchmarking/render_benchmark.cc
  geometry/internal_frame.h
  geometry/internal_geometry.h
  geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc
  geometry/proximity/bounding_volume_hierarchy.h
  geometry/proximity/collision_filter_legacy.h
  geometry/proximity/collisions_exist_callback.h
  geometry/proximity/distance_to_point_callback.h
  geometry/proximity/distance_to_point_with_gradient.h
  geometry/proximity/distance_to_shape_callback.h
  geometry/proximity/find_collision_candidates_callback.h
  geometry/proximity/hydroelastic_callback.h
  geometry/proximity/hydroelastic_internal.h
  geometry/proximity/make_box_field.h
  geometry/proximity/make_cylinder_field.h
  geometry/proximity/make_cylinder_mesh.h
  geometry/proximity/make_ellipsoid_field.h
  geometry/proximity/make_ellipsoid_mesh.h
  geometry/proximity/make_sphere_field.h
  geometry/proximity/make_sphere_mesh.h
  geometry/proximity/mesh_intersection.cc
  geometry/proximity/mesh_to_vtk.cc
  geometry/proximity/mesh_to_vtk.h
  geometry/proximity/obj_to_surface_mesh.cc
  geometry/proximity/penetration_as_point_pair_callback.h
  geometry/proximity/plane.h
  geometry/proximity/posed_half_space.h
  geometry/proximity/proximity_utilities.h
  geometry/proximity/sorted_triplet.h
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/hydroelastic_internal_test.cc
  geometry/proximity/test/mesh_half_space_intersection_test.cc
  geometry/proximity/volume_to_surface_mesh.h
  geometry/proximity_engine.h
  geometry/proximity_properties.h
  geometry/render/render_label_class.h
  geometry/render/test/render_engine_ospray_test.cc
  geometry/render/test/render_engine_vtk_test.cc
  geometry/test_utilities/dummy_render_engine.h
  geometry/utilities.h
Labels: priority: medium

#13693 wsg_50_description: Deprecate the URDF and meshes
  manipulation/models/wsg_50_description/README.md
Labels: status: single reviewer ok

#13654 Release notes v0.20.0
  doc/release_notes/release_notes.rst
  doc/release_notes/v0.20.0.rst
Labels: status: single reviewer ok

#13555 pydrake doc: Elaborate on how to discover C++ Python bindings
  bindings/pydrake/pydrake_doxygen.h
Labels: priority: medium

#13474 Unit test CalcForceElementsContribution() includes gravity.
  multibody/plant/test/multibody_plant_test.cc
Labels: component: multibody plant, team: dynamics, type: feature request

#13704 Tell gojs to autoscale for javascript system diagrams
  systems/framework/system_html.cc
Labels: status: single reviewer ok

#13703 Add python binding for AddLinearEqualityConstraint overload.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.h
Labels: status: single reviewer ok

#13696 Prep TAMSI for discrete hydro info
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/tamsi_solver.cc
  multibody/plant/tamsi_solver.h
  multibody/plant/test/tamsi_solver_test.cc
Labels: component: multibody plant, team: dynamics

#13721 doc: Add v0.20.0 warning about GoJS
  doc/release_notes/v0.20.0.rst
Labels: priority: high, status: single reviewer ok

#13712 Fixes sub-stepping update of fn0.
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: team: dynamics, type: bug

#13720 framework: Remove GoJS from GenerateHtml; rendering is now broken
  systems/framework/system_html.cc
  systems/framework/system_html.h
  tutorials/dynamical_systems.ipynb
Labels: priority: high, status: single reviewer ok

#13725 Fix typo.
  tutorials/README.md
Labels: priority: high, status: single reviewer ok, team: dynamics, type: cleanup, type: documentation

#13706 Makes inverse dynamics system const
  systems/controllers/inverse_dynamics.cc
  systems/controllers/inverse_dynamics.h
Labels: status: squashing now, type: cleanup

#13716 pydrake_pybind: Use simplified alias py_rvp
  bindings/pydrake/attic/multibody/collision_py.cc
  bindings/pydrake/attic/multibody/rigid_body_plant_py.cc
  bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
  bindings/pydrake/attic/multibody/shapes_py.cc
  bindings/pydrake/attic/systems/sensors_py.cc
  bindings/pydrake/common/eigen_pybind.h
  bindings/pydrake/common/test/wrap_test_util_py.cc
  bindings/pydrake/common/value_pybind.h
  bindings/pydrake/common/wrap_pybind.h
  bindings/pydrake/examples/acrobot_py.cc
  bindings/pydrake/examples/compass_gait_py.cc
  bindings/pydrake/examples/manipulation_station_py.cc
  bindings/pydrake/examples/pendulum_py.cc
  bindings/pydrake/examples/rimless_wheel_py.cc
  bindings/pydrake/examples/van_der_pol_py.cc
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/manipulation/schunk_wsg_py.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/perception_py.cc
  bindings/pydrake/pydrake_doxygen.h
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/rendering_py.cc
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/test/pydrake_pybind_test.cc
Labels: status: single reviewer ok

#13723 geometry: Fix minor broken URL for benchmarking
  geometry/benchmarking/README.md
Labels: status: single reviewer ok

#13728 getting_help: Add note about inviting people directly to Slack
  doc/getting_help.rst
Labels: status: single reviewer ok

#13732 yaml: Move method definition to cc file
  common/yaml/yaml_write_archive.cc
  common/yaml/yaml_write_archive.h
Labels: priority: medium, status: single reviewer ok

#13733 yaml: Factor out example_structs for unit tests
  common/yaml/BUILD.bazel
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/test/yaml_write_archive_test.cc
Labels: priority: low, status: single reviewer ok

#13682 Performance tweak to MultibodyTree.CalcJacobianAngularAndOrTranslationalVelocityInWorld
  bindings/pydrake/multibody/tree_py.cc
  multibody/tree/BUILD.bazel
  multibody/tree/multibody_tree.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: status: squashing now

#13724 doc: Add release notes v0.21.0
  doc/release_notes/release_notes.rst
  doc/release_notes/v0.21.0.rst
Labels: status: single reviewer ok

#13740 Reformat text in mkdoc comment text
  tools/workspace/pybind11/test/mkdoc_comment_test.py
Labels: status: single reviewer ok

#13698 Rename libspdlog.so to libdrake_spdlog.so
  tools/workspace/spdlog/package-create-cps.py
  tools/workspace/spdlog/package.BUILD.bazel
Labels: component: distribution, priority: low, status: single reviewer ok, team: kitware

#13759 CSDP on mac should have a different numerical tolerance.
  solvers/test/csdp_solver_test.cc
Labels: status: single reviewer ok

#13743 setup: Update recommended Bazel version to 3.4
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: priority: low, status: single reviewer ok

#13757 Make set_default_positions an NVI
  multibody/tree/ball_rpy_joint.h
  multibody/tree/joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/revolute_joint.h
  multibody/tree/universal_joint.h
  multibody/tree/weld_joint.h
Labels: component: multibody plant, team: dynamics, type: bug

#13761 pydrake: Improve unit test error message
  bindings/pydrake/test/all_test.py
Labels: status: single reviewer ok

#13762 Fix line length and whitespace nits throughout
  attic/multibody/approximate_ik.cc
  attic/multibody/global_inverse_kinematics.h
  attic/multibody/ik_options.h
  attic/multibody/rigid_body.h
  attic/multibody/rigid_body_ik.h
  common/trajectories/discrete_time_trajectory.h
  examples/scene_graph/solar_system.h
  geometry/geometry_roles.h
  geometry/proximity/contact_surface_utility.h
  geometry/query_object.h
  math/autodiff_gradient.h
  multibody/parsing/detail_scene_graph.h
  multibody/plant/propeller.h
  multibody/plant/tamsi_solver.h
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.h
  solvers/test_utilities/check_constraint_eval_nonsymbolic.h
  systems/analysis/implicit_euler_integrator.h
  systems/analysis/integrator_base.h
  systems/analysis/velocity_implicit_euler_integrator.h
  systems/framework/system_html.h
Labels: priority: low, status: single reviewer ok

#13765 Relax the tolerance on the Motzkin example for mosek test.
  solvers/test/mosek_solver_test.cc
Labels: status: single reviewer ok

#13766 Ignore debian directory during bazel build and doxygen doc generation
  .bazelignore
  doc/doxygen_main.py
Labels: component: distribution, priority: low, status: single reviewer ok, team: kitware

#13772 Replace tabs with spaces in xml files
  examples/atlas/sdf/block_angle_steps_1/model.rsdf
  examples/atlas/sdf/block_angle_steps_2/model.rsdf
  examples/atlas/urdf/robotiq.urdf
  examples/atlas/urdf/robotiq_simple.urdf
  examples/atlas/urdf/robotiq_tendons.urdf
  examples/irb140/urdf/irb_140_robotiq.urdf
  examples/irb140/urdf/irb_140_robotiq_ati.urdf
  examples/irb140/urdf/irb_140_robotiq_simple_ati.urdf
  manipulation/models/jaco_description/urdf/j2n6s300.urdf
  manipulation/models/jaco_description/urdf/j2n6s300_col.urdf
Labels: status: single reviewer ok

#13774 Simplify SDFormat //pose elements
  bindings/pydrake/multibody/test/two_bodies.sdf
  examples/acrobot/Acrobot.sdf
  examples/allegro_hand/joint_control/simple_mug.sdf
  examples/atlas/sdf/cinder_block_2/model.sdf
  examples/atlas/sdf/cinder_block_wide/model.sdf
  examples/atlas/sdf/drc_practice_task_2.world
  examples/atlas/urdf/atlas_convex_hull.urdf
  examples/atlas/urdf/atlas_minimal_contact.urdf
  examples/kuka_iiwa_arm/models/desk/transcendesk55inch.sdf
  examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf
  examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table_surface_only_collision.sdf
  examples/manipulation_station/models/061_foam_brick.sdf
  examples/manipulation_station/models/amazon_table_simplified.sdf
  examples/manipulation_station/models/bin.sdf
  examples/manipulation_station/models/cupboard.sdf
  examples/manipulation_station/models/cylinder.sdf
  examples/manipulation_station/models/sphere.sdf
  examples/manipulation_station/models/thin_box.sdf
  examples/manipulation_station/models/thin_cylinder.sdf
  examples/multibody/cart_pole/cart_pole.sdf
  examples/multibody/four_bar/four_bar.sdf
  examples/planar_gripper/planar_brick.sdf
  examples/planar_gripper/planar_gripper.sdf
  examples/planar_gripper/planar_gripper.xacro
  examples/quadrotor/warehouse.sdf
  examples/simple_four_bar/FourBar.sdf
  examples/simple_gripper/simple_gripper.sdf
  examples/simple_gripper/simple_mug.sdf
  manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf
  manipulation/models/allegro_hand_description/sdf/allegro_hand_description_right.sdf
  manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf
  manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf
  manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
  manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf
  manipulation/models/wsg_50_description/sdf/schunk_wsg_50.sdf
  manipulation/models/wsg_50_description/sdf/schunk_wsg_50_ball_contact.sdf
  manipulation/models/ycb/sdf/003_cracker_box.sdf
  manipulation/models/ycb/sdf/004_sugar_box.sdf
  manipulation/models/ycb/sdf/005_tomato_soup_can.sdf
  manipulation/models/ycb/sdf/006_mustard_bottle.sdf
  manipulation/models/ycb/sdf/009_gelatin_box.sdf
  manipulation/models/ycb/sdf/010_potted_meat_can.sdf
  multibody/benchmarks/acrobot/acrobot.sdf
  multibody/parsing/test/links_with_visuals_and_collisions.urdf
  multibody/parsing/test/package_map_test_packages/package_map_test_package_a/sdf/test_model.sdf
  multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf
  multibody/plant/test/box.sdf
  systems/sensors/models/box.sdf
  systems/sensors/models/sphere.sdf
  systems/sensors/test/models/box.sdf
  systems/sensors/test/models/box_with_mesh.sdf
  systems/sensors/test/models/nothing.sdf
  systems/sensors/test/models/sphere.sdf
Labels: status: single reviewer ok
