Repository RobotLocomotion/drake, pull requests merged in 2020-05, with the labels that each got.

#13188 workspace: Switch sdformat and ignition_math to GitHub
  tools/workspace/ignition_math/repository.bzl
  tools/workspace/sdformat/repository.bzl
Labels: status: single reviewer ok

#13169 attic,examples: Remove deprecated code 2020-05
  attic/manipulation/util/BUILD.bazel
  attic/manipulation/util/README.md
  attic/manipulation/util/robot_state_msg_translator.cc
  attic/manipulation/util/robot_state_msg_translator.h
  attic/manipulation/util/sim_diagram_builder.cc
  attic/manipulation/util/sim_diagram_builder.h
  attic/manipulation/util/test/robot_state_msg_translator_test.cc
  attic/manipulation/util/test/sim_diagram_builder_test.cc
  attic/manipulation/util/world_sim_tree_builder.h
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_common.cc
  examples/kuka_iiwa_arm/iiwa_common.h
  examples/kuka_iiwa_arm/iiwa_world/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_world/README.md
  examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.cc
  examples/kuka_iiwa_arm/iiwa_world/iiwa_wsg_diagram_factory.h
  examples/kuka_iiwa_arm/iiwa_world/multi_arm_with_gripper_demo.cc
  examples/kuka_iiwa_arm/iiwa_world/test/iiwa_wsg_diagram_factory_test.cc
  examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
  examples/kuka_iiwa_arm/kuka_torque_controller.cc
  examples/kuka_iiwa_arm/kuka_torque_controller.h
  examples/kuka_iiwa_arm/oracular_state_estimator.cc
  examples/kuka_iiwa_arm/oracular_state_estimator.h
  examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc
  examples/kuka_iiwa_arm/test/iiwa_wsg_simulation_installed_test.py
  examples/kuka_iiwa_arm/test/kuka_torque_controller_test.cc
  tools/install/libdrake/build_components.bzl
Labels: priority: backlog, status: single reviewer ok

#13170 common,geometry,multibody: Remove deprecated code 2020-05
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  common/BUILD.bazel
  common/drake_nodiscard.h
  common/test/drake_nodiscard_test.cc
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  examples/multibody/rolling_sphere/make_rolling_sphere_plant.cc
  geometry/BUILD.bazel
  geometry/identifier.cc
  geometry/identifier.h
  geometry/scene_graph_inspector.h
  geometry/test/scene_graph_inspector_test.cc
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  multibody/parsing/test/acrobot_parser_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/kuka_iiwa_model_tests.h
  systems/analysis/test_utilities/generic_integrator_test.h
  systems/controllers/test/inverse_dynamics_controller_test.cc
  systems/controllers/test/inverse_dynamics_test.cc
Labels: priority: backlog, status: single reviewer ok

#13171 setup,tools: Remove deprecated code 2020-05
  setup/mac/source_distribution/install_prereqs.sh
  solvers/BUILD.bazel
  solvers/no_snopt.cc
  tools/BUILD.bazel
  tools/bazel.rc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/json/BUILD.bazel
  tools/workspace/json/package.BUILD.bazel
  tools/workspace/json/repository.bzl
  tools/workspace/json/stub.cc
Labels: priority: backlog, status: single reviewer ok

#13172 systems: Remove deprecated code 2020-05
  systems/analysis/simulator.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_base.h
  systems/framework/test/system_base_test.cc
Labels: priority: backlog, status: single reviewer ok

#13193 workspace: Deprecate bitbucket.bzl
  tools/lint/buildifier-tables.json
  tools/workspace/README.md
  tools/workspace/bitbucket.bzl
  tools/workspace/github.bzl
  tools/workspace/mirrors.bzl
  tools/workspace/new_release.py
Labels: priority: backlog, status: single reviewer ok

#13190 tools: Disable python imports from ~/.local (pip -U)
  tools/ubuntu-bionic.bazelrc
Labels: priority: low

#13189 third_party: Remove spurious include path
  third_party/com_github_finetjul_bender/BUILD.bazel
Labels: priority: medium, status: single reviewer ok

#13198 workspace: Upgrade buildifier to latest release 3.0.0
  tools/workspace/buildifier/repository.bzl
Labels: priority: backlog, status: single reviewer ok

#13195 py common: Use kDrakeAssertIsArmed instead of _DRAKE_ASSERT_IS_ARMED
  bindings/pydrake/common/__init__.py
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/module_test.py
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: status: single reviewer ok

#13200 workspace: Upgrade fmt to latest release 6.2.0
  common/text_logging.h
  tools/workspace/fmt/repository.bzl
Labels: priority: low, status: single reviewer ok

#13203 getting_help: Remove stray asterisk, add template on helper commands
  doc/getting_help.rst
Labels: status: single reviewer ok

#13199 workspace: Upgrade lcm to latest commit
  tools/workspace/lcm/repository.bzl
Labels: priority: backlog, status: single reviewer ok

#13196 tools: Improve new_release checking heuristics
  tools/workspace/new_release.py
Labels: priority: backlog, status: single reviewer ok

#12430 py common: Move AbstractValue and Value here
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
  bindings/pydrake/attic/systems/test/sensors_test.py
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/all.py
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/common/test/value_test.py
  bindings/pydrake/common/test/value_test_util_py.cc
  bindings/pydrake/common/test/wrap_pybind_test.py
  bindings/pydrake/common/value_py.cc
  bindings/pydrake/common/value_pybind.h
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/systems/framework.py
  bindings/pydrake/systems/framework_py.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/perception.py
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
  bindings/pydrake/systems/test/perception_test.py
  bindings/pydrake/systems/test/primitives_test.py
  bindings/pydrake/systems/test/rendering_test.py
  bindings/pydrake/systems/test/sensors_test.py
  bindings/pydrake/systems/test/test_util_py.cc
  bindings/pydrake/systems/test/value_test.py
  bindings/pydrake/test/geometry_test.py
  bindings/pydrake/test/math_test.py
  bindings/pydrake/test/perception_test.py
Labels: priority: medium

#13197 workspace: Upgrade pycodestyle to latest release 2.5.0
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/system_sliders_test.py
  common/test/cpplint_wrapper.py
  manipulation/util/meshlab_to_sdf.py
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/lint/bazel_lint.bzl
  tools/lint/buildifier.py
  tools/lint/library_lint.bzl
  tools/lint/python_lint.bzl
  tools/skylark/drake_cc.bzl
  tools/workspace/deb.bzl
  tools/workspace/github.bzl
  tools/workspace/pycodestyle/repository.bzl
  tools/workspace/semantic_version/repository.bzl
Labels: priority: low, status: single reviewer ok

#13191 drake_py_unittest: Force Drake deprecation warnings at import to be errors
  common/test_utilities/drake_py_unittest_main.py
Labels: status: single reviewer ok

#13217 Revert "py common: Move AbstractValue and Value here"
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
  bindings/pydrake/attic/systems/test/sensors_test.py
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/all.py
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/common/test/value_test.py
  bindings/pydrake/common/test/value_test_util_py.cc
  bindings/pydrake/common/test/wrap_pybind_test.py
  bindings/pydrake/common/value_py.cc
  bindings/pydrake/common/value_pybind.h
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/systems/framework.py
  bindings/pydrake/systems/framework_py.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/perception.py
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
  bindings/pydrake/systems/test/perception_test.py
  bindings/pydrake/systems/test/primitives_test.py
  bindings/pydrake/systems/test/rendering_test.py
  bindings/pydrake/systems/test/sensors_test.py
  bindings/pydrake/systems/test/test_util_py.cc
  bindings/pydrake/systems/test/value_test.py
  bindings/pydrake/test/geometry_test.py
  bindings/pydrake/test/math_test.py
  bindings/pydrake/test/perception_test.py
Labels: priority: emergency, status: single reviewer ok

#13223 models: Sort lists alphabetically for better maintainability
  tools/workspace/models/files.bzl
  tools/workspace/models/package.BUILD.bazel
Labels: priority: medium, status: single reviewer ok

#13178 controllers: Support for Finite-Horizon LQR result as a System
  bindings/pydrake/common/test/wrap_pybind_test.py
  bindings/pydrake/common/test/wrap_test_util_py.cc
  bindings/pydrake/common/wrap_pybind.h
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/test/controllers_test.py
  systems/controllers/BUILD.bazel
  systems/controllers/finite_horizon_linear_quadratic_regulator.cc
  systems/controllers/finite_horizon_linear_quadratic_regulator.h
  systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Labels: priority: medium

#13228 pybind: Avoid duplicate linting with `add_pybind_coverage_data`
  tools/skylark/pybind.bzl
Labels: status: single reviewer ok

#13229 multibody: add python binding for get_body_poses_output_port()
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok

#13222 models: Move jaco meshes to RobotLocomotion/models
  manipulation/models/jaco_description/BUILD.bazel
  manipulation/models/jaco_description/meshes/arm.obj
  manipulation/models/jaco_description/meshes/arm_half_1.obj
  manipulation/models/jaco_description/meshes/arm_half_2.obj
  manipulation/models/jaco_description/meshes/arm_mico.obj
  manipulation/models/jaco_description/meshes/base.obj
  manipulation/models/jaco_description/meshes/finger_distal.obj
  manipulation/models/jaco_description/meshes/finger_proximal.obj
  manipulation/models/jaco_description/meshes/forearm.obj
  manipulation/models/jaco_description/meshes/forearm_mico.obj
  manipulation/models/jaco_description/meshes/hand_2finger.obj
  manipulation/models/jaco_description/meshes/hand_3finger.obj
  manipulation/models/jaco_description/meshes/ring_big.obj
  manipulation/models/jaco_description/meshes/ring_small.obj
  manipulation/models/jaco_description/meshes/shoulder.obj
  manipulation/models/jaco_description/meshes/wrist.obj
  manipulation/models/jaco_description/meshes/wrist_spherical_1.obj
  manipulation/models/jaco_description/meshes/wrist_spherical_2.obj
  tools/workspace/models/files.bzl
  tools/workspace/models/package.BUILD.bazel
  tools/workspace/models/repository.bzl
Labels: priority: medium, status: single reviewer ok

#13232 geometry_properties: Explicitly test number of copies / moves
  geometry/test/geometry_properties_test.cc
Labels: status: single reviewer ok

#13233 pydrake: Remove old (undated) deprecations
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/attic/multibody/BUILD.bazel
  bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/examples/manipulation_station_py.cc
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/trajectory_optimization_py.cc
  bindings/pydrake/test/geometry_test.py
Labels: priority: low, status: single reviewer ok

#13216 Add instructions for getting Stackoverflow drake-tag notifications.
  doc/developers.rst
  doc/stackoverflow_notifications.rst
Labels: priority: low

#13235 setup: Install /usr/bin/python for Focal source builds
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: priority: backlog

#13204 lint: Enable W504 for python
  bindings/pydrake/attic/multibody/test/rigid_body_tree_test.py
  bindings/pydrake/attic/systems/test/controllers_test.py
  bindings/pydrake/common/cpp_const.py
  bindings/pydrake/common/cpp_template.py
  bindings/pydrake/common/test_utilities/numpy_compare.py
  bindings/pydrake/doc/pydrake_sphinx_extension.py
  bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py
  bindings/pydrake/examples/test/acrobot_test.py
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/test/controllers_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/rendering_test.py
  bindings/pydrake/test/geometry_test.py
  common/proto/call_python_client.py
  common/test/resource_tool_test.py
  common/test_utilities/drake_py_unittest_main.py
  examples/manipulation_station/differential_ik.py
  manipulation/util/test/geometry_inspector_test.py
  third_party/com_github_pybind_pybind11/mkdoc.py
  tools/install/libdrake/build_components_refresh.py
  tools/lint/bazel_lint.bzl
  tools/lint/buildifier.py
  tools/lint/clang_format_includes.py
  tools/lint/drakelint.py
  tools/lint/formatter.py
  tools/lint/library_lint_reporter.py
  tools/lint/python_lint.bzl
  tools/lint/test/buildifier_test.py
  tools/lint/test/util_test.py
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_image.py
  tools/workspace/drake_visualizer/drake_visualizer_bazel.py
Labels: priority: backlog, status: single reviewer ok

#13239 nice_type_name: Update test for anonymous namespaces
  common/test/nice_type_name_test.cc
Labels: status: single reviewer ok

#13230 tools: Trim FCL to only compile the parts we need
  tools/workspace/BUILD.bazel
  tools/workspace/fcl/package.BUILD.bazel
  tools/workspace/octomap/BUILD.bazel
  tools/workspace/octomap/package.BUILD.bazel
  tools/workspace/octomap/stub.cc
Labels: priority: medium

#13225 pydrake: Resolve RTTI inconsistency on macOS, restore pydrake Value move
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
  bindings/pydrake/attic/systems/test/sensors_test.py
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/all.py
  bindings/pydrake/common/cpp_param_pybind.cc
  bindings/pydrake/common/cpp_param_pybind.h
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/eigen_geometry_pybind.h
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/cpp_param_pybind_test.cc
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/common/test/value_test.py
  bindings/pydrake/common/test/value_test_util_py.cc
  bindings/pydrake/common/test/wrap_pybind_test.py
  bindings/pydrake/common/test/wrap_test_util_py.cc
  bindings/pydrake/common/value_py.cc
  bindings/pydrake/common/value_pybind.h
  bindings/pydrake/common/wrap_pybind.h
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/systems/framework.py
  bindings/pydrake/systems/framework_py.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/perception.py
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
  bindings/pydrake/systems/test/perception_test.py
  bindings/pydrake/systems/test/primitives_test.py
  bindings/pydrake/systems/test/rendering_test.py
  bindings/pydrake/systems/test/sensors_test.py
  bindings/pydrake/systems/test/test_util_py.cc
  bindings/pydrake/systems/test/value_test.py
  bindings/pydrake/test/geometry_test.py
  bindings/pydrake/test/math_test.py
  bindings/pydrake/test/perception_test.py
Labels: status: squashing now

#13243 Revert "[geometry] Parcel QueryObject queries into unique classes"
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  geometry/BUILD.bazel
  geometry/perception_query_object.cc
  geometry/perception_query_object.h
  geometry/proximity_query_object.cc
  geometry/proximity_query_object.h
  geometry/query_object.cc
  geometry/query_object.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/perception_query_object_test.cc
  geometry/test/proximity_query_object_test.cc
Labels: status: single reviewer ok

#13226 [render/dev] Start pulling mesh generation *out* of render engine
  geometry/render/gl_renderer/dev/BUILD.bazel
  geometry/render/gl_renderer/dev/load_mesh.cc
  geometry/render/gl_renderer/dev/render_engine_gl.cc
  geometry/render/gl_renderer/dev/render_engine_gl.h
  geometry/render/gl_renderer/dev/shape_meshes.cc
  geometry/render/gl_renderer/dev/shape_meshes.h
  geometry/render/gl_renderer/dev/test/load_mesh_test.cc
  geometry/render/gl_renderer/dev/test/shape_meshes_test.cc
Labels: status: squashing now

#13256 Add some Dynamics component labels for GitHub issues
  doc/issues.rst
Labels: priority: low, team: dynamics, type: documentation

#13252 examples: make Acrobot swing-up with trajectory optimization SNOPT only
  examples/acrobot/BUILD.bazel
  examples/acrobot/test/run_swing_up_traj_optimization.cc
  systems/trajectory_optimization/direct_collocation.cc
Labels: status: single reviewer ok

#13055 multibody: Implement UniversalJoint
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/tree/BUILD.bazel
  multibody/tree/ball_rpy_joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/space_xyz_mobilizer.h
  multibody/tree/test/free_rotating_body_test.cc
  multibody/tree/test/universal_joint_test.cc
  multibody/tree/universal_joint.cc
  multibody/tree/universal_joint.h
  multibody/tree/weld_joint.h
Labels: status: commits are properly curated

#13262 workspace: Remove dependency on ruby
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  tools/workspace/default.bzl
  tools/workspace/ruby/repository.bzl
  tools/workspace/sdformat/3bbd303.patch
  tools/workspace/sdformat/BUILD.bazel
  tools/workspace/sdformat/embed_sdf.py
  tools/workspace/sdformat/package.BUILD.bazel
  tools/workspace/sdformat/repository.bzl
Labels: priority: medium

#13260 setup: Add dependency on clang-format-9
  setup/mac/source_distribution/Brewfile
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal.txt
Labels: priority: low, status: single reviewer ok

#13265 parsing: Add regression test for libsdformat version upgrades
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/sdf_parser_test/very_old_version.sdf
Labels: priority: low, status: single reviewer ok

#13263 Temporarily remove //examples/acrobot:run_swing_up_traj_optimization_test
  examples/acrobot/BUILD.bazel
Labels: status: single reviewer ok

#13270 py systems: Bind OutputPort.Allocate(), DiagramBuilder.empty(), .GetMutableSystems()
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: commits are properly curated, status: single reviewer ok

#13268 workspace: Remove vestigial sdformat build rules
  tools/workspace/sdformat/BUILD.bazel
  tools/workspace/sdformat/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok

#13049 Update to gurobi9.
  CMakeLists.txt
  cmake/modules/FindGurobi.cmake
  doc/bazel.rst
  doc/python_bindings.rst
  solvers/gurobi_solver.cc
  solvers/gurobi_solver.h
  solvers/solver_options.h
  solvers/test/gurobi_solver_test.cc
  tools/bazel.rc
  tools/dynamic_analysis/tsan.supp
  tools/workspace/gurobi/package-macos.BUILD.bazel.in
  tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in
  tools/workspace/gurobi/repository.bzl
Labels: priority: medium, status: squashing now

#13267 Add module for "accuracy" and "tolerance" conventions
  doc/doxygen.h
  systems/analysis/integrator_base.h
Labels: priority: low, team: dynamics, type: documentation

#13274 [geometry] Update FCL to latest commit
  tools/workspace/fcl/repository.bzl
Labels: status: single reviewer ok

#13273 Remove unittest deprecation warnings
  manipulation/util/test/meshlab_to_sdf_test.py
  tools/lint/test/formatter_test.py
Labels: priority: backlog, status: single reviewer ok

#13277 Fix a couple of typos in accuracy/tolerance doc.
  doc/doxygen.h
Labels: priority: low, status: single reviewer ok

#13259 tools: Upgrade to clang-format-9 for includes
  attic/multibody/kinematics_cache.cc
  tools/lint/clang_format.py
  tools/lint/drakelint.py
  tools/lint/formatter.py
  tools/lint/test/formatter_test.py
Labels: priority: high

#13286 tools: Change order of third-party includes
  .clang-format
  attic/systems/sensors/test/depth_sensor_to_lcm_point_cloud_message_test.cc
  bindings/pydrake/.clang-format
  bindings/pydrake/autodiff_types_pybind.h
  bindings/pydrake/common/eigen_geometry_pybind.h
  bindings/pydrake/common/eigen_pybind.h
  bindings/pydrake/common/test/cpp_param_pybind_test.cc
  bindings/pydrake/common/test/cpp_template_pybind_test.cc
  bindings/pydrake/common/test/eigen_geometry_test_util_py.cc
  bindings/pydrake/common/test/type_safe_index_pybind_test.cc
  bindings/pydrake/systems/rendering_py.cc
  bindings/pydrake/test/pydrake_pybind_test.cc
  common/yaml/yaml_read_archive.h
  common/yaml/yaml_write_archive.h
  examples/allegro_hand/joint_control/run_twisting_mug.cc
  examples/kinova_jaco_arm/jaco_controller.cc
  examples/kinova_jaco_arm/move_jaco_ee.cc
  examples/kuka_iiwa_arm/iiwa_controller.cc
  examples/kuka_iiwa_arm/move_iiwa_ee.cc
  examples/kuka_iiwa_arm/test/optitrack_test.cc
  examples/simple_gripper/simple_gripper.cc
  geometry/benchmarking/mesh_intersection_benchmark.cc
  geometry/benchmarking/render_benchmark.cc
  geometry/render/render_engine_vtk_base.cc
  lcm/test/drake_lcm_test.cc
  lcm/test/drake_lcm_thread_test.cc
  manipulation/perception/test/optitrack_pose_extractor_test.cc
  manipulation/planner/test/robot_plan_interpolator_test.cc
  manipulation/util/bot_core_lcm_encode_decode.h
  multibody/parsing/test/detail_scene_graph_test.cc
  systems/analysis/test_utilities/test/controlled_spring_mass_system_test.cc
  systems/sensors/image_to_lcm_image_array_t.cc
  systems/sensors/image_writer.cc
  systems/sensors/lcm_image_array_receive_example.cc
  systems/sensors/lcm_image_array_to_images.cc
  systems/sensors/test/image_to_lcm_image_array_t_test.cc
  systems/sensors/test/lcm_image_array_to_images_test.cc
  systems/sensors/test/optitrack_sender_test.cc
Labels: priority: high, status: single reviewer ok

#13155 workspace: Bump meshcat_python to latest commit
  tools/workspace/meshcat_python/repository.bzl
Labels: status: single reviewer ok

#13287 tools: Use clang-format-9 for developers and pydrake
  bindings/pydrake/attic/multibody/rigid_body_plant_py.cc
  bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
  bindings/pydrake/attic/multibody/shapes_py.cc
  bindings/pydrake/attic/solvers/ik_py.cc
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/common/default_scalars_pybind.h
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/deprecation_example/cc_module_py.cc
  bindings/pydrake/common/type_safe_index_pybind.h
  bindings/pydrake/common/value_py.cc
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/manipulation/planner_py.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/perception_py.cc
  bindings/pydrake/polynomial_py.cc
  bindings/pydrake/pydrake_doxygen.h
  bindings/pydrake/solvers/branch_and_bound_py.cc
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/mixed_integer_optimization_util_py.cc
  bindings/pydrake/solvers/solvers_pybind.h
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/rendering_py.cc
  bindings/pydrake/systems/trajectory_optimization_py.cc
  bindings/pydrake/trajectories_py.cc
  doc/clion.rst
  doc/code_style_tools.rst
  setup/mac/source_distribution/Brewfile
  setup/ubuntu/source_distribution/packages-bionic.txt
  tools/dynamic_analysis/drd.sh
  tools/dynamic_analysis/helgrind.sh
  tools/dynamic_analysis/valgrind.sh
  tools/lint/clang_format.py
  tools/lint/formatter.py
Labels: priority: high

#13294 py mbp: Bind set_stiction_tolerance, get_contact_penalty_method_time_scale
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok

#13290 [doc] Add four new components that are all geometry related
  doc/issues.rst
Labels: status: single reviewer ok

#13255 Parses custom LinearBushingRollPitchYaw tag in SDF/URDF
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: component: multibody plant, status: squashing now, team: dynamics, type: feature request

#13295 schema: Add stochastic types
  common/schema/dev/BUILD.bazel
  common/schema/dev/stochastic.cc
  common/schema/dev/stochastic.h
  common/schema/dev/test/stochastic_test.cc
Labels: priority: medium, status: commits are properly curated

#13303 setup: fix various package names on Focal
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-focal.txt
Labels: component: build system, priority: low, status: single reviewer ok, team: kitware

#13194 pydrake: Override NiceTypeName::Get(ptr) when possible
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/module_test.py
  bindings/pydrake/common/test/value_test.py
  bindings/pydrake/common/test/value_test_util_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/scalar_conversion_test.py
  common/BUILD.bazel
  common/nice_type_name.cc
  common/nice_type_name.h
  common/nice_type_name_override.cc
  common/nice_type_name_override.h
  common/test/nice_type_name_test.cc
Labels: priority: medium, status: commits are properly curated

#13305 Add mathematicalprogram component to issues.rst
  doc/issues.rst
Labels: status: single reviewer ok

#13306 Remove redundant and pessimizing return std::moves
  attic/multibody/joints/fixed_joint.cc
  attic/multibody/joints/helical_joint.cc
  attic/multibody/joints/prismatic_joint.cc
  attic/multibody/joints/quaternion_ball_joint.cc
  attic/multibody/joints/quaternion_floating_joint.cc
  attic/multibody/joints/revolute_joint.cc
  attic/multibody/joints/roll_pitch_yaw_floating_joint.cc
  geometry/proximity/make_sphere_mesh.h
  multibody/tree/ball_rpy_joint.cc
  multibody/tree/joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_spring.cc
  multibody/tree/universal_joint.cc
  multibody/tree/weld_joint.cc
  systems/analysis/test/scalar_view_dense_output_test.cc
Labels: priority: low, status: single reviewer ok

#13261 doc: Add release notes v0.18.0
  doc/release_notes/release_notes.rst
  doc/release_notes/v0.18.0.rst
Labels: priority: high, status: do not merge, status: single reviewer ok

#13292 scene_graph: Mention adding geometry in the context of collision filters
  geometry/scene_graph.h
Labels: status: single reviewer ok

#13208 doc issues: Add pydrake and jupyter components
  doc/issues.rst
Labels: component: jupyter, component: pydrake, status: single reviewer ok

#13279 solvers: Skip compiled-but-unconfigured commercial solvers by default
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/BUILD.bazel
  solvers/choose_best_solver.cc
  solvers/csdp_solver.h
  solvers/csdp_solver_common.cc
  solvers/dreal_solver.h
  solvers/dreal_solver_common.cc
  solvers/equality_constrained_qp_solver.cc
  solvers/equality_constrained_qp_solver.h
  solvers/gurobi_solver.cc
  solvers/gurobi_solver.h
  solvers/gurobi_solver_common.cc
  solvers/ipopt_solver.h
  solvers/ipopt_solver_common.cc
  solvers/linear_system_solver.cc
  solvers/linear_system_solver.h
  solvers/moby_lcp_solver.cc
  solvers/moby_lcp_solver.h
  solvers/mosek_solver.cc
  solvers/mosek_solver.h
  solvers/mosek_solver_common.cc
  solvers/nlopt_solver.h
  solvers/nlopt_solver_common.cc
  solvers/osqp_solver.h
  solvers/osqp_solver_common.cc
  solvers/scs_solver.h
  solvers/scs_solver_common.cc
  solvers/snopt_solver.h
  solvers/snopt_solver_common.cc
  solvers/solver_base.cc
  solvers/solver_base.h
  solvers/solver_interface.h
  solvers/test/gurobi_solver_grb_license_file_test.cc
  solvers/test/mosek_solver_moseklm_license_file_test.cc
  solvers/test/solver_base_deprecated_test.cc
  solvers/test/solver_base_test.cc
  solvers/unrevised_lemke_solver.cc
  solvers/unrevised_lemke_solver.h
Labels: priority: medium

#13304 tools: Add xacro helper macros
  tools/workspace/ros_xacro/BUILD.bazel
  tools/workspace/ros_xacro/defs.bzl
  tools/workspace/ros_xacro/disable-import-warning.patch
  tools/workspace/ros_xacro/repository.bzl
  tools/workspace/ros_xacro/test/box.xml
  tools/workspace/ros_xacro/test/sample1.xml.expected
  tools/workspace/ros_xacro/test/sample1.xml.xacro
  tools/workspace/ros_xacro/test/sample2.xml.expected
  tools/workspace/ros_xacro/test/sample2.xml.xacro
  tools/workspace/ros_xacro/test/xacro_smoke_test.py
Labels: priority: medium

#13318 autodiffutils_test: Use numpy version check for error message
  bindings/pydrake/test/autodiffutils_test.py
Labels: status: single reviewer ok

#13311 manipulation: Check for whole default message, not just utime==0
  lcm/BUILD.bazel
  lcm/drake_lcm_interface.h
  lcm/lcm_messages.cc
  lcm/lcm_messages.h
  lcm/test/lcm_messages_test.cc
  manipulation/kinova_jaco/jaco_command_receiver.cc
  manipulation/kinova_jaco/test/jaco_command_receiver_test.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
  manipulation/schunk_wsg/BUILD.bazel
  manipulation/schunk_wsg/schunk_wsg_lcm.cc
  manipulation/schunk_wsg/test/schunk_wsg_lcm_test.cc
Labels: status: commits are properly curated

#13319 tools: Remove stray xacro console output
  tools/workspace/ros_xacro/disable-console-print.patch
  tools/workspace/ros_xacro/repository.bzl
Labels: priority: low, status: single reviewer ok

#13201 workspace: Upgrade libsdformat to latest release 9.2.0
  tools/workspace/sdformat/3bbd303.patch
  tools/workspace/sdformat/package.BUILD.bazel
  tools/workspace/sdformat/repository.bzl
Labels: priority: backlog, status: single reviewer ok

#13323 setup: use clang-format@9 and other cleanup
  setup/mac/binary_distribution/Brewfile
  setup/mac/source_distribution/Brewfile
  setup/mac/source_distribution/install_prereqs.sh
  tools/lint/clang_format.py
Labels: component: build system, configuration: mac, team: kitware

#13266 doxygen: add 1.8.15 binary for Focal
  doc/Doxyfile_CXX.in
  doc/DoxygenLayout.xml
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  tools/workspace/doxygen/.dockerignore
  tools/workspace/doxygen/Dockerfile
  tools/workspace/doxygen/build_binaries_with_docker
  tools/workspace/doxygen/repository.bzl
Labels: component: build system, priority: low, team: kitware

#12624 Removes dead code; IntegratorBase::InitializeAccuracy().
  systems/analysis/integrator_base.h
Labels: status: single reviewer ok, team: dynamics, type: bug, type: cleanup

#13331 query_object: Update doc to warn about ignoring Mesh shapes
  geometry/query_object.h
Labels: status: single reviewer ok

#13283 Add binaries for drake-visualizer and vtk for focal and update binaries on bionic
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/vtk/Dockerfile
  tools/workspace/vtk/build_binaries_with_docker
  tools/workspace/vtk/dockerfile_build_vtk_binaries
  tools/workspace/vtk/ospray_ospcommon.patch
  tools/workspace/vtk/repository.bzl
Labels: component: build system, priority: low, team: kitware

#13329 doc: Fix typo in Contact Modeling section
  multibody/plant/contact_model_doxygen.h
Labels: status: single reviewer ok

#13325 Make the core of move_iiwa_ee reusable and convert jaco example
  examples/kinova_jaco_arm/BUILD.bazel
  examples/kinova_jaco_arm/README.md
  examples/kinova_jaco_arm/move_jaco_ee.cc
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/move_iiwa_ee.cc
  manipulation/planner/robot_plan_interpolator.cc
  manipulation/planner/test/robot_plan_interpolator_test.cc
  manipulation/util/BUILD.bazel
  manipulation/util/move_ik_demo_base.cc
  manipulation/util/move_ik_demo_base.h
  manipulation/util/test/move_ik_demo_base_test.cc
Labels: priority: low, status: commits are properly curated

#13344 Disable move_ik_demo_test case which causes timeouts
  manipulation/util/BUILD.bazel
  manipulation/util/test/move_ik_demo_base_test.cc
Labels: status: single reviewer ok

#13341 Remove use of XXX in comments
  multibody/plant/multibody_plant.h
  multibody/tree/force_element.h
  multibody/tree/multibody_tree.h
  multibody/tree/uniform_gravity_field_element.cc
  tutorials/mathematical_program.ipynb
Labels: priority: low

#13346 Fix more GCC 8/9 warnings
  attic/multibody/rigid_body.cc
  solvers/nlopt_solver.cc
Labels: component: build system, priority: low, status: commits are properly curated, status: single reviewer ok, team: kitware

#13345 Do not error when downloading ibex on Focal
  tools/workspace/ibex/repository.bzl
Labels: component: build system, status: single reviewer ok, team: kitware

#13339 Fix location of VTK on Focal in drake-visualizer launcher
  tools/workspace/drake_visualizer/drake_visualizer_bazel.py
Labels: component: build system, priority: low, status: single reviewer ok, team: kitware

#13342 py geom, mbp: Add GetDefaultFreeBodyPose, bind joint accessors, update type index wrappers
  bindings/pydrake/common/test/type_safe_index_pybind_test.cc
  bindings/pydrake/common/type_safe_index_pybind.h
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/test/geometry_test.py
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: status: commits are properly curated

#13322 Allow using Binding<C> as key in unordered_map.
  solvers/BUILD.bazel
  solvers/binding.h
  solvers/test/binding_test.cc
Labels: status: squashing now

#13335 Do not use pkg-config to find libjpeg and yaml-cpp
  tools/workspace/libjpeg/package-macos.BUILD.bazel
  tools/workspace/libjpeg/package-ubuntu.BUILD.bazel
  tools/workspace/libjpeg/repository.bzl
  tools/workspace/yaml_cpp/package-macos.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
  tools/workspace/yaml_cpp/repository.bzl
Labels: component: build system, priority: low, team: kitware

#13338 geometry: Add SceneGraphInspector::CloneGeometryInstance
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  geometry/BUILD.bazel
  geometry/scene_graph_inspector.cc
  geometry/scene_graph_inspector.h
  geometry/test/scene_graph_inspector_test.cc
Labels: status: commits are properly curated

#13106 Guidance for picking bushing stiffness/damping constants
  multibody/tree/linear_bushing_roll_pitch_yaw.h
Labels: priority: medium, status: squashing now, team: dynamics, type: documentation

#13353 Add missing yaml-cpp headers
  tools/workspace/yaml_cpp/package-macos.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
Labels: component: build system, priority: emergency, status: single reviewer ok, team: kitware

#13352 py geometry: Bind Mesh and Convex accessors
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
Labels: status: single reviewer ok

#13343 pydrake: Added some simulator bindings
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok

#13302 Strandbeest example
  examples/multibody/strandbeest/BUILD.bazel
  examples/multibody/strandbeest/README.md
  examples/multibody/strandbeest/model/LegAssembly.xacro
  examples/multibody/strandbeest/model/LegPair.xacro
  examples/multibody/strandbeest/model/Macros.xacro
  examples/multibody/strandbeest/model/Strandbeest.xacro
  examples/multibody/strandbeest/run_with_motor.cc
  examples/multibody/strandbeest/test/run_with_motor_test.py
Labels: status: squashing now

#13355 py mbp: Bind MultibodyPlant.time_step()
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok

#13356 doc: Minor fix to Python debugging tips
  doc/python_bindings.rst
Labels: status: single reviewer ok

#13359 Added support for all types in VectorExternallyAppliedSpatialForce
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok

#13351 geometry: Add and bind GeometryInstance::set_name
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  geometry/geometry_instance.cc
  geometry/geometry_instance.h
  geometry/test/geometry_instance_test.cc
Labels: status: commits are properly curated

#13348 Fix shadow warning and include <fstream> for std::ifstream and std::ofstream
  geometry/render/render_engine_ospray.cc
  geometry/render/render_engine_vtk.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  perception/test/depth_image_to_point_cloud_test.cc
Labels: component: build system, priority: low, status: commits are properly curated, status: single reviewer ok, team: kitware

#13361 py geometry: Bind Shape.Clone()
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
Labels: status: single reviewer ok

#13363 py systems: Bind system accessors
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok

#13360 Fix pessimizing-move warning in LeafSystem
  systems/framework/leaf_system.cc
Labels: component: build system, priority: low, status: single reviewer ok, team: kitware

#13336 primitives: Disable DiscreteDerivative transient by default
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  examples/manipulation_station/test/manipulation_station_test.cc
  systems/primitives/discrete_derivative.cc
  systems/primitives/discrete_derivative.h
  systems/primitives/test/discrete_derivative_test.cc
Labels: priority: high

#13014 Updates the developer notes of MBP::RegisterGeometry().
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok, team: dynamics, type: documentation

#13063 Rename BiasForJacobian methods, new notation and documentation, plan expansion of CalcBiasSpatialAcceleration
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/multibody_tree_test.cc
Labels: priority: medium, status: squashing now, team: dynamics

#13373 binder: Update local instructions to use `--rm -it`
  .binder/README.md
Labels: status: single reviewer ok

#13366 Use static library for yaml-cpp on Focal due to hidden visibility patch
  tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
Labels: component: build system, priority: low, status: single reviewer ok, team: kitware

#13328 Add a tutorial on updating costs/constraints in mathematical program.
  tutorials/mathematical_program.ipynb
  tutorials/updating_costs_and_constraints.ipynb
Labels: status: squashing now

#13378 manipulation_station: Put code into main() functions
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
  examples/manipulation_station/joint_teleop.py
  examples/manipulation_station/print_station_context.py
Labels: priority: high, status: single reviewer ok

#13365 systems: Use Eigen's formatting in VectorBase::operator<<() output
  bindings/pydrake/systems/test/general_test.py
  systems/framework/test/basic_vector_test.cc
  systems/framework/test/continuous_state_test.cc
  systems/framework/vector_base.h
Labels: status: squashing now

#13384 Revert "systems: Use Eigen's formatting in VectorBase::operator<<() output (#13365)"
  bindings/pydrake/systems/test/general_test.py
  systems/framework/test/basic_vector_test.cc
  systems/framework/test/continuous_state_test.cc
  systems/framework/vector_base.h
Labels: status: single reviewer ok

#13386 doc: Update tutorials section to mention nbviewer
  doc/index.rst
  tutorials/README.md
Labels: status: single reviewer ok

#13380 manipulation_station: Add initialization regression tests
  examples/manipulation_station/end_effector_teleop_sliders.py
  examples/manipulation_station/joint_teleop.py
Labels: priority: high

#13357 Fix range-loop-construct warnings
  bindings/pydrake/symbolic_py.cc
  common/test/symbolic_monomial_test.cc
  examples/manipulation_station/manipulation_station.cc
  geometry/proximity/mesh_half_space_intersection.cc
  geometry/proximity/mesh_plane_intersection.cc
  geometry/proximity/test/make_box_field_test.cc
  geometry/proximity/test/make_cylinder_field_test.cc
  geometry/proximity/test/make_ellipsoid_field_test.cc
  geometry/proximity/test/make_sphere_field_test.cc
  geometry/proximity/test/mesh_field_linear_test.cc
  geometry/proximity/test/mesh_plane_intersection_test.cc
  geometry/proximity_engine.cc
  geometry/render/render_engine_vtk_base.cc
  geometry/test/proximity_engine_test.cc
  manipulation/planner/robot_plan_interpolator.cc
  math/test/rotation_conversion_test.cc
  multibody/tree/test/multibody_tree_test.cc
  solvers/test/mathematical_program_test.cc
  tools/workspace/ignition_math/package.BUILD.bazel
Labels: component: build system, priority: low, status: commits are properly curated, team: kitware

#13358 pydrake: Collision filtering bindings
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/test/geometry_test.py
Labels: status: squashing now

#13364 Spatial velocity and acceleration ports
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: component: multibody plant, team: dynamics

#13370 Suppress symbolic feedthrough check if non-default output prerequisites were specified.
  systems/controllers/finite_horizon_linear_quadratic_regulator.cc
  systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
  systems/framework/cache_entry.h
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/test/cache_entry_test.cc
  systems/framework/test/leaf_system_test.cc
Labels: component: system framework, priority: low

#13399 Revert "Spatial velocity and acceleration ports"
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: emergency, status: single reviewer ok

#13340 manipulation: Use input (not parameter) for no-op IIWA command
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
  examples/manipulation_station/joint_teleop.py
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/mock_station_simulation.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.h
  manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
  manipulation/schunk_wsg/schunk_wsg_position_controller.cc
  manipulation/schunk_wsg/schunk_wsg_position_controller.h
  manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
Labels: priority: high

#13397 Add parsing of string options to SNOPT.
  solvers/snopt_solver.cc
  solvers/test/snopt_solver_test.cc
Labels: status: squashing now

#13377 Gurobi gets dual solution for QP and LP
  solvers/gurobi_solver.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/linear_program_examples.cc
  solvers/test/linear_program_examples.h
  solvers/test/osqp_solver_test.cc
  solvers/test/quadratic_program_examples.cc
  solvers/test/quadratic_program_examples.h
Labels: status: squashing now

#13390 Migrating Jacobian tests
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/test/multibody_tree_test.cc
Labels: component: multibody plant, team: dynamics

#13400 Fix python_direct_link target on Focal
  tools/workspace/python/repository.bzl
Labels: component: build system, priority: low, team: kitware

#13404 Fix the CI failure for LPDualSolution1.
  solvers/test/linear_program_examples.cc
Labels: priority: emergency

#13410 py cpp_template: Enable deprecating instantiations
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/cpp_template.py
  bindings/pydrake/common/test/cpp_template_test.py
Labels: status: single reviewer ok

#13381 workspace: Add dependency on pygame
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/end_effector_teleop_mouse.py
  setup/ubuntu/source_distribution/packages-focal.txt
  tools/workspace/default.bzl
  tools/workspace/mirrors.bzl
  tools/workspace/pygame_py/BUILD.bazel
  tools/workspace/pygame_py/package-stub.BUILD.bazel
  tools/workspace/pygame_py/repository.bzl
  tools/workspace/pypi_wheel.bzl
Labels: priority: medium

#13412 Disable global_inverse_kinematics_feasible_posture_test in debug
  attic/multibody/dev/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok

#13405 Enable kinematics computations on models with zero dofs
  multibody/plant/BUILD.bazel
  multibody/plant/test/frame_kinematics_test.cc
  multibody/test_utilities/add_fixed_objects_to_plant.h
  multibody/tree/body_node.h
  multibody/tree/multibody_tree.cc
Labels: component: multibody plant, status: squashing now, team: dynamics, type: bug

#13419 pybind: Allow specifying copts
  tools/skylark/pybind.bzl
Labels: status: single reviewer ok

#13415 py mbp: Bind accessors for inertias
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok

#13383 Use EmitFromEvents from emitfromevents.{cpp,h} vendored from yaml-cpp
  BUILD.bazel
  common/yaml/BUILD.bazel
  common/yaml/yaml_write_archive.cc
  common/yaml/yaml_write_archive.h
  third_party/com_github_jbeder_yaml_cpp/BUILD.bazel
  third_party/com_github_jbeder_yaml_cpp/LICENSE
  third_party/com_github_jbeder_yaml_cpp/include/yaml-cpp/emitfromevents.h
  third_party/com_github_jbeder_yaml_cpp/src/emitfromevents.cpp
  tools/install/libdrake/build_components.bzl
  tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
Labels: component: build system, priority: low, status: commits are properly curated, team: kitware

#13420 pydrake/*_extra.py: Ensure all files have consistent boilerplate comment
  bindings/pydrake/_math_extra.py
  bindings/pydrake/_symbolic_extra.py
  bindings/pydrake/examples/_manipulation_station_extra.py
  bindings/pydrake/solvers/_mathematicalprogram_extra.py
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/test/_pydrake_pybind_test_extra.py
Labels: status: single reviewer ok

#13422 workspace: Fix pypi_wheel support in release tooling
  tools/workspace/mirrors.bzl
  tools/workspace/new_release.py
  tools/workspace/pypi_wheel.bzl
Labels: priority: medium

#13414 py geometry: Bind HalfSpace.MakePose
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
Labels: status: single reviewer ok

#13418 parsing: Work around some GCC 8 maybe-uninitialized warnings
  multibody/parsing/detail_scene_graph.cc
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/test/detail_common_test.cc
Labels: priority: low, status: single reviewer ok

#13423 Implements spatial velocity and acceleration ports
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: component: multibody plant, team: dynamics

#13411 Move CalcBiasSpatialAcceleration() test from multibody_tree_test.cc to multibody_plant_jacobians_test.cc
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/test/multibody_tree_test.cc
Labels: component: multibody plant, priority: high, team: dynamics

#13424 Improve robustness and diagnostic messages of S3 mirroring script
  tools/workspace/mirror_to_s3.py
Labels: component: continuous integration, status: single reviewer ok, team: kitware

#13413 py systems: Bind Simulator.set_monitor
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/analysis_test.py
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
Labels: status: commits are properly curated

#13425 std::filesystem-related fixes for Focal
  common/test/filesystem_test.cc
  multibody/parsing/package_map.cc
Labels: component: build system, priority: low, status: commits are properly curated, status: single reviewer ok, team: kitware

#13430 workspace: Upgrade pycodestyle to latest release 2.6.0
  tools/install/check_licenses.bzl
  tools/install/install.bzl
  tools/workspace/pycodestyle/repository.bzl
Labels: priority: low, status: single reviewer ok

#13431 workspace: Upgrade fmt and spdlog to latest release
  common/text_logging.h
  tools/workspace/fmt/repository.bzl
  tools/workspace/spdlog/repository.bzl
Labels: priority: low, status: single reviewer ok

#13429 workspace: Upgrade imported bazel rules to latest
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/bazel_skylib/repository.bzl
  tools/workspace/rules_python/repository.bzl
Labels: priority: low, status: single reviewer ok

#13432 Add libclang-9-dev to prerequisites
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal.txt
Labels: component: build system, priority: low, status: single reviewer ok, team: kitware

#13436 Do not delete VisualElement move constructor
  attic/multibody/shapes/element.h
  attic/multibody/shapes/visual_element.h
Labels: component: build system, priority: low, status: single reviewer ok, team: kitware

#13385 Ignore class-memaccess warning in IsMemcpyMovable
  common/test_utilities/is_memcpy_movable.h
Labels: component: build system, priority: low, team: kitware

#13435 Allows calling MBP::set_penetration_allowance() pre-finalize.
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/inclined_plane_test.cc
Labels: component: multibody plant, priority: high, team: dynamics, type: feature request

#13450 Fix range-loop-construct warnings in gurobi_solver.cc
  solvers/gurobi_solver.cc
Labels: component: build system, priority: low, status: single reviewer ok, team: kitware

#13447 drake_visualizer: Prevent clipping volume from going to infinity
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/BUILD.bazel
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/limit_clipping_range.py
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/use_builtin_scripts.py
Labels: status: single reviewer ok

#13449 Fix hash_template_argument_from_pretty_func for GCC 9
  common/test/value_test.cc
  common/value.h
Labels: component: build system, priority: low, team: kitware

#13455 py common: Use `py::object_api::get_type()`, not indirect Python C++ API
  bindings/pydrake/common/module_py.cc
Labels: status: single reviewer ok
