Repository RobotLocomotion/drake, pull requests merged in 2020-11, with the labels that each got.

#14270 bindings: Remove cpp_const
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/all.py
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/all.py
  bindings/pydrake/common/cpp_const.py
  bindings/pydrake/common/test/cpp_const_test.py
  bindings/pydrake/doc/gen_sphinx.py
  bindings/pydrake/third_party/BUILD.bazel
  bindings/pydrake/third_party/__init__.py
  third_party/BUILD.bazel
  third_party/com_github_grahamdumpleton_wrapt/LICENSE
  third_party/com_github_grahamdumpleton_wrapt/README.md
  third_party/com_github_grahamdumpleton_wrapt/__init__.py
  third_party/com_github_grahamdumpleton_wrapt/wrappers.py
Labels: priority: low, status: single reviewer ok

#14271 workspace: Upgrade fcl to latest commit
  tools/workspace/fcl/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14274 workspace: Upgrade intel_realsense_ros to latest release 2.2.18
  tools/workspace/intel_realsense_ros/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14278 workspace: Upgrade rules_python to latest release 0.1.0
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/rules_python/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14277 workspace: Upgrade rules_pkg to latest release 0.3.0
  tools/workspace/rules_pkg/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14272 workspace: Upgrade fmt to latest release 7.1.0
  bindings/pydrake/systems/test/analysis_test.py
  common/test/text_logging_test.cc
  common/text_logging.h
  common/trajectories/test/discrete_time_trajectory_test.cc
  common/yaml/yaml_write_archive.h
  multibody/parsing/test/detail_scene_graph_test.cc
  tools/workspace/fmt/repository.bzl
Labels: component: build system, priority: low

#14246 setup: Upgrade recommended Bazel version to 3.7
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: priority: low, status: single reviewer ok

#14273 workspace: Upgrade ghc_filesystem to latest release 1.3.6
  tools/workspace/ghc_filesystem/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14275 workspace: Upgrade lcm to latest commit
  tools/workspace/lcm/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14276 workspace: Upgrade ros_xacro to latest release 1.13.9
  tools/workspace/ros_xacro/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14283 perception: Split unit test cases
  perception/test/point_cloud_flags_test.cc
Labels: component: build system, priority: emergency, status: single reviewer ok

#14284 systems: Move spring_mass_system to a test utility
  systems/analysis/BUILD.bazel
  systems/analysis/test/implicit_integrator_test.cc
  systems/analysis/test/integrator_base_test.cc
  systems/analysis/test/simulator_test.cc
  systems/analysis/test_utilities/BUILD.bazel
  systems/analysis/test_utilities/controlled_spring_mass_system.h
  systems/analysis/test_utilities/implicit_integrator_test.h
  systems/analysis/test_utilities/my_spring_mass_system.h
  systems/analysis/test_utilities/spring_mass_damper_system.h
  systems/analysis/test_utilities/spring_mass_system.cc
  systems/analysis/test_utilities/spring_mass_system.h
  systems/analysis/test_utilities/test/spring_mass_system_test.cc
  systems/plants/spring_mass_system/BUILD.bazel
  tools/install/libdrake/build_components.bzl
Labels: priority: low, status: single reviewer ok

#14251 [geometry] Use the new box mesh in hydroelastic contact model.
  geometry/profiling/BUILD.bazel
  geometry/profiling/README.md
  geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/hydroelastic_internal.h
  geometry/proximity/test/hydroelastic_internal_test.cc
Labels: component: geometry proximity, priority: medium, team: dynamics

#14293 Minor fixes for flake8's F821 (undefined name) error
  bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py
  bindings/pydrake/manipulation/simple_ui.py
  examples/manipulation_station/differential_ik.py
Labels: status: single reviewer ok

#14288 Switch to ipopt@3.11 formula on macOS
  setup/mac/binary_distribution/Brewfile
  tools/workspace/ipopt/repository.bzl
Labels: component: build system, configuration: mac, team: kitware

#14304 [visualization] Allow force publish calls on DrakeVisualizer
  geometry/drake_visualizer.cc
  geometry/drake_visualizer.h
  geometry/test/drake_visualizer_test.cc
Labels: priority: high

#14311 Disable tests that are failing valgrind in CI
  multibody/fem/dev/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok

#14168 Make installing documentation prereqs optional
  bindings/pydrake/doc/BUILD.bazel
  doc/BUILD.bazel
  doc/documentation_instructions.rst
  setup/mac/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: component: distribution, priority: high, team: kitware

#14308 systems/lcm: Add LcmScopeSystem
  lcmtypes/BUILD.bazel
  lcmtypes/lcmt_scope.lcm
  systems/lcm/BUILD.bazel
  systems/lcm/connect_lcm_scope.h
  systems/lcm/lcm_scope_system.cc
  systems/lcm/lcm_scope_system.h
  systems/lcm/test/lcm_scope_system_test.cc
Labels: priority: high

#14314 [pybind] Correct bindings for DrakeVisualizer.AddToBuilder
  bindings/pydrake/geometry_py.cc
Labels: status: single reviewer ok

#14320 hotfix: typo in _warn_deprecated caused error outside of drake that was masked inside of drake
  bindings/pydrake/systems/meshcat_visualizer.py
Labels: priority: high, status: single reviewer ok

#14323 Add parsing for reflected inertia parameters
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: component: multibody plant, priority: medium, team: dynamics, type: feature request

#14294 kcov: Implement parallel testing schedule
  doc/bazel.rst
  doc/sample_vimrc
  tools/dynamic_analysis/bazel.rc
  tools/dynamic_analysis/kcov.sh
  tools/dynamic_analysis/kcov_tool
Labels: priority: low

#14207 pydrake: Bind some missing multibody tree-related items
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: priority: low, status: single reviewer ok

#14338 Only retrieve Mosek dual solution when there is no integer variables.
  solvers/mosek_solver.cc
Labels: priority: emergency

#14331 Change to use SetInitialGuess in the nlp tutorial.
  tutorials/nonlinear_program.ipynb
Labels: status: single reviewer ok

#14327 yaml: Correctly emit variants with templated inner types
  common/schema/BUILD.bazel
  common/schema/test/stochastic_test.cc
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/test/yaml_write_archive_defaults_test.cc
  common/yaml/test/yaml_write_archive_test.cc
  common/yaml/yaml_write_archive.h
Labels: priority: low

#14347 Propagate joint default positions through scalar conversion
  multibody/tree/ball_rpy_joint.cc
  multibody/tree/planar_joint.cc
  multibody/tree/prismatic_joint.cc
  multibody/tree/revolute_joint.cc
  multibody/tree/test/ball_rpy_joint_test.cc
  multibody/tree/test/planar_joint_test.cc
  multibody/tree/test/prismatic_joint_test.cc
  multibody/tree/test/revolute_joint_test.cc
  multibody/tree/test/universal_joint_test.cc
  multibody/tree/universal_joint.cc
Labels: component: multibody plant, priority: medium, team: dynamics

#14352 Remove support for macOS Mojave 10.14
  CMakeLists.txt
  doc/developers.rst
  doc/jenkins.rst
  doc/release_playbook.rst
  tools/workspace/os.bzl
  tools/workspace/pkg_config.bzl
Labels: component: distribution, configuration: mac, priority: high, team: kitware

#14316 Per issue #13646, throw an exception if composite_mass <= 0.
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_com_test.cc
  multibody/tree/multibody_tree.cc
Labels: component: multibody plant, priority: low, status: squashing now, team: dynamics, type: cleanup

#14204 Allegro with reflected inertia
  examples/allegro_hand/allegro_common.cc
  examples/allegro_hand/allegro_common.h
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
Labels: component: multibody plant, team: dynamics

#14357 [render] Fully account for full camera intrinsics in RenderEngine ecosystem
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  geometry/render/gl_renderer/render_engine_gl.cc
  geometry/render/gl_renderer/render_engine_gl.h
  geometry/render/gl_renderer/test/render_engine_gl_test.cc
  geometry/render/render_engine.cc
  geometry/render/render_engine.h
  geometry/render/render_engine_vtk.cc
  geometry/render/render_engine_vtk.h
  geometry/render/test/render_engine_test.cc
  geometry/render/test/render_engine_vtk_test.cc
  geometry/test_utilities/dummy_render_engine.h
Labels: priority: high

#14324 Remove MBP's awareness of SG<AutoDiff> support
  bindings/pydrake/multibody/test/plant_test.py
  geometry/geometry_state.h
  geometry/proximity/hydroelastic_callback.h
  geometry/proximity/mesh_intersection.cc
  geometry/proximity/test/hydroelastic_callback_test.cc
  geometry/proximity/test/mesh_intersection_test.cc
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/query_object.cc
  geometry/query_object.h
  geometry/test/proximity_engine_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: status: squashing now

#14364 Cache/CacheEntry rename.
  multibody/fem/dev/BUILD.bazel
  multibody/fem/dev/constitutive_model.h
  multibody/fem/dev/deformation_gradient_cache.h
  multibody/fem/dev/deformation_gradient_cache_entry.h
  multibody/fem/dev/elasticity_element.cc
  multibody/fem/dev/elasticity_element.h
  multibody/fem/dev/elasticity_element_cache.h
  multibody/fem/dev/elasticity_element_cache_entry.h
  multibody/fem/dev/elasticity_model.h
  multibody/fem/dev/element_cache.h
  multibody/fem/dev/element_cache_entry.h
  multibody/fem/dev/fem_element.h
  multibody/fem/dev/fem_model.cc
  multibody/fem/dev/fem_state.h
  multibody/fem/dev/linear_elasticity_model.cc
  multibody/fem/dev/linear_elasticity_model.h
  multibody/fem/dev/linear_elasticity_model_cache_entry.cc
  multibody/fem/dev/linear_elasticity_model_cache_entry.h
  multibody/fem/dev/test/elasticity_element_test.cc
  multibody/fem/dev/test/elasticity_model_test.cc
  multibody/fem/dev/test/fem_state_test.cc
  multibody/fem/dev/test/linear_elasticity_model_cache_entry_test.cc
  multibody/fem/dev/test/linear_elasticity_model_cache_test.cc
  multibody/fem/dev/test/linear_elasticity_model_test.cc
Labels: status: single reviewer ok

#14360 yaml: Fix parsing bugs with zero-sized matrices
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/test/yaml_write_archive_test.cc
  common/yaml/yaml_read_archive.h
Labels: priority: low

#14359 [render] Deprecate RenderEngine::Render*Image(CameraProperties) API
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  examples/scene_graph/bouncing_ball_run_dynamics.cc
  geometry/benchmarking/render_benchmark.cc
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/query_object.cc
  geometry/query_object.h
  geometry/render/gl_renderer/test/render_engine_gl_test.cc
  geometry/render/render_engine.cc
  geometry/render/render_engine.h
  geometry/render/render_engine_vtk.cc
  geometry/render/test/render_engine_test.cc
  geometry/render/test/render_engine_vtk_test.cc
  geometry/scene_graph.h
  geometry/test/query_object_test.cc
Labels: priority: high

#14358 [render] Deprecate RgbdSensor's CameraProperties API
  bindings/pydrake/common/deprecation_pybind.h
  bindings/pydrake/common/test/deprecation_example/cc_module_py.cc
  bindings/pydrake/common/test/deprecation_example/example_class.h
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  bindings/pydrake/test/geometry_test.py
  geometry/render/render_camera.cc
  geometry/render/render_camera.h
  geometry/render/test/render_camera_test.cc
  systems/sensors/rgbd_sensor.cc
  systems/sensors/rgbd_sensor.h
  systems/sensors/test/rgbd_sensor_test.cc
  tutorials/rendering_multibody_plant.ipynb
Labels: priority: high

#14370 py examples: Ensure manipulation_station_py.cc imports dep modules
  bindings/pydrake/examples/manipulation_station_py.cc
Labels: status: single reviewer ok

#14371 py deprecation: Correct minor error in test
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/deprecation_example/cc_module_py.cc
  bindings/pydrake/common/test/deprecation_test.py
Labels: status: single reviewer ok

#14377 Replace robotlocomotion.robot_plan_t with drake.lcmt_robot_plan
  examples/kinova_jaco_arm/BUILD.bazel
  examples/kinova_jaco_arm/jaco_controller.cc
  examples/kinova_jaco_arm/move_jaco_ee.cc
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_controller.cc
  examples/kuka_iiwa_arm/kuka_plan_runner.cc
  examples/kuka_iiwa_arm/move_iiwa_ee.cc
  lcmtypes/BUILD.bazel
  lcmtypes/lcmt_robot_plan.lcm
  lcmtypes/lcmt_robot_state.lcm
  manipulation/planner/BUILD.bazel
  manipulation/planner/robot_plan_interpolator.cc
  manipulation/planner/robot_plan_interpolator.h
  manipulation/planner/test/robot_plan_interpolator_test.cc
  manipulation/util/BUILD.bazel
  manipulation/util/move_ik_demo_base.cc
  manipulation/util/move_ik_demo_base.h
  manipulation/util/robot_plan_utils.cc
  manipulation/util/robot_plan_utils.h
  manipulation/util/test/robot_plan_utils_test.cc
Labels: priority: low

#14379 Allow tests to pass with both fmt < 7.1 and fmt >= 7.1
  bindings/pydrake/systems/test/analysis_test.py
  common/trajectories/test/discrete_time_trajectory_test.cc
  common/yaml/yaml_write_archive.h
  multibody/parsing/test/detail_scene_graph_test.cc
Labels: priority: low, status: single reviewer ok

#14375 [render] Deprecate ManipulationStation CameraProperties API
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/examples/manipulation_station_py.cc
  bindings/pydrake/examples/test/manipulation_station_test.py
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station.h
  examples/manipulation_station/test/manipulation_station_test.cc
Labels: priority: high

#14351 [proximity] Implement Mesh for proximity via its convex hull.
  geometry/BUILD.bazel
  geometry/proximity_engine.cc
  geometry/query_object.h
  geometry/test/extruded_u.obj
  geometry/test/proximity_engine_test.cc
Labels: priority: high

#14376 [render] Deprecate CameraProperties and DepthCameraProperties
  bindings/pydrake/examples/test/manipulation_station_test.py
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  bindings/pydrake/test/geometry_test.py
  examples/manipulation_station/test/manipulation_station_test.cc
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/query_object.cc
  geometry/query_object.h
  geometry/render/camera_properties.h
  geometry/render/render_camera.cc
  geometry/render/render_camera.h
  geometry/render/render_engine.cc
  geometry/render/render_engine.h
  geometry/render/test/render_camera_test.cc
  geometry/render/test/render_engine_test.cc
  geometry/test/query_object_test.cc
  systems/sensors/rgbd_sensor.h
  systems/sensors/test/rgbd_sensor_test.cc
Labels: priority: high

#14353 Move code from symbolic_extraction to symbolic_decompose.
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/BUILD.bazel
  common/symbolic_decompose.cc
  common/symbolic_decompose.h
  common/symbolic_expression.h
  common/test/symbolic_decompose_test.cc
  solvers/BUILD.bazel
  solvers/constraint.cc
  solvers/create_constraint.cc
  solvers/create_cost.cc
  solvers/mathematical_program.cc
  solvers/symbolic_extraction.cc
  solvers/symbolic_extraction.h
Labels: status: single reviewer ok

#14388 dualshock: Update example to use Logitech controller
  examples/manipulation_station/end_effector_teleop_dualshock4.py
Labels: status: single reviewer ok
