Repository RobotLocomotion/drake, pull requests merged in 2021-10, with the labels that each got.

#15834 Remove deprecated code 2021-10
  bindings/pydrake/math_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/test/math_test.py
  math/BUILD.bazel
  math/orthonormal_basis.cc
  math/orthonormal_basis.h
  math/test/orthonormal_basis_test.cc
  systems/framework/cache_entry.cc
  systems/framework/cache_entry.h
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/system_scalar_converter.h
  systems/framework/test/cache_entry_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_scalar_converter_test.cc
  systems/framework/test/system_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#15850 [geometry] Visualize at 32 Hz or 64 Hz by default
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/pyplot_visualizer.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
  examples/scene_graph/simple_contact_surface_vis.cc
  geometry/drake_visualizer_params.h
  geometry/meshcat_visualizer_params.h
  geometry/test/drake_visualizer_test.cc
  multibody/fixed_fem/dev/run_scripted_deformable_motion.cc
  multibody/fixed_fem/dev/run_simple_gripper.cc
  multibody/fixed_fem/dev/test/deformable_box_test.cc
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/contact_results_to_lcm.h
  multibody/plant/test/contact_results_to_lcm_test.cc
Labels: priority: low

#15862 [systems] Move DeclareCacheEntry to protected access
  systems/framework/system_base.h
Labels: priority: medium, status: single reviewer ok, release notes: removal of deprecated

#15857 [pydrake] Fix ODR violations in get_new_id bindings
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/frame_id_test.py
  common/BUILD.bazel
  common/identifier.cc
  common/identifier.h
  geometry/geometry_frame.cc
  geometry/render/gl_renderer/shader_program.cc
  geometry/render/gl_renderer/shader_program.h
Labels: priority: high

#15860 [pydrake] Breakout geometry/optimization bindings into its own file
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/geometry_py.h
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  bindings/pydrake/test/geometry_test.py
Labels: status: commits are properly curated, release notes: none

#15863 [framework] Demote deprecated SystemScalarConverter::Add to internal
  bindings/pydrake/systems/framework_py_systems.cc
  systems/framework/system_scalar_converter.cc
  systems/framework/system_scalar_converter.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#15861 [multibody] Add internal cross-check for default contact model
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: priority: low, status: single reviewer ok, release notes: none

#15851 [geometry:meshcat] Adds visualization for Point Clouds
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  geometry/BUILD.bazel
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/meshcat_types.h
  geometry/test/meshcat_manual_test.cc
  geometry/test/meshcat_test.cc
Labels: priority: high

#15870 [workspace] Upgrade rules_python to latest release 0.4.0
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/rules_python/repository.bzl
Labels: component: distribution, priority: low, status: single reviewer ok

#15864 [workspace] Add new_release tooling for automatic upgrades
  tools/workspace/metadata.py
  tools/workspace/new_release.py
Labels: priority: low, release notes: none

#15879 [pydrake] Restore history to geometry bindings
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py_all.cc
  bindings/pydrake/test/geometry_all_test.py
Labels: priority: high, status: commits are properly curated, status: single reviewer ok, release notes: none

#15880 [workspace] Upgrade buildifier to latest release 4.2.0
  tools/workspace/buildifier/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: yes

#15882 Remove TODO in the doxygen of StaticEquilibriumProblem
  multibody/optimization/static_equilibrium_problem.h
Labels: status: single reviewer ok

#15877 py deprecation: Expose `deprecated_callable` as decorator
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/common/test/deprecation_example/__init__.py
  bindings/pydrake/common/test/deprecation_test.py
Labels: release notes: yes

#15875 Deprecate old names for autodiff utilities
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/_autodiffutils_extra.py
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/test/autodiffutils_test.py
  math/autodiff.h
  math/autodiff_gradient.h
  math/test/autodiff_test.cc
  tutorials/debug_mathematical_program.ipynb
Labels: type: cleanup, priority: low, team: dynamics, component: system framework, release notes: newly deprecated

#15881 [pydrake] Breakout core geometry elements
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py.h
  bindings/pydrake/geometry_py_all.cc
  bindings/pydrake/geometry_py_common.cc
  bindings/pydrake/test/geometry_all_test.py
  bindings/pydrake/test/geometry_common_test.py
Labels: status: commits are properly curated

#15789 [geometry/optimization] IrisInConfigurationSpace with Ibex
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/iris.cc
  geometry/optimization/iris.h
  geometry/optimization/test/iris_test.cc
Labels: release notes: yes
