Repository RobotLocomotion/drake, pull requests merged in 2021-03, with the labels that each got.

#14712 workspace: Upgrade ros_xacro to latest release 1.13.10
  tools/workspace/ros_xacro/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14713 workspace: Upgrade intel_realsense_ros to latest release 2.2.22
  tools/workspace/intel_realsense_ros/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14717 setup: Upgrade recommended Bazel version to 4.0
  doc/_pages/developers.md
  doc/developers.rst
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: component: build system, priority: low, status: single reviewer ok

#14711 workspace: Upgrade ghc_filesystem to latest release 1.5.0
  tools/workspace/ghc_filesystem/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14714 workspace: Upgrade osqp and qdldl
  tools/workspace/osqp/repository.bzl
  tools/workspace/qdldl/repository.bzl
Labels: component: build system, priority: low

#14715 workspace: Upgrade meshcat and meshcat_python to latest commit
  tools/workspace/meshcat/repository.bzl
  tools/workspace/meshcat_python/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14681 [FEM] Add abstract base class for FEM model and state
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/dirichlet_boundary_condition.h
  multibody/fixed_fem/dev/dynamic_elasticity_model.h
  multibody/fixed_fem/dev/elasticity_model.h
  multibody/fixed_fem/dev/fem_model.h
  multibody/fixed_fem/dev/fem_model_base.cc
  multibody/fixed_fem/dev/fem_model_base.h
  multibody/fixed_fem/dev/fem_solver.h
  multibody/fixed_fem/dev/fem_state.h
  multibody/fixed_fem/dev/fem_state_base.h
  multibody/fixed_fem/dev/newmark_scheme.h
  multibody/fixed_fem/dev/state_updater.h
  multibody/fixed_fem/dev/static_elasticity_model.h
  multibody/fixed_fem/dev/test/dirichlet_boundary_condition_test.cc
  multibody/fixed_fem/dev/test/dynamic_elasticity_model_test.cc
  multibody/fixed_fem/dev/test/fem_solver_test.cc
  multibody/fixed_fem/dev/test/newmark_scheme_test.cc
  multibody/fixed_fem/dev/test/static_elasticity_model_test.cc
  multibody/fixed_fem/dev/test/zeroth_order_state_updater_test.cc
  multibody/fixed_fem/dev/zeroth_order_state_updater.h
Labels: status: single reviewer ok

#14705 Upgrade sdformat to 10.3.0
  examples/manipulation_station/models/cupboard.sdf
  manipulation/models/wsg_50_description/sdf/schunk_wsg_50_no_tip.sdf
  manipulation/models/wsg_50_description/sdf/schunk_wsg_50_with_tip.sdf
  multibody/parsing/detail_scene_graph.cc
  multibody/parsing/detail_scene_graph.h
  multibody/parsing/test/detail_scene_graph_test.cc
  tools/workspace/pkg_config.BUILD.tpl
  tools/workspace/pkg_config.bzl
  tools/workspace/sdformat/3bbd303.patch
  tools/workspace/sdformat/no-console-file.patch
  tools/workspace/sdformat/package.BUILD.bazel
  tools/workspace/sdformat/repository.bzl
  tools/workspace/tinyxml/repository.bzl
Labels: status: commits are properly curated

#14728 Bump CRU and VGT externals to latest
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: component: geometry externals

#14709 common: Improve AbstractValue error message suggestions
  common/value.cc
Labels: priority: low

#14573 Add script for building drake-visualizer binaries for Ubuntu
  tools/workspace/drake_visualizer/.dockerignore
  tools/workspace/drake_visualizer/.editorconfig
  tools/workspace/drake_visualizer/0001-dv-opengl-glvnd.patch
  tools/workspace/drake_visualizer/0002-dv-externals-warnings.patch
  tools/workspace/drake_visualizer/0003-dv-externals-module-linker-flags.patch
  tools/workspace/drake_visualizer/Dockerfile
  tools/workspace/drake_visualizer/build_binaries_with_docker
Labels: component: build system, team: kitware

#14730 Use correct suffix for Python C extensions
  tools/skylark/pybind.bzl
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/python/repository.bzl
Labels: component: pydrake, priority: low, team: kitware

#14723 [FEM] Improve API for FemStateBase
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/fem_model.h
  multibody/fixed_fem/dev/fem_model_base.cc
  multibody/fixed_fem/dev/fem_model_base.h
  multibody/fixed_fem/dev/fem_solver.h
  multibody/fixed_fem/dev/fem_state.h
  multibody/fixed_fem/dev/fem_state_base.cc
  multibody/fixed_fem/dev/fem_state_base.h
  multibody/fixed_fem/dev/test/dirichlet_boundary_condition_test.cc
  multibody/fixed_fem/dev/test/fem_solver_test.cc
  multibody/fixed_fem/dev/test/fem_state_test.cc
Labels: priority: medium, status: single reviewer ok, status: squashing now, team: dynamics

#14737 doc: Fix 29 nits on new Jekyll website
  doc/_pages/clion.md
  doc/_pages/code_review_checklist.md
  doc/_pages/code_style_guide.md
  doc/_pages/code_style_tools.md
  doc/_pages/developers.md
  doc/_pages/getting_help.md
  doc/_pages/jenkins.md
  doc/_pages/mac.md
  doc/_pages/python_bindings.md
  doc/_pages/release_playbook.md
  doc/_pages/sublime_text.md
  doc/_pages/vim.md
  doc/_release-notes/older_releases.md
  doc/index.md
Labels: priority: high, status: single reviewer ok, type: documentation

#14734 [FEM] Add mesh utilities to support FEM demo
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/images/diamond_cubic_box_volume_mesh.png
  multibody/fixed_fem/dev/mesh_utilities.cc
  multibody/fixed_fem/dev/mesh_utilities.h
  multibody/fixed_fem/dev/test/mesh_utilities_test.cc
Labels: status: single reviewer ok, team: dynamics

#14738 framework: Add more checks that a Context matches its System
  systems/framework/diagram.cc
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
Labels: component: system framework, priority: low

#14743 pybind11: Remove stray coverage deps from mkdoc
  tools/workspace/pybind11/BUILD.bazel
Labels: component: build system, priority: low, status: single reviewer ok

#14225 workspace: Update pybind11 fork to latest commit
  bindings/pydrake/common/test/cpp_param_pybind_test.cc
  bindings/pydrake/common/test/cpp_template_pybind_test.cc
  bindings/pydrake/common/test/type_safe_index_pybind_test.cc
  bindings/pydrake/test/pydrake_pybind_test.cc
  tools/workspace/pybind11/package.BUILD.bazel
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok

#14748 Revert "[pybind] Moves a historically flaky RenderEngine test into its own test (#14724)"
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/geometry_render_engine_subclass_test.py
  bindings/pydrake/test/geometry_test.py
Labels: status: single reviewer ok, status: squashing now

#14753 doc: Debounce Jekyll nav menus
  doc/assets/css/main.css
Labels: priority: low, status: single reviewer ok, type: documentation

#14742 fix for jupyter runAll when using process_ipywidget_events
  bindings/pydrake/common/jupyter.py
Labels: status: single reviewer ok

#14750 Do not use yaml.CLoader in acrobot example
  examples/acrobot/acrobot_io.py
Labels: component: build system, team: kitware

#14719 Replaces std::string with std::string_view in MBP.
  bindings/pydrake/multibody/plant_py.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.h
  multibody/tree/string_view_map_key.h
  multibody/tree/test/string_view_map_key_test.cc
Labels: status: squashing now

#14751 workspace: Bump pybind11 fork to latest commit
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok

#14756 [patch] Adds the missing std header causing mac to fail
  multibody/tree/test/string_view_map_key_test.cc
Labels: priority: emergency, status: single reviewer ok

#14708 doc: Switch website to use Jekyll
  doc/build.py
Labels: component: build system, status: single reviewer ok, type: documentation

#14741 [FEM] Add SoftsimSystem and a large deformation demo
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/deformable_body_config.h
  multibody/fixed_fem/dev/dynamic_elasticity_element.h
  multibody/fixed_fem/dev/eigen_conjugate_gradient_solver.h
  multibody/fixed_fem/dev/elasticity_element.h
  multibody/fixed_fem/dev/fem_indexes.h
  multibody/fixed_fem/dev/fem_model.h
  multibody/fixed_fem/dev/linear_system_solver.h
  multibody/fixed_fem/dev/matrix_utilities.h
  multibody/fixed_fem/dev/mesh_utilities.h
  multibody/fixed_fem/dev/run_cantilever_beam.cc
  multibody/fixed_fem/dev/softsim_system.cc
  multibody/fixed_fem/dev/softsim_system.h
  multibody/fixed_fem/dev/state_updater.h
  multibody/fixed_fem/dev/test/softsim_system_test.cc
Labels: status: single reviewer ok

#14759 doc: Change Github to GitHub on the website
  doc/_includes/footer.html
  doc/_includes/header.html
  doc/_pages/from_source.md
Labels: status: single reviewer ok, team: kitware, type: documentation

#14765 py mbp: Fix typo on docstring for SpatialVelocity.Rotate
  bindings/pydrake/multibody/math_py.cc
Labels: status: single reviewer ok

#14764 getting_help: Fix typo (should be all-caps)
  doc/_pages/getting_help.md
Labels: status: single reviewer ok

#14766 Revert "Hardcode python version to 3.6 in setup_drake_colab"
  tools/install/colab/setup_drake_colab.py
Labels: component: distribution, priority: low, status: single reviewer ok, team: kitware

#14767 [FEM] Add support for basic deformable contact
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/deformable_contact.cc
  multibody/fixed_fem/dev/deformable_contact.h
  multibody/fixed_fem/dev/test/deformable_contact_test.cc
Labels: status: single reviewer ok

#14763 doc: Add cautionary comment about changing the hero text
  doc/index.md
Labels: priority: low, status: single reviewer ok

#14769 Update and re-enable drake-visualizer for macOS
  tools/workspace/drake_visualizer/drake_visualizer_bazel.py
  tools/workspace/drake_visualizer/drake_visualizer_installed.py.in
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/drake_visualizer/test/drake_visualizer_bazel_test.py
  tools/workspace/drake_visualizer/test/drake_visualizer_installed_test.py
Labels: component: build system, configuration: mac, priority: high, team: kitware

#14773 [geometry] Improve SceneGraph error for unconnected input ports
  geometry/scene_graph.cc
  geometry/test/scene_graph_test.cc
Labels: priority: low, status: single reviewer ok

#14771 Add script for building drake-visualizer on macOS
  tools/workspace/drake_visualizer/.dockerignore
  tools/workspace/drake_visualizer/0001-dv-ubuntu-opengl-glvnd.patch
  tools/workspace/drake_visualizer/0002-dv-all-externals-warnings.patch
  tools/workspace/drake_visualizer/0003-dv-all-externals-module-linker-flags.patch
  tools/workspace/drake_visualizer/0004-dv-mac-python-manager.patch
  tools/workspace/drake_visualizer/build_mac_binaries
  tools/workspace/drake_visualizer/repository.bzl
Labels: component: build system, configuration: mac, priority: medium, team: kitware

#14721 [FEM] Add analytic solution test for elasticity
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/doc/stretch_bar.png
  multibody/fixed_fem/dev/doc/stretch_bar_test.pdf
  multibody/fixed_fem/dev/doc/stretch_bar_test.tex
  multibody/fixed_fem/dev/test/stretch_test.cc
Labels: priority: low, status: single reviewer ok, team: dynamics

#14762 doc: Add release notes v0.28.0
  doc/_pages/release_playbook.md
  doc/_release-notes/template.txt
  doc/_release-notes/v0.28.0.md
Labels: status: squashing now

#14127 sensors: add documentation about the camera frame
  systems/sensors/camera_info.h
  systems/sensors/rgbd_sensor.h
Labels: status: single reviewer ok, status: squashing now

#14761 doc: Ensure website favicons render correctly on all platforms
  .gitattributes
  doc/BUILD.bazel
  doc/_layouts/default.html
  doc/android-chrome.png
  doc/apple-touch-icon.png
  doc/browserconfig.xml
  doc/favicon.ico
  doc/favicon.png
  doc/images/favicon.README.txt
  doc/images/favicon.png
  doc/mask-icon.svg
  doc/site.webmanifest
Labels: team: kitware, type: documentation

#14778 doc: Generate a minimal sitemap of HTML files
  doc/build.py
Labels: priority: low, team: kitware, type: documentation

#14780 Fix sitemap generation
  doc/build.py
Labels: status: single reviewer ok, team: kitware, type: bug, type: documentation

#14772 [geometry] Move elements of distance_to_shape.h into .cc
  geometry/proximity/BUILD.bazel
  geometry/proximity/distance_to_shape_callback.cc
  geometry/proximity/distance_to_shape_callback.h
  geometry/proximity/test/distance_sphere_to_shape_test.cc
Labels: status: single reviewer ok

#14788 systems: Avoid redundantly computing subsystem feedthrough maps
  systems/framework/diagram.cc
Labels: component: system framework, priority: high

#14791 Revert "Revert "[pybind] Moves a historically flaky RenderEngine test into its own test (#14724)""
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/geometry_render_engine_subclass_test.py
  bindings/pydrake/test/geometry_test.py
Labels: status: single reviewer ok

#14798 cmake: Fix python3 search for CMake 3.10 (Ubuntu 18.04)
  CMakeLists.txt
Labels: component: build system, priority: high

#14790 Add documentation on polynomial type.
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
Labels: status: single reviewer ok

#14797 workspace: Upgrade styleguide latest commit
  tools/workspace/styleguide/repository.bzl
Labels: priority: low, status: single reviewer ok

#14806 doc: Relocate bindings/pydrake/doc to doc/pydrake
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/doc/README.md
  bindings/pydrake/pydrake_doxygen.h
  doc/BUILD.bazel
  doc/README.txt
  doc/_pages/documentation_instructions.md
  doc/build.py
  doc/pydrake/BUILD.bazel
  doc/pydrake/LICENSE.TXT
  doc/pydrake/_static/css/custom.css
  doc/pydrake/conf.py
  doc/pydrake/gen_sphinx.py
  doc/pydrake/pydrake_sphinx_extension.py
  doc/pydrake/serve_sphinx.py
  doc/pydrake/sphinx.LICENSE.txt
  doc/pydrake/sphinx_base.py
Labels: priority: low, status: single reviewer ok

#14801 rotation_matrix: Minor fix for message on matrices that fail SO(3) check
  math/rotation_matrix.h
Labels: status: single reviewer ok

#14804 workspace: Deprecate the @sphinx repository
  doc/pydrake/BUILD.bazel
  doc/pydrake/sphinx_base.py
  tools/workspace/default.bzl
  tools/workspace/sphinx/repository.bzl
  tools/workspace/which.bzl
Labels: priority: low, status: single reviewer ok

#14813 py mbp: Fix bindings for plant test
  bindings/pydrake/multibody/test/plant_test.py
Labels: priority: emergency, status: single reviewer ok

#14810 doc: Relocate Doxygen tools into doxygen_cxx subdirectory
  doc/BUILD.bazel
  doc/README.txt
  doc/_pages/documentation_instructions.md
  doc/build.py
  doc/defs.bzl
  doc/doxygen_cxx/BUILD.bazel
  doc/doxygen_cxx/Doxyfile_CXX.in
  doc/doxygen_cxx/DoxygenLayout.xml
  doc/doxygen_cxx/build.py
  doc/doxygen_cxx/doxygen.h
  doc/doxygen_cxx/doxygen_extra.css
  doc/doxygen_cxx/footer.html
  doc/doxygen_cxx/system_doxygen.py
  doc/doxygen_cxx/test/system_doxygen_test.py
  doc/pydrake/BUILD.bazel
  doc/pydrake/pydrake_sphinx_extension.py
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pybind11/mkdoc_comment.py
Labels: priority: low, status: single reviewer ok

#14784 Use python3-semantic-version package on Ubuntu
  setup/mac/binary_distribution/requirements.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  tools/workspace/pycps/package.BUILD.bazel
  tools/workspace/semantic_version/package.BUILD.bazel
Labels: status: single reviewer ok, team: kitware

#14825 Perturbs multibody_plant_scalar_conversion_test to fix kcov failure
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
Labels: component: continuous integration, component: multibody plant, configuration: linux, priority: high, team: dynamics

#14811 doc: Add direct styleguide publication
  doc/BUILD.bazel
  doc/README.txt
  doc/_pages/documentation_instructions.md
  doc/build.py
  doc/defs.bzl
  doc/defs.py
  doc/styleguide/BUILD.bazel
  doc/styleguide/_config.yml
  doc/styleguide/_layouts/default.html
  doc/styleguide/build.py
  tools/workspace/styleguide/package.BUILD.bazel
Labels: priority: low

#14831 doc: Fix styleguide publication on Focal
  doc/styleguide/_config.yml
Labels: priority: emergency, status: single reviewer ok

#14835 Put GeometryPairContactWrenchEvaluatorBinding in the public namespace.
  multibody/optimization/contact_wrench_evaluator.h
  multibody/optimization/manipulator_equation_constraint.cc
  multibody/optimization/manipulator_equation_constraint.h
  multibody/optimization/static_equilibrium_constraint.cc
  multibody/optimization/static_equilibrium_constraint.h
Labels: status: single reviewer ok

#14832 Add python-tk@3.9 to mac prerequisites
  setup/mac/binary_distribution/Brewfile
Labels: configuration: mac, priority: high, status: single reviewer ok

#14823 Allow python binding of SignalLogger to log autodiffxd data.
  bindings/pydrake/common/test/numpy_compare_test.py
  bindings/pydrake/common/test_utilities/numpy_compare.py
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
Labels: status: squashing now

#14833 doc: Refactor main Jekyll site builder to use common code
  doc/BUILD.bazel
  doc/_config.yml
  doc/_pages/documentation_instructions.md
  doc/build.py
  doc/gen_jekyll.py
  doc/jekyll_base.py
  doc/pages.py
  doc/serve_jekyll.py
  doc/styleguide/build.py
Labels: priority: low
