Repository RobotLocomotion/drake, pull requests merged in 2021-08, with the labels that each got.

#15515 [workspace] Remove deprecated lcmtypes externals
  lcmtypes/BUILD.bazel
  systems/sensors/BUILD.bazel
  systems/sensors/image_to_lcm_image_array_t.h
  systems/sensors/lcm_image_array_to_images.h
  systems/sensors/lcm_image_traits.h
  systems/sensors/robotlocomotion_compat.h
  systems/sensors/test/lcm_image_array_to_images_deprecated_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/lcmtypes_bot2_core/BUILD.bazel
  tools/workspace/lcmtypes_bot2_core/package.BUILD.bazel
  tools/workspace/lcmtypes_bot2_core/package.cps
  tools/workspace/lcmtypes_bot2_core/repository.bzl
  tools/workspace/lcmtypes_robotlocomotion/BUILD.bazel
  tools/workspace/lcmtypes_robotlocomotion/package.BUILD.bazel
  tools/workspace/lcmtypes_robotlocomotion/package.cps
  tools/workspace/lcmtypes_robotlocomotion/repository.bzl
Labels: priority: low, status: single reviewer ok

#15542 [fem] Make fem indexes follow TypeSafeIndex convention
  multibody/fixed_fem/dev/fem_indexes.h
Labels: priority: backlog, release notes: none

#15517 [framework] Respell SFINAE for Apple Clang
  systems/framework/value_producer.h
Labels: priority: low, release notes: none, status: single reviewer ok

#15525 [geometry] Deprecate SceneGraphInspector::all_frame_ids()
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/test/geometry_test.py
  geometry/drake_visualizer.cc
  geometry/geometry_state.h
  geometry/scene_graph_inspector.h
  geometry/test/scene_graph_inspector_test.cc
  geometry/test/utilities_test.cc
  geometry/utilities.h
Labels: status: single reviewer ok

#15540 [parsing] Require exactly one model or world
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/parser_test.cc
Labels: priority: low

#15533 Retire many more duplicated-word typos
  bindings/pydrake/systems/system_sliders.py
  bindings/pydrake/systems/test/general_test.py
  common/symbolic_expression_cell.h
  common/test/reset_after_move_test.cc
  common/test/symbolic_simplification_test.cc
  common/test_utilities/expect_throws_message.h
  common/test_utilities/test/limit_malloc_test.cc
  common/type_safe_index.h
  common/yaml/yaml_read_archive.h
  common/yaml/yaml_write_archive.h
  doc/_pages/developers.md
  geometry/drake_visualizer.cc
  geometry/drake_visualizer.h
  geometry/optimization/graph_of_convex_sets.h
  geometry/proximity/test/mesh_plane_intersection_test.cc
  geometry/query_object.h
  geometry/shape_specification.h
  lcm/drake_lcm.h
  manipulation/kinova_jaco/jaco_command_receiver.cc
  math/autodiff.h
  math/roll_pitch_yaw.h
  math/rotation_matrix.h
  multibody/constraint/constraint_doxygen.h
  multibody/constraint/constraint_problem_data.h
  multibody/plant/hydroelastic_traction_calculator.cc
  multibody/plant/multibody_plant.h
  multibody/tree/articulated_body_inertia.h
  multibody/tree/body.h
  multibody/tree/spatial_inertia.h
  multibody/tree/test/multibody_tree_creation_test.cc
  solvers/mosek_solver.cc
  systems/analysis/dense_output.h
  systems/framework/context_base.h
  systems/framework/event.h
  systems/framework/system.h
  systems/systems.h
  tools/clion/bazel_wrapper
  tools/skylark/drake_cc.bzl
  tools/vector_gen/test/sample_test.cc
  tools/workspace/buildifier/repository.bzl
  tools/workspace/github.bzl
  tools/workspace/libblas/repository.bzl
  tools/workspace/liblapack/repository.bzl
  tools/workspace/openblas/repository.bzl
Labels: priority: low, release notes: none, status: single reviewer ok

#15532 [geometry] Finish deprecation of "is gradient unique" from signed distance queries
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  geometry/proximity/distance_to_point_callback.cc
  geometry/proximity/distance_to_point_callback.h
  geometry/proximity/distance_to_shape_callback.cc
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/distance_to_point_callback_test.cc
  geometry/query_results/signed_distance_pair.h
  geometry/query_results/signed_distance_to_point.h
Labels: priority: low, status: single reviewer ok

#15536 [fem] Add PermuteBlockVector()
  multibody/fixed_fem/dev/matrix_utilities.h
  multibody/fixed_fem/dev/permute_block_sparse_matrix.h
  multibody/fixed_fem/dev/test/matrix_utilities_test.cc
Labels: release notes: none, status: single reviewer ok

#15513 [common] Deprecate DRAKE_THROW_UNLESS on a bare pointer
  common/drake_throw.h
  common/test/drake_throw_test.cc
Labels: priority: low

#15547 [workspace] Upgrade styleguide latest commit
  tools/workspace/styleguide/repository.bzl
Labels: priority: low, status: single reviewer ok

#15544 [workspace] Upgrade gtest to latest release 1.11.0
  manipulation/models/jaco_description/urdf/test/jaco_arm_test.cc
  multibody/parsing/test/test_loaders.cc
  multibody/parsing/test/test_loaders.h
  tools/workspace/gtest/dont-define-test-f.patch
  tools/workspace/gtest/repository.bzl
Labels: priority: low, status: single reviewer ok

#15548 [workspace] Upgrade rules_pkg to latest release 0.5.0
  tools/workspace/rules_pkg/repository.bzl
Labels: priority: low, status: single reviewer ok

#15539 [systems/framework] Sugar for setting/getting Eigen::VectorX data from DiscreteValues
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  examples/manipulation_station/differential_ik.py
  examples/mass_spring_cloth/cloth_spring_model.cc
  examples/planar_gripper/planar_gripper_lcm.cc
  examples/planar_gripper/planar_manipuland_lcm.cc
  examples/rod2d/rod2d.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/planner/differential_inverse_kinematics_integrator.cc
  multibody/fixed_fem/dev/deformable_model.cc
  multibody/fixed_fem/dev/deformable_rigid_manager.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/discrete_update_manager_test.cc
  systems/analysis/test/simulator_test.cc
  systems/controllers/test/linear_model_predictive_controller_test.cc
  systems/framework/BUILD.bazel
  systems/framework/discrete_values.h
  systems/framework/test/discrete_values_test.cc
  systems/framework/test/system_symbolic_inspector_test.cc
  systems/framework/vector_system.h
  systems/primitives/affine_system.cc
  systems/primitives/discrete_derivative.cc
  systems/primitives/discrete_time_delay.cc
  systems/primitives/linear_system.cc
  systems/primitives/test/linear_system_test.cc
  systems/primitives/zero_order_hold.cc
  systems/trajectory_optimization/test/direct_transcription_test.cc
Labels: status: commits are properly curated

#15317 set unrecognized elements to warning
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: status: squashing now

#15526 [fem] Move DeformationGradientData out of dev
  multibody/fem/BUILD.bazel
  multibody/fem/deformation_gradient_data.cc
  multibody/fem/deformation_gradient_data.h
  multibody/fem/test/deformation_gradient_data_test.cc
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/constitutive_model.h
  multibody/fixed_fem/dev/corotated_model_data.h
  multibody/fixed_fem/dev/deformation_gradient_data.cc
  multibody/fixed_fem/dev/linear_constitutive_model_data.h
Labels: release notes: none

#15459 [fem] Calculate free motion velocities for contact
  multibody/fixed_fem/dev/deformable_rigid_manager.cc
  multibody/fixed_fem/dev/deformable_rigid_manager.h
  multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
Labels: release notes: none

#15506 Eschew use of operator!!
  bindings/pydrake/common/module_py.cc
  common/nice_type_name_override.cc
  common/test_utilities/limit_malloc.cc
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/multibody/acrobot/passive_simulation.cc
  examples/multibody/acrobot/run_lqr.cc
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
  examples/multibody/pendulum/passive_simulation.cc
  examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
  examples/simple_gripper/simple_gripper.cc
  multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
  systems/lcm/lcm_publisher_system.cc
Labels: priority: low, release notes: none, status: single reviewer ok

#15556 Adapt uses of reset_after_move vs Eigen 3.4 prerelease
  systems/primitives/vector_log.cc
Labels: priority: low, status: single reviewer ok

#15567 controllers: Reorder inverse dynamics test cases
  systems/controllers/test/inverse_dynamics_test.cc
Labels: status: single reviewer ok

#15557 [framework] Tidy up ValueProducer loose ends
  systems/framework/leaf_output_port.h
  systems/framework/value_producer.h
Labels: priority: backlog, status: single reviewer ok

#15487 [multibody] An option for discrete hydroelastics to choose the type of contact surfaces.
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: team: dynamics, priority: medium, component: geometry proximity

#15580 [solvers] Fix assertion in AddPositiveSemidefiniteConstraint
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  solvers/mathematical_program.h
Labels: priority: low

#15553 AddLorentzConeConstraint accept eval_type.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/constraint.h
  solvers/create_constraint.cc
  solvers/create_constraint.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/constraint_test.cc
  solvers/test/create_constraint_test.cc
  solvers/test/mathematical_program_test.cc
Labels: priority: low

#15566 [fem] Move LinearConstitutiveModelData out of dev
  multibody/fem/BUILD.bazel
  multibody/fem/linear_constitutive_model_data.cc
  multibody/fem/linear_constitutive_model_data.h
  multibody/fem/test/deformation_gradient_data_test.cc
  multibody/fem/test/linear_constitutive_model_data_test.cc
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/corotated_model_data.h
  multibody/fixed_fem/dev/linear_constitutive_model.h
  multibody/fixed_fem/dev/linear_constitutive_model_data.cc
Labels: priority: low, release notes: none

#15585 [pydrake] Don't load native code upon 'import pydrake'
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/common/__init__.py
  bindings/pydrake/examples/__init__.py
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/manipulation/__init__.py
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/__init__.py
  bindings/pydrake/perception_py.cc
  bindings/pydrake/solvers/__init__.py
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/systems/__init__.py
  bindings/pydrake/test/all_each_import_test.py
  bindings/pydrake/test/minimal_import_test.py
  bindings/pydrake/trajectories_py.cc
  doc/_pages/python_bindings.md
Labels: priority: high

#15589 [pydrake] Disable memory_maps acceptance test on macOS
  bindings/pydrake/test/minimal_import_test.py
Labels: priority: emergency, status: single reviewer ok

#15590 [manipulation_station] remove stray XML element from 061_foam_brick.sdf
  examples/manipulation_station/models/061_foam_brick.sdf
Labels: status: single reviewer ok, release notes: none

#15588 Fix a comment in BasicVector
  systems/framework/basic_vector.h
Labels: type: bug, priority: low, type: documentation, team: dynamics, status: single reviewer ok, component: system framework

#15587 pydrake: Add guidance for ambiguous const-vs-mutable overloads" (#15439)
  bindings/pydrake/pydrake_doxygen.h
Labels: priority: low, status: squashing now, release notes: none

#15592 VectorLogSink API for mutable access requires mutable Context
  systems/primitives/test/vector_log_sink_test.cc
  systems/primitives/vector_log_sink.cc
  systems/primitives/vector_log_sink.h
Labels: priority: high, team: dynamics, component: system framework, release notes: none

#15591 [pydrake] Various fixes in prep for pydrake.lcmtypes
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/test/all_each_import_test.py
  bindings/pydrake/visualization/__init__.py
  tools/workspace/lcm/example/BUILD.bazel
  tools/workspace/lcm/example/README.md
  tools/workspace/lcm/example/lcmt_bar.lcm
  tools/workspace/lcm/example/lcmt_foo.lcm
  tools/workspace/lcm/example/test/cc_lib_test.cc
  tools/workspace/lcm/example/test/py_lib_test.py
  tools/workspace/lcm/lcm.bzl
Labels: priority: medium

#15595 Speed up ValidateCreatedForThisSystem() for inner-loop use
  common/identifier.h
  common/test/identifier_test.cc
  systems/framework/diagram.cc
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/system_compatibility_doxygen.h
  systems/framework/system_output.h
  systems/framework/test/system_base_test.cc
Labels: team: dynamics, priority: medium, type: performance, component: system framework

#15489 Replace an expensive dynamic_cast with a cheap static_cast
  multibody/parsing/test/acrobot_parser_test.cc
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.h
Labels: priority: low, team: dynamics, type: performance, component: multibody plant

#15516 doc: Add release notes v0.33.0
  doc/_release-notes/v0.33.0.md
Labels: priority: high, status: do not merge, status: single reviewer ok, release notes: none

#15598 [lcmtypes] Refactor build file to rely less on globbing
  lcmtypes/BUILD.bazel
  lcmtypes/defs.bzl
Labels: priority: medium, status: single reviewer ok

#15584 Make simulator config functions autodiffable.
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  systems/analysis/BUILD.bazel
  systems/analysis/simulator_config_functions.cc
  systems/analysis/simulator_config_functions.h
  systems/analysis/simulator_gflags.cc
  systems/analysis/simulator_gflags.h
  systems/analysis/simulator_print_stats.cc
  systems/analysis/simulator_print_stats.h
  systems/analysis/test/simulator_config_functions_test.cc
  systems/analysis/test/simulator_gflags_main.cc
  systems/analysis/test/simulator_gflags_test.py
  systems/analysis/test/simulator_print_stats_test.cc
Labels: priority: medium

#15572 Add GraphOfConvexSets::LockEdge()
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: squashing now

#15605 [fem] FEM matrix math helpers improvements
  multibody/fixed_fem/dev/matrix_utilities.h
Labels: priority: low, status: single reviewer ok, release notes: none

#15559 [fem] Calculate two-way coupled contact results
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/deformable_model.cc
  multibody/fixed_fem/dev/deformable_model.h
  multibody/fixed_fem/dev/deformable_rigid_manager.cc
  multibody/fixed_fem/dev/deformable_rigid_manager.h
  multibody/fixed_fem/dev/inverse_spd_operator.cc
  multibody/fixed_fem/dev/inverse_spd_operator.h
  multibody/fixed_fem/dev/test/deformable_rigid_contact_solver_test.cc
  multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
  multibody/fixed_fem/dev/test/inverse_spd_operator_test.cc
Labels: status: single reviewer ok, release notes: none

#15607 [solvers] IbexSolver supports more constraints / costs
  solvers/ibex_solver.cc
  solvers/ibex_solver.h
  solvers/ibex_solver_common.cc
  solvers/test/ibex_solver_test.cc
Labels: team: robot locomotion group

#15564 Switch to per-context dummy CacheEntryValue for thread safety
  systems/framework/BUILD.bazel
  systems/framework/cache.h
  systems/framework/context_base.h
  systems/framework/dependency_tracker.cc
  systems/framework/dependency_tracker.h
  systems/framework/framework_common.h
  systems/framework/test/dependency_tracker_test.cc
  systems/framework/test/thread_sanitizer_test.cc
Labels: type: feature request, team: dynamics, priority: medium, component: system framework

#15537 Perform MonteCarloSimulation in parallel
  bindings/pydrake/systems/analysis_py.cc
  systems/analysis/BUILD.bazel
  systems/analysis/monte_carlo.cc
  systems/analysis/monte_carlo.h
  systems/analysis/test/monte_carlo_test.cc
Labels: priority: low

#15617 [geometry] Correct internal nomenclature for collision filtering
  geometry/collision_filter_manager.h
  geometry/geometry_state.cc
  geometry/proximity/collision_filter.cc
  geometry/proximity/collision_filter.h
  geometry/proximity/test/collision_filter_test.cc
  geometry/proximity/test/collisions_exist_callback_test.cc
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/find_collision_candidates_callback_test.cc
  geometry/proximity/test/hydroelastic_callback_test.cc
  geometry/proximity/test/penetration_as_point_pair_callback_test.cc
  geometry/test/proximity_engine_test.cc
Labels: status: single reviewer ok, release notes: none

#15593 [fem] Modify NewmarkScheme to allow velocity as the unknown variable
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/acceleration_newmark_scheme.cc
  multibody/fixed_fem/dev/acceleration_newmark_scheme.h
  multibody/fixed_fem/dev/dynamic_elasticity_model.h
  multibody/fixed_fem/dev/elasticity_element.h
  multibody/fixed_fem/dev/newmark_scheme.h
  multibody/fixed_fem/dev/test/acceleration_newmark_scheme_test.cc
  multibody/fixed_fem/dev/test/newmark_scheme_test.cc
  multibody/fixed_fem/dev/test/velocity_newmark_scheme_test.cc
  multibody/fixed_fem/dev/velocity_newmark_scheme.cc
  multibody/fixed_fem/dev/velocity_newmark_scheme.h
Labels: priority: low, status: single reviewer ok, release notes: none

#15477 Adding collision filter groups sdf support
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/links_with_visuals_and_collisions.sdf
  multibody/parsing/test/sdf_parser_test/collision_filter_group_parsing_test.sdf
Labels: status: squashing now

#15622 [fem] Fix bug in DeformableRigidContactData
  multibody/fixed_fem/dev/deformable_contact_data.h
  multibody/fixed_fem/dev/test/deformable_contact_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#15611 [fem] Implement DeformableRigidManager::DoCalcContactSolverResults()
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/deformable_rigid_manager.cc
  multibody/fixed_fem/dev/deformable_rigid_manager.h
  multibody/fixed_fem/dev/run_cantilever_beam.cc
  multibody/fixed_fem/dev/test/deformable_rigid_contact_solver_test.cc
  multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
  multibody/fixed_fem/dev/test/rigid_update_test.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
Labels: priority: high, release notes: none

#15575 Fix #15569 By adding SubscribeAllChannels and get_lcm_url
  lcm/drake_lcm.cc
  lcm/drake_lcm.h
  lcm/drake_lcm_interface.h
  lcm/drake_lcm_log.cc
  lcm/drake_lcm_log.h
  lcm/test/drake_lcm_log_test.cc
  lcm/test/drake_lcm_test.cc
  lcm/test/drake_mock_lcm_test.cc
  systems/lcm/lcm_interface_system.cc
  systems/lcm/lcm_interface_system.h
Labels: priority: low, release notes: breaking change

#15618 [geometry] Establishes Meshcat in C++ (step 1)
  doc/BUILD.bazel
  geometry/dev/BUILD.bazel
  geometry/dev/meshcat.cc
  geometry/dev/meshcat.h
  geometry/dev/meshcat_demo.cc
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/meshcat/package.BUILD.bazel
  tools/workspace/msgpack/BUILD.bazel
  tools/workspace/msgpack/repository.bzl
  tools/workspace/usockets/BUILD.bazel
  tools/workspace/usockets/package.BUILD.bazel
  tools/workspace/usockets/repository.bzl
  tools/workspace/uwebsockets/BUILD.bazel
  tools/workspace/uwebsockets/package.BUILD.bazel
  tools/workspace/uwebsockets/repository.bzl
Labels: priority: high

#15624 [doc] Add more relnotes and review assignment processes
  doc/_pages/platform_reviewer_checklist.md
  doc/_pages/reviewable.md
Labels: priority: low, type: documentation, release notes: none

#15639 Deprecate various unused bits of code
  common/BUILD.bazel
  common/eigen_stl_types.h
  manipulation/schunk_wsg/schunk_buttons.py
  multibody/tree/position_kinematics_cache.h
  tools/workspace/jsoncpp/BUILD.bazel
  tools/workspace/jsoncpp/repository.bzl
Labels: type: cleanup, priority: low, team: kitware, status: single reviewer ok, component: build system, release notes: newly deprecated

#15600 [tools] Link ignition-math statically
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake.cps
  tools/workspace/ignition_math/package.BUILD.bazel
  tools/workspace/sdformat/package.BUILD.bazel
Labels: priority: low

#15621 [fem] Prepare to move utility methods out of dev
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/calc_lame_parameters.cc
  multibody/fixed_fem/dev/calc_lame_parameters.h
  multibody/fixed_fem/dev/corotated_model.cc
  multibody/fixed_fem/dev/deformable_rigid_manager.cc
  multibody/fixed_fem/dev/linear_constitutive_model.cc
  multibody/fixed_fem/dev/matrix_utilities.cc
  multibody/fixed_fem/dev/matrix_utilities.h
  multibody/fixed_fem/dev/permute_block_sparse_matrix.cc
  multibody/fixed_fem/dev/permute_block_sparse_matrix.h
  multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc
  multibody/fixed_fem/dev/test/matrix_utilities_test.cc
  multibody/fixed_fem/dev/test/test_utilities.cc
  multibody/fixed_fem/dev/test/test_utilities.h
Labels: priority: low, status: single reviewer ok, release notes: none

#15648 [manipulation/models] Fix warnings generated by sdf parsing of ycb objects
  manipulation/models/ycb/sdf/003_cracker_box.sdf
  manipulation/models/ycb/sdf/004_sugar_box.sdf
  manipulation/models/ycb/sdf/005_tomato_soup_can.sdf
  manipulation/models/ycb/sdf/006_mustard_bottle.sdf
  manipulation/models/ycb/sdf/009_gelatin_box.sdf
  manipulation/models/ycb/sdf/010_potted_meat_can.sdf
Labels: status: single reviewer ok

#15649 [geometry] Minor fixups
  geometry/drake_visualizer.cc
  geometry/scene_graph_inspector.h
Labels: status: single reviewer ok, release notes: none

#15650 Turn off kcov on a test that hit kcov#339
  systems/controllers/BUILD.bazel
Labels: status: single reviewer ok

#15561 MBP SetPositions(.), SetVelocities(.) etc. take an Eigen::Ref rather than a VectorX
  bindings/pydrake/multibody/plant_py.cc
  geometry/optimization/iris.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: release notes: breaking change

#15654 Remove .clang-tidy
  .clang-tidy
Labels: status: squashing now, status: single reviewer ok

#15612 [solvers] Support IBEX Solver options
  solvers/BUILD.bazel
  solvers/constraint.cc
  solvers/ibex_solver.cc
  solvers/ibex_solver.h
  solvers/solver_options.h
  solvers/test/constraint_test.cc
  solvers/test/ibex_solver_test.cc
Labels: status: commits are properly curated

#15646 multibody: Properly validate State at public APIs
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok

#15653 Allow multiple LcmInterfaceSystems on the same URL
  systems/lcm/lcm_interface_system.cc
  systems/lcm/test/lcm_interface_system_test.cc
Labels: status: single reviewer ok

#15641 py value: Register Value[float] for use with ProximityProperties
  bindings/pydrake/common/test/value_test.py
  bindings/pydrake/common/value_py.cc
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
Labels: status: single reviewer ok

#15657 [framework] Fix deprecated AddIfSupported scalar conversion helper
  systems/framework/system_scalar_converter.h
  systems/framework/test/system_scalar_converter_test.cc
Labels: priority: medium, status: single reviewer ok

#15656 [multibody] Add new enumerator names for ContactModel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: priority: low

#15658 Deprecate two unused autodiff utility functions
  math/autodiff.h
  math/autodiff_gradient.h
Labels: type: cleanup, priority: low, team: dynamics, status: single reviewer ok, release notes: newly deprecated

#15659 py math: Add patch for rich comparison operators; test combinatorics
  bindings/pydrake/_math_extra.py
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/common/test_utilities/numpy_compare.py
  bindings/pydrake/test/autodiffutils_test.py
  bindings/pydrake/test/symbolic_test.py
Labels: priority: high

#15680 detail_sdf_parser: Shift date (error on bad elements) back to 2022-01-01
  multibody/parsing/detail_sdf_parser.cc
Labels: status: single reviewer ok

#15541 Choose best solver based on program type.
  geometry/optimization/test/graph_of_convex_sets_test.cc
  solvers/BUILD.bazel
  solvers/choose_best_solver.cc
  solvers/get_program_type.cc
  solvers/mathematical_program_doxygen.h
  solvers/program_attribute.h
  solvers/test/choose_best_solver_test.cc
  solvers/test/solve_test.cc
Labels: priority: low

#15686 Fixes BodyNode::GetJacobianFromArray() to return an empty map when nv=0.
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/tree/body_node.h
Labels: type: bug, team: dynamics, component: multibody plant
