Repository RobotLocomotion/drake, pull requests merged in 2021-02, with the labels that each got.

#14600 Update VGT external for new device voxelizer interface
  tools/workspace/voxelized_geometry_tools/package.BUILD.bazel
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: component: geometry externals

#14567 Implement Dirichlet boundary condition
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/dirichlet_boundary_condition.h
  multibody/fixed_fem/dev/fem_indexes.h
  multibody/fixed_fem/dev/test/dirichlet_boundary_condition_test.cc
Labels: status: single reviewer ok

#14615 primitives: Promote some ASSERT to DEMAND
  systems/primitives/affine_system.cc
  systems/primitives/first_order_low_pass_filter.cc
  systems/primitives/integrator.cc
  systems/primitives/linear_system.cc
Labels: priority: low, status: single reviewer ok

#14607 Remove deprecated code 2021-02
  multibody/math/spatial_vector.h
  setup/mac/binary_distribution/install_prereqs.sh
  systems/sensors/BUILD.bazel
  systems/sensors/accelerometer_sensor.h
  systems/sensors/gyroscope_sensor.h
Labels: priority: low

#14609 doc: Remove vestigial sw2urdf.tex file
  doc/sw2urdf.tex
Labels: status: single reviewer ok

#14525 acrobot: Fix spong LCM to actually work
  examples/acrobot/README.md
  examples/acrobot/spong_controller_w_lcm.cc
Labels: priority: low

#14608 Allow for new macOS versioning scheme and sync minimum compiler and CMake versions for macOS
  CMakeLists.txt
  doc/developers.rst
  tools/macos.bazelrc
  tools/workspace/cc/repository.bzl
  tools/workspace/os.bzl
Labels: component: build system, configuration: mac, priority: medium, status: commits are properly curated, status: single reviewer ok, team: kitware

#14595 Implement external force in ElasticityElement/Model
  multibody/fixed_fem/dev/dynamic_elasticity_element.h
  multibody/fixed_fem/dev/elasticity_element.h
  multibody/fixed_fem/dev/elasticity_model.h
  multibody/fixed_fem/dev/fem_model.h
  multibody/fixed_fem/dev/static_elasticity_element.h
  multibody/fixed_fem/dev/static_elasticity_model.h
  multibody/fixed_fem/dev/test/dynamic_elasticity_element_test.cc
  multibody/fixed_fem/dev/test/elasticity_element_test.cc
  multibody/fixed_fem/dev/test/static_elasticity_element_test.cc
  multibody/fixed_fem/dev/test/static_elasticity_model_test.cc
Labels: status: single reviewer ok

#14620 workspace: Upgrade fcl to latest commit
  tools/workspace/fcl/repository.bzl
Labels: status: single reviewer ok

#14472 Add lint check for unguarded OpenMP uses
  tools/lint/drakelint.py
Labels: status: squashing now, type: TRI anzu wishlist

#14618 yaml: Allow for operating on non-default MaxRows or MaxCols storage
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/test/yaml_write_archive_test.cc
  common/yaml/yaml_read_archive.h
  common/yaml/yaml_write_archive.h
Labels: priority: low

#14492 Add retry to brew and apt-get update calls and add flag to skip update altogether
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  setup/ubuntu/binary_distribution/install_prereqs.sh
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: component: continuous integration, priority: low, team: kitware

#14569 Templatize DrakeVisualizer class.
  bindings/pydrake/geometry_py.cc
  bindings/pydrake/test/geometry_test.py
  geometry/BUILD.bazel
  geometry/drake_visualizer.cc
  geometry/drake_visualizer.h
  geometry/test/drake_visualizer_test.cc
Labels: status: squashing now

#14627 Pybind MathematicalProgram::NewNonnegativePolynomial
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: status: single reviewer ok

#14625 Pass the time limit to OSQP settings
  solvers/osqp_solver.cc
  solvers/test/osqp_solver_test.cc
Labels: status: squashing now

#14622 Hydroelastic visualization speedup
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
Labels: component: geometry externals, priority: high, team: dynamics, type: performance

#14632 Add support for macOS Big Sur 11.x
  CMakeLists.txt
  doc/developers.rst
  examples/manipulation_station/end_effector_teleop_sliders.py
  tools/workspace/os.bzl
Labels: component: build system, configuration: mac, status: commits are properly curated, team: kitware

#14612 Convert rst to md
  doc/_release-notes/older_releases.md
  doc/_release-notes/v0.10.0.md
  doc/_release-notes/v0.11.0.md
  doc/_release-notes/v0.12.0.md
  doc/_release-notes/v0.13.0.md
  doc/_release-notes/v0.14.0.md
  doc/_release-notes/v0.15.0.md
  doc/_release-notes/v0.16.0.md
  doc/_release-notes/v0.16.1.md
  doc/_release-notes/v0.17.0.md
  doc/_release-notes/v0.18.0.md
  doc/_release-notes/v0.19.0.md
  doc/_release-notes/v0.20.0.md
  doc/_release-notes/v0.21.0.md
  doc/_release-notes/v0.22.0.md
  doc/_release-notes/v0.23.0.md
  doc/_release-notes/v0.24.0.md
  doc/_release-notes/v0.25.0.md
  doc/_release-notes/v0.26.0.md
  doc/bazel.md
  doc/buildcop.md
  doc/clion.md
  doc/code_review_checklist.md
  doc/code_style_guide.md
  doc/code_style_tools.md
  doc/credits.md
  doc/developers.md
  doc/development_on_mac.md
  doc/directory_structure.md
  doc/docker.md
  doc/documentation_instructions.md
  doc/downstream_testing.md
  doc/doxygen_instructions.md
  doc/from_binary.md
  doc/from_source.md
  doc/gallery.md
  doc/getting_help.md
  doc/index.md
  doc/installation.md
  doc/issues.md
  doc/jenkins.md
  doc/julia_bindings.md
  doc/mac.md
  doc/model_version_control.md
  doc/no_push_to_origin.md
  doc/platform_reviewer_checklist.md
  doc/python_bindings.md
  doc/release_playbook.md
  doc/reviewable.md
  doc/sphinx_instructions.md
  doc/stackoverflow_notifications.md
  doc/sublime_text.md
  doc/ubuntu.md
  doc/unicode_tips_tricks.md
  doc/unit_testing_instructions.md
  doc/vim.md
Labels: status: commits are properly curated

#14637 Increase error margin for OSQP solve time in the unit test
  solvers/test/osqp_solver_test.cc
Labels: priority: emergency, status: squashing now

#14645 Check status code in OSQP time limit test instead
  solvers/test/osqp_solver_test.cc
Labels: status: squashing now

#14647 release notes: Remove `attic` from template
  doc/release_notes/template.txt
Labels: status: single reviewer ok

#14653 doc: Add example of searching for commits that modify deprecations
  doc/code_review_checklist.rst
Labels: status: single reviewer ok

#14643 Tests to ensure RigidTransform<double> can work with optimization instructions.
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
Labels: priority: medium, team: dynamics, type: performance

#14660 getting_help: Add hints for Binder / Colab
  doc/getting_help.rst
Labels: status: single reviewer ok

#14658 doc: Move Jekyll Markdown pages to `_pages`, hoist headings
  doc/_pages/bazel.md
  doc/_pages/buildcop.md
  doc/_pages/clion.md
  doc/_pages/code_review_checklist.md
  doc/_pages/code_style_guide.md
  doc/_pages/code_style_tools.md
  doc/_pages/credits.md
  doc/_pages/developers.md
  doc/_pages/development_on_mac.md
  doc/_pages/directory_structure.md
  doc/_pages/docker.md
  doc/_pages/documentation_instructions.md
  doc/_pages/downstream_testing.md
  doc/_pages/doxygen_instructions.md
  doc/_pages/from_binary.md
  doc/_pages/from_source.md
  doc/_pages/gallery.md
  doc/_pages/getting_help.md
  doc/_pages/installation.md
  doc/_pages/issues.md
  doc/_pages/jenkins.md
  doc/_pages/julia_bindings.md
  doc/_pages/mac.md
  doc/_pages/model_version_control.md
  doc/_pages/no_push_to_origin.md
  doc/_pages/platform_reviewer_checklist.md
  doc/_pages/python_bindings.md
  doc/_pages/release_playbook.md
  doc/_pages/reviewable.md
  doc/_pages/sphinx_instructions.md
  doc/_pages/stackoverflow_notifications.md
  doc/_pages/sublime_text.md
  doc/_pages/ubuntu.md
  doc/_pages/unicode_tips_tricks.md
  doc/_pages/unit_testing_instructions.md
  doc/_pages/vim.md
  doc/_release-notes/older_releases.md
  doc/_release-notes/v0.11.0.md
  doc/_release-notes/v0.12.0.md
  doc/_release-notes/v0.13.0.md
  doc/_release-notes/v0.14.0.md
  doc/_release-notes/v0.15.0.md
  doc/_release-notes/v0.16.0.md
  doc/_release-notes/v0.16.1.md
  doc/_release-notes/v0.17.0.md
  doc/_release-notes/v0.18.0.md
  doc/_release-notes/v0.19.0.md
  doc/_release-notes/v0.20.0.md
  doc/_release-notes/v0.21.0.md
  doc/_release-notes/v0.22.0.md
  doc/_release-notes/v0.23.0.md
  doc/_release-notes/v0.24.0.md
  doc/_release-notes/v0.25.0.md
  doc/_release-notes/v0.26.0.md
Labels: priority: high, status: commits are properly curated, status: single reviewer ok

#14659 doc: Update Markdown to ensure Jekyll preview can work
  doc/_pages/clion.md
  doc/_pages/gallery.md
  doc/_pages/python_bindings.md
  doc/_release-notes/v0.17.0.md
  doc/_release-notes/v0.18.0.md
  doc/_release-notes/v0.19.0.md
  doc/_release-notes/v0.20.0.md
  doc/_release-notes/v0.22.0.md
  doc/_release-notes/v0.26.0.md
Labels: status: single reviewer ok

#14666 gitattributes: Treat svg files as binaries
  .gitattributes
Labels: status: single reviewer ok

#14605 Switch to Python 3.9 on macOS
  CMakeLists.txt
  doc/_pages/developers.md
  doc/_pages/python_bindings.md
  doc/developers.rst
  doc/python_bindings.rst
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  tools/install/install_test_helper.py
  tools/py_toolchain/interpreter_paths.bzl
  tools/workspace/drake_visualizer/drake_visualizer_bazel.py
  tools/workspace/drake_visualizer/drake_visualizer_installed.py.in
  tools/workspace/drake_visualizer/test/drake_visualizer_bazel_test.py
  tools/workspace/drake_visualizer/test/drake_visualizer_installed_test.py
  tools/workspace/python/repository.bzl
Labels: component: build system, configuration: mac, status: commits are properly curated, team: kitware

#14614 doc: Add third-party images (GitHub, Python)
  doc/third_party/README.md
  doc/third_party/images/GitHub-Mark-64px.png
  doc/third_party/images/GitHub-Mark-Light-64px.png
  doc/third_party/images/GitHub-Mark.README.md
  doc/third_party/images/python-logo-generic.svg
  doc/third_party/images/python.README.md
Labels: priority: high

#14665 doc/BUILD: Carve out Sphinx images for use in Jekyll website
  doc/BUILD.bazel
Labels: status: single reviewer ok

#14613 doc: Add in novel Drake images for newer website
  doc/images/drake-dragon.README.md
  doc/images/drake-dragon.png
  doc/images/drake-dragon.svg
  doc/images/drake-logo-white.svg
  doc/images/drake-logo.svg
  doc/images/favicon.README.md
  doc/images/favicon.png
Labels: priority: high

#14662 third_party: Import dracula, github-styling, and pylons
  doc/third_party/dracula/LICENSE.txt
  doc/third_party/dracula/README.md
  doc/third_party/dracula/syntax.css
  doc/third_party/github-styling/LICENSE.txt
  doc/third_party/github-styling/README.md
  doc/third_party/github-styling/github-markdown.css
  doc/third_party/pylons/CONTRIBUTORS.txt
  doc/third_party/pylons/LICENSE.txt
  doc/third_party/pylons/README.md
  doc/third_party/pylons/dialog-note.png
  doc/third_party/pylons/dialog-warning.png
  doc/third_party/pylons/pylons.css
Labels: priority: high, status: commits are properly curated

#14651 release_playbook: Modifications used for v0.27.0
  doc/release_playbook.rst
  tools/release_engineering/BUILD.bazel
  tools/release_engineering/download_release_candidate.py
  tools/release_engineering/relnotes.py
Labels: status: single reviewer ok

#14672 jekyll: Do not use strict mode
  doc/_config.yml
  doc/_includes/header.html
Labels: priority: emergency

#14674 [geometry] Fix-forward for CI failures on `make_capsule_mesh_test`.
  geometry/proximity/BUILD.bazel
  geometry/proximity/test/make_capsule_mesh_test.cc
Labels: priority: emergency

#14669 pybind: Hard code -std=c++17 option spelling
  tools/skylark/pybind.bzl
Labels: component: build system, priority: low

#14678 Test to ensure RigidTransform<double> can work with optimization instructions.…
  math/rotation_matrix.h
Labels: component: multibody plant, priority: medium, status: single reviewer ok, team: dynamics, type: performance

#14683 jekyll: Move release_notes index into the collection
  doc/BUILD.bazel
  doc/README.txt
  doc/_layouts/release.html
  doc/_pages/installation.md
  doc/_release-notes/release_notes.md
Labels: priority: medium, status: single reviewer ok

#14684 jekyll: Misc fixes
  doc/_pages/clion.md
  doc/_pages/code_style_guide.md
  doc/_pages/from_binary.md
  doc/_pages/from_source.md
Labels: priority: medium, status: single reviewer ok

#14682 jekyll: Fix sample_vimrc dowload link
  doc/BUILD.bazel
  doc/_pages/vim.md
Labels: priority: medium, status: single reviewer ok

#14687 jekyll: Ports recent .rst changes to Markdown
  doc/_pages/getting_help.md
  doc/_pages/release_playbook.md
  doc/_release-notes/v0.27.0.md
  doc/release_playbook.rst
Labels: status: commits are properly curated, status: single reviewer ok

#14679 [tools:drake_visualizer] Simple vector menu for hydroelastic contact.
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_pair_contact.py
Labels: component: geometry externals, priority: high, team: dynamics, type: feature request

#14693 Hardcode python version to 3.6 in setup_drake_colab
  tools/install/colab/setup_drake_colab.py
Labels: priority: emergency, status: single reviewer ok

#14685 jekyll: Add landing page links to binder and nbviewer
  doc/index.md
Labels: priority: medium, status: single reviewer ok

#14696 doc: Tidy up Jekyll instructions
  doc/_pages/documentation_instructions.md
  doc/documentation_instructions.rst
Labels: priority: medium, status: single reviewer ok, type: documentation

#14663 Make sure DoCalcNextUpdateTime() timed trigger is accompanied by an Event object.
  systems/analysis/integrator_base.h
  systems/analysis/simulator.cc
  systems/analysis/simulator.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_test.cc
  systems/lcm/lcm_interface_system.cc
Labels: component: simulator, priority: medium

#14698 Enable simple caching for FEM state dependent quantities
  multibody/fixed_fem/dev/element_cache_entry.h
  multibody/fixed_fem/dev/fem_state.h
  multibody/fixed_fem/dev/newmark_scheme.h
  multibody/fixed_fem/dev/test/dummy_element.h
  multibody/fixed_fem/dev/test/dynamic_elasticity_model_test.cc
  multibody/fixed_fem/dev/test/elasticity_element_test.cc
  multibody/fixed_fem/dev/test/fem_solver_test.cc
  multibody/fixed_fem/dev/test/fem_state_test.cc
  multibody/fixed_fem/dev/test/newmark_scheme_test.cc
  multibody/fixed_fem/dev/test/static_elasticity_model_test.cc
  multibody/fixed_fem/dev/zeroth_order_state_updater.h
Labels: status: single reviewer ok

#14700 fixed two links on the homepage that were not correct
  doc/index.md
Labels: status: single reviewer ok

#14710 setup: Remove stale paths for macOS dependencies
  setup/mac/binary_distribution/install_prereqs.sh
  tools/workspace/ipopt/repository.bzl
Labels: component: build system, priority: low, status: single reviewer ok

#14716 [doc] Remove example using RenderEngineOspray
  doc/_pages/gallery.md
  doc/gallery.rst
Labels: status: single reviewer ok
