Repository RobotLocomotion/drake, pull requests merged in 2022-10, with the labels that each got.

#18017 py deprecation: Ignore warnings for dtype=object operations
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/test/symbolic_test.py
Labels: release notes: fix

#18012 [solvers] Remove deprecated code 2022-10
  solvers/fbstab/BUILD.bazel
  solvers/fbstab/README.md
  solvers/fbstab/components/BUILD.bazel
  solvers/fbstab/components/dense_data.cc
  solvers/fbstab/components/dense_data.h
  solvers/fbstab/components/dense_feasibility.cc
  solvers/fbstab/components/dense_feasibility.h
  solvers/fbstab/components/dense_linear_solver.cc
  solvers/fbstab/components/dense_linear_solver.h
  solvers/fbstab/components/dense_residual.cc
  solvers/fbstab/components/dense_residual.h
  solvers/fbstab/components/dense_variable.cc
  solvers/fbstab/components/dense_variable.h
  solvers/fbstab/components/mpc_data.cc
  solvers/fbstab/components/mpc_data.h
  solvers/fbstab/components/mpc_feasibility.cc
  solvers/fbstab/components/mpc_feasibility.h
  solvers/fbstab/components/mpc_residual.cc
  solvers/fbstab/components/mpc_residual.h
  solvers/fbstab/components/mpc_variable.cc
  solvers/fbstab/components/mpc_variable.h
  solvers/fbstab/components/riccati_linear_solver.cc
  solvers/fbstab/components/riccati_linear_solver.h
  solvers/fbstab/components/test/dense_component_unit_tests.cc
  solvers/fbstab/components/test/dense_component_unit_tests.h
  solvers/fbstab/components/test/mpc_component_unit_tests.cc
  solvers/fbstab/components/test/mpc_component_unit_tests.h
  solvers/fbstab/fbstab_algorithm.h
  solvers/fbstab/fbstab_dense.cc
  solvers/fbstab/fbstab_dense.h
  solvers/fbstab/fbstab_mpc.cc
  solvers/fbstab/fbstab_mpc.h
  solvers/fbstab/test/fbstab_dense_unit_tests.cc
  solvers/fbstab/test/fbstab_mpc_unit_tests.cc
  solvers/fbstab/test/ocp_generator.cc
  solvers/fbstab/test/ocp_generator.h
  tools/install/libdrake/build_components.bzl
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#18013 [workspace] Remove deprecated externals 2022-10
  tools/workspace/BUILD.bazel
  tools/workspace/boost/BUILD.bazel
  tools/workspace/boost/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/meshcat_python/BUILD.bazel
  tools/workspace/meshcat_python/meshcat-server.py
  tools/workspace/meshcat_python/package.BUILD.bazel
  tools/workspace/meshcat_python/repository.bzl
  tools/workspace/meshcat_python/test/meshcat-server-install-test.py
  tools/workspace/meshcat_python/test/meshcat_server_test.py
  tools/workspace/meshcat_python/test/meshcat_test.py
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#18014 [misc] Remove deprecated code 2022-10
  bindings/pydrake/geometry_py_scene_graph.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/test/geometry_scene_graph_test.py
  bindings/pydrake/test/lcm_test.py
  geometry/BUILD.bazel
  geometry/frame_kinematics_vector.h
  geometry/kinematics_vector.cc
  geometry/kinematics_vector.h
  geometry/test/kinematics_vector_test.cc
  lcm/drake_lcm.cc
  lcm/drake_lcm.h
  lcm/test/drake_lcm_test.cc
  multibody/inverse_kinematics/global_inverse_kinematics.cc
  multibody/inverse_kinematics/global_inverse_kinematics.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#18022 [workspace] Upgrade mypy_internal to latest commit
  tools/workspace/mypy_internal/package.BUILD.bazel
  tools/workspace/mypy_internal/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#18008 [install] Add lcm and autodiff support to drake_bazel_installed
  tools/install/bazel/drake.BUILD.bazel
  tools/install/bazel/repo_template.bzl
Labels: priority: low, release notes: fix

#18006 [doc] Fix description list handling for pydrake
  bindings/pydrake/systems/drawing_graphviz_example.py
  doc/_pages/documentation_instructions.md
  tools/workspace/pybind11/mkdoc_comment.py
Labels: release notes: none

#18027 [cmake] WITH_USER_foo properly sandboxes shared libraries
  CMakeLists.txt
  cmake/external/workspace/conversion.bzl
  cmake/external/workspace/fmt/BUILD.bazel.in
  cmake/external/workspace/spdlog/BUILD.bazel.in
Labels: priority: medium, release notes: fix

#18020 [pydrake] Implement __repr__ for RollPitchYaw
  bindings/pydrake/_math_extra.py
  bindings/pydrake/test/math_test.py
Labels: priority: low, component: pydrake, release notes: feature

#18018 [plant] Extend deprecation dates
  multibody/plant/multibody_plant.h
Labels: priority: low, release notes: newly deprecated

#18009 [doc] Suppress socket error messages during local preview
  doc/defs.py
Labels: priority: low, release notes: none

#18037 [pydrake/multibody] Add bindings for MassDamperSpringAnalyticalSolution
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/benchmarks_py.cc
  bindings/pydrake/multibody/test/benchmarks_test.py
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18030 Construct EvaluatorCost as a linear transformation of another evaluator
  solvers/cost.h
  solvers/test/cost_test.cc
Labels: release notes: feature

#18035 [workspace] Upgrade curl_internal to latest release curl-7_85_0
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#18021 Support end-effector velocity limits in DiffIK and integrate through kStuck
  bindings/pydrake/manipulation/planner_py.cc
  bindings/pydrake/manipulation/test/planner_test.py
  manipulation/planner/differential_inverse_kinematics.cc
  manipulation/planner/differential_inverse_kinematics.h
  manipulation/planner/differential_inverse_kinematics_integrator.cc
  manipulation/planner/differential_inverse_kinematics_integrator.h
  manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc
  manipulation/planner/test/differential_inverse_kinematics_test.cc
Labels: priority: medium, component: planning and control, release notes: feature

#17993 DeformableDriver computes dynamic data for contact solver
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/test/deformable_driver_contact_test.cc
Labels: release notes: none

#18034 [workspace] Update qdldl to latest release 0.1.6
  tools/workspace/osqp/repository.bzl
  tools/workspace/qdldl/README.md
  tools/workspace/qdldl/package.BUILD.bazel
  tools/workspace/qdldl/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#18036 [workspace] Ignore old ignition tags when checking for a new_release
  tools/workspace/new_release.py
Labels: priority: low, release notes: none

#18040 [bindings/optimization] Fix binding for solver_options in GraphOfConvexSetsOptions
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
Labels: status: single reviewer ok, release notes: fix

#18003 [parsing] Restructure parsers for format-agnostic recursion
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_composite_parse.cc
  multibody/parsing/detail_composite_parse.h
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_mujoco_parser.h
  multibody/parsing/detail_parsing_workspace.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_sdf_parser.h
  multibody/parsing/detail_select_parser.cc
  multibody/parsing/detail_select_parser.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/process_model_directives.cc
  multibody/parsing/test/detail_common_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_select_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/parser_test.cc
Labels: release notes: none

#17899 [examples/manipulation_station] Use DifferentialInverseKinematicsIntegrator
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/README.md
  examples/manipulation_station/differential_ik.py
  examples/manipulation_station/end_effector_teleop_dualshock4.py
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
Labels: priority: low, release notes: fix, component: planning and control

#17960 [wheel] Tidy up some metadata
  tools/wheel/image/setup.py
Labels: release notes: fix

#18051 [multibody] remove joint locking from reaction forces test
  multibody/plant/BUILD.bazel
  multibody/plant/test/joint_locking_test.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
Labels: status: squashing now, component: multibody plant, release notes: none

#18050 [tools] Improve release tooling for wheels
  doc/_pages/release_playbook.md
  tools/release_engineering/download_release_candidate.py
Labels: priority: high, release notes: none

#18039 [multibody] Add DoGetOnePosition and DoGetOneVelocity to ScrewJoint
  multibody/tree/screw_joint.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/test/screw_joint_test.cc
Labels: release notes: fix

#18029 [multibody] DeformableDriver computes discrete contact pairs
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/contact_properties.cc
  multibody/plant/contact_properties.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/discrete_update_manager.h
  multibody/plant/test/contact_properties_test.cc
  multibody/plant/test/deformable_driver_contact_test.cc
Labels: release notes: none

#18047 [multibody] DeformableDriver computes ContactPairKinematics
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/deformable_model_test.cc
Labels: release notes: none

#18028 October 2022 updates
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/lcm/repository.bzl
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/rules_pkg/repository.bzl
  tools/workspace/rules_python/repository.bzl
  tools/workspace/sdformat_internal/repository.bzl
Labels: status: commits are properly curated, release notes: fix

#18044 Add joint sliders and dual geometry capability to show_model
  manipulation/util/geometry_inspector.py
  manipulation/util/show_model.py
  manipulation/util/test/geometry_inspector_test.py
  manipulation/util/test/show_model_test.py
  tools/workspace/meshcat/README.md
Labels: release notes: feature

#17623 [parsing] Add model directives support to Parser
  multibody/benchmarking/homecart_global_ik.cc
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/detail_dmd_parser.h
  multibody/parsing/detail_select_parser.cc
  multibody/parsing/parser.h
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/process_model_directives.cc
  multibody/parsing/test/parser_test.cc
  multibody/parsing/test/process_model_directives_test/acrobot.dmd.yaml
Labels: release notes: feature

#18053 [doc] Add release notes v1.9.0
  doc/_pages/from_binary.md
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_pages/python_bindings.md
  doc/_pages/release_playbook.md
  doc/_pages/rosetta2.md
  doc/_release-notes/template.txt
  doc/_release-notes/v1.9.0.md
  tools/release_engineering/relnotes.py
Labels: release notes: none

#18043 [geometry/optimization] Fix multiple Vertex costs bug
  geometry/optimization/BUILD.bazel
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: fix

#18046 Refactor mosek_solver.cc
  solvers/BUILD.bazel
  solvers/defs.bzl
  solvers/mosek_solver.cc
  solvers/mosek_solver_internal.cc
  solvers/mosek_solver_internal.h
Labels: release notes: none

#18070 [pydrake/systems] Add binding for State.get_abstract_state(index)
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/custom_test.py
Labels: priority: low, status: single reviewer ok, component: pydrake, release notes: feature

#18072 [pydrake] Add bindings for PortSwitch and Value instantiations for TypeSafeIndex
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/type_safe_index_pybind_test.cc
  bindings/pydrake/common/type_safe_index_pybind.h
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/port_switch.h
Labels: priority: medium, component: pydrake, release notes: feature

#18073 [manipulation/planner] Add optional use_robot_state port to Diff IK Integrator
  manipulation/planner/differential_inverse_kinematics_integrator.cc
  manipulation/planner/differential_inverse_kinematics_integrator.h
  manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc
Labels: priority: medium, component: planning and control, release notes: feature

#18074 Install .pyi files
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/stubgen.bzl
  bindings/pydrake/test/all_install_test.py
  bindings/pydrake/test/pyi_sanity_test.py
  bindings/pydrake/test/stubgen_test.py
  tools/wheel/image/provision-python.sh
  tools/wheel/image/setup.py
  tools/wheel/test/test-wheel.sh
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18081 [pydrake] Move import-error handling out of pydrake.all
  bindings/pydrake/systems/all.py
  bindings/pydrake/systems/drawing.py
Labels: priority: low, status: single reviewer ok, release notes: fix

#18068 Switch EventData from abstract to std::variant
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  systems/analysis/simulator.cc
  systems/framework/diagram.cc
  systems/framework/event.h
  systems/framework/leaf_system.cc
  systems/framework/test/event_test.cc
Labels: type: cleanup, release notes: breaking change

#18066 [hardware_sim] Add python flavor of the example
  bindings/pydrake/manipulation/__init__.py
  bindings/pydrake/manipulation/test/util_test.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/README.md
  examples/hardware_sim/hardware_sim.cc
  examples/hardware_sim/hardware_sim.py
  examples/hardware_sim/scenario.h
  examples/hardware_sim/test/hardware_sim_py_test.py
Labels: release notes: feature

#18090 [systems/lcm] Factor out magical lcm_buses lookup for reuse
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_buses.cc
  systems/lcm/lcm_buses.h
  systems/lcm/lcm_config_functions.cc
  systems/lcm/lcm_config_functions.h
  systems/lcm/test/lcm_config_functions_test.cc
  visualization/BUILD.bazel
  visualization/test/visualization_config_functions_test.cc
  visualization/visualization_config_functions.cc
Labels: priority: high, release notes: feature

#18078 [framework] Add more by-name sugar to Diagram and DiagramBuilder
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  common/pointer_cast.h
  common/test/pointer_cast_test.cc
  systems/framework/BUILD.bazel
  systems/framework/diagram.cc
  systems/framework/diagram.h
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
  systems/framework/test/diagram_builder_test.cc
  systems/framework/test/diagram_test.cc
  visualization/test/visualization_config_functions_test.cc
  visualization/visualization_config_functions.cc
Labels: priority: high, release notes: feature

#18092 Minor clarifications to the Notation Basics page
  multibody/multibody_doxygen.h
Labels: priority: low, type: documentation, status: single reviewer ok, release notes: none, component: tutorials

#18049 Screwjoint PR.
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: squashing now, release notes: feature

#18079 [geometry/render_gltf_client] Add integration test for RPC pipeline
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/test/integration_test.py
Labels: release notes: none

#18104 Fix CI failure by disabling a test
  geometry/render_gltf_client/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok, release notes: none

#18069 [sensors] Add lcm_bus name to CameraConfig
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  examples/hardware_sim/hardware_sim.cc
  examples/hardware_sim/hardware_sim.py
  examples/hardware_sim/test/hardware_sim_py_test.py
  examples/hardware_sim/test/test_scenarios.yaml
  systems/sensors/BUILD.bazel
  systems/sensors/camera_config.h
  systems/sensors/camera_config_functions.cc
  systems/sensors/camera_config_functions.h
  systems/sensors/test/camera_config_functions_test.cc
  visualization/visualization_config.h
Labels: priority: medium, release notes: newly deprecated, release notes: feature

#18085 parse affine expressions in Mosek
  solvers/BUILD.bazel
  solvers/defs.bzl
  solvers/mosek_solver_internal.cc
  solvers/mosek_solver_internal.h
  solvers/test/mosek_solver_internal_test.cc
Labels: status: squashing now, release notes: none

#18087 [meshcat] Support keycodes in JointSliders
  bindings/pydrake/multibody/meshcat_py.cc
  bindings/pydrake/multibody/test/meshcat_test.py
  multibody/meshcat/joint_sliders.cc
  multibody/meshcat/joint_sliders.h
  multibody/meshcat/test/joint_sliders_test.cc
Labels: priority: medium, component: geometry illustration, release notes: feature

#18075 [tools] Add push_release script to drake
  tools/release_engineering/dev/push_release
Labels: status: single reviewer ok, release notes: none

#18111 [multibody] Fix missing newline in discrete solver error message
  multibody/plant/multibody_plant.cc
Labels: status: single reviewer ok, release notes: none

#18108 [pydrake] Bind all model directives
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
Labels: priority: high, status: single reviewer ok, release notes: feature

#18115 [pydrake] Add type canonicalization for all unsigned ints
  bindings/pydrake/common/cpp_param.py
  bindings/pydrake/common/cpp_param_pybind.cc
  bindings/pydrake/common/test/cpp_param_pybind_test.cc
  bindings/pydrake/common/test/cpp_param_test.py
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18112 py multibody math: Add repr() for spatial vectors
  bindings/pydrake/_math_extra.py
  bindings/pydrake/math_py.cc
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/_math_extra.py
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
Labels: release notes: feature

#18107 Fix installation of symlinks
  tools/install/BUILD.bazel
  tools/install/installer.py
  tools/install/test/installer_test.py
Labels: status: single reviewer ok, release notes: fix

#18120 [geometry] Clean up AssignAllRoles for registering geometry
  geometry/geometry_state.cc
  geometry/geometry_state.h
Labels: status: single reviewer ok, release notes: none

#18116 Re-enable render server integration test
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/test/integration_test.py
  geometry/render_gltf_client/test/server_demo.py
Labels: status: single reviewer ok, release notes: none

#18117 [pydrake] Use Python's typing for generic types
  bindings/pydrake/common/cpp_param.py
  bindings/pydrake/common/test/cpp_param_test.py
Labels: priority: medium, release notes: feature

#18110 [parsing] Add Parser::AddModelsFromString
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/test/iris_in_configuration_space_test.cc
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/test/parser_test.cc
  multibody/plant/test/multibody_plant_query_object_connect_test.cc
Labels: priority: low, release notes: newly deprecated, release notes: feature

#18067 [multibody] DeformableDriver uses contact solver results
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/sap_contact_problem.h
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/deformable_model.h
  multibody/plant/discrete_update_manager.h
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/deformable_driver_contact_test.cc
  multibody/plant/test/deformable_driver_multiplexer_test.cc
  multibody/plant/test/deformable_driver_test.cc
  multibody/plant/test/sap_driver_test.cc
Labels: release notes: none

#18019 ScrewJoint: accept axis unit vector in constructor
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/tree/prismatic_joint.cc
  multibody/tree/prismatic_joint.h
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_joint.h
  multibody/tree/revolute_mobilizer.h
  multibody/tree/screw_joint.cc
  multibody/tree/screw_joint.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/test/screw_mobilizer_test.cc
Labels: type: bug, status: squashing now, component: multibody plant, release notes: fix, release notes: feature

#18056 Refactor wheel tests into individual tests
  tools/wheel/macos/provision-test-python.sh
  tools/wheel/macos/test-wheel.sh
  tools/wheel/test/install-wheel.sh
  tools/wheel/test/test-wheel.sh
  tools/wheel/test/tests/pyi-install-test.py
  tools/wheel/test/tests/sanity-test.py
  tools/wheel/test/tests/size-test.py
  tools/wheel/wheel_builder/common.py
  tools/wheel/wheel_builder/linux.py
  tools/wheel/wheel_builder/macos.py
Labels: release notes: none

#18101 Move Joint::type_name() to their source files
  multibody/tree/ball_rpy_joint.cc
  multibody/tree/ball_rpy_joint.h
  multibody/tree/planar_joint.cc
  multibody/tree/planar_joint.h
  multibody/tree/prismatic_joint.cc
  multibody/tree/prismatic_joint.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_joint.h
  multibody/tree/screw_joint.cc
  multibody/tree/screw_joint.h
  multibody/tree/universal_joint.cc
  multibody/tree/universal_joint.h
  multibody/tree/weld_joint.cc
  multibody/tree/weld_joint.h
Labels: release notes: none

#18131 [render_gltf_client] Weaken test threshold (for macOS arm64)
  geometry/render_gltf_client/test/integration_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#18122 Deprecate Python default parameters for ScrewJoint
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/tree/screw_joint.h
Labels: status: squashing now, status: single reviewer ok, component: multibody plant, release notes: newly deprecated

#18132 [workspace] Upgrade meshcat to latest commit
  tools/workspace/meshcat/README.md
  tools/workspace/meshcat/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#18124 [solvers] Gurobi options are handled more gracefully
  solvers/gurobi_solver.cc
  solvers/test/gurobi_solver_test.cc
Labels: priority: low, release notes: fix

#18125 [doc] Correct link names and minor edits
  doc/_pages/apt.md
  doc/_pages/bazel.md
  doc/_pages/code_review_checklist.md
  doc/_pages/code_style_tools.md
  doc/_pages/developers.md
  doc/_pages/directory_structure.md
  doc/_pages/docker.md
  doc/_pages/doxygen_instructions.md
  doc/_pages/from_binary.md
  doc/_pages/from_source.md
  doc/_pages/getting_help.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_pages/reviewable.md
  doc/_pages/sphinx_instructions.md
  doc/_pages/stable.md
  doc/_pages/sublime_text.md
Labels: status: single reviewer ok, release notes: none

#18130 [workspace] Upgrade sdformat_internal to 13.1.0
  multibody/parsing/test/detail_sdf_geometry_test.cc
  tools/workspace/sdformat_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#18100 [meshcat] Add a binding/doc/test for SetTriangleColorMesh
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/test/geometry_visualizers_test.py
  geometry/meshcat.h
  geometry/test/meshcat_manual_test.cc
Labels: priority: medium, component: geometry illustration, release notes: feature

#18143 [doc] Jenkins Mac jobs have been renamed
  doc/_pages/code_review_checklist.md
  doc/_pages/jenkins.md
  doc/_pages/release_playbook.md
Labels: status: single reviewer ok, release notes: none

#18142 [doc] Jenkins jobs have been renamed from M1 to ARM
  doc/_pages/release_playbook.md
Labels: status: single reviewer ok, release notes: none

#18144 [tools] Fully evict pydrake from drake_visualizer
  tools/BUILD.bazel
  tools/workspace/drake_visualizer/BUILD.bazel
  tools/workspace/drake_visualizer/drake_visualizer_bazel.py
  tools/workspace/drake_visualizer/stub/pydrake/__init__.py
  tools/workspace/drake_visualizer/use_drake_lcmtypes.patch
Labels: priority: medium, release notes: fix

#18109 [pydrake] Bind dataclass-like schemas for serializable structs
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/serialize_pybind.h
  bindings/pydrake/common/test/serialize_import_failure_test.py
  bindings/pydrake/common/test/serialize_pybind_test.py
  bindings/pydrake/common/test/serialize_test_bar_py.cc
  bindings/pydrake/common/test/serialize_test_foo_py.cc
  bindings/pydrake/common/test/serialize_test_foo_py.h
  bindings/pydrake/common/test/serialize_test_util_py.cc
  bindings/pydrake/systems/sensors_py.cc
Labels: priority: medium, release notes: feature

#18138 Move multibody/dev/c_iris to multibody/rational
  multibody/dev/c_iris/rational_forward_kinematics_internal.cc
  multibody/dev/c_iris/rational_forward_kinematics_internal.h
  multibody/dev/c_iris/test/rational_forward_kinematics_internal_test.cc
  multibody/rational/BUILD.bazel
  multibody/rational/rational_forward_kinematics_internal.cc
  multibody/rational/rational_forward_kinematics_internal.h
  multibody/rational/test/rational_forward_kinematics_internal_test.cc
  multibody/rational/test/rational_forward_kinematics_test_utilities.cc
  multibody/rational/test/rational_forward_kinematics_test_utilities.h
  tools/install/libdrake/build_components.bzl
Labels: status: single reviewer ok, release notes: none

#18146 [plant] Reduce symbolic test sensitivity to implementation details
  multibody/plant/test/multibody_plant_symbolic_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#18137 Refactor show_model into a future library class
  manipulation/util/BUILD.bazel
  manipulation/util/show_model.py
  manipulation/util/test/show_model_test.py
Labels: release notes: none

#18114 Add affine cone constraint in Mosek.
  solvers/mosek_solver.cc
  solvers/mosek_solver_internal.cc
  solvers/mosek_solver_internal.h
  solvers/test/mosek_solver_internal_test.cc
Labels: release notes: feature

#18141 [pydrake] Revert "Don't load native code upon 'import pydrake'"
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
  bindings/pydrake/common/__init__.py
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/manipulation/__init__.py
  bindings/pydrake/multibody/__init__.py
  bindings/pydrake/systems/__init__.py
  bindings/pydrake/test/all_each_import_test.py
  bindings/pydrake/test/minimal_import_test.py
Labels: priority: medium, release notes: fix

#18105 [multibody] Add deformable integration test
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_driver.h
  multibody/plant/test/deformable_integration_test.cc
Labels: release notes: none

#18149 Add multibody::world_frame_index() getter
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/frame.h
  multibody/tree/multibody_tree_indexes.h
  multibody/tree/test/multibody_tree_indexes_test.cc
  multibody/tree/test/tree_from_mobilizers_test.cc
Labels: release notes: fix

#18155 [parsing] Fix a deprecation typo
  multibody/parsing/test/parser_test.cc
Labels: status: single reviewer ok, release notes: none

#18063 [geometry/optimization] Fix depth first search failure in GraphOfConvexSets rounding
  geometry/optimization/BUILD.bazel
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: single reviewer ok, release notes: fix

#18015 Improve error reporting when pydrake import fails
  bindings/pydrake/__init__.py
  doc/_pages/pip.md
  tools/wheel/.dockerignore
  tools/wheel/Dockerfile
  tools/wheel/content/INSTALLATION
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/setup.py
  tools/wheel/test/tests/hermetic/import-error-test.sh
  tools/wheel/wheel_builder/linux.py
Labels: release notes: fix

#18164 [doc] Remove externals tagging from release playbook
  doc/_pages/release_playbook.md
Labels: priority: low, status: single reviewer ok, release notes: none

#18140 [geometry/optimization] Remove requirement that CartesianProduct sets must be bounded
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/test/cartesian_product_test.cc
Labels: release notes: fix

#18127 Parse screw joints from SDFormat
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf
  tools/workspace/sdformat_internal/repository.bzl
Labels: status: squashing now, release notes: feature

#18160 [pydrake] Merge all visualization API into the top-level module
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/all.py
  bindings/pydrake/test/all_test.py
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/_plotting.py
  bindings/pydrake/visualization/_visualization_extra.py
  bindings/pydrake/visualization/all.py
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/plotting.py
  bindings/pydrake/visualization/test/meldis_test.py
  bindings/pydrake/visualization/test/plotting_test.py
  bindings/pydrake/visualization/visualization_py.cc
Labels: priority: medium, status: commits are properly curated, release notes: newly deprecated

#18121 Removes experimental ContactSolver workflow from MultibodyPlant
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/test/contact_solver_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: release notes: none

#18166 [setup] Add ubuntu testonly dependency on python3-opencv
  setup/ubuntu/source_distribution/packages-focal-test-only.txt
  setup/ubuntu/source_distribution/packages-jammy-test-only.txt
Labels: priority: medium, status: single reviewer ok, release notes: none

#18169 cpp_template: Add get_module_name()
  bindings/pydrake/common/cpp_template.py
  bindings/pydrake/common/test/cpp_template_test.py
  bindings/pydrake/common/test/value_test.py
Labels: release notes: feature

#18165 [wheel] Hotfix broken auditwheel and import error test case
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/provision-python.sh
  tools/wheel/test/tests/hermetic/import-error-test.sh
Labels: priority: high, status: single reviewer ok, release notes: none

#18158 multibody: Change world body name from "WorldBody" to "world"
  multibody/parsing/test/detail_collision_filter_group_resolver_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/topology/multibody_graph.h
  multibody/tree/multibody_tree.cc
Labels: status: squashing now, release notes: fix

#18167 [manipulation] Expose utime input port for IiwaCommandSender and IiwaStatusSender
  bindings/pydrake/manipulation/kuka_iiwa_py.cc
  bindings/pydrake/manipulation/test/kuka_iiwa_test.py
  manipulation/kuka_iiwa/iiwa_command_sender.cc
  manipulation/kuka_iiwa/iiwa_command_sender.h
  manipulation/kuka_iiwa/iiwa_status_sender.cc
  manipulation/kuka_iiwa/iiwa_status_sender.h
  manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc
  manipulation/kuka_iiwa/test/iiwa_status_sender_test.cc
Labels: release notes: feature

#18163 Use patchelf from pip for wheel builds
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/patchelf.cmake
  tools/wheel/image/provision-python.sh
Labels: priority: low, status: single reviewer ok, release notes: none

#17572 Add RationalForwardKinematics class.
  common/symbolic/trigonometric_polynomial.cc
  common/symbolic/trigonometric_polynomial.h
  multibody/rational/BUILD.bazel
  multibody/rational/rational_forward_kinematics.cc
  multibody/rational/rational_forward_kinematics.h
  multibody/rational/test/rational_forward_kinematics_test.cc
Labels: release notes: feature

#18174 Improve documentation for spatial forces.
  multibody/multibody_doxygen.h
Labels: priority: low, status: single reviewer ok, release notes: none

#18173 Python bind RigidTransform::GetMaximumAbsoluteTranslationalDifference, etc.
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
  math/rigid_transform.h
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18172 [math] Add RotationMatrix::ToRollPitchYaw()
  math/rotation_matrix.h
  math/test/rotation_matrix_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18181 Correct comment typos
  bindings/pydrake/visualization/meldis.py
  geometry/meshcat_point_cloud_visualizer.h
  geometry/meshcat_visualizer.h
  geometry/meshcat_visualizer_params.h
  multibody/meshcat/contact_visualizer_params.h
  multibody/meshcat/joint_sliders.h
Labels: status: single reviewer ok, release notes: none

#18184 [solvers] Support L2NormCost in SnoptSolver and IpoptSolver.
  solvers/cost.cc
  solvers/ipopt_solver_common.cc
  solvers/mathematical_program.h
  solvers/snopt_solver.cc
  solvers/snopt_solver_common.cc
  solvers/test/ipopt_solver_test.cc
  solvers/test/optimization_examples.cc
  solvers/test/optimization_examples.h
  solvers/test/snopt_solver_test.cc
Labels: priority: medium, release notes: feature

#18183 [math] Convert between std::vector<VectorX<T>> and MatrixX<T>
  common/trajectories/BUILD.bazel
  common/trajectories/discrete_time_trajectory.cc
  common/trajectories/piecewise_polynomial.cc
  math/matrix_util.h
  math/test/matrix_util_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18171 Add ExternallyAppliedSpatialForceMultiplexer
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/BUILD.bazel
  multibody/plant/externally_applied_spatial_force_multiplexer.cc
  multibody/plant/externally_applied_spatial_force_multiplexer.h
  multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc
  systems/primitives/test/adder_test.cc
Labels: status: squashing now, release notes: feature

#18182 [pydrake] Improve BsplineTrajectory usability
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/bspline_trajectory.cc
  common/trajectories/bspline_trajectory.h
  common/trajectories/test/bspline_trajectory_test.cc
Labels: priority: medium, release notes: breaking change

#18187 [math] Python binding for RotationMatrix::ToRollPitchYaw().
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18139 [examples] Add a deformable simulation example
  examples/multibody/deformable_box/BUILD.bazel
  examples/multibody/deformable_box/README.md
  examples/multibody/deformable_box/box.vtk
  examples/multibody/deformable_box/deformable_box.cc
  examples/simple_gripper/simple_gripper.sdf
  multibody/plant/sap_driver.cc
Labels: priority: low, release notes: none

#18136 [geometry/optimization] Allow IrisInConfigurationSpace to optionally consider configuration space obstacles
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/iris.cc
  geometry/optimization/iris.h
  geometry/optimization/test/iris_in_configuration_space_test.cc
Labels: release notes: feature

#18197 Split rational_forward_kinematics_test.cc
  multibody/rational/BUILD.bazel
  multibody/rational/test/rational_forward_kinematics_test.cc
Labels: status: single reviewer ok, release notes: none

#18179 Support prismatic joint in RationalForwardKinematics.
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic/test/trigonometric_polynomial_test.cc
  common/symbolic/trigonometric_polynomial.cc
  common/symbolic/trigonometric_polynomial.h
  multibody/rational/rational_forward_kinematics.cc
  multibody/rational/rational_forward_kinematics.h
  multibody/rational/test/rational_forward_kinematics_test.cc
Labels: component: mathematical program, release notes: newly deprecated, release notes: feature

#18186 Relocate helper methods for slicing and indexing
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/slicing_and_indexing.cc
  multibody/plant/slicing_and_indexing.h
  multibody/plant/test/slicing_and_indexing_test.cc
Labels: release notes: none

#18180 Move model viz to pydrake
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/all_test.py
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/_model_visualizer.py
  bindings/pydrake/visualization/_visualization_extra.py
  bindings/pydrake/visualization/model_visualizer.py
  bindings/pydrake/visualization/test/model_visualizer_test.py
  bindings/pydrake/visualization/visualization_py.cc
  manipulation/util/BUILD.bazel
  manipulation/util/show_model.py
  manipulation/util/test/show_model_test.py
  tools/BUILD.bazel
Labels: release notes: feature

#18199 [visualization] Avoid using webbrowser in unit test
  bindings/pydrake/visualization/test/model_visualizer_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#17597 [visualization] Add VideoWriter system
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/_video.py
  bindings/pydrake/visualization/_visualization_extra.py
  bindings/pydrake/visualization/test/video_test.py
Labels: priority: medium, release notes: feature

#18188 Implements additional helper methods to retrieve contact properties
  multibody/plant/contact_properties.cc
  multibody/plant/contact_properties.h
  multibody/plant/test/contact_properties_test.cc
Labels: release notes: none

#18207 py serialize: Add mising .Finished() for no-doc case
  bindings/pydrake/common/serialize_pybind.h
  bindings/pydrake/common/test/serialize_pybind_test.py
Labels: status: single reviewer ok, release notes: fix

#18201 Provide Python module information in drake-config.cmake
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake-config.cmake.in
  tools/install/libdrake/test/drake_python_dir_install_test.py
Labels: release notes: feature

#18210 [workspace] Don't abort for unsupported macOS versions
  tools/workspace/os.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#18211 Do not use dynamic_cast to control flow in global IK
  multibody/inverse_kinematics/global_inverse_kinematics.cc
Labels: status: single reviewer ok, release notes: none

#18214 [pydrake] Add bindings for MultibodyPlant::set_discrete_contact_solver
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18213 [meshcat] Fix PerspectiveCamera msgpack
  geometry/meshcat_types.h
  geometry/test/meshcat_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#18215 [meshcat] JointSliders::Run() returns the final positions
  bindings/pydrake/multibody/test/meshcat_test.py
  multibody/meshcat/joint_sliders.cc
  multibody/meshcat/joint_sliders.h
  multibody/meshcat/test/joint_sliders_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18185 Replace quadratic cost with affine cone constraint and linear cost.
  solvers/BUILD.bazel
  solvers/mosek_solver_internal.cc
  solvers/mosek_solver_internal.h
  solvers/test/mosek_solver_internal_test.cc
Labels: component: mathematical program, release notes: none

#18209 py plant: Bind MakeActuatorSelectorMatrix overloads
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok, release notes: feature

#18208 [parsing] Modernize parser.AddAllModelsFromFile
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  bindings/pydrake/visualization/_model_visualizer.py
  multibody/benchmarking/homecart_global_ik.cc
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/test/parser_manual_test.cc
  multibody/parsing/test/parser_test.cc
  multibody/plant/multibody_plant.h
  planning/test/robot_diagram_test.cc
Labels: release notes: feature

#18219 [symbolic] Fix SparseMatrix<Expression> data loss
  common/symbolic/expression/BUILD.bazel
  common/symbolic/expression/boxed_cell.cc
  common/symbolic/expression/test/boxed_cell_test.cc
  common/symbolic/expression/test/sparse_test.cc
Labels: priority: high, release notes: fix
