Repository RobotLocomotion/drake, pull requests merged in 2022-04, with the labels that each got.

#16891 [examples/hydroelastics] ball-plate, add case: spin the ball
  examples/hydroelastic/ball_plate/README.md
  examples/hydroelastic/ball_plate/images/ball_plate_spin_the_ball.jpg
Labels: team: dynamics, priority: medium, status: single reviewer ok, release notes: none

#16871 [doc] Add tip for profiling with google benchmark
  doc/_pages/profiling.md
Labels: type: documentation, status: single reviewer ok, release notes: none

#16870 Upgrade documentation for SpatialVector to be more consistent with its subclasses.
  multibody/math/spatial_vector.h
Labels: type: cleanup, type: documentation, team: dynamics, priority: medium, status: squashing now, component: multibody plant, release notes: none

#16883 [fem] Simplify external force/gravity calculation
  multibody/fem/fem_element.h
  multibody/fem/fem_model.h
  multibody/fem/fem_model_impl.h
  multibody/fem/test/dummy_element.h
  multibody/fem/test/fem_element_test.cc
  multibody/fem/test/fem_model_test.cc
  multibody/fem/test/volumetric_element_test.cc
  multibody/fem/volumetric_element.h
Labels: release notes: none, component: softsim fem

#16844 Upgrade SpatialMomentum documentation and keyword arguments for Python.
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
  multibody/math/spatial_acceleration.h
  multibody/math/spatial_momentum.h
  multibody/math/spatial_velocity.h
Labels: type: cleanup, type: documentation, team: dynamics, priority: medium, status: squashing now, component: multibody plant, release notes: newly deprecated

#16851 Upgrade SpatialForce documentation and keyword arguments for Python.
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
  multibody/math/spatial_force.h
Labels: type: cleanup, type: documentation, team: dynamics, priority: medium, status: squashing now, component: multibody plant, release notes: newly deprecated

#16863 Update the Jaco LCM systems
  examples/kinova_jaco_arm/BUILD.bazel
  examples/kinova_jaco_arm/jaco_controller.cc
  examples/kinova_jaco_arm/jaco_simulation.cc
  manipulation/kinova_jaco/jaco_command_receiver.cc
  manipulation/kinova_jaco/jaco_command_receiver.h
  manipulation/kinova_jaco/jaco_command_sender.cc
  manipulation/kinova_jaco/jaco_command_sender.h
  manipulation/kinova_jaco/jaco_status_receiver.cc
  manipulation/kinova_jaco/jaco_status_receiver.h
  manipulation/kinova_jaco/jaco_status_sender.cc
  manipulation/kinova_jaco/jaco_status_sender.h
  manipulation/kinova_jaco/test/jaco_command_receiver_test.cc
  manipulation/kinova_jaco/test/jaco_command_sender_test.cc
  manipulation/kinova_jaco/test/jaco_status_receiver_test.cc
  manipulation/kinova_jaco/test/jaco_status_sender_test.cc
Labels: priority: low, release notes: newly deprecated

#16881 [fem] Add VolumetricModel
  multibody/fem/BUILD.bazel
  multibody/fem/fem_element.h
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
  multibody/fem/fem_model_impl.h
  multibody/fem/test/volumetric_model_test.cc
  multibody/fem/volumetric_element.h
  multibody/fem/volumetric_model.h
Labels: release notes: none, component: softsim fem

#16905 Use reference `&` to fix errors in CI mac-monterey-clang-bazel-continuous-release
  multibody/parsing/test/diagnostic_policy_test_base.h
Labels: priority: high, configuration: mac, team: dynamics, configuration: bazel, status: single reviewer ok, component: multibody plant, release notes: none

#16906 [examples/rimless_wheel] Improve meshcat animation
  examples/rimless_wheel/rimless_wheel.cc
  examples/rimless_wheel/rimless_wheel.h
  examples/rimless_wheel/test/rimless_wheel_test.cc
Labels: type: cleanup, team: robot locomotion group, priority: medium, type: MIT 6.832, release notes: yes

#16845 Add the smooth formulation of augmented Lagrangian.
  bindings/pydrake/solvers/augmented_lagrangian_py.cc
  bindings/pydrake/solvers/test/augmented_lagrangian_test.py
  solvers/augmented_lagrangian.cc
  solvers/augmented_lagrangian.h
  solvers/test/augmented_lagrangian_test.cc
Labels: release notes: yes

#16858 Fixes documentation on the modeling of friction
  multibody/plant/contact_model_doxygen.h
Labels: type: documentation, team: dynamics, status: single reviewer ok, component: multibody plant, release notes: none

#16904 [parsing] Add diagnostic policy to AddMaterialToMaterialMap
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/test/detail_urdf_geometry_test.cc
Labels: release notes: none

#16873 Add a new frame Abar to specify the PositionConstraint bound.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/position_constraint.cc
  multibody/inverse_kinematics/position_constraint.h
  multibody/inverse_kinematics/test/position_constraint_test.cc
Labels: release notes: yes

#16892 [geometry/optimization] Expose the costs and constraints of an Edge in GraphOfConvexSets
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: yes

#16910 [parsing] Complete adding diagnostic policy in urdf_geometry
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
Labels: release notes: none

#16914 [trajectory] PiecewiseQuaternion returns Vector4 as values
  bindings/pydrake/test/trajectories_test.py
  common/trajectories/piecewise_quaternion.h
  common/trajectories/test/piecewise_quaternion_test.cc
  systems/primitives/trajectory_source.h
Labels: release notes: breaking change

#16916 meldis: Minor style adjustment to code blocks
  bindings/pydrake/visualization/meldis.py
Labels: priority: low, configuration: python, release notes: none

#16889 [fem] Add Dirichlet BC to FemModel
  multibody/fem/BUILD.bazel
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
  multibody/fem/test/fem_model_test.cc
Labels: release notes: none, component: softsim fem

#16912 [WIP] SapSolver is no longer a ContactSolver
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/sap_solver.h
  multibody/contact_solvers/sap/sap_solver_results.cc
  multibody/contact_solvers/sap/sap_solver_results.h
  multibody/contact_solvers/sap/test/sap_solver_test.cc
Labels: team: dynamics, release notes: none

#16897 Tree topology only includes tress with non-zero DOFs.
  multibody/tree/multibody_tree_topology.h
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: component: multibody plant, release notes: none

#16926 [doc] Upgrade recommended Bazel version to 5.1 on Mac
  doc/_pages/from_source.md
Labels: type: documentation, status: single reviewer ok, release notes: yes

#16876 [geometry/dev] Client-Server API Doxygen documentation
  geometry/render/dev/render_engine_gltf_client_factory.h
  geometry/render/dev/render_gltf_client_doxygen.h
  geometry/render/dev/render_server/README.md
Labels: status: single reviewer ok, release notes: none

#16928 [workspace] Modernize mosek's libcilkrts explanation
  tools/workspace/mosek/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#16925 Upgrade meshcat and meshcat_python to the latest commit
  tools/workspace/meshcat/repository.bzl
  tools/workspace/meshcat_python/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: yes

#16920 [multibody] Filter collisions within welded subgraphs
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: release notes: yes

#16921 [MathematicalProgram] Add convex quadratic constraint as rotated Lorentz cone constraint.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/create_constraint.cc
  solvers/create_constraint.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/create_constraint_test.cc
  solvers/test/mathematical_program_test.cc
Labels: release notes: yes

#16929 Remove Bionic wheel(s)
  tools/wheel/Dockerfile
  tools/wheel/build-wheels
  tools/wheel/image/packages-bionic
  tools/wheel/image/packages-focal
  tools/wheel/image/provision-base.sh
  tools/wheel/test/Dockerfile
Labels: release notes: removal of deprecated

#16934 [workspace] Add MOSEK redistribution contract to our installed docs
  tools/workspace/mosek/BUILD.bazel
  tools/workspace/mosek/drake_mosek_redistribution.txt
  tools/workspace/mosek/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: none

#16924 Fix out-of-date filename in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type: cleanup, type: documentation, team: robot locomotion group, status: single reviewer ok, release notes: none

#16896 Use std::vector instead of Eigen::Vector in ExtractAndAppendVariablesFromExpression
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic_decompose.cc
  common/symbolic_decompose.h
  common/test/symbolic_decompose_test.cc
  solvers/constraint.cc
  solvers/create_constraint.cc
Labels: release notes: yes

#16933 [pydrake] Add missing module to pydrake/solvers/all
  bindings/pydrake/solvers/all.py
  bindings/pydrake/test/all_test.py
Labels: status: single reviewer ok, release notes: none

#16936 Enforce file naming and folder structure in //geometry/render/dev
  geometry/render/dev/render_engine_gltf_client_factory.cc
  geometry/render/dev/render_gltf_client/BUILD.bazel
  geometry/render/dev/render_gltf_client/factory.cc
  geometry/render/dev/render_gltf_client/factory.h
  geometry/render/dev/render_gltf_client/internal_http_service.cc
  geometry/render/dev/render_gltf_client/internal_http_service.h
  geometry/render/dev/render_gltf_client/internal_http_service_curl.cc
  geometry/render/dev/render_gltf_client/internal_http_service_curl.h
  geometry/render/dev/render_gltf_client/internal_render_client.cc
  geometry/render/dev/render_gltf_client/internal_render_client.h
  geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.h
  geometry/render/dev/render_gltf_client/render_gltf_client_doxygen.h
  geometry/render/dev/render_gltf_client/test/4_color_texture.png
  geometry/render/dev/render_gltf_client/test/flask_import_test.py
  geometry/render/dev/render_gltf_client/test/gltf_render_server.py
  geometry/render/dev/render_gltf_client/test/gltf_render_server_backend.cc
  geometry/render/dev/render_gltf_client/test/internal_http_service_curl_test.cc
  geometry/render/dev/render_gltf_client/test/internal_http_service_test.cc
  geometry/render/dev/render_gltf_client/test/internal_render_client_test.cc
  geometry/render/dev/render_gltf_client/test/internal_render_engine_gltf_client_test.cc
  geometry/render/dev/render_gltf_client/test/internal_test_png.cc
  geometry/render/dev/render_gltf_client/test/internal_test_png.h
  geometry/render/dev/render_gltf_client/test/internal_test_tiff.cc
  geometry/render/dev/render_gltf_client/test/internal_test_tiff.h
  geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc
Labels: release notes: none

#16938 setup: Deprecate Bionic-specific option --with-kov
  doc/_pages/bazel.md
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
  tools/dynamic_analysis/kcov.sh
  tools/dynamic_analysis/kcov_tool
Labels: release notes: newly deprecated

#16931 Remove support for Ubuntu 18.04 Bionic
  CMakeLists.txt
  bindings/pydrake/pydrake_doxygen.h
  doc/_pages/apt.md
  doc/_pages/bazel.md
  doc/_pages/from_source.md
  doc/_pages/getting_help.md
  doc/_pages/installation.md
  doc/_release-notes/template.txt
  setup/BUILD.bazel
  setup/ubuntu/binary_distribution/install_prereqs.sh
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/packages-bionic-clang.txt
  setup/ubuntu/source_distribution/packages-bionic-doc-only.txt
  setup/ubuntu/source_distribution/packages-bionic-maintainer-only.txt
  setup/ubuntu/source_distribution/packages-bionic-test-only.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  tools/install/bazel/generate_installed_files_manifest.bzl
  tools/install/dockerhub/bionic/.dockerignore
  tools/install/dockerhub/bionic/Dockerfile
  tools/install/dockerhub/bionic/README.md
  tools/release_engineering/download_release_candidate.py
  tools/workspace/README.md
  tools/workspace/fmt/repository.bzl
  tools/workspace/os.bzl
  tools/workspace/python/repository.bzl
  tools/workspace/spdlog/repository.bzl
Labels: release notes: removal of deprecated

#16900 Add a benchmark on MathematicalProgram.
  solvers/benchmarking/BUILD.bazel
  solvers/benchmarking/benchmark_mathematical_program.cc
Labels: release notes: none

#16948 [setup] Add xvfb init script for deepnote
  setup/BUILD.bazel
  setup/deepnote/README.md
  setup/deepnote/install_xvfb
  setup/deepnote/xvfb
  tools/install/bazel/generate_installed_files_manifest.bzl
Labels: priority: high, release notes: yes

#16946 [workspace] Remove bionic doxygen build.
  doc/_pages/documentation_instructions.md
  tools/workspace/doxygen/Dockerfile
  tools/workspace/doxygen/build_binaries_with_docker
  tools/workspace/doxygen/repository.bzl
Labels: release notes: removal of deprecated

#16902 Add SparseAndDenseMatrix class.
  solvers/BUILD.bazel
  solvers/sparse_and_dense_matrix.cc
  solvers/sparse_and_dense_matrix.h
  solvers/test/sparse_and_dense_matrix_test.cc
Labels: release notes: none

#16915 [parsing] Plumb the last URDF error to diagnostic policy
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_tinyxml.cc
  multibody/parsing/detail_tinyxml.h
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_tinyxml_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: release notes: none

#16927 Enable MOSEK in wheel builds.
  tools/wheel/image/build-drake.sh
  tools/wheel/image/build-wheel.sh
  tools/wheel/test/test-wheel.sh
Labels: status: single reviewer ok, release notes: yes

#16945 [workspace] Disable drake-visualizer on macOS
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/install_prereqs.sh
  tools/BUILD.bazel
  tools/wheel/image/build-drake.sh
  tools/workspace/BUILD.bazel
  tools/workspace/drake_visualizer/BUILD.bazel
  tools/workspace/drake_visualizer/README.md
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py
  tools/workspace/drake_visualizer/build_mac_binaries
  tools/workspace/drake_visualizer/image/director-patches/0004-dv-mac-python-manager.patch
  tools/workspace/drake_visualizer/repository.bzl
Labels: priority: medium, release notes: removal of deprecated

#16962 [workspace] Fix "disable drake-visualizer on macOS" for Ubuntu
  tools/workspace/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok, release notes: yes

#16943 Add clang-12 on Focal, macOS
  setup/mac/source_distribution/Brewfile
  setup/ubuntu/source_distribution/packages-focal-clang.txt
  setup/ubuntu/source_distribution/packages-focal-test-only.txt
  setup/ubuntu/source_distribution/packages-focal.txt
Labels: status: single reviewer ok, release notes: yes

#16958 [multibody, dev] Refactor DeformableContactSurface and ComputeTetMeshTriMeshContact
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/deformable_contact_surface.h
  multibody/fixed_fem/dev/deformable_rigid_contact_pair.h
  multibody/fixed_fem/dev/deformable_rigid_mesh_intersection.cc
  multibody/fixed_fem/dev/deformable_rigid_mesh_intersection.h
  multibody/fixed_fem/dev/test/deformable_contact_test.cc
Labels: type: cleanup, team: dynamics, priority: medium, status: squashing now, status: single reviewer ok, release notes: none, component: softsim fem

#16959 [workspace] Remove bionic pygame, deprecate @pygame_py repository.
  examples/manipulation_station/BUILD.bazel
  tools/workspace/pygame_py/package-stub.BUILD.bazel
  tools/workspace/pygame_py/repository.bzl
Labels: status: single reviewer ok, release notes: newly deprecated, release notes: removal of deprecated

#16964 [workspace] Fix "disable drake-visualizer on macOS" for Ubuntu again
  tools/workspace/BUILD.bazel
  tools/workspace/drake_visualizer/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok, release notes: yes

#16930 [SAP] SapSolver uses SapModel
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/sap_solver.h
  multibody/contact_solvers/sap/test/sap_solver_test.cc
Labels: team: dynamics, component: multibody plant, release notes: none

#16894 LinearConstraint stores a sparse matrix A.
  bindings/pydrake/common/test_utilities/scipy_stub/scipy/sparse/__init__.py
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/BUILD.bazel
  solvers/constraint.cc
  solvers/constraint.h
  solvers/mosek_solver.cc
  solvers/osqp_solver.cc
  solvers/scs_solver.cc
  solvers/snopt_solver.cc
  solvers/test/constraint_test.cc
Labels: release notes: yes

#16965 [workspace] Update realsense comment melodic => noetic.
  tools/workspace/intel_realsense_ros/repository.bzl
Labels: release notes: none

#16967 [workspace] Remove bionic support for ros_xacro.
  tools/workspace/ros_xacro/repository.bzl
Labels: release notes: removal of deprecated

#16968 [SAP] Note on the choice of LLT vs LDLT in dense version of the solver
  multibody/contact_solvers/sap/sap_solver.cc
Labels: type: documentation, team: dynamics, status: single reviewer ok, release notes: none

#16961 [fem] Report status of Petsc solver
  multibody/fem/petsc_symmetric_block_sparse_matrix.cc
  multibody/fem/petsc_symmetric_block_sparse_matrix.h
  multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc
Labels: release notes: none, component: softsim fem

#16973 [wheel] manylinux 3.6 and 3.7 support dropped.
  tools/workspace/python/repository.bzl
Labels: release notes: yes

#16974 Revert "[fem] Report status of Petsc solver"
  multibody/fem/petsc_symmetric_block_sparse_matrix.cc
  multibody/fem/petsc_symmetric_block_sparse_matrix.h
  multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc
Labels: status: single reviewer ok, release notes: none

#16893 Create Frame::EvalSpatialVelocityInWorld() and Frame::CalcAngularVelocity().
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/tree/frame.h
Labels: team: dynamics, type: design, priority: medium, type: performance, status: squashing now, component: multibody plant, release notes: yes

#16951 [examples] Remove obsolete examples built on loop_joint
  examples/BUILD.bazel
  examples/simple_four_bar/BUILD.bazel
  examples/simple_four_bar/FourBar.sdf
  examples/simple_four_bar/FourBar.urdf
  examples/simple_four_bar/FourBar2.urdf
  examples/simple_four_bar/README.md
Labels: status: single reviewer ok, release notes: none

#16972 [workspace] Remove bionic support for drake_visualizer.
  tools/workspace/drake_visualizer/Dockerfile
  tools/workspace/drake_visualizer/build_binaries_with_docker
  tools/workspace/drake_visualizer/image/package.sh
  tools/workspace/drake_visualizer/image/prereqs
  tools/workspace/drake_visualizer/image/provision.sh
  tools/workspace/drake_visualizer/repository.bzl
Labels: release notes: removal of deprecated

#16975 [fem] Report status of Petsc solver
  multibody/fem/petsc_symmetric_block_sparse_matrix.cc
  multibody/fem/petsc_symmetric_block_sparse_matrix.h
  multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc
Labels: status: single reviewer ok, release notes: none, component: softsim fem

#16980 [common] Improve symbolic polynomial performance via is_expanded
  common/symbolic_expression_cell.cc
  common/symbolic_expression_cell.h
  common/test/symbolic_expansion_test.cc
Labels: priority: medium, release notes: yes

#16985 "Fix" install RPATH for MOSEK
  tools/install/installer.py
Labels: priority: high, release notes: yes

#16917 [fem] Add Femsolver
  multibody/fem/BUILD.bazel
  multibody/fem/fem_model.h
  multibody/fem/fem_solver.cc
  multibody/fem/fem_solver.h
  multibody/fem/test/dummy_element.h
  multibody/fem/test/fem_model_test.cc
  multibody/fem/test/fem_solver_test.cc
Labels: release notes: none, component: softsim fem

#16986 Add another SOS benchmark program.
  solvers/benchmarking/benchmark_mathematical_program.cc
Labels: release notes: none

#16983 MathematicalProgram::NewSosPolynomial takes degree=0
  solvers/mathematical_program.cc
  solvers/test/mathematical_program_test.cc
Labels: release notes: yes

#16984 Add Monomial::Evaluate() for a batch of data.
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic_monomial.cc
  common/symbolic_monomial.h
  common/test/symbolic_monomial_test.cc
Labels: release notes: yes

#16947 [geometry] Add rigid and deformable representation for proximity
  geometry/proximity/BUILD.bazel
  geometry/proximity/deformable_contact_geometries.cc
  geometry/proximity/deformable_contact_geometries.h
  geometry/proximity/test/deformable_contact_geometries_test.cc
Labels: component: geometry proximity, release notes: none

#16995 [geometry] Updates hydroelastic user guide for compliant convex feature.
  multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
Labels: team: dynamics, status: single reviewer ok, component: geometry proximity, release notes: yes

#16989 CompliantContactManager computes contact results
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/test/compliant_contact_manager_test.cc
Labels: team: dynamics, release notes: none

#16939 [doc] Add release notes v1.2.0
  doc/_pages/apt.md
  doc/_pages/docker.md
  doc/_pages/from_binary.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_pages/release_playbook.md
  doc/_release-notes/template.txt
  doc/_release-notes/v1.0.0.md
  doc/_release-notes/v1.1.0.md
  doc/_release-notes/v1.2.0.md
Labels: status: single reviewer ok, release notes: none

#16991 Fix install RPATH mangling
  tools/install/installer.py
Labels: release notes: none

#17005 [doc] Remove broken cloudfront stylesheet links
  doc/doxygen_cxx/doxygen_extra.css
  doc/pydrake/_static/css/custom.css
Labels: priority: low, status: single reviewer ok, release notes: none

#16977 Small improvement to Frame class documentation.
  multibody/tree/frame.h
Labels: type: documentation, team: dynamics, priority: medium, status: single reviewer ok, component: multibody plant, release notes: none

#16957 [doc] Move macOS profiling instructions
  doc/_pages/bazel.md
  doc/_pages/profiling.md
Labels: priority: low, status: single reviewer ok, release notes: none

#17008 [meshcat] Add python bindings for Meshcat::SetCamera
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/test/geometry_visualizers_test.py
  geometry/meshcat.h
Labels: status: single reviewer ok, release notes: yes

#17004 [SAP] Fixes bug with velocity permutations in SapModel
  multibody/contact_solvers/sap/partial_permutation.cc
  multibody/contact_solvers/sap/partial_permutation.h
  multibody/contact_solvers/sap/sap_model.cc
  multibody/contact_solvers/sap/test/partial_permutation_test.cc
  multibody/contact_solvers/sap/test/sap_model_test.cc
Labels: type: bug, team: dynamics, release notes: none

#16998 [geometry] Add MakeDeformableMesh
  geometry/BUILD.bazel
  geometry/make_mesh_for_deformable.cc
  geometry/make_mesh_for_deformable.h
  geometry/test/make_mesh_for_deformable_test.cc
Labels: component: geometry general, release notes: none

#16953 [parsing] Warn about unsupported URDF features
  examples/atlas/urdf/atlas_convex_hull.urdf
  examples/pr2/BUILD.bazel
  examples/pr2/README.md
  examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf
  manipulation/models/franka_description/BUILD.bazel
  manipulation/models/franka_description/README.md
  manipulation/models/franka_description/urdf/hand.urdf
  manipulation/models/franka_description/urdf/panda_arm.urdf
  manipulation/models/franka_description/urdf/panda_arm_hand.urdf
  manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf
  manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf
  manipulation/models/jaco_description/BUILD.bazel
  manipulation/models/jaco_description/README.md
  manipulation/models/jaco_description/urdf/j2n6s300.urdf
  manipulation/models/jaco_description/urdf/j2s7s300.urdf
  manipulation/models/jaco_description/urdf/j2s7s300_arm.urdf
  manipulation/models/jaco_description/urdf/j2s7s300_arm_sphere_collision.urdf
  manipulation/models/jaco_description/urdf/j2s7s300_sphere_collision.urdf
  multibody/parsing/detail_tinyxml2_diagnostic.cc
  multibody/parsing/detail_tinyxml2_diagnostic.h
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/test/detail_tinyxml2_diagnostic_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/plant/test/atlas_with_fixed_joints.urdf
Labels: release notes: yes

#17001 [doc] Fix some nits in the release playbook
  doc/_pages/release_playbook.md
Labels: priority: low, status: single reviewer ok, release notes: none

#17011 Speedup MathematicalProgram::NewFreePolynomial.
  common/symbolic_polynomial.cc
  solvers/mathematical_program.cc
Labels: release notes: yes

#17012 [doc] Add new pydrake header, footer, and style customizations
  doc/BUILD.bazel
  doc/defs.py
  doc/pydrake/BUILD.bazel
  doc/pydrake/_static/css/custom.css
  doc/pydrake/footer.html
  doc/pydrake/layout.html
Labels: priority: medium, status: single reviewer ok, release notes: none

#16960 [doc] Add new Doxygen header, footer, and style customizations
  doc/doxygen_cxx/doxygen_extra.css
  doc/doxygen_cxx/footer.html
  doc/doxygen_cxx/header.html.patch
Labels: status: single reviewer ok, release notes: none

#17013 [common] Speed up SoS using negation instead of subtraction
  common/symbolic_expression.h
  common/symbolic_generic_polynomial.cc
  common/symbolic_polynomial.cc
Labels: release notes: yes

#17006 ScsSolver uses get_sparse_A from linear matrix.
  solvers/scs_solver.cc
Labels: release notes: none

#17003 Fix gradient computation in SamePointConstraint.
  geometry/optimization/iris.cc
Labels: release notes: none

#17015 [tools] Suppress pybind11 clang warning globally (not via pragmas)
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/symbolic_py.cc
  tools/skylark/pybind.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#17029 [systems] Controllability and observability for discrete-time systems
  systems/primitives/linear_system.cc
  systems/primitives/test/linear_system_test.cc
Labels: release notes: yes

#16996 Refactor wheel build script(s)
  tools/wheel/BUILD.bazel
  tools/wheel/README.rst
  tools/wheel/__init__.py
  tools/wheel/wheel_builder/common.py
  tools/wheel/wheel_builder/linux.py
  tools/wheel/wheel_builder/main.py
Labels: release notes: none

#17017 [parsing] Add API to set strict parsing
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/test/parser_test.cc
Labels: release notes: yes

#17010 [doc] Add instructions for tutorials deployment
  doc/_pages/release_playbook.md
Labels: priority: low, status: single reviewer ok, release notes: none

#17025 [examples/quadrotor] hotfix: fix segfault when QuadrotorPlant input port was not connected
  examples/quadrotor/BUILD.bazel
  examples/quadrotor/quadrotor_plant.cc
  examples/quadrotor/quadrotor_plant.h
  examples/quadrotor/test/quadrotor_plant_test.cc
Labels: type: bug, team: robot locomotion group, priority: medium, status: single reviewer ok, release notes: breaking change

#16950 [geometry] Move HttpService to //geometry/render_gltf_client
  geometry/render/dev/render_gltf_client/BUILD.bazel
  geometry/render/dev/render_gltf_client/factory.h
  geometry/render/dev/render_gltf_client/internal_http_service.cc
  geometry/render/dev/render_gltf_client/internal_http_service_curl.cc
  geometry/render/dev/render_gltf_client/internal_http_service_curl.h
  geometry/render/dev/render_gltf_client/internal_render_client.cc
  geometry/render/dev/render_gltf_client/internal_render_client.h
  geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render/dev/render_gltf_client/render_gltf_client_params.cc
  geometry/render/dev/render_gltf_client/render_gltf_client_params.h
  geometry/render/dev/render_gltf_client/test/internal_http_service_curl_test.cc
  geometry/render/dev/render_gltf_client/test/internal_http_service_test.cc
  geometry/render/dev/render_gltf_client/test/internal_render_client_test.cc
  geometry/render/dev/render_gltf_client/test/internal_render_engine_gltf_client_test.cc
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_http_service.cc
  geometry/render_gltf_client/internal_http_service.h
  geometry/render_gltf_client/test/internal_http_service_test.cc
  tools/install/libdrake/build_components.bzl
Labels: release notes: none

#17032 Add implicit dynamics binding
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
Labels: release notes: yes

#17042 [pydrake] Bind MbP::GetRigidBodyByName()
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok, release notes: yes

#17041 [tools] Remove various stray bits of Ubuntu 18.04 (Bionic) support
  doc/_pages/pip.md
  doc/images/drake-dragon.README.txt
  examples/manipulation_station/BUILD.bazel
  tools/workspace/nlopt/package-ubuntu-18.04.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#17034 [solvers] Ipopt supports kPrintFileName
  solvers/BUILD.bazel
  solvers/ipopt_solver.cc
  solvers/test/ipopt_solver_test.cc
Labels: priority: low, release notes: yes

#17016 Include additional diagonal inertias in forward dynamics
  multibody/plant/test/multibody_plant_reflected_inertia_test.cc
  multibody/tree/body_node.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: team: dynamics, component: multibody plant, release notes: none

#17019 Joint API to retrieve viscous damping.
  multibody/tree/ball_rpy_joint.h
  multibody/tree/joint.h
  multibody/tree/planar_joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/revolute_joint.h
  multibody/tree/screw_joint.h
  multibody/tree/test/ball_rpy_joint_test.cc
  multibody/tree/test/planar_joint_test.cc
  multibody/tree/test/prismatic_joint_test.cc
  multibody/tree/test/revolute_joint_test.cc
  multibody/tree/test/screw_joint_test.cc
  multibody/tree/test/universal_joint_test.cc
  multibody/tree/test/weld_joint_test.cc
  multibody/tree/universal_joint.h
Labels: component: multibody plant, release notes: yes

#17021 Determine if a polynomial is even or odd.
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic_polynomial.cc
  common/symbolic_polynomial.h
  common/test/symbolic_polynomial_test.cc
Labels: release notes: yes

#17033 ClpSolver uses sparse matrix in linear constraint.
  solvers/clp_solver.cc
Labels: release notes: none

#17043 Add Bazel config for compiler selection
  doc/_pages/bazel.md
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
  tools/bazel.rc
  tools/macos.bazelrc
  tools/ubuntu-focal.bazelrc
Labels: release notes: yes

#17048 SupernodalSolver bug fix
  multibody/contact_solvers/supernodal_solver.cc
  multibody/contact_solvers/test/supernodal_solver_test.cc
Labels: type: bug, team: dynamics, status: squashing now, release notes: none

#17049 [atlas] Revert to a larger default time step
  examples/atlas/atlas_run_dynamics.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#17038 [multibody] Replace M.ldlt() in Tamsi no-contact path with LinearSolver
  multibody/plant/BUILD.bazel
  multibody/plant/tamsi_solver.cc
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
Labels: type: bug, priority: high, team: dynamics, component: multibody plant, release notes: yes

#17035 [tutorials] Avoid kPrintToConsole in online notebooks
  tutorials/debug_mathematical_program.ipynb
Labels: priority: low, release notes: none

#17047 [parsing] Route package deprecations into the diagnostic channel
  bindings/pydrake/multibody/parsing_py.cc
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/package_map.cc
  multibody/parsing/package_map.h
  multibody/parsing/test/detail_path_utils_test.cc
  multibody/parsing/test/package_map_test.cc
Labels: release notes: yes

#17027 [multibody] implements a Wing class to provide basic aerodynamics
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/BUILD.bazel
  multibody/plant/test/wing_test.cc
  multibody/plant/wing.cc
  multibody/plant/wing.h
Labels: priority: high, release notes: yes

#17050 Add tool to capture and report --config compiler
  tools/cc_toolchain/BUILD.bazel
  tools/cc_toolchain/print_compiler_config.sh
Labels: release notes: none

#17060 [parsing] Invalid SDFormat syntax is now an error (not warning)
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: priority: low, release notes: removal of deprecated

#16940 [SAP] Newton iteration tests
  multibody/contact_solvers/sap/test/sap_solver_test.cc
Labels: team: dynamics, release notes: none

#17064 [doc] Fix a wording defect in parsing doc
  multibody/parsing/parsing_doxygen.h
Labels: status: single reviewer ok, release notes: none

#17054 [parsing] Slightly improve joint parsing diagnostics
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: priority: low, release notes: none

#17071 [parsing] Work around test error in coverage builds (kcov 339)
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#17074 Make2NormSquaredCost should set convex flag to true.
  solvers/cost.cc
  solvers/test/cost_test.cc
Labels: status: single reviewer ok, release notes: yes
