Repository RobotLocomotion/drake, pull requests merged in 2022-09, with the labels that each got.

#17801 Fix misspelling of "Riccati"
  systems/controllers/finite_horizon_linear_quadratic_regulator.h
Labels: status: single reviewer ok

#17793 [multibody] MultibodyPlant::SetDefaultPositions
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: medium, component: multibody plant, release notes: feature

#17811 [multibody/parsing] Add optional X_PC to model directives AddWeld
  multibody/parsing/model_directives.h
  multibody/parsing/process_model_directives.cc
  multibody/parsing/test/model_directives_test.cc
  multibody/parsing/test/process_model_directives_test.cc
  multibody/parsing/test/process_model_directives_test/inject_frames.dmd.yaml
Labels: priority: medium, component: multibody parsing, release notes: feature

#17770 New function MultibodyPlant::CalcSpatialInertia()
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_momentum_energy_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: priority: medium, status: squashing now, component: multibody plant, release notes: feature

#17810 [multibody/parsing] LoadModelDirectivesFromString
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  multibody/parsing/process_model_directives.cc
  multibody/parsing/process_model_directives.h
  multibody/parsing/test/process_model_directives_test.cc
Labels: priority: medium, component: multibody parsing, release notes: feature

#17812 [geometry] Remove deprecated code 2022-09
  geometry/render/BUILD.bazel
  geometry/render/gl_renderer/BUILD.bazel
  geometry/render/gl_renderer/render_engine_gl_factory.h
  geometry/render/gl_renderer/render_engine_gl_params.h
  geometry/render/stub/render_engine_vtk.h
  geometry/render/stub/render_engine_vtk_base.h
  geometry/render/stub/render_engine_vtk_factory.h
  geometry/render/stub/vtk_util.h
  geometry/render/test/deprecation_test.cc
  geometry/render_gl/BUILD.bazel
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/factory.h
  geometry/render_vtk/render_engine_vtk_params.h
  systems/sensors/BUILD.bazel
  tools/install/libdrake/build_components.bzl
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#17813 [misc] Remove deprecated code 2022-09
  CMakeLists.txt
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/module_test.py
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py_csdp.cc
  bindings/pydrake/solvers/test/augmented_lagrangian_test.py
  bindings/pydrake/solvers/test/csdp_solver_test.py
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/meshcat_visualizer.py
  bindings/pydrake/systems/test/meshcat_visualizer_test.py
  bindings/pydrake/test/symbolic_test.py
  common/symbolic/polynomial.cc
  common/symbolic/polynomial.h
  common/symbolic/test/polynomial_test.cc
  common/yaml/BUILD.bazel
  common/yaml/test/yaml_deprecation_test.cc
  common/yaml/yaml_read_archive.h
  common/yaml/yaml_write_archive.h
  solvers/csdp_solver.cc
  solvers/csdp_solver.h
  solvers/csdp_solver_common.cc
  solvers/test/csdp_solver_test.cc
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/cc/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#17815 [hardware_sim] Move header to internal namespace
  examples/hardware_sim/hardware_sim.cc
  examples/hardware_sim/scenario.cc
  examples/hardware_sim/scenario.h
Labels: priority: low, status: single reviewer ok, release notes: none

#17797 [sensors] Add infrastructure to support applying CameraConfig
  systems/sensors/BUILD.bazel
  systems/sensors/sim_rgbd_sensor.cc
  systems/sensors/sim_rgbd_sensor.h
  systems/sensors/test/sim_rgbd_sensor_test.cc
Labels: release notes: none

#17757 [meshcat] no crash from visualizing almost-zero hydroelastic force or moment
  multibody/meshcat/BUILD.bazel
  multibody/meshcat/hydroelastic_contact_visualizer.cc
  multibody/meshcat/test/hydroelastic_contact_visualizer_test.cc
Labels: component: multibody plant, release notes: fix

#17818 GetInfeasibleConstraints: Only return infeasible constraint once
  solvers/mathematical_program_result.cc
  solvers/test/mathematical_program_result_test.cc
Labels: release notes: fix

#17825 [pydrake/common] Bind default constructor for TypeSafeIndex
  bindings/pydrake/common/test/type_safe_index_pybind_test.cc
  bindings/pydrake/common/type_safe_index_pybind.h
Labels: priority: medium, status: single reviewer ok, component: pydrake, release notes: feature

#17835 Add unnamed namespace to prevent kcov issue #339
  systems/primitives/test/linear_transform_density_test.cc
Labels: status: single reviewer ok, component: build system, release notes: none

#17841 Fix bazel visibility on //geometry/render
  geometry/render/BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#17804 [render_vtk] Restore most macOS m1 tests
  geometry/render_vtk/BUILD.bazel
Labels: release notes: none

#17822 [parsing] Remove unnecessary optional
  multibody/parsing/model_directives.h
  multibody/parsing/process_model_directives.cc
  multibody/parsing/test/model_directives_test.cc
Labels: priority: medium, release notes: none

#17823 [config] Update examples to use AddDefaultVisualization where convenient
  bindings/pydrake/examples/multibody/BUILD.bazel
  bindings/pydrake/examples/multibody/cart_pole_passive_simulation.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/drawing_graphviz_example.py
  examples/allegro_hand/BUILD.bazel
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/atlas/BUILD.bazel
  examples/atlas/atlas_run_dynamics.cc
  examples/hydroelastic/ball_plate/BUILD.bazel
  examples/hydroelastic/ball_plate/ball_plate_run_dynamics.cc
  examples/hydroelastic/python_ball_paddle/contact_sim_demo.py
  examples/multibody/acrobot/BUILD.bazel
  examples/multibody/acrobot/run_lqr.cc
  examples/multibody/cart_pole/BUILD.bazel
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  examples/multibody/cylinder_with_multicontact/BUILD.bazel
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
  examples/multibody/four_bar/BUILD.bazel
  examples/multibody/four_bar/passive_simulation.cc
  examples/multibody/strandbeest/BUILD.bazel
  examples/multibody/strandbeest/run_with_motor.cc
  examples/quadrotor/BUILD.bazel
  examples/quadrotor/run_quadrotor_dynamics.cc
  examples/simple_gripper/BUILD.bazel
  examples/simple_gripper/simple_gripper.cc
Labels: release notes: none

#17826 [geometry] Improve ComputeSignedDistancePairClosestPoints feedback
  bindings/pydrake/test/geometry_scene_graph_test.py
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/query_object.h
  geometry/test/geometry_state_test.cc
Labels: release notes: none

#17805 [doc] Update supported Xcode / python versions to match CI
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  tools/workspace/python/repository.bzl
Labels: type: documentation, release notes: none

#17834 [common] Switch to std::filesystem
  common/BUILD.bazel
  common/filesystem.cc
  common/filesystem.h
  tools/workspace/BUILD.bazel
  tools/workspace/ghc_filesystem/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated, release notes: fix

#17397 [geometry/optimization] Enable preprocessing GCS before solving ShortestPath
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: feature

#17790 Add RigidTransform multiply by Vector4d
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
  math/rigid_transform.cc
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
Labels: release notes: feature

#17830 [workspace] Build tinyxml2 from source
  BUILD.bazel
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_common.h
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_tinyxml.h
  multibody/parsing/detail_tinyxml2_diagnostic.h
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/package_map.cc
  setup/mac/binary_distribution/Brewfile
  tools/install/cmake/BUILD.bazel
  tools/install/cmake/FindTinyXML2.cmake
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake-config.cmake
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/tinyxml2.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/sdformat_internal/package.BUILD.bazel
  tools/workspace/tinyxml2/repository.bzl
  tools/workspace/tinyxml2_internal/BUILD.bazel
  tools/workspace/tinyxml2_internal/package.BUILD.bazel
  tools/workspace/tinyxml2_internal/patches/namespace.patch
  tools/workspace/tinyxml2_internal/repository.bzl
Labels: priority: low, release notes: newly deprecated, release notes: fix

#17755 [workspace] Add private curl build from source
  geometry/render_gltf_client/BUILD.bazel
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/install_prereqs.sh
  tools/workspace/BUILD.bazel
  tools/workspace/cmake_configure_file.py
  tools/workspace/curl_internal/BUILD.bazel
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/package.BUILD.bazel
  tools/workspace/curl_internal/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/libcurl/repository.bzl
Labels: priority: low, release notes: newly deprecated, release notes: fix

#17842 [doc] Add build OOM troubleshooting
  doc/_pages/from_source.md
  doc/_pages/troubleshooting.md
Labels: priority: low, release notes: none

#17827 [sensors] Add ApplyCameraConfig function
  systems/sensors/BUILD.bazel
  systems/sensors/camera_config.h
  systems/sensors/camera_config_functions.cc
  systems/sensors/camera_config_functions.h
  systems/sensors/test/camera_config_functions_test.cc
Labels: release notes: feature

#17817 [geometry] Add scaling parameter for ReadVtkToVolumeMesh()
  geometry/proximity/BUILD.bazel
  geometry/proximity/test/vtk_to_volume_mesh_test.cc
  geometry/proximity/vtk_to_volume_mesh.cc
  geometry/proximity/vtk_to_volume_mesh.h
Labels: component: geometry proximity, release notes: none

#17490 [workspace] Upgrade to Mosek 10
  doc/_pages/bazel.md
  solvers/mathematical_program_result.h
  solvers/mosek_solver.cc
  solvers/mosek_solver.h
  solvers/test/linear_program_examples.h
  solvers/test/mosek_solver_test.cc
  solvers/test/semidefinite_program_examples.h
  tools/dynamic_analysis/tsan.supp
  tools/install/bazel/drake.BUILD.bazel
  tools/wheel/image/build-wheel.sh
  tools/workspace/mosek/BUILD.bazel
  tools/workspace/mosek/LICENSE.third_party
  tools/workspace/mosek/LICENSE_CilkPlus
  tools/workspace/mosek/repository.bzl
Labels: release notes: feature

#17843 [doc] Use linux wheel staging in release playbook
  doc/_pages/release_playbook.md
Labels: status: single reviewer ok, release notes: none

#17855 [geometry/optimization] Turn off preprocessing in all tests of GraphOfConvexSets except preprocessing tests
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: single reviewer ok, release notes: none

#17838 [manipulation/models] Fix colors on kinova jaco models
  manipulation/models/jaco_description/LICENSE.TXT
  manipulation/models/jaco_description/urdf/j2n6s300.urdf
  manipulation/models/jaco_description/urdf/j2s7s300.urdf
  manipulation/models/jaco_description/urdf/j2s7s300_arm.urdf
  manipulation/models/jaco_description/urdf/j2s7s300_arm_sphere_collision.urdf
  manipulation/models/jaco_description/urdf/j2s7s300_hand.urdf
  manipulation/models/jaco_description/urdf/j2s7s300_hand_sphere_collision.urdf
  manipulation/models/jaco_description/urdf/j2s7s300_sphere_collision.urdf
  manipulation/util/BUILD.bazel
Labels: priority: medium, component: geometry illustration, release notes: fix

#17854 [sensors] Validate CameraConfig substructs only as part of the whole
  systems/sensors/camera_config.cc
  systems/sensors/camera_config.h
  systems/sensors/test/camera_config_test.cc
Labels: priority: medium, release notes: none

#17824 [planning] Add initialization event to DiffIK Integrator
  manipulation/planner/BUILD.bazel
  manipulation/planner/differential_inverse_kinematics_integrator.cc
  manipulation/planner/differential_inverse_kinematics_integrator.h
  manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc
  systems/framework/leaf_system.h
Labels: priority: high, component: planning and control, release notes: feature

#17846 Remove LD_LIBRARY_PATH from apt instructions and Dockerfiles
  doc/_pages/apt.md
  tools/install/dockerhub/focal/Dockerfile
  tools/install/dockerhub/focal/README.md
  tools/install/dockerhub/jammy/Dockerfile
  tools/install/dockerhub/jammy/README.md
Labels: release notes: fix

#17857 [tutorials] Update SimpleDiscreteSystem to use DeclarePeriodicUpdateEvent
  tutorials/dynamical_systems.ipynb
Labels: priority: medium, status: single reviewer ok, release notes: none, component: tutorials

#17856 [examples] Set an initial position for the hardware_sim demo
  examples/hardware_sim/example_iiwa_wsg.dmd.yaml
Labels: priority: low, status: single reviewer ok, release notes: none

#17800 [multibody] Compute bodies affected by joints
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_topology.h
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: priority: low, component: multibody plant, release notes: feature

#17829 [perception] Add PointCloud::Crop and Concatenate(vector<PointCloud>)
  bindings/pydrake/perception_py.cc
  bindings/pydrake/test/perception_test.py
  perception/point_cloud.cc
  perception/point_cloud.h
  perception/test/point_cloud_test.cc
Labels: priority: medium, component: geometry perception, release notes: feature

#17864 [examples] Reduce smoke test time for hardware_sim demo
  examples/hardware_sim/test/hardware_sim_test.py
Labels: priority: emergency, status: single reviewer ok, release notes: none

#17863 Suppress memcheck when VTK file reader compares header line with garbage
  tools/dynamic_analysis/valgrind.supp
Labels: status: single reviewer ok, release notes: none

#17852 [config] Provide bindings for CameraConfig and ApplyCameraConfig
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
Labels: release notes: feature

#17848 [meldis] Support deformable geometries
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: component: softsim fem, release notes: feature

#17867 lcmtypes: Denote ordering for quaternion vectors
  lcmtypes/lcmt_viewer_draw.lcm
  lcmtypes/lcmt_viewer_geometry_data.lcm
Labels: release notes: none

#17844 [geometry/optimization] Enable adding costs to vertices in GraphOfConvexSets
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: commits are properly curated, release notes: feature

#17816 Add PathParameterizedTrajectory
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/BUILD.bazel
  common/trajectories/path_parameterized_trajectory.cc
  common/trajectories/path_parameterized_trajectory.h
  common/trajectories/test/path_parameterized_trajectory_test.cc
Labels: release notes: feature

#17871 [install] Add better help for running just one test
  tools/install/install_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#17875 Add a link to the hydroelastic blog post to the user guide
  multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
Labels: priority: low, type: documentation, status: single reviewer ok, release notes: none, component: tutorials

#17874 [bazel] Tweak drake_py.bzl for clarity
  tools/skylark/drake_py.bzl
Labels: status: single reviewer ok, release notes: none

#17858 Add install test to verify library paths
  tools/install/BUILD.bazel
  tools/install/install.bzl
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/test/rpath_install_test.py
Labels: release notes: none

#17879 Revert "Add install test to verify library paths"
  tools/install/BUILD.bazel
  tools/install/install.bzl
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/test/rpath_install_test.py
Labels: priority: emergency, status: single reviewer ok, release notes: none

#17865 Port make_arm_controller_model() to Drake
  manipulation/util/BUILD.bazel
  manipulation/util/make_arm_controller_model.cc
  manipulation/util/make_arm_controller_model.h
  manipulation/util/test/iiwa7_wsg.dmd.yaml
  manipulation/util/test/make_arm_controller_model_test.cc
Labels: status: commits are properly curated, release notes: none

#17847 Use new CalcSpatialInertia() function in manipulation_station
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/test/manipulation_station_test.cc
Labels: type: cleanup, priority: medium, status: squashing now, component: multibody plant, release notes: none

#17868 [doc] Update macOS arm64 instructions
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/rosetta2.md
Labels: priority: low, release notes: none

#17883 [geometry/optimization] Fix GCS vertex cost test on mac arm64
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: single reviewer ok, release notes: none

#17887 Update CMakeLists.txt to remove check for X86
  CMakeLists.txt
Labels: release notes: fix

#17891 [install] Add mirrors to bazel acceptance test
  tools/install/bazel/test/drake_bazel_installed_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#17820 [geometry] Make VolumeMesh from VTK specified in geometry::Mesh
  geometry/BUILD.bazel
  geometry/proximity/BUILD.bazel
  geometry/proximity/make_mesh_from_vtk.cc
  geometry/proximity/make_mesh_from_vtk.h
  geometry/proximity/test/make_mesh_from_vtk_test.cc
  geometry/proximity/volume_mesh.h
  geometry/test/non_convex_mesh.vtk
  geometry/test/one_negative_tetrahedron.vtk
Labels: component: geometry proximity, release notes: none

#17878 [meldis] Help message in meldis_test
  bindings/pydrake/visualization/test/meldis_test.py
  common/test_utilities/drake_py_unittest_main.py
Labels: priority: low, release notes: none

#17849 Improve RigidTransform unit test
  math/test/rigid_transform_test.cc
Labels: type: cleanup, priority: medium, status: squashing now, component: multibody plant, release notes: none

#17894 [pydrake] Add missing items to pydrake.visualization.all
  bindings/pydrake/test/all_test.py
  bindings/pydrake/visualization/all.py
Labels: priority: low, status: single reviewer ok, release notes: fix

#17876 [geometry/optimization] Fix preprocessing for GraphOfConvexSets
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: fix

#17884 Use [[ instead of [ in wheel scripts
  tools/wheel/image/build-dependencies.sh
  tools/wheel/image/build-wheel.sh
  tools/wheel/macos/build-wheel.sh
  tools/wheel/macos/test-wheel.sh
  tools/wheel/test/test-wheel.sh
Labels: release notes: none

#17880 [geometry] Make deformable mesh from VTK in mesh specification.
  geometry/BUILD.bazel
  geometry/make_mesh_for_deformable.cc
  geometry/make_mesh_for_deformable.h
  geometry/test/make_mesh_for_deformable_test.cc
Labels: component: geometry proximity, release notes: none, component: softsim fem

#17557 Throw exception if distal body translates and has zero/NaN mass or rotates and has zero/NaN rotational inertia (towards issue #17081).
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_topology.h
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: type: feature request, priority: medium, status: squashing now, component: multibody plant, release notes: none, type: usability

#17872 September 2022 updates
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/bazel_skylib/repository.bzl
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/lcm/repository.bzl
  tools/workspace/optitrack_driver/repository.bzl
  tools/workspace/picosha2/repository.bzl
  tools/workspace/pycodestyle/repository.bzl
  tools/workspace/rules_python/repository.bzl
Labels: status: commits are properly curated, release notes: fix

#17859 [pydrake] Enable return-None cases for System event handlers
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
Labels: priority: medium, release notes: fix

#17895 Add tol as input argument to HPolyhedron functions
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/test/hpolyhedron_test.cc
Labels: priority: high, release notes: fix

#17901 [workspace] Fix MOSEK wheel support for archive URLs
  tools/workspace/mosek/repository.bzl
Labels: release notes: none

#17896 [cmake] Remove incorrect warning on Jammy python version
  CMakeLists.txt
Labels: release notes: fix

#17821 Add AngleBetweenVectorsCost
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/angle_between_vectors_cost.cc
  multibody/inverse_kinematics/angle_between_vectors_cost.h
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/test/angle_between_vectors_cost_test.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
Labels: release notes: feature

#17893 [hardware_sim] Adding perception cameras to hardware sim
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/example_scenarios.yaml
  examples/hardware_sim/hardware_sim.cc
  examples/hardware_sim/scenario.h
  examples/hardware_sim/test/test_scenarios.yaml
Labels: release notes: feature

#17778 Build wheels with self-built Python 3.10
  tools/wheel/BUILD.bazel
  tools/wheel/Dockerfile
  tools/wheel/image/build-python.sh
  tools/wheel/image/provision-python.sh
  tools/wheel/test/provision.sh
  tools/wheel/wheel_builder/linux.py
  tools/wheel/wheel_builder/linux_types.py
  tools/workspace/python/repository.bzl
  tools/workspace/vtk/repository.bzl
Labels: release notes: feature

#17885 [perception] Implement PointCloud::VoxelizedDownSample
  bindings/pydrake/perception_py.cc
  bindings/pydrake/test/perception_test.py
  perception/BUILD.bazel
  perception/point_cloud.cc
  perception/point_cloud.h
  perception/test/point_cloud_test.cc
Labels: priority: medium, component: geometry perception, release notes: feature

#17902 Add install test to verify library paths
  tools/install/BUILD.bazel
  tools/install/install.bzl
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/test/rpath_install_test.py
Labels: status: single reviewer ok, release notes: none

#17903 [doc] Add articles section to landing page
  doc/_pages/gallery.md
  doc/_pages/python_bindings.md
  doc/index.md
Labels: priority: low, release notes: none

#17904 [workspace] Install license snippet for SNOPT
  tools/workspace/BUILD.bazel
  tools/workspace/snopt/BUILD.bazel
  tools/workspace/snopt/LICENSE
Labels: priority: low, release notes: none

#17828 [geometry] Make pressure field for non-convex volume mesh
  geometry/proximity/BUILD.bazel
  geometry/proximity/make_mesh_field.cc
  geometry/proximity/make_mesh_field.h
  geometry/proximity/test/make_mesh_field_test.cc
  geometry/query_results/contact_surface.h
Labels: component: geometry proximity, release notes: none

#17836 [geometry] Support compliant non-convex mesh in hydroelastic_internal.
  geometry/proximity/BUILD.bazel
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/hydroelastic_internal.h
  geometry/proximity/test/hydroelastic_internal_test.cc
Labels: component: geometry proximity, release notes: none

#17917 [geometry/optimization] Fix GraphOfConvexSet test failure under Mosek
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: single reviewer ok, release notes: none

#17921 [workspace] Disable int128 support for absl
  tools/workspace/abseil_cpp_internal/patches/disable_int128_on_clang.patch
  tools/workspace/abseil_cpp_internal/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: none

#17925 [perception] Fixed link error reported by thread sanitizer
  perception/BUILD.bazel
  perception/point_cloud.cc
Labels: priority: high, status: single reviewer ok, component: geometry perception, release notes: none

#17926 [workspace] Upgrade uwebsockets to latest release v20.16.0
  tools/workspace/usockets/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#17929 Fix `build_iiwa_control_test` address sanitizer
  manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
Labels: status: single reviewer ok, release notes: none

#17781 Move client example binary and remove the dev folder
  geometry/render/dev/render_gltf_client/BUILD.bazel
  geometry/render/dev/render_gltf_client/test/flask_import_test.py
  geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/test/4_color_texture.png
  geometry/render_gltf_client/test/README.md
  geometry/render_gltf_client/test/acceptance_test.py
  geometry/render_gltf_client/test/client_demo.cc
  geometry/render_gltf_client/test/example_scene.sdf
  geometry/render_gltf_client/test/server_demo.py
  geometry/render_gltf_client/test/server_vtk_backend.cc
Labels: release notes: none

#17796 [geometry/optimization] Enable rounding of GCS solution when solving convex relaxation of ShortestPath
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: feature

#17920 Add CalcJacobianPositionVector
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_jacobians_test.cc
Labels: priority: medium, release notes: feature

#17931 [pydrake] Add binding for CalcJacobianPositionVector
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.h
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: none

#17938 call_python_client: Use newer matplotlib API for 3d plotting
  common/proto/call_python_client.py
Labels: release notes: none

#17932 Revert "[workspace] Upgrade uwebsockets to latest release v20.16.0"
  tools/workspace/usockets/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: none

#17914 [perception] Implement PointCloud::EstimateNormals
  bindings/pydrake/perception_py.cc
  bindings/pydrake/test/perception_test.py
  perception/BUILD.bazel
  perception/point_cloud.cc
  perception/point_cloud.h
  perception/test/point_cloud_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/nanoflann_internal/BUILD.bazel
  tools/workspace/nanoflann_internal/package.BUILD.bazel
  tools/workspace/nanoflann_internal/patches/namespace.patch
  tools/workspace/nanoflann_internal/repository.bzl
Labels: priority: medium, component: geometry perception, release notes: feature

#17939 Replace 0xa0 character with space
  multibody/inverse_kinematics/minimum_distance_constraint.h
  multibody/plant/multibody_plant.h
  solvers/minimum_value_constraint.cc
  solvers/minimum_value_constraint.h
Labels: priority: low, status: single reviewer ok, release notes: none

#17945 [perception] Normalize normals in PointCloud::VoxelizedDownSample
  perception/point_cloud.cc
  perception/test/point_cloud_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#17944 [tools] Teach clang-format about C++20 and C++23 headers
  .clang-format
  bindings/pydrake/.clang-format
  tools/install/libdrake/test/header_dependency_test.py
Labels: priority: medium, status: single reviewer ok, release notes: fix

#17948 [perception] Fix PointCloud::Concatenate for XYZs only.
  perception/point_cloud.cc
  perception/test/point_cloud_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#17949 Use constexpr (not just const) for fmt strings
  common/trajectories/discrete_time_trajectory.cc
  geometry/render/test/render_camera_test.cc
  geometry/render/test/render_engine_test.cc
  geometry/render_gl/internal_opengl_context.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  solvers/program_attribute.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#17918 Fix C++20 errors on macOS
  bindings/pydrake/geometry_py_scene_graph.cc
  common/test/eigen_types_test.cc
  doc/_pages/installation.md
  geometry/query_results/penetration_as_point_pair.h
  manipulation/kuka_iiwa/iiwa_driver.h
  manipulation/schunk_wsg/schunk_wsg_driver.h
Labels: priority: low, status: single reviewer ok, release notes: none

#17937 [proximity] Improve/fix obb hierarchy construction
  geometry/proximity/obb.cc
  geometry/proximity/obb.h
  geometry/proximity/test/obb_test.cc
Labels: release notes: fix

#17950 [geometry/optimization] Hotfix for graph_of_convex_sets_test
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: priority: high, release notes: none

#17853 [doc] Add release notes v1.8.0
  doc/_pages/apt.md
  doc/_pages/from_binary.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_release-notes/v1.8.0.md
Labels: release notes: none

#17953 [workspace] Upgrade petsc to latest release v3.17.4
  tools/workspace/petsc/patches/petscimpl.patch
  tools/workspace/petsc/repository.bzl
Labels: release notes: fix

#17881 [geometry] Change DeformableRigidContact to DeformableContact
  geometry/geometry_state.h
  geometry/proximity/BUILD.bazel
  geometry/proximity/deformable_contact_internal.cc
  geometry/proximity/deformable_contact_internal.h
  geometry/proximity/deformable_mesh_intersection.cc
  geometry/proximity/deformable_mesh_intersection.h
  geometry/proximity/test/deformable_contact_internal_test.cc
  geometry/proximity/test/deformable_mesh_intersection_test.cc
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/query_object.cc
  geometry/query_object.h
  geometry/query_results/BUILD.bazel
  geometry/query_results/deformable_contact.cc
  geometry/query_results/deformable_contact.h
  geometry/query_results/deformable_rigid_contact.cc
  geometry/query_results/deformable_rigid_contact.h
  geometry/query_results/test/deformable_contact_test.cc
  geometry/query_results/test/deformable_rigid_contact_test.cc
  geometry/test/geometry_state_test.cc
  geometry/test/proximity_engine_test.cc
  geometry/test/query_object_test.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
Labels: release notes: none

#17942 Deprecate math::saturate which is identical to std::clamp
  common/symbolic/expression/expression.cc
  common/symbolic/expression/expression.h
  common/symbolic/expression/test/expression_test.cc
  common/trajectories/bspline_trajectory.cc
  common/trajectories/path_parameterized_trajectory.cc
  common/trajectories/piecewise_polynomial.cc
  common/trajectories/piecewise_trajectory.cc
  common/trajectories/test/bspline_trajectory_test.cc
  common/trajectories/test/path_parameterized_trajectory_test.cc
  manipulation/schunk_wsg/BUILD.bazel
  manipulation/schunk_wsg/schunk_wsg_position_controller.cc
  math/BUILD.bazel
  math/saturate.h
  systems/primitives/BUILD.bazel
  systems/primitives/saturation.cc
Labels: priority: low, release notes: newly deprecated

#17927 [config] Allow specification of render engine type in CameraConfig
  geometry/BUILD.bazel
  geometry/render_gl/factory.cc
  geometry/render_gl/factory.h
  geometry/render_gl/no_factory.cc
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/scene_graph_test.cc
  systems/sensors/BUILD.bazel
  systems/sensors/camera_config.cc
  systems/sensors/camera_config.h
  systems/sensors/camera_config_functions.cc
  systems/sensors/test/camera_config_functions_test.cc
  systems/sensors/test/camera_config_test.cc
Labels: priority: high, release notes: feature

#17837 [geometry] Compliant hydroelastic non-convex mesh in ProximityEngine
  geometry/BUILD.bazel
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/test/hydroelastic_internal_test.cc
  geometry/proximity_engine.cc
  geometry/test/proximity_engine_test.cc
Labels: component: geometry proximity, release notes: none

#17947 [meshcat] Allow keyboard events to move sliders and click buttons
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/test/geometry_visualizers_test.py
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/meshcat_types.h
  geometry/test/meshcat_manual_test.cc
  geometry/test/meshcat_test.cc
  tools/workspace/meshcat/repository.bzl
Labels: priority: medium, release notes: feature

#17958 [common] Add fmt_runtime compatibility shim for C++20
  common/test/text_logging_test.cc
  common/text_logging.h
  geometry/meshcat.cc
  systems/sensors/image_writer.cc
  tools/install/bazel/test/drake_bazel_installed_test.py
Labels: priority: medium, release notes: none

#17967 Hotfix CI leak
  systems/sensors/BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#17968 [install] Add eigen support to the drake_bazel_installed workflow
  tools/install/bazel/drake.BUILD.bazel
  tools/install/bazel/repo_template.bzl
Labels: priority: low, release notes: fix

#17940 [bindings/manipulation] Bind manipulation drivers
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/all.py
  bindings/pydrake/manipulation/kuka_iiwa_py.cc
  bindings/pydrake/manipulation/schunk_wsg_py.cc
  bindings/pydrake/manipulation/test/kuka_iiwa_test.py
  bindings/pydrake/manipulation/test/schunk_wsg_test.py
  bindings/pydrake/manipulation/test/util_test.py
  bindings/pydrake/manipulation/util_py.cc
Labels: release notes: feature

#17970 [workspace] Patch dReal to fix fmt strings
  tools/workspace/dreal/patches/pull283.patch
  tools/workspace/dreal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#17956 [parsing] Support parsing continuous joint in SDFormat
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf
Labels: release notes: feature

#17792 [multibody] Add DeformableDriver
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/physical_model.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/deformable_driver_test.cc
  multibody/plant/test/deformable_model_test.cc
  multibody/plant/test/dummy_model.h
Labels: release notes: none

#17973 [workspace] Fix Qhull build errors when in C++20 mode
  tools/workspace/qhull_internal/patches/cxx20.patch
  tools/workspace/qhull_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#17941 website: Add link to drake-ros
  doc/_pages/tm.md
  doc/_pages/website_licenses.md
  doc/index.md
  doc/third_party/images/python-logo-generic.svg
  doc/third_party/images/python.README.txt
Labels: status: squashing now, release notes: feature

#17975 [solvers] Tweak OSQP solver test to satisfy CI
  solvers/test/osqp_solver_test.cc
Labels: release notes: none

#17974 [geometry/optimization] Improve GraphOfConvexSets handling of infeasible problems
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: fix

#17972 [multibody] Add output port for deformable configurations
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/test/deformable_model_test.cc
Labels: release notes: none

#17930 [visualization] Add comment on design rationale
  visualization/visualization_config_functions.cc
Labels: priority: backlog, status: single reviewer ok, release notes: none

#17982 [geometry/optimization] Fix corner case in HPolyhedron::UniformSample
  bindings/pydrake/geometry_py_optimization.cc
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/test/hpolyhedron_test.cc
Labels: priority: medium, status: squashing now, component: geometry general, release notes: fix

#17955 [multibody] Support deformable free motion calculation
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/test/deformable_driver_test.cc
Labels: release notes: none

#17984 Make make_arm_controller_model externally accessible
  bindings/pydrake/manipulation/kuka_iiwa_py.cc
  manipulation/kuka_iiwa/build_iiwa_control.h
  manipulation/util/BUILD.bazel
Labels: status: single reviewer ok, release notes: fix

#17971 [doc] Unify the tutorials links to a single destination
  doc/_config.yml
  doc/doxygen_cxx/header.html.patch
  doc/index.md
  doc/pydrake/layout.html
  tutorials/README.md
  tutorials/authoring_multibody_simulation.ipynb
  tutorials/debug_mathematical_program.ipynb
  tutorials/dynamical_systems.ipynb
  tutorials/index.ipynb
  tutorials/licensed_solvers_deepnote.ipynb
  tutorials/linear_program.ipynb
  tutorials/mathematical_program.ipynb
  tutorials/mathematical_program_multibody_plant.ipynb
  tutorials/multibody_plant_autodiff_mass.ipynb
  tutorials/nonlinear_program.ipynb
  tutorials/pyplot_animation_multibody_plant.ipynb
  tutorials/quadratic_program.ipynb
  tutorials/rendering_multibody_plant.ipynb
  tutorials/solver_parameters.ipynb
  tutorials/sum_of_squares_optimization.ipynb
  tutorials/test/notebook_lint_test.py
  tutorials/updating_costs_and_constraints.ipynb
Labels: priority: low, status: single reviewer ok, release notes: none

#17913 workspace: Upgrade libsdformat to latest release 13.0.0
  multibody/parsing/detail_ignition.cc
  multibody/parsing/detail_ignition.h
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_parser.cc
  tools/workspace/gz_math_internal/package.BUILD.bazel
  tools/workspace/gz_math_internal/repository.bzl
  tools/workspace/gz_utils_internal/package.BUILD.bazel
  tools/workspace/gz_utils_internal/repository.bzl
  tools/workspace/sdformat_internal/BUILD.bazel
  tools/workspace/sdformat_internal/embed_sdf.py
  tools/workspace/sdformat_internal/gz_sdf_main.cc
  tools/workspace/sdformat_internal/package.BUILD.bazel
  tools/workspace/sdformat_internal/patches/1043.patch
  tools/workspace/sdformat_internal/patches/no_global_config.patch
  tools/workspace/sdformat_internal/repository.bzl
  tools/workspace/sdformat_internal/test/gz_sdf_test.py
Labels: release notes: fix

#17988 [pydrake] Add binding for ContactWrenchFromForceInWorldFrameEvaluator
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/optimization_py.cc
  bindings/pydrake/multibody/test/optimization_test.py
Labels: priority: medium, component: pydrake, release notes: feature

#17994 [plant] Remove fmt precision in error messages
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/multibody_plant.cc
Labels: priority: low, release notes: none

#17987 [IRIS] New termination conditions for IrisInConfigurationSpace
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/iris.cc
  geometry/optimization/iris.h
  geometry/optimization/test/iris_in_configuration_space_test.cc
Labels: priority: medium, component: geometry general, release notes: breaking change, release notes: feature

#17995 Fix some miscellaneous C++20 warnings
  bindings/pydrake/systems/lcm_pybind.h
  math/autodiff.h
Labels: priority: low, status: single reviewer ok, release notes: none

#17741 Refactors SAP code outside of CompliantContactManager
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/contact_pair_kinematics.cc
  multibody/plant/contact_pair_kinematics.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/compliant_contact_manager_tester.h
  multibody/plant/test/deformable_driver_test.cc
  multibody/plant/test/sap_driver_joint_limits_test.cc
  multibody/plant/test/sap_driver_multidof_joints_test.cc
  multibody/plant/test/sap_driver_test.cc
  multibody/plant/test/spheres_stack.h
Labels: component: multibody plant, release notes: none

#17969 [multibody] DeformableDriver processes deformable body contacts
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/test/deformable_driver_contact_test.cc
  multibody/plant/test/deformable_driver_multiplexer_test.cc
Labels: release notes: none

#18002 [hotfix] Reconcile difference between #17741 and #17969
  multibody/plant/test/deformable_driver_contact_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#18000 [doc] Updates to release playbook for tutorials
  doc/_pages/release_playbook.md
Labels: priority: low, status: single reviewer ok, release notes: fix

#17992 kcov_tool: Implement Bazel 5.3.1 compatibility
  tools/dynamic_analysis/kcov_tool
Labels: status: single reviewer ok, release notes: none

#17943 Use C++20 on macOS and Ubuntu 22
  common/bit_cast.h
  doc/_pages/installation.md
  tools/macos.bazelrc
  tools/ubuntu-jammy.bazelrc
  tools/workspace/qhull_internal/package.BUILD.bazel
Labels: priority: medium, release notes: feature

#17998 Add tolerance to rotation_constraint_test TestRpyLimits
  solvers/test/rotation_constraint_test.cc
Labels: status: single reviewer ok, release notes: none

#17977 [planner] Clean up formulation of Differential IK
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/planner_py.cc
  bindings/pydrake/manipulation/test/planner_test.py
  examples/manipulation_station/end_effector_teleop_dualshock4.py
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
  manipulation/planner/BUILD.bazel
  manipulation/planner/differential_inverse_kinematics.cc
  manipulation/planner/differential_inverse_kinematics.h
  manipulation/planner/differential_inverse_kinematics_integrator.cc
  manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  multibody/parsing/detail_sdf_parser.cc
Labels: priority: medium, release notes: newly deprecated, release notes: fix, component: planning and control

#18011 [wheel] Use Eigen 3.4 on macOS
  tools/wheel/image/dependencies/projects.cmake
Labels: priority: high, status: single reviewer ok, release notes: fix

#18005 [doc] x86_64 macOS monterey uses Xcode 14
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/mac.md
Labels: release notes: breaking change
