Repository RobotLocomotion/drake, pull requests merged in 2022-01, with the labels that each got.

#16298 Add Acrobot unit test for LQR
  systems/controllers/BUILD.bazel
  systems/controllers/test/linear_quadratic_regulator_test.cc
Labels: release notes: none

#16302 [controllers] Document the N term in LinearQuadraticRegulator.
  systems/controllers/linear_quadratic_regulator.h
Labels: status: single reviewer ok, release notes: none

#16289 Add AddNonnegativePolynomialConstraint function.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
  solvers/test/scaled_diagonally_dominant_matrix_test.cc
Labels: release notes: yes

#16297 Add UpdateCoefficients to (rotated)LorentzConeConstraint
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/constraint.cc
  solvers/constraint.h
  solvers/test/constraint_test.cc
Labels: release notes: yes

#16290 Minor wheel fixes
  tools/wheel/build-wheels
  tools/wheel/test/provision.sh
Labels: status: commits are properly curated, release notes: none

#16305 Update Ubuntu codename to match release
  tools/release_engineering/relnotes.py
  tools/workspace/new_release.py
Labels: status: single reviewer ok, release notes: none

#16296 Return the new cost and slack variables from AddMaximizeLogDeterminantSymmetricMatrixCost
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/exponential_cone_program_examples.cc
Labels: release notes: yes

#16303 Mbt GetByName() heap alloc fix
  multibody/tree/BUILD.bazel
  multibody/tree/multibody_tree.cc
  multibody/tree/test/multibody_tree_test.cc
Labels: status: squashing now, release notes: yes

#16306 [fem] Integrate PETSc matrix with FemSolver
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/dirichlet_boundary_condition.h
  multibody/fixed_fem/dev/fem_model_base.cc
  multibody/fixed_fem/dev/fem_solver.h
  multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc
  multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h
  multibody/fixed_fem/dev/test/dirichlet_boundary_condition_test.cc
  multibody/fixed_fem/dev/test/fem_solver_test.cc
Labels: status: commits are properly curated, status: single reviewer ok, release notes: none, component: softsim fem

#16257 [geometry] Take care of centroids of zero-area polygons in PolygonSurfaceMesh
  geometry/proximity/polygon_surface_mesh.cc
  geometry/proximity/polygon_surface_mesh.h
  geometry/proximity/test/polygon_surface_mesh_test.cc
Labels: type: bug, team: dynamics, priority: medium, component: geometry proximity, release notes: yes

#16258 [examples/multibody] Hydroelastic-representation option for rolling sphere
  examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
Labels: team: dynamics, priority: medium, component: multibody plant, release notes: none

#16317 [tutorials] intializeAutoDiff => InitializeAutoDiff in tutorial
  tutorials/multibody_plant_autodiff_mass.ipynb
Labels: status: single reviewer ok, release notes: none

#16312 [tutorials] Fixup debug_mathematical_program
  tutorials/debug_mathematical_program.ipynb
Labels: status: single reviewer ok, release notes: none

#16321 [fixed_fem] Disable deformable_rigid_manager_test under ubsan
  multibody/fixed_fem/dev/BUILD.bazel
Labels: priority: high, release notes: none

#16314 [tutorials] fixup dynamical_systems tutorial
  tutorials/README.md
  tutorials/dynamical_systems.ipynb
Labels: status: single reviewer ok, release notes: none

#16315 [tutorials] fixup lp tutorial for deepnote
  tutorials/linear_program.ipynb
Labels: status: single reviewer ok, release notes: none

#16318 [tutorials] fixup latex in nonlinear_program.ipynb for deepnote
  tutorials/nonlinear_program.ipynb
Labels: status: single reviewer ok, release notes: none

#16319 [tutorials] fixup remaining tutorials for deepnote
  tutorials/pyplot_animation_multibody_plant.ipynb
  tutorials/quadratic_program.ipynb
  tutorials/sum_of_squares_optimization.ipynb
  tutorials/updating_costs_and_constraints.ipynb
Labels: status: single reviewer ok, release notes: none

#16323 [doc] Link directly to pip instructions
  doc/_pages/python_bindings.md
Labels: priority: low, status: single reviewer ok, release notes: none

#16299 Enable removing Vertices and Edges from GraphOfConvexSets
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: yes

#16330 Fix sporadic segfault in RemoveVertex
  geometry/optimization/graph_of_convex_sets.cc
Labels: status: single reviewer ok, release notes: none

#16309 Rename to AddMaximizeLogDeterminantCost.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  geometry/optimization/hpolyhedron.cc
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/exponential_cone_program_examples.cc
Labels: status: single reviewer ok, release notes: newly deprecated

#16328 [fem] Fix 3x3 block Cholesky in PETSc
  multibody/fixed_fem/dev/BUILD.bazel
  tools/workspace/petsc/patches/sbaijfact2.patch
  tools/workspace/petsc/repository.bzl
Labels: status: single reviewer ok, release notes: none, component: softsim fem

#16331 [tools] Set Python version to 3 explicitly
  tools/BUILD.bazel
  tools/workspace/meshcat_python/package.BUILD.bazel
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pycodestyle/package.BUILD.bazel
  tools/workspace/ros_xacro/package.BUILD.bazel
  tools/workspace/sdformat/package.BUILD.bazel
  tools/workspace/styleguide/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#16337 Change mathematicalprogram tutorial to deepnote.
  tutorials/mathematical_program.ipynb
Labels: status: single reviewer ok, release notes: none

#16327 Remove deprecated code 2022-01
  common/trajectories/piecewise_pose.h
  common/trajectories/test/piecewise_pose_test.cc
  geometry/BUILD.bazel
  geometry/geometry_index.h
  geometry/proximity/mesh_field_linear.h
  geometry/proximity/test/mesh_field_linear_test.cc
  math/linear_solve.h
  math/test/linear_solve_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#16325 urdf: Modernize collision filter groups
  examples/atlas/urdf/atlas_convex_hull.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf
  manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf
  multibody/parsing/test/links_with_visuals_and_collisions.urdf
  multibody/plant/test/atlas_with_fixed_joints.urdf
Labels: release notes: none

#16227 python_bindings: Add advice for using self-contained `ipdb.iex`
  doc/_pages/python_bindings.md
Labels: priority: low, configuration: python, release notes: yes

#16341 [geometry] Fix unit tests of hydroelastic callback on macOS unprovisioned
  geometry/proximity/test/hydroelastic_callback_test.cc
Labels: configuration: mac, team: dynamics, priority: emergency, status: single reviewer ok, component: geometry proximity, release notes: none

#16324 Upgrade externals to latest releases
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/buildifier/repository.bzl
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/json/repository.bzl
  tools/workspace/petsc/repository.bzl
  tools/workspace/rules_python/repository.bzl
  tools/workspace/tinyobjloader/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
  tools/workspace/voxelized_geometry_tools/package.BUILD.bazel
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: yes

#16173 Replace relative paths with package URIs in models
  geometry/render/test/box.sdf
  manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf
  multibody/parsing/test/links_with_visuals_and_collisions.sdf
  multibody/parsing/test/links_with_visuals_and_collisions.urdf
  multibody/parsing/test/sdf_parser_test/all_geometries_as_collision.sdf
  multibody/parsing/test/sdf_parser_test/all_geometries_as_visual.sdf
  multibody/parsing/test/urdf_parser_test/all_geometries_as_collision.urdf
  multibody/parsing/test/urdf_parser_test/all_geometries_as_visual.urdf
  multibody/parsing/test/urdf_parser_test/convex_and_nonconvex_test.urdf
  multibody/parsing/test/urdf_parser_test/non_conflicting_materials_2.urdf
Labels: release notes: none

#16333 [trajectory_optimization] MultipleShooting has-a MathematicalProgram
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_trajectory_optimization_extra.py
  bindings/pydrake/systems/test/trajectory_optimization_test.py
  bindings/pydrake/systems/trajectory_optimization_py.cc
  examples/acrobot/test/run_swing_up_traj_optimization.cc
  examples/pendulum/trajectory_optimization_simulation.cc
  systems/controllers/linear_model_predictive_controller.cc
  systems/trajectory_optimization/BUILD.bazel
  systems/trajectory_optimization/direct_collocation.cc
  systems/trajectory_optimization/direct_transcription.cc
  systems/trajectory_optimization/multiple_shooting.cc
  systems/trajectory_optimization/multiple_shooting.h
  systems/trajectory_optimization/test/direct_collocation_test.cc
  systems/trajectory_optimization/test/direct_transcription_test.cc
  systems/trajectory_optimization/test/multiple_shooting_test.cc
Labels: release notes: breaking change

#16346 direct_transcription_test: Double shard_count
  systems/trajectory_optimization/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok, release notes: none

#16326 [kuka_iiwa_arm] Do not install example C++ binaries
  examples/BUILD.bazel
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/kuka_plan_runner.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/kuka_iiwa_arm/test/kuka_plan_runner_installed_test.py
  examples/kuka_iiwa_arm/test/kuka_simulation_installed_test.py
  tools/wheel/image/build-wheel.sh
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#16343 [perception] Deprecate PoseSmoother
  manipulation/perception/BUILD.bazel
  manipulation/perception/pose_smoother.h
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#16308 Add wheels for Focal (Python 3.8 and 3.9)
  tools/wheel/Dockerfile
  tools/wheel/build-wheels
  tools/wheel/image/packages-bionic
  tools/wheel/image/packages-focal
  tools/wheel/image/provision-base.sh
  tools/workspace/nlopt/repository.bzl
  tools/workspace/os.bzl
Labels: status: commits are properly curated, release notes: yes

#16336 [symbolic] Output symbolic::Expression/Formula as a LaTeX string
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/BUILD.bazel
  common/symbolic_latex.cc
  common/symbolic_latex.h
  common/test/symbolic_latex_test.cc
Labels: release notes: yes

#16329 [plant] Remove deprecated code 2022-01
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/contact_results_to_lcm.h
  multibody/plant/test/contact_results_to_lcm_test.cc
Labels: priority: low, release notes: removal of deprecated

#16332 Add more tests on symbolic::Polynomial on ndeterminates/decision_variables
  common/test/symbolic_polynomial_test.cc
Labels: release notes: none

#16003 Update position, velocity, and effort limits for kuka iiwa14 variants
  manipulation/models/iiwa_description/BUILD.bazel
  manipulation/models/iiwa_description/README.md
  manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
  manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf
  manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc
  manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14.xacro
  manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf
  manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf
  manipulation/models/iiwa_description/urdf/test/dual_iiwa14_polytope_collision_test.cc
  multibody/plant/test/joint_limits_test.cc
Labels: status: squashing now, release notes: breaking change

#16335 [workspace] Improve new_release heuristics
  tools/workspace/new_release.py
Labels: release notes: none

#16334 Add L1NormCost and LInfNormCost to GraphOfConvexSets cost options
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
  solvers/cost.cc
  solvers/cost.h
  solvers/test/cost_test.cc
Labels: release notes: yes

#16340 Fix internally inconsistent RenderEngineVtk opacity.
  geometry/render/render_engine_vtk.cc
  geometry/render/test/render_engine_vtk_test.cc
Labels: priority: high, release notes: none

#16322 [multibody] HydroelasticEngine ignores hydroelastic_modulus of rigid geometries.
  multibody/hydroelastics/hydroelastic_engine.cc
  multibody/hydroelastics/test/hydroelastic_engine_test.cc
  multibody/parsing/detail_common.cc
  multibody/parsing/test/detail_common_test.cc
Labels: type: bug, priority: low, team: dynamics, component: multibody plant, release notes: none

#16349 [multibody] Add unit inertia for ellipsoid
  multibody/tree/test/unit_inertia_test.cc
  multibody/tree/unit_inertia.h
Labels: priority: high, component: multibody plant, release notes: yes

#16353 Use `lsb_release` for distro detection
  tools/workspace/os.bzl
Labels: status: commits are properly curated, release notes: none

#16361 [framework] Fix a deprecation date typo
  systems/framework/system.h
Labels: status: single reviewer ok, release notes: none

#16360 [geometry] Remove date target in TODO
  geometry/geometry_properties.h
Labels: priority: low, status: single reviewer ok, release notes: none

#16347 Updates to unrecognized sdf elements EnforcementPolicy
  examples/multibody/four_bar/four_bar.sdf
  examples/planar_gripper/planar_gripper.sdf
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/plant/test/block_on_halfspace.sdf
Labels: status: squashing now, release notes: yes

#16359 [primitives] Deprecate RandomSourced alias
  systems/primitives/random_source.h
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#16354 [geometry] Implements `CalcVolume` for basic `Shape`s
  bindings/pydrake/geometry_py_common.cc
  bindings/pydrake/test/geometry_common_test.py
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/test/shape_specification_test.cc
Labels: release notes: yes

#16283 Allow CMake build type to be case-insensitive
  CMakeLists.txt
Labels: configuration: cmake, status: squashing now, release notes: none

#16352 [pydrake] Bind SystemVisitor and Diagram introspection methods
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok, release notes: yes

#16351 VPolytope implements convex geometry.
  geometry/BUILD.bazel
  geometry/optimization/BUILD.bazel
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
  geometry/proximity_engine.cc
  geometry/read_obj.cc
  geometry/read_obj.h
  geometry/test/octahedron.mtl
  geometry/test/octahedron.obj
  geometry/test/read_obj_test.cc
Labels: release notes: yes

#16371 [doc] Explain the work-around for a kcov build error
  doc/_pages/bazel.md
Labels: priority: low, status: single reviewer ok, release notes: none

#16364 [geometry/dev] add comment with useful viewpoints
  geometry/render/dev/render_engine_vtk_minimal_example.cc
Labels: status: single reviewer ok, release notes: none

#16348 [parsing] Redirect sdformat console messages to drake logging
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  tools/workspace/sdformat/package.BUILD.bazel
  tools/workspace/sdformat/patches/console.patch
  tools/workspace/sdformat/repository.bzl
Labels: priority: low, release notes: yes

#16372 Don't memcheck lcm_vector_gen_test
  tools/vector_gen/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#16370 [multibody] Establish detail_mujoco_parser.
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_mujoco_parser.h
  multibody/parsing/test/detail_mujoco_parser_test.cc
  tools/workspace/default.bzl
  tools/workspace/dm_control/BUILD.bazel
  tools/workspace/dm_control/files.bzl
  tools/workspace/dm_control/package.BUILD.bazel
  tools/workspace/dm_control/repository.bzl
Labels: release notes: yes

#16356 [doc] Add release notes v0.38.0
  doc/_pages/from_binary.md
  doc/_pages/pip.md
  doc/_pages/release_playbook.md
  doc/_release-notes/v0.38.0.md
Labels: status: single reviewer ok

#16382 [doc] Deprecate drake-visualizer on macOS
  doc/_release-notes/v0.38.0.md
Labels: priority: high, status: squashing now, status: single reviewer ok, release notes: none

#16368 Add SceneGraphInspector::GetParent(FrameId)
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/scene_graph_inspector.h
  geometry/test/geometry_state_test.cc
  geometry/test/scene_graph_inspector_test.cc
Labels: team: dynamics, status: squashing now, component: geometry general, release notes: yes

#16384 [doc] Add a tip for improving DiagramBuilder performance
  systems/framework/diagram_builder.h
Labels: priority: low, status: single reviewer ok, release notes: none

#16386 [tools] Deprecate drake-visualizer on macOS
  doc/_release-notes/v0.38.0.md
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#16388 [wheel] Remove vestigial dev folder
  tools/wheel/dev/README.md
  tools/wheel/dev/build-wheels
Labels: priority: low, release notes: none

#16376 adding dual iiwa14 polytope collision test
  manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc
Labels: status: single reviewer ok, release notes: none

#16387 [workspace] Upgrade stduuid to latest commit
  tools/workspace/stduuid/repository.bzl
Labels: status: single reviewer ok, release notes: yes

#16381 [doc] Explain how to run Drake under Rosetta 2
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/rosetta2.md
Labels: priority: low, release notes: none

#16357 [multibody] Add unit inertia for capsule
  multibody/tree/test/unit_inertia_test.cc
  multibody/tree/unit_inertia.cc
  multibody/tree/unit_inertia.h
Labels: priority: high, component: multibody plant, release notes: yes

#16375 deprecate MathematicalProgram::NewNonnegativePolynomial.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
  solvers/test/scaled_diagonally_dominant_matrix_test.cc
Labels: status: single reviewer ok, release notes: newly deprecated

#16395 Modify credits
  doc/_pages/credits.md
Labels: status: single reviewer ok, release notes: none

#16378 [multibody] Parse mujoco geometry (but not meshes)
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_tinyxml.cc
  multibody/parsing/detail_tinyxml.h
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: none

#16402 [doc] Provide better error messages when sphinx-build isn't found
  doc/pydrake/build.py
Labels: priority: low, status: single reviewer ok, release notes: none

#16377 Iiwa14 acceleration limits
  manipulation/models/iiwa_description/README.md
  manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
  manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf
  manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc
  manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14.xacro
  manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf
  manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf
Labels: status: squashing now, release notes: breaking change

#16396 [systems] Add MultilayerPerceptron
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/BUILD.bazel
  systems/primitives/multilayer_perceptron.cc
  systems/primitives/multilayer_perceptron.h
  systems/primitives/test/multilayer_perceptron_test.cc
Labels: release notes: yes

#16311 [fem] Use PETSc matrix in DeformableRigidManager
  multibody/fixed_fem/dev/deformable_rigid_manager.cc
  multibody/fixed_fem/dev/deformable_rigid_manager.h
  multibody/fixed_fem/dev/fem_model.h
  multibody/fixed_fem/dev/test/deformable_rigid_contact_solver_test.cc
  multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
Labels: status: single reviewer ok, release notes: none, component: softsim fem

#16374 [geometry] Refactor ClipPolygonByHalfSpace() for code reuse.
  geometry/proximity/mesh_intersection.cc
  geometry/proximity/mesh_intersection.h
  geometry/proximity/test/mesh_intersection_test.cc
Labels: team: dynamics, component: geometry proximity, release notes: yes

#16405 [tools] Fix "generated by these conflicting actions" in Bazel 5.0
  tools/cc_toolchain/bazel.rc
  tools/skylark/drake_cc.bzl
Labels: priority: low, status: single reviewer ok, release notes: yes

#16390 [multibody] Guard hazardous map access by GeometryId
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: low, release notes: yes

#16406 [hotfix] fix random generator seed in multilayer_perceptron_test
  systems/primitives/test/multilayer_perceptron_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#16407 [pydrake] Factor out the std::monostate support for reuse
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/monostate_pybind.h
  bindings/pydrake/geometry_py_scene_graph.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#16398 [geometry/optimization] Fix Iris regions not collision free issue
  geometry/optimization/iris.cc
  geometry/optimization/test/iris_test.cc
Labels: release notes: none

#16411 [workspace] Add issue number to drake-visualizer deprecation
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py
Labels: priority: low, status: single reviewer ok, release notes: none

#16373 Return geometric mean cost
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/second_order_cone_program_examples.h
Labels: release notes: yes

#16401 Improve code and tests for UnitInertia for a capsule.
  multibody/tree/test/unit_inertia_test.cc
  multibody/tree/unit_inertia.cc
  multibody/tree/unit_inertia.h
Labels: type: cleanup, priority: low, team: dynamics, status: squashing now, component: multibody plant, release notes: none

#16413 [pydrake] Bind DrakeLcmInterface::get_lcm_url
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/test/lcm_test.py
Labels: priority: low, status: single reviewer ok, release notes: yes

#16083 [yaml] Add Doxygen overview
  common/name_value.h
  common/schema/rotation.h
  common/schema/stochastic.h
  common/schema/transform.h
  common/trajectories/bspline_trajectory.h
  common/yaml/BUILD.bazel
  common/yaml/test/yaml_doxygen_test.cc
  common/yaml/yaml_doxygen.h
  common/yaml/yaml_io.h
  common/yaml/yaml_node.h
  common/yaml/yaml_read_archive.h
  math/bspline_basis.h
Labels: priority: low, release notes: none

#16412 [tools] Enable Werror=literal-conversion with Clang
  tools/skylark/drake_cc.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#16392 [tools] Collect python test coverage data with kcov
  bindings/pydrake/common/BUILD.bazel
  common/test_utilities/drake_py_unittest_main.py
  doc/_pages/bazel.md
  tools/dynamic_analysis/BUILD.bazel
  tools/dynamic_analysis/kcov.sh
  tools/dynamic_analysis/kcoverage.py
  tools/jupyter/jupyter_py.bzl
Labels: priority: low, release notes: none

#16416 [yaml] Fix unit test of fmt output
  common/yaml/test/yaml_doxygen_test.cc
  common/yaml/yaml_doxygen.h
Labels: priority: emergency, status: single reviewer ok

#16418 Rename dummy library to fix Bazel 5 error
  tools/install/dummy/BUILD.bazel
Labels: status: single reviewer ok, release notes: yes

#16417 Add README for build-wheels
  tools/wheel/README.rst
Labels: status: commits are properly curated, status: single reviewer ok, release notes: none

#16414 installer: Add tests that invoke by import
  tools/install/BUILD.bazel
  tools/install/test/install_meta_test.py
Labels: release notes: none

#16410 [systems/primitives] Add BatchOutput to MultilayerPerceptron
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/multilayer_perceptron.cc
  systems/primitives/multilayer_perceptron.h
  systems/primitives/test/multilayer_perceptron_test.cc
Labels: release notes: yes

#16419 Use upstream vtkCapsuleSource
  BUILD.bazel
  geometry/render/BUILD.bazel
  geometry/render/render_engine_vtk_base.cc
  third_party/com_github_finetjul_bender/BUILD.bazel
  third_party/com_github_finetjul_bender/LICENSE
  third_party/com_github_finetjul_bender/NOTICE
  third_party/com_github_finetjul_bender/README.md
  third_party/com_github_finetjul_bender/vtkCapsuleSource.cxx
  third_party/com_github_finetjul_bender/vtkCapsuleSource.h
  tools/install/libdrake/build_components.bzl
Labels: status: commits are properly curated, release notes: yes

#16389 [workspace] Infer homebrew path based on arch
  setup/mac/source_distribution/install_prereqs_user_environment.sh
  tools/lint/clang_format.py
  tools/macos-arch-arm64.bazelrc
  tools/macos-arch-i386.bazelrc
  tools/macos.bazelrc
  tools/py_toolchain/BUILD.bazel
  tools/py_toolchain/interpreter_paths.bzl
  tools/wheel/image/pip-drake.patch
  tools/workspace/boost/repository.bzl
  tools/workspace/clp/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/double_conversion/package-macos.BUILD.bazel
  tools/workspace/double_conversion/repository.bzl
  tools/workspace/eigen/repository.bzl
  tools/workspace/execute.bzl
  tools/workspace/gflags/repository.bzl
  tools/workspace/glew/repository.bzl
  tools/workspace/glib/repository.bzl
  tools/workspace/ipopt/repository.bzl
  tools/workspace/libcurl/repository.bzl
  tools/workspace/libjpeg/package-macos.BUILD.bazel
  tools/workspace/libjpeg/repository.bzl
  tools/workspace/liblz4/repository.bzl
  tools/workspace/liblzma/repository.bzl
  tools/workspace/libpng/repository.bzl
  tools/workspace/libtiff/repository.bzl
  tools/workspace/msgpack/repository.bzl
  tools/workspace/nlopt/package-macos.BUILD.bazel
  tools/workspace/nlopt/repository.bzl
  tools/workspace/openblas/repository.bzl
  tools/workspace/os.bzl
  tools/workspace/pkg_config.bzl
  tools/workspace/python/repository.bzl
  tools/workspace/suitesparse/repository.bzl
  tools/workspace/tinyxml2/repository.bzl
  tools/workspace/vtk/repository.bzl
  tools/workspace/yaml_cpp/package-macos.BUILD.bazel
  tools/workspace/yaml_cpp/repository.bzl
Labels: priority: low, release notes: yes

#16400 [meshcat] Add JointSliders system
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/all.py
  bindings/pydrake/multibody/meshcat_py.cc
  bindings/pydrake/multibody/test/meshcat_test.py
  bindings/pydrake/test/all_test.py
  multibody/meshcat/BUILD.bazel
  multibody/meshcat/joint_sliders.cc
  multibody/meshcat/joint_sliders.h
  multibody/meshcat/test/joint_sliders_test.cc
  multibody/meshcat/test/universal_joint.sdf
  tools/install/libdrake/build_components.bzl
Labels: priority: high, release notes: yes

#16263 [tools] Add meshcat display server for drake_visualizer's protocol
  bindings/pydrake/test/all_test.py
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/all.py
  bindings/pydrake/visualization/meldis.py
  examples/acrobot/README.md
  tools/BUILD.bazel
Labels: priority: medium, release notes: yes

#16425 [multibody/parsing] Support default geometry attributes in MuJoCo parser
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: none

#16428 fix detail_mujoco_parser on mac
  multibody/parsing/detail_mujoco_parser.cc
Labels: status: single reviewer ok, release notes: none

#16409 Compute volume of a VPolytope.
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: release notes: yes

#16430 tools: Remove global subdirs from installer
  tools/install/installer.py
  tools/install/test/install_meta_test.py
Labels: status: single reviewer ok, release notes: none

#16429 multibody doc: Fix a broken section title
  multibody/plant/contact_model_doxygen.h
Labels: status: single reviewer ok, release notes: none

#16391 Eval augmented lagrangian
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/augmented_lagrangian_py.cc
  bindings/pydrake/solvers/test/augmented_lagrangian_test.py
  solvers/BUILD.bazel
  solvers/augmented_lagrangian.cc
  solvers/augmented_lagrangian.h
  solvers/test/augmented_lagrangian_test.cc
Labels: release notes: yes

#16426 [meshcat] Add JointSliders::Run
  bindings/pydrake/multibody/meshcat_py.cc
  bindings/pydrake/multibody/test/meshcat_test.py
  multibody/meshcat/BUILD.bazel
  multibody/meshcat/joint_sliders.cc
  multibody/meshcat/joint_sliders.h
  multibody/meshcat/test/joint_sliders_test.cc
Labels: priority: high, release notes: yes

#16438 [doxygen] use @name rather than \name
  geometry/render/render_engine_vtk.h
Labels: type: documentation, status: commits are properly curated, status: single reviewer ok, release notes: none

#16437 [multibody] Move ContactResultsToMeshcat into meshcat directory
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/_plant_extra.py
  bindings/pydrake/multibody/meshcat_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/meshcat_test.py
  bindings/pydrake/multibody/test/plant_test.py
  geometry/BUILD.bazel
  geometry/test/meshcat_manual_test.cc
  multibody/meshcat/BUILD.bazel
  multibody/meshcat/contact_visualizer.cc
  multibody/meshcat/contact_visualizer.h
  multibody/meshcat/contact_visualizer_params.h
  multibody/meshcat/test/contact_visualizer_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/contact_results_to_meshcat.h
  multibody/plant/contact_results_to_meshcat_params.h
  multibody/plant/test/contact_results_to_meshcat_test.cc
Labels: priority: medium, status: commits are properly curated, release notes: breaking change, release notes: newly deprecated

#16424 AddFooConstraint support matrix input.
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: release notes: yes

#16434 [parsing] Deprecate PopulateUpstreamToDrake
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  examples/pr2/test/load_pr2_simplified_test.cc
  multibody/parsing/package_map.cc
  multibody/parsing/package_map.h
  multibody/parsing/parser.cc
  multibody/parsing/test/detail_path_utils_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/package_map_test.cc
Labels: priority: low, release notes: newly deprecated

#16443 [hotfix] Fix bug in MLP binding test
  bindings/pydrake/systems/test/primitives_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#16440 [meshcat] Factor out internal::PointContactVisualizer
  geometry/meshcat.h
  multibody/meshcat/BUILD.bazel
  multibody/meshcat/contact_visualizer.cc
  multibody/meshcat/contact_visualizer.h
  multibody/meshcat/point_contact_visualizer.cc
  multibody/meshcat/point_contact_visualizer.h
Labels: priority: high, release notes: none

#16441 [workspace] Add libcmaes as a testonly dependency
  tools/workspace/default.bzl
  tools/workspace/libcmaes/BUILD.bazel
  tools/workspace/libcmaes/dev/BUILD.bazel
  tools/workspace/libcmaes/dev/sample_code.cc
  tools/workspace/libcmaes/package.BUILD.bazel
  tools/workspace/libcmaes/repository.bzl
Labels: release notes: yes

#16446 sdf, urdf: Add/canonicalize xmlns: declarations
  bindings/pydrake/multibody/test/hydroelastic.sdf
  examples/atlas/urdf/atlas_convex_hull.urdf
  manipulation/models/franka_description/urdf/panda_arm.urdf
  manipulation/models/franka_description/urdf/panda_arm_hand.urdf
  manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
  manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf
  multibody/contact_solvers/test/particle_with_infinite_inertia.sdf
  multibody/parsing/test/detail_scene_graph_test.cc
  multibody/parsing/test/links_with_visuals_and_collisions.sdf
  multibody/parsing/test/links_with_visuals_and_collisions.urdf
  multibody/parsing/test/process_model_directives_test/simple_model.sdf
  multibody/parsing/test/sdf_parser_test/all_geometries_as_collision.sdf
  multibody/parsing/test/sdf_parser_test/all_geometries_as_visual.sdf
  multibody/parsing/test/sdf_parser_test/collision_filter_group_parsing_test.sdf
  multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf
  multibody/parsing/test/urdf_parser_test/accepting_renderer.urdf
  multibody/parsing/test/urdf_parser_test/all_geometries_as_collision.urdf
  multibody/parsing/test/urdf_parser_test/all_geometries_as_visual.urdf
  multibody/parsing/test/urdf_parser_test/collision_filter_group_parsing_test.urdf
  multibody/parsing/test/urdf_parser_test/convex_and_nonconvex_test.urdf
  multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
  multibody/parsing/test/urdf_parser_test/joint_parsing_test_tag_mismatch_1.urdf
  multibody/plant/test/atlas_with_fixed_joints.urdf
Labels: status: single reviewer ok, release notes: none

#16450 [meldis] Add unit test for ViewerApplet
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/test/geometry_visualizers_test.py
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#16436 [meldis] Display point contact results
  bindings/pydrake/multibody/meshcat_py.cc
  bindings/pydrake/multibody/test/meshcat_test.py
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
  examples/multibody/strandbeest/README.md
  examples/multibody/strandbeest/run_with_motor.cc
Labels: priority: medium, release notes: yes

#16453 [doc] Give better examples for previewing the documentation
  doc/_pages/documentation_instructions.md
Labels: priority: low, status: single reviewer ok, release notes: none

#16234 [geometry/dev] Add glTF Render Client and Server
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/render_client.cc
  geometry/render/dev/render_client.h
  geometry/render/dev/render_client_gltf.cc
  geometry/render/dev/render_client_gltf.h
  geometry/render/dev/render_client_gltf_factory.cc
  geometry/render/dev/render_client_gltf_factory.h
  geometry/render/dev/render_engine_vtk_minimal_example.cc
  geometry/render/dev/render_server/README.md
  geometry/render/dev/render_server/gltf_render_server.py
  geometry/render/dev/render_server/vtk_render_server_backend.cc
  geometry/render/dev/render_server/wsgi.py
  geometry/render/dev/test/json_compile_test.cc
  geometry/render/dev/test/libcurl_compile_test.cc
  geometry/render/dev/test/picosha2_compile_test.cc
  geometry/render/render_engine_vtk.cc
  geometry/render/render_engine_vtk.h
Labels: release notes: none

#16461 iris_test: Run in 12 shards (#16459)
  geometry/optimization/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#16465 [pydrake] Add deprecation for ContactResultsToMeshcat.AddToBuilder
  bindings/pydrake/multibody/_plant_extra.py
  bindings/pydrake/multibody/test/plant_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#16454 [meldis] Use flushing and throttling to keep pace
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: priority: medium, release notes: yes

#16462 [tools] Disable third-party assertions in memcheck
  tools/dynamic_analysis/bazel.rc
Labels: priority: medium, release notes: none

#16445 [meldis] Auto-quit when idle for more than 15 minutes
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/visualization/meldis.py
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/test/meshcat_test.cc
Labels: priority: low, release notes: yes

#16467 [pydrake] Add bindings for CalcImplicitTimeDerivativesResidual
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok, release notes: yes

#16458 Add lightweight version of Tetrahedron/Plane intersection
  geometry/proximity/mesh_plane_intersection.cc
  geometry/proximity/mesh_plane_intersection.h
  geometry/proximity/test/mesh_plane_intersection_test.cc
Labels: priority: high, team: dynamics, component: geometry proximity, release notes: yes

#16365 [geometry] Contact surface from two compliant meshes with pressure
  geometry/proximity/BUILD.bazel
  geometry/proximity/field_intersection.cc
  geometry/proximity/field_intersection.h
  geometry/proximity/mesh_intersection.cc
  geometry/proximity/mesh_intersection.h
  geometry/proximity/test/field_intersection_test.cc
  geometry/proximity/test/mesh_intersection_test.cc
Labels: team: dynamics, component: geometry proximity, release notes: yes

#16366 [geometry] Hydroelastic callback for compliant-compliant contact.
  geometry/proximity/BUILD.bazel
  geometry/proximity/hydroelastic_callback.h
  geometry/proximity/test/hydroelastic_callback_test.cc
  geometry/test/proximity_engine_test.cc
  multibody/plant/test/compliant_contact_manager_test.cc
Labels: team: dynamics, component: geometry proximity, release notes: yes
