Repository RobotLocomotion/drake, pull requests merged in 2022-12, with the labels that each got.

#18382 Change sprintf() to snprintf() to avoid security warnings/errors.
  multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc
Labels: priority: high, release notes: none

#18381 [wheel] Use the correct python version in macOS wheel build
  tools/wheel/macos/build-wheel.sh
  tools/wheel/macos/provision-test-python.sh
Labels: release notes: none

#18386 [doc] Add hydroelastic example to the drake gallery.
  doc/_pages/gallery.md
Labels: release notes: none

#18383 [trajectories] BSplineTrajectory::EvalDerivative now clamps time.
  common/trajectories/bspline_trajectory.cc
  common/trajectories/test/bspline_trajectory_test.cc
Labels: release notes: fix

#18389 Move joint locking parameter to mobilizer
  multibody/tree/body.h
  multibody/tree/joint.h
  multibody/tree/mobilizer.h
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.cc
Labels: release notes: none

#18373 Improve documentation and tests for ComposeWithMovingFrameVelocity().
  multibody/math/spatial_acceleration.h
  multibody/math/spatial_velocity.h
  multibody/math/test/spatial_algebra_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#18322 [parsing] Add SDFormat support for //world/joint
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/sdf_parser_test/world_joint_test.sdf
Labels: status: squashing now, release notes: feature

#18345 Calculate SpatialInertia from Shape and TriangleMesh
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/tree/BUILD.bazel
  multibody/tree/geometry_spatial_inertia.cc
  multibody/tree/geometry_spatial_inertia.h
  multibody/tree/rotational_inertia.h
  multibody/tree/test/geometry_spatial_inertia_test.cc
Labels: release notes: feature

#18397 [contact_properties] Use GetProperty<double>, not GetProperty<T>
  multibody/plant/contact_properties.cc
Labels: priority: emergency, status: squashing now, release notes: fix

#18384 add CspaceFreeRegion class constructor.
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/separating_plane.cc
  geometry/optimization/dev/separating_plane.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
  multibody/rational/rational_forward_kinematics.h
  multibody/rational/test/rational_forward_kinematics_test.cc
Labels: status: single reviewer ok, release notes: none

#18395 [geometry_spatial_inertia] Increase tolerance for mass check
  multibody/tree/test/geometry_spatial_inertia_test.cc
Labels: status: single reviewer ok, release notes: none

#18401 Snopt handles duplicated variables.
  solvers/snopt_solver.cc
  solvers/test/nonlinear_program_test.cc
  solvers/test/optimization_examples.cc
  solvers/test/optimization_examples.h
  solvers/test/snopt_solver_test.cc
Labels: release notes: fix

#18371 [deformable] Zero out jacobian columns for dofs under bc
  multibody/plant/deformable_driver.cc
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
Labels: release notes: none

#18392 [geometry] Fix meshcat_manual_test bugs
  geometry/test/meshcat_manual_test.cc
Labels: priority: low, release notes: none

#18388 ScsSolver returns the dual solution for linear equality constraints.
  solvers/scs_solver.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/linear_program_examples.cc
  solvers/test/linear_program_examples.h
  solvers/test/mosek_solver_test.cc
  solvers/test/scs_solver_test.cc
Labels: release notes: feature

#18390 [multibody] Add joint for each free body
  manipulation/models/allegro_hand_description/test/parse_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/plant/test/multibody_plant_mass_matrix_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: status: squashing now, release notes: breaking change

#18403 [multibody] Add testing for scalar promotion from double to AutoDiffXd
  multibody/plant/test/contact_properties_test.cc
Labels: release notes: none

#18405 [planning] Add RobotCollisionType
  planning/BUILD.bazel
  planning/robot_collision_type.h
  planning/test/robot_collision_type_test.cc
Labels: priority: medium, status: commits are properly curated, release notes: feature

#18408 [wheel] Set macOS deployment target explicitly
  tools/wheel/macos/build-wheel.sh
  tools/wheel/wheel_builder/macos.py
Labels: release notes: none

#18394 Upgrade Externals December 2022
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/gz_math_internal/repository.bzl
  tools/workspace/lcm/repository.bzl
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/petsc/repository.bzl
  tools/workspace/pycodestyle/repository.bzl
  tools/workspace/rules_pkg/repository.bzl
  tools/workspace/rules_python/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#18391 Add comment that MotionGenesis auto-generated file was slightly edited.
  multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc
Labels: priority: low, status: squashing now, status: single reviewer ok, release notes: none

#18400 Add CspaceFreePolytope::GenerateRationals.
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/separating_plane.h
  geometry/optimization/dev/test/c_iris_test_utilities.cc
  geometry/optimization/dev/test/c_iris_test_utilities.h
  geometry/optimization/dev/test/collision_geometry_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: status: single reviewer ok, release notes: none

#18240 Add PrismaticSpring and its SDF parsing
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/prismatic_spring.cc
  multibody/tree/prismatic_spring.h
  multibody/tree/test/prismatic_spring_test.cc
Labels: status: commits are properly curated, release notes: feature

#18329 Improve tests for non-positive definite articulated hinge inertia matrices.
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#18414 Bug fix for SAP holonomic constraints with infinite stiffness
  multibody/contact_solvers/sap/sap_holonomic_constraint.cc
  multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc
Labels: release notes: fix

#18196 Implements support for distance constraints with SAP
  multibody/plant/BUILD.bazel
  multibody/plant/constraint_specs.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/sap_driver_distance_constraints_test.cc
Labels: release notes: feature

#18411 Allow pressing Escape to stop ModelVisualizer
  bindings/pydrake/visualization/_model_visualizer.py
Labels: release notes: fix

#18419 [bindings] Alphabetize joint code
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok, release notes: none

#18420 [bindings] Add bindings for QuaternionFloatingJoint
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: release notes: feature

#18418 [planning] Add RobotClearance
  planning/BUILD.bazel
  planning/robot_clearance.cc
  planning/robot_clearance.h
  planning/test/robot_clearance_test.cc
Labels: status: commits are properly curated, release notes: feature

#18426 Fix docker naming issues with the wheel builder
  tools/wheel/wheel_builder/linux.py
Labels: release notes: none

#18430 [py systems] Bind System.{AllocateInputVector,AllocateInputAbstract}
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok, release notes: feature

#18429 Compute a polynomial from monomial basis and the lower triangular of the Gram.
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic/monomial_util.h
  common/symbolic/polynomial.h
  common/symbolic/test/polynomial_test.cc
Labels: release notes: feature

#18431 [input_port] Add Allocate() method
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  systems/framework/BUILD.bazel
  systems/framework/input_port.cc
  systems/framework/input_port.h
  systems/framework/test/input_port_test.cc
Labels: release notes: feature

#18427 [multibody] Some minor documentation tweaks and internal cleanup
  multibody/plant/multibody_plant.h
  multibody/tree/BUILD.bazel
  multibody/tree/body_node_impl.h
  multibody/tree/body_node_welded.h
  multibody/tree/body_node_world.h
  multibody/tree/multibody_tree.cc
Labels: type: cleanup, priority: low, release notes: none

#18432 Add HPolyhedron::FindRedundant
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/test/hpolyhedron_test.cc
Labels: release notes: feature

#18439 [geometry/optimization] Fix Iris Hit and Run failure bug
  geometry/optimization/iris.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#18434 [primitives] Add TrajectorySource::UpdateTrajectory
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/test/trajectory_source_test.cc
  systems/primitives/trajectory_source.cc
  systems/primitives/trajectory_source.h
Labels: priority: medium, release notes: feature

#18441 [misc] Remove deprecated code 2022-12
  bindings/pydrake/geometry_py_hydro.cc
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/test/geometry_hydro_test.py
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
  multibody/tree/fixed_offset_frame.h
  multibody/tree/frame.cc
  multibody/tree/frame.h
  multibody/tree/rigid_body.cc
  multibody/tree/rigid_body.h
  multibody/tree/test/frames_test.cc
  multibody/tree/weld_joint.h
  solvers/BUILD.bazel
  solvers/bilinear_product_util.cc
  solvers/bilinear_product_util.h
  solvers/test/bilinear_product_util_test.cc
  tools/workspace/default.bzl
  tools/workspace/libcurl/BUILD.bazel
  tools/workspace/libcurl/repository.bzl
Labels: status: single reviewer ok, release notes: removal of deprecated

#18444 [C-IRIS] Construct the program to search for the separating plane
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/c_iris_test_utilities.cc
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18407 New SpatialInertia factory method for SolidBox.
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/tree/geometry_spatial_inertia.cc
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/articulated_body_inertia_test.cc
  multibody/tree/test/spatial_inertia_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#18447 Google Benchmark 2-step update
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  tools/workspace/default.bzl
  tools/workspace/googlebenchmark/repository.bzl
  tools/workspace/libpfm4/BUILD.bazel
  tools/workspace/libpfm4/repository.bzl
Labels: status: commits are properly curated, release notes: feature

#18449 Revert "Google Benchmark 2-step update"
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  tools/workspace/default.bzl
  tools/workspace/googlebenchmark/repository.bzl
  tools/workspace/libpfm4/BUILD.bazel
  tools/workspace/libpfm4/repository.bzl
Labels: status: single reviewer ok, release notes: none

#18453 [cmake] Add pybind11_strip to enable -DCMAKE_BUILD_TYPE=Release
  tools/workspace/pybind11/package.BUILD.bazel
  tools/workspace/pybind11/pybind11-config.cmake
Labels: release notes: fix

#18438 [doc] Add release notes v1.11.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.11.0.md
Labels: status: squashing now, release notes: none

#18428 [planning] Add CollisionCheckerContext
  planning/BUILD.bazel
  planning/collision_checker_context.cc
  planning/collision_checker_context.h
  planning/test/collision_checker_context_test.cc
Labels: status: commits are properly curated, release notes: feature

#18454 [visualization] Add sliders for geometry alpha in MeshcatVisualizer
  bindings/pydrake/test/geometry_visualizers_test.py
  geometry/meshcat_visualizer.cc
  geometry/meshcat_visualizer.h
  geometry/meshcat_visualizer_params.h
  geometry/test/meshcat_visualizer_test.cc
  manipulation/models/ycb/test/parse_test.cc
  visualization/test/visualization_config_functions_test.cc
  visualization/visualization_config.h
  visualization/visualization_config_functions.cc
Labels: release notes: feature

#18458 [doc] Sort release notes index by article date
  doc/_release-notes/2015.md
  doc/_release-notes/2016.md
  doc/_release-notes/template.txt
  doc/_release-notes/v0.10.0.md
  doc/_release-notes/v0.11.0.md
  doc/_release-notes/v0.12.0.md
  doc/_release-notes/v0.13.0.md
  doc/_release-notes/v0.14.0.md
  doc/_release-notes/v0.15.0.md
  doc/_release-notes/v0.16.0.md
  doc/_release-notes/v0.16.1.md
  doc/_release-notes/v0.17.0.md
  doc/_release-notes/v0.18.0.md
  doc/_release-notes/v0.19.0.md
  doc/_release-notes/v0.20.0.md
  doc/_release-notes/v0.21.0.md
  doc/_release-notes/v0.22.0.md
  doc/_release-notes/v0.23.0.md
  doc/_release-notes/v0.24.0.md
  doc/_release-notes/v0.25.0.md
  doc/_release-notes/v0.26.0.md
  doc/_release-notes/v0.27.0.md
  doc/_release-notes/v0.28.0.md
  doc/_release-notes/v0.29.0.md
  doc/_release-notes/v0.30.0.md
  doc/_release-notes/v0.31.0.md
  doc/_release-notes/v0.32.0.md
  doc/_release-notes/v0.33.0.md
  doc/_release-notes/v0.34.0.md
  doc/_release-notes/v0.35.0.md
  doc/_release-notes/v0.36.0.md
  doc/_release-notes/v0.37.0.md
  doc/_release-notes/v0.38.0.md
  doc/_release-notes/v0.39.0.md
  doc/_release-notes/v1.0.0.md
  doc/_release-notes/v1.1.0.md
  doc/_release-notes/v1.10.0.md
  doc/_release-notes/v1.11.0.md
  doc/_release-notes/v1.2.0.md
  doc/_release-notes/v1.3.0.md
  doc/_release-notes/v1.4.0.md
  doc/_release-notes/v1.5.0.md
  doc/_release-notes/v1.6.0.md
  doc/_release-notes/v1.7.0.md
  doc/_release-notes/v1.8.0.md
  doc/_release-notes/v1.9.0.md
Labels: status: single reviewer ok, release notes: none

#18463 Revert "[visualization] Add sliders for geometry alpha in MeshcatVisu…
  bindings/pydrake/test/geometry_visualizers_test.py
  geometry/meshcat_visualizer.cc
  geometry/meshcat_visualizer.h
  geometry/meshcat_visualizer_params.h
  geometry/test/meshcat_visualizer_test.cc
  manipulation/models/ycb/test/parse_test.cc
  visualization/test/visualization_config_functions_test.cc
  visualization/visualization_config.h
  visualization/visualization_config_functions.cc
Labels: status: single reviewer ok, release notes: none

#18460 Remove unneeded CRTP parameter from MultibodyElement
  multibody/tree/body.h
  multibody/tree/body_node.h
  multibody/tree/force_element.h
  multibody/tree/frame_base.h
  multibody/tree/joint.h
  multibody/tree/joint_actuator.cc
  multibody/tree/joint_actuator.h
  multibody/tree/mobilizer.h
  multibody/tree/model_instance.h
  multibody/tree/multibody_element.h
  multibody/tree/multibody_tree_system.h
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: type: cleanup, priority: low, release notes: breaking change

#18424 [planning] Add BodyShapeDescription
  planning/BUILD.bazel
  planning/body_shape_description.cc
  planning/body_shape_description.h
  planning/test/body_shape_description_test.cc
Labels: status: commits are properly curated, release notes: feature

#18468 Add Linux Python 3.11 wheel
  doc/_pages/pip.md
  doc/_pages/release_playbook.md
  tools/release_engineering/download_release_candidate.py
  tools/wheel/image/provision-python.sh
  tools/wheel/wheel_builder/linux.py
  tools/workspace/python/repository.bzl
Labels: release notes: feature

#18469 [visualization] Add sliders for geometry alpha in MeshcatVisualizer
  geometry/meshcat_visualizer.cc
  geometry/meshcat_visualizer.h
  geometry/meshcat_visualizer_params.h
  geometry/test/meshcat_visualizer_test.cc
  visualization/test/visualization_config_functions_test.cc
  visualization/visualization_config.h
  visualization/visualization_config_functions.cc
Labels: release notes: feature

#18472 [planning] Restore move semantics to BodyShapeDescription
  planning/body_shape_description.h
Labels: release notes: fix

#18461 [C-IRIS] Add unit length vector constraint when searching for separating plane
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18474 [C-IRIS] search many separating planes in parallel.
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18402 [multibody] Add ContactResults calculation to DiscreteUpdateManager
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/discrete_contact_pair.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/hydroelastic_quadrature_point_data.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/compliant_contact_manager_tester.h
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/plant/test/tamsi_driver_test.cc
  multibody/plant/test_utilities/BUILD.bazel
  multibody/plant/test_utilities/rigid_body_on_compliant_ground.h
  multibody/plant/test_utilities/square_surface.obj
Labels: status: squashing now, release notes: none

#18475 [C-IRIS] compute the distance from a halfspace to a collision geometry.
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/test/collision_geometry_test.cc
Labels: release notes: none

#18478 buildcop: Disable a test failing TSAN
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: status: single reviewer ok, release notes: none

#18448 Deprecate "register w.r.t. geometry" SceneGraph APIs
  bindings/pydrake/geometry_py_scene_graph.cc
  bindings/pydrake/test/geometry_scene_graph_test.py
  examples/scene_graph/solar_system.cc
  geometry/geometry_state.h
  geometry/query_object.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/scene_graph_inspector.cc
  geometry/scene_graph_inspector.h
  geometry/test/geometry_state_test.cc
  geometry/test/scene_graph_inspector_test.cc
  geometry/test/scene_graph_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: newly deprecated

#18479 Upgrade tinyobjloader to the latest commit and fix tests
  geometry/render_gl/internal_shape_meshes.cc
  geometry/render_gl/internal_shape_meshes.h
  geometry/render_gl/test/internal_shape_meshes_test.cc
  tools/workspace/tinyobjloader/repository.bzl
Labels: release notes: none

#18481 [visualization] Enable alpha sliders in ModelVisualizer
  bindings/pydrake/visualization/_model_visualizer.py
Labels: release notes: feature

#18482 [C-IRIS] fix tsan problem with multiple threads.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18459 Remove a redundant check on the signed_distance < influence_distance in MinimumDistanceConstraint.
  multibody/inverse_kinematics/minimum_distance_constraint.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h
  multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
Labels: release notes: none

#18473 [planning] Add CollisionCheckerParams
  planning/BUILD.bazel
  planning/collision_checker_params.h
Labels: status: commits are properly curated, release notes: feature

#18485 Create the CspaceFreePolytope rationals at object construction
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: status: squashing now, release notes: none

#18486 Replace unsupported NumPy aliases
  bindings/pydrake/common/test/numpy_compare_test.py
  bindings/pydrake/forwarddiff.py
  bindings/pydrake/test/autodiffutils_test.py
  common/proto/call_python_client.py
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
Labels: status: single reviewer ok, release notes: none

#18476 Add ComputeQ to rational forward kinematics
  multibody/rational/rational_forward_kinematics.cc
  multibody/rational/rational_forward_kinematics.h
  multibody/rational/test/rational_forward_kinematics_test.cc
Labels: status: squashing now, release notes: feature

#18455 [doc] Add direct links for buildcop cache server checks
  doc/_pages/buildcop.md
Labels: release notes: none

#18484 [C-IRIS] Add a public function to search for separation certificate for a given polytope.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18489 [doc] add carrot scooping video to the drake gallery
  doc/_pages/gallery.md
Labels: status: single reviewer ok

#18440 Prerequisites for Drake Gym: Import OpenAI Gym; fake-vendor stable_b…
  tools/workspace/default.bzl
  tools/workspace/gym_py/BUILD.bazel
  tools/workspace/gym_py/README.md
  tools/workspace/gym_py/package.BUILD.bazel
  tools/workspace/gym_py/repository.bzl
  tools/workspace/stable_baselines3_internal/BUILD.bazel
  tools/workspace/stable_baselines3_internal/README.md
  tools/workspace/stable_baselines3_internal/connection.patch
  tools/workspace/stable_baselines3_internal/no_torch.patch
  tools/workspace/stable_baselines3_internal/package.BUILD.bazel
  tools/workspace/stable_baselines3_internal/repository.bzl
  tools/workspace/stable_baselines3_internal/test/stable_baselines3_internal_test.py
Labels: priority: medium, release notes: none

#18488 Enable manual model reloading in ModelVisualizer
  bindings/pydrake/visualization/_model_visualizer.py
  bindings/pydrake/visualization/model_visualizer.py
Labels: release notes: feature

#18493 [geometry] Construct an HPoyhedron from a VPolytope.
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/test/hpolyhedron_test.cc
Labels: release notes: feature

#18494 [C-IRIS] Fix a problem when generating rationals for polytope on one side of plane
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/test/collision_geometry_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18496 [C-IRIS] Consolidate to the formulation using Chebyshev center for polytope
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/test/collision_geometry_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18497 [C-IRIS] construct polytope search program.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18495 Rational forward kinematics python bindings
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/all.py
  bindings/pydrake/multibody/rational_py.cc
  bindings/pydrake/multibody/test/pendulum_on_rail.sdf
  bindings/pydrake/multibody/test/rational_test.py
  multibody/rational/rational_forward_kinematics.h
Labels: status: squashing now, release notes: feature

#18499 [C-IRIS] Add bilinear alternation to CspaceFreePolytope.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18504 [C-IRIS] increase timeout for cspace_free_polytope_test
  geometry/optimization/dev/BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none
