Repository RobotLocomotion/drake, pull requests merged in 2022-03, with the labels that each got.

#16673 [yaml] Remove deprecated functions 2022-03
  bindings/pydrake/BUILD.bazel
  common/yaml/BUILD.bazel
  common/yaml/test/yaml_read_archive_deprecated_test.cc
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_read_archive.cc
  common/yaml/yaml_read_archive.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#16674 Remove deprecated package.xml files 2022-03
  examples/atlas/package.xml
  examples/manipulation_station/models/package.xml
  manipulation/models/allegro_hand_description/package.xml
  manipulation/models/franka_description/LICENSE.TXT
  manipulation/models/franka_description/package.xml
  manipulation/models/iiwa_description/package.xml
  manipulation/models/jaco_description/LICENSE.TXT
  manipulation/models/jaco_description/package.xml
  manipulation/models/realsense2_description/test/realsense_parse_test.cc
  manipulation/models/wsg_50_description/package.xml
  manipulation/models/ycb/package.xml
  multibody/parsing/package_map.h
  multibody/parsing/parser.cc
  multibody/parsing/test/parser_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#16685 Upgrade externals to latest
  tools/workspace/bazel_skylib/repository.bzl
  tools/workspace/buildifier/repository.bzl
  tools/workspace/dm_control/repository.bzl
  tools/workspace/github3_py/repository.bzl
  tools/workspace/petsc/patches/sbaijfact2.patch
  tools/workspace/petsc/repository.bzl
  tools/workspace/ros_xacro/repository.bzl
Labels: priority: low, status: commits are properly curated, status: single reviewer ok, release notes: yes

#16671 [systems] Mark simulator_gflags as internal
  examples/hydroelastic/ball_plate/ball_plate_run_dynamics.cc
  examples/mass_spring_cloth/run_cloth_spring_model.cc
  examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
  systems/analysis/simulator_gflags.cc
  systems/analysis/simulator_gflags.h
  systems/analysis/test/simulator_gflags_main.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#16670 [geometry] Add cleanup logic for unexpected websocket thread exit
  geometry/BUILD.bazel
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/test/meshcat_test.cc
Labels: priority: medium, release notes: yes

#16688 Fix noncompliant name kInfeasible_Or_Unbounded
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc
  solvers/BUILD.bazel
  solvers/gurobi_solver.cc
  solvers/solution_result.cc
  solvers/solution_result.h
  solvers/test/diagonally_dominant_matrix_test.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/mathematical_program_result_test.cc
  solvers/test/mixed_integer_rotation_constraint_test.cc
  solvers/test/non_convex_optimization_util_test.cc
  solvers/test/scaled_diagonally_dominant_matrix_test.cc
Labels: priority: low, component: mathematical program, release notes: newly deprecated, release notes: yes

#16680 [geometry/optimization] Enable linear costs in GraphOfConvexSets
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: yes

#16679 [solvers] Add PerspectiveQuadraticCost and include in GraphOfConvexSets cost options
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
  solvers/cost.cc
  solvers/cost.h
  solvers/test/cost_test.cc
Labels: release notes: yes

#16692 [solvers] Print more details for parameterized test cases
  solvers/test/linear_program_examples.cc
  solvers/test/linear_program_examples.h
  solvers/test/optimization_examples.cc
  solvers/test/optimization_examples.h
  solvers/test/quadratic_program_examples.cc
  solvers/test/quadratic_program_examples.h
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/second_order_cone_program_examples.h
Labels: priority: low, release notes: none

#16652 Allow external fmt, spdlog
  BUILD.bazel
  CMakeLists.txt
  cmake/external/workspace/fmt/BUILD.bazel.in
  cmake/external/workspace/spdlog/BUILD.bazel.in
  tools/workspace/cmake_util.bzl
Labels: priority: high, release notes: yes

#16668 [examples: hydroelastic] Adds Spatula Slip Example
  examples/BUILD.bazel
  examples/hydroelastic/spatula_slip_control/BUILD.bazel
  examples/hydroelastic/spatula_slip_control/README.md
  examples/hydroelastic/spatula_slip_control/images/spatula_1.jpg
  examples/hydroelastic/spatula_slip_control/images/spatula_2.jpg
  examples/hydroelastic/spatula_slip_control/models/schunk_wsg_50_hydro_bubble.sdf
  examples/hydroelastic/spatula_slip_control/models/spatula.sdf
  examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc
  tools/install/install_data.bzl
  tools/workspace/models/files.bzl
  tools/workspace/models/package.BUILD.bazel
  tools/workspace/models/repository.bzl
Labels: status: squashing now, release notes: yes

#16696 Remove unused model.config files
  examples/atlas/sdf/block_angle_steps_1/model.config
  examples/atlas/sdf/block_angle_steps_2/model.config
  examples/atlas/sdf/block_level_steps_1/model.config
  examples/atlas/sdf/block_level_steps_2/model.config
  examples/atlas/sdf/cinder_block_2/model.config
  examples/atlas/sdf/cinder_block_wide/model.config
  examples/atlas/sdf/ground_plane/model.config
  examples/atlas/sdf/sun/model.config
  examples/kuka_iiwa_arm/models/README.md
  examples/kuka_iiwa_arm/models/desk/model.config
  examples/kuka_iiwa_arm/models/table/model.config
  manipulation/models/iiwa_description/model.config
  manipulation/models/wsg_50_description/BUILD.bazel
  manipulation/models/wsg_50_description/LICENSE.TXT
  manipulation/models/wsg_50_description/README.md
  manipulation/models/wsg_50_description/model.config
Labels: priority: low, status: single reviewer ok, release notes: yes

#16698 [pydrake/trajectories] Make BsplineTrajectory picklable
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
Labels: release notes: yes

#16700 Allow external Eigen3
  CMakeLists.txt
  cmake/external/workspace/eigen/BUILD.bazel.in
Labels: release notes: yes

#16694 [SAP] ContactProblemGraph provides participating cliques
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/contact_problem_graph.cc
  multibody/contact_solvers/sap/contact_problem_graph.h
  multibody/contact_solvers/sap/partial_permutation.cc
  multibody/contact_solvers/sap/partial_permutation.h
  multibody/contact_solvers/sap/test/contact_problem_graph_test.cc
  multibody/contact_solvers/sap/test/partial_permutation_test.cc
Labels: status: squashing now, release notes: none

#16705 [multibody] Correct documentation of default set_contact_model()
  multibody/plant/multibody_plant.h
Labels: priority: high, type: documentation, team: dynamics, status: single reviewer ok, release notes: none

#16601 [doc] Add release notes v1.0.0
  bindings/pydrake/tutorials.py
  doc/_pages/from_binary.md
  doc/_pages/release_playbook.md
  doc/_release-notes/v1.0.0.md
  tools/release_engineering/download_release_candidate.py
  tools/release_engineering/relnotes.py
  tutorials/README.md
Labels: status: single reviewer ok, release notes: none

#16697 [SAP] Introduces SapConstraintBundle
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_constraint_bundle.cc
  multibody/contact_solvers/sap/sap_constraint_bundle.h
  multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc
Labels: team: dynamics, status: squashing now, release notes: none

#16653 [fem] Add FemState and FemStateManager
  multibody/fem/BUILD.bazel
  multibody/fem/fem_indexes.h
  multibody/fem/fem_state.cc
  multibody/fem/fem_state.h
  multibody/fem/fem_state_system.cc
  multibody/fem/fem_state_system.h
  multibody/fem/test/fem_state_system_test.cc
  multibody/fem/test/fem_state_test.cc
Labels: priority: high, release notes: none, component: softsim fem

#16703 [geometry] Fix Meshcat crash on unknown message
  geometry/meshcat.cc
  geometry/test/meshcat_test.cc
  geometry/test/meshcat_websocket_client.py
Labels: priority: medium, release notes: yes

#16707 [wheel] Add missing apt-get update
  tools/wheel/image/provision-python.sh
Labels: priority: low, release notes: none

#16686 [workspace] Upgrade scs to latest release 3.2.0
  solvers/scs_solver.cc
  solvers/test/optimization_examples.cc
  solvers/test/scs_solver_test.cc
  tools/workspace/scs/repository.bzl
Labels: priority: low, release notes: yes

#16701 [workspace] Build yaml-cpp from source
  BUILD.bazel
  common/yaml/BUILD.bazel
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_write_archive.cc
  examples/acrobot/BUILD.bazel
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/binary_distribution/packages-focal.txt
  third_party/com_github_jbeder_yaml_cpp/BUILD.bazel
  third_party/com_github_jbeder_yaml_cpp/LICENSE
  third_party/com_github_jbeder_yaml_cpp/include/yaml-cpp/emitfromevents.h
  third_party/com_github_jbeder_yaml_cpp/src/emitfromevents.cpp
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/drake-config.cmake
  tools/install/libdrake/test/header_dependency_test.py
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/yaml-cpp.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/yaml_cpp/emit-local-tag.patch
  tools/workspace/yaml_cpp/package-macos.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
  tools/workspace/yaml_cpp/package.BUILD.bazel
  tools/workspace/yaml_cpp/repository.bzl
Labels: priority: low, release notes: yes

#16720 [symbolic] ToLatex displays matrix/vector variables using subscript for indices
  common/symbolic_latex.cc
  common/test/symbolic_latex_test.cc
Labels: release notes: yes

#16714 [fem] Add discrete time integrator
  multibody/fem/BUILD.bazel
  multibody/fem/discrete_time_integrator.cc
  multibody/fem/discrete_time_integrator.h
  multibody/fem/test/discrete_time_integrator_test.cc
Labels: release notes: none, component: softsim fem

#16691 New Frame methods CalcRelativeSpatialVelocity(), CalcRelativeSpatialVelocityInWorld().
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/test/frame_kinematics_test.cc
  multibody/tree/frame.h
Labels: type: feature request, team: dynamics, priority: medium, status: squashing now, release notes: yes

#16718 [pydrake] Add DefAttributesUsingSerialize helper function
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/serialize_pybind.h
  bindings/pydrake/common/test/serialize_pybind_test.py
  bindings/pydrake/common/test/serialize_test_util_py.cc
  tools/workspace/pybind11/mkdoc.py
  tools/workspace/pybind11/test/sample_header.h
  tools/workspace/pybind11/test/sample_header_class_coverage_expected.csv
  tools/workspace/pybind11/test/sample_header_documentation.expected.h
  tools/workspace/pybind11/test/sample_header_documentation_pybind_expected.xml
  tools/workspace/pybind11/test/sample_header_file_coverage_expected.csv
Labels: priority: medium, release notes: yes

#16721 [pydrake] add bindings for BsplineBasis::EvaluateCurve
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
Labels: status: single reviewer ok, release notes: yes

#16704 [systems/analysis] Implements RegionOfAttraction for implicit dynamics
  systems/analysis/BUILD.bazel
  systems/analysis/region_of_attraction.cc
  systems/analysis/region_of_attraction.h
  systems/analysis/test/region_of_attraction_test.cc
Labels: release notes: yes

#16728 Revert "[workspace] Build yaml-cpp from source"
  BUILD.bazel
  common/yaml/BUILD.bazel
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_write_archive.cc
  examples/acrobot/BUILD.bazel
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/binary_distribution/packages-focal.txt
  third_party/com_github_jbeder_yaml_cpp/BUILD.bazel
  third_party/com_github_jbeder_yaml_cpp/LICENSE
  third_party/com_github_jbeder_yaml_cpp/include/yaml-cpp/emitfromevents.h
  third_party/com_github_jbeder_yaml_cpp/src/emitfromevents.cpp
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/drake-config.cmake
  tools/install/libdrake/test/header_dependency_test.py
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/yaml-cpp.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/yaml_cpp/emit-local-tag.patch
  tools/workspace/yaml_cpp/package-macos.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
  tools/workspace/yaml_cpp/package.BUILD.bazel
  tools/workspace/yaml_cpp/repository.bzl
Labels: priority: emergency, status: single reviewer ok, release notes: yes

#16710 [doc] Update wheel release playbook to ensure fresh base images
  doc/_pages/release_playbook.md
  tools/wheel/README.rst
  tools/wheel/build-wheels
Labels: priority: low, status: single reviewer ok, release notes: none

#16717 [pydrake] Add bindings for SimulatorConfig, MultibodyPlantConfig
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/schema_py.cc
  bindings/pydrake/common/test/schema_test.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
Labels: priority: low, release notes: yes

#16724 [pydrake] Ensure GIL is locked when logging from a C++ worker thread
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/text_logging_gil_test.py
  bindings/pydrake/common/test/text_logging_test_py.cc
  bindings/pydrake/common/text_logging_pybind.cc
Labels: priority: medium, release notes: yes

#16695 [geometry] Denote the Meshcat worker thread's lifecycle with an enum
  geometry/meshcat.cc
Labels: priority: low, release notes: none

#16592 [workspace] remove scipy.interpolate dependency
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_resample_interp1d.py
  bindings/pydrake/systems/pyplot_visualizer.py
  bindings/pydrake/systems/test/_resample_log_interp1d_test.py
Labels: release notes: none

#16725 MultibodyTreeTopology provides per-tree information.
  multibody/tree/multibody_tree_indexes.h
  multibody/tree/multibody_tree_topology.h
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: team: dynamics, release notes: none

#16702 [geometry/dev] introduce HttpService helper interface
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/http_service.cc
  geometry/render/dev/http_service.h
  geometry/render/dev/test/http_service_test.cc
Labels: status: single reviewer ok, release notes: none

#16726 [geometry] Fix Meshcat crash with duplicated controls names
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/test/meshcat_test.cc
Labels: priority: medium, release notes: yes

#16712 [fem] Add FemElement
  multibody/fem/BUILD.bazel
  multibody/fem/fem_element.cc
  multibody/fem/fem_element.h
  multibody/fem/fem_indexes.h
  multibody/fem/test/dummy_element.cc
  multibody/fem/test/dummy_element.h
  multibody/fem/test/fem_element_test.cc
  multibody/fem/test/fem_state_test.cc
Labels: release notes: none, component: softsim fem

#16730 [geometry] In meshcat, use logic_error not out_of_range
  geometry/meshcat.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#16731 [pydrake] Fix race condition in text_logging_gil_test
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/text_logging_test_py.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#16734 [fix] Revert a git mishap
  multibody/fem/discrete_time_integrator.cc
  multibody/fem/discrete_time_integrator.h
  multibody/fem/test/discrete_time_integrator_test.cc
Labels: status: single reviewer ok, release notes: none, component: softsim fem

#16715 [SAP] Implements contact constraint.
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_friction_cone_constraint.cc
  multibody/contact_solvers/sap/sap_friction_cone_constraint.h
  multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
Labels: team: dynamics, status: squashing now, release notes: none

#16687 [parsing] Port URDF diagnostics to policy: first steps
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/parser.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/parser_test.cc
Labels: release notes: none

#16713 [SAP] Implements SapModel.
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_model.cc
  multibody/contact_solvers/sap/sap_model.h
  multibody/contact_solvers/sap/test/sap_model_test.cc
Labels: team: dynamics, release notes: none

#16723 [geometry/dev] add HttpServiceCurl implementation
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/http_service_curl.cc
  geometry/render/dev/http_service_curl.h
  geometry/render/dev/test/http_service_curl_test.cc
Labels: status: single reviewer ok, release notes: none

#16754 [manipulation_station] Remove the camera mesh from self-perception
  examples/manipulation_station/manipulation_station.cc
Labels: priority: high, status: single reviewer ok, release notes: yes

#16743 [parsing] Introduce multibody parser manual test program
  multibody/parsing/BUILD.bazel
  multibody/parsing/test/parser_manual_test.cc
Labels: release notes: none

#16741 [common] Deprecate TrigPoly
  common/test/trig_poly_test.cc
  common/trig_poly.h
  solvers/system_identification.cc
  solvers/system_identification.h
  solvers/test/system_identification_test.cc
Labels: release notes: newly deprecated

#16755 [fem] Move documentation of stiffness matrix out of dev
  multibody/fem/doc/stiffness_matrix.pdf
  multibody/fem/doc/stiffness_matrix.tex
Labels: priority: low, release notes: none, component: softsim fem

#16740 jupyter: Pull in minor Bazel improvements
  tools/jupyter/jupyter_bazel.py
  tools/jupyter/jupyter_py.bzl
Labels: priority: low, release notes: none

#16729 Add ability to create a VPolytope from a non-minimal set of vertices
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: release notes: yes

#16756 [workspace] Build yaml-cpp from source
  BUILD.bazel
  common/yaml/BUILD.bazel
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_read_archive.cc
  common/yaml/yaml_write_archive.cc
  examples/acrobot/BUILD.bazel
  third_party/com_github_jbeder_yaml_cpp/BUILD.bazel
  third_party/com_github_jbeder_yaml_cpp/LICENSE
  third_party/com_github_jbeder_yaml_cpp/include/yaml-cpp/emitfromevents.h
  third_party/com_github_jbeder_yaml_cpp/src/emitfromevents.cpp
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/drake-config.cmake
  tools/install/libdrake/test/header_dependency_test.py
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/yaml-cpp.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/yaml_cpp/package-macos.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
  tools/workspace/yaml_cpp/repository.bzl
  tools/workspace/yaml_cpp_internal/BUILD.bazel
  tools/workspace/yaml_cpp_internal/emit-local-tag.patch
  tools/workspace/yaml_cpp_internal/package.BUILD.bazel
  tools/workspace/yaml_cpp_internal/repository.bzl
  tools/workspace/yaml_cpp_internal/vendor_cxx.py
Labels: priority: low, release notes: newly deprecated

#16758 [fem] Remove pdf file from documentation
  multibody/fem/doc/stiffness_matrix.pdf
  multibody/fem/doc/stiffness_matrix.tex
  multibody/fixed_fem/dev/doc/stretch_bar_test.pdf
Labels: priority: low, status: single reviewer ok, release notes: none, component: softsim fem

#16752 Simplify several third-party inclusions
  tools/workspace/double_conversion/package-ubuntu.BUILD.bazel
  tools/workspace/double_conversion/package.BUILD.bazel
  tools/workspace/double_conversion/repository.bzl
  tools/workspace/libjpeg/package-macos.BUILD.bazel
  tools/workspace/libjpeg/package.BUILD.bazel
  tools/workspace/libjpeg/repository.bzl
  tools/workspace/suitesparse/repository.bzl
Labels: release notes: none

#16733 [fem] Add VolumetricElement
  multibody/fem/BUILD.bazel
  multibody/fem/fem_element.h
  multibody/fem/test/dummy_element.h
  multibody/fem/test/fem_element_test.cc
  multibody/fem/test/volumetric_element_test.cc
  multibody/fem/volumetric_element.cc
  multibody/fem/volumetric_element.h
Labels: release notes: none, component: softsim fem

#16757 [geometry] Enable valgrind on Meshcat testing
  geometry/BUILD.bazel
  geometry/test/meshcat_test.cc
  geometry/test/meshcat_websocket_client.py
  tools/dynamic_analysis/drd.sh
  tools/dynamic_analysis/helgrind.sh
  tools/dynamic_analysis/valgrind.sh
Labels: priority: low, status: single reviewer ok, release notes: none

#16737 [fem] Add acceleration and velocity newmark schemes
  multibody/fem/BUILD.bazel
  multibody/fem/acceleration_newmark_scheme.cc
  multibody/fem/acceleration_newmark_scheme.h
  multibody/fem/newmark_scheme.h
  multibody/fem/test/acceleration_newmark_scheme_test.cc
  multibody/fem/test/velocity_newmark_scheme_test.cc
  multibody/fem/velocity_newmark_scheme.cc
  multibody/fem/velocity_newmark_scheme.h
Labels: priority: low, release notes: none, component: softsim fem

#16763 [geometry] A bit of house cleaning for Meshcat
  geometry/BUILD.bazel
  geometry/meshcat.cc
  geometry/test/meshcat_websocket_client.py
Labels: priority: medium, status: single reviewer ok, release notes: none

#16736 [solvers] In CsdpSolver, use longjmp to avoid full-program exits
  solvers/BUILD.bazel
  solvers/csdp_cpp_wrapper.cc
  solvers/csdp_cpp_wrapper.h
  solvers/csdp_solver.cc
  solvers/csdp_solver_error_handling.cc
  solvers/csdp_solver_error_handling.h
  solvers/csdp_solver_internal.cc
  solvers/csdp_solver_internal.h
  solvers/test/csdp_cpp_wrapper_test.cc
  solvers/test/csdp_solver_internal_test.cc
  solvers/test/sdpa_free_format_test.cc
  tools/workspace/csdp/package.BUILD.bazel
  tools/workspace/csdp/patches/params_pathname.patch
  tools/workspace/csdp/patches/printlevel.patch
  tools/workspace/csdp/repository.bzl
Labels: priority: low, release notes: yes

#16587 Enable split debug symbols on Ubuntu
  CMakeLists.txt
  tools/dynamic_analysis/bazel.rc
  tools/ubuntu-bionic.bazelrc
Labels: release notes: yes

#16767 CMake: --fission needs to be a build argument
  CMakeLists.txt
Labels: priority: emergency, release notes: none

#16659 [geometry] Be sure to print exceptions from Meshcat's worker thread
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/test/meshcat_test.cc
  geometry/test/meshcat_websocket_client.py
Labels: priority: low, release notes: yes

#16777 Removes unnecessary cone constraint smoothness specification
  multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
Labels: team: dynamics, component: multibody plant, release notes: none

#16770 [parsing] Split TinyXml2Diagnostic to its own module
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_tinyxml2_diagnostic.cc
  multibody/parsing/detail_tinyxml2_diagnostic.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_tinyxml2_diagnostic_test.cc
Labels: release notes: none

#16776 [geometry/dev] make HttpService stateless
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/http_service.cc
  geometry/render/dev/http_service.h
  geometry/render/dev/http_service_curl.cc
  geometry/render/dev/http_service_curl.h
  geometry/render/dev/test/http_service_curl_test.cc
  geometry/render/dev/test/http_service_test.cc
Labels: status: single reviewer ok, release notes: none

#16788 [tools] Don't enable (split) debug symbols in release builds
  tools/ubuntu-bionic.bazelrc
Labels: priority: high, status: single reviewer ok, release notes: yes

#16751 [geometry/dev] Use new HttpService Interface with GLTF
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/render_client.cc
  geometry/render/dev/render_client.h
  geometry/render/dev/render_engine_gltf_client.cc
  geometry/render/dev/render_engine_gltf_client.h
  geometry/render/dev/test/render_client_test.cc
  geometry/render/dev/test_utilities/BUILD.bazel
  geometry/render/dev/test_utilities/test_png.cc
  geometry/render/dev/test_utilities/test_png.h
  geometry/render/dev/test_utilities/test_tiff.cc
  geometry/render/dev/test_utilities/test_tiff.h
Labels: status: single reviewer ok, release notes: none

#16716 upgrade gurobi to 9.5.1 (which includes macos arm64 support)
  CMakeLists.txt
  doc/_pages/bazel.md
  doc/_pages/python_bindings.md
  solvers/gurobi_solver.cc
  solvers/gurobi_solver.h
  solvers/mathematical_program_result.h
  solvers/solver_options.h
  solvers/test/gurobi_solver_test.cc
  tools/bazel.rc
  tools/dynamic_analysis/tsan.supp
  tools/workspace/gurobi/package-macos.BUILD.bazel.in
  tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in
  tools/workspace/gurobi/repository.bzl
Labels: release notes: breaking change

#16792 [inverse_kinematics] minor cleanup of MinimumDistanceConstraint documentation
  multibody/inverse_kinematics/minimum_distance_constraint.h
  solvers/minimum_value_constraint.h
Labels: release notes: none

#16794 CMake: Update Guorbi version in FindGurobi module
  cmake/modules/FindGurobi.cmake
Labels: priority: emergency, status: single reviewer ok, release notes: none

#16790 [parsing] Add a fixture to detail_sdf_parser_test
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#16778 [solvers] Combine MathematicalProgram::AddConstraint overloads
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  solvers/create_constraint.cc
  solvers/create_constraint.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
Labels: priority: medium, release notes: yes

#16797 [parsing] Fix dangling reference to destroyed stack variable
  multibody/parsing/detail_sdf_parser.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#16786 [parsing] Remove deprecated `drake:elastic_modulus`
  multibody/parsing/detail_common.cc
  multibody/parsing/test/detail_common_test.cc
Labels: release notes: removal of deprecated

#16772 [workspace] Don't build libsdformat's URDF parser
  multibody/parsing/detail_common.h
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  tools/workspace/sdformat/package.BUILD.bazel
  tools/workspace/sdformat/patches/no_urdf.patch
  tools/workspace/sdformat/repository.bzl
Labels: priority: low, release notes: yes

#16789 [multibody] Install deprecated contact_results_to_meshcat.h header
  multibody/contact_solvers/sap/BUILD.bazel
  tools/install/libdrake/build_components.bzl
Labels: priority: low, status: single reviewer ok, release notes: yes

#16795 Revert "[geometry/dev] Use new HttpService Interface with GLTF"
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/render_client.cc
  geometry/render/dev/render_client.h
  geometry/render/dev/render_engine_gltf_client.cc
  geometry/render/dev/render_engine_gltf_client.h
  geometry/render/dev/test/render_client_test.cc
  geometry/render/dev/test_utilities/BUILD.bazel
  geometry/render/dev/test_utilities/test_png.cc
  geometry/render/dev/test_utilities/test_png.h
  geometry/render/dev/test_utilities/test_tiff.cc
  geometry/render/dev/test_utilities/test_tiff.h
Labels: priority: emergency, release notes: none

#16791 [parsing] Stop using mutable globals
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  tools/workspace/sdformat/patches/fix_broken_config.patch
  tools/workspace/sdformat/patches/no_global_config.patch
  tools/workspace/sdformat/repository.bzl
Labels: priority: medium, release notes: yes

#16803 CMake: Update gurobi install directory on Mac
  cmake/modules/FindGurobi.cmake
Labels: status: single reviewer ok, release notes: yes

#16802 [geometry/dev] Use new HttpService Interface with GLTF
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/render_client.cc
  geometry/render/dev/render_client.h
  geometry/render/dev/render_engine_gltf_client.cc
  geometry/render/dev/render_engine_gltf_client.h
  geometry/render/dev/test/render_client_test.cc
  geometry/render/dev/test_utilities/BUILD.bazel
  geometry/render/dev/test_utilities/test_png.cc
  geometry/render/dev/test_utilities/test_png.h
  geometry/render/dev/test_utilities/test_tiff.cc
  geometry/render/dev/test_utilities/test_tiff.h
Labels: status: single reviewer ok, release notes: none

#16804 [setup] Adjust Deepnote NginX config for longer timeouts
  setup/deepnote/nginx-meshcat-proxy.conf
Labels: priority: medium, status: single reviewer ok, release notes: none

#16806 [solvers] fix broken docstring for SetVariableScaling
  solvers/mathematical_program.h
Labels: status: single reviewer ok, release notes: none

#16807 [examples] add missing ConnectMeshcatVisualizer import
  examples/manipulation_station/joint_teleop.py
Labels: status: single reviewer ok, release notes: none

#16799 [parsing] Start to add DiagnosticPolicy for detail_sdf_parser
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_sdf_parser.h
  multibody/parsing/parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/parser_test.cc
  multibody/parsing/test/sdf_parser_test/bad.forced_nesting_sdf
  multibody/parsing/test/sdf_parser_test/bad.urdf
Labels: priority: medium, release notes: none

#16801 [yaml] Extract Options struct out of YamlReadArchive
  common/yaml/BUILD.bazel
  common/yaml/test/yaml_io_test.cc
  common/yaml/test/yaml_performance_test.cc
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_io.h
  common/yaml/yaml_io_options.cc
  common/yaml/yaml_io_options.h
  common/yaml/yaml_read_archive.cc
  common/yaml/yaml_read_archive.h
Labels: priority: low, status: single reviewer ok, release notes: yes

#16805 [pydrake] StartMeshcat uses NginX when on Deepnote
  bindings/pydrake/_geometry_extra.py
Labels: priority: medium, release notes: yes

#16810 [parsing] Use DiagnosticPolicy instead of log_once in SDFormat
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/test/detail_common_test.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
Labels: priority: medium, release notes: none

#16808 [geometry] Repeated Meshcat::AddButton calls reset the click count
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/test/meshcat_test.cc
Labels: priority: low, release notes: yes

#16813 ParseConstraint throws error for false formula.
  solvers/BUILD.bazel
  solvers/create_constraint.cc
  solvers/create_constraint.h
  solvers/test/create_constraint_test.cc
Labels: release notes: yes

#16793 [geometry/dev] Add RenderEngineGltfClient unit tests.
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/render_engine_gltf_client.cc
  geometry/render/dev/render_engine_gltf_client.h
  geometry/render/dev/test/render_engine_gltf_client_test.cc
Labels: status: single reviewer ok, release notes: none

#16821 [parsing] Allow linear bushing parse to fail
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
Labels: release notes: none

#16602 [release_engineering] Add a tool to convert tgz => deb
  tools/release_engineering/dev/BUILD.bazel
  tools/release_engineering/dev/debian/changelog.in
  tools/release_engineering/dev/debian/control
  tools/release_engineering/dev/debian/copyright
  tools/release_engineering/dev/repack_deb.py
Labels: priority: low, release notes: none

#16823 update license year
  LICENSE.TXT
Labels: component: distribution, type: cleanup, team: robot locomotion group, status: single reviewer ok, release notes: none

#16827 Change comment openers and replace int32_t with int
  geometry/render/dev/http_service.h
  geometry/render/dev/http_service_curl.cc
  geometry/render/dev/http_service_curl.h
  geometry/render/dev/render_client.cc
  geometry/render/dev/render_client.h
  geometry/render/dev/render_engine_gltf_client_factory.h
  geometry/render/dev/test/http_service_curl_test.cc
  geometry/render/dev/test/http_service_test.cc
  geometry/render/dev/test/render_client_test.cc
  geometry/render/dev/test/render_engine_gltf_client_test.cc
Labels: release notes: none

#16817 [doc] Add tips for profiling
  doc/_pages/developers.md
  doc/_pages/profiling.md
  geometry/profiling/README.md
Labels: priority: low, release notes: none

#16826 [solvers] Clean up CheckBinding code style
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
  systems/trajectory_optimization/test/multiple_shooting_test.cc
Labels: priority: medium, release notes: none

#16819 [parsing] Route SDFormat warnings through DiagnosticPolicy
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  tools/workspace/sdformat/patches/deprecation_unit_testing.patch
  tools/workspace/sdformat/repository.bzl
Labels: priority: medium, release notes: yes

#16824 [parsing] Introduce class into urdf parser implementation
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: release notes: none

#16699 Update SpatialAcceleration methods to parallel SpatialVelocity.
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
  multibody/math/spatial_acceleration.h
  multibody/math/spatial_velocity.h
  multibody/tree/body_node.h
Labels: type: documentation, team: dynamics, priority: medium, status: squashing now, component: multibody plant, release notes: newly deprecated

#16765 Remove scipy.spatial.ConvexHull dependency
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: release notes: yes

#16762 Python bindings for LcmPublisherSystem and Simulator
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  bindings/pydrake/systems/test/lcm_test.py
Labels: status: squashing now, component: pydrake, release notes: yes

#16831 [doc] Split tutorial docs into user docs vs developer docs
  tutorials/README.md
  tutorials/_developers.md
Labels: priority: medium, status: single reviewer ok, release notes: none

#16830 [pydrake] Remove stray print in StartMeshcat
  bindings/pydrake/_geometry_extra.py
Labels: priority: medium, status: single reviewer ok, release notes: yes

#16820 [parsing] Use DiagnosticPolicy in ResolveUri
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/detail_path_utils.h
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/test/detail_path_utils_test.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/parser_test.cc
Labels: priority: low, release notes: yes

#16760 Create new method Frame::CalcSpatialAcceleration().
  multibody/plant/test/frame_kinematics_test.cc
  multibody/tree/frame.h
Labels: type: feature request, team: dynamics, priority: medium, status: squashing now, release notes: yes

#16825 MathematicalProgram ignores the constraint if it were empty.
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: release notes: yes

#16840 [pydrake] Stub out scipy.sparse for unit testing
  bindings/pydrake/common/test_utilities/BUILD.bazel
  bindings/pydrake/common/test_utilities/scipy_stub/scipy/__init__.py
  bindings/pydrake/common/test_utilities/scipy_stub/scipy/sparse/__init__.py
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/test/csdp_solver_test.py
Labels: priority: medium, release notes: newly deprecated

#16829 [parsing] Port remainder of detail_urdf_parser to diagnostics
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: release notes: none

#16812 [controllers] Implements the square-root form of finite-horizon LQR
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/test/controllers_test.py
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/piecewise_polynomial.cc
  common/trajectories/piecewise_polynomial.h
  common/trajectories/test/piecewise_polynomial_test.cc
  systems/controllers/finite_horizon_linear_quadratic_regulator.cc
  systems/controllers/finite_horizon_linear_quadratic_regulator.h
  systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Labels: release notes: yes

#16849 [tools] Add more known-defects to header lint checks
  tools/install/libdrake/header_lint.bzl
Labels: priority: high, status: single reviewer ok, release notes: none

#16837 Remove uses of interactive matplotlib from tutorials to support deepnote/colab
  tutorials/dynamical_systems.ipynb
  tutorials/mathematical_program.ipynb
  tutorials/nonlinear_program.ipynb
Labels: priority: high

#16838 [tutorials] Add linter for required styles choices
  tutorials/BUILD.bazel
  tutorials/_developers.md
  tutorials/debug_mathematical_program.ipynb
  tutorials/dynamical_systems.ipynb
  tutorials/index.ipynb
  tutorials/linear_program.ipynb
  tutorials/mathematical_program.ipynb
  tutorials/mathematical_program_multibody_plant.ipynb
  tutorials/multibody_plant_autodiff_mass.ipynb
  tutorials/pyplot_animation_multibody_plant.ipynb
  tutorials/quadratic_program.ipynb
  tutorials/rendering_multibody_plant.ipynb
  tutorials/solver_parameters.ipynb
  tutorials/sum_of_squares_optimization.ipynb
  tutorials/test/notebook_lint_test.py
  tutorials/updating_costs_and_constraints.ipynb
Labels: priority: medium, release notes: none

#16593 [multibody/parsing] Splitting up existing ModelDirectives tests
  multibody/parsing/BUILD.bazel
  multibody/parsing/test/process_model_directives_test.cc
  multibody/parsing/test/process_model_directives_test/add_frame_without_model_namespace.yaml
  multibody/parsing/test/process_model_directives_test/add_scoped_mid.yaml
  multibody/parsing/test/process_model_directives_test/add_scoped_top.yaml
  multibody/parsing/test/process_model_directives_test/inject_frames.yaml
  multibody/parsing/test/process_model_directives_test/test_backreferences.yaml
  multibody/parsing/test/scoped_names_model.sdf
  multibody/parsing/test/scoped_names_test.cc
Labels: release notes: none

#16850 [tools] Defer header_lint failures to lint-time, not build-time
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/header_lint.bzl
Labels: priority: low, release notes: none

#16853 [parsing] Hotfix unit test for macOS
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#16835 [multibody] Add `MultibodyPlant::GetEffortLowerLimits` (and friends)
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/joint_actuator.cc
  multibody/tree/joint_actuator.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/joint_actuator_test.cc
  multibody/tree/test/multibody_tree_test.cc
Labels: release notes: yes

#16846 [geometry] Update RenderEngineVtk and remove private friendship
  geometry/render/dev/render_engine_gltf_client.cc
  geometry/render/dev/render_engine_gltf_client.h
  geometry/render/dev/render_engine_gltf_client_factory.cc
  geometry/render/dev/test/render_engine_gltf_client_test.cc
  geometry/render/render_engine_vtk.cc
  geometry/render/render_engine_vtk.h
Labels: release notes: none

#16855 [geometry] Update function comments to use indicative mood
  geometry/render/dev/http_service.h
  geometry/render/dev/http_service_curl.cc
  geometry/render/dev/render_client.cc
  geometry/render/dev/render_client.h
  geometry/render/dev/render_engine_gltf_client.cc
  geometry/render/dev/render_engine_gltf_client.h
  geometry/render/dev/render_engine_vtk_minimal_example.cc
  geometry/render/dev/test/render_client_test.cc
  geometry/render/dev/test/render_engine_gltf_client_test.cc
  geometry/render/dev/test_utilities/test_png.cc
  geometry/render/dev/test_utilities/test_png.h
  geometry/render/dev/test_utilities/test_tiff.h
Labels: release notes: none

#16847 [trajopt] Add `MultipleShooting::AddConstraintToAllKnotPoints` variants
  bindings/pydrake/systems/test/trajectory_optimization_test.py
  bindings/pydrake/systems/trajectory_optimization_py.cc
  systems/trajectory_optimization/BUILD.bazel
  systems/trajectory_optimization/multiple_shooting.cc
  systems/trajectory_optimization/multiple_shooting.h
  systems/trajectory_optimization/sequential_expression_manager.cc
  systems/trajectory_optimization/sequential_expression_manager.h
  systems/trajectory_optimization/test/multiple_shooting_test.cc
  systems/trajectory_optimization/test/sequential_expression_manager_test.cc
Labels: release notes: yes

#16852 [geometry:drake_visualizer] Fix for disabling/enabling hydro contact plugin
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
Labels: type: bug, priority: high, team: dynamics, status: squashing now, component: geometry illustration, release notes: yes

#16859 [geometry/dev] Restructure glTF server / simulation targets
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/render_server/README.md
  geometry/render/dev/test/4_color_texture.png
  geometry/render/dev/test/gltf_render_server.py
  geometry/render/dev/test/gltf_render_server_backend.cc
  geometry/render/dev/test/run_simulation_and_render.cc
Labels: status: single reviewer ok, release notes: none

#16854 ParseConstraint ignores formula being always true.
  solvers/create_constraint.cc
  solvers/create_constraint.h
  solvers/test/create_constraint_test.cc
Labels: release notes: yes

#16860 [doc] Switch tutorial links to point to Deepnote
  doc/index.md
  tutorials/README.md
Labels: priority: medium, release notes: yes

#16857 [inverse kinematics] Add benchmark for position constraint.
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/position_constraint_benchmark.cc
Labels: release notes: none

#16867 [drake_visualizer] Fix message handling in hydro visualization
  tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
Labels: release notes: yes

#16800 [fem] Add FemModel and FemModelImpl
  multibody/fem/BUILD.bazel
  multibody/fem/fem_element.h
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
  multibody/fem/fem_model_impl.cc
  multibody/fem/fem_model_impl.h
  multibody/fem/fem_state.h
  multibody/fem/fem_state_system.cc
  multibody/fem/fem_state_system.h
  multibody/fem/test/acceleration_newmark_scheme_test.cc
  multibody/fem/test/dummy_model.cc
  multibody/fem/test/dummy_model.h
  multibody/fem/test/fem_model_test.cc
  multibody/fem/test/fem_state_system_test.cc
  multibody/fem/test/velocity_newmark_scheme_test.cc
Labels: release notes: none, component: softsim fem

#16771 [SAP] Implements missing features in SapModel
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_model.cc
  multibody/contact_solvers/sap/sap_model.h
  multibody/contact_solvers/sap/test/sap_model_test.cc
Labels: team: dynamics, release notes: none

#16781 [SAP] Computation of Jacobian blocks
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/test/compliant_contact_manager_test.cc
Labels: team: dynamics, component: multibody plant, release notes: none

#16843 [fem] Remove element index from FemElement
  multibody/fem/fem_element.h
  multibody/fem/fem_indexes.h
  multibody/fem/fem_model_impl.h
  multibody/fem/test/dummy_element.h
  multibody/fem/test/dummy_model.cc
  multibody/fem/test/fem_element_test.cc
  multibody/fem/test/volumetric_element_test.cc
  multibody/fem/volumetric_element.h
Labels: release notes: none, component: softsim fem

#16868 [geometry/dev] Move test_utilities to test
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/test/render_client_test.cc
  geometry/render/dev/test/render_engine_gltf_client_test.cc
  geometry/render/dev/test/test_png.cc
  geometry/render/dev/test/test_png.h
  geometry/render/dev/test/test_tiff.cc
  geometry/render/dev/test/test_tiff.h
  geometry/render/dev/test_utilities/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#16862 [doc] Add release notes v1.1.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.1.0.md
Labels: status: squashing now, release notes: none

#16878 setup: Upgrade recommended Bazel version to 5.1.0 for Linux
  doc/_pages/from_source.md
  setup/ubuntu/source_distribution/install_prereqs.sh
  tools/wheel/image/provision-base.sh
  tools/workspace/drake_visualizer/image/provision.sh
Labels: release notes: yes

#16818 Use correct indices for joint/body velocities
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/test/joint_locking_test.cc
Labels: type: bug, priority: high, team: dynamics, status: squashing now, component: multibody plant, release notes: yes

#16839 [fem] Add Dirichlet boundary conditions
  multibody/fem/BUILD.bazel
  multibody/fem/dirichlet_boundary_condition.cc
  multibody/fem/dirichlet_boundary_condition.h
  multibody/fem/test/dirichlet_boundary_condition_test.cc
Labels: release notes: none, component: softsim fem

#16864 [workspace] install flask for unit tests
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/render_server/README.md
  geometry/render/dev/test/flask_import_test.py
  setup/mac/source_distribution/requirements-test-only.txt
  setup/ubuntu/source_distribution/packages-bionic-test-only.txt
  setup/ubuntu/source_distribution/packages-focal-test-only.txt
Labels: release notes: none

#16884 [workspace] fix drake-visualizer for system jchart2d
  tools/workspace/drake_visualizer/image/build-lcm.sh
  tools/workspace/drake_visualizer/image/package.sh
  tools/workspace/drake_visualizer/image/prereqs
  tools/workspace/drake_visualizer/repository.bzl
Labels: priority: low, component: build system, release notes: none

#16874 Make SapContactProblem and friends clonable.
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/contact_problem_graph.cc
  multibody/contact_solvers/sap/contact_problem_graph.h
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/sap_contact_problem.h
  multibody/contact_solvers/sap/sap_friction_cone_constraint.h
  multibody/contact_solvers/sap/test/contact_problem_graph_test.cc
  multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc
  multibody/contact_solvers/sap/test/sap_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
  multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_model_test.cc
Labels: team: dynamics, release notes: none

#16880 Implements missing features in SapModel (cont.)
  multibody/contact_solvers/sap/sap_model.cc
  multibody/contact_solvers/sap/sap_model.h
  multibody/contact_solvers/sap/test/sap_model_test.cc
Labels: type: bug, team: dynamics, release notes: none

#16534 [examples] Ball-paddle with hydroelastics in Python.
  examples/hydroelastic/python_ball_paddle/BUILD.bazel
  examples/hydroelastic/python_ball_paddle/README.md
  examples/hydroelastic/python_ball_paddle/ball.sdf
  examples/hydroelastic/python_ball_paddle/contact_sim_demo.py
  examples/hydroelastic/python_ball_paddle/images/ball_paddle_corner.jpg
  examples/hydroelastic/python_ball_paddle/images/ball_paddle_default.jpg
  examples/hydroelastic/python_ball_paddle/images/ball_paddle_near_edge.jpg
  examples/hydroelastic/python_ball_paddle/images/drake_visualizer_hydroelastic_settings.jpg
  examples/hydroelastic/python_ball_paddle/paddle.sdf
Labels: priority: low, team: manipulation, team: dynamics, release notes: none

#16885 Upgrade externals to latest
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/bazel_skylib/repository.bzl
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/dm_control/repository.bzl
  tools/workspace/github3_py/repository.bzl
  tools/workspace/petsc/repository.bzl
  tools/workspace/rules_python/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: yes

#16888 [fem] Rename FemModel::ThrowModelDataIncompatible
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
Labels: status: single reviewer ok, release notes: none, component: softsim fem
