Repository RobotLocomotion/drake, pull requests merged in 2022-07, with the labels that each got.

#17487 [examples] Remove cassie AutoDiffXd change detector tests
  examples/multibody/cassie_benchmark/test/cassie_bench.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#17476 CompliantContactManager computes accelerations cache
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/test/compliant_contact_manager_test.cc
Labels: component: multibody plant, release notes: none

#17459 [systems] Remove deprecated code 2022-07
  systems/analysis/BUILD.bazel
  systems/analysis/antiderivative_function.h
  systems/analysis/initial_value_problem.cc
  systems/analysis/initial_value_problem.h
  systems/analysis/scalar_initial_value_problem.h
  systems/analysis/test/antiderivative_function_deprecated_test.cc
  systems/analysis/test/initial_value_problem_deprecated_test.cc
  systems/analysis/test/scalar_initial_value_problem_deprecated_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#17460 [solvers] Remove deprecated code 2022-07
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/_augmented_lagrangian_extra.py
  bindings/pydrake/solvers/augmented_lagrangian_py.cc
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/solvers/test/augmented_lagrangian_test.py
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/BUILD.bazel
  solvers/augmented_lagrangian.h
  solvers/solution_result.h
  solvers/system_identification.cc
  solvers/system_identification.h
  solvers/test/augmented_lagrangian_test.cc
  solvers/test/mathematical_program_result_test.cc
  solvers/test/system_identification_test.cc
Labels: priority: low, release notes: removal of deprecated

#17480 Update CMakeLists.txt to allow Jammy
  CMakeLists.txt
Labels: status: single reviewer ok, release notes: none

#17493 Fix more ibex on Jammy issues
  tools/workspace/ibex/include_limits.patch
Labels: release notes: none

#17465 [multibody/wing] Add more original reference for flat plate theory
  multibody/plant/wing.h
Labels: priority: low, type: documentation, component: multibody plant, release notes: none

#17461 [common,multibody,tools] Remove deprecated code 2022-07
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
  common/BUILD.bazel
  common/test/trig_poly_test.cc
  common/trig_poly.h
  multibody/math/spatial_acceleration.h
  tools/workspace/default.bzl
  tools/workspace/yaml_cpp/BUILD.bazel
  tools/workspace/yaml_cpp/package-macos.BUILD.bazel
  tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
  tools/workspace/yaml_cpp/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#17500 [misc] Tidy up weird spellings of AutoDiffXd
  geometry/proximity/distance_to_point_callback.h
  geometry/proximity/distance_to_shape_callback.h
  geometry/proximity/penetration_as_point_pair_callback.cc
  geometry/utilities.h
  multibody/benchmarks/acrobot/acrobot.cc
  systems/analysis/test/explicit_euler_integrator_test.cc
  systems/controllers/test/inverse_dynamics_test.cc
  systems/primitives/test/demultiplexer_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#17498 [common] Centralize Eigen minimum version requirement
  common/autodiff.h
  common/eigen_types.h
  tools/workspace/eigen/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#17499 [common] Deprecate autodiffxd_make_coherent
  common/BUILD.bazel
  common/autodiffxd_make_coherent.h
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#17502 [systems] Use InitializeAutoDiff instead of manual looping
  systems/analysis/implicit_integrator.cc
  systems/analysis/velocity_implicit_euler_integrator.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#17505 [build system] Update picosat to latest commit
  tools/dynamic_analysis/bazel.rc
  tools/workspace/picosat/repository.bzl
Labels: release notes: fix

#17501 [math] Avoid fixed-sized derivatives in quaternion_test
  math/test/quaternion_test.cc
Labels: priority: low, release notes: none

#17504 [inverse_kinematics] Update global IK
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/global_inverse_kinematics.cc
  multibody/inverse_kinematics/global_inverse_kinematics.h
  multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc
Labels: priority: medium, release notes: newly deprecated, component: planning and control, release notes: feature

#17510 [parsing] Add missed check in SDFormat drake:proximity_properties
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/sdf_parser_test/unsupported_elements.sdf
Labels: release notes: fix

#17484 [geometry] Simplify deformable mesh generation code
  geometry/BUILD.bazel
  geometry/make_mesh_for_deformable.cc
  geometry/make_mesh_for_deformable.h
  geometry/test/geometry_state_test.cc
  geometry/test/internal_geometry_test.cc
  geometry/test/make_mesh_for_deformable_test.cc
  geometry/test/scene_graph_test.cc
Labels: release notes: none

#17509 [workspace] Upgrade petsc to latest release v3.17.3
  tools/workspace/petsc/patches/mal.patch
  tools/workspace/petsc/repository.bzl
Labels: component: build system, release notes: fix

#17488 SAP with exact line search
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/sap_solver.h
  multibody/contact_solvers/sap/test/sap_solver_test.cc
  multibody/plant/test/compliant_contact_manager_test.cc
Labels: component: multibody plant, release notes: none

#17517 [yaml] Output special floating point values correctly
  common/yaml/test/yaml_write_archive_test.cc
  common/yaml/yaml_write_archive.h
Labels: priority: medium, release notes: fix

#16683 [primitives] Add performance binary for MultilayerPerceptron
  systems/benchmarking/BUILD.bazel
  systems/benchmarking/multilayer_perceptron_performance.cc
Labels: priority: low, release notes: feature

#17497 [common] Add and use MatrixLikewise sugar typedef
  common/eigen_types.h
  common/extract_double.h
  common/symbolic/expression/expression.h
  common/symbolic/polynomial.h
  common/symbolic/trigonometric_polynomial.h
  common/test/eigen_types_test.cc
  solvers/branch_and_bound.h
  solvers/mathematical_program.h
  solvers/mathematical_program_result.h
  solvers/test/branch_and_bound_test.cc
Labels: priority: low, release notes: feature

#17491 Replace sin/cos in a symbolic polynomial with half-angle rational functions
  common/symbolic/BUILD.bazel
  common/symbolic/test/trigonometric_polynomial_test.cc
  common/symbolic/trigonometric_polynomial.cc
  common/symbolic/trigonometric_polynomial.h
Labels: release notes: feature

#17512 Parse dissipation_time_scale for SAP.
  geometry/proximity_properties.cc
  geometry/proximity_properties.h
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/test/detail_common_test.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/multibody_plant.h
  multibody/plant/test/compliant_contact_manager_test.cc
Labels: component: multibody plant, release notes: feature

#17400 Option to choose the SAP solver
  examples/atlas/atlas_run_dynamics.cc
  examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_config.h
  multibody/plant/multibody_plant_config_functions.cc
  multibody/plant/multibody_plant_config_functions.h
  multibody/plant/test/multibody_plant_config_functions_test.cc
Labels: component: multibody plant, release notes: feature

#17526 [multibody] Move all benchmarks into one place
  examples/acrobot/BUILD.bazel
  examples/acrobot/README.md
  examples/acrobot/test/benchmark_autodiff_test.sh
  examples/multibody/cassie_benchmark/BUILD.bazel
  multibody/benchmarking/BUILD.bazel
  multibody/benchmarking/README.md
  multibody/benchmarking/acrobot.cc
  multibody/benchmarking/cassie.cc
  multibody/benchmarking/cassie_v2.urdf
  multibody/benchmarking/position_constraint.cc
  multibody/inverse_kinematics/BUILD.bazel
  tools/performance/BUILD.bazel
  tools/performance/README.md
Labels: priority: low, status: single reviewer ok, release notes: none

#17534 [tools] Don't rename github files or directories named "build"
  tools/workspace/github.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#17535 [benchmarking] Require an explicit choice for add_test_rule
  geometry/benchmarking/BUILD.bazel
  multibody/benchmarking/BUILD.bazel
  solvers/benchmarking/BUILD.bazel
  systems/benchmarking/BUILD.bazel
  tools/performance/defs.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#16981 [meshcat] Add realtime rate display to MeshcatVisualizer
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/test/geometry_visualizers_test.py
  bindings/pydrake/visualization/meldis.py
  common/BUILD.bazel
  common/test/timer_test.cc
  common/timer.cc
  common/timer.h
  geometry/BUILD.bazel
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/meshcat.html
  geometry/meshcat_types.h
  geometry/meshcat_visualizer.cc
  geometry/meshcat_visualizer.h
  geometry/test/meshcat_test.cc
  systems/analysis/BUILD.bazel
  systems/analysis/instantaneous_realtime_rate_calculator.cc
  systems/analysis/instantaneous_realtime_rate_calculator.h
  systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/msgpack_lite_js/BUILD.bazel
  tools/workspace/msgpack_lite_js/package.BUILD.bazel
  tools/workspace/msgpack_lite_js/repository.bzl
  tools/workspace/statsjs/BUILD.bazel
  tools/workspace/statsjs/package.BUILD.bazel
  tools/workspace/statsjs/repository.bzl
Labels: release notes: feature

#17537 Mark run_twisting_mug_test as flaky
  examples/allegro_hand/joint_control/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#17533 [primitives] Spell ternary operator compatibly with new AutoDiff
  systems/primitives/test/linear_transform_density_test.cc
  systems/primitives/test/multilayer_perceptron_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#17489 Update documentation for Jammy
  doc/_pages/from_source.md
  doc/_pages/installation.md
Labels: priority: high, status: squashing now, release notes: feature

#17536 [workspace] Add and use syntactic sugar for repository.bzl labels
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/ccd/repository.bzl
  tools/workspace/clang_cindex_python3_internal/repository.bzl
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/conex/repository.bzl
  tools/workspace/csdp/repository.bzl
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/dreal/repository.bzl
  tools/workspace/fcl/repository.bzl
  tools/workspace/ghc_filesystem/repository.bzl
  tools/workspace/github.bzl
  tools/workspace/github3_py_internal/repository.bzl
  tools/workspace/gtest/repository.bzl
  tools/workspace/gz_math_internal/repository.bzl
  tools/workspace/gz_utils_internal/repository.bzl
  tools/workspace/ibex/repository.bzl
  tools/workspace/intel_realsense_ros_internal/repository.bzl
  tools/workspace/json/repository.bzl
  tools/workspace/lcm/repository.bzl
  tools/workspace/libcmaes/repository.bzl
  tools/workspace/meshcat/repository.bzl
  tools/workspace/models_internal/repository.bzl
  tools/workspace/nlopt_internal/repository.bzl
  tools/workspace/osqp/repository.bzl
  tools/workspace/petsc/repository.bzl
  tools/workspace/picosha2/repository.bzl
  tools/workspace/pybind11/repository.bzl
  tools/workspace/pycodestyle/repository.bzl
  tools/workspace/qdldl/repository.bzl
  tools/workspace/qhull_internal/repository.bzl
  tools/workspace/ros_xacro_internal/repository.bzl
  tools/workspace/scs/repository.bzl
  tools/workspace/sdformat_internal/repository.bzl
  tools/workspace/stduuid/repository.bzl
  tools/workspace/styleguide/repository.bzl
  tools/workspace/tinyobjloader/repository.bzl
  tools/workspace/uritemplate_py_internal/repository.bzl
  tools/workspace/usockets/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
  tools/workspace/voxelized_geometry_tools/repository.bzl
  tools/workspace/xmlrunner_py/repository.bzl
  tools/workspace/yaml_cpp_internal/repository.bzl
Labels: priority: low, release notes: none

#17521 Generate .pyi's using pybind11-stubgen
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/stubgen.py
  bindings/pydrake/test/stubgen_test.py
  tools/workspace/default.bzl
  tools/workspace/mypy_extensions_internal/BUILD.bazel
  tools/workspace/mypy_extensions_internal/package.BUILD.bazel
  tools/workspace/mypy_extensions_internal/repository.bzl
  tools/workspace/mypy_internal/BUILD.bazel
  tools/workspace/mypy_internal/package.BUILD.bazel
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/tomli_internal/BUILD.bazel
  tools/workspace/tomli_internal/package.BUILD.bazel
  tools/workspace/tomli_internal/repository.bzl
  tools/workspace/typing_extensions_internal/BUILD.bazel
  tools/workspace/typing_extensions_internal/package.BUILD.bazel
  tools/workspace/typing_extensions_internal/repository.bzl
Labels: release notes: fix

#17454 [pydrake] Fold pydrake.examples into a single module
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/examples/__init__.py
  bindings/pydrake/examples/_examples_extra.py
  bindings/pydrake/examples/acrobot.py
  bindings/pydrake/examples/compass_gait.py
  bindings/pydrake/examples/examples_py.cc
  bindings/pydrake/examples/examples_py.h
  bindings/pydrake/examples/examples_py_acrobot.cc
  bindings/pydrake/examples/examples_py_compass_gait.cc
  bindings/pydrake/examples/examples_py_manipulation_station.cc
  bindings/pydrake/examples/examples_py_pendulum.cc
  bindings/pydrake/examples/examples_py_quadrotor.cc
  bindings/pydrake/examples/examples_py_rimless_wheel.cc
  bindings/pydrake/examples/examples_py_van_der_pol.cc
  bindings/pydrake/examples/manipulation_station.py
  bindings/pydrake/examples/multibody/BUILD.bazel
  bindings/pydrake/examples/pendulum.py
  bindings/pydrake/examples/quadrotor.py
  bindings/pydrake/examples/rimless_wheel.py
  bindings/pydrake/examples/van_der_pol.py
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/test/controllers_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/trajectory_optimization_test.py
  doc/pydrake/build.py
  examples/acrobot/spong_sim.py
  examples/manipulation_station/end_effector_teleop_dualshock4.py
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
  examples/manipulation_station/joint_teleop.py
  examples/manipulation_station/print_station_context.py
  examples/van_der_pol/plot_limit_cycle.py
  tutorials/dynamical_systems.ipynb
Labels: priority: medium, release notes: feature

#17548 [visualization] Repair meldis --host option
  bindings/pydrake/visualization/meldis.py
Labels: status: single reviewer ok, release notes: none

#17549 [pydrake] Give a big unit test some extra time
  bindings/pydrake/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok, release notes: none

#17528 Deprecated Body.get_default_mass() in favor of Body.default_mass().
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  examples/multibody/strandbeest/run_with_motor.cc
  examples/planar_gripper/brick_static_equilibrium_constraint.cc
  examples/planar_gripper/test/brick_static_equilibrium_constraint_test.cc
  multibody/contact_solvers/test/contact_solver_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/body.h
  multibody/tree/multibody_tree.cc
  multibody/tree/rigid_body.h
Labels: priority: medium, status: squashing now, component: multibody plant, release notes: breaking change, release notes: newly deprecated

#17545 Refactor to shorten into set/get_discrete_contact_solver().
  examples/atlas/atlas_run_dynamics.cc
  examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_config.h
  multibody/plant/multibody_plant_config_functions.cc
  multibody/plant/multibody_plant_config_functions.h
  multibody/plant/test/multibody_plant_config_functions_test.cc
Labels: priority: high, component: multibody plant, release notes: none

#17529 [plant] Shore up enum-string conversion implementation
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_config_functions.cc
Labels: priority: low, release notes: none

#17470 Reverse the suffix semantics of DrakeLcm::SubscribeAllChannels
  lcm/drake_lcm.cc
  lcm/drake_lcm_params.h
  lcm/test/drake_lcm_test.cc
Labels: priority: high, release notes: none

#17546 [docker] Enable Jammy docker builds
  tools/install/dockerhub/jammy/.dockerignore
  tools/install/dockerhub/jammy/Dockerfile
  tools/install/dockerhub/jammy/README.md
Labels: release notes: none

#17553 [workspace] Skip drake-visualizer wrapper install on unsupported platforms
  tools/workspace/drake_visualizer/BUILD.bazel
Labels: release notes: none

#17556 [wheel] Teach setuptools about __init__.so files
  tools/wheel/image/setup.py
Labels: priority: emergency, status: single reviewer ok, release notes: none

#17387 [manipulation] Add UR3e model and TRI Homecart
  doc/_pages/model_version_control.md
  manipulation/models/BUILD.bazel
  manipulation/models/tri_homecart/BUILD.bazel
  manipulation/models/tri_homecart/README.md
  manipulation/models/tri_homecart/homecart.yaml
  manipulation/models/tri_homecart/homecart_bimanual.urdf.xacro
  manipulation/models/tri_homecart/homecart_collision_walls.sdf
  manipulation/models/tri_homecart/homecart_cutting_board.sdf.xacro
  manipulation/models/tri_homecart/homecart_grippers.yaml
  manipulation/models/tri_homecart/homecart_no_grippers.yaml
  manipulation/models/tri_homecart/test/parse_homecart_test.cc
  manipulation/models/ur3e/BUILD.bazel
  manipulation/models/ur3e/README.md
  manipulation/models/ur3e/test/parse_test.cc
  manipulation/models/ur3e/ur.transmission.xacro
  manipulation/models/ur3e/ur3e.urdf.xacro
  manipulation/models/ur3e/ur3e_cylinders_collision.urdf.xacro
  manipulation/models/ur3e/ur3e_spheres_collision.urdf.xacro
  tools/wheel/image/build-wheel.sh
  tools/workspace/models_internal/files.bzl
  tools/workspace/models_internal/package.BUILD.bazel
  tools/workspace/models_internal/repository.bzl
Labels: component: planning and control, release notes: feature

#17300 [examples] Update manipulation station end_effector joystick Meshcat
  examples/manipulation_station/end_effector_teleop_dualshock4.py
Labels: priority: low, release notes: feature

#17513 Updates SAP's reference year
  multibody/contact_solvers/sap/sap_model.h
  multibody/contact_solvers/sap/test/sap_solver_test.cc
Labels: status: single reviewer ok, component: multibody plant, release notes: none

#17550 [meshcat] More robust parsing of .mtl texture map filenames
  geometry/meshcat.cc
  geometry/render/test/meshes/box.obj.mtl
Labels: priority: medium, component: geometry illustration, release notes: fix

#17251 [parsing] Add PackageMap::PopulateFromRosPackagePath
  bindings/pydrake/multibody/parsing_py.cc
  multibody/parsing/BUILD.bazel
  multibody/parsing/package_map.cc
  multibody/parsing/package_map.h
  multibody/parsing/test/package_map_test.cc
  multibody/parsing/test/package_map_test_packages/package_map_test_package_a/package_map_test_package_aa/package.xml
  multibody/parsing/test/package_map_test_packages/package_map_test_package_e/COLCON_IGNORE
  multibody/parsing/test/package_map_test_packages/package_map_test_package_e/package.xml
Labels: release notes: feature

#17558 [lcm] De-flake a unit test
  lcm/test/drake_lcm_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#17555 [tutorials] Move Multibody to the top of the index page
  tutorials/index.ipynb
Labels: priority: medium, status: single reviewer ok, release notes: none

#17561 [lcm] De-flake a unit test again
  lcm/test/drake_lcm_test.cc
Labels: priority: high, release notes: none

#17569 doc bazel: Mention editing Gurobi URL
  doc/_pages/bazel.md
Labels: priority: low, status: single reviewer ok, release notes: none

#17574 [inverse_kinematics] Use pydrake_mkdoc_identifier
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  multibody/inverse_kinematics/angle_between_vectors_constraint.h
  multibody/inverse_kinematics/com_in_polyhedron_constraint.h
  multibody/inverse_kinematics/com_position_constraint.h
  multibody/inverse_kinematics/distance_constraint.h
  multibody/inverse_kinematics/gaze_target_constraint.h
  multibody/inverse_kinematics/minimum_distance_constraint.h
  multibody/inverse_kinematics/orientation_constraint.h
  multibody/inverse_kinematics/point_to_point_distance_constraint.h
  multibody/inverse_kinematics/position_constraint.h
Labels: type: cleanup, status: single reviewer ok, release notes: fix

#17575 [inverse_kinematics] Rename kinematic_constraint => kinematic_evaluators
  examples/planar_gripper/BUILD.bazel
  examples/planar_gripper/brick_static_equilibrium_constraint.cc
  examples/planar_gripper/gripper_brick_planning_constraint_helper.cc
  multibody/benchmarking/BUILD.bazel
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/angle_between_vectors_constraint.cc
  multibody/inverse_kinematics/com_in_polyhedron_constraint.cc
  multibody/inverse_kinematics/com_position_constraint.cc
  multibody/inverse_kinematics/distance_constraint.cc
  multibody/inverse_kinematics/gaze_target_constraint.cc
  multibody/inverse_kinematics/kinematic_evaluator_utilities.cc
  multibody/inverse_kinematics/kinematic_evaluator_utilities.h
  multibody/inverse_kinematics/minimum_distance_constraint.cc
  multibody/inverse_kinematics/orientation_constraint.cc
  multibody/inverse_kinematics/point_to_point_distance_constraint.cc
  multibody/inverse_kinematics/position_constraint.cc
  multibody/optimization/BUILD.bazel
  multibody/optimization/centroidal_momentum_constraint.cc
  multibody/optimization/manipulator_equation_constraint.cc
  multibody/optimization/sliding_friction_complementarity_constraint.cc
  multibody/optimization/static_equilibrium_constraint.cc
  multibody/optimization/static_friction_cone_complementarity_constraint.cc
  multibody/optimization/static_friction_cone_constraint.cc
Labels: type: cleanup, status: single reviewer ok, release notes: fix

#17519 [doc] Add release notes v1.5.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.5.0.md
Labels: status: squashing now, status: single reviewer ok, release notes: none

#17567 Remove various lingering references to 18.04 support
  bindings/pydrake/common/cpp_param.py
  bindings/pydrake/common/test/deprecation_autocomplete_test.py
  solvers/test/augmented_lagrangian_test.cc
  tools/dynamic_analysis/valgrind.supp
Labels: status: single reviewer ok, release notes: none

#17578 [common] Make wall-clock less flaky but still mark as flaky
  common/BUILD.bazel
  common/test/timer_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#17539 [multibody] Reformulate cassie benchmark case permutations
  multibody/benchmarking/BUILD.bazel
  multibody/benchmarking/cassie.cc
Labels: priority: medium, release notes: none

#17577 fix #17576 -- incorrect use of InitializeAutoDiff when gradients are not needed
  multibody/inverse_kinematics/angle_between_vectors_constraint.cc
  multibody/inverse_kinematics/gaze_target_constraint.cc
  multibody/inverse_kinematics/orientation_constraint.cc
  multibody/inverse_kinematics/point_to_point_distance_constraint.cc
  multibody/inverse_kinematics/position_constraint.cc
  solvers/minimum_value_constraint.cc
  systems/trajectory_optimization/direct_collocation.cc
  systems/trajectory_optimization/direct_transcription.cc
Labels: release notes: fix, component: planning and control

#17463 [geometry] Report deformable rigid contact data
  geometry/proximity/BUILD.bazel
  geometry/proximity/deformable_contact_surface.h
  geometry/proximity/deformable_mesh_intersection.cc
  geometry/proximity/deformable_mesh_intersection.h
  geometry/proximity/deformable_rigid_contact_pair.h
  geometry/proximity/test/deformable_mesh_intersection_test.cc
  geometry/proximity/test/deformable_rigid_contact_pair_test.cc
  geometry/query_results/BUILD.bazel
  geometry/query_results/deformable_contact_data.cc
  geometry/query_results/deformable_contact_data.h
  geometry/query_results/deformable_rigid_contact.cc
  geometry/query_results/deformable_rigid_contact.h
  geometry/query_results/test/deformable_contact_data_test.cc
  geometry/query_results/test/deformable_rigid_contact_test.cc
  multibody/contact_solvers/sap/partial_permutation.h
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/deformable_rigid_mesh_intersection.cc
  multibody/fixed_fem/dev/deformable_rigid_mesh_intersection.h
  multibody/fixed_fem/dev/test/deformable_contact_test.cc
Labels: component: geometry proximity, release notes: none

#17552 Increase timeout in mypy ModuleImport
  bindings/pydrake/BUILD.bazel
  tools/workspace/mypy_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#17516 [math] Reduce implementation boilerplate for autodiff
  math/autodiff.h
  math/autodiff_gradient.h
  math/test/autodiff_test.cc
  tools/skylark/drake_cc.bzl
Labels: priority: low, release notes: breaking change, release notes: fix

#17584 Try to avoid mypy timing out
  bindings/pydrake/stubgen.py
  bindings/pydrake/test/stubgen_test.py
Labels: priority: emergency, status: single reviewer ok, release notes: none

#17583 Notes from v1.5.0 release experience
  doc/_pages/release_playbook.md
Labels: type: documentation, status: single reviewer ok, release notes: none

#17547 Remove SpatialInertia::MakeTestCube() in favor of SpatialInertia::MakeUnitary().
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/joint_locking_test.cc
  multibody/plant/test/multibody_plant_introspection_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/multibody_tree_creation_test.cc
  multibody/tree/test/spatial_inertia_test.cc
Labels: type: cleanup, priority: medium, status: squashing now, component: multibody plant, release notes: feature

#17586 [fem/dev] Remove unused files
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/deformable_visualizer.cc
  multibody/fixed_fem/dev/deformable_visualizer.h
  multibody/fixed_fem/dev/fem_indexes.h
  multibody/fixed_fem/dev/mesh_utilities.cc
  multibody/fixed_fem/dev/mesh_utilities.h
  multibody/fixed_fem/dev/reference_deformable_geometry.cc
  multibody/fixed_fem/dev/reference_deformable_geometry.h
  multibody/fixed_fem/dev/test/mesh_utilities_test.cc
Labels: status: single reviewer ok, release notes: none, component: softsim fem

#17593 [tools] Reduce local_ram_resources under ASan
  tools/dynamic_analysis/bazel.rc
Labels: release notes: none

#17485 [multibody] Provide more feedback when MbP query object port is unconnected
  doc/_pages/troubleshooting.md
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
  multibody/plant/test/multibody_plant_query_object_connect_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: release notes: fix

#17581 [performance] Add gflags support to benchmarks
  geometry/benchmarking/BUILD.bazel
  geometry/benchmarking/mesh_intersection_benchmark.cc
  geometry/benchmarking/render_benchmark.cc
  multibody/benchmarking/BUILD.bazel
  multibody/benchmarking/cassie.cc
  multibody/benchmarking/iiwa_relaxed_pos_ik.cc
  solvers/benchmarking/BUILD.bazel
  solvers/benchmarking/benchmark_mathematical_program.cc
  systems/benchmarking/BUILD.bazel
  systems/benchmarking/framework_benchmarks.cc
  systems/benchmarking/multilayer_perceptron_performance.cc
  tools/performance/BUILD.bazel
  tools/performance/README.md
  tools/performance/defs.bzl
  tools/performance/gflags_main.cc
Labels: priority: low, release notes: none

#17590 Fix missing internal::enable_if. Replace with std::enable_if
  common/autodiffxd.h
Labels: status: single reviewer ok, release notes: none

#17587 [inverse_kinematics] Add PositionCost
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/global_inverse_kinematics.h
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/position_cost.cc
  multibody/inverse_kinematics/position_cost.h
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/position_cost_test.cc
Labels: priority: medium, release notes: feature

#17591 [inverse_kinematics] Speed up OrientationConstraint implementation
  multibody/inverse_kinematics/orientation_constraint.cc
  multibody/inverse_kinematics/orientation_constraint.h
Labels: release notes: fix

#17588 [symbolic] Tidy up some comment cross-references
  bindings/pydrake/symbolic_types_pybind.h
  common/drake_assert.h
  common/symbolic/expression/expression.h
  common/symbolic/expression/formula.h
  common/symbolic/monomial_util.h
  common/symbolic/polynomial.h
  common/symbolic/polynomial_basis.h
Labels: priority: low, status: single reviewer ok, release notes: none

#17592 [inverse_kinematics] Add OrientationCost
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/orientation_cost.cc
  multibody/inverse_kinematics/orientation_cost.h
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/orientation_cost_test.cc
Labels: release notes: feature

#17580 [examples] Update examples to make use of AddMultibodyPlantSceneGraph
  bindings/pydrake/examples/multibody/cart_pole_passive_simulation.py
  bindings/pydrake/systems/drawing_graphviz_example.py
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/kinova_jaco_arm/jaco_simulation.cc
  examples/multibody/cylinder_with_multicontact/BUILD.bazel
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
  examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc
  examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.h
  examples/multibody/cylinder_with_multicontact/test/populate_cylinder_plant_test.cc
  examples/multibody/rolling_sphere/BUILD.bazel
  examples/multibody/rolling_sphere/make_rolling_sphere_plant.cc
  examples/multibody/rolling_sphere/populate_ball_plant.cc
  examples/multibody/rolling_sphere/populate_ball_plant.h
  examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
  examples/planar_gripper/planar_gripper_simulation.cc
  examples/simple_gripper/simple_gripper.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
Labels: priority: low, release notes: fix

#17449 [geometry/render_gltf_client] add RenderClient class
  geometry/render/dev/render_gltf_client/BUILD.bazel
  geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render/dev/render_gltf_client/internal_render_engine_gltf_client.h
  geometry/render/dev/render_gltf_client/test/internal_render_client_test.cc
  geometry/render/dev/render_gltf_client/test/internal_render_engine_gltf_client_test.cc
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_render_client.cc
  geometry/render_gltf_client/internal_render_client.h
  geometry/render_gltf_client/test/internal_render_client_test.cc
  geometry/render_gltf_client/test/internal_sample_image_data.cc
  geometry/render_gltf_client/test/internal_sample_image_data.h
  geometry/render_gltf_client/test/test_depth_32F.tiff
  geometry/render_gltf_client/test/test_label_16I.png
  geometry/render_gltf_client/test/test_rgb_8U.png
  geometry/render_gltf_client/test/test_rgba_8U.png
Labels: release notes: none

#17602 Revert "[tools] Reduce local_ram_resources under ASan"
  tools/dynamic_analysis/bazel.rc
Labels: release notes: none

#17601 [inverse_kinematics] Cleanup PositionCost implementation.
  multibody/inverse_kinematics/kinematic_evaluator_utilities.h
  multibody/inverse_kinematics/orientation_cost.cc
  multibody/inverse_kinematics/position_cost.cc
  multibody/inverse_kinematics/position_cost.h
Labels: priority: low, status: single reviewer ok, release notes: none, component: planning and control

#17604 [parsing] Handle unknown packages gracefully while processing model directives
  multibody/parsing/BUILD.bazel
  multibody/parsing/process_model_directives.cc
  multibody/parsing/test/process_model_directives_test.cc
  multibody/parsing/test/process_model_directives_test/bad_package_uri.yaml
Labels: release notes: fix

#17594 [planning] Add RobotDiagram and RobotDiagramBuilder
  planning/BUILD.bazel
  planning/robot_diagram.cc
  planning/robot_diagram.h
  planning/robot_diagram_builder.cc
  planning/robot_diagram_builder.h
  planning/test/robot_diagram_test.cc
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
  systems/framework/test/diagram_builder_test.cc
  tools/install/libdrake/build_components.bzl
Labels: priority: medium, status: commits are properly curated, release notes: feature

#17582 [geometry] Calculate distance from point to triangle surface mesh
  geometry/proximity/BUILD.bazel
  geometry/proximity/calc_distance_to_surface_mesh.cc
  geometry/proximity/calc_distance_to_surface_mesh.h
  geometry/proximity/test/calc_distance_to_surface_mesh_test.cc
Labels: component: geometry proximity, release notes: none

#17608 [inverse_kinematics] Add GlobalIK::SetInitialGuess and benchmark
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/benchmarking/BUILD.bazel
  multibody/benchmarking/homecart_global_ik.cc
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/global_inverse_kinematics.cc
  multibody/inverse_kinematics/global_inverse_kinematics.h
  multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc
Labels: priority: medium, release notes: fix, release notes: feature

#17596 add PolyhedronConstraint as a kinematic constraint.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/polyhedron_constraint.cc
  multibody/inverse_kinematics/polyhedron_constraint.h
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/polyhedron_constraint_test.cc
Labels: release notes: feature

#17522 Rational function python bindings
  bindings/pydrake/common/test_utilities/numpy_compare.py
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/symbolic_types_pybind.h
  bindings/pydrake/test/symbolic_test.py
  common/symbolic/rational_function.cc
  common/symbolic/rational_function.h
  common/symbolic/test/rational_function_test.cc
Labels: status: squashing now, release notes: feature

#17605 [geometry] Data structure for geometries in deformable contact
  geometry/proximity/BUILD.bazel
  geometry/proximity/deformable_contact_internal.cc
  geometry/proximity/deformable_contact_internal.h
  geometry/proximity/hydroelastic_internal.h
  geometry/proximity/test/deformable_contact_internal_test.cc
Labels: priority: medium, component: geometry proximity, release notes: none

#17612 [symbolic] Add BoxedCell helper class
  common/symbolic/expression/BUILD.bazel
  common/symbolic/expression/all.h
  common/symbolic/expression/boxed_cell.cc
  common/symbolic/expression/boxed_cell.h
  common/symbolic/expression/expression.cc
  common/symbolic/expression/expression.h
  common/symbolic/expression/expression_cell.cc
  common/symbolic/expression/expression_cell.h
  common/symbolic/expression/expression_kind.h
  common/symbolic/expression/test/boxed_cell_test.cc
Labels: priority: medium, release notes: none

#17611 Polynomial removes the term if is_zero(coeff) is true in that term.
  common/symbolic/polynomial.cc
  common/symbolic/polynomial.h
  common/symbolic/test/polynomial_test.cc
Labels: release notes: fix

#17617 Add python binding of SubstituteStereographicProjection
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
Labels: status: single reviewer ok, release notes: feature

#17614 [lcm] Add LcmBuses and related config functions
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_buses.cc
  systems/lcm/lcm_buses.h
  systems/lcm/lcm_config_functions.cc
  systems/lcm/lcm_config_functions.h
  systems/lcm/test/lcm_buses_test.cc
  systems/lcm/test/lcm_config_functions_test.cc
Labels: priority: medium, status: commits are properly curated, release notes: feature

#17613 Remove duplicate command in build-wheel.sh
  tools/wheel/image/build-wheel.sh
Labels: status: single reviewer ok, release notes: none

#17544 [symbolic] Speed up Expression via nanboxing
  common/symbolic/expression/expression.cc
  common/symbolic/expression/expression.h
  common/symbolic/expression/expression_cell.cc
  common/symbolic/expression/expression_cell.h
  common/symbolic/expression/test/expression_cell_test.cc
  common/symbolic/expression/test/expression_test.cc
Labels: priority: low, release notes: feature

#17620 [misc] Clean up unsupported/Eigen/AutoDiff include and using
  bindings/pydrake/autodiffutils_py.cc
  common/yaml/test/yaml_performance_test.cc
  examples/bead_on_a_wire/bead_on_a_wire.h
  math/autodiff.h
  math/jacobian.h
  math/test/autodiff_test.cc
  math/test/differentiable_norm_test.cc
  math/test/expmap_test.cc
  math/test/jacobian_test.cc
  math/test/linear_solve_test.cc
  multibody/tree/rotational_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
  multibody/tree/test/unit_inertia_test.cc
  solvers/constraint.cc
  solvers/constraint.h
  solvers/moby_lcp_solver.cc
  solvers/test/moby_lcp_solver_test.cc
  systems/analysis/test/simulator_test.cc
  tools/vector_gen/test/sample_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#17413 [doc] Document all nightly uploads and expiration policies
  doc/_pages/apt.md
  doc/_pages/from_binary.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_release-notes/2016.md
  doc/_release-notes/v1.1.0.md
  tools/workspace/vtk/README.md
Labels: release notes: feature

#17619 [doc] Add macOS stable releases for pip wheels
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_pages/release_playbook.md
Labels: priority: low, release notes: feature

#17624 Check if denominator is zero in RationalFunction.
  common/symbolic/rational_function.cc
Labels: status: single reviewer ok, release notes: none

#17618 [pydrake] Unify binding strategy for config structs
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/serialize_pybind.h
  bindings/pydrake/common/test/serialize_pybind_test.py
  bindings/pydrake/common/test/serialize_test_util_py.cc
  bindings/pydrake/geometry_py_render.cc
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/meshcat_py.cc
  bindings/pydrake/multibody/optimization_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/meshcat_test.py
  bindings/pydrake/multibody/test/optimization_test.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/test/geometry_render_test.py
  bindings/pydrake/test/geometry_visualizers_test.py
  bindings/pydrake/test/lcm_test.py
  geometry/BUILD.bazel
  geometry/drake_visualizer_params.h
  geometry/meshcat.h
  geometry/meshcat_visualizer_params.h
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/render_engine_gl_params.h
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/render_engine_vtk_params.h
  lcm/drake_lcm_params.h
  multibody/meshcat/BUILD.bazel
  multibody/meshcat/contact_visualizer_params.h
  multibody/optimization/BUILD.bazel
  multibody/optimization/toppra.h
  multibody/plant/multibody_plant_config.h
  multibody/tree/BUILD.bazel
  multibody/tree/door_hinge.h
  systems/analysis/BUILD.bazel
  systems/analysis/simulator.h
  systems/analysis/simulator_config.h
Labels: priority: high, release notes: none

#17627 [pydrake/lcm] Bind LcmBuses
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/lcm_test.py
Labels: status: single reviewer ok, release notes: none

#17631 [parsing] Extract ModelInstanceInfo to its own header file
  multibody/parsing/BUILD.bazel
  multibody/parsing/model_instance_info.h
  multibody/parsing/process_model_directives.h
Labels: status: single reviewer ok, release notes: none

#17615 Add demo program for hardware simulation
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/README.md
  examples/hardware_sim/example_scenarios.yaml
  examples/hardware_sim/hardware_sim.cc
  examples/hardware_sim/scenario.cc
  examples/hardware_sim/scenario.h
  examples/hardware_sim/test/hardware_sim_test.py
  examples/hardware_sim/test/test_scenarios.yaml
Labels: priority: medium, release notes: feature

#17603 [geometry] Build deformable sdf from distance to surface mesh
  geometry/proximity/BUILD.bazel
  geometry/proximity/deformable_contact_geometries.cc
  geometry/proximity/deformable_contact_geometries.h
  geometry/proximity/deformable_mesh_intersection.cc
  geometry/proximity/test/deformable_contact_geometries_test.cc
  geometry/proximity/test/deformable_mesh_intersection_test.cc
Labels: priority: medium, component: geometry proximity, release notes: none

#17633 [pydrake] Add missing include
  bindings/pydrake/common/serialize_pybind.h
Labels: priority: high, status: single reviewer ok, release notes: none

#17621 [ad] Add AutoDiff replacement class for AutoDiffXd
  common/ad/BUILD.bazel
  common/ad/README.md
  common/ad/auto_diff.h
  common/ad/internal/partials.cc
  common/ad/internal/partials.h
  common/ad/internal/standard_operations.cc
  common/ad/internal/standard_operations.h
  common/ad/test/auto_diff_basic_test.cc
  common/ad/test/partials_test.cc
  common/ad/test/standard_operations_stream_test.cc
Labels: priority: low, release notes: none

#17628 Implements SAP holonomic constraint
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_holonomic_constraint.cc
  multibody/contact_solvers/sap/sap_holonomic_constraint.h
  multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc
Labels: component: multibody plant, release notes: none

#17632 [multibody] All bodies and frames must have a non-empty name
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  multibody/parsing/detail_sdf_parser.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/body.h
  multibody/tree/fixed_offset_frame.h
  multibody/tree/frame.cc
  multibody/tree/frame.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/rigid_body.cc
  multibody/tree/rigid_body.h
  multibody/tree/test/articulated_body_algorithm_test.cc
  multibody/tree/test/ball_rpy_joint_test.cc
  multibody/tree/test/frames_test.cc
  multibody/tree/test/free_rotating_body_plant.cc
  multibody/tree/test/joint_actuator_test.cc
  multibody/tree/test/mobilizer_tester.h
  multibody/tree/test/multibody_forces_test.cc
  multibody/tree/test/multibody_tree_creation_test.cc
  multibody/tree/test/multibody_tree_test.cc
  multibody/tree/test/planar_joint_test.cc
  multibody/tree/test/prismatic_joint_test.cc
  multibody/tree/test/revolute_joint_test.cc
  multibody/tree/test/rigid_body_test.cc
  multibody/tree/test/screw_joint_test.cc
  multibody/tree/test/tree_from_joints_test.cc
  multibody/tree/test/tree_from_mobilizers_test.cc
  multibody/tree/test/universal_joint_test.cc
  multibody/tree/test/weld_joint_test.cc
Labels: priority: low, release notes: newly deprecated

#17642 [visualization] Improve meldis error message
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: priority: low, release notes: fix

#17570 [pydrake] Ignore Eigen::Sparse overloads when scipy is missing
  bindings/pydrake/common/test_utilities/BUILD.bazel
  bindings/pydrake/common/test_utilities/scipy_none/scipy/__init__.py
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/test/noscipy_test.py
  tools/workspace/pybind11/repository.bzl
Labels: priority: medium, release notes: fix

#17637 [pydrake] Binding ContactSurface mesh fields
  bindings/pydrake/geometry_py_hydro.cc
  bindings/pydrake/geometry_py_scene_graph.cc
  bindings/pydrake/test/geometry_scene_graph_test.py
Labels: release notes: feature

#17645 [visualization] Add ApplyVisualizerConfig
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/__init__.py
  bindings/pydrake/visualization/test/config_test.py
  bindings/pydrake/visualization/visualization_py.cc
  bindings/pydrake/visualization/visualization_py.h
  bindings/pydrake/visualization/visualization_py_config.cc
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/hardware_sim.cc
  examples/hardware_sim/scenario.h
  examples/hardware_sim/test/test_scenarios.yaml
  tools/install/libdrake/build_components.bzl
  visualization/BUILD.bazel
  visualization/test/visualizer_config_functions_test.cc
  visualization/visualizer_config.cc
  visualization/visualizer_config.h
  visualization/visualizer_config_functions.cc
  visualization/visualizer_config_functions.h
Labels: priority: medium, status: commits are properly curated, release notes: feature

#17646 Use Ubuntu mirror for MUMPS (wheel builds)
  tools/wheel/image/dependencies/patches/mumps/patch.diff
  tools/wheel/image/dependencies/projects.cmake
Labels: priority: high, status: single reviewer ok, release notes: fix

#17559 [workspace] Remove scipy dependency
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-focal-test-only.txt
  tools/wheel/image/setup.py
  tools/workspace/drake_visualizer/image/prereqs
Labels: release notes: removal of deprecated

#17606 [geometry] Complete the deformable::Geometries data structure
  geometry/proximity/deformable_contact_internal.cc
  geometry/proximity/deformable_contact_internal.h
  geometry/proximity/test/deformable_contact_internal_test.cc
Labels: component: geometry proximity, release notes: none

#17652 [pydrake] Hotfix for broken wheels
  tools/wheel/image/setup.py
Labels: priority: high, status: single reviewer ok, release notes: none
