Repository RobotLocomotion/drake, pull requests merged in 2022-11, with the labels that each got.

#18190 [planning] Adds KinematicTrajectoryOptimization
  bindings/pydrake/systems/test/trajectory_optimization_test.py
  bindings/pydrake/systems/trajectory_optimization_py.cc
  systems/trajectory_optimization/BUILD.bazel
  systems/trajectory_optimization/kinematic_trajectory_optimization.cc
  systems/trajectory_optimization/kinematic_trajectory_optimization.h
  systems/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Labels: priority: medium, release notes: feature

#18202 [geometry] Define alphabetical order to Shapes by convention
  geometry/drake_visualizer.cc
  geometry/make_mesh_for_deformable.cc
  geometry/make_mesh_for_deformable.h
  geometry/meshcat.cc
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/iris.cc
  geometry/proximity/deformable_contact_internal.cc
  geometry/proximity/deformable_contact_internal.h
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/hydroelastic_internal.h
  geometry/proximity_engine.cc
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/shape_to_string.cc
  geometry/shape_to_string.h
  geometry/test/geometry_state_test.cc
  geometry/test/shape_specification_test.cc
  geometry/test/shape_to_string_test.cc
  geometry/test_utilities/dummy_render_engine.h
Labels: priority: low, release notes: none

#18156 [solvers] Deprecate dReal and IBEX for removal
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py_dreal.cc
  bindings/pydrake/solvers/solvers_py_ibex.cc
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/dreal_solver_test.py
  bindings/pydrake/solvers/test/ibex_solver_test.py
  solvers/BUILD.bazel
  solvers/dreal_solver.cc
  solvers/dreal_solver.h
  solvers/dreal_solver_common.cc
  solvers/ibex_solver.cc
  solvers/ibex_solver.h
  solvers/ibex_solver_common.cc
  solvers/solver_type.h
  solvers/solver_type_converter.cc
  solvers/test/solver_type_converter_test.cc
  tools/workspace/cds/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/dreal/repository.bzl
  tools/workspace/ibex/repository.bzl
  tools/workspace/picosat/repository.bzl
Labels: priority: low, release notes: newly deprecated

#18226 [parsing] Deprecate PopulateFromEnvironment("ROS_PACKAGE_PATH")
  multibody/parsing/package_map.cc
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#18225 [pydrake] Remove deprecated MeshcatVisualizerCpp 2022-11
  bindings/pydrake/_geometry_extra.py
  bindings/pydrake/test/geometry_visualizers_test.py
  examples/manipulation_station/end_effector_teleop_dualshock4.py
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#18224 [common] Remove deprecated code 2022-11
  common/BUILD.bazel
  common/autodiffxd_make_coherent.h
  common/symbolic.h
  common/symbolic/decompose.h
  common/symbolic/test/decompose_test.cc
  common/symbolic_latex.h
  common/test/autodiffxd_make_coherent_test.cc
  common/test/deprecated_symbolic_headers_test.cc
  multibody/rational/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#18228 [sensors] Fix typo in deprecation date
  systems/sensors/camera_config_functions.h
Labels: priority: backlog, status: single reviewer ok, release notes: none

#18221 [math] Don't use march=broadwell on Ubuntu arm64 machines
  math/BUILD.bazel
  math/test/fast_pose_composition_functions_test.cc
Labels: priority: low, status: single reviewer ok, release notes: fix

#18230 Partially revert "... march=broadwell on Ubuntu arm64 machines"
  math/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok, release notes: none

#18231 Add memory leak exception to valgrind.supp to mute mosek memory leak error
  tools/dynamic_analysis/valgrind.supp
Labels: priority: high, status: single reviewer ok, release notes: none

#18229 [setup] Remove macOS auto-cleanup for drake_visualizer's removal
  setup/mac/binary_distribution/install_prereqs.sh
Labels: priority: low, release notes: none

#18189 [wheel] Enable mac arm64 wheel builds
  tools/wheel/image/dependencies/CMakeLists.txt
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/libjpeg-turbo.cmake
Labels: release notes: feature

#18239 [math] Remove stray "fast pose composition" Doxygen details
  math/fast_pose_composition_functions.h
  math/fast_pose_composition_functions_avx2_fma.h
Labels: priority: backlog, status: single reviewer ok, release notes: none

#18245 [pydrake] Improve unit test demo/coverage for lcmt_image_array
  bindings/pydrake/systems/test/sensors_test.py
Labels: priority: medium, release notes: none

#17319 [meshcat] Add capsule support
  geometry/meshcat.cc
  geometry/meshcat_types.h
  geometry/test/meshcat_manual_test.cc
  geometry/test/meshcat_test.cc
Labels: status: squashing now, release notes: feature

#18244 November 2022 updates
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/petsc/repository.bzl
  tools/workspace/ros_xacro_internal/repository.bzl
  tools/workspace/styleguide/repository.bzl
  tools/workspace/tinyobjloader/repository.bzl
  tools/workspace/typing_extensions_internal/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#18206 Fix a bug in GlobalInverseKinematics
  multibody/inverse_kinematics/global_inverse_kinematics.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.h
Labels: release notes: fix

#18238 [math] Don't use march=broadwell on Ubuntu arm64 machines
  math/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: fix

#18242 Complete deprecation of get_default_mass()
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/tree/body.h
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: removal of deprecated

#18222 Compute monomial basis with the degree for each variable <= 1
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic/BUILD.bazel
  common/symbolic/monomial_util.cc
  common/symbolic/monomial_util.h
  common/symbolic/test/monomial_util_test.cc
Labels: release notes: feature

#18237 [pydrake] Bind LcmImageArrayToImages
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
Labels: priority: low, release notes: feature

#18048 Add System::EvalUniquePeriodicDiscreteUpdate()
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
  systems/framework/context.h
  systems/framework/context_base.cc
  systems/framework/diagram.cc
  systems/framework/diagram.h
  systems/framework/framework_common.h
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_base.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/system_test.cc
Labels: priority: medium, release notes: feature

#18248 Fix a missing paramname
  multibody/meshcat/joint_sliders.h
Labels: status: single reviewer ok, release notes: fix

#18250 [workspace] Add dependency on bazelbuild/platforms
  math/BUILD.bazel
  tools/cc_toolchain/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/dreal/patches/platforms.patch
  tools/workspace/dreal/repository.bzl
  tools/workspace/platforms/BUILD.bazel
  tools/workspace/platforms/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#18220 Add jaco lcm time input/output ports
  bindings/pydrake/manipulation/kuka_iiwa_py.cc
  bindings/pydrake/manipulation/test/kuka_iiwa_test.py
  manipulation/kinova_jaco/jaco_command_receiver.cc
  manipulation/kinova_jaco/jaco_command_receiver.h
  manipulation/kinova_jaco/jaco_command_sender.cc
  manipulation/kinova_jaco/jaco_command_sender.h
  manipulation/kinova_jaco/jaco_status_receiver.cc
  manipulation/kinova_jaco/jaco_status_receiver.h
  manipulation/kinova_jaco/jaco_status_sender.cc
  manipulation/kinova_jaco/jaco_status_sender.h
  manipulation/kinova_jaco/test/jaco_command_receiver_test.cc
  manipulation/kinova_jaco/test/jaco_command_sender_test.cc
  manipulation/kinova_jaco/test/jaco_status_receiver_test.cc
  manipulation/kinova_jaco/test/jaco_status_sender_test.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.h
  manipulation/kuka_iiwa/iiwa_command_sender.cc
  manipulation/kuka_iiwa/iiwa_command_sender.h
  manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
  manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc
Labels: release notes: feature

#18191 [multibody] Parse screw joints from URDF
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
  multibody/parsing/test/urdf_parser_test/joint_parsing_test_missing_screw_thread_pitch.urdf
  multibody/parsing/test/urdf_parser_test/joint_parsing_test_missing_screw_thread_pitch_attribute.urdf
Labels: status: squashing now, release notes: feature

#18253 [lint] Tidy up genquery input
  tools/lint/library_lint.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#18255 parsing_doxygen: Clarify that SDFormat uses screw_thread_pitch
  multibody/parsing/parsing_doxygen.h
Labels: status: single reviewer ok, release notes: none

#18256 [typo] reserve => reverse
  tools/workspace/pkg_config.bzl
Labels: status: single reviewer ok, release notes: none

#18254 Update DeclareAbstractState() doc and py kwarg names
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
Labels: priority: low, status: single reviewer ok, release notes: none

#18270 Use const for quaternion used to build math::RigidTransform
  multibody/tree/quaternion_floating_mobilizer.cc
Labels: status: single reviewer ok, release notes: none

#18273 [meshcat] Remove stale reference to #15965 in meshcat_manual_test
  geometry/test/meshcat_manual_test.cc
Labels: priority: low, status: single reviewer ok, release notes: fix

#18267 py systems: Bind SetStateAndParametersFrom
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok, release notes: feature

#18264 [tools] Removes pybind (libclang setup) errors on arm64
  tools/workspace/pybind11/libclang_setup.py
Labels: status: single reviewer ok, release notes: none

#18269 [meshcat] Update Meshcat sha (now using msgpack-javascript)
  geometry/BUILD.bazel
  geometry/meshcat.cc
  geometry/meshcat.html
  geometry/test/meshcat_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/meshcat/repository.bzl
  tools/workspace/msgpack_lite_js/BUILD.bazel
  tools/workspace/msgpack_lite_js/package.BUILD.bazel
  tools/workspace/msgpack_lite_js/repository.bzl
Labels: priority: medium, release notes: feature

#18259 [workspace] Upgrade usockets and uwebsockets
  tools/workspace/usockets/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#18198 Deprecate FixedOffsetFrame::SetPoseInBodyFrame() for SetPoseInParentFrame()
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/fixed_offset_frame.h
Labels: status: squashing now, release notes: newly deprecated

#18271 [controllers] InverseDynamics doxygen and scalar support
  bindings/pydrake/systems/controllers_py.cc
  common/trajectories/discrete_time_trajectory.h
  common/trajectories/path_parameterized_trajectory.h
  common/trajectories/piecewise_polynomial.h
  common/trajectories/piecewise_pose.h
  common/trajectories/piecewise_quaternion.h
  common/trajectories/piecewise_trajectory.h
  common/trajectories/trajectory.h
  multibody/plant/externally_applied_spatial_force_multiplexer.h
  systems/controllers/BUILD.bazel
  systems/controllers/inverse_dynamics.cc
  systems/controllers/inverse_dynamics.h
  systems/controllers/inverse_dynamics_controller.cc
  systems/controllers/inverse_dynamics_controller.h
  systems/controllers/test/inverse_dynamics_controller_test.cc
  systems/controllers/test/inverse_dynamics_test.cc
  systems/estimators/luenberger_observer.h
Labels: priority: medium, release notes: feature

#18216 Parallelize pointcloud operations with OpenMP and use CRU DSHVG for voxel filter
  bindings/pydrake/perception_py.cc
  bindings/pydrake/test/perception_test.py
  perception/BUILD.bazel
  perception/point_cloud.cc
  perception/point_cloud.h
  perception/test/point_cloud_test.cc
Labels: status: squashing now, release notes: feature

#18281 [pydrake] Switch the clang-format directives order
  bindings/pydrake/.clang-format
  bindings/pydrake/test/dot_clang_format_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#18251 Improve documentation for RigidBody::SetCenterOfMassInBodyFrame()
  multibody/tree/rigid_body.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#18153 MultibodyPlant sometimes throws an exception for invalid mass/inertia properties
  multibody/plant/BUILD.bazel
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/articulated_body_inertia_cache.h
  multibody/tree/body_node.cc
  multibody/tree/body_node.h
  multibody/tree/test/body_node_test.cc
Labels: status: squashing now, release notes: fix

#18274 [framework] Add the ability to deprecate input and output ports
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_deprecated_test.cc
  multibody/plant/test/multibody_plant_test.cc
  systems/framework/BUILD.bazel
  systems/framework/diagram.cc
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/port_base.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/test/input_port_test.cc
  systems/framework/test/leaf_system_deprecation_test.cc
Labels: priority: low, release notes: newly deprecated, release notes: feature

#18243 [meshcat] Add support for gamepads in Meshcat
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/test/geometry_visualizers_test.py
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/meshcat.html
  geometry/meshcat_types.h
  geometry/test/meshcat_manual_test.cc
  geometry/test/meshcat_test.cc
Labels: status: squashing now, release notes: feature

#18205 [render_gltf_client] Add 16U PNG and TIFF depth support
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_render_client.cc
  geometry/render_gltf_client/internal_render_client.h
  geometry/render_gltf_client/render_gltf_client_doxygen.h
  geometry/render_gltf_client/test/internal_render_client_test.cc
  geometry/render_gltf_client/test/test_depth_16U.png
  geometry/render_gltf_client/test/test_depth_16U.tiff
Labels: release notes: feature

#18148 [release] Update release playbook for new staging jobs
  doc/_pages/release_playbook.md
  tools/release_engineering/download_release_candidate.py
  tools/wheel/wheel_builder/linux.py
Labels: status: squashing now, release notes: none

#18261 [setup] Remove errors on Ubuntu arm64
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: release notes: fix

#18265 Implements TamsiDriver
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/tamsi_driver.cc
  multibody/plant/tamsi_driver.h
  multibody/plant/test/square_surface.obj
  multibody/plant/test/tamsi_driver_test.cc
Labels: priority: high, release notes: none

#18283 [pydrake] Add PopulateFromRosPackagePath docstring
  bindings/pydrake/multibody/parsing_py.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#18284 Add a Stop Running button and Meshcat reuse to ModelVisualizer
  bindings/pydrake/visualization/_model_visualizer.py
  bindings/pydrake/visualization/test/model_visualizer_test.py
Labels: release notes: feature

#18282 Update buildcop instructions to match recent practice
  doc/_pages/buildcop.md
Labels: priority: low, type: documentation, status: single reviewer ok, release notes: none

#18280 MosekSolver aggregates duplicated variables in constraints.
  solvers/aggregate_costs_constraints.cc
  solvers/aggregate_costs_constraints.h
  solvers/mosek_solver_internal.cc
  solvers/mosek_solver_internal.h
  solvers/test/aggregate_costs_constraints_test.cc
  solvers/test/linear_program_examples.cc
  solvers/test/linear_program_examples.h
  solvers/test/mosek_solver_test.cc
Labels: component: mathematical program, release notes: fix

#18277 [parsing] Port to parser.AddModels, part 2
  bindings/pydrake/examples/test/manipulation_station_test.py
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/multibody/test/optimization_test.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/systems/test/rendering_test.py
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/allegro_hand/joint_control/simple_mug.sdf
  examples/hydroelastic/python_ball_paddle/BUILD.bazel
  examples/hydroelastic/python_ball_paddle/contact_sim_demo.py
  examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc
  examples/kinova_jaco_arm/jaco_simulation.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  examples/manipulation_station/test/manipulation_station_test.cc
  examples/planar_gripper/gripper_brick.cc
  examples/planar_gripper/planar_gripper_simulation.cc
  examples/planar_gripper/test/planar_gripper_common_test.cc
  examples/quadrotor/quadrotor_geometry.cc
  examples/simple_gripper/simple_gripper.cc
  examples/simple_gripper/simple_mug.sdf
  geometry/render_gltf_client/test/client_demo.cc
  manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
  manipulation/models/allegro_hand_description/test/parse_test.cc
  manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc
  manipulation/planner/constraint_relaxing_ik.cc
  manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  manipulation/schunk_wsg/test/build_schunk_wsg_control_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_driver_functions_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
  manipulation/util/test/zero_force_driver_functions_test.cc
  multibody/benchmarking/iiwa_relaxed_pos_ik.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc
  multibody/optimization/test/toppra_test.cc
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/plant/test/multibody_plant_introspection_test.cc
  multibody/plant/test/multibody_plant_mass_matrix_test.cc
  multibody/plant/test/multibody_plant_reflected_inertia_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/test_utilities/add_fixed_objects_to_plant.h
  tutorials/mathematical_program_multibody_plant.ipynb
Labels: release notes: none

#18289 Revert "[workspace] Upgrade usockets and uwebsockets"
  tools/workspace/usockets/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#18288 [visualization] Eschew ModelVisualizer use of properties
  bindings/pydrake/visualization/_model_visualizer.py
  bindings/pydrake/visualization/model_visualizer.py
  bindings/pydrake/visualization/test/model_visualizer_test.py
Labels: priority: medium, release notes: none

#18126 [geometry/render_gltf_client] Add glTF integration test
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/render_engine_gltf_client_params.h
  geometry/render_gltf_client/test/README.md
  geometry/render_gltf_client/test/acceptance_test.py
  geometry/render_gltf_client/test/client_demo.cc
  geometry/render_gltf_client/test/example_scene.sdf
  geometry/render_gltf_client/test/ground_truth.gltf
  geometry/render_gltf_client/test/integration_test.py
  geometry/render_gltf_client/test/server_demo.py
Labels: status: squashing now, release notes: none

#18293 [visualization] Do not show stack trace for meldis on sigint
  bindings/pydrake/visualization/meldis.py
Labels: release notes: fix

#18291 Gurobi handles duplicated variables in its linear constraints.
  solvers/gurobi_solver.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/second_order_cone_program_examples.h
Labels: component: mathematical program, release notes: fix

#18285 [workspace] Upgrade curl_internal to latest release 7.86.0
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/package.BUILD.bazel
  tools/workspace/curl_internal/repository.bzl
Labels: priority: low, release notes: fix

#18298 Disable glTF integration test on macOS
  geometry/render_gltf_client/test/integration_test.py
Labels: status: single reviewer ok, release notes: none

#18301 [pydrake] Remove spurous keep-alive annotations
  bindings/pydrake/trajectories_py.cc
Labels: priority: low, status: single reviewer ok, release notes: fix

#18299 [workspace] Drop macOS Big Sur support
  .github/ISSUE_TEMPLATE/BUG.yml
  CMakeLists.txt
  doc/_pages/code_review_checklist.md
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/jenkins.md
  doc/_pages/pip.md
  doc/_pages/release_playbook.md
  examples/manipulation_station/end_effector_teleop_sliders.py
  tools/release_engineering/download_release_candidate.py
  tools/workspace/cc/repository.bzl
  tools/workspace/os.bzl
Labels: release notes: fix

#18297 [workspace] Update pybind11 to include python@3.11 patches
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok, release notes: none

#18192 [trajectories] Add StackedTrajectory
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/BUILD.bazel
  common/trajectories/stacked_trajectory.cc
  common/trajectories/stacked_trajectory.h
  common/trajectories/test/stacked_trajectory_test.cc
Labels: priority: medium, release notes: feature

#18307 [multibody] Move DeformableModel out of internal
  examples/multibody/deformable_box/deformable_box.cc
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/physical_model.h
Labels: status: single reviewer ok, release notes: none

#18272 [controllers] Implements JointStiffnessController
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/test/controllers_test.py
  multibody/benchmarks/acrobot/double_pendulum.urdf
  systems/controllers/BUILD.bazel
  systems/controllers/inverse_dynamics.cc
  systems/controllers/inverse_dynamics.h
  systems/controllers/inverse_dynamics_controller.h
  systems/controllers/joint_stiffness_controller.cc
  systems/controllers/joint_stiffness_controller.h
  systems/controllers/test/inverse_dynamics_controller_test.cc
  systems/controllers/test/inverse_dynamics_test.cc
  systems/controllers/test/joint_stiffness_controller_test.cc
Labels: priority: medium, release notes: feature

#18308 [bindings] Add bindings for DeformableBodyConfig
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/all.py
  bindings/pydrake/multibody/fem_py.cc
  bindings/pydrake/multibody/test/fem_test.py
Labels: release notes: none

#18316 [py controllers] Use `using Class` conventions
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/test/controllers_test.py
Labels: status: single reviewer ok, release notes: none

#18320 Add test to csdp_solver_test on duplicated variables in constraints.
  solvers/test/csdp_solver_test.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/linear_program_examples.cc
  solvers/test/linear_program_examples.h
  solvers/test/mosek_solver_test.cc
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/second_order_cone_program_examples.h
Labels: release notes: none

#18319 [trajectories] Deprecate PiecewisePolynomial::Cubic
  common/trajectories/piecewise_polynomial.h
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#18313 [graph of convex sets] adjust test tolerance on rounding test
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: priority: medium, release notes: none

#18318 Test ScsSolver with duplicate variables
  solvers/test/scs_solver_test.cc
Labels: status: single reviewer ok, release notes: none

#18249 Simplify the authoring_multibody_simulation tutorial
  tutorials/authoring_multibody_simulation.ipynb
Labels: release notes: none

#18312 [geometry] Implements CalcVolume for mesh geometry
  geometry/BUILD.bazel
  geometry/proximity/BUILD.bazel
  geometry/proximity/meshing_utilities.cc
  geometry/proximity/meshing_utilities.h
  geometry/proximity/test/meshing_utilities_test.cc
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/test/octahedron.obj
  geometry/test/quad_cube.stl
  geometry/test/shape_specification_test.cc
Labels: priority: high, release notes: feature

#18326 [framework] Update deprecation date
  systems/framework/system.h
Labels: status: single reviewer ok, release notes: none

#18324 defer import of matplotlib.animation in pyplot_visualizer
  bindings/pydrake/systems/pyplot_visualizer.py
Labels: status: single reviewer ok, release notes: fix

#18305 [example] Change deformable box to a torus
  examples/multibody/deformable_box/box.vtk
  examples/multibody/deformable_torus/BUILD.bazel
  examples/multibody/deformable_torus/README.md
  examples/multibody/deformable_torus/deformable_torus.cc
  examples/multibody/deformable_torus/simple_gripper.sdf
  examples/multibody/deformable_torus/torus.vtk
Labels: priority: low, release notes: none

#18317 [parsing] Implements basic material and mesh support in MuJoCo parser
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/box_package/mjcfs/box.xml
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: priority: medium, release notes: feature

#18263 [doc] Add release notes v1.10.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.10.0.md
Labels: status: squashing now, status: single reviewer ok, release notes: none

#18332 [geometry/render_gltf_client] disable integration test on macOS
  geometry/render_gltf_client/test/integration_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#18304 Add tests for RigidFrame::SetCenterOfMassInBodyFrame
  multibody/tree/BUILD.bazel
  multibody/tree/rigid_body.h
  multibody/tree/test/rigid_body_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#18340 [workspace] Use host OS VTK 9.1 when on Ubuntu 22.04
  bindings/pydrake/visualization/_video.py
  bindings/pydrake/visualization/test/video_test.py
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  tools/workspace/vtk/build_binaries_with_docker
  tools/workspace/vtk/repository.bzl
Labels: priority: high, release notes: fix

#18343 [parsing] Port to parser.AddModels, part 3
  bindings/pydrake/systems/test/controllers_test.py
  multibody/plant/test/multibody_plant_deprecated_test.cc
  systems/controllers/test/inverse_dynamics_controller_test.cc
  systems/controllers/test/inverse_dynamics_test.cc
  systems/controllers/test/joint_stiffness_controller_test.cc
Labels: status: single reviewer ok, release notes: none

#18290 Set wall boundary condition for deformable bodies
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/test/deformable_boundary_condition_test.cc
  multibody/plant/test/deformable_model_test.cc
Labels: priority: high, release notes: none

#18341 [pydrake] Add missing bindings to UnitInertia
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok, release notes: fix

#18357 [py all] Add Preferred Ordering mechanism and tests
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/all.py
  bindings/pydrake/test/all_test.py
  bindings/pydrake/test/print_symbol_collisions.py
Labels: status: single reviewer ok, release notes: fix

#18354 [py framework] Bind CacheEntry.Eval for better workflow
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/custom_test.py
Labels: release notes: fix

#18330 workspace: Update optitrack_driver for skeleton support
  tools/workspace/optitrack_driver/repository.bzl
Labels: release notes: breaking change

#18369 [doc] Fix missing date substitution for release v1.10.0
  doc/_release-notes/v1.10.0.md
Labels: status: single reviewer ok, release notes: none

#18361 Change the returned dual solution for rotated Lorentz cone constraint in MosekSolver
  solvers/mosek_solver_internal.h
  solvers/test/mosek_solver_test.cc
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/second_order_cone_program_examples.h
Labels: release notes: fix

#18367 GurobiSolver always returns the best effort solution.
  solvers/gurobi_solver.cc
  solvers/test/gurobi_solver_test.cc
Labels: release notes: fix

#18339 [common] Add simple scalar_casting_test
  common/BUILD.bazel
  common/test/scalar_casting_test.cc
Labels: priority: low, release notes: none

#18358 Add CollisionGeometry for C-Iris.
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/test/c_iris_test_utilities.cc
  geometry/optimization/dev/test/c_iris_test_utilities.h
  geometry/optimization/dev/test/collision_geometry_test.cc
  geometry/optimization/dev/test/convex.mtl
  geometry/optimization/dev/test/convex.obj
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: status: single reviewer ok, release notes: none

#18364 [multibody/optimization] Add SpatialVelocityConstraint
  bindings/pydrake/multibody/optimization_py.cc
  bindings/pydrake/multibody/test/optimization_test.py
  multibody/optimization/BUILD.bazel
  multibody/optimization/spatial_velocity_constraint.cc
  multibody/optimization/spatial_velocity_constraint.h
  multibody/optimization/test/spatial_velocity_constraint_test.cc
Labels: priority: medium, release notes: feature

#18372 [parsing] Port to parser.AddModels, part 4
  examples/hydroelastic/python_nonconvex_mesh/drop_pepper.py
Labels: priority: low, status: single reviewer ok, release notes: none

#18310 [bindings] Bind DeformableModel and related functions
  bindings/pydrake/geometry_py_scene_graph.cc
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/all.py
  bindings/pydrake/multibody/fem_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/test/geometry_scene_graph_test.py
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/deformable_model.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_model_attorney.h
  multibody/plant/physical_model.cc
  multibody/plant/physical_model.h
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
Labels: release notes: none

#18375 Support sphere and capsule in C-IRIS collision geometry.
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/test/collision_geometry_test.cc
Labels: status: squashing now, release notes: none

#18378 Fix a memory bug when setting gurobi dual solution.
  solvers/gurobi_solver.cc
Labels: status: single reviewer ok, release notes: none

#18376 [geometry/optimization] Add Iris support for Convex mesh geometries
  geometry/optimization/BUILD.bazel
  geometry/optimization/iris.cc
  geometry/optimization/test/iris_in_configuration_space_test.cc
Labels: priority: medium, release notes: feature

#18360 ScsSolver result reports dual solution.
  solvers/scs_solver.cc
  solvers/test/scs_solver_test.cc
Labels: component: mathematical program, release notes: feature
