Repository RobotLocomotion/drake, pull requests merged in 2022-02, with the labels that each got.

#16471 [geometry] Document QueryObject to support compliant-compliant contact.
  geometry/query_object.h
Labels: type: documentation, team: dynamics, status: single reviewer ok, component: geometry proximity, release notes: yes

#16473 [doc] Add full website DDG search to pydrake search panel
  doc/pydrake/BUILD.bazel
  doc/pydrake/conf.py
  doc/pydrake/searchbox.html
Labels: priority: low, status: single reviewer ok, release notes: yes

#16474 Ensure Doxygen runs in a UTF-8 locale
  doc/defs.py
Labels: status: single reviewer ok, release notes: none

#16479 Remove deprecated code 2022-02
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/_autodiffutils_extra.py
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/planner_py.cc
  bindings/pydrake/manipulation/test/planner_test.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/test/autodiffutils_test.py
  common/test_utilities/BUILD.bazel
  common/test_utilities/eigen_geometry_compare.cc
  common/test_utilities/eigen_geometry_compare.h
  manipulation/models/ycb/package.xml
  manipulation/perception/BUILD.bazel
  manipulation/perception/optitrack_pose_extractor.cc
  manipulation/perception/optitrack_pose_extractor.h
  manipulation/perception/test/pose_smoother_test.cc
  manipulation/planner/differential_inverse_kinematics.h
  manipulation/planner/differential_inverse_kinematics_integrator.cc
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  math/autodiff.h
  math/autodiff_gradient.h
  math/test/autodiff_test.cc
  multibody/parsing/process_model_directives.cc
  multibody/parsing/process_model_directives.h
  multibody/parsing/test/process_model_directives_test.cc
  multibody/plant/BUILD.bazel
  systems/controllers/BUILD.bazel
  systems/controllers/setpoint.cc
  systems/controllers/setpoint.h
  systems/primitives/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#16480 [doc] Remove Doxygen tabs header and "generated by" footer
  doc/doxygen_cxx/Doxyfile_CXX.in
  doc/doxygen_cxx/footer.html
Labels: status: single reviewer ok, release notes: none

#16415 Enhance documentation and notation for offset frames.
  multibody/multibody_doxygen.h
Labels: type: documentation, team: dynamics, priority: medium, status: squashing now, component: multibody plant, release notes: none

#16489 [plant] Add internal::GeometryNames utility
  multibody/models/box.urdf
  multibody/plant/BUILD.bazel
  multibody/plant/internal_geometry_names.cc
  multibody/plant/internal_geometry_names.h
  multibody/plant/multibody_plant.cc
  multibody/plant/test/internal_geometry_names_test.cc
Labels: priority: medium, release notes: none

#16477 [framework] Add DiagramBuilder::connection_map function
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
  systems/framework/diagram.h
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
  systems/framework/test/diagram_builder_test.cc
Labels: priority: medium, release notes: yes

#16475 [meshcat] Remove accidental support for Expression
  bindings/pydrake/multibody/meshcat_py.cc
  multibody/meshcat/contact_visualizer.h
Labels: priority: high, status: single reviewer ok, release notes: none

#16468 [primitives] Clean up MultilayerPerceptron implementation
  systems/primitives/multilayer_perceptron.cc
  systems/primitives/multilayer_perceptron.h
Labels: status: single reviewer ok, release notes: none

#16478 [plant] Add MbP back-pointer into ContactResults struct
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/box_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
Labels: priority: high, release notes: yes

#16483 Make JacoCommandReceiver use an input port for initial position
  examples/kinova_jaco_arm/BUILD.bazel
  examples/kinova_jaco_arm/jaco_simulation.cc
  manipulation/kinova_jaco/jaco_command_receiver.cc
  manipulation/kinova_jaco/jaco_command_receiver.h
  manipulation/kinova_jaco/test/jaco_command_receiver_test.cc
Labels: release notes: newly deprecated

#16466 [multibody] Parse mujoco inertial bodies
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: none

#16367 [multibody] hydroelastic compliant-compliant contact
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: priority: high, team: dynamics, component: multibody plant, release notes: yes

#16469 [multibody] Fix to enable Expression in MakeFromCentralInertia
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/tree/test/spatial_inertia_test.cc
  multibody/tree/unit_inertia.h
Labels: status: single reviewer ok, release notes: yes

#16488 Adds missing collision filters to Atlas model.
  examples/atlas/urdf/atlas_convex_hull.urdf
Labels: type: bug, team: dynamics, release notes: yes

#16484 Upgrade externals to latest releases (Feb 2022)
  solvers/scs_solver.cc
  tools/workspace/buildifier/repository.bzl
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/dm_control/repository.bzl
  tools/workspace/googlebenchmark/repository.bzl
  tools/workspace/ignition_math/package.BUILD.bazel
  tools/workspace/ignition_math/repository.bzl
  tools/workspace/ros_xacro/repository.bzl
  tools/workspace/scs/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: yes

#16491 [doc] Add DDG searches to our Doxygen header
  doc/doxygen_cxx/BUILD.bazel
  doc/doxygen_cxx/Doxyfile_CXX.in
  doc/doxygen_cxx/build.py
  doc/doxygen_cxx/doxygen_extra.css
  doc/doxygen_cxx/footer.html
  doc/doxygen_cxx/header.html.patch
Labels: priority: low, status: single reviewer ok, release notes: yes

#16472 Use std::vector<Variable> instead of VectorX<Variable> for decision_variables_ and indeterminates_ in MathematicalProgram
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
Labels: release notes: yes

#16452 [examples] Recommend using meldis where possible
  examples/acrobot/README.md
  examples/acrobot/run_lqr.cc
  examples/acrobot/run_lqr_w_estimator.cc
  examples/acrobot/run_passive.cc
  examples/acrobot/run_swing_up.cc
  examples/allegro_hand/joint_control/README.md
  examples/atlas/atlas_run_dynamics.cc
  examples/compass_gait/simulate.cc
  examples/kinova_jaco_arm/README.md
  examples/kuka_iiwa_arm/README.md
  examples/multibody/acrobot/passive_simulation.cc
  examples/multibody/acrobot/run_lqr.cc
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
  examples/multibody/four_bar/passive_simulation.cc
  examples/multibody/pendulum/passive_simulation.cc
  examples/particles/README.md
  examples/particles/uniformly_accelerated_particle.cc
  examples/planar_gripper/README.md
  examples/rimless_wheel/simulate.cc
  examples/simple_gripper/README.md
  examples/simple_gripper/simple_gripper.cc
  multibody/plant/contact_results_to_lcm.h
Labels: priority: low, release notes: yes

#16485 [workspace] Upgrade rules_pkg to latest release 0.6.0
  tools/workspace/rules_pkg/repository.bzl
Labels: status: single reviewer ok, release notes: yes

#16490 [multibody] Document default collision filtering
  geometry/scene_graph.h
  multibody/plant/multibody_plant.h
Labels: release notes: none

#16506 [fem] Remove unused files in dev
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/acceleration_newmark_scheme.cc
  multibody/fixed_fem/dev/acceleration_newmark_scheme.h
  multibody/fixed_fem/dev/damping_model.h
  multibody/fixed_fem/dev/deformable_model.cc
  multibody/fixed_fem/dev/deformable_model.h
  multibody/fixed_fem/dev/deformable_rigid_manager.cc
  multibody/fixed_fem/dev/deformable_rigid_manager.h
  multibody/fixed_fem/dev/dirichlet_boundary_condition.h
  multibody/fixed_fem/dev/dynamic_elasticity_element.h
  multibody/fixed_fem/dev/dynamic_elasticity_model.h
  multibody/fixed_fem/dev/eigen_conjugate_gradient_solver.h
  multibody/fixed_fem/dev/elasticity_element.h
  multibody/fixed_fem/dev/elasticity_model.h
  multibody/fixed_fem/dev/fem_element.h
  multibody/fixed_fem/dev/fem_model.h
  multibody/fixed_fem/dev/fem_model_base.cc
  multibody/fixed_fem/dev/fem_model_base.h
  multibody/fixed_fem/dev/fem_solver.h
  multibody/fixed_fem/dev/fem_state.h
  multibody/fixed_fem/dev/fem_state_base.cc
  multibody/fixed_fem/dev/fem_state_base.h
  multibody/fixed_fem/dev/inverse_spd_operator.cc
  multibody/fixed_fem/dev/inverse_spd_operator.h
  multibody/fixed_fem/dev/linear_system_solver.h
  multibody/fixed_fem/dev/newmark_scheme.h
  multibody/fixed_fem/dev/run_cantilever_beam.cc
  multibody/fixed_fem/dev/run_scripted_deformable_motion.cc
  multibody/fixed_fem/dev/run_simple_gripper.cc
  multibody/fixed_fem/dev/state_updater.h
  multibody/fixed_fem/dev/static_elasticity_element.h
  multibody/fixed_fem/dev/static_elasticity_model.h
  multibody/fixed_fem/dev/test/acceleration_newmark_scheme_test.cc
  multibody/fixed_fem/dev/test/deformable_box_test.cc
  multibody/fixed_fem/dev/test/deformable_model_test.cc
  multibody/fixed_fem/dev/test/deformable_rigid_contact_solver_test.cc
  multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
  multibody/fixed_fem/dev/test/dirichlet_boundary_condition_test.cc
  multibody/fixed_fem/dev/test/dummy_element.h
  multibody/fixed_fem/dev/test/dynamic_elasticity_element_test.cc
  multibody/fixed_fem/dev/test/dynamic_elasticity_model_test.cc
  multibody/fixed_fem/dev/test/eigen_conjugate_gradient_solver_test.cc
  multibody/fixed_fem/dev/test/elasticity_element_test.cc
  multibody/fixed_fem/dev/test/fem_element_test.cc
  multibody/fixed_fem/dev/test/fem_solver_test.cc
  multibody/fixed_fem/dev/test/fem_state_test.cc
  multibody/fixed_fem/dev/test/inverse_spd_operator_test.cc
  multibody/fixed_fem/dev/test/permute_block_sparse_matrix_test.cc
  multibody/fixed_fem/dev/test/rigid_update_test.cc
  multibody/fixed_fem/dev/test/static_elasticity_element_test.cc
  multibody/fixed_fem/dev/test/static_elasticity_model_test.cc
  multibody/fixed_fem/dev/test/stretch_test.cc
  multibody/fixed_fem/dev/test/velocity_newmark_scheme_test.cc
  multibody/fixed_fem/dev/test/zeroth_order_state_updater_test.cc
  multibody/fixed_fem/dev/velocity_newmark_scheme.cc
  multibody/fixed_fem/dev/velocity_newmark_scheme.h
  multibody/fixed_fem/dev/zeroth_order_state_updater.h
Labels: priority: low, status: single reviewer ok, release notes: none, component: softsim fem

#16505 [workspace] Upgrade meshcat_python to latest commit
  tools/workspace/meshcat_python/repository.bzl
Labels: status: single reviewer ok, release notes: yes

#16497 [fem] Calculate Lame parameters from Young's modulus and Poisson ratio
  multibody/fem/BUILD.bazel
  multibody/fem/calc_lame_parameters.cc
  multibody/fem/calc_lame_parameters.h
  multibody/fem/test/calc_lame_parameters_test.cc
Labels: release notes: none, component: softsim fem

#16499 [parsing] Stop putting memory addresses into geometry names
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/urdf_parser_test/two_unnamed_boxes.urdf
Labels: priority: high, release notes: yes

#16496 [fem] Add Rayleigh damping model
  multibody/fem/BUILD.bazel
  multibody/fem/damping_model.cc
  multibody/fem/damping_model.h
  multibody/fem/test/damping_model_test.cc
Labels: release notes: none, component: softsim fem

#16510 [geometry] Don't spuriously test for exception subtypes
  geometry/proximity/test/contact_surface_utility_test.cc
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/hydroelastic_callback_test.cc
  geometry/proximity/test/hydroelastic_internal_test.cc
  geometry/proximity/test/obj_to_surface_mesh_test.cc
  geometry/proximity/test/penetration_as_point_pair_callback_test.cc
  geometry/proximity/test/plane_test.cc
  geometry/proximity/test/posed_half_space_test.cc
  geometry/render/gl_renderer/test/no_render_engine_gl_test.cc
  geometry/render/gl_renderer/test/opengl_geometry_test.cc
  geometry/render/gl_renderer/test/render_engine_gl_test.cc
  geometry/render/gl_renderer/test/shader_program_test.cc
  geometry/render/gl_renderer/test/shape_meshes_test.cc
  geometry/render/test/render_camera_test.cc
  geometry/render/test/render_engine_test.cc
  geometry/render/test/render_engine_vtk_test.cc
  geometry/render/test/render_label_test.cc
  geometry/test/frame_kinematics_vector_test.cc
  geometry/test/geometry_frame_test.cc
  geometry/test/geometry_instance_test.cc
  geometry/test/geometry_properties_test.cc
  geometry/test/geometry_state_test.cc
  geometry/test/internal_geometry_test.cc
  geometry/test/proximity_engine_test.cc
  geometry/test/proximity_properties_test.cc
  geometry/test/query_object_test.cc
  geometry/test/rgba_test.cc
  geometry/test/scene_graph_test.cc
  geometry/test/shape_specification_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#16512 [systems] Don't spuriously test for exception subtypes
  systems/analysis/test/antiderivative_function_test.cc
  systems/analysis/test/hermitian_dense_output_test.cc
  systems/analysis/test/initial_value_problem_test.cc
  systems/analysis/test/integrator_base_test.cc
  systems/analysis/test/scalar_initial_value_problem_test.cc
  systems/analysis/test/scalar_view_dense_output_test.cc
  systems/analysis/test/simulator_test.cc
  systems/framework/test/cache_entry_test.cc
  systems/framework/test/cache_test.cc
  systems/framework/test/diagram_builder_test.cc
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/discrete_values_test.cc
  systems/framework/test/input_port_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/output_port_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/value_to_abstract_value_test.cc
  systems/optimization/test/system_constraint_adapter_test.cc
  systems/primitives/test/gain_test.cc
  systems/primitives/test/linear_system_test.cc
  systems/primitives/test/linear_transform_density_test.cc
  systems/rendering/test/multibody_position_to_geometry_pose_test.cc
  systems/sensors/test/image_writer_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#16513 [common,solvers] Don't spuriously test for exception subtypes
  common/test/pointer_cast_test.cc
  common/test/symbolic_chebyshev_basis_element_test.cc
  common/test/symbolic_expression_matrix_test.cc
  common/test/symbolic_generic_polynomial_test.cc
  common/test/symbolic_monomial_basis_element_test.cc
  common/test/symbolic_monomial_test.cc
  common/test/symbolic_polynomial_basis_element_test.cc
  common/test/symbolic_rational_function_test.cc
  common/test/type_safe_index_test.cc
  solvers/test/choose_best_solver_test.cc
  solvers/test/constraint_test.cc
  solvers/test/equality_constrained_qp_solver_test.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/mathematical_program_result_test.cc
  solvers/test/mathematical_program_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/solver_base_test.cc
  solvers/test/solver_options_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#16517 [doc] Document Hunt and Crossley-inspired dissipation model
  multibody/parsing/parsing_doxygen.h
  multibody/plant/multibody_plant.h
Labels: release notes: none

#16520 [doc] Add xuchenhan-tri as a platform reviwer
  doc/_pages/developers.md
Labels: release notes: none

#16493 [meshcat] Use body names for point contact visualization
  multibody/meshcat/contact_visualizer.cc
  multibody/meshcat/contact_visualizer.h
  multibody/meshcat/point_contact_visualizer.h
  multibody/meshcat/test/contact_visualizer_test.cc
  multibody/plant/internal_geometry_names.cc
  multibody/plant/internal_geometry_names.h
  multibody/plant/test/internal_geometry_names_test.cc
Labels: priority: medium, release notes: yes

#16522 [doc] Fix broken links in multibody doc
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok, release notes: none

#16516 [examples] Remove dead XML data
  examples/multibody/cassie_benchmark/cassie_v2.urdf
Labels: status: single reviewer ok, release notes: none

#16508 [fem] Prepare matrix utilities to move out of dev
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/matrix_utilities.cc
  multibody/fixed_fem/dev/matrix_utilities.h
  multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc
  multibody/fixed_fem/dev/test/matrix_utilities_test.cc
  multibody/fixed_fem/dev/test/test_utilities.cc
  multibody/fixed_fem/dev/test/test_utilities.h
Labels: status: single reviewer ok, release notes: none, component: softsim fem

#16527 [doc] Remove non-drake namespaces from Doxygen output
  common/sorted_pair.h
  geometry/meshcat_types.h
  multibody/contact_solvers/supernodal_solver.h
Labels: priority: low, status: single reviewer ok, release notes: none

#16530 Clarify some text that confused a user
  doc/_pages/clion.md
Labels: priority: low, type: documentation, team: dynamics, status: single reviewer ok, release notes: none

#16523 setup: Upgrade recommended Bazel version to 5.0
  doc/_pages/from_source.md
  setup/ubuntu/source_distribution/install_prereqs.sh
  tools/wheel/image/provision-base.sh
  tools/workspace/drake_visualizer/image/provision.sh
Labels: status: single reviewer ok, release notes: yes

#16515 [meshcat] Wire up geometry names for point contact visualization
  bindings/pydrake/multibody/meshcat_py.cc
  bindings/pydrake/multibody/test/meshcat_test.py
  multibody/meshcat/contact_visualizer.cc
  multibody/meshcat/contact_visualizer.h
  multibody/meshcat/test/contact_visualizer_test.cc
Labels: priority: medium, release notes: yes

#16535 [urdf] Delete wrong and/or unused namespace declarations
  examples/acrobot/Acrobot.urdf
  examples/acrobot/Acrobot_no_collision.urdf
  examples/pendulum/Pendulum.urdf
  examples/pendulum/test/PendulumWithFriction.urdf
  examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf
  examples/quadrotor/quadrotor.urdf
  examples/simple_four_bar/FourBar.urdf
  examples/simple_four_bar/FourBar2.urdf
  multibody/benchmarks/acrobot/double_pendulum.urdf
Labels: status: single reviewer ok, release notes: none

#16509 [fem] Move matrix utilities out of dev
  multibody/fem/BUILD.bazel
  multibody/fem/matrix_utilities.cc
  multibody/fem/matrix_utilities.h
  multibody/fem/test/matrix_utilities_test.cc
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/corotated_model_data.h
  multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc
Labels: release notes: none, component: softsim fem

#16536 [examples] Fix a malformed XML comment
  examples/multibody/cassie_benchmark/cassie_v2.urdf
Labels: status: single reviewer ok, release notes: none

#16529 [primitives] Implement LeCun initialization for MultilayerPerceptron
  systems/primitives/multilayer_perceptron.cc
  systems/primitives/multilayer_perceptron.h
  systems/primitives/test/multilayer_perceptron_test.cc
Labels: release notes: yes

#16528 Mosek also print solution summary.
  solvers/mosek_solver.cc
Labels: release notes: yes

#16532 Enable ipopt in pip build
  tools/wheel/image/build-drake.sh
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/ipopt.cmake
Labels: release notes: yes

#16531 [geometry,doc] Clarify RenderEngineVtk texture assignment
  geometry/render/render_engine_vtk_factory.h
Labels: release notes: none

#16542 [primitives] Add MultilayerPerceptron::GetMutableParameters()
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/multilayer_perceptron.cc
  systems/primitives/multilayer_perceptron.h
  systems/primitives/test/multilayer_perceptron_test.cc
Labels: status: single reviewer ok, release notes: yes

#16514 [test_utilities] Deprecate checking the specific exception subtype
  bindings/pydrake/common/test/cpp_template_pybind_test.cc
  common/test_utilities/expect_throws_message.h
  lcm/test/drake_lcm_interface_test.cc
  lcm/test/lcm_messages_test.cc
  math/test/roll_pitch_yaw_test.cc
  math/test/rotation_matrix_test.cc
  tools/vector_gen/test/sample_test.cc
Labels: priority: low, release notes: newly deprecated

#16449 Add Hydroelastic User Guide Doxygen module
  multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
  multibody/hydroelastics/images/contact-fig-01.png
  multibody/hydroelastics/images/contact-fig-02.png
  multibody/hydroelastics/images/contact-fig-03.png
  multibody/hydroelastics/images/contact-fig-04.png
  multibody/hydroelastics/images/drake-vis-01.png
  multibody/hydroelastics/images/drake-vis-02.png
  multibody/hydroelastics/images/drake-vis-03.png
  multibody/hydroelastics/images/drake-vis-04.png
  multibody/hydroelastics/images/drake-vis-05.png
  multibody/hydroelastics/images/drake-vis-06.png
  multibody/hydroelastics/images/drake-vis-07.png
Labels: type: documentation, release notes: none

#16498 [fem] Move SchurComplement out of dev
  multibody/fem/BUILD.bazel
  multibody/fem/schur_complement.cc
  multibody/fem/schur_complement.h
  multibody/fem/test/schur_complement_test.cc
Labels: release notes: none, component: softsim fem

#16546 WIP [workspace] fix macOS bazel 5 builds
  tools/macos.bazelrc
Labels: component: continuous integration, component: build system, release notes: yes

#16541 Rename RigidTransform::IsIdentityToEpsilon to IsNearlyIdentity
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
  geometry/optimization/test/hyperellipsoid_test.cc
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
Labels: type: feature request, team: dynamics, priority: medium, status: squashing now, component: multibody plant, release notes: newly deprecated

#16549 [doc,geometry,multibody] Add refs to Hydroelastic User Guide
  geometry/proximity_properties.h
  multibody/parsing/parsing_doxygen.h
Labels: release notes: none

#16526 [geometry] Add support for SceneGraph<Expression>
  bindings/pydrake/geometry_py_scene_graph.cc
  bindings/pydrake/test/geometry_scene_graph_test.py
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/proximity/distance_to_point_callback.cc
  geometry/proximity/distance_to_point_callback.h
  geometry/proximity/distance_to_shape_callback.cc
  geometry/proximity/distance_to_shape_callback.h
  geometry/proximity/penetration_as_point_pair_callback.cc
  geometry/proximity/test/characterization_utilities.cc
  geometry/proximity/test/distance_to_point_callback_test.cc
  geometry/proximity/test/distance_to_shape_characterize_test.cc
  geometry/proximity/test/penetration_as_point_pair_callback_test.cc
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/query_object.cc
  geometry/query_object.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/scene_graph_inspector.cc
  geometry/test/geometry_state_test.cc
  geometry/test/proximity_engine_test.cc
  geometry/test/query_object_test.cc
  geometry/test/scene_graph_test.cc
  geometry/test/utilities_test.cc
  geometry/utilities.h
  math/rotation_matrix.cc
  math/rotation_matrix.h
  math/test/rotation_matrix_test.cc
  systems/sensors/rgbd_sensor.cc
  systems/sensors/rgbd_sensor.h
  systems/sensors/test/rgbd_sensor_test.cc
Labels: status: commits are properly curated, release notes: yes

#16537 [doc] Add release notes v0.39.0
  doc/_pages/from_binary.md
  doc/_release-notes/v0.39.0.md
Labels: release notes: none

#16544 Suppress vtkRenderWindow TSAN warning
  tools/dynamic_analysis/tsan.supp
Labels: status: single reviewer ok, release notes: none

#16525 [multibody] Parse MuJoCo joint elements
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: none

#16504 [geometry/dev] Only use one endpoint between the client and server.
  geometry/render/dev/render_client.cc
  geometry/render/dev/render_client.h
  geometry/render/dev/render_client_gltf.cc
  geometry/render/dev/render_client_gltf.h
  geometry/render/dev/render_client_gltf_factory.h
  geometry/render/dev/render_server/README.md
  geometry/render/dev/render_server/gltf_render_server.py
Labels: status: single reviewer ok, release notes: none

#16555 [doc] Fix markup in v0.39.0 release notes
  doc/_release-notes/v0.39.0.md
Labels: priority: emergency, status: single reviewer ok, release notes: none

#16533 [geometry/dev] cleanup gltf UpdateViewpoint transform modification
  geometry/render/dev/render_client_gltf.cc
Labels: status: single reviewer ok, release notes: none

#16559 [pydrake/examples] store visualizer return for args.playback
  bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py
Labels: status: single reviewer ok, release notes: none

#16552 Replace RotationMatrix::IsIdentityToInternalTolerance() with RotationMatrix::IsNearlyIdentity().
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
  math/rigid_transform.h
  math/rotation_matrix.h
  math/test/rigid_transform_test.cc
  math/test/rotation_matrix_test.cc
Labels: team: dynamics, type: design, priority: medium, status: squashing now, component: multibody plant, release notes: newly deprecated

#16539 Switch documentation and mirroring builds to Ubuntu 20.04 Focal
  doc/_pages/documentation_instructions.md
  doc/_pages/release_playbook.md
  tools/workspace/mirror_to_s3.py
Labels: status: single reviewer ok, release notes: none

#16567 Split out IrisInConfigurationSpaceTest
  geometry/optimization/BUILD.bazel
  geometry/optimization/test/iris_in_configuration_space_test.cc
  geometry/optimization/test/iris_test.cc
Labels: release notes: none

#16563 [framework] Add DiagramBuilder::ConnectToSame sugar
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  multibody/meshcat/contact_visualizer.cc
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
  systems/framework/test/diagram_builder_test.cc
Labels: priority: low, release notes: yes

#16548 Introduce SapContactProblem
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/sap_contact_problem.h
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
Labels: component: multibody plant, release notes: none

#16550 [fem] Move Petsc matrix out of dev
  multibody/fem/BUILD.bazel
  multibody/fem/petsc_symmetric_block_sparse_matrix.cc
  multibody/fem/petsc_symmetric_block_sparse_matrix.h
  multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc
  multibody/fixed_fem/dev/BUILD.bazel
Labels: release notes: none, component: softsim fem

#16557 Update valgrind builds to use Focal
  doc/_pages/jenkins.md
  tools/dynamic_analysis/drd.sh
  tools/dynamic_analysis/helgrind.sh
  tools/dynamic_analysis/valgrind.sh
Labels: status: single reviewer ok, release notes: yes

#16572 [primitives] Add (optional) gradients to MultilayerPerceptron::BatchOutput
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/multilayer_perceptron.cc
  systems/primitives/multilayer_perceptron.h
  systems/primitives/test/multilayer_perceptron_test.cc
Labels: release notes: yes

#16562 [fem] Move constitutive model test utils out of dev
  multibody/fem/BUILD.bazel
  multibody/fem/test/constitutive_model_test_utilities.cc
  multibody/fem/test/constitutive_model_test_utilities.h
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/test/corotated_model_test.cc
  multibody/fixed_fem/dev/test/linear_constitutive_model_test.cc
Labels: release notes: none, component: softsim fem

#16585 [plant] Enable AddMultibodyPlantSceneGraph for Expression
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
Labels: priority: low, release notes: yes

#16583 [pydrake] Stop installing useless bazel py_binary stubs
  bindings/pydrake/examples/multibody/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#16573 [pydrake] Add bindings for InvertAndCompose
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
Labels: status: single reviewer ok, release notes: yes

#16553 Implements SapConstraint
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_constraint.cc
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/test/sap_constraint_test.cc
Labels: team: dynamics, release notes: none

#16588 [doc] Clarify instructions for Bazel running with flags
  doc/_pages/bazel.md
  doc/_pages/from_source.md
Labels: priority: low, status: single reviewer ok, release notes: none

#16547 [doc] Add stability policy
  doc/_pages/installation.md
  doc/_pages/reviewable.md
  doc/_pages/stable.md
Labels: priority: medium, release notes: yes

#16576 [doc] Use ™ on MOSEK and always capitalize it
  doc/_pages/apt.md
  doc/_pages/bazel.md
  doc/_pages/docker.md
  doc/_pages/from_binary.md
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_pages/tm.md
  doc/_release-notes/v0.13.0.md
  doc/_release-notes/v0.25.0.md
  doc/_release-notes/v0.26.0.md
  doc/_release-notes/v0.39.0.md
  doc/defs.py
  doc/doxygen_cxx/build.py
  doc/pages.py
  doc/pydrake/build.py
  solvers/constraint.h
  solvers/mathematical_program.h
  solvers/mathematical_program_doxygen.h
  solvers/mathematical_program_result.h
  solvers/mosek_solver.h
  solvers/solver_options.h
  tools/bazel.rc
  tools/install/check_licenses.bzl
  tools/jupyter/jupyter_bazel.py
  tools/skylark/test_tags.bzl
  tools/workspace/mosek/repository.bzl
  tutorials/linear_program.ipynb
  tutorials/quadratic_program.ipynb
Labels: priority: low, release notes: none

#16598 [doc] Fix Jekyll output to avoid symlinks
  doc/defs.py
  doc/pages.py
Labels: priority: emergency, status: single reviewer ok, release notes: none

#16594 [parsing] Fix mis-parse of collision filter groups
  multibody/parsing/detail_common.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/sdf_parser_test/collision_filter_group_parsing_test.sdf
  multibody/parsing/test/urdf_parser_test/collision_filter_group_parsing_test.urdf
Labels: release notes: yes

#16599 [doc] Fix Jekyll output to avoid symlinks, part deux
  doc/styleguide/build.py
Labels: priority: emergency, status: single reviewer ok, release notes: none

#16600 [doc] Update build cop play book to check github pages
  doc/_pages/buildcop.md
Labels: release notes: none

#16569 [multibody] By default, use hydroelastic contact with fallback.
  multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_config.h
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: type: feature request, team: dynamics, component: multibody plant, release notes: yes

#16570 [SAP] Implements ContactProblemGraph
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/contact_problem_graph.cc
  multibody/contact_solvers/sap/contact_problem_graph.h
  multibody/contact_solvers/sap/test/contact_problem_graph_test.cc
Labels: team: dynamics, release notes: none

#16597 [fem] Add unit test for CorotatedModelData
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/test/corotated_model_data_test.cc
Labels: status: single reviewer ok, release notes: none, component: softsim fem

#16591 [geometry] Don't include geometry_state.h publicly
  examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
  geometry/query_object.cc
  geometry/query_object.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/scene_graph_inspector.cc
  geometry/scene_graph_inspector.h
  geometry/test/drake_visualizer_test.cc
  geometry/test/query_object_test.cc
  geometry/test/scene_graph_inspector_test.cc
  geometry/test/scene_graph_test.cc
  multibody/contact_solvers/test/multibody_sim_driver.cc
  multibody/hydroelastics/hydroelastic_engine.cc
  multibody/hydroelastics/test/hydroelastic_engine_test.cc
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: low, release notes: none

#16586 [fem] Move LinearConstitutiveModel out of dev
  multibody/fem/BUILD.bazel
  multibody/fem/linear_constitutive_model.cc
  multibody/fem/linear_constitutive_model.h
  multibody/fem/linear_constitutive_model_data.h
  multibody/fem/test/constitutive_model_test_utilities.cc
  multibody/fem/test/linear_constitutive_model_test.cc
  multibody/fixed_fem/dev/BUILD.bazel
Labels: release notes: none, component: softsim fem

#16185 [workspace] Use libjchart2d-java from apt on Ubuntu
  setup/ubuntu/binary_distribution/packages-bionic.txt
  setup/ubuntu/binary_distribution/packages-focal.txt
  third_party/BUILD.bazel
  third_party/net_sf_jchart2d/LICENSE
  tools/install/install.bzl
  tools/install/installer.py
  tools/workspace/BUILD.bazel
  tools/workspace/com_jidesoft_jide_oss/repository.bzl
  tools/workspace/commons_io/repository.bzl
  tools/workspace/java.bzl
  tools/workspace/lcm/lcm-config.cmake
  tools/workspace/net_sf_jchart2d/BUILD.bazel
  tools/workspace/net_sf_jchart2d/jchart2d-config-version.cmake
  tools/workspace/net_sf_jchart2d/jchart2d-config.cmake
  tools/workspace/net_sf_jchart2d/repository.bzl
  tools/workspace/org_apache_xmlgraphics_commons/repository.bzl
Labels: priority: low, release notes: yes

#16613 [workspace] Nerf the license checker for jar files
  tools/install/check_licenses.bzl
  tools/workspace/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok, release notes: none

#16609 [geometry/dev] rename RenderClientGltf => RenderEngineGltfClient
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/render_client.h
  geometry/render/dev/render_client_gltf_factory.cc
  geometry/render/dev/render_engine_gltf_client.cc
  geometry/render/dev/render_engine_gltf_client.h
  geometry/render/dev/render_engine_gltf_client_factory.cc
  geometry/render/dev/render_engine_gltf_client_factory.h
  geometry/render/dev/render_engine_vtk_minimal_example.cc
  geometry/render/render_engine_vtk.h
Labels: release notes: none

#16608 [parsing] Simplify use of scene graph in parsing
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_mujoco_parser.h
  multibody/parsing/detail_scene_graph.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_sdf_parser.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: status: single reviewer ok, release notes: none

#16614 [wheel] Hotfix to add now-missing jchart2d dependency
  tools/wheel/image/packages-bionic
  tools/wheel/image/packages-focal
Labels: priority: high, status: single reviewer ok, release notes: none

#16619 Allow start_new_change_event() on const Context
  systems/framework/cache_entry.h
  systems/framework/context_base.h
  systems/framework/test/diagram_context_test.cc
Labels: type: bug, priority: low, team: dynamics, component: system framework, release notes: yes

#16603 [geometry] Add in place transform for volume mesh
  geometry/proximity/BUILD.bazel
  geometry/proximity/test/volume_mesh_test.cc
  geometry/proximity/volume_mesh.cc
  geometry/proximity/volume_mesh.h
  multibody/fixed_fem/dev/mesh_utilities.cc
Labels: component: geometry general, release notes: yes

#16577 [pydrake] Overhaul logging configuration
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/__init__.py
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/text_logging_example.py
  bindings/pydrake/common/test/text_logging_test.py
  bindings/pydrake/common/test/text_logging_test_py.cc
  bindings/pydrake/common/test_utilities/meta.py
  bindings/pydrake/common/text_logging_pybind.cc
  bindings/pydrake/common/text_logging_pybind.h
  bindings/pydrake/test/text_logging_example.py
  bindings/pydrake/test/text_logging_test.py
  bindings/pydrake/visualization/meldis.py
  common/text_logging.h
Labels: priority: medium, release notes: yes

#16605 [primitives] Support sin/cos input features in MultilayerPerceptron.
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/multilayer_perceptron.cc
  systems/primitives/multilayer_perceptron.h
  systems/primitives/test/multilayer_perceptron_test.cc
Labels: release notes: yes

#16397 [geometry/optimization] Add two-cycle constraint to Shortest Path formulation
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/minkowski_sum.h
  geometry/optimization/point.cc
  geometry/optimization/point.h
  geometry/optimization/test/cartesian_product_test.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/optimization/test/hyperellipsoid_test.cc
  geometry/optimization/test/minkowski_sum_test.cc
  geometry/optimization/test/point_test.cc
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: status: commits are properly curated, release notes: yes

#16632 [pydrake/common] Bind __index__ for TypeSafeIndex
  bindings/pydrake/common/type_safe_index_pybind.h
  bindings/pydrake/systems/test/controllers_test.py
Labels: status: single reviewer ok, release notes: yes

#16637 [common] Add TODO for IsAffine bug
  common/symbolic_expression.cc
Labels: priority: low, release notes: none

#16633 [common] Give RandomGenerator efficient default and move constructors
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/module_test.py
  common/BUILD.bazel
  common/random.cc
  common/random.h
  common/test/random_test.cc
Labels: priority: low, release notes: yes

#16631 PositionConstraint can update lower and upper bounds
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  multibody/inverse_kinematics/position_constraint.h
  multibody/inverse_kinematics/test/position_constraint_test.cc
  solvers/constraint.h
Labels: priority: low, release notes: yes

#16610 [parsing] Rename detail_scene_graph ==> detail_sdf_geometry
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: release notes: none

#15490 [performance] Rewrite benchmark_tool infrastructure
  examples/acrobot/BUILD.bazel
  examples/multibody/cassie_benchmark/BUILD.bazel
  examples/multibody/cassie_benchmark/README.md
  examples/multibody/cassie_benchmark/conduct_experiment
  examples/multibody/cassie_benchmark/copy_results_to
  examples/multibody/cassie_benchmark/record_results.sh
  geometry/benchmarking/README.md
  systems/benchmarking/BUILD.bazel
  systems/benchmarking/README.md
  tools/performance/BUILD.bazel
  tools/performance/README.md
  tools/performance/benchmark_tool.py
  tools/performance/defs.bzl
  tools/performance/record_results.py
  tools/workspace/cc/BUILD.bazel
Labels: priority: low, release notes: none

#16616 [geometry/optimization] Add optional solver and solver options to SolveShortestPath
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: yes

#16618 [SAP] Implements SapContactProblem::AddConstraint()
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/contact_problem_graph.h
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/sap_contact_problem.h
  multibody/contact_solvers/sap/test/contact_problem_graph_test.cc
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
Labels: team: dynamics, release notes: none

#16621 [common] Add if_then_else overload for Eigen::Vector
  common/BUILD.bazel
  common/drake_bool.h
  common/test/drake_bool_test.cc
  math/quaternion.h
  math/rotation_matrix.h
  systems/primitives/discrete_derivative.cc
Labels: priority: backlog, status: single reviewer ok, release notes: yes

#16622 [setup] Restructure Ubuntu dependencies on clang-9
  setup/BUILD.bazel
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/packages-bionic-clang.txt
  setup/ubuntu/source_distribution/packages-bionic.txt
  setup/ubuntu/source_distribution/packages-focal-clang.txt
  setup/ubuntu/source_distribution/packages-focal.txt
Labels: priority: medium, release notes: yes

#16638 [geometry] Add URL customization to Meshcat ctor
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/test/geometry_visualizers_test.py
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/meshcat.html
  geometry/test/meshcat_test.cc
Labels: priority: high, release notes: yes

#16628 [pydrake/geometry] Make ConvexSets picklable
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
Labels: release notes: yes

#16617 [fem] Move corotated model out of dev
  multibody/fem/BUILD.bazel
  multibody/fem/corotated_model.cc
  multibody/fem/corotated_model.h
  multibody/fem/corotated_model_data.cc
  multibody/fem/corotated_model_data.h
  multibody/fem/test/constitutive_model_test_utilities.cc
  multibody/fem/test/corotated_model_data_test.cc
  multibody/fem/test/corotated_model_test.cc
  multibody/fixed_fem/dev/BUILD.bazel
Labels: release notes: none, component: softsim fem

#16646 Fix asan_everything config
  tools/dynamic_analysis/bazel.rc
Labels: status: single reviewer ok, release notes: none

#16641 [common] Introduce diagnostic policy module
  common/BUILD.bazel
  common/diagnostic_policy.cc
  common/diagnostic_policy.h
  common/test/diagnostic_policy_test.cc
Labels: release notes: none

#16645 [analysis] Tidy up monte_carlo implementation
  systems/analysis/monte_carlo.cc
  systems/analysis/monte_carlo.h
Labels: priority: low, status: single reviewer ok, release notes: none

#16647 [fem] Remove unused files in fixed_fem/dev
  multibody/fixed_fem/dev/BUILD.bazel
  multibody/fixed_fem/dev/calc_lame_parameters.cc
  multibody/fixed_fem/dev/calc_lame_parameters.h
  multibody/fixed_fem/dev/collision_objects.cc
  multibody/fixed_fem/dev/collision_objects.h
  multibody/fixed_fem/dev/element_cache_entry.h
  multibody/fixed_fem/dev/schur_complement.cc
  multibody/fixed_fem/dev/schur_complement.h
  multibody/fixed_fem/dev/test/collision_objects_test.cc
  multibody/fixed_fem/dev/test/hyperelastic_constitutive_model_test.cc
  multibody/fixed_fem/dev/test/schur_complement_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none, component: softsim fem

#16595 [geometry/dev] drop gunicorn for single threaded flask server
  geometry/render/dev/BUILD.bazel
  geometry/render/dev/render_server/README.md
  geometry/render/dev/render_server/gltf_render_server.py
  geometry/render/dev/render_server/wsgi.py
Labels: status: single reviewer ok, release notes: none

#16568 [doc] Withdraw tutorials from Colab
  bindings/pydrake/_geometry_extra.py
  bindings/pydrake/test/geometry_visualizers_test.py
  doc/_pages/getting_help.md
  tools/install/colab/README.md
  tutorials/README.md
  tutorials/linear_program.ipynb
  tutorials/mathematical_program.ipynb
  tutorials/quadratic_program.ipynb
Labels: priority: medium, release notes: yes

#16644 [tutorials] Install tutorials in binary releases
  BUILD.bazel
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/tutorials.py
  doc/pydrake/build.py
  tools/install/bazel/generate_installed_files_manifest.bzl
  tools/wheel/image/build-wheel.sh
  tutorials/BUILD.bazel
  tutorials/README.md
Labels: priority: medium, release notes: yes

#16629 [geometry/optimization] Add Intersection Convex Set
  bindings/pydrake/geometry_py_optimization.cc
  bindings/pydrake/test/geometry_optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/intersection.cc
  geometry/optimization/intersection.h
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/optimization/test/intersection_test.cc
Labels: release notes: yes

#16639 [pydrake] Add proxy feature for MeshCat on Deepnote
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/_geometry_extra.py
  setup/BUILD.bazel
  setup/deepnote/README.md
  setup/deepnote/install_nginx
  setup/deepnote/nginx-meshcat-proxy.conf
  tools/install/bazel/generate_installed_files_manifest.bzl
  tools/skylark/pybind.bzl
  tools/wheel/image/build-wheel.sh
Labels: priority: high, release notes: none

#16651 [geometry] Fix a doxygen doc bug
  geometry/geometry_set.h
Labels: status: single reviewer ok, release notes: none

#16650 [parsing] Introduce parsing workspace
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_parsing_workspace.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: release notes: none

#16655 [multibody] Add plant getter to Parser
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  multibody/parsing/parser.h
  multibody/parsing/test/parser_test.cc
Labels: priority: low, status: single reviewer ok, release notes: yes

#16657 [analysis] Don't Initialize during MakeSimulatorFromGflags
  systems/analysis/simulator_gflags.cc
Labels: priority: high, status: single reviewer ok, release notes: yes

#15804 [examples: hydroelastic] A compliant ball on a rigid plate mesh from SDF file.
  examples/hydroelastic/ball_plate/BUILD.bazel
  examples/hydroelastic/ball_plate/README.md
  examples/hydroelastic/ball_plate/ball_plate_run_dynamics.cc
  examples/hydroelastic/ball_plate/floor.sdf
  examples/hydroelastic/ball_plate/images/ball_plate.jpg
  examples/hydroelastic/ball_plate/images/ball_plate_contact_polygons.jpg
  examples/hydroelastic/ball_plate/images/ball_plate_contact_triangles.jpg
  examples/hydroelastic/ball_plate/images/ball_plate_hydroelastic_contact_visualization_settings.jpg
  examples/hydroelastic/ball_plate/make_ball_plate_plant.cc
  examples/hydroelastic/ball_plate/make_ball_plate_plant.h
  examples/hydroelastic/ball_plate/plate_8in.sdf
  examples/hydroelastic/ball_plate/plate_8in_col.mtl
  examples/hydroelastic/ball_plate/plate_8in_col.obj
Labels: team: dynamics, priority: medium, status: squashing now, release notes: yes

#16654 [geometry] Add host name option to MeshcatParams
  bindings/pydrake/geometry_py_visualizers.cc
  bindings/pydrake/test/geometry_visualizers_test.py
  bindings/pydrake/visualization/meldis.py
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/test/meshcat_test.cc
Labels: priority: low, release notes: yes

#16630 [parsing] Support actuator/motor tags in MuJoCo parser
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: none

#16662 [geometry] Factor our uWS callbacks for readability
  geometry/meshcat.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#16660 [pydrake] Hotfix unit test for localhost vs *
  bindings/pydrake/test/geometry_visualizers_test.py
Labels: priority: emergency, status: single reviewer ok, release notes: none

#16664 [geometry] Centralize Meshcat's calls to defer()
  geometry/meshcat.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#16661 py math: Fix missing default for RotationMatrix.IsNearlyIdentity()
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
Labels: status: single reviewer ok, release notes: none

#16667 [geometry] Centralize Meshcat's checks for a null loop
  geometry/meshcat.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#16666 Replace `"${var[@]:-}"` with `"${var[@]}"`
  setup/mac/install_prereqs.sh
  setup/ubuntu/install_prereqs.sh
Labels: priority: low, status: single reviewer ok, release notes: none

#16625 Implement a pybind11 type_caster for drake::EigenPtr
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/eigen_pybind.h
  bindings/pydrake/common/test/eigen_pybind_test.py
  bindings/pydrake/common/test/eigen_pybind_test_util_py.cc
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/mathematicalprogram_py.cc
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/primitives_py.cc
Labels: status: commits are properly curated, release notes: none

#16665 [doc] Website enhancements
  doc/_includes/header.html
  doc/_layouts/default.html
  doc/assets/css/main.css
  doc/assets/js/search.js
  doc/index.md
Labels: priority: high, release notes: none

#16672 Partially revert "Replace `"${var[@]:-}"` with `"${var[@]}"`"
  setup/mac/install_prereqs.sh
Labels: status: single reviewer ok, release notes: none

#16681 [geometry] Refactor Meshcat to strictly obey PIMPL
  geometry/meshcat.cc
  geometry/meshcat.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#16658 [pydrake] Add missing config files for MeshCat proxy on Deepnote
  tools/install/dockerhub/focal/Dockerfile
Labels: priority: medium, status: single reviewer ok, release notes: none

#16682 [geometry] Rename Meshcat::Impl and use const-correct accessors
  geometry/meshcat.cc
  geometry/meshcat.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#16649 [doc] Highlight Anaconda incompatibility in the installation docs
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_pages/python_bindings.md
Labels: priority: low, release notes: none

#16656 deprecate tkinter
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/all.py
  bindings/pydrake/manipulation/simple_ui.py
  bindings/pydrake/manipulation/test/simple_ui_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/all.py
  bindings/pydrake/systems/system_sliders.py
  bindings/pydrake/systems/test/system_sliders_test.py
  doc/_pages/pip.md
  tools/wheel/test/provision.sh
Labels: release notes: newly deprecated

#16677 [parsing] Clean up some path handling
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/detail_path_utils.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/parser.cc
  multibody/parsing/test/detail_common_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/parsing/test/detail_path_utils_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/parser_test.cc
Labels: release notes: none

#16350 Clarify and consolidate documentation for SpatialVelocity class.
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/test/math_test.py
  multibody/math/spatial_force.h
  multibody/math/spatial_momentum.h
  multibody/math/spatial_velocity.h
Labels: type: documentation, team: dynamics, priority: medium, status: squashing now, component: multibody plant, release notes: newly deprecated

#16596 Introduces PartialPermutation
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/partial_permutation.cc
  multibody/contact_solvers/sap/partial_permutation.h
  multibody/contact_solvers/sap/test/partial_permutation_test.cc
Labels: team: dynamics, release notes: none
