Repository RobotLocomotion/drake, pull requests merged in 2023-10, with the labels that each got.

#20285 [render] Parsing an .obj file can produce multiple RenderMesh instances
  geometry/render/render_mesh.cc
  geometry/render/render_mesh.h
  geometry/render/test/render_mesh_test.cc
Labels: status: squashing now, status: single reviewer ok, release notes: none

#20291 [optimization] Remove deprecated code 2023-10
  geometry/optimization/cspace_separating_plane.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#20293 [doc] Add links to experimental Jenkins bot commands
  doc/_pages/jenkins.md
Labels: status: single reviewer ok, release notes: none

#20292 [workspace] Nerf new_release for rust crates
  tools/workspace/new_release.py
Labels: priority: low, status: single reviewer ok, release notes: none

#20276 [workspace] Build libpng_internal from source
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/png.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/libpng/repository.bzl
  tools/workspace/libpng_internal/BUILD.bazel
  tools/workspace/libpng_internal/package.BUILD.bazel
  tools/workspace/libpng_internal/png_drake_vendor.h
  tools/workspace/libpng_internal/repository.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: low, release notes: newly deprecated, release notes: feature

#20270 [geometry] Indicate Meshcat connections in System graphviz output
  geometry/BUILD.bazel
  geometry/meshcat_graphviz.cc
  geometry/meshcat_graphviz.h
  geometry/meshcat_point_cloud_visualizer.cc
  geometry/meshcat_point_cloud_visualizer.h
  geometry/meshcat_visualizer.cc
  geometry/meshcat_visualizer.h
  geometry/test/meshcat_graphviz_test.cc
  geometry/test/meshcat_point_cloud_visualizer_test.cc
  geometry/test/meshcat_visualizer_test.cc
  multibody/meshcat/BUILD.bazel
  multibody/meshcat/contact_visualizer.cc
  multibody/meshcat/contact_visualizer.h
  multibody/meshcat/joint_sliders.cc
  multibody/meshcat/joint_sliders.h
  multibody/meshcat/test/contact_visualizer_test.cc
  multibody/meshcat/test/joint_sliders_test.cc
  systems/framework/system_base.h
  visualization/BUILD.bazel
  visualization/meshcat_pose_sliders.cc
  visualization/meshcat_pose_sliders.h
  visualization/test/meshcat_pose_sliders_test.cc
Labels: priority: medium, release notes: feature

#20035 [framework] Propagate EventStatus through the API
  bindings/pydrake/systems/test/test_util_py.cc
  geometry/test/meshcat_visualizer_test.cc
  systems/analysis/simulator.cc
  systems/analysis/simulator.h
  systems/analysis/test/simulator_test.cc
  systems/framework/BUILD.bazel
  systems/framework/context_base.h
  systems/framework/diagram.cc
  systems/framework/diagram.h
  systems/framework/event_status.cc
  systems/framework/event_status.h
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/event_deprecated_test.cc
  systems/framework/test/event_status_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/system_test.cc
  systems/lcm/test/lcm_publisher_system_test.cc
  systems/lcm/test/lcm_subscriber_system_test.cc
  systems/sensors/test/image_writer_test.cc
  systems/sensors/test/rgbd_sensor_async_test.cc
Labels: priority: low, release notes: breaking change, release notes: feature

#20305 [sensors] RgbdSensor now passes the correct camera pose
  systems/sensors/rgbd_sensor.cc
  systems/sensors/test/rgbd_sensor_test.cc
Labels: release notes: fix

#20304 Upgrade Externals October 2023
  tools/workspace/build_bazel_apple_support/repository.bzl
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/rules_rust/repository.bzl
  tools/workspace/suitesparse_internal/repository.bzl
  tools/workspace/typing_extensions_internal/repository.bzl
  tools/workspace/yaml_cpp_internal/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#20303 [workspace] Upgrade sdformat_internal, gz_utils_internal to latest
  multibody/parsing/detail_sdf_parser.cc
  tools/workspace/gz_utils_internal/package.BUILD.bazel
  tools/workspace/gz_utils_internal/repository.bzl
  tools/workspace/sdformat_internal/package.BUILD.bazel
  tools/workspace/sdformat_internal/repository.bzl
  tools/workspace/sdformat_internal/test/gz_sdf_test.py
Labels: release notes: fix

#20299 [wheel] Add Python 3.12 manylinux support
  doc/_pages/installation.md
  doc/_pages/release_playbook.md
  tools/release_engineering/download_release_candidate.py
  tools/wheel/wheel_builder/linux.py
  tools/workspace/python/repository.bzl
Labels: priority: low, release notes: feature

#20272 RenderEngineGl supports multiple meshes from OBJ
  geometry/render/test/meshes/rainbow_box.mtl
  geometry/render/test/meshes/rainbow_box.obj
  geometry/render/test/meshes/rainbow_stripes.png
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_opengl_geometry.h
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/test/internal_opengl_geometry_test.cc
  geometry/render_gl/test/internal_render_engine_gl_test.cc
Labels: release notes: feature

#20297 Bug fix for deformable fixed constraints
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/test/deformable_fixed_constraint_test.cc
  multibody/plant/test/deformable_model_test.cc
Labels: release notes: none

#20289 [math] Clarify implementation of fast pose composition functions
  math/fast_pose_composition_functions_avx2_fma.cc
Labels: priority: low, release notes: none

#20282 Deprecate MinimumDistanceConstraint.
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/test/evaluators_test.py
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/minimum_distance_constraint.cc
  multibody/inverse_kinematics/minimum_distance_constraint.h
  multibody/inverse_kinematics/minimum_distance_lower_bound_constraint.cc
  multibody/inverse_kinematics/minimum_distance_lower_bound_constraint.h
  multibody/inverse_kinematics/minimum_distance_upper_bound_constraint.cc
  multibody/inverse_kinematics/minimum_distance_upper_bound_constraint.h
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
  solvers/minimum_value_constraint.h
  solvers/test/minimum_value_constraint_test.cc
Labels: release notes: newly deprecated, release notes: feature

#20302 [workspace] Upgrade curl_internal to latest release curl-8_3_0
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/package.BUILD.bazel
  tools/workspace/curl_internal/repository.bzl
Labels: priority: low, status: squashing now, status: single reviewer ok, release notes: fix

#20279 [tools] Add test to flag hazardous exported symbols
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/test/exported_symbols_test.py
Labels: priority: low, release notes: none

#20283 Actuate the iiwa in the hardware_sim example
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/README.md
  examples/hardware_sim/example_scenarios.yaml
  examples/hardware_sim/robot_commander.py
  examples/hardware_sim/test/robot_commander_test.py
Labels: release notes: none

#20308 [lcm] Remove spurious deps from library code
  examples/multibody/acrobot/BUILD.bazel
  examples/multibody/cylinder_with_multicontact/BUILD.bazel
  examples/multibody/inclined_plane_with_body/BUILD.bazel
  examples/multibody/pendulum/BUILD.bazel
  examples/multibody/rolling_sphere/BUILD.bazel
  examples/scene_graph/BUILD.bazel
  geometry/BUILD.bazel
  geometry/profiling/BUILD.bazel
  geometry/render_gltf_client/BUILD.bazel
  manipulation/kuka_iiwa/BUILD.bazel
  manipulation/schunk_wsg/BUILD.bazel
  multibody/plant/BUILD.bazel
  systems/lcm/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#20247 [systems/lcm] Add protocol for opting out of LCM messaging
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/test/lcm_test.py
  manipulation/kuka_iiwa/build_iiwa_control.cc
  manipulation/kuka_iiwa/build_iiwa_control.h
  manipulation/kuka_iiwa/iiwa_driver_functions.cc
  manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
  manipulation/kuka_iiwa/test/iiwa_driver_functions_test.cc
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_buses.h
  systems/lcm/lcm_config_functions.cc
  systems/lcm/lcm_config_functions.h
  systems/lcm/test/lcm_config_functions_test.cc
Labels: priority: medium, release notes: feature

#20309 [multibody] Remove the unused provision for a Joint to be modeled with multiple Mobilizers
  multibody/plant/test/sap_driver_multidof_joints_test.cc
  multibody/tree/ball_rpy_joint.cc
  multibody/tree/ball_rpy_joint.h
  multibody/tree/joint.cc
  multibody/tree/joint.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/planar_joint.cc
  multibody/tree/planar_joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/quaternion_floating_joint.cc
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_joint.h
  multibody/tree/screw_joint.cc
  multibody/tree/screw_joint.h
  multibody/tree/universal_joint.cc
  multibody/tree/universal_joint.h
  multibody/tree/weld_joint.cc
  multibody/tree/weld_joint.h
Labels: priority: medium, release notes: none

#20312 Extend MatrixBlock::LeftMultiplyByBlockDiagonal()
  multibody/contact_solvers/matrix_block.cc
  multibody/contact_solvers/matrix_block.h
  multibody/contact_solvers/test/matrix_block_test.cc
  multibody/plant/deformable_driver.cc
Labels: release notes: none

#20315 [wheel] Save time by not compressing drake-src
  tools/wheel/Dockerfile
  tools/wheel/wheel_builder/linux.py
Labels: priority: medium, release notes: none

#20307 [multibody] Implements MultibodyTreeSystem::SetDefaultParameters
  multibody/plant/test/multibody_plant_reflected_inertia_test.cc
  multibody/tree/body.h
  multibody/tree/fixed_offset_frame.h
  multibody/tree/force_element.h
  multibody/tree/frame.h
  multibody/tree/joint_actuator.h
  multibody/tree/linear_bushing_roll_pitch_yaw.h
  multibody/tree/mobilizer.h
  multibody/tree/multibody_element.cc
  multibody/tree/multibody_element.h
  multibody/tree/multibody_tree_system.cc
  multibody/tree/multibody_tree_system.h
  multibody/tree/rigid_body.h
Labels: release notes: fix

#20235 [render] RenderEngineVtk supports multiple meshes from OBJ
  geometry/geometry_file_formats_doxygen.h
  geometry/render/render_mesh.cc
  geometry/render/render_mesh.h
  geometry/render/test/render_mesh_test.cc
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
Labels: status: squashing now, release notes: feature

#20318 [tools] Nerf the symbol visibility test when Clarabel is enabled
  tools/install/libdrake/BUILD.bazel
  tools/workspace/clarabel_cpp_internal/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#20311 [tools] Improve single point of control for Python interpreter
  CMakeLists.txt
  cmake/WORKSPACE.in
  cmake/external/workspace/cmake_python/BUILD.bazel.in
  tools/install/install_test_helper.py
  tools/py_toolchain/BUILD.bazel
  tools/py_toolchain/interpreter_paths.bzl
  tools/ubuntu.bazelrc
  tools/wheel/Dockerfile
  tools/wheel/image/build-drake.sh
  tools/wheel/image/pip-drake.patch
  tools/wheel/macos/build-wheel.sh
  tools/wheel/wheel_builder/linux.py
  tools/workspace/default.bzl
  tools/workspace/python/repository.bzl
Labels: priority: high, release notes: none

#20306 Make multibody/plant clang-format compliant
  multibody/plant/calc_distance_and_time_derivative.cc
  multibody/plant/contact_model_doxygen.h
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/contact_results_to_lcm.h
  multibody/plant/coulomb_friction.cc
  multibody/plant/coulomb_friction.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/externally_applied_spatial_force_multiplexer.cc
  multibody/plant/externally_applied_spatial_force_multiplexer.h
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/hydroelastic_traction_calculator.cc
  multibody/plant/hydroelastic_traction_calculator.h
  multibody/plant/internal_geometry_names.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_config_functions.cc
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/point_pair_contact_info.cc
  multibody/plant/point_pair_contact_info.h
  multibody/plant/propeller.cc
  multibody/plant/tamsi_solver.cc
  multibody/plant/tamsi_solver.h
  multibody/plant/test_utilities/rigid_body_on_compliant_ground.h
Labels: priority: low, release notes: none

#20319 Add SceneGraph::RemoveRenderer().
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/test/scene_graph_test.py
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/scene_graph_test.cc
Labels: release notes: feature

#20328 Work around test error in coverage builds (kcov 339)
  examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
Labels: status: single reviewer ok, release notes: none

#20310 [systems/lcm] Indicate LCM connections in System graphviz output
  geometry/BUILD.bazel
  geometry/drake_visualizer.cc
  geometry/drake_visualizer.h
  geometry/meshcat_graphviz.h
  geometry/test/drake_visualizer_test.cc
  manipulation/kuka_iiwa/test/iiwa_driver_functions_test.cc
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_config_functions.cc
  systems/lcm/lcm_interface_system.cc
  systems/lcm/lcm_interface_system.h
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/lcm_publisher_system.h
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/lcm_system_graphviz.cc
  systems/lcm/lcm_system_graphviz.h
  systems/lcm/test/lcm_config_functions_test.cc
  systems/lcm/test/lcm_interface_system_test.cc
  systems/lcm/test/lcm_publisher_system_test.cc
  systems/lcm/test/lcm_subscriber_system_test.cc
  systems/lcm/test/lcm_system_graphviz_test.cc
Labels: priority: medium, release notes: feature

#20332 [geometry] Fix clang warning in render_mesh
  geometry/render/render_mesh.cc
Labels: priority: backlog, status: single reviewer ok, release notes: none

#20335 [vtk] Remove dead code
  tools/workspace/vtk_internal/patches/rendering_opengl2_nobacktrace.patch
  tools/workspace/vtk_internal/repository.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#20334 [tools] Handle unusual `readelf` output in exported_symbols_test
  tools/install/libdrake/test/exported_symbols_test.py
Labels: status: single reviewer ok, release notes: none

#20337 [py visualization] Split out flaky visualizer reload test
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/test/model_visualizer_reload_test.py
  bindings/pydrake/visualization/test/model_visualizer_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#20330 [snopt] Nerf gfortran argument-mismatch errors into warnings
  tools/workspace/gfortran/repository.bzl
  tools/workspace/snopt/fortran-macos.bzl
  tools/workspace/snopt/fortran-ubuntu.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#20331 [workspace] Build libtiff_internal from source
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/libtiff.cmake
  tools/wheel/image/dependencies/projects/xz.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/libtiff/repository.bzl
  tools/workspace/libtiff_internal/BUILD.bazel
  tools/workspace/libtiff_internal/package.BUILD.bazel
  tools/workspace/libtiff_internal/repository.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: low, release notes: newly deprecated, release notes: fix

#20338 Port more event-handling code to modern API
  bindings/pydrake/systems/pyplot_visualizer.py
  examples/bouncing_ball/bouncing_ball.h
Labels: priority: medium, release notes: none

#20301 Add DeformableContactInfo to ContactResults
  multibody/plant/BUILD.bazel
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/deformable_contact_info.cc
  multibody/plant/deformable_contact_info.h
  multibody/plant/hydroelastic_quadrature_point_data.h
  multibody/plant/test/contact_results_test.cc
  multibody/plant/test/deformable_contact_info_test.cc
Labels: priority: medium, release notes: none

#20323 [geometry] Add zero_simplex_manual_test
  geometry/proximity/BUILD.bazel
  geometry/proximity/test/zero_simplex_manual_test.cc
Labels: release notes: none

#20325 [workspace] Add rust_toolchain externals
  WORKSPACE
  tools/workspace/default.bzl
  tools/workspace/rules_rust/repository.bzl
  tools/workspace/rust_toolchain/BUILD.bazel
  tools/workspace/rust_toolchain/README.md
  tools/workspace/rust_toolchain/lock/archives.bzl
  tools/workspace/rust_toolchain/lock/details/BUILD.rust_darwin_aarch64__aarch64-apple-darwin__stable.bazel
  tools/workspace/rust_toolchain/lock/details/BUILD.rust_darwin_aarch64__aarch64-apple-darwin__stable_tools.bazel
  tools/workspace/rust_toolchain/lock/details/BUILD.rust_darwin_x86_64__x86_64-apple-darwin__stable.bazel
  tools/workspace/rust_toolchain/lock/details/BUILD.rust_darwin_x86_64__x86_64-apple-darwin__stable_tools.bazel
  tools/workspace/rust_toolchain/lock/details/BUILD.rust_linux_aarch64__aarch64-unknown-linux-gnu__stable.bazel
  tools/workspace/rust_toolchain/lock/details/BUILD.rust_linux_aarch64__aarch64-unknown-linux-gnu__stable_tools.bazel
  tools/workspace/rust_toolchain/lock/details/BUILD.rust_linux_x86_64__x86_64-unknown-linux-gnu__stable.bazel
  tools/workspace/rust_toolchain/lock/details/BUILD.rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools.bazel
  tools/workspace/rust_toolchain/repository.bzl
  tools/workspace/rust_toolchain/upgrade.py
  tools/workspace/rust_toolchain/upgrade/BUILD.bazel
  tools/workspace/rust_toolchain/upgrade/WORKSPACE.bazel
  tools/workspace/rust_toolchain/upgrade/rules_rust_tracing.patch
Labels: priority: low, release notes: feature

#20353 [setup] Add nasm to source prereqs
  setup/mac/source_distribution/Brewfile
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  tools/wheel/image/packages-focal
  tools/wheel/image/packages-macos
Labels: priority: medium, status: single reviewer ok, release notes: fix

#20349 Make multibody/plant clang-format compliant
  multibody/plant/BUILD.bazel
  multibody/plant/test/applied_generalized_force_test.cc
  multibody/plant/test/compliant_contact_manager_tester.h
  multibody/plant/test/contact_properties_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/coulomb_friction_test.cc
  multibody/plant/test/deformable_boundary_condition_test.cc
  multibody/plant/test/deformable_driver_test.cc
  multibody/plant/test/deformable_integration_test.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/dummy_model.h
  multibody/plant/test/energy_and_power_test.cc
  multibody/plant/test/external_forces_test.cc
  multibody/plant/test/externally_applied_spatial_force_multiplexer_test.cc
  multibody/plant/test/externally_applied_spatial_force_test.cc
  multibody/plant/test/floating_body_test.cc
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/hydroelastic_traction_test.cc
  multibody/plant/test/inclined_plane_test.cc
  multibody/plant/test/internal_geometry_names_test.cc
  multibody/plant/test/joint_limits_test.cc
  multibody/plant/test/joint_locking_test.cc
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/plant/test/multibody_plant_com_test.cc
  multibody/plant/test/multibody_plant_config_functions_test.cc
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
  multibody/plant/test/multibody_plant_introspection_test.cc
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/plant/test/multibody_plant_kinematics_test.cc
  multibody/plant/test/multibody_plant_mass_matrix_test.cc
  multibody/plant/test/multibody_plant_momentum_energy_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/propeller_test.cc
  multibody/plant/test/sap_driver_distance_constraints_test.cc
  multibody/plant/test/slicing_and_indexing_test.cc
  multibody/plant/test/spring_mass_system_test.cc
  multibody/plant/test/tamsi_solver_test.cc
  multibody/plant/test/tamsi_solver_test_util.h
  multibody/plant/test/wing_test.cc
Labels: status: single reviewer ok, release notes: none

#20094 [framework] Deprecate LeafSystem update dispatcher overrides
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  systems/analysis/test/simulator_test.cc
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/vector_system_test.cc
  systems/framework/vector_system.cc
  systems/framework/vector_system.h
Labels: priority: low, release notes: newly deprecated

#20346 [workspace] Build VTK-vendored third-party code with hidden symbols
  tools/install/libdrake/test/exported_symbols_test.py
  tools/workspace/vtk_internal/patches/common_core_noutf8.patch
  tools/workspace/vtk_internal/patches/vtkdoubleconversion_hidden.patch
  tools/workspace/vtk_internal/patches/vtkglew_hidden.patch
  tools/workspace/vtk_internal/patches/vtkpugixml_hidden.patch
  tools/workspace/vtk_internal/repository.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: low, release notes: fix

#20351 [workspace] Deprecate the expat external
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  tools/workspace/default.bzl
  tools/workspace/expat/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#20273 DiscreteUpdateManager computes contact kinematics
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/sap_driver.cc
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/compliant_contact_manager_tester.h
  multibody/plant/test/deformable_boundary_condition_test.cc
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/deformable_driver_contact_test.cc
  multibody/plant/test/deformable_driver_test.cc
  multibody/plant/test/deformable_integration_test.cc
  multibody/plant/test/deformable_model_test.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
Labels: priority: medium, release notes: none

#20355 SceneGraph modifies/access renderer in the context.
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/test/scene_graph_test.py
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/scene_graph_test.cc
Labels: release notes: feature

#20357 [workspace] Use hidden symbols for tinyobjloader
  tools/install/libdrake/test/exported_symbols_test.py
  tools/workspace/BUILD.bazel
  tools/workspace/tinyobjloader_internal/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: fix

#20347 Avoid unnecessary re-computation of deformable sdf
  geometry/proximity/deformable_contact_internal.cc
  geometry/proximity/deformable_mesh_intersection.cc
  geometry/proximity/deformable_mesh_intersection.h
  geometry/proximity/test/deformable_contact_internal_test.cc
  geometry/proximity/test/deformable_mesh_intersection_test.cc
Labels: release notes: none

#20341 Add python binding for AffineSubspace::OrthogonalComplementBasis.
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
Labels: release notes: feature

#20352 [setup] Remove dependency on bzip2
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  tools/wheel/image/build-python.sh
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/bzip2.cmake
Labels: priority: low, release notes: fix

#20342 Tests for AffineSubspace::CalcVolume.
  geometry/optimization/affine_subspace.cc
  geometry/optimization/test/affine_subspace_test.cc
Labels: release notes: none

#20358 [workspace] Cull some unwanted ClpSolver code
  tools/install/libdrake/test/exported_symbols_test.py
  tools/workspace/clp_internal/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: fix

#20359 [workspace] Fix leaky symbol in abseil_cpp
  tools/install/libdrake/test/exported_symbols_test.py
  tools/workspace/abseil_cpp_internal/patches/inline_namespace.patch
Labels: priority: low, status: single reviewer ok, release notes: fix

#20329 [schunk_wsg] Opt-in to clang-format lint
  manipulation/schunk_wsg/BUILD.bazel
  manipulation/schunk_wsg/build_schunk_wsg_control.cc
  manipulation/schunk_wsg/build_schunk_wsg_control.h
  manipulation/schunk_wsg/schunk_wsg_constants.h
  manipulation/schunk_wsg/schunk_wsg_driver_functions.cc
  manipulation/schunk_wsg/schunk_wsg_lcm.cc
  manipulation/schunk_wsg/schunk_wsg_lcm.h
  manipulation/schunk_wsg/schunk_wsg_plain_controller.h
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator.h
  manipulation/schunk_wsg/test/schunk_wsg_controller_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_lcm_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
  manipulation/schunk_wsg/test/schunk_wsg_trajectory_generator_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#20317 Add Functions for adding DD and SDD dual cone constraints
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/BUILD.bazel
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/diagonally_dominant_dual_cone_matrix_test.cc
  solvers/test/scaled_diagonally_dominant_dual_cone_matrix_test.cc
Labels: status: squashing now, release notes: feature

#20371 [workspace] Install Qhull patches and required testimonials
  tools/workspace/coinutils_internal/defs.bzl
  tools/workspace/ipopt_internal_fromsource/package.BUILD.bazel
  tools/workspace/ipopt_internal_fromsource/test/lint_test.py
  tools/workspace/qhull_internal/BUILD.bazel
  tools/workspace/qhull_internal/package.BUILD.bazel
  tools/workspace/qhull_internal/patches/cxx20.patch
  tools/workspace/qhull_internal/patches/disable_dead_code.patch
  tools/workspace/qhull_internal/patches/vendor.patch
  tools/workspace/qhull_internal/repository.bzl
  tools/workspace/vendor_cxx.bzl
Labels: priority: high, status: single reviewer ok, release notes: none

#20369 add numeric tolerances to test
  solvers/test/diagonally_dominant_dual_cone_matrix_test.cc
  solvers/test/scaled_diagonally_dominant_dual_cone_matrix_test.cc
Labels: priority: high, status: squashing now, status: single reviewer ok, release notes: none

#20326 [doc] Add release notes v1.22.0
  doc/_pages/from_binary.md
  doc/_pages/release_playbook.md
  doc/_release-notes/template.txt
  doc/_release-notes/v1.22.0.md
Labels: status: do not merge, status: single reviewer ok, release notes: none

#20038 Implement AffineBall subclass of ConvexSet
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/affine_ball.cc
  geometry/optimization/affine_ball.h
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/test/affine_ball_test.cc
Labels: release notes: feature

#20365 [common] Add WarnDeprecated sugar for console deprecation logs
  bindings/pydrake/common/deprecation.py
  common/BUILD.bazel
  common/drake_deprecated.cc
  common/drake_deprecated.h
  common/test/drake_deprecated_test.cc
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render_vtk/internal_render_engine_vtk.cc
  multibody/tree/unit_inertia.cc
  systems/framework/leaf_system.cc
  systems/framework/system.cc
Labels: priority: low, release notes: none

#20212 Bug fix in actuation inputs ordering
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/actuated_models_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/joint_actuator.cc
  multibody/tree/joint_actuator.h
  multibody/tree/model_instance.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree_topology.h
Labels: release notes: fix

#20278 [geometry] Allow some sub-optimal uses for vtk volume mesh files
  geometry/BUILD.bazel
  geometry/geometry_file_formats_doxygen.h
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/make_mesh_from_vtk.cc
  geometry/proximity/make_mesh_from_vtk.h
  geometry/proximity/test/hydroelastic_internal_test.cc
  geometry/proximity/test/make_mesh_from_vtk_test.cc
  geometry/proximity_engine.cc
  geometry/query_object.h
  geometry/test/extruded_u_volume_mesh.vtk
  geometry/test/proximity_engine_test.cc
Labels: release notes: feature

#20361 Sparse add linear constraint
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/evaluators_test.py
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/iris.cc
  solvers/constraint.cc
  solvers/constraint.h
  solvers/ipopt_solver.cc
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/sdpa_free_format.cc
  solvers/semidefinite_relaxation.cc
  solvers/sparse_and_dense_matrix.cc
  solvers/sparse_and_dense_matrix.h
  solvers/test/constraint_test.cc
  solvers/test/mathematical_program_test.cc
  solvers/test/sparse_and_dense_matrix_test.cc
Labels: status: squashing now, release notes: feature

#20382 [pydrake] Remove misleadingly long spellings in BUILD files
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/multibody/BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#20387 [workspace] Bump VGT to support hidden visibility
  tools/workspace/voxelized_geometry_tools/package.BUILD.bazel
  tools/workspace/voxelized_geometry_tools/patches/vendor.patch
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#20381 [parsing] Support drake:joint involving links in nested models
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: release notes: fix

#20390 [workspace] Disable kcov on CRU and VGT tests
  tools/workspace/common_robotics_utilities/package.BUILD.bazel
  tools/workspace/voxelized_geometry_tools/package.BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#20274 ContactResults report deformable contact results
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/discrete_contact_data.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/compliant_contact_manager_tester.h
  multibody/plant/test/deformable_contact_results_test.cc
  multibody/plant/test/deformable_driver_contact_test.cc
  multibody/plant/test/deformable_integration_test.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
Labels: release notes: none

#20389 [math] Clang-format the non-test files
  math/autodiff.h
  math/autodiff_gradient.h
  math/bspline_basis.cc
  math/bspline_basis.h
  math/continuous_lyapunov_equation.cc
  math/discrete_lyapunov_equation.cc
  math/eigen_sparse_triplet.h
  math/fast_pose_composition_functions.cc
  math/fast_pose_composition_functions_avx2_fma.cc
  math/fast_pose_composition_functions_avx2_fma.h
  math/gradient.h
  math/gradient_util.h
  math/gray_code.h
  math/jacobian.h
  math/matrix_util.h
  math/quadratic_form.cc
  math/quadratic_form.h
  math/quaternion.h
  math/rigid_transform.cc
  math/rigid_transform.h
  math/roll_pitch_yaw.cc
  math/roll_pitch_yaw.h
  math/rotation_conversion_gradient.h
  math/rotation_matrix.cc
  math/rotation_matrix.h
  math/wrap_to.h
Labels: priority: low, status: single reviewer ok, release notes: none

#20396 [lint] Identify mismatched clang-format-{on,off} comments
  common/symbolic/expression/test/substitution_test.cc
  geometry/optimization/test/affine_subspace_test.cc
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/optimization/test/intersection_test.cc
  solvers/test/complementary_problem_test.cc
  solvers/test/mathematical_program_test.cc
  systems/controllers/test/linear_quadratic_regulator_test.cc
  tools/lint/drakelint.py
Labels: priority: low, release notes: fix

#20379 Update dd and sdd dual cone constraints to use sparse matrices
  solvers/mathematical_program.cc
  solvers/test/diagonally_dominant_dual_cone_matrix_test.cc
Labels: status: squashing now, release notes: none

#20386 [multibody] Allow zero-dof trees in the multibody forest
  multibody/plant/discrete_update_manager.cc
  multibody/plant/sap_driver.cc
  multibody/plant/test/sap_driver_ball_constraints_test.cc
  multibody/plant/test/sap_driver_distance_constraints_test.cc
  multibody/plant/test/sap_driver_weld_constraints_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_topology.h
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: priority: medium, release notes: none

#20391 [yaml] Retain default values when parsing a variant
  bindings/pydrake/common/test/yaml_typed_test.py
  bindings/pydrake/common/yaml.py
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_read_archive.h
Labels: priority: medium, release notes: fix

#20392 [math] Clang-format the tests
  math/BUILD.bazel
  math/test/autodiff_test.cc
  math/test/barycentric_test.cc
  math/test/compute_numerical_gradient_test.cc
  math/test/continuous_algebraic_riccati_equation_test.cc
  math/test/convert_time_derivative_test.cc
  math/test/differentiable_norm_test.cc
  math/test/fast_pose_composition_functions_test.cc
  math/test/gradient_util_test.cc
  math/test/gray_code_test.cc
  math/test/jacobian_test.cc
  math/test/linear_solve_test.cc
  math/test/normalize_vector_test.cc
  math/test/quadratic_form_test.cc
  math/test/quaternion_test.cc
  math/test/rigid_transform_test.cc
  math/test/roll_pitch_yaw_test.cc
  math/test/rotation_conversion_test.cc
  math/test/rotation_matrix_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#20117 [pydrake] Add conversion to/from SymPy
  bindings/pydrake/symbolic/BUILD.bazel
  bindings/pydrake/symbolic/_symbolic_extra.py
  bindings/pydrake/symbolic/_symbolic_sympy.py
  bindings/pydrake/symbolic/test/sympy_test.py
  tools/workspace/default.bzl
  tools/workspace/mpmath_py_internal/BUILD.bazel
  tools/workspace/mpmath_py_internal/package.BUILD.bazel
  tools/workspace/mpmath_py_internal/repository.bzl
  tools/workspace/sympy_py_internal/BUILD.bazel
  tools/workspace/sympy_py_internal/package.BUILD.bazel
  tools/workspace/sympy_py_internal/repository.bzl
Labels: priority: backlog, release notes: feature

#20313 Consolidate code that verifies whether a vector is a reasonable unit vector.
  math/BUILD.bazel
  math/rotation_matrix.cc
  math/rotation_matrix.h
  math/test/rotation_matrix_test.cc
  math/test/unit_vector_test.cc
  math/unit_vector.cc
  math/unit_vector.h
  multibody/tree/BUILD.bazel
  multibody/tree/spatial_inertia.cc
  multibody/tree/test/spatial_inertia_test.cc
  multibody/tree/test/unit_inertia_test.cc
  multibody/tree/unit_inertia.cc
Labels: priority: medium, release notes: none

#16727 [parsing] Add support for using merge-includes with custom parsed models
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_mujoco_parser.h
  multibody/parsing/detail_parsing_workspace.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/sdf_parser_test/interface_api_test/arm.xml
  multibody/parsing/test/sdf_parser_test/interface_api_test/arm_merge_include.sdf
  multibody/parsing/test/sdf_parser_test/interface_api_test/arm_with_gripper_merge_include.sdf
  multibody/parsing/test/sdf_parser_test/interface_api_test/top_merge_include.sdf
  multibody/parsing/test/sdf_parser_test/interface_api_test/top_merge_include_in_nested_model.sdf
  multibody/parsing/test/sdf_parser_test/interface_api_test/top_merge_include_world.sdf
Labels: status: squashing now, release notes: feature

#20400 [py autodiff,math,symbolic] Hotfix wheel build for subdirs
  tools/wheel/image/setup.py
Labels: priority: high, status: single reviewer ok, release notes: none

#20375 Add ClarabelSolver.
  solvers/BUILD.bazel
  solvers/clarabel_solver.cc
  solvers/clarabel_solver.h
  solvers/clarabel_solver_common.cc
  solvers/mathematical_program_doxygen.h
  solvers/no_clarabel.cc
  solvers/test/clarabel_solver_test.cc
  solvers/test/optimization_examples.cc
Labels: release notes: feature

#20407 CompositeTrajectory binding isa PiecewiseTrajectory
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#20403 [py tools] Vastly improve stubgen wrapper
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/_all_everything.py
  bindings/pydrake/all.py
  bindings/pydrake/stubgen.bzl
  bindings/pydrake/stubgen.py
  bindings/pydrake/test/all_install_test.py
  doc/pydrake/build.py
  tools/workspace/mypy_internal/patches/no_retry.patch
  tools/workspace/mypy_internal/repository.bzl
Labels: priority: high, release notes: fix

#20409 [py tools] Update test for new stubgen wrapper
  tools/wheel/test/tests/pyi-install-test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#20418 Disable memcheck for parallelism tests
  tools/workspace/common_robotics_utilities/package.BUILD.bazel
Labels: release notes: none

#20416 minor: fix a few typos in DrakeGym docs
  bindings/pydrake/gym/README.md
  bindings/pydrake/gym/test/drake_gym_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#20420 Updated inertias for the iiwa 7
  manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
  manipulation/models/iiwa_description/BUILD.bazel
  manipulation/models/iiwa_description/README.md
  manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf
  manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf
  manipulation/models/iiwa_description/test/iiwa_variants_parsing_test.cc
Labels: release notes: fix

#20406 Fix divide by norm bug in RotationMatrix::NormalizeOrThrow().
  math/rotation_matrix.cc
  math/test/rotation_matrix_test.cc
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#20414 Fix mujoco parser joint kinematics.
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: priority: high, release notes: fix, release notes: feature

#20398 Add tighten and relax PSD constraint via DD, SDD, and their duals
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/diagonally_dominant_dual_cone_matrix_test.cc
  solvers/test/mathematical_program_test.cc
  solvers/test/scaled_diagonally_dominant_dual_cone_matrix_test.cc
  solvers/test/scaled_diagonally_dominant_matrix_test.cc
Labels: status: squashing now, release notes: feature

#20426 Clarify MultibodyPlant::CalcGeneralizedForces()
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree.h
Labels: status: single reviewer ok, release notes: none

#20423 Move internal static RotationMatrix::NormalizeOrThrow() to unit_vector.
  math/BUILD.bazel
  math/rotation_matrix.cc
  math/rotation_matrix.h
  math/test/rotation_matrix_test.cc
  math/unit_vector.cc
  math/unit_vector.h
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: none

#20385 Use environment maps in RenderEngineVtk
  BUILD.bazel
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/geometry/test/render_test.py
  geometry/BUILD.bazel
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/render_engine_vtk_params.h
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  geometry/render_vtk/test/render_engine_vtk_params_test.cc
  geometry/test/env_256_six_color_room.hdr
  geometry/test/env_256_six_color_room.png
  tools/workspace/vtk_internal/patches/io_image_formats.patch
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: medium, release notes: feature

#20422 [examples/gym] Shorten running time of play_cart_pole_test
  bindings/pydrake/examples/gym/play_cart_pole.py
Labels: priority: high, release notes: none

#20428 [multibody] Make coordinate numbering for Weld mobilizers consistent with others
  multibody/tree/multibody_tree_topology.h
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: priority: medium, release notes: none

#20411 Add log(det(X)) >= lower to MathematicalProgram.
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/exponential_cone_program_examples.cc
  solvers/test/exponential_cone_program_examples.h
  solvers/test/mathematical_program_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/scs_solver_test.cc
Labels: release notes: feature

#20427 [multibody] Eliminate mention of flexible body support from MultibodyTree
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/multibody_doxygen.h
  multibody/plant/sap_driver.cc
  multibody/tree/body.h
  multibody/tree/body_node.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree_topology.h
  multibody/tree/rigid_body.h
  multibody/tree/test/body_node_test.cc
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: priority: medium, release notes: removal of deprecated

#20431 [py visualization] Follow code layout conventions
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/visualization_py.cc
  bindings/pydrake/visualization/visualization_py.h
  bindings/pydrake/visualization/visualization_py_sliders.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#20435 [multibody] Disambiguate use of "velocity_start" in MultibodyTree
  multibody/plant/deformable_driver.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/sap_driver.cc
  multibody/plant/tamsi_driver.cc
  multibody/plant/test/compliant_contact_manager_tester.h
  multibody/plant/test/sap_driver_joint_limits_test.cc
  multibody/plant/test/sap_driver_test.cc
  multibody/tree/body.h
  multibody/tree/body_node.h
  multibody/tree/joint.h
  multibody/tree/mobilizer_impl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree_topology.h
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#20410 Upgrade to bazel 6.4.0
  .bazeliskrc
  doc/_pages/from_source.md
  setup/ubuntu/source_distribution/install_bazel.sh
  tools/workspace/drake_visualizer/image/provision.sh
Labels: status: single reviewer ok, release notes: feature

#20432 [py doc] Set a policy that modules must always be factored
  bindings/pydrake/pydrake_doxygen.h
Labels: priority: low, release notes: none

#20434 Increase timeout for internal_render_engine_vtk_test
  geometry/render_vtk/BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#20442 Upgrade meshcat to latest commit
  geometry/meshcat.html
  tools/workspace/meshcat/repository.bzl
Labels: release notes: fix

#20452 [tools] Remove --edit-include feature for vendoring
  tools/workspace/conex_internal/vendor.bzl
  tools/workspace/vendor_cxx.bzl
  tools/workspace/vendor_cxx.py
  tools/workspace/vendor_cxx_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#20445 [vtk] Dispatch vtkPNGReader errors correctly
  tools/workspace/vtk_internal/patches/io_image_png_messages.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: priority: low, release notes: fix

#20453 [workspace] Clean up NLopt vendoring patches
  tools/workspace/nlopt_internal/package.BUILD.bazel
  tools/workspace/nlopt_internal/patches/stogo.patch
  tools/workspace/nlopt_internal/patches/vendor.patch
  tools/workspace/nlopt_internal/patches/vendoring.patch
  tools/workspace/nlopt_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#20448 [sensors] Add internal helpers in anticipation of ImageIo support
  systems/sensors/BUILD.bazel
  systems/sensors/image_io.h
  systems/sensors/image_io_internal.cc
  systems/sensors/image_io_internal.h
  systems/sensors/test/image_io_internal_test.cc
  systems/sensors/test/tiff_32f_test.tif
  systems/sensors/test/vtk_diagnostic_event_observer_test.cc
  systems/sensors/vtk_diagnostic_event_observer.cc
  systems/sensors/vtk_diagnostic_event_observer.h
Labels: priority: medium, release notes: none
