Repository RobotLocomotion/drake, pull requests merged in 2023-07, with the labels that each got.

#19710 [primitives] Opt-in to clang-format-lint
  systems/primitives/BUILD.bazel
  systems/primitives/test/affine_system_test.cc
  systems/primitives/test/barycentric_system_test.cc
  systems/primitives/test/constant_value_source_test.cc
  systems/primitives/test/constant_vector_source_test.cc
  systems/primitives/test/discrete_derivative_test.cc
  systems/primitives/test/discrete_time_delay_test.cc
  systems/primitives/test/first_order_low_pass_filter_test.cc
  systems/primitives/test/integrator_test.cc
  systems/primitives/test/linear_system_test.cc
  systems/primitives/test/linear_transform_density_test.cc
  systems/primitives/test/pass_through_test.cc
  systems/primitives/test/random_source_test.cc
  systems/primitives/test/saturation_test.cc
  systems/primitives/test/shared_pointer_system_test.cc
  systems/primitives/test/sine_test.cc
  systems/primitives/test/symbolic_vector_system_test.cc
  systems/primitives/test/trajectory_affine_system_test.cc
  systems/primitives/test/trajectory_linear_affine_test.h
  systems/primitives/test/trajectory_linear_system_test.cc
  systems/primitives/test/trajectory_source_test.cc
  systems/primitives/test/vector_log_sink_test.cc
  systems/primitives/test/wrap_to_system_test.cc
  systems/primitives/test/zero_order_hold_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#19714 Remove deprecated code 2023-07
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  bindings/pydrake/planning/planning_py_collision_checker.cc
  bindings/pydrake/planning/test/collision_checker_test.py
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/_model_visualizer.py
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/test/model_visualizer_test.py
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/factory.cc
  geometry/render_gl/factory.h
  geometry/render_gl/no_factory.cc
  geometry/render_gl/render_engine_gl_params.h
  geometry/render_gl/test/deprecation_test.cc
  manipulation/util/make_arm_controller_model.cc
  multibody/parsing/scoped_names.cc
  multibody/parsing/scoped_names.h
  planning/collision_checker.h
  planning/test/collision_checker_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#19677 [py visualization] Meldis supports inertia visualization
  bindings/pydrake/geometry/geometry_py_visualizers.cc
  bindings/pydrake/geometry/test/visualizers_test.py
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: priority: medium, release notes: feature

#19433 Update gallery.md
  doc/_pages/gallery.md
Labels: status: squashing now, status: single reviewer ok, release notes: none

#19665 [solvers] Support upper bound in MinimumValueConstraint.
  multibody/inverse_kinematics/minimum_distance_constraint.h
  solvers/minimum_value_constraint.cc
  solvers/minimum_value_constraint.h
  solvers/test/minimum_value_constraint_test.cc
Labels: release notes: newly deprecated, release notes: feature

#19719 GraphOfConvexSets returns kInfeasibleConstraints when no path exists.
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: fix

#19718 [InverseKinematics] Add upper bound on the minimum distance.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  multibody/inverse_kinematics/minimum_distance_constraint.cc
  multibody/inverse_kinematics/minimum_distance_constraint.h
  multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
  solvers/minimum_value_constraint.cc
  solvers/minimum_value_constraint.h
Labels: release notes: feature

#19721 Add link from solvers doxygen to build info for priopriety solvers.
  solvers/mathematical_program_doxygen.h
Labels: status: single reviewer ok, release notes: none

#19713 GurobiSolver acquires a local license at most once per process
  solvers/BUILD.bazel
  solvers/gurobi_solver.cc
  solvers/gurobi_solver.h
  solvers/test/gurobi_solver_license_retention_test.py
  solvers/test/gurobi_solver_license_retention_test_helper.cc
Labels: release notes: feature

#19635 Meshcat can handle Mesh(foo.gltf)
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/render/test/meshes/cube.gltf
  geometry/test/meshcat_manual_test.cc
  geometry/test/meshcat_test.cc
  tools/workspace/meshcat/repository.bzl
Labels: priority: high, release notes: feature

#19656 Add tolerance to check zero off-diagonal elements of a rotational inertia. Return identity matrix if all principal moments of inertia are equal.
  multibody/tree/rotational_inertia.cc
  multibody/tree/test/rotational_inertia_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#19632 Implements MakeSemidefiniteRelaxation
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py.cc
  bindings/pydrake/solvers/solvers_py.h
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/solvers_py_semidefinite_relaxation.cc
  bindings/pydrake/solvers/test/semidefinite_relaxation_test.py
  geometry/optimization/spectrahedron.cc
  solvers/BUILD.bazel
  solvers/semidefinite_relaxation.cc
  solvers/semidefinite_relaxation.h
  solvers/test/semidefinite_relaxation_test.cc
Labels: release notes: feature

#19671 Hyperellipsoid::MinimumUniformScalingToTouch handles the empty case.
  geometry/optimization/BUILD.bazel
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/test/hyperellipsoid_test.cc
Labels: release notes: fix

#19716 Implement IsEmpty for ConvexSet and derived classes
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/minkowski_sum.h
  geometry/optimization/point.cc
  geometry/optimization/point.h
  geometry/optimization/test/cartesian_product_test.cc
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/optimization/test/hyperellipsoid_test.cc
  geometry/optimization/test/intersection_test.cc
  geometry/optimization/test/minkowski_sum_test.cc
  geometry/optimization/test/point_test.cc
  geometry/optimization/test/spectrahedron_test.cc
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: release notes: feature

#19730 [yaml] Improve error message for parsing a non-Mapping root node
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_read_archive.cc
  common/yaml/yaml_read_archive.h
Labels: priority: low, release notes: fix

#19720 Optional default options for GraphOfConvexSets.
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
  planning/trajectory_optimization/BUILD.bazel
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  solvers/choose_best_solver.cc
Labels: release notes: feature

#19724 [multibody] Reject duplicated frame names
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/model_instance_test.cc
  multibody/tree/test/multibody_tree_test.cc
Labels: priority: medium, release notes: breaking change, release notes: fix

#19535 Add Minimum Degree ordering
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/minimum_degree_ordering.cc
  multibody/contact_solvers/minimum_degree_ordering.h
  multibody/contact_solvers/test/minimum_degree_ordering_test.cc
Labels: release notes: none

#19684 Allowing RenderEngineGltfClient to accept gltf
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_merge_gltf.cc
  geometry/render_gltf_client/internal_merge_gltf.h
  geometry/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render_gltf_client/internal_render_engine_gltf_client.h
  geometry/render_gltf_client/test/internal_merge_gltf_test.cc
  geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc
  geometry/render_gltf_client/test/tri.obj
  geometry/render_gltf_client/test/tri_tree.gltf
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
Labels: release notes: fix

#19705 MosekSolver supports QuadraticConstraint
  solvers/BUILD.bazel
  solvers/mathematical_program.h
  solvers/mosek_solver.cc
  solvers/mosek_solver_common.cc
  solvers/mosek_solver_internal.cc
  solvers/mosek_solver_internal.h
  solvers/test/mosek_solver_internal_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/quadratic_constrained_program_examples.cc
  solvers/test/quadratic_constrained_program_examples.h
Labels: release notes: feature

#19658 Add ConstructPlaneSearchProgram to CspaceFreeBox.
  geometry/optimization/BUILD.bazel
  geometry/optimization/cspace_free_box.cc
  geometry/optimization/cspace_free_box.h
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/cspace_free_polytope.h
  geometry/optimization/cspace_free_polytope_base.cc
  geometry/optimization/cspace_free_polytope_base.h
  geometry/optimization/cspace_free_structs.h
  geometry/optimization/test/c_iris_test_utilities.cc
  geometry/optimization/test/c_iris_test_utilities.h
  geometry/optimization/test/cspace_free_box_test.cc
  geometry/optimization/test/cspace_free_box_with_mosek_test.cc
  geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc
Labels: release notes: none

#19733 Adds HPolyhedron::Scale()
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/test/hpolyhedron_test.cc
Labels: release notes: feature

#19728 Fix IrisInConfigurationSpace hit and run.
  geometry/optimization/iris.cc
  geometry/optimization/test/iris_in_configuration_space_test.cc
Labels: priority: high, release notes: fix

#19707 Update coefficients in AffineSystem
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/affine_system.cc
  systems/primitives/affine_system.h
  systems/primitives/test/affine_system_test.cc
Labels: release notes: feature

#19744 [tools] Fix a typo in googlebench command line
  tools/performance/defs.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#19750 Fix outdated doxygen comments and some typos
  geometry/render_gl/internal_opengl_includes.h
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/internal_vtk_util.h
  tools/skylark/drake_cc.bzl
  visualization/visualization_config.h
Labels: status: single reviewer ok, release notes: none

#19745 [systems] Enable clang-format lint for benchmarking
  systems/benchmarking/BUILD.bazel
  systems/benchmarking/framework_benchmarks.cc
  systems/benchmarking/multilayer_perceptron_benchmark.cc
  tools/performance/defs.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#19726 Notation clean-up (replace frame P with frame A). Isolate calculation of canonical principal directions.
  multibody/tree/rotational_inertia.cc
  multibody/tree/rotational_inertia.h
Labels: priority: medium, status: squashing now, release notes: none

#19697 [wrap_function] Allow for empty std::function objects
  bindings/pydrake/common/test/wrap_pybind_test.py
  bindings/pydrake/common/test/wrap_test_util_py.cc
  bindings/pydrake/common/wrap_function.h
Labels: release notes: fix

#19751 Follow-up fix for IrisInConfigurationSpace mac test
  geometry/optimization/test/iris_in_configuration_space_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#19741 Add BlockSparseCholeskySolver
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/block_sparse_cholesky_solver.cc
  multibody/contact_solvers/block_sparse_cholesky_solver.h
  multibody/contact_solvers/test/block_sparse_cholesky_solver_test.cc
Labels: priority: high, release notes: none

#19743 [visualization] Enable inertia visualization by default
  bindings/pydrake/visualization/test/meldis_test.py
  visualization/inertia_visualizer.h
  visualization/test/inertia_visualizer_test.cc
  visualization/test/visualization_config_functions_test.cc
  visualization/visualization_config.h
Labels: release notes: feature

#19736 CollisionChecker validates distance/interpolation funcs with default config
  planning/collision_checker.cc
  planning/collision_checker.h
  planning/collision_checker_params.h
  planning/test/collision_checker_test.cc
Labels: release notes: fix

#19753 [bindings] Fix bugs for sorted_pair_pybind; add test
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/sorted_pair_pybind.h
  bindings/pydrake/common/test/sorted_pair_pybind_test.cc
Labels: release notes: fix

#19739 [render] Handle geometry::Mesh("foo.gltf", 1) throughout Drake
  .gitattributes
  bindings/pydrake/geometry/geometry_py_common.cc
  bindings/pydrake/geometry/test/common_test.py
  examples/scene_graph/BUILD.bazel
  examples/scene_graph/solar_system.cc
  examples/scene_graph/sun.gltf
  examples/scene_graph/sun.sdf
  geometry/drake_visualizer.h
  geometry/meshcat.cc
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/test_utilities.cc
  geometry/optimization/test_utilities.h
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/test/hydroelastic_internal_test.cc
  geometry/proximity_engine.cc
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/test/proximity_engine_test.cc
  geometry/test/shape_specification_test.cc
  multibody/tree/geometry_spatial_inertia.cc
Labels: priority: high, release notes: feature

#19737 Add more SpatialInertia::ObjectWithMass() functions
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/articulated_body_algorithm_test.cc
  multibody/tree/test/spatial_inertia_test.cc
  multibody/tree/unit_inertia.h
Labels: priority: medium, release notes: feature

#19754 Implement SuperNodalSolver with BlockSparseCholeskySolver
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/block_sparse_matrix.h
  multibody/contact_solvers/block_sparse_supernodal_solver.cc
  multibody/contact_solvers/block_sparse_supernodal_solver.h
  multibody/contact_solvers/conex_supernodal_solver.cc
  multibody/contact_solvers/conex_supernodal_solver.h
  multibody/contact_solvers/supernodal_solver.cc
  multibody/contact_solvers/supernodal_solver.h
  multibody/contact_solvers/test/block_sparse_matrix_test.cc
  multibody/contact_solvers/test/supernodal_solver_test.cc
Labels: priority: high, release notes: none

#19757 SAP uses BlockSparseSuperNodalSolver
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/sap_solver.h
  multibody/contact_solvers/sap/test/sap_solver_test.cc
Labels: release notes: feature

#19767 Remove outdated TODO from MeshcatVisualizer
  geometry/meshcat_visualizer.h
Labels: status: single reviewer ok, release notes: none

#19772 Fixup for #19765. Remove problematic doxygen ref.
  systems/controllers/finite_horizon_linear_quadratic_regulator.h
Labels: status: single reviewer ok, release notes: none

#19769 Use temporary DiagnosticPolicy object
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
Labels: release notes: none

#19748 [doc] Add release notes v1.19.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.19.0.md
  tools/release_engineering/relnotes.py
Labels: status: squashing now, status: single reviewer ok, release notes: none

#19773 Upgrade Externals July 2023
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/googlebenchmark/repository.bzl
  tools/workspace/libcmaes/repository.bzl
  tools/workspace/msgpack_internal/repository.bzl
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/petsc/repository.bzl
  tools/workspace/qdldl_internal/repository.bzl
  tools/workspace/rules_python/repository.bzl
  tools/workspace/suitesparse_internal/repository.bzl
  tools/workspace/tinyobjloader/repository.bzl
  tools/workspace/typing_extensions_internal/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#19761 Move code from unit_inertia.h to unit_inertia.cc. TODO() for later possible breaking change.
  multibody/tree/unit_inertia.cc
  multibody/tree/unit_inertia.h
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: none

#19776 [workspace] Upgrade gz_math_internal to latest release gz-math7_7.2.0
  tools/workspace/gz_math_internal/package.BUILD.bazel
  tools/workspace/gz_math_internal/repository.bzl
Labels: status: squashing now, release notes: fix

#19778 [workspace] Upgrade abseil_cpp_internal to latest commit
  tools/workspace/abseil_cpp_internal/patches/hidden_visibility.patch
  tools/workspace/abseil_cpp_internal/repository.bzl
Labels: status: squashing now, release notes: fix

#19784 [install] Upgrade rules_python to latest release to match workspace
  tools/install/bazel/test/drake_bazel_installed_test.py
Labels: status: single reviewer ok, release notes: none

#19788 [workspace] Remove spurious lcm-gen dependency
  tools/workspace/lcm/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: fix

#19785 Add GraphOfConvexSets::SolveConvexRestriction()
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: feature

#19790 Adds MathematicalProgramResult::SetSolution()
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program_result.cc
  solvers/mathematical_program_result.h
  solvers/test/mathematical_program_result_test.cc
Labels: release notes: feature

#19794 Fix GraphOfConvexSets test tolerances
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: single reviewer ok, release notes: none

#19775 [workspace] Upgrade nanoflann_internal to latest release v1.5.0
  perception/point_cloud.cc
  tools/workspace/nanoflann_internal/repository.bzl
Labels: release notes: fix

#19796 [workspace] Patch googlebenchmark to avoid shadow warnings
  geometry/benchmarking/render_benchmark.cc
  multibody/benchmarking/acrobot.cc
  multibody/benchmarking/cassie.cc
  multibody/benchmarking/position_constraint.cc
  systems/benchmarking/framework_benchmarks.cc
  systems/benchmarking/multilayer_perceptron_benchmark.cc
  tools/workspace/googlebenchmark/patches/remove_overloaded_fixture_set_up.patch
  tools/workspace/googlebenchmark/repository.bzl
Labels: priority: medium, release notes: fix

#19799 [render_vtk] Hide VTK derived class symbols
  geometry/render_vtk/internal_render_engine_vtk.h
Labels: status: single reviewer ok, release notes: none

#19780 [parsing] Parse custom ball constraint elements.
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/plant/constraint_specs.h
  multibody/plant/multibody_plant.h
  multibody/plant/test/sap_driver_ball_constraints_test.cc
  multibody/plant/test/sap_driver_distance_constraints_test.cc
Labels: release notes: feature

#19789 [pybind] Add python binding for soft min/max.
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_test.py
Labels: status: single reviewer ok, release notes: feature

#19756 Deprecate SeparatingPlaneOrder.
  geometry/optimization/BUILD.bazel
  geometry/optimization/c_iris_separating_plane.cc
  geometry/optimization/c_iris_separating_plane.h
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/cspace_free_polytope.h
  geometry/optimization/cspace_free_polytope_base.cc
  geometry/optimization/cspace_free_polytope_base.h
  geometry/optimization/cspace_separating_plane.cc
  geometry/optimization/cspace_separating_plane.h
  geometry/optimization/test/cspace_separating_plane_test.cc
Labels: release notes: breaking change

#19798 Upgrade Mosek patch from 10.0.18 to 10.0.46
  tools/workspace/mosek/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#19795 Handle bounding box constraints in MakeSemidefiniteRelaxation
  solvers/semidefinite_relaxation.cc
  solvers/semidefinite_relaxation.h
  solvers/test/semidefinite_relaxation_test.cc
Labels: release notes: fix

#19762 Compute MD ordering with priority nodes
  multibody/contact_solvers/minimum_degree_ordering.cc
  multibody/contact_solvers/minimum_degree_ordering.h
  multibody/contact_solvers/test/minimum_degree_ordering_test.cc
Labels: release notes: none

#19801 Adjust test tolerance for GraphOfConvexSetsTest
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: fix

#19791 [pybind] split solvers_py_mathematicalprogram.
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py.cc
  bindings/pydrake/solvers/solvers_py.h
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/evaluators_test.py
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: release notes: none

#19797 fix names shown off-by-one in RationalForwardKinematics var names
  multibody/rational/rational_forward_kinematics.cc
Labels: release notes: fix

#19764 Compute in-group Minimum Degree ordering
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/minimum_degree_ordering.cc
  multibody/contact_solvers/minimum_degree_ordering.h
  multibody/contact_solvers/test/minimum_degree_ordering_test.cc
Labels: release notes: none

#19808 Fix MosekSolver doxygen
  solvers/mosek_solver.h
Labels: status: single reviewer ok, release notes: none

#19729 Bump CRU and VGT with new DegreeOfParallelism API
  perception/point_cloud.cc
  planning/collision_checker.cc
  planning/collision_checker.h
  tools/workspace/common_robotics_utilities/BUILD.bazel
  tools/workspace/common_robotics_utilities/package.BUILD.bazel
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/voxelized_geometry_tools/BUILD.bazel
  tools/workspace/voxelized_geometry_tools/package.BUILD.bazel
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: status: squashing now, release notes: fix

#19812 [tutorials] Highlight inertia visualization in multibody tutorial
  tutorials/authoring_multibody_simulation.ipynb
Labels: priority: medium, release notes: none

#19814 Add MathematicalProgramResult::get_decision_variable_index()
  solvers/mathematical_program_result.h
  solvers/test/mathematical_program_result_test.cc
Labels: priority: high, release notes: feature

#19792 Adds GraphOfConvexSets::GetSolutionPath() and supporting introspection methods.
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
Labels: release notes: feature

#19804 Implement MaybeGetFeasiblePoint for ConvexSet
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/cartesian_product.cc
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/test/cartesian_product_test.cc
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/optimization/test/hyperellipsoid_test.cc
  geometry/optimization/test/intersection_test.cc
  geometry/optimization/test/minkowski_sum_test.cc
  geometry/optimization/test/point_test.cc
  geometry/optimization/test/spectrahedron_test.cc
  geometry/optimization/test/vpolytope_test.cc
Labels: release notes: feature

#19817 [workspace] Upgrade meshcat to latest commit
  tools/workspace/meshcat/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#19821 Fix UB in GraphOfConvexSets::GetSolutionPath error handling
  geometry/optimization/graph_of_convex_sets.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#19815 [geometry] Demote warning message for too many materials
  geometry/render/render_mesh.cc
  geometry/render/test/render_mesh_test.cc
Labels: priority: medium, release notes: fix

#19813 [geometry] Fix MeshcatVisualizer initialization of alpha slider
  geometry/meshcat_visualizer.cc
  geometry/meshcat_visualizer.h
  geometry/test/meshcat_visualizer_test.cc
Labels: priority: medium, release notes: fix

#19818 Adjust value in GraphOfConvexSets::GetGraphvizString test
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: none

#19816 Use GraphOfConvexSets::SolveConvexRestriction in rounding.
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
  solvers/cost.h
Labels: release notes: feature

#19746 [framework] Improve DiagramBuilder::Build performance
  systems/framework/diagram.cc
  systems/framework/diagram.h
Labels: priority: low, release notes: fix

#19825 Removes VertexId and EdgeId overloads from GraphOfConvexSets API
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
Labels: release notes: breaking change

#19771 Adds a benchmark for IrisInConfigurationSpace
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/models/bin2.sdf
  examples/manipulation_station/models/shelves.sdf
  examples/manipulation_station/models/table_wide.sdf
  geometry/benchmarking/BUILD.bazel
  geometry/benchmarking/README.md
  geometry/benchmarking/iris_in_configuration_space_benchmarks.cc
  tools/workspace/drake_models/repository.bzl
Labels: release notes: feature

#19824 Subclass-Specific Implementations of DoMaybeGetFeasiblePoint
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/minkowski_sum.h
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: component: geometry general, release notes: feature

#19830 Updated inertias for link 2 and link 4 for the kuka iiwa
  manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
  manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf
  manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc
  manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14.xacro
  manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf
  manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf
Labels: release notes: fix

#19836 Don't install drake_models from manipulation_station
  examples/manipulation_station/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#19832 Modernize articulated body algorithm test
  multibody/tree/BUILD.bazel
  multibody/tree/test/articulated_body_algorithm_test.cc
Labels: priority: low, release notes: none

#19834 Adds more meshcat visualizations for IrishInConfigurationSpace tests.
  geometry/optimization/test/iris_in_configuration_space_test.cc
Labels: release notes: none

#19742 CspaceFreeBox find separation certificates for a given box.
  geometry/optimization/BUILD.bazel
  geometry/optimization/cspace_free_box.cc
  geometry/optimization/cspace_free_box.h
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/cspace_free_polytope_base.cc
  geometry/optimization/cspace_free_polytope_base.h
  geometry/optimization/test/c_iris_test_utilities.h
  geometry/optimization/test/cspace_free_box_with_mosek_test.cc
Labels: release notes: none

#19844 Adjust termination conditions for IRIS-NP on focal
  geometry/optimization/test/iris_in_configuration_space_test.cc
Labels: release notes: none

#19845 Fix an asan bug in CspaceFreePolytope.
  geometry/optimization/cspace_free_box.cc
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/cspace_free_polytope_base.cc
  geometry/optimization/cspace_free_polytope_base.h
Labels: priority: high, status: single reviewer ok, release notes: none

#19847 Add optional visualization debugging to IrisInConfigurationSpace
  geometry/optimization/BUILD.bazel
  geometry/optimization/iris.cc
  geometry/optimization/iris.h
  geometry/optimization/test/iris_in_configuration_space_test.cc
Labels: release notes: none

#19849 Clarify the documentation of AddMaximizeLogDeterminantCost.
  solvers/mathematical_program.h
Labels: status: single reviewer ok, release notes: none

#19839 add pybind for MinimumValueConstraint
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/test/evaluators_test.py
Labels: release notes: fix

#19803 Add SpatialInertia::SolidCylinderWithMassAboutEnd()
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/test/joint_limits_test.cc
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
  multibody/tree/test/unit_inertia_test.cc
  multibody/tree/unit_inertia.cc
  multibody/tree/unit_inertia.h
Labels: priority: medium, status: squashing now, release notes: newly deprecated, release notes: feature

#19838 Fix bug in DoAddPointInNonnegativeScalingConstraints for Spectrahedron class
  geometry/optimization/spectrahedron.cc
  geometry/optimization/test/spectrahedron_test.cc
Labels: release notes: fix

#19855 Add python binding for MinimumDistanceConstraint.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
Labels: status: single reviewer ok, release notes: feature

#19862 [workspace] Uniformly use a patches directory
  tools/workspace/drake_visualizer/patches/draw_lcm_mesh.patch
  tools/workspace/drake_visualizer/patches/use_drake_lcmtypes.patch
  tools/workspace/drake_visualizer/patches/warn_gltf.patch
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/ros_xacro_internal/patches/disable-console-print.patch
  tools/workspace/ros_xacro_internal/patches/disable-import-warning.patch
  tools/workspace/ros_xacro_internal/repository.bzl
  tools/workspace/snopt/patches/snopt-openmp.patch
  tools/workspace/snopt/repository.bzl
  tools/workspace/stable_baselines3_internal/patches/no_torch.patch
  tools/workspace/stable_baselines3_internal/repository.bzl
  tools/workspace/tinyobjloader/patches/default_texture_color.patch
  tools/workspace/tinyobjloader/patches/double_precision.patch
  tools/workspace/tinyobjloader/patches/faster_float_parsing.patch
  tools/workspace/tinyobjloader/repository.bzl
  tools/workspace/yaml_cpp_internal/patches/emit-local-tag.patch
  tools/workspace/yaml_cpp_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#19853 Change template type T(doubleNumber) to just doubleNumber in part of code.
  math/quaternion.h
  math/roll_pitch_yaw.cc
  math/rotation_matrix.cc
  math/rotation_matrix.h
  multibody/tree/linear_bushing_roll_pitch_yaw.cc
  multibody/tree/rotational_inertia.h
  multibody/tree/unit_inertia.cc
  multibody/tree/unit_inertia.h
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: none

#19856 Clarify the documentation for AddMaximizeGeometricMeanCost
  solvers/mathematical_program.h
Labels: status: single reviewer ok, release notes: none

#19877 [workspace] Remove vestigial meshcat files from the install
  tools/workspace/meshcat/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: fix

#19857 Implements Hyperellipsoid::MinimumVolumeCircumscribedEllipsoid
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/test/hyperellipsoid_test.cc
Labels: release notes: feature

#19807 BlockSparseCholeskySolver computes Schur complement
  multibody/contact_solvers/block_sparse_cholesky_solver.cc
  multibody/contact_solvers/block_sparse_cholesky_solver.h
  multibody/contact_solvers/test/block_sparse_cholesky_solver_test.cc
Labels: release notes: none

#19869 [py manipulation] Deprecate three vestigial sub-modules
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/kuka_iiwa.py
  bindings/pydrake/manipulation/schunk_wsg.py
  bindings/pydrake/manipulation/test/kuka_iiwa_test.py
  bindings/pydrake/manipulation/test/schunk_wsg_test.py
  bindings/pydrake/manipulation/test/util_test.py
  bindings/pydrake/manipulation/util.py
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#19875 [framework] Fix wrong SystemId on the ports of a cloned system
  systems/framework/system.cc
  systems/framework/system_base.cc
  systems/framework/system_base.h
Labels: priority: medium, status: single reviewer ok, release notes: fix

#19782 [examples] Strandbeest with constraints
  examples/multibody/strandbeest/BUILD.bazel
  examples/multibody/strandbeest/model/LegAssembly.xacro
  examples/multibody/strandbeest/model/LegPair.xacro
  examples/multibody/strandbeest/model/Macros.xacro
  examples/multibody/strandbeest/model/Strandbeest.xacro
  examples/multibody/strandbeest/model/StrandbeestBushings.urdf.xacro
  examples/multibody/strandbeest/model/StrandbeestConstraints.urdf.xacro
  examples/multibody/strandbeest/run_with_motor.cc
Labels: release notes: feature

#19850 Implement AffineSubspace Methods to Check Containment and Equivalence
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/affine_subspace.cc
  geometry/optimization/affine_subspace.h
  geometry/optimization/test/affine_subspace_test.cc
Labels: component: geometry general, release notes: feature

#19872 [workspace] Deprecate the rules_pkg external
  tools/workspace/default.bzl
  tools/workspace/metadata.py
  tools/workspace/rules_pkg/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#19890 [workspace] Deprecate the petsc external
  multibody/fem/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/petsc/package.BUILD.bazel
  tools/workspace/petsc/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#19703 [py common] Add use_native_cpp_logging feature
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/__init__.py
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/text_logging_example.py
  bindings/pydrake/common/test/text_logging_test.py
  bindings/pydrake/common/test/text_logging_test_helpers_py.cc
  bindings/pydrake/common/test/text_logging_threading_direct_to_stderr_test.py
  bindings/pydrake/common/test/text_logging_threading_with_gil_release_test.py
  bindings/pydrake/common/text_logging_pybind.cc
  bindings/pydrake/common/text_logging_pybind.h
  bindings/pydrake/pydrake_doxygen.h
  doc/doxygen_cxx/doxygen.h
Labels: priority: low, release notes: feature

#19848 Added visualization triads in meldis
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: release notes: feature

#19866 Deprecate all optitrack-related code for removal
  systems/sensors/BUILD.bazel
  systems/sensors/optitrack_receiver.h
  systems/sensors/optitrack_sender.h
  tools/install/libdrake/drake-config.cmake.in
  tools/install/libdrake/header_lint.bzl
  tools/install/libdrake/test/header_dependency_test.py
  tools/workspace/default.bzl
  tools/workspace/optitrack_driver/optitrack_client
  tools/workspace/optitrack_driver/repository.bzl
Labels: priority: medium, release notes: newly deprecated

#19693 Add lights to RenderEngineGlParams
  bindings/pydrake/geometry/geometry_py_common.cc
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/geometry/test/common_test.py
  bindings/pydrake/geometry/test/render_test.py
  geometry/render/BUILD.bazel
  geometry/render/light_parameter.cc
  geometry/render/light_parameter.h
  geometry/render/render_engine.h
  geometry/render/test/light_parameter_test.cc
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/internal_shader_program.cc
  geometry/render_gl/internal_shader_program.h
  geometry/render_gl/render_engine_gl_params.h
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/render_gl/test/internal_shader_program_test.cc
  geometry/rgba.cc
  geometry/rgba.h
  geometry/test/rgba_test.cc
Labels: status: squashing now, release notes: feature
