Repository RobotLocomotion/drake, pull requests merged in 2023-09, with the labels that each got.

#20106 [py systems] Improve error message for missing witness functions
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
Labels: priority: low, status: single reviewer ok, release notes: fix

#20119 [py symbolic] Bind Formula(bool) constructor
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
Labels: priority: low, status: single reviewer ok, release notes: fix

#20116 [lcm] Eschew LCM C++ API (use C instead)
  lcm/drake_lcm.cc
Labels: release notes: none

#20121 [doc] More clearly explain our version support timelines
  doc/_pages/installation.md
  doc/_pages/stable.md
Labels: priority: low, release notes: none

#20115 [lcm] Deprecate direct access to the native LCM library
  lcm/drake_lcm.cc
  lcm/drake_lcm.h
  lcm/test/drake_lcm_test.cc
  lcm/test/drake_lcm_thread_test.cc
Labels: priority: low, release notes: newly deprecated

#20083 [doc] Improve code block formatting in API docs
  doc/_pages/documentation_instructions.md
  doc/doxygen_cxx/Doxyfile_CXX.in
  doc/doxygen_cxx/build.py
  geometry/scene_graph.h
  tools/workspace/pybind11/mkdoc_comment.py
  tools/workspace/pybind11/test/mkdoc_comment_test.py
Labels: priority: low, release notes: none

#20104 [math] Rewrite the DARE solver to use a faster algorithm
  math/BUILD.bazel
  math/discrete_algebraic_riccati_equation.cc
  math/discrete_algebraic_riccati_equation.h
  math/test/discrete_algebraic_riccati_equation_test.cc
  systems/primitives/linear_system_internal.cc
Labels: status: squashing now, release notes: fix

#20086 DeformableDriver uses the new FemSolver
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
  multibody/fem/fem_solver.cc
  multibody/fem/fem_solver.h
  multibody/fem/test/fem_solver_test.cc
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/test/deformable_driver_contact_test.cc
Labels: release notes: none

#20085 Remove deprecated code 2023-09
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/systems/test/primitives_test.py
  bindings/pydrake/visualization/visualization_py_config.cc
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/cspace_free_polytope.h
  planning/trajectory_optimization/multiple_shooting.h
  planning/trajectory_optimization/test/multiple_shooting_test.cc
  solvers/solution_result.h
  solvers/test/mathematical_program_result_test.cc
  systems/lcm/BUILD.bazel
  systems/lcm/serializer.h
  systems/lcm/test/serializer_deprecated_test.cc
  visualization/test/visualization_config_functions_test.cc
  visualization/visualization_config_functions.cc
  visualization/visualization_config_functions.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#20137 [lcm] Hotfix for "Eschew LCM C++ API"
  lcm/drake_lcm.cc
  lcm/test/drake_lcm_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#20129 [py visualization] De-flake TestModelVisualizer.test_reload
  bindings/pydrake/visualization/test/model_visualizer_test.py
Labels: priority: medium, status: single reviewer ok, release notes: none

#20110 Implements SAP constraint to model PD controllers
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_pd_controller_constraint.cc
  multibody/contact_solvers/sap/sap_pd_controller_constraint.h
  multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc
Labels: release notes: none

#20114 Update primitives and examples to use modern event API
  examples/rod2d/rod2d.cc
  examples/rod2d/rod2d.h
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc
  manipulation/schunk_wsg/schunk_wsg_trajectory_generator.h
  planning/trajectory_optimization/test/direct_transcription_test.cc
  systems/controllers/linear_model_predictive_controller.cc
  systems/controllers/linear_model_predictive_controller.h
  systems/controllers/test/linear_model_predictive_controller_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/system_symbolic_inspector_test.cc
  systems/framework/test_utilities/initialization_test_system.h
  systems/primitives/discrete_derivative.cc
  systems/primitives/discrete_derivative.h
  systems/primitives/symbolic_vector_system.cc
  systems/primitives/symbolic_vector_system.h
  systems/primitives/test/linear_system_test.cc
Labels: priority: low, release notes: none

#19699 [geometry] Detect problems in hydroelastic tetrahedral meshes
  geometry/proximity/BUILD.bazel
  geometry/proximity/detect_zero_simplex.cc
  geometry/proximity/detect_zero_simplex.h
  geometry/proximity/test/detect_zero_simplex_test.cc
Labels: release notes: none

#20138 [planning] CollisionChecker parallelism updates
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py_collision_checker.cc
  bindings/pydrake/planning/planning_py_collision_checker_interface_types.cc
  bindings/pydrake/planning/test/collision_checker_test.py
  planning/BUILD.bazel
  planning/collision_avoidance.cc
  planning/collision_avoidance.h
  planning/collision_checker.cc
  planning/collision_checker.h
  planning/collision_checker_params.h
  planning/test/collision_avoidance_test.cc
  planning/test/collision_checker_test.cc
  planning/test_utilities/collision_checker_abstract_test_suite.cc
  planning/test_utilities/collision_checker_abstract_test_suite.h
  planning/visibility_graph.cc
Labels: status: squashing now, release notes: feature

#20118 GraphOfConvexSets: don't try to display costs for convex restriction solutions
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: fix

#20142 [wheel] Update xz url to newly mirrored 5.2.5
  tools/wheel/image/dependencies/projects.cmake
Labels: priority: high, status: single reviewer ok, release notes: none

#20147 [workspace] Upgrade stable_baselines3_internal to latest release v2.1.0
  tools/workspace/stable_baselines3_internal/patches/version.patch
  tools/workspace/stable_baselines3_internal/repository.bzl
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#19982 HyperRectangles and Volume of Convex Sets
  bindings/pydrake/geometry/geometry_py_optimization.cc
  geometry/optimization/BUILD.bazel
  geometry/optimization/affine_subspace.cc
  geometry/optimization/affine_subspace.h
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/hyperrectangle.cc
  geometry/optimization/hyperrectangle.h
  geometry/optimization/intersection.cc
  geometry/optimization/intersection.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/point.cc
  geometry/optimization/point.h
  geometry/optimization/spectrahedron.cc
  geometry/optimization/spectrahedron.h
  geometry/optimization/test/cartesian_product_test.cc
  geometry/optimization/test/convex_set_test.cc
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/optimization/test/hyperellipsoid_test.cc
  geometry/optimization/test/hyperrectangle_test.cc
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/test_utilities.h
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: status: squashing now, release notes: feature

#20148 Upgrade Externals September 2023
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/buildifier/repository.bzl
  tools/workspace/googlebenchmark/repository.bzl
  tools/workspace/gymnasium_py/repository.bzl
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/rules_python/repository.bzl
  tools/workspace/tinyobjloader_internal/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#19945 [workspace] Use VTK built from source
  geometry/proximity/BUILD.bazel
  geometry/render_gl/BUILD.bazel
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/factory.h
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  systems/sensors/BUILD.bazel
  systems/sensors/test_utilities/BUILD.bazel
  third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl
  tools/dynamic_analysis/lsan.supp
  tools/dynamic_analysis/tsan.supp
  tools/dynamic_analysis/valgrind.supp
  tools/install/libdrake/BUILD.bazel
  tools/wheel/Dockerfile
  tools/wheel/image/build-vtk.sh
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/double-conversion.cmake
  tools/wheel/image/dependencies/projects/lz4.cmake
  tools/wheel/image/vtk-args
  tools/wheel/macos/build-wheel.sh
  tools/wheel/wheel_builder/macos.py
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/double_conversion/package.BUILD.bazel
  tools/workspace/glew/repository.bzl
  tools/workspace/liblz4/repository.bzl
  tools/workspace/liblzma/repository.bzl
  tools/workspace/mirrors.bzl
  tools/workspace/vtk/.dockerignore
  tools/workspace/vtk/BUILD.bazel
  tools/workspace/vtk/Dockerfile
  tools/workspace/vtk/README.md
  tools/workspace/vtk/build_binaries_with_docker
  tools/workspace/vtk/find_vtk_headers.py
  tools/workspace/vtk/image/build-vtk.sh
  tools/workspace/vtk/image/package.sh
  tools/workspace/vtk/image/prereqs
  tools/workspace/vtk/image/provision.sh
  tools/workspace/vtk/image/vtk-args
  tools/workspace/vtk/repository.bzl
  tools/workspace/vtk_internal/BUILD.bazel
  tools/workspace/vtk_internal/gen/README.md
  tools/workspace/vtk_internal/gen/vtkRenderingOpenGL2ObjectFactory.cxx
  tools/workspace/vtk_internal/gen/vtkRenderingOpenGL2ObjectFactory.h
  tools/workspace/vtk_internal/package.BUILD.bazel
  tools/workspace/vtk_internal/rules.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: medium, release notes: newly deprecated, release notes: feature

#20143 [render_vtk] Add gflag for show_window
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
Labels: priority: backlog, status: single reviewer ok, release notes: none

#20145 [workspace] Upgrade abseil_cpp_internal to latest commit
  tools/workspace/abseil_cpp_internal/patches/disable_int128_on_clang.patch
  tools/workspace/abseil_cpp_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#20155 [optimization] Fix LimitMalloc vs MosekSolver fighting in unit tests
  geometry/optimization/BUILD.bazel
  geometry/optimization/test/convex_set_limit_malloc_test.cc
  geometry/optimization/test/convex_set_solving_test.cc
  geometry/optimization/test/convex_set_test.cc
Labels: priority: high, status: squashing now, status: single reviewer ok, release notes: none

#20099 [common] Add polynomial matrix multiplication overloads
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_overloads_matrix_test.py
  common/symbolic/expression/expression.cc
  common/symbolic/expression/expression.h
  common/symbolic/expression/test/expression_matrix_test.cc
  common/symbolic/polynomial.cc
  common/symbolic/polynomial.h
  common/symbolic/test/monomial_test.cc
  common/symbolic/test/polynomial_matrix_test.cc
  common/symbolic/test/polynomial_test.cc
  systems/primitives/test/linear_system_test.cc
Labels: release notes: feature

#20146 [workspace] Upgrade gz_math_internal to latest release gz-math7_7.3.0
  tools/workspace/gz_math_internal/package.BUILD.bazel
  tools/workspace/gz_math_internal/repository.bzl
Labels: status: squashing now, release notes: fix

#20158 [symbolic] Opt-in to clang-format-lint
  common/symbolic/BUILD.bazel
  common/symbolic/decompose.cc
  common/symbolic/generic_polynomial.h
  common/symbolic/latex.cc
  common/symbolic/monomial.cc
  common/symbolic/monomial.h
  common/symbolic/monomial_basis_element.h
  common/symbolic/polynomial.cc
  common/symbolic/polynomial.h
  common/symbolic/rational_function.cc
  common/symbolic/rational_function.h
  common/symbolic/test/codegen_test.cc
  common/symbolic/test/decompose_test.cc
  common/symbolic/test/polynomial_basis_element_test.cc
  common/symbolic/test/rational_function_test.cc
  common/symbolic/test/simplification_test.cc
  common/symbolic/trigonometric_polynomial.cc
  common/symbolic/trigonometric_polynomial.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#20163 Bump VGT with workaround for macOS OpenCL and fixes for Intel OpenCL
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#20157 [tools] Claw back some disk space under UBSan
  tools/dynamic_analysis/bazel.rc
Labels: priority: high, status: single reviewer ok, release notes: none

#20161 Implements symbolic::Polynomial::Roots()
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic/BUILD.bazel
  common/symbolic/polynomial.cc
  common/symbolic/polynomial.h
  common/symbolic/test/polynomial_test.cc
Labels: release notes: feature

#20156 [tools] Switch ASan back to using ld.gold and fission
  tools/dynamic_analysis/bazel.rc
Labels: priority: high, status: single reviewer ok, release notes: none

#20166 [systems] Remove spurious deps
  examples/bouncing_ball/BUILD.bazel
  multibody/benchmarks/free_body/BUILD.bazel
  multibody/plant/BUILD.bazel
  multibody/tree/BUILD.bazel
  systems/analysis/BUILD.bazel
Labels: priority: backlog, status: single reviewer ok, release notes: none

#20167 [controllers] Add InverseDynamicsController deprecation annotation
  systems/controllers/inverse_dynamics_controller.cc
  systems/controllers/test/inverse_dynamics_controller_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#20107 [parsing] URDF planar joint uses canonical frame
  math/rotation_matrix.h
  math/test/rotation_matrix_test.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: release notes: fix, release notes: feature

#20140 [vis] MeshcatVisualizer and Meldis rely on meshcat APIs to handle alpha sliders
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
  geometry/meshcat_visualizer.cc
  geometry/meshcat_visualizer.h
  geometry/test/meshcat_visualizer_test.cc
  tools/workspace/meshcat/repository.bzl
  visualization/inertia_visualizer.cc
Labels: status: squashing now, release notes: fix

#20168 [kuka_iiwa] Opt-in to clang-format lint
  manipulation/kuka_iiwa/BUILD.bazel
  manipulation/kuka_iiwa/build_iiwa_control.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.cc
  manipulation/kuka_iiwa/iiwa_command_receiver.h
  manipulation/kuka_iiwa/iiwa_command_sender.cc
  manipulation/kuka_iiwa/iiwa_constants.cc
  manipulation/kuka_iiwa/iiwa_constants.h
  manipulation/kuka_iiwa/iiwa_driver_functions.cc
  manipulation/kuka_iiwa/iiwa_status_receiver.cc
  manipulation/kuka_iiwa/iiwa_status_sender.cc
  manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
  manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc
  manipulation/kuka_iiwa/test/iiwa_constants_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#20130 [py systems] Simulator.AdvanceTo is interruptible by default
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  systems/analysis/BUILD.bazel
  systems/analysis/simulator.cc
  systems/analysis/simulator.h
  systems/analysis/simulator_python_internal.h
  systems/analysis/test/simulator_python_internal_test.cc
  tools/skylark/pybind.bzl
Labels: priority: medium, release notes: feature

#20135 Remove PetscSymmetricBlockSparseMatrix
  multibody/fem/BUILD.bazel
  multibody/fem/dirichlet_boundary_condition.cc
  multibody/fem/dirichlet_boundary_condition.h
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
  multibody/fem/fem_model_impl.h
  multibody/fem/petsc_symmetric_block_sparse_matrix.cc
  multibody/fem/petsc_symmetric_block_sparse_matrix.h
  multibody/fem/test/dirichlet_boundary_condition_test.cc
  multibody/fem/test/fem_model_test.cc
  multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc
  multibody/fem/test/volumetric_model_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/coinutils_internal/package.BUILD.bazel
  tools/workspace/petsc/package.BUILD.bazel
Labels: priority: medium, release notes: none

#20170 [py visualization] Hotfix TestModelVisualizer.test_reload
  bindings/pydrake/visualization/test/model_visualizer_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#20169 Remove vtkAssembly from RenderEngineVtk
  geometry/render_gltf_client/internal_render_engine_gltf_client.h
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/internal_vtk_util.cc
  geometry/render_vtk/internal_vtk_util.h
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  geometry/render_vtk/test/internal_vtk_util_test.cc
Labels: release notes: none

#20111 Actuators with PD control implicitly integrated with SAP
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/BUILD.bazel
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/actuated_models_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/sap_driver_pd_controller_constraints_test.cc
  multibody/tree/joint_actuator.cc
  multibody/tree/joint_actuator.h
  multibody/tree/test/joint_actuator_test.cc
Labels: priority: high, release notes: feature

#20164 [symbolic] Give the default Variable a name
  common/symbolic/expression/BUILD.bazel
  common/symbolic/expression/environment.cc
  common/symbolic/expression/environment.h
  common/symbolic/expression/expression.h
  common/symbolic/expression/expression_cell.cc
  common/symbolic/expression/expression_cell.h
  common/symbolic/expression/formula.h
  common/symbolic/expression/formula_cell.cc
  common/symbolic/expression/formula_cell.h
  common/symbolic/expression/test/environment_test.cc
  common/symbolic/expression/test/variable_test.cc
  common/symbolic/expression/variable.cc
  common/symbolic/expression/variable.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: priority: high, release notes: fix

#20175 [doc] Refresh hydroelastic guide instructions for visualization
  examples/hydroelastic/ball_plate/README.md
  examples/hydroelastic/ball_plate/ball_plate_run_dynamics.cc
  examples/hydroelastic/ball_plate/images/ball_plate.jpg
  examples/hydroelastic/ball_plate/images/ball_plate_contact_polygons.jpg
  examples/hydroelastic/ball_plate/images/ball_plate_contact_triangles.jpg
  examples/hydroelastic/ball_plate/images/ball_plate_hydroelastic_contact_visualization_settings.jpg
  examples/hydroelastic/ball_plate/images/ball_plate_spin_the_ball.jpg
  multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
  multibody/hydroelastics/images/drake-vis-01.png
  multibody/hydroelastics/images/drake-vis-02.png
  multibody/hydroelastics/images/drake-vis-03.png
  multibody/hydroelastics/images/drake-vis-04.png
  multibody/hydroelastics/images/drake-vis-05.png
  multibody/hydroelastics/images/drake-vis-06.png
  multibody/hydroelastics/images/drake-vis-07.png
Labels: priority: low, release notes: none

#20183 [systems] Deprecate and nerf GenerateHtml
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
  systems/framework/BUILD.bazel
  systems/framework/system.h
  systems/framework/system_html.cc
  systems/framework/system_html.h
  systems/framework/test/system_html_test.cc
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#20181 [py optimization] Add missing repr and docs for polytope options
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/cspace_free_polytope_base.h
Labels: priority: low, status: single reviewer ok, release notes: fix

#20098 [multibody] Add SapFixedConstraint
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_fixed_constraint.cc
  multibody/contact_solvers/sap/sap_fixed_constraint.h
  multibody/contact_solvers/sap/test/sap_fixed_constraint_test.cc
Labels: release notes: none

#20134 [doc] Add release notes v1.21.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.21.0.md
Labels: status: squashing now, release notes: none

#20194 [tutorials] Remove unsupported matplotlib argument
  tutorials/dynamical_systems.ipynb
Labels: status: single reviewer ok, release notes: none

#20192 [tutorial] Fix LaTeX display in nonlinear program
  tutorials/nonlinear_program.ipynb
Labels: status: single reviewer ok, release notes: none

#20189 [doc] Advertise PEP 503 nightly pip wheel Index
  doc/_pages/pip.md
Labels: priority: medium, release notes: fix

#20196 [controllers] Remove PidController's special Graphviz
  systems/controllers/pid_controller.cc
  systems/controllers/pid_controller.h
  systems/controllers/test/pid_controller_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#20197 [systems/lcm] Opt-in to clang-format-lint
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_buses.cc
  systems/lcm/lcm_buses.h
  systems/lcm/lcm_config_functions.cc
  systems/lcm/lcm_config_functions.h
  systems/lcm/lcm_interface_system.cc
  systems/lcm/lcm_interface_system.h
  systems/lcm/lcm_log_playback_system.cc
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/lcm_publisher_system.h
  systems/lcm/lcm_scope_system.cc
  systems/lcm/lcm_scope_system.h
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/serializer.h
  systems/lcm/test/lcm_config_functions_test.cc
  systems/lcm/test/lcm_interface_system_test.cc
  systems/lcm/test/lcm_log_playback_test.cc
  systems/lcm/test/lcm_publisher_system_test.cc
  systems/lcm/test/lcm_scope_system_test.cc
  systems/lcm/test/lcm_subscriber_system_test.cc
  systems/lcm/test/serializer_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#20199 Use bullet point rather than number list in MosekSolver doxygen.
  solvers/mosek_solver.h
Labels: status: single reviewer ok, release notes: none

#20201 Fix HPolyhedronTest.
  geometry/optimization/test/hpolyhedron_test.cc
Labels: status: single reviewer ok, release notes: none

#20200 [framework] Move GetMemoryObjectName to SystemBase
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/test/system_base_test.cc
  systems/framework/test/system_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#20195 [workspace] Upgrade sdformat_internal to latest release sdformat13_13.6.0
  multibody/parsing/test/parser_test.cc
  tools/workspace/sdformat_internal/patches/deprecation_unit_testing.patch
  tools/workspace/sdformat_internal/patches/no_urdf.patch
  tools/workspace/sdformat_internal/repository.bzl
Labels: release notes: none

#20198 [hardware_sim] Add option to output Graphviz
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/hardware_sim.cc
  examples/hardware_sim/hardware_sim.py
  examples/hardware_sim/test/hardware_sim_test_common.py
Labels: priority: medium, status: single reviewer ok, release notes: feature

#20205 [render_vtk] Nerf the macOS arm64 tests even harder
  geometry/render_vtk/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#20208 [py systems] Fix clang-format to avoid "mission accomplished"
  bindings/pydrake/systems/framework_py_systems.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#20215 Disconnected actuation input ports evaluate to zero actuation
  multibody/plant/multibody_plant.cc
  multibody/plant/test/actuated_models_test.cc
Labels: priority: high, release notes: fix

#20216 Move DeformableBodyId/Index out of deformable_model.h
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_ids.h
  multibody/plant/deformable_model.h
Labels: status: single reviewer ok, release notes: none

#20219 [workspace] Fail-fast in miscofigured VTK build on macOS
  doc/_release-notes/v1.21.0.md
  tools/workspace/vtk_internal/package.BUILD.bazel
  tools/workspace/vtk_internal/rules.bzl
Labels: priority: medium, status: single reviewer ok, release notes: fix

#20218 [github] Add macOS 13 to issue template drop-down
  .github/ISSUE_TEMPLATE/BUG.yml
Labels: priority: low, status: single reviewer ok, release notes: none

#20204 [framework] Improve system graphviz output
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  examples/hardware_sim/hardware_sim.cc
  systems/framework/diagram.cc
  systems/framework/diagram.h
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_system_test.cc
Labels: priority: medium, release notes: newly deprecated, release notes: feature

#20213 [symbolic] Unify comment formatting in Polynomial and Monomial
  common/symbolic/monomial.h
  common/symbolic/polynomial.h
Labels: release notes: none

#20178 [py solvers] Improve error message for evaluator return type mistakes
  bindings/pydrake/solvers/_extra.py
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: priority: backlog, status: single reviewer ok, release notes: fix

#20227 [hardware_sim] Fix graphviz output
  examples/hardware_sim/hardware_sim.cc
  examples/hardware_sim/hardware_sim.py
  examples/hardware_sim/test/hardware_sim_test_common.py
Labels: status: single reviewer ok, release notes: none

#20182 [kuka_iiwa] Factor non-LCM iiwa driver into a separate Diagram
  bindings/pydrake/manipulation/test/kuka_iiwa_test.py
  manipulation/kuka_iiwa/BUILD.bazel
  manipulation/kuka_iiwa/build_iiwa_control.cc
  manipulation/kuka_iiwa/build_iiwa_control.h
  manipulation/kuka_iiwa/sim_iiwa_driver.cc
  manipulation/kuka_iiwa/sim_iiwa_driver.h
  manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
  manipulation/kuka_iiwa/test/sim_iiwa_driver_test.cc
Labels: priority: medium, release notes: fix

#20237 [meshcat] Set Content-Type for HTML pages
  bindings/pydrake/geometry/test/visualizers_test.py
  geometry/meshcat.cc
  geometry/test/meshcat_test.cc
Labels: priority: low, status: single reviewer ok, release notes: fix

#20239 [framework] Add DiagramBuilder num_{input/output}_ports accessors
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
  systems/framework/test/diagram_builder_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: feature

#20160 Add more tests on the BoundingBoxConstraint dual solution.
  solvers/test/clp_solver_test.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/ipopt_solver_test.cc
  solvers/test/linear_program_examples.cc
  solvers/test/linear_program_examples.h
  solvers/test/mosek_solver_test.cc
  solvers/test/scs_solver_test.cc
  solvers/test/snopt_solver_test.cc
Labels: release notes: none

#20041 Specify fixed constraints
  geometry/query_results/deformable_contact.cc
  geometry/query_results/deformable_contact.h
  geometry/query_results/test/deformable_contact_test.cc
  multibody/contact_solvers/sap/sap_fixed_constraint.cc
  multibody/contact_solvers/sap/sap_fixed_constraint.h
  multibody/contact_solvers/sap/test/sap_fixed_constraint_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/constraint_specs.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/deformable_model_test.cc
Labels: release notes: none

#20245 [workspace] Remove the libcmaes external
  tools/workspace/default.bzl
  tools/workspace/libcmaes/BUILD.bazel
  tools/workspace/libcmaes/dev/BUILD.bazel
  tools/workspace/libcmaes/dev/sample_code.cc
  tools/workspace/libcmaes/package.BUILD.bazel
  tools/workspace/libcmaes/repository.bzl
Labels: priority: low, release notes: fix

#20228 [systems] Don't render SharedPointerSystem in Graphviz
  systems/primitives/shared_pointer_system.cc
  systems/primitives/shared_pointer_system.h
  systems/primitives/test/shared_pointer_system_test.cc
Labels: priority: low, release notes: fix

#20241 [planning] RobotDiagramBuilder fails fast on a missing MbP or SG
  planning/BUILD.bazel
  planning/robot_diagram_builder.cc
  planning/robot_diagram_builder.h
  planning/test/robot_diagram_test.cc
Labels: priority: low, release notes: fix

#20236 [render] RenderMaterial offers more nuanced and complete warnings
  geometry/render/render_material.cc
  geometry/render/render_material.h
  geometry/render/render_mesh.cc
  geometry/render/render_mesh.h
  geometry/render/test/render_material_test.cc
  geometry/render/test/render_mesh_test.cc
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_opengl_geometry.h
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/test/internal_opengl_geometry_test.cc
  geometry/render_vtk/internal_render_engine_vtk.cc
Labels: release notes: none

#20184 RenderEngineGltfClient changes how input glTFs are handled
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_merge_gltf.cc
  geometry/render_gltf_client/internal_merge_gltf.h
  geometry/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render_gltf_client/internal_render_engine_gltf_client.h
  geometry/render_gltf_client/test/internal_merge_gltf_test.cc
Labels: status: squashing now, release notes: fix

#20248 Add RenderEngineGltfClient to the rendering documentation
  geometry/render/render_doxygen.h
Labels: status: single reviewer ok, release notes: none

#20177 Fix segfault in SAP when caching is disabled
  multibody/plant/sap_driver.cc
  multibody/plant/test/sap_driver_test.cc
Labels: priority: low, release notes: fix

#20229 Add MinimumValueLower/UpperBoundConstraint
  solvers/minimum_value_constraint.cc
  solvers/minimum_value_constraint.h
  solvers/test/minimum_value_constraint_test.cc
Labels: release notes: none

#20242 [bazel] Remove irrelevant rcfile flag
  tools/bazel.rc
Labels: priority: backlog, status: single reviewer ok, release notes: none

#20252 [math] Add hash_append to RollPitchYaw/RotationMatrix/RigidTransform
  math/BUILD.bazel
  math/rigid_transform.h
  math/roll_pitch_yaw.h
  math/rotation_matrix.h
  math/test/rigid_transform_test.cc
  math/test/roll_pitch_yaw_test.cc
  math/test/rotation_matrix_test.cc
Labels: priority: low, release notes: feature

#20262 Mosek license acquisition failure prints more info
  solvers/mosek_solver.cc
Labels: status: single reviewer ok, release notes: fix

#20249 SapDriver supports fixed constraints
  multibody/plant/BUILD.bazel
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/deformable_fixed_constraint_test.cc
Labels: release notes: none

#20269 [hotfix] Mac fmt::format chokes on enum
  solvers/mosek_solver.cc
Labels: release notes: none

#20238 [planning] Export ports from RobotDiagram by default
  planning/robot_diagram.cc
  planning/robot_diagram.h
  planning/robot_diagram_builder.cc
  planning/robot_diagram_builder.h
  planning/test/robot_diagram_test.cc
Labels: priority: low, release notes: feature

#20261 [workspace] Patch clang.cindex vs Clang 15
  tools/workspace/clang_cindex_python3_internal/changelog.txt
  tools/workspace/clang_cindex_python3_internal/patches/clang-15.patch
  tools/workspace/clang_cindex_python3_internal/repository.bzl
  tools/workspace/pybind11/mkdoc.py
Labels: priority: high, status: single reviewer ok, release notes: fix

#20259 Removes duplicated contribution of actuation when using PD controllers
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/tamsi_driver.cc
  multibody/plant/test/actuated_models_test.cc
  multibody/plant/test/compliant_contact_manager_tester.h
Labels: priority: high, release notes: fix

#20264 Implement APIs to enable/disable gravity
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/gravity_test.cc
  multibody/tree/uniform_gravity_field_element.cc
  multibody/tree/uniform_gravity_field_element.h
  systems/controllers/inverse_dynamics.h
  systems/controllers/inverse_dynamics_controller.h
Labels: release notes: feature

#20250 Parsing an .obj file can produce multiple RenderMesh instances
  geometry/render/render_mesh.cc
  geometry/render/render_mesh.h
  geometry/render/test/render_mesh_test.cc
Labels: release notes: none

#20257 [meldis] Offer --browser selection on the command line
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: priority: low, release notes: feature

#20209 Add DiscreteContactData
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/discrete_contact_data.h
  multibody/plant/sap_driver.cc
  multibody/plant/tamsi_driver.cc
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/compliant_contact_manager_tester.h
  multibody/plant/test/deformable_contact_results_test.cc
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/deformable_driver_contact_test.cc
  multibody/plant/test/discrete_contact_data_test.cc
  multibody/plant/test/sap_driver_joint_limits_test.cc
  multibody/plant/test/sap_driver_test.cc
Labels: release notes: fix

#20275 [workspace] Fix deprecation notations in pkg-config
  tools/workspace/glew/repository.bzl
  tools/workspace/liblzma/repository.bzl
  tools/workspace/pkg_config.bzl
Labels: priority: medium, status: single reviewer ok, release notes: none

#20240 [geometry] Strengthen VTK to volume mesh error cases
  geometry/BUILD.bazel
  geometry/proximity/test/vtk_to_volume_mesh_test.cc
  geometry/proximity/vtk_to_volume_mesh.cc
  geometry/test/bad_tet.vtk
  geometry/test/cube_as_6_squares.vtk
  geometry/test/some_volume.vtk
  geometry/test/unstructured.vtk
Labels: release notes: fix

#20266 Split MinimumDistanceConstraint.
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/distance_constraint_utilities.cc
  multibody/inverse_kinematics/distance_constraint_utilities.h
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/minimum_distance_constraint.cc
  multibody/inverse_kinematics/minimum_distance_lower_bound_constraint.cc
  multibody/inverse_kinematics/minimum_distance_lower_bound_constraint.h
  multibody/inverse_kinematics/minimum_distance_upper_bound_constraint.cc
  multibody/inverse_kinematics/minimum_distance_upper_bound_constraint.h
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h
  multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
Labels: status: squashing now, release notes: none

#20277 [tools] Fix mis-detection of linux platform
  tools/install/libdrake/test/snopt_visibility_install_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#20280 [hotfix] Crafted vtk file caused UB inside VTK
  geometry/BUILD.bazel
  geometry/proximity/test/vtk_to_volume_mesh_test.cc
  geometry/test/bad_tet.vtk
Labels: priority: emergency, release notes: none

#20254 [visualization] ColorizeDepthImage takes 32F and 16U depth as input
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/_lcm_image_array_viewer.py
  bindings/pydrake/visualization/_video.py
  bindings/pydrake/visualization/test/video_test.py
Labels: priority: low, release notes: none

#20246 [workspace] Add clarabel_cpp_internal as an opt-in dependency
  .gitattributes
  WORKSPACE
  tools/BUILD.bazel
  tools/bazel.rc
  tools/ubuntu-focal.bazelrc
  tools/workspace/build_bazel_apple_support/BUILD.bazel
  tools/workspace/build_bazel_apple_support/repository.bzl
  tools/workspace/clarabel_cpp_internal/BUILD.bazel
  tools/workspace/clarabel_cpp_internal/package.BUILD.bazel
  tools/workspace/clarabel_cpp_internal/patches/git_submodule.patch
  tools/workspace/clarabel_cpp_internal/repository.bzl
  tools/workspace/clarabel_cpp_internal/test/clarabel_example_lp.cc
  tools/workspace/clarabel_cpp_internal/test/noop.cc
  tools/workspace/crate_universe/BUILD.bazel
  tools/workspace/crate_universe/README.md
  tools/workspace/crate_universe/defs.bzl
  tools/workspace/crate_universe/lock/Cargo.toml.lock
  tools/workspace/crate_universe/lock/archives.bzl
  tools/workspace/crate_universe/lock/details/BUILD.amd-0.2.2.bazel
  tools/workspace/crate_universe/lock/details/BUILD.autocfg-1.1.0.bazel
  tools/workspace/crate_universe/lock/details/BUILD.bazel
  tools/workspace/crate_universe/lock/details/BUILD.cfg-if-1.0.0.bazel
  tools/workspace/crate_universe/lock/details/BUILD.clarabel-0.6.0.bazel
  tools/workspace/crate_universe/lock/details/BUILD.darling-0.14.4.bazel
  tools/workspace/crate_universe/lock/details/BUILD.darling_core-0.14.4.bazel
  tools/workspace/crate_universe/lock/details/BUILD.darling_macro-0.14.4.bazel
  tools/workspace/crate_universe/lock/details/BUILD.derive_builder-0.11.2.bazel
  tools/workspace/crate_universe/lock/details/BUILD.derive_builder_core-0.11.2.bazel
  tools/workspace/crate_universe/lock/details/BUILD.derive_builder_macro-0.11.2.bazel
  tools/workspace/crate_universe/lock/details/BUILD.either-1.9.0.bazel
  tools/workspace/crate_universe/lock/details/BUILD.enum_dispatch-0.3.12.bazel
  tools/workspace/crate_universe/lock/details/BUILD.fnv-1.0.7.bazel
  tools/workspace/crate_universe/lock/details/BUILD.ident_case-1.0.1.bazel
  tools/workspace/crate_universe/lock/details/BUILD.itertools-0.11.0.bazel
  tools/workspace/crate_universe/lock/details/BUILD.lazy_static-1.4.0.bazel
  tools/workspace/crate_universe/lock/details/BUILD.num-traits-0.2.16.bazel
  tools/workspace/crate_universe/lock/details/BUILD.once_cell-1.18.0.bazel
  tools/workspace/crate_universe/lock/details/BUILD.proc-macro2-1.0.67.bazel
  tools/workspace/crate_universe/lock/details/BUILD.quote-1.0.33.bazel
  tools/workspace/crate_universe/lock/details/BUILD.strsim-0.10.0.bazel
  tools/workspace/crate_universe/lock/details/BUILD.syn-1.0.109.bazel
  tools/workspace/crate_universe/lock/details/BUILD.syn-2.0.37.bazel
  tools/workspace/crate_universe/lock/details/BUILD.thiserror-1.0.48.bazel
  tools/workspace/crate_universe/lock/details/BUILD.thiserror-impl-1.0.48.bazel
  tools/workspace/crate_universe/lock/details/BUILD.unicode-ident-1.0.12.bazel
  tools/workspace/crate_universe/lock/details/defs.bzl
  tools/workspace/crate_universe/repository.bzl
  tools/workspace/crate_universe/upgrade.sh
  tools/workspace/default.bzl
  tools/workspace/mirrors.bzl
  tools/workspace/rules_rust/BUILD.bazel
  tools/workspace/rules_rust/repository.bzl
  tools/workspace/rules_rust_tinyjson/BUILD.bazel
  tools/workspace/rules_rust_tinyjson/repository.bzl
Labels: priority: low, release notes: feature

#20281 Revert "Parsing an .obj file can produce multiple RenderMesh instances"
  geometry/render/render_mesh.cc
  geometry/render/render_mesh.h
  geometry/render/test/render_mesh_test.cc
Labels: status: single reviewer ok, release notes: none

#20287 Refactor MGChaoticBabyboot methods to use explicit array sizes.
  multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc
  multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.h
Labels: status: single reviewer ok, release notes: fix

#20286 [vtk_internal] Patch to work around memcheck false positives
  tools/workspace/vtk_internal/patches/io_legacy_data_reader_uninit.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: status: single reviewer ok, release notes: none

#20263 [doc] Bump Bazel minimum version to 5.1
  CMakeLists.txt
  WORKSPACE
  doc/_release-notes/v1.21.0.md
Labels: priority: low, status: single reviewer ok, release notes: none
