Repository RobotLocomotion/drake, pull requests merged in 2023-06, with the labels that each got.

#19509 JointActuator Python bindings for rotor inertias
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: single reviewer ok, component: multibody plant, release notes: feature

#19506 [doc] Guidance to review tutorials
  tutorials/_developers.md
Labels: release notes: none

#19505 Fix visualization of contact_surface_rigid_bowl_soft_ball
  geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc
Labels: release notes: none, release notes: fix

#19465 Add BlockSparseLowerTriangularOrSymmetricMatrix
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h
  multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
Labels: release notes: none

#19516 Remove deprecated code 2023-06
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/planner.py
  bindings/pydrake/manipulation/test/planner_deprecated_test.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py_robot_diagram.cc
  bindings/pydrake/planning/test/robot_diagram_test.py
  common/constants.h
  common/copyable_unique_ptr.h
  common/eigen_types.h
  common/sorted_pair.h
  common/test/copyable_unique_ptr_test.cc
  common/test/sorted_pair_test.cc
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/distance_to_point_callback_test.cc
  geometry/proximity/test/mesh_plane_intersection_test.cc
  geometry/test/kinematics_vector_test.cc
  manipulation/planner/BUILD.bazel
  manipulation/planner/stub/constraint_relaxing_ik.h
  manipulation/planner/stub/differential_inverse_kinematics.h
  manipulation/planner/stub/differential_inverse_kinematics_integrator.h
  manipulation/planner/stub/robot_plan_interpolator.h
  manipulation/planner/test/deprecation_test.cc
  multibody/tree/multibody_tree.cc
  planning/robot_diagram_builder.h
  planning/test/robot_diagram_test.cc
  solvers/solver_base.cc
  solvers/solver_base.h
  solvers/test/solver_base_test.cc
  systems/controllers/test/zmp_planner_test.cc
  systems/controllers/test/zmp_test_util.h
  systems/controllers/zmp_planner.h
  tools/install/libdrake/build_components.bzl
Labels: status: single reviewer ok, release notes: removal of deprecated

#19518 [setup] Remove deprecated code 2023-06
  setup/mac/install_prereqs.sh
Labels: status: single reviewer ok, release notes: removal of deprecated

#19521 Python bind RotationalInertia::CalcPrincipalMomentsAndAxesOfInertia()
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
Labels: status: squashing now, status: single reviewer ok, release notes: feature

#19508 OpenGlInstance now references OpenGlGeometry in preparation for cloning
  geometry/render_gl/internal_opengl_geometry.h
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/test/internal_opengl_geometry_test.cc
  geometry/render_gl/test/internal_render_engine_gl_test.cc
Labels: release notes: none

#19530 Disable RenderEngineVtkTest.NonUcharChannelTextures test on Mac Arm
  geometry/render_vtk/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#17518 [performance] Add allocation reporting
  multibody/benchmarking/cassie.cc
  tools/BUILD.bazel
  tools/dynamic_analysis/bazel.rc
  tools/performance/BUILD.bazel
  tools/performance/fixture_memory.h
  tools/performance/fixture_memory_no.cc
  tools/performance/fixture_memory_yes.cc
  tools/performance/gflags_main.cc
  tools/workspace/googlebenchmark/patches/console_allocs.patch
  tools/workspace/googlebenchmark/patches/string_precision.patch
  tools/workspace/googlebenchmark/repository.bzl
Labels: priority: low, release notes: none

#19533 MultibodyPlant no longer assigned perception color
  multibody/plant/multibody_plant.cc
Labels: release notes: fix

#19507 [rendering] TextureLibrary upgraded to prepare for cloning
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/internal_shader_program.h
  geometry/render_gl/internal_texture_library.cc
  geometry/render_gl/internal_texture_library.h
  geometry/render_gl/test/internal_texture_library_test.cc
  geometry/render_gl/test/multithread_safety_test.cc
Labels: release notes: none

#19539 [workspace] Upgrade bazel_skylib to latest release 1.4.2
  tools/workspace/bazel_skylib/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#19467 [tutorials] Basic hydroelastic contact
  tutorials/BUILD.bazel
  tutorials/authoring_multibody_simulation.ipynb
  tutorials/hydroelastic_basics.ipynb
  tutorials/index.ipynb
Labels: release notes: feature

#19515 [doc] Soften the warnings around Anaconda
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_pages/python_bindings.md
  setup/mac/binary_distribution/install_prereqs.sh
  setup/ubuntu/binary_distribution/install_prereqs.sh
Labels: priority: low, release notes: none

#19525 [geometry] Add SceneGraphInspector::GetAllSourceIds
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/test/scene_graph_test.py
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/scene_graph.h
  geometry/scene_graph_inspector.cc
  geometry/scene_graph_inspector.h
  geometry/test/geometry_state_test.cc
  geometry/test/scene_graph_inspector_test.cc
Labels: priority: medium, release notes: feature

#19529 [math] Narrow the circular dependency on systems/primitives
  math/BUILD.bazel
  math/continuous_algebraic_riccati_equation.cc
  systems/primitives/BUILD.bazel
  systems/primitives/linear_system.cc
  systems/primitives/linear_system_internal.cc
  systems/primitives/linear_system_internal.h
Labels: priority: low, release notes: none

#19541 [pydrake] Mark systems lcm_test as flaky
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/systems/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#19321 Add a default constructor to all ConvexSet subclasses
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/intersection.cc
  geometry/optimization/intersection.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/minkowski_sum.h
  geometry/optimization/point.cc
  geometry/optimization/point.h
  geometry/optimization/test/cartesian_product_test.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/optimization/test/hyperellipsoid_test.cc
  geometry/optimization/test/intersection_test.cc
  geometry/optimization/test/minkowski_sum_test.cc
  geometry/optimization/test/point_test.cc
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
Labels: priority: medium, release notes: feature

#19536 Upgrade Externals June 2023
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/curl_internal/package.BUILD.bazel
  tools/workspace/curl_internal/repository.bzl
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/petsc/repository.bzl
  tools/workspace/ros_xacro_internal/repository.bzl
  tools/workspace/sdformat_internal/package.BUILD.bazel
  tools/workspace/sdformat_internal/repository.bzl
  tools/workspace/tinyobjloader/repository.bzl
  tools/workspace/typing_extensions_internal/repository.bzl
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#19543 [parsing] Improve inertia warning text to be more specific
  multibody/parsing/detail_common.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#19527 Implement the more general perspective function for Spectrahedron
  geometry/optimization/convex_set.h
  geometry/optimization/spectrahedron.cc
  geometry/optimization/test/spectrahedron_test.cc
Labels: release notes: feature

#19512 Serializes IrisOptions
  geometry/optimization/BUILD.bazel
  geometry/optimization/iris.h
  geometry/optimization/test/iris_test.cc
Labels: release notes: feature

#19542 Zero out rows and columns in block sparse matrix
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h
  multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
Labels: release notes: none

#19537 [workspace] Upgrade googlebenchmark to latest release v1.8.0
  multibody/benchmarking/position_constraint.cc
  tools/performance/fixture_memory_yes.cc
  tools/workspace/googlebenchmark/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#19444 [planning] Removed unnecessary variables in constraints
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: none

#19556 Fix an aliasing bug in block sparse matrix
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc
  multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
Labels: status: single reviewer ok, release notes: none

#19500 Updated URDFs for Franka with the reflected rotor inertia values
  manipulation/models/franka_description/README.md
  manipulation/models/franka_description/urdf/panda_arm.urdf
  manipulation/models/franka_description/urdf/panda_arm_hand.urdf
  manipulation/models/franka_description/urdf/test/franka_arm_test.cc
Labels: release notes: fix

#19311 Fix ConvexSet move operations
  geometry/optimization/convex_set.h
  geometry/optimization/test/cartesian_product_test.cc
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/optimization/test/hyperellipsoid_test.cc
  geometry/optimization/test/intersection_test.cc
  geometry/optimization/test/minkowski_sum_test.cc
  geometry/optimization/test/point_test.cc
  geometry/optimization/test/spectrahedron_test.cc
  geometry/optimization/test/vpolytope_test.cc
Labels: priority: medium, release notes: fix

#19488 [multibody] Reduce SapContactProblem to selected/excluded dofs.
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_constraint.cc
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/sap_contact_problem.h
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/slicing_and_indexing.cc
  multibody/plant/slicing_and_indexing.h
  multibody/plant/test/slicing_and_indexing_test.cc
Labels: type: feature request, component: multibody plant, release notes: none

#19545 Disallow partial Dirichlet BC for an FEM node
  multibody/fem/dirichlet_boundary_condition.cc
  multibody/fem/dirichlet_boundary_condition.h
  multibody/fem/fem_state.h
  multibody/fem/test/dirichlet_boundary_condition_test.cc
  multibody/fem/test/fem_model_test.cc
  multibody/fem/test/fem_state_test.cc
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_model.cc
Labels: release notes: none

#19210 [visualization] Add basic inertia visualizer
  visualization/BUILD.bazel
  visualization/inertia_visualizer.cc
  visualization/inertia_visualizer.h
  visualization/test/inertia_visualizer_test.cc
  visualization/test/visualization_config_functions_test.cc
  visualization/visualization_config.h
  visualization/visualization_config_functions.cc
Labels: release notes: feature

#19560 [tools] Opt-in to clang-format lint
  tools/install/dummy/BUILD.bazel
  tools/install/dummy/dummy.cc
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/test/drake_shared_library_test.cc
  tools/install/libdrake/test/fast_math_test.cc
  tools/vector_gen/BUILD.bazel
  tools/vector_gen/test/sample_test.cc
  tools/workspace/cc/BUILD.bazel
  tools/workspace/cc/identify_compiler.cc
  tools/workspace/petsc/BUILD.bazel
  tools/workspace/petsc/stubs/petscconf.h
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pybind11/test/sample_header_documentation_cc_test.cc
  tools/workspace/sdformat_internal/BUILD.bazel
  tools/workspace/sdformat_internal/gz_sdf_main.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#19426 Make RenderEngineGl intelligently threadsafe
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/factory.h
  geometry/render_gl/internal_opengl_context.cc
  geometry/render_gl/internal_opengl_context.h
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/internal_shader_program.cc
  geometry/render_gl/internal_shader_program.h
  geometry/render_gl/internal_texture_library.cc
  geometry/render_gl/internal_texture_library.h
  geometry/render_gl/test/internal_opengl_context_test.cc
  geometry/render_gl/test/internal_shader_program_test.cc
  geometry/render_gl/test/multithread_safety_test.cc
Labels: release notes: feature

#19510 Start refactoring push_release script
  tools/release_engineering/dev/BUILD.bazel
  tools/release_engineering/dev/README.md
  tools/release_engineering/dev/push_release
  tools/release_engineering/dev/push_release.py
Labels: release notes: none

#19565 Hotfix ODR violation in MeshcatPoseSliders bindings
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/visualization/visualization_py.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#19561 [manipulation] Opt-in to clang-format lint for models and util
  manipulation/models/allegro_hand_description/BUILD.bazel
  manipulation/models/allegro_hand_description/test/parse_test.cc
  manipulation/models/franka_description/BUILD.bazel
  manipulation/models/franka_description/urdf/test/franka_arm_test.cc
  manipulation/models/iiwa_description/BUILD.bazel
  manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc
  manipulation/models/jaco_description/BUILD.bazel
  manipulation/models/jaco_description/urdf/test/jaco_arm_test.cc
  manipulation/models/realsense2_description/BUILD.bazel
  manipulation/models/realsense2_description/test/realsense_parse_test.cc
  manipulation/models/wsg_50_description/BUILD.bazel
  manipulation/models/wsg_50_description/sdf/test/wsg_50_sdf_test.cc
  manipulation/models/ycb/BUILD.bazel
  manipulation/models/ycb/test/parse_test.cc
  manipulation/util/BUILD.bazel
  manipulation/util/apply_driver_configs.h
  manipulation/util/make_arm_controller_model.cc
  manipulation/util/move_ik_demo_base.cc
  manipulation/util/move_ik_demo_base.h
  manipulation/util/moving_average_filter.cc
  manipulation/util/robot_plan_interpolator.cc
  manipulation/util/robot_plan_interpolator.h
  manipulation/util/robot_plan_utils.cc
  manipulation/util/robot_plan_utils.h
  manipulation/util/stl2obj.cc
  manipulation/util/test/move_ik_demo_base_test.cc
  manipulation/util/test/robot_plan_interpolator_test.cc
  manipulation/util/test/robot_plan_utils_test.cc
  manipulation/util/zero_force_driver_functions.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#19414 RotationalInertia to equivalent principal lengths and axes for various shapes
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/rotational_inertia_test.cc
  multibody/tree/test/spatial_inertia_test.cc
  multibody/tree/test/unit_inertia_test.cc
  multibody/tree/unit_inertia.cc
  multibody/tree/unit_inertia.h
Labels: priority: medium, status: squashing now, release notes: feature

#19567 Increase model_visualizer_test timeout
  bindings/pydrake/visualization/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#19563 Implements MultibodyPlant::IsVelocityEqualToQDot
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  manipulation/util/robot_plan_interpolator.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/floating_body_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/mobilizer.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/planar_mobilizer.h
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/revolute_mobilizer.h
  multibody/tree/screw_mobilizer.h
  multibody/tree/space_xyz_floating_mobilizer.h
  multibody/tree/space_xyz_mobilizer.h
  multibody/tree/test/articulated_body_algorithm_test.cc
  multibody/tree/test/planar_mobilizer_test.cc
  multibody/tree/test/prismatic_mobilizer_test.cc
  multibody/tree/test/quaternion_floating_mobilizer_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
  multibody/tree/test/screw_mobilizer_test.cc
  multibody/tree/test/space_xyz_floating_mobilizer_test.cc
  multibody/tree/test/space_xyz_mobilizer_test.cc
  multibody/tree/test/universal_mobilizer_test.cc
  multibody/tree/test/weld_mobilizer_test.cc
  multibody/tree/universal_mobilizer.h
  multibody/tree/weld_mobilizer.h
  systems/controllers/joint_stiffness_controller.cc
  systems/controllers/joint_stiffness_controller.h
  systems/primitives/discrete_derivative.h
Labels: release notes: feature

#19568 [doc] Hotfix for system ports figure typo
  systems/controllers/joint_stiffness_controller.h
Labels: priority: emergency, status: single reviewer ok, release notes: none

#19573 Add iris_internal.h/cc.
  geometry/optimization/BUILD.bazel
  geometry/optimization/iris.cc
  geometry/optimization/iris_internal.cc
  geometry/optimization/iris_internal.h
Labels: status: single reviewer ok, release notes: none

#19572 [pydrake] Factor out DRAKE_PYBIND11_NUMPY_OBJECT_DTYPE helper
  bindings/pydrake/autodiff_types_pybind.h
  bindings/pydrake/polynomial_types_pybind.h
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/symbolic_types_pybind.h
Labels: priority: low, release notes: none

#19562 [tutorials] Fix typos for hydroelastic_basics.ipynb
  tutorials/hydroelastic_basics.ipynb
Labels: release notes: none

#19558 [sensors] Opt-in to clang-format lint
  systems/sensors/BUILD.bazel
  systems/sensors/accelerometer.h
  systems/sensors/beam_model.cc
  systems/sensors/camera_config.cc
  systems/sensors/camera_config_functions.cc
  systems/sensors/camera_info.cc
  systems/sensors/camera_info.h
  systems/sensors/color_palette.h
  systems/sensors/gyroscope.h
  systems/sensors/image.h
  systems/sensors/image_to_lcm_image_array_t.cc
  systems/sensors/image_to_lcm_image_array_t.h
  systems/sensors/image_writer.cc
  systems/sensors/image_writer.h
  systems/sensors/lcm_image_array_receive_example.cc
  systems/sensors/lcm_image_array_to_images.cc
  systems/sensors/lcm_image_traits.h
  systems/sensors/optitrack_receiver.cc
  systems/sensors/optitrack_receiver.h
  systems/sensors/optitrack_sender.cc
  systems/sensors/optitrack_sender.h
  systems/sensors/pixel_types.h
  systems/sensors/rotary_encoders.cc
  systems/sensors/rotary_encoders.h
  systems/sensors/sim_rgbd_sensor.h
  systems/sensors/test/beam_model_test.cc
  systems/sensors/test/camera_config_functions_test.cc
  systems/sensors/test/camera_config_test.cc
  systems/sensors/test/camera_info_test.cc
  systems/sensors/test/image_to_lcm_image_array_t_test.cc
  systems/sensors/test/image_writer_test.cc
  systems/sensors/test/lcm_image_array_to_images_test.cc
  systems/sensors/test/optitrack_receiver_test.cc
  systems/sensors/test/optitrack_sender_test.cc
  systems/sensors/test/rgbd_sensor_test.cc
  systems/sensors/test/rotary_encoders_test.cc
  systems/sensors/test/sim_rgbd_sensor_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#19570 [workspace] Use hdrs consistency checking for pybind11
  tools/workspace/pybind11/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#19279 ConvexSet can report when its just a point
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/intersection.cc
  geometry/optimization/intersection.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/minkowski_sum.h
  geometry/optimization/point.cc
  geometry/optimization/point.h
  geometry/optimization/spectrahedron.h
  geometry/optimization/test/cartesian_product_test.cc
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/optimization/test/hyperellipsoid_test.cc
  geometry/optimization/test/intersection_test.cc
  geometry/optimization/test/minkowski_sum_test.cc
  geometry/optimization/test/point_test.cc
  geometry/optimization/test/spectrahedron_test.cc
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
Labels: release notes: feature

#19552 Create CspaceFreeBox class constructor.
  geometry/optimization/BUILD.bazel
  geometry/optimization/cspace_free_box.cc
  geometry/optimization/cspace_free_box.h
  geometry/optimization/cspace_free_internal.cc
  geometry/optimization/cspace_free_internal.h
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/cspace_free_polytope.h
  geometry/optimization/cspace_free_polytope_base.cc
  geometry/optimization/cspace_free_polytope_base.h
  geometry/optimization/test/c_iris_test_utilities.h
  geometry/optimization/test/cspace_free_box_test.cc
  geometry/optimization/test/cspace_free_polytope_base_test.cc
  geometry/optimization/test/cspace_free_polytope_test.cc
Labels: release notes: none

#19576 [doc] Consolidate advice about PR size limits
  doc/_pages/code_review_checklist.md
  doc/_pages/developers.md
Labels: priority: low, release notes: none

#19583 [tutorials] Fix title of hydroelastic tutorial
  tutorials/BUILD.bazel
  tutorials/authoring_multibody_simulation.ipynb
  tutorials/hydroelastic_contact_basics.ipynb
  tutorials/index.ipynb
Labels: status: single reviewer ok, release notes: none

#19578 MeshcatVisualizer sets visibility directly without events
  geometry/meshcat_visualizer.cc
  geometry/meshcat_visualizer.h
  geometry/test/meshcat_visualizer_test.cc
Labels: release notes: fix

#19557 SapContactProblem reports multibody forces.
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_constraint.cc
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/sap_contact_problem.h
  multibody/contact_solvers/sap/sap_friction_cone_constraint.cc
  multibody/contact_solvers/sap/sap_holonomic_constraint.cc
  multibody/contact_solvers/sap/sap_limit_constraint.cc
  multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc
  multibody/contact_solvers/sap/test/sap_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
  multibody/contact_solvers/sap/test/sap_model_test.cc
  multibody/contact_solvers/sap/test/sap_solver_test.cc
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/sap_driver_multidof_joints_test.cc
Labels: release notes: none

#19587 [geometry] Add context validation to SceneGraph
  geometry/scene_graph.cc
  geometry/test/scene_graph_test.cc
Labels: status: single reviewer ok, release notes: fix

#19590 [visualization] Make LCM CONTACT_RESULTS from ApplyVisualizationConfig() respect publish_period
  visualization/visualization_config_functions.cc
Labels: release notes: fix

#19581 SpatialInertia::MakeFromCentralInertia() immediately checks physical validity
  multibody/tree/rotational_inertia.h
  multibody/tree/spatial_inertia.cc
  multibody/tree/test/spatial_inertia_test.cc
  multibody/tree/unit_inertia.h
  visualization/test/inertia_visualizer_test.cc
Labels: priority: medium, status: squashing now, release notes: fix

#19606 [visualization] Add missing unit test for publish period config
  visualization/test/visualization_config_functions_test.cc
Labels: release notes: none

#19595 [pydrake] Fix type inference for Value constructor
  bindings/pydrake/common/_value_extra.py
  bindings/pydrake/common/cpp_template.py
  bindings/pydrake/common/test/type_safe_index_pybind_test.cc
  bindings/pydrake/common/test/value_test.py
  bindings/pydrake/common/value_py.cc
  bindings/pydrake/systems/jupyter_widgets_examples.ipynb
  bindings/pydrake/systems/perception.py
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/lcm_test.py
  bindings/pydrake/systems/test/lifetime_test_notebook.ipynb
  bindings/pydrake/systems/test/primitives_test.py
  bindings/pydrake/systems/test/value_test.py
  bindings/pydrake/test/perception_test.py
  bindings/pydrake/visualization/_video.py
  examples/manipulation_station/end_effector_teleop_dualshock4.py
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
  tutorials/authoring_leaf_systems.ipynb
  tutorials/hydroelastic_contact_basics.ipynb
Labels: priority: medium, release notes: fix

#19559 Store FEM tangent matrix in block sparse matrix
  multibody/fem/BUILD.bazel
  multibody/fem/dirichlet_boundary_condition.cc
  multibody/fem/dirichlet_boundary_condition.h
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
  multibody/fem/fem_model_impl.h
  multibody/fem/test/dirichlet_boundary_condition_test.cc
  multibody/fem/test/fem_model_test.cc
Labels: release notes: none

#19553 [sensors] Add RgbdSensorAsync
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  systems/sensors/BUILD.bazel
  systems/sensors/rgbd_sensor.h
  systems/sensors/rgbd_sensor_async.cc
  systems/sensors/rgbd_sensor_async.h
  systems/sensors/test/rgbd_sensor_async_gl_test.cc
  systems/sensors/test/rgbd_sensor_async_gl_test.dmd.yaml
  systems/sensors/test/rgbd_sensor_async_test.cc
Labels: priority: medium, release notes: feature

#19613 [sensors] Hotfix for async test vs TSan
  systems/sensors/BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#19612 Adds SaveIrisRegionsYamlFile and LoadIrisRegionsYamlFile to pydrake
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/iris.h
Labels: status: single reviewer ok, release notes: feature

#19618 [wheel] Use 'docker cp' (not tar) to extract wheels
  tools/wheel/wheel_builder/linux.py
Labels: priority: high, release notes: none

#19622 [ad] Add Eigen trait specializations
  common/ad/BUILD.bazel
  common/ad/auto_diff.h
  common/ad/internal/eigen_specializations.h
  common/ad/test/auto_diff_basic_test.cc
  common/ad/test/matrix_test.cc
Labels: priority: low, release notes: none

#19626 [pydrake] Adjust deprecation test for pydrake >= 1.25
  bindings/pydrake/test/symbolic_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#19621 [ad] Opt-in to clang-format lint
  common/ad/BUILD.bazel
  common/ad/auto_diff.h
  common/ad/internal/partials.cc
  common/ad/internal/partials.h
  common/ad/internal/standard_operations.cc
  common/ad/test/partials_test.cc
  common/ad/test/standard_operations_add_test.cc
  common/ad/test/standard_operations_atan_test.cc
  common/ad/test/standard_operations_cmp_test.cc
  common/ad/test/standard_operations_pow_special_test.cc
  common/ad/test/standard_operations_sub_test.cc
  common/ad/test/standard_operations_test.h
Labels: priority: low, status: single reviewer ok, release notes: none

#19614 [tools] Always set forward_files to manual
  geometry/profiling/BUILD.bazel
  manipulation/models/realsense2_description/BUILD.bazel
  multibody/parsing/BUILD.bazel
  tools/workspace/forward_files.bzl
Labels: priority: medium, release notes: none

#19616 [examples] Remove optitrack_test
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/test/optitrack_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#19625 Add nlohmann as internal vendored library
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/test/merge_gltf_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/nlohmann_internal/BUILD.bazel
  tools/workspace/nlohmann_internal/package.BUILD.bazel
  tools/workspace/nlohmann_internal/patches/vendor.patch
  tools/workspace/nlohmann_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#19534 [doc] Add release notes v1.18.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.18.0.md
Labels: status: single reviewer ok, release notes: none

#19633 MathematicalProgram::AddConstraint parses QuadraticConstraint
  solvers/constraint.h
  solvers/create_constraint.cc
  solvers/mathematical_program.h
  solvers/test/create_constraint_test.cc
Labels: release notes: feature

#19640 [doc] Fix some release playbook typos
  doc/_pages/release_playbook.md
Labels: priority: low, status: single reviewer ok, release notes: none

#19638 [py autodiff] Handle empty derivatives in pydrake.forwarddiff.jacobian.
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/forwarddiff.py
  bindings/pydrake/test/forward_diff_test.py
Labels: release notes: fix

#19610 Improve spatial inertia shift efficiency.
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/tree/rotational_inertia.h
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/unit_inertia.h
Labels: priority: medium, status: squashing now, release notes: none

#19639 [py solvers] Add more MixedIntegerBranchAndBound::Options bindings
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py_branch_and_bound.cc
  bindings/pydrake/solvers/test/branch_and_bound_test.py
  solvers/BUILD.bazel
  solvers/branch_and_bound.h
Labels: priority: low, release notes: fix

#19630 push_release: get GPG fingerprint from public key
  tools/release_engineering/dev/push_release
Labels: status: single reviewer ok, release notes: none

#19596 SAP contact constraint reports multibody forces
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/contact_configuration.cc
  multibody/contact_solvers/contact_configuration.h
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_friction_cone_constraint.cc
  multibody/contact_solvers/sap/sap_friction_cone_constraint.h
  multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc
  multibody/contact_solvers/sap/test/sap_solver_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/contact_pair_kinematics.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/sap_driver.cc
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/sap_driver_test.cc
Labels: release notes: none

#19643 [tutorials] Remove hard linebreaks in Hydroelastic Contact
  tutorials/hydroelastic_contact_basics.ipynb
Labels: status: single reviewer ok, release notes: fix

#19548 [manipulation_station] Use applied spatial force in MbP
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/test/manipulation_station_test.cc
Labels: release notes: fix

#19645 [geometry] Clean up meshcat tests for maintainability
  geometry/test/meshcat_manual_test.cc
  geometry/test/meshcat_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#19634 [planning] ConvexSet::AddPointInSetConstraints returns the new variables
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/intersection.cc
  geometry/optimization/intersection.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/minkowski_sum.h
  geometry/optimization/point.cc
  geometry/optimization/point.h
  geometry/optimization/spectrahedron.cc
  geometry/optimization/spectrahedron.h
  geometry/optimization/test/cartesian_product_test.cc
  geometry/optimization/test/intersection_test.cc
  geometry/optimization/test/minkowski_sum_test.cc
  geometry/optimization/test/spectrahedron_test.cc
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/test_utilities.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: release notes: breaking change, release notes: feature

#19649 [sensors] Split RgbdSensorDiscrete into its own file
  bindings/pydrake/systems/sensors_py.cc
  systems/sensors/BUILD.bazel
  systems/sensors/rgbd_sensor.cc
  systems/sensors/rgbd_sensor.h
  systems/sensors/rgbd_sensor_discrete.cc
  systems/sensors/rgbd_sensor_discrete.h
  systems/sensors/test/rgbd_sensor_async_gl_test.cc
  systems/sensors/test/rgbd_sensor_discrete_test.cc
  systems/sensors/test/rgbd_sensor_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#19647 Allow zero matrix on the diagonal for block sparse matrix
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc
  multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#19591 [math] Add soft min and max function
  math/BUILD.bazel
  math/soft_min_max.cc
  math/soft_min_max.h
  math/test/soft_min_max_test.cc
  solvers/BUILD.bazel
  solvers/minimum_value_constraint.cc
Labels: status: squashing now, release notes: feature

#19620 Implements BezierCurve::ElevateOrder()
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/bezier_curve.cc
  common/trajectories/bezier_curve.h
  common/trajectories/test/bezier_curve_test.cc
Labels: release notes: feature

#19609 [C-IRIS] Compute s on the kinematics chain between each body.
  geometry/optimization/cspace_free_box.cc
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/cspace_free_polytope_base.cc
  geometry/optimization/cspace_free_polytope_base.h
  geometry/optimization/test/cspace_free_polytope_base_test.cc
Labels: release notes: fix

#19644 Add MakeDenseBottomRightCorner to block sparse matrix
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h
  multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
Labels: release notes: none

#19648 [trajectories] Fix BezierCurve move operators
  common/trajectories/bezier_curve.cc
  common/trajectories/bezier_curve.h
  common/trajectories/test/bezier_curve_test.cc
Labels: priority: low, release notes: fix

#19607 [multibody] Expand SapSolver results from reduced problem.
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/sap_contact_problem.h
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
Labels: component: multibody plant, release notes: none

#19623 [py autodiff] Bind constructor overload for unit derivatives vector
  bindings/pydrake/autodiffutils_py.cc
  bindings/pydrake/forwarddiff.py
  bindings/pydrake/test/autodiffutils_test.py
Labels: priority: low, release notes: fix

#19669 Adds more bindings for CacheEntry
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok, release notes: feature

#19670 Adds Serialize to Hyperellipsoid
  geometry/optimization/BUILD.bazel
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/test/hyperellipsoid_test.cc
Labels: release notes: feature

#19655 [bindings] Use vanilla py::cast() for keep alive behavior
  bindings/pydrake/common/eigen_pybind.h
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/pydrake_pybind.h
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/test/_pydrake_pybind_test_extra.py
  bindings/pydrake/test/pydrake_pybind_test.cc
Labels: release notes: fix

#19678 Compute number of nonzeros in a sparsity pattern
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h
  multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
Labels: priority: low, release notes: none

#19642 Add functionality to merge one glTF file into another
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_merge_gltf.cc
  geometry/render_gltf_client/internal_merge_gltf.h
  geometry/render_gltf_client/test/internal_merge_gltf_test.cc
  geometry/render_gltf_client/test/merge_gltf_test.cc
  geometry/render_gltf_client/test/red_box.gltf
  geometry/render_gltf_client/test/textured_green_box.gltf
Labels: release notes: none

#19663 [multibody] Select a subset of hydroelastic ContactResults
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/BUILD.bazel
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/test/contact_results_test.cc
Labels: release notes: feature

#19686 Fix memcheck failure in internal_merge_gltf_test.cc
  geometry/render_gltf_client/test/internal_merge_gltf_test.cc
Labels: status: single reviewer ok, release notes: none

#19673 Adds some text logging to IrisInConfigurationSpace
  geometry/optimization/iris.cc
Labels: release notes: none

#19688 SapLimitConstraint reports forces
  multibody/contact_solvers/sap/sap_limit_constraint.cc
  multibody/contact_solvers/sap/sap_limit_constraint.h
  multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc
Labels: component: multibody plant, release notes: none

#19681 [multibody] Fix bug in SapContactProblem::velocities_start()
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
Labels: component: multibody plant, release notes: none

#19672 VPolytope and IrisInConfigurationSpace support Mesh geometry.
  geometry/optimization/iris.cc
  geometry/optimization/test/iris_in_configuration_space_test.cc
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: release notes: feature

#19577 Implements System<T>::ExecuteInitializationEvents()
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  multibody/meshcat/BUILD.bazel
  multibody/meshcat/joint_sliders.cc
  multibody/meshcat/joint_sliders.h
  multibody/meshcat/test/joint_sliders_test.cc
  systems/framework/BUILD.bazel
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test_utilities/BUILD.bazel
  systems/framework/test_utilities/initialization_test_system.h
  visualization/BUILD.bazel
  visualization/meshcat_pose_sliders.cc
  visualization/test/meshcat_pose_sliders_test.cc
Labels: release notes: feature

#19631 Rewrite push_release logic for docker
  tools/release_engineering/dev/README.md
  tools/release_engineering/dev/push_release
  tools/release_engineering/dev/push_release.py
Labels: release notes: none

#19661 [doc] Add 1.18 release notes caveat for DockerHub
  doc/_release-notes/v1.18.0.md
Labels: priority: low, release notes: none

#19682 [tutorials] Fix broken link to differential inverse kinematics
  tutorials/quadratic_program.ipynb
Labels: status: single reviewer ok, release notes: none

#19687 [py visualization] Split flaky camera_test into its own file
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/test/model_visualizer_camera_test.py
  bindings/pydrake/visualization/test/model_visualizer_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#19675 Implements MultibodyPlant::MakeVelocityToQDotMap and MakeQDotToVelocityMap
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  geometry/geometry_state.h
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: release notes: feature

#19652 [doc] Update Hydroelastic Contact User Guide
  multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
  multibody/hydroelastics/images/HydroelasticTutorialCompliantRigidOutsideInside800x669.jpg
  multibody/hydroelastics/images/HydroelasticTutorialContactSurfaceCompliantCompliant.png
  multibody/hydroelastics/images/HydroelasticTutorialContactSurfaceRigidCompliantBubble.png
  multibody/hydroelastics/images/HydroelasticTutorialImage600x388.jpg
Labels: release notes: none

#19654 Refactor SuperNodalSolver to allow alternative implementation
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/conex_supernodal_solver.cc
  multibody/contact_solvers/conex_supernodal_solver.h
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/sap_solver.h
  multibody/contact_solvers/sap/test/sap_solver_test.cc
  multibody/contact_solvers/supernodal_solver.cc
  multibody/contact_solvers/supernodal_solver.h
  multibody/contact_solvers/test/supernodal_solver_test.cc
Labels: status: commits are properly curated, release notes: none

#19689 [panda_arm] Upstream acc. limits and collision filtering from Anzu
  manipulation/models/franka_description/BUILD.bazel
  manipulation/models/franka_description/README.md
  manipulation/models/franka_description/urdf/panda_arm.urdf
  manipulation/models/franka_description/urdf/panda_arm_hand.urdf
  manipulation/models/franka_description/urdf/test/franka_arm_test.cc
Labels: release notes: fix

#19522 Add support for num_positions != num_velocities in DifferentialIK
  bindings/pydrake/multibody/inverse_kinematics_py_differential.cc
  bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/differential_inverse_kinematics.cc
  multibody/inverse_kinematics/differential_inverse_kinematics.h
  multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc
  multibody/plant/multibody_plant.h
Labels: release notes: feature

#19690 push_release: fix bug, add more logging
  tools/release_engineering/dev/push_release.py
Labels: release notes: none

#19694 Add set_monitor() reference to Simulator::AdvanceTo() docs
  systems/analysis/simulator.h
Labels: priority: low, status: single reviewer ok, release notes: none

#19660 [tutorials] Make Hydroelastic Contact use images from User Guide
  tutorials/hydroelastic_contact_basics.ipynb
Labels: release notes: fix

#19692 [drake_visualizer] Warn on glTF meshes instead of crashing
  tools/workspace/drake_visualizer/repository.bzl
  tools/workspace/drake_visualizer/warn_gltf.patch
Labels: status: single reviewer ok, release notes: fix

#18983 [multibody] Add joint locking feature to SAP
  multibody/contact_solvers/sap/sap_constraint.cc
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/sap_contact_problem.h
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/slicing_and_indexing.cc
  multibody/plant/slicing_and_indexing.h
  multibody/plant/tamsi_driver.cc
  multibody/plant/test/deformable_driver_test.cc
  multibody/plant/test/joint_locking_test.cc
  multibody/plant/test/slicing_and_indexing_test.cc
Labels: type: feature request, component: multibody plant, release notes: feature

#19667 Add Reset functions for realtime rate calculation
  geometry/meshcat_visualizer.h
  geometry/test/meshcat_test.cc
  geometry/test/meshcat_visualizer_test.cc
  systems/analysis/instantaneous_realtime_rate_calculator.h
  systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc
Labels: status: squashing now, component: geometry illustration, release notes: fix

#19526 fix copy slicing in CSpaceSeparatingPlane
  geometry/optimization/c_iris_separating_plane.h
  geometry/optimization/cspace_separating_plane.cc
  geometry/optimization/cspace_separating_plane.h
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/cspace_free_path.cc
  geometry/optimization/dev/cspace_free_path.h
  geometry/optimization/dev/cspace_free_path_separating_plane.cc
  geometry/optimization/dev/cspace_free_path_separating_plane.h
  geometry/optimization/dev/test/c_iris_path_test_utilities.h
  geometry/optimization/dev/test/cspace_free_path_separating_plane_test.cc
  geometry/optimization/dev/test/cspace_free_path_test.cc
  geometry/optimization/test/c_iris_separating_plane_test.cc
Labels: release notes: newly deprecated, release notes: fix

#19668 [solvers] Add FindNonconvexQuadraticConstraint.
  solvers/aggregate_costs_constraints.cc
  solvers/aggregate_costs_constraints.h
  solvers/osqp_solver_common.cc
  solvers/test/aggregate_costs_constraints_test.cc
Labels: release notes: newly deprecated, release notes: fix

#19685 [bindings] Add env var DRAKE_PYTHON_LOGGING to disable redirect
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/text_logging_example.py
  bindings/pydrake/common/test/text_logging_gil_test.py
  bindings/pydrake/common/test/text_logging_test.py
  bindings/pydrake/common/test/text_logging_test_helpers_py.cc
  bindings/pydrake/common/text_logging_pybind.cc
  bindings/pydrake/pydrake_doxygen.h
  doc/doxygen_cxx/doxygen.h
Labels: release notes: feature

#19696 [sensors] Improve RgbdSensorDiscrete and RgbdSensorAsync
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  systems/sensors/rgbd_sensor.cc
  systems/sensors/rgbd_sensor.h
  systems/sensors/rgbd_sensor_async.cc
  systems/sensors/rgbd_sensor_async.h
  systems/sensors/rgbd_sensor_discrete.cc
  systems/sensors/rgbd_sensor_discrete.h
  systems/sensors/test/rgbd_sensor_async_test.cc
  systems/sensors/test/rgbd_sensor_discrete_test.cc
  systems/sensors/test/rgbd_sensor_test.cc
Labels: priority: medium, release notes: fix, release notes: feature

#19674 Avoid false self collisions in iiwa_primitive_collision.urdf
  manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14.xacro
  manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
Labels: release notes: fix

#19698 [multibody] Change ConstraintIndex into ConstraintId
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/BUILD.bazel
  multibody/plant/constraint_specs.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/sap_driver_ball_constraints_test.cc
  multibody/plant/test/sap_driver_distance_constraints_test.cc
  multibody/plant/test/sap_driver_joint_limits_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/multibody_tree_indexes.h
Labels: status: commits are properly curated, component: multibody plant, release notes: breaking change

#19706 Adds bindings for ExpressionCost and ExpressionConstraint
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: status: squashing now, status: single reviewer ok, release notes: feature

#19708 [primitives] Run clang-format on all non-test files
  systems/primitives/adder.cc
  systems/primitives/affine_system.cc
  systems/primitives/affine_system.h
  systems/primitives/barycentric_system.cc
  systems/primitives/barycentric_system.h
  systems/primitives/constant_value_source.h
  systems/primitives/constant_vector_source.cc
  systems/primitives/constant_vector_source.h
  systems/primitives/discrete_derivative.cc
  systems/primitives/discrete_derivative.h
  systems/primitives/discrete_time_delay.cc
  systems/primitives/discrete_time_delay.h
  systems/primitives/first_order_low_pass_filter.cc
  systems/primitives/first_order_low_pass_filter.h
  systems/primitives/gain.cc
  systems/primitives/gain.h
  systems/primitives/integrator.cc
  systems/primitives/integrator.h
  systems/primitives/linear_system.cc
  systems/primitives/matrix_gain.cc
  systems/primitives/multiplexer.h
  systems/primitives/pass_through.cc
  systems/primitives/pass_through.h
  systems/primitives/random_source.cc
  systems/primitives/shared_pointer_system.cc
  systems/primitives/shared_pointer_system.h
  systems/primitives/sine.cc
  systems/primitives/sine.h
  systems/primitives/symbolic_vector_system.cc
  systems/primitives/trajectory_affine_system.cc
  systems/primitives/trajectory_linear_system.cc
  systems/primitives/trajectory_source.cc
  systems/primitives/trajectory_source.h
  systems/primitives/vector_log.cc
  systems/primitives/vector_log_sink.cc
  systems/primitives/vector_log_sink.h
  systems/primitives/wrap_to_system.cc
  systems/primitives/zero_order_hold.cc
  systems/primitives/zero_order_hold.h
Labels: priority: medium, status: single reviewer ok, release notes: none
