Repository RobotLocomotion/drake, pull requests merged in 2023-05, with the labels that each got.

#19317 [setup] Revert removal of macOS maintainer only flag
  setup/mac/install_prereqs.sh
Labels: priority: high, status: single reviewer ok, release notes: none

#19238 [parsing] Improve URDF inertia invalidity handling
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: release notes: fix

#19303 [common] Add benchmark for Gemm on Expression
  common/benchmarking/BUILD.bazel
  common/benchmarking/benchmark_polynomial.cc
Labels: priority: medium, release notes: none

#19298 [pydrake] Add math.matmul
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/math_py.cc
  bindings/pydrake/test/math_overloads_matrix_test.py
  common/eigen_types.h
Labels: priority: medium, release notes: feature

#19313 Tidy up ConvexSet implementation conventions
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/intersection.cc
  geometry/optimization/intersection.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/minkowski_sum.h
  geometry/optimization/point.cc
  geometry/optimization/point.h
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: priority: high, status: single reviewer ok, release notes: none

#19292 Relocate DiagnosticPolicyTestBase to common/test_utilities
  common/test_utilities/BUILD.bazel
  common/test_utilities/diagnostic_policy_test_base.h
  multibody/parsing/BUILD.bazel
  multibody/parsing/test/detail_collision_filter_group_resolver_test.cc
  multibody/parsing/test/detail_mesh_parser_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/parsing/test/detail_sdf_diagnostic_test.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_select_parser_test.cc
  multibody/parsing/test/detail_tinyxml2_diagnostic_test.cc
  multibody/parsing/test/detail_tinyxml_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: status: single reviewer ok, release notes: none

#19324 Update optitrack driver version
  tools/workspace/optitrack_driver/repository.bzl
Labels: status: single reviewer ok, release notes: feature

#19315 Touch up MathematicalProgram docs for linear constraints.
  solvers/mathematical_program.h
Labels: priority: low, status: squashing now, release notes: none

#19326 [doc] Switch some links to use relative (host-agnostic) paths
  doc/_config.yml
  doc/_pages/python_bindings.md
  doc/doxygen_cxx/header.html.patch
  doc/index.md
  doc/pydrake/layout.html
Labels: status: single reviewer ok, release notes: none

#19225 [multibody] Refresh cache entry hack upon update
  examples/manipulation_station/test/manipulation_station_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/tamsi_driver.cc
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/compliant_contact_manager_tester.h
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/sap_driver_joint_limits_test.cc
Labels: release notes: fix

#19302 Add CheckConvexHullProperty to bezier curve
  common/trajectories/BUILD.bazel
  common/trajectories/test/bezier_curve_test.cc
Labels: release notes: none

#19329 Add guidance for release notes when bumping externals
  doc/_pages/reviewable.md
Labels: priority: low, status: single reviewer ok, release notes: none

#19301 [planning] Adds a time cost to GcsTrajectoryOptimization
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: feature

#19332 Upgrade Externals May 2023
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/buildifier/repository.bzl
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/lcm/lcm-config-version.cmake
  tools/workspace/lcm/lcm-config.cmake
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/lcm/repository.bzl
  tools/workspace/petsc/repository.bzl
  tools/workspace/rules_python/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#19316 Adds Spectrahedron isa ConvexSet
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/spectrahedron.cc
  geometry/optimization/spectrahedron.h
  geometry/optimization/test/spectrahedron_test.cc
Labels: priority: medium, release notes: feature

#19331 [geometry/optimization] Opt-in to clang-format lint
  geometry/optimization/BUILD.bazel
  geometry/optimization/cspace_free_polytope.h
  geometry/optimization/test/convex_set_solving_test.cc
  geometry/optimization/vpolytope.cc
Labels: priority: low, release notes: none

#19339 [hotfix] Fix lint in geometry/optimization
  geometry/optimization/test/spectrahedron_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#19336 Move ConvexSet cloning to vtable instead of std::function
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/intersection.cc
  geometry/optimization/intersection.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/minkowski_sum.h
  geometry/optimization/point.cc
  geometry/optimization/point.h
  geometry/optimization/spectrahedron.cc
  geometry/optimization/spectrahedron.h
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: priority: medium, release notes: none

#19334 [planning] Add velocity bounds to subgraphs
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: feature

#19304 [symbolic] Speed up matmul
  common/symbolic/expression/expression.cc
  common/symbolic/expression/expression.h
  common/symbolic/expression/test/expression_matrix_test.cc
Labels: priority: high, release notes: fix

#19343 [pydrake] Remove CopyableUniquePtrConvexSet binding
  bindings/pydrake/geometry/BUILD.bazel
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/optimization_pybind.h
  bindings/pydrake/geometry/test/optimization_test.py
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
Labels: priority: low, status: single reviewer ok, release notes: breaking change

#19350 [workspace] Do not warn against macOS Ventura
  tools/workspace/os.bzl
Labels: status: single reviewer ok, release notes: none

#19354 Avoid 'using std::move'
  common/symbolic/expression/environment.cc
  common/symbolic/expression/test/variable_test.cc
  common/symbolic/expression/variable.cc
  common/symbolic/expression/variables.cc
  common/test/copyable_unique_ptr_test.cc
  common/test/drake_bool_test.cc
  common/test/type_safe_index_test.cc
  common/test_utilities/test/is_memcpy_movable_test.cc
  geometry/drake_visualizer.cc
  geometry/geometry_state.cc
  geometry/internal_geometry.cc
  geometry/proximity/deformable_contact_geometries.cc
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/polygon_surface_mesh.cc
  geometry/proximity/test/contact_surface_test.cc
  geometry/proximity/test/contact_surface_utility_test.cc
  geometry/proximity/test/deformable_contact_geometries_test.cc
  geometry/proximity/test/mesh_half_space_intersection_test.cc
  geometry/proximity_engine.cc
  geometry/query_results/contact_surface.cc
  geometry/query_results/deformable_contact.cc
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/test/collision_filter_manager_test.cc
  geometry/test/drake_visualizer_test.cc
  geometry/test/geometry_frame_test.cc
  geometry/test/geometry_instance_test.cc
  geometry/test/geometry_state_test.cc
  geometry/test/proximity_engine_test.cc
  multibody/fem/petsc_symmetric_block_sparse_matrix.cc
  multibody/fem/simplex_gaussian_quadrature.cc
  multibody/parsing/detail_sdf_geometry.cc
  multibody/plant/test/contact_properties_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/deformable_boundary_condition_test.cc
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/deformable_driver_contact_test.cc
  multibody/plant/test/deformable_driver_test.cc
  multibody/plant/test/deformable_integration_test.cc
  multibody/tree/test/body_node_test.cc
  planning/collision_checker.cc
  planning/test/collision_avoidance_test.cc
  planning/test/collision_checker_test.cc
  solvers/test/mathematical_program_test.cc
  systems/rendering/test/multibody_position_to_geometry_pose_test.cc
  systems/sensors/rgbd_sensor.cc
  systems/sensors/test/rgbd_sensor_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#19356 Avoid ADL std::move
  common/symbolic/generic_polynomial.cc
  common/symbolic/polynomial.cc
  geometry/proximity/test/contact_surface_test.cc
  geometry/proximity/test/contact_surface_utility_test.cc
  geometry/proximity/test/mesh_field_linear_test.cc
  geometry/proximity/test/mesh_half_space_intersection_test.cc
  geometry/proximity/test/mesh_intersection_test.cc
  geometry/proximity/test/mesh_plane_intersection_test.cc
  geometry/proximity/test/polygon_surface_mesh_test.cc
  geometry/proximity/test/triangle_surface_mesh_test.cc
  geometry/query_results/contact_surface.h
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/test/scene_graph_test.cc
  multibody/plant/test/contact_properties_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/deformable_boundary_condition_test.cc
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/deformable_integration_test.cc
  multibody/plant/test/deformable_model_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/test/body_node_test.cc
  systems/rendering/multibody_position_to_geometry_pose.cc
  systems/rendering/test/multibody_position_to_geometry_pose_test.cc
  systems/sensors/test/rgbd_sensor_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#19358 Remove dead code
  geometry/proximity/mesh_plane_intersection.cc
  multibody/inverse_kinematics/constraint_relaxing_ik.cc
  multibody/plant/multibody_plant.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#19352 Add RenderMaterial to geometry/render
  geometry/render/BUILD.bazel
  geometry/render/render_material.cc
  geometry/render/render_material.h
  geometry/render/test/render_material_test.cc
Labels: release notes: none

#19359 Fix fmt for fs::path
  geometry/render/render_material.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#19353 Generalize render_gl/MeshData into render/RenderMesh
  geometry/render/BUILD.bazel
  geometry/render/render_mesh.cc
  geometry/render/render_mesh.h
  geometry/render/test/render_mesh_test.cc
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/internal_shape_meshes.cc
  geometry/render_gl/internal_shape_meshes.h
  geometry/render_gl/test/internal_shape_meshes_test.cc
Labels: priority: high, release notes: none

#19360 Remove dead code
  common/symbolic/expression/test/substitution_test.cc
Labels: status: single reviewer ok, release notes: none

#19361 [symbolic] Work around TSan bug
  common/symbolic/expression/BUILD.bazel
  common/symbolic/expression/expression.cc
  common/symbolic/expression/test/mixing_scalar_types_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#19363 [abseil] Fix TSan linking errors
  common/symbolic/expression/BUILD.bazel
  common/symbolic/expression/expression.cc
  common/symbolic/expression/test/mixing_scalar_types_test.cc
  tools/workspace/abseil_cpp_internal/patches/hidden_visibility.patch
Labels: release notes: none

#19374 [common] Add tolerance for schema/transform_test
  common/schema/test/transform_test.cc
Labels: status: single reviewer ok, release notes: none

#19378 [solvers] Add tolerance for clp_solver_test
  solvers/test/clp_solver_test.cc
Labels: release notes: none

#19373 [math] Add tolerance to linear_solve_test Eigen compare
  math/test/linear_solve_test.cc
Labels: release notes: none

#19377 [solvers] Increase tolerance for constraint_test
  solvers/test/constraint_test.cc
Labels: release notes: none

#19375 [systems] Add tolerance to primitives/symbolic_vector_system_test
  systems/primitives/test/symbolic_vector_system_test.cc
Labels: status: single reviewer ok, release notes: none

#19382 Improve monthly updates documentation
  tools/workspace/README.md
Labels: status: single reviewer ok, release notes: none

#19364 Add RenderMaterial to RenderMesh
  geometry/render/BUILD.bazel
  geometry/render/render_material.cc
  geometry/render/render_material.h
  geometry/render/render_mesh.cc
  geometry/render/render_mesh.h
  geometry/render/test/render_mesh_test.cc
  geometry/render_gl/internal_render_engine_gl.cc
  tools/workspace/tinyobjloader/default_texture_color.patch
  tools/workspace/tinyobjloader/repository.bzl
Labels: release notes: none

#19312 Make GCS Preprocessing respect solver options
  geometry/optimization/BUILD.bazel
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: priority: medium, status: squashing now, release notes: fix

#19371 [geometry] Increase tolerance for proximity/obb_test
  geometry/proximity/test/obb_test.cc
Labels: status: squashing now, release notes: none

#19349 Filter contact results for completely locked trees
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/tamsi_driver.cc
  multibody/plant/test/joint_locking_test.cc
Labels: component: multibody plant, release notes: breaking change

#19390 [systems/lcm] Improve error messages
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/systems/test/lcm_test.py
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/lcm_publisher_system.h
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/lcm_subscriber_system.h
Labels: priority: low, status: single reviewer ok, release notes: none

#19344 Added updated models of the IIWA 14 with estimated rotor inertia and gear ratio
  bindings/pydrake/visualization/test/video_test.py
  manipulation/models/iiwa_description/README.md
  manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
  manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf
  manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc
  manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14.xacro
  manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf
  manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf
  manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf
  multibody/plant/test/joint_limits_test.cc
  multibody/plant/test/multibody_plant_reflected_inertia_test.cc
Labels: release notes: fix

#19369 [systems/lcm] Use shared_ptr for LCM serializers
  bindings/pydrake/systems/_lcm_extra.py
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/systems/lcm_pybind.h
  bindings/pydrake/systems/test/lcm_test.py
  systems/lcm/BUILD.bazel
  systems/lcm/lcm_publisher_system.cc
  systems/lcm/lcm_publisher_system.h
  systems/lcm/lcm_subscriber_system.cc
  systems/lcm/lcm_subscriber_system.h
  systems/lcm/serializer.h
  systems/lcm/test/serializer_deprecated_test.cc
  systems/lcm/test/serializer_test.cc
Labels: priority: low, release notes: newly deprecated, release notes: fix

#19383 Update RenderEngineVtk to use RenderMaterial
  geometry/render/BUILD.bazel
  geometry/render/render_material.cc
  geometry/render_gltf_client/test/test_color_scene.gltf
  geometry/render_gltf_client/test/test_depth_scene.gltf
  geometry/render_gltf_client/test/test_label_scene.gltf
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/internal_render_engine_vtk_base.cc
  geometry/render_vtk/internal_render_engine_vtk_base.h
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
Labels: release notes: breaking change

#19368 Refactor CspaceFreePolytope
  geometry/optimization/BUILD.bazel
  geometry/optimization/c_iris_separating_plane.h
  geometry/optimization/cspace_free_internal.cc
  geometry/optimization/cspace_free_internal.h
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/cspace_free_polytope.h
  geometry/optimization/cspace_free_structs.h
  geometry/optimization/cspace_separating_plane.cc
  geometry/optimization/cspace_separating_plane.h
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/test/cspace_free_internal_test.cc
  geometry/optimization/test/cspace_free_polytope_test.cc
Labels: status: squashing now, release notes: newly deprecated

#19366 [solvers] Add max_nodes_in_tree for branch_and_bound.
  bindings/pydrake/solvers/solvers_py_branch_and_bound.cc
  bindings/pydrake/solvers/test/branch_and_bound_test.py
  solvers/branch_and_bound.cc
  solvers/branch_and_bound.h
  solvers/test/branch_and_bound_test.cc
Labels: release notes: feature

#19393 Improve math::AreAutoDiffVecXdEqual
  math/autodiff_gradient.cc
  math/test/autodiff_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#19245 [parsing] Improve SDFormat inertia handling
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_sdf_diagnostic.cc
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_common_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/tree/rotational_inertia.h
  multibody/tree/spatial_inertia.h
  multibody/tree/unit_inertia.h
Labels: release notes: fix

#19399 [geometry] Bump tolerance for mesh_plane_intersection_test
  geometry/proximity/test/mesh_plane_intersection_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#19398 RenderEngine no longer ignores sensor pose in camera body
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/test/geometry_state_test.cc
Labels: release notes: fix

#19090 Model directives fail to load deep nested weld tests
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/test/process_model_directives_test.cc
  multibody/parsing/test/process_model_directives_test/deep_child_frame_weld.dmd.yaml
  multibody/parsing/test/process_model_directives_test/deep_child_weld.dmd.yaml
  multibody/parsing/test/process_model_directives_test/model_with_directly_nested_models.sdf
Labels: status: squashing now, release notes: fix

#19376 [solvers] Start nonlinear_program_test closer to solution
  solvers/test/nonlinear_program_test.cc
Labels: status: single reviewer ok, release notes: none

#19403 [py solvers] Fix branch and bound test vs solution ordering
  bindings/pydrake/solvers/test/branch_and_bound_test.py
Labels: priority: low, release notes: none

#19401 [multibody] Bump tolerance for compliant_contact_manager_test
  multibody/plant/test/compliant_contact_manager_test.cc
Labels: priority: low, release notes: none

#19400 [multibody] Bump tolerance for free_body_test
  multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc
Labels: priority: low, release notes: none

#19410 [optimization] Defend test against kcov bug
  systems/optimization/test/system_constraint_adapter_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#19387 [planning] Improve performance of SceneGraphCollisionChecker through better collision filtering
  bindings/pydrake/planning/planning_py_collision_checker.cc
  bindings/pydrake/planning/test/collision_checker_test.py
  planning/collision_checker.cc
  planning/collision_checker.h
  planning/scene_graph_collision_checker.cc
  planning/scene_graph_collision_checker.h
  planning/test/collision_checker_test.cc
  planning/test/scene_graph_collision_checker_test.cc
  planning/unimplemented_collision_checker.cc
  planning/unimplemented_collision_checker.h
Labels: status: squashing now, release notes: fix

#19406 Improve error message for xyz mobilizers in singularity.
  multibody/tree/BUILD.bazel
  multibody/tree/space_xyz_floating_mobilizer.cc
  multibody/tree/space_xyz_mobilizer.cc
  multibody/tree/test/space_xyz_floating_mobilizer_test.cc
  multibody/tree/test/space_xyz_mobilizer_test.cc
Labels: priority: medium, release notes: none

#19397 [geometry] Map white color to kDontCare in render_gltf_client
  geometry/render/render_engine.h
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render_gltf_client/render_gltf_client_doxygen.h
  geometry/render_gltf_client/test/integration_test.py
  geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc
  geometry/render_gltf_client/test/internal_sample_image_data.cc
  geometry/render_gltf_client/test/internal_sample_image_data.h
  geometry/render_gltf_client/test/server_vtk_backend.cc
  geometry/render_gltf_client/test/test_colored_label_rgba_8U.png
Labels: release notes: fix

#19407 [multibody] Improve error message for !(Delta > 0)
  multibody/plant/tamsi_solver.cc
  multibody/plant/tamsi_solver.h
  multibody/plant/test/tamsi_solver_test.cc
Labels: priority: medium, release notes: fix

#19405 Implements ExpressionCost
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  solvers/BUILD.bazel
  solvers/cost.cc
  solvers/cost.h
  solvers/create_cost.cc
  solvers/mathematical_program.h
  solvers/test/cost_test.cc
  solvers/test/mathematical_program_test.cc
Labels: priority: medium, release notes: feature

#19187 [workspace] Upgrade stable_baselines3_internal to latest release v1.8.0
  tools/workspace/stable_baselines3_internal/connection.patch
  tools/workspace/stable_baselines3_internal/no_torch.patch
  tools/workspace/stable_baselines3_internal/repository.bzl
Labels: priority: low, status: squashing now, status: single reviewer ok, release notes: fix

#19418 [geometry] Add benchmark experiment wrappers for reproducible reports
  geometry/benchmarking/BUILD.bazel
  geometry/benchmarking/README.md
  geometry/benchmarking/render_benchmark_doxygen.h
  tools/performance/README.md
Labels: priority: medium, release notes: none

#19412 [doc] Fix C++ API footer size and scrolling
  doc/doxygen_cxx/doxygen_extra.css
  doc/doxygen_cxx/footer.html
Labels: release notes: none

#19158 [visualization] Add render camera preview
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/_model_visualizer.py
  bindings/pydrake/visualization/_rgbd_camera_sliders.dmd.yaml
  bindings/pydrake/visualization/_rgbd_camera_sliders.sdf
  bindings/pydrake/visualization/model_visualizer.py
  bindings/pydrake/visualization/test/model_visualizer_test.py
  tools/install/bazel/drake.BUILD.bazel
  tools/install/bazel/drake__bindings__pydrake.BUILD.bazel
Labels: priority: medium, release notes: feature

#19413 [multibody] Remove the deprecated Parser::AddModelFromString
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/test/parser_test.cc
Labels: status: single reviewer ok, release notes: removal of deprecated

#19402 Introduce new SapConstraint APIs implemented in terms of older APIs.
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_constraint.cc
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_constraint_bundle.cc
  multibody/contact_solvers/sap/sap_constraint_bundle.h
  multibody/contact_solvers/sap/sap_friction_cone_constraint.h
  multibody/contact_solvers/sap/sap_holonomic_constraint.cc
  multibody/contact_solvers/sap/sap_holonomic_constraint.h
  multibody/contact_solvers/sap/sap_limit_constraint.cc
  multibody/contact_solvers/sap/sap_limit_constraint.h
  multibody/contact_solvers/sap/sap_model.cc
  multibody/contact_solvers/sap/sap_model.h
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc
  multibody/contact_solvers/sap/test/sap_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
  multibody/contact_solvers/sap/test/sap_model_test.cc
  multibody/contact_solvers/sap/test/sap_solver_test.cc
Labels: release notes: none

#19427 [setup] Remove NLopt dependency from Ubuntu
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
Labels: priority: low, status: single reviewer ok, release notes: fix

#19391 [doc] Add release notes v1.16.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.16.0.md
Labels: status: squashing now, status: single reviewer ok, release notes: none

#19425 [render_vtk] Nerf a few test cases on macOS
  geometry/render_vtk/BUILD.bazel
Labels: priority: low, release notes: none

#19431 [doc] Improve 1.16 release notes
  doc/_release-notes/v1.16.0.md
Labels: priority: high, release notes: none

#19432 [doc] Refresh tutorials release playbook from experience with v1.16.0
  doc/_pages/release_playbook.md
Labels: status: single reviewer ok, release notes: none

#19420 [multibody] Including joint locking in forward dynamics computations
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/tree/body.h
  multibody/tree/body_node.h
  multibody/tree/joint.h
  multibody/tree/mobilizer.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree_system.cc
Labels: type: feature request, component: multibody plant, release notes: feature

#19357 [planning] Add velocity bounds to edges between subgraphs
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: feature

#19423 [solvers] Increase tolerance for create_constraint_test
  solvers/test/create_constraint_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#19448 Improve error message for GetGeometryIdByName.
  geometry/geometry_state.cc
  geometry/test/geometry_state_test.cc
Labels: status: squashing now, release notes: none

#19300 Check IsStabilizable and IsDetectable in ContinuousAlgebraicRiccatiEquation
  math/BUILD.bazel
  math/continuous_algebraic_riccati_equation.cc
  math/test/continuous_algebraic_riccati_equation_test.cc
  systems/controllers/zmp_planner.h
Labels: release notes: fix

#19451 Fix build errors vs fmt 10
  geometry/proximity/test/characterization_utilities.h
  geometry/render_gltf_client/internal_http_service_curl.cc
Labels: priority: high, status: single reviewer ok, release notes: fix

#19445 [pydrake] Add binding for LinearComplementarityConstraint M and q.
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: status: single reviewer ok, release notes: feature

#19323 [render_gl] Support multithreaded operation (sometimes)
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_opengl_context.cc
  geometry/render_gl/test/thread_test.cc
Labels: priority: medium, release notes: fix

#19422 Overload Trajectory::vector_values to accept Eigen::VectorXd
  bindings/pydrake/trajectories_py.cc
  common/trajectories/test/piecewise_polynomial_test.cc
  common/trajectories/trajectory.cc
  common/trajectories/trajectory.h
Labels: status: single reviewer ok, release notes: fix

#19439 [tutorials] Taking derivatives of MultibodyPlant with respect to mass
  tutorials/index.ipynb
Labels: status: single reviewer ok, release notes: feature

#19443 [sensors] Simplify the creation of empty images
  systems/sensors/image.h
  systems/sensors/test/image_test.cc
Labels: priority: low, release notes: fix

#19455 Fix default arguments for GetStateNames() and friends to match C++.
  bindings/pydrake/multibody/plant_py.cc
Labels: status: single reviewer ok, release notes: breaking change, release notes: fix

#19454 [common] Provide fmt helper for consistent floating point output
  common/fmt.h
  common/test/fmt_test.cc
  common/test/text_logging_test.cc
  common/yaml/yaml_write_archive.h
  solvers/sdpa_free_format.cc
Labels: priority: high, release notes: fix

#19436 [sensors] Add depth image conversion helpers
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/test/sensors_test.py
  geometry/render_gltf_client/internal_render_client.cc
  systems/sensors/image.cc
  systems/sensors/image.h
  systems/sensors/image_writer.h
  systems/sensors/rgbd_sensor.cc
  systems/sensors/rgbd_sensor.h
  systems/sensors/test/image_test.cc
  systems/sensors/test/rgbd_sensor_test.cc
Labels: priority: medium, release notes: feature

#19458 [doc] Offically support macOS Ventura
  doc/_pages/from_source.md
  doc/_pages/installation.md
Labels: type: documentation, status: single reviewer ok, release notes: feature

#19460 [pydrake] Bind MobyLCP solver.
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py.cc
  bindings/pydrake/solvers/solvers_py.h
  bindings/pydrake/solvers/solvers_py_mobylcp.cc
  bindings/pydrake/solvers/test/mobylcp_solver_test.py
Labels: status: single reviewer ok, release notes: feature

#19459 Fix build errors vs fmt 10
  solvers/mosek_solver_internal.cc
Labels: priority: high, status: single reviewer ok, release notes: fix

#19469 Rename fields in HPolyhedron::Serialize to match convention
  geometry/optimization/convex_set.h
  geometry/optimization/hpolyhedron.h
Labels: status: single reviewer ok, release notes: breaking change

#19456 [doc] Add release notes v1.17.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.17.0.md
Labels: priority: high, status: do not merge, status: squashing now, status: single reviewer ok, release notes: none

#19457 Add binary operator overloads for Polynomial bop Expression
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic/polynomial.cc
  common/symbolic/polynomial.h
  common/symbolic/test/polynomial_test.cc
Labels: release notes: feature

#19395 Restructure cspace_free_path
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/cspace_free_path.cc
  geometry/optimization/dev/cspace_free_path.h
  geometry/optimization/dev/cspace_free_path_separating_plane.cc
  geometry/optimization/dev/cspace_free_path_separating_plane.h
  geometry/optimization/dev/test/c_iris_path_test_utilities.h
  geometry/optimization/dev/test/cspace_free_path_separating_plane_test.cc
  geometry/optimization/dev/test/cspace_free_path_test.cc
  geometry/optimization/dev/test/cspace_free_path_with_mosek_test.cc
Labels: status: single reviewer ok, release notes: none

#19461 [examples] Use modern Meshcat visualization in spatula_slip_control
  examples/hydroelastic/spatula_slip_control/BUILD.bazel
  examples/hydroelastic/spatula_slip_control/README.md
  examples/hydroelastic/spatula_slip_control/images/spatula3.jpg
  examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc
Labels: release notes: feature

#18966 Fix warning when ball joint has an axis
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: status: squashing now, release notes: fix

#19452 Implement SapLimitConstraint in terms of new APIs introduced in #19402
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_limit_constraint.cc
  multibody/contact_solvers/sap/sap_limit_constraint.h
  multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc
Labels: release notes: none

#19475 Rename timestep => time_step in systems/primitives
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/discrete_time_delay.cc
  systems/primitives/discrete_time_delay.h
  systems/primitives/test/discrete_derivative_test.cc
  systems/primitives/test/discrete_time_delay_test.cc
Labels: status: single reviewer ok, release notes: newly deprecated

#19476 Rename timestep => time_step in systems/controllers
  bindings/pydrake/systems/test/controllers_test.py
  systems/controllers/dynamic_programming.cc
  systems/controllers/dynamic_programming.h
  systems/controllers/test/dynamic_programming_test.cc
Labels: status: single reviewer ok, release notes: none

#19477 Rename timestep => time_step in pyplot_visualizer
  bindings/pydrake/systems/_resample_interp1d.py
  bindings/pydrake/systems/pyplot_visualizer.py
  bindings/pydrake/systems/test/_resample_log_interp1d_test.py
Labels: status: single reviewer ok, release notes: none

#19478 Rename timestep => time_step in remaining uses/comments throughout
  bindings/pydrake/multibody/test/plant_test.py
  examples/hardware_sim/hardware_sim.py
  examples/hardware_sim/scenario.h
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/test/manipulation_station_test.cc
  examples/mass_spring_cloth/README.md
  examples/mass_spring_cloth/cloth_spring_model.h
  geometry/drake_visualizer_params.h
  geometry/meshcat_visualizer_params.h
  manipulation/util/robot_plan_utils.cc
  multibody/constraint/test/constraint_solver_test.cc
  multibody/fem/discrete_time_integrator.cc
  multibody/fem/newmark_scheme.h
  multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h
  multibody/meshcat/contact_visualizer_params.h
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/joint_locking_test.cc
  multibody/plant/test/propeller_test.cc
  multibody/plant/test_utilities/rigid_body_on_compliant_ground.h
  systems/analysis/test/simulator_test.cc
  systems/analysis/velocity_implicit_euler_integrator.h
  tutorials/dynamical_systems.ipynb
  visualization/visualization_config.h
Labels: status: single reviewer ok, release notes: none

#19481 Improve error message for integrator smaller step size
  systems/analysis/integrator_base.h
Labels: status: single reviewer ok, release notes: none

#19487 Fix some xml file typos
  examples/kuka_iiwa_arm/models/objects/simple_cuboid.urdf
  examples/quadrotor/office.urdf
  multibody/parsing/test/sdf_parser_test/table_in_world.sdf
  multibody/parsing/test/urdf_parser_test/collision_filter_group_parsing_test.urdf
  multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
Labels: status: single reviewer ok, release notes: none, release notes: fix

#19468 Fix caching for autodiff in direct collocation
  planning/trajectory_optimization/direct_collocation.cc
  planning/trajectory_optimization/direct_collocation.h
  planning/trajectory_optimization/test/direct_collocation_test.cc
Labels: release notes: fix

#19486 [doc] Improve source install instructions
  doc/_pages/from_source.md
  doc/_pages/mac.md
  doc/_pages/ubuntu.md
Labels: priority: low, release notes: none

#19462 Introduce SapConstraintJacobian
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_constraint.cc
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_constraint_jacobian.cc
  multibody/contact_solvers/sap/sap_constraint_jacobian.h
  multibody/contact_solvers/sap/sap_friction_cone_constraint.cc
  multibody/contact_solvers/sap/sap_friction_cone_constraint.h
  multibody/contact_solvers/sap/sap_holonomic_constraint.cc
  multibody/contact_solvers/sap/sap_holonomic_constraint.h
  multibody/contact_solvers/sap/sap_limit_constraint.cc
  multibody/contact_solvers/sap/sap_limit_constraint.h
  multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc
  multibody/contact_solvers/sap/test/sap_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
  multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_model_test.cc
  multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc
  multibody/contact_solvers/sap/test/sap_solver_test.cc
  multibody/plant/sap_driver.cc
  multibody/plant/test/sap_driver_test.cc
Labels: release notes: none

#19411 Fix document of ComputeContactSurfaces() that compliant Mesh is supported
  geometry/query_object.h
Labels: status: single reviewer ok, release notes: none

#19495 SapFrictionConeConstraint: Move constraint data into abstract value
  multibody/contact_solvers/sap/sap_friction_cone_constraint.cc
Labels: status: single reviewer ok, release notes: none

#19497 Use preferred signed-distance query in StaticFrictionConeConstraint
  multibody/optimization/static_friction_cone_constraint.cc
Labels: release notes: none

#19502 Upgrade to Bazel 6.2.0
  .bazeliskrc
  doc/_pages/from_source.md
  setup/ubuntu/source_distribution/install_prereqs.sh
  tools/wheel/image/provision-base.sh
  tools/workspace/drake_visualizer/image/provision.sh
Labels: status: single reviewer ok, release notes: fix

#19499 [osqp_solver] Allow for primal-only warm-start
  planning/trajectory_optimization/BUILD.bazel
  planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
  solvers/osqp_solver.cc
  solvers/test/osqp_solver_test.cc
Labels: release notes: none

#19496 [releng] Don't sign individual files
  tools/release_engineering/dev/push_release
Labels: release notes: none
