Repository RobotLocomotion/drake, pull requests merged in 2023-01, with the labels that each got.

#18500 [C-IRIS] allow the user to set the constant multiplier for poytope Chebyshev center.
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/collision_geometry_test.cc
Labels: release notes: none

#18506 [C-IRIS] fix Lagrangian for s_lower <= s <= s_upper.
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18503 [solvers] Add test with ipopt for problem costs/constraints containing duplicated variables.
  solvers/test/ipopt_solver_test.cc
  solvers/test/nonlinear_program_test.cc
Labels: status: single reviewer ok, release notes: none

#18502 Add LorentzCone constraint using non-symbolic form in HPolyhedron.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/hpolyhedron.cc
Labels: release notes: none

#18509 [workspace] Remove deprecated externals 2023-01
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  tools/workspace/default.bzl
  tools/workspace/ghc_filesystem/BUILD.bazel
  tools/workspace/ghc_filesystem/package.BUILD.bazel
  tools/workspace/ghc_filesystem/repository.bzl
  tools/workspace/tinyxml2/BUILD.bazel
  tools/workspace/tinyxml2/repository.bzl
Labels: status: single reviewer ok, release notes: removal of deprecated

#18515 [multibody] Require finalize before state counts are available
  multibody/plant/multibody_plant.h
  multibody/tree/multibody_tree.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#18521 [planning] BodyShapeDescription fails fast upon mis-use
  planning/body_shape_description.h
  planning/test/body_shape_description_test.cc
Labels: release notes: none

#18519 [planning] Fix typo in BUILD file
  planning/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#18522 [multibody] Repair some physical dependency defects in MbT
  multibody/tree/BUILD.bazel
  multibody/tree/joint.h
  multibody/tree/multibody_element.cc
  multibody/tree/multibody_element.h
Labels: status: single reviewer ok, release notes: newly deprecated

#18518 [pydrake] Fixup alpha-import order
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok, release notes: none

#18524 [workspace] Upgrade rules_python to latest release 0.16.1
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/rules_python/repository.bzl
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#18501 Add unit test for input_port.FixValue() cache invalidation
  systems/framework/test/input_port_test.cc
Labels: type: cleanup, priority: low, status: single reviewer ok, release notes: none

#18517 Request WIP PRs on failed external upgrades
  tools/workspace/README.md
Labels: release notes: none

#18527 Increase mypy timeout for glacial CI machines
  tools/workspace/mypy_internal/patches/timeout.patch
  tools/workspace/mypy_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#18528 [doc] Enable Doxygen builds on Ubuntu 22.04
  tools/workspace/doxygen/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: none

#18523 [doc] Remove "newly bound" itemization
  doc/_pages/release_playbook.md
  doc/_pages/reviewable.md
  doc/_release-notes/template.txt
Labels: release notes: none

#18532 [workspace] Remove deprecated @json and @nlopt externals
  tools/workspace/default.bzl
  tools/workspace/json/BUILD.bazel
  tools/workspace/json/package.BUILD.bazel
  tools/workspace/json/repository.bzl
  tools/workspace/nlopt/BUILD.bazel
  tools/workspace/nlopt/package-macos.BUILD.bazel
  tools/workspace/nlopt/package-ubuntu-20.04.BUILD.bazel
  tools/workspace/nlopt/package-ubuntu-22.04.BUILD.bazel
  tools/workspace/nlopt/repository.bzl
Labels: status: single reviewer ok, release notes: removal of deprecated

#18534 Mark `gym_py` as not to be upgraded.
  tools/workspace/gym_py/README.md
  tools/workspace/new_release.py
Labels: release notes: none

#18513 SceneGraph allows changing geometry shape
  geometry/BUILD.bazel
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/internal_geometry.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/geometry_state_test.cc
  geometry/test/internal_geometry_test.cc
  geometry/test/scene_graph_test.cc
Labels: release notes: feature

#18533 Remove deprecated code 2022-11
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  multibody/inverse_kinematics/BUILD.bazel
  systems/analysis/simulator_config_functions.cc
  systems/analysis/simulator_config_functions.h
  systems/analysis/test/simulator_config_functions_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#18526 [multibody] Remove MultibodyElement's second template argument
  multibody/tree/body.h
  multibody/tree/body_node.h
  multibody/tree/force_element.h
  multibody/tree/frame_base.h
  multibody/tree/joint.h
  multibody/tree/joint_actuator.cc
  multibody/tree/joint_actuator.h
  multibody/tree/mobilizer.h
  multibody/tree/model_instance.h
  multibody/tree/multibody_element.cc
  multibody/tree/multibody_element.h
  multibody/tree/multibody_tree_system.h
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: release notes: breaking change

#18525 [framework] Fix physical dependencies for InputPort::Allocate
  bindings/pydrake/systems/framework_py_semantics.cc
  systems/framework/BUILD.bazel
  systems/framework/input_port.cc
  systems/framework/input_port.h
  systems/framework/input_port_base.cc
  systems/framework/input_port_base.h
  systems/framework/system.cc
  systems/framework/test/input_port_test.cc
Labels: release notes: breaking change

#18537 [workspace] Fix conex build with modern compilers
  tools/workspace/conex/patches/debug_macros.patch
  tools/workspace/conex/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#18498 Allow unsupported compilers with warning (CMake)
  CMakeLists.txt
Labels: release notes: fix

#18529 [pydrake] Add __repr__ to several classes
  bindings/pydrake/geometry_py_render.cc
  bindings/pydrake/math_py.cc
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/test/geometry_render_test.py
  bindings/pydrake/test/math_test.py
Labels: priority: low, release notes: fix

#18538 [multibody] Fix misuse of forward-declared classes
  multibody/topology/multibody_graph.cc
  multibody/topology/multibody_graph.h
Labels: priority: high, status: single reviewer ok, release notes: fix

#18540 [setup] Avoid accidentally installing OpenBLAS
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
Labels: priority: medium, status: single reviewer ok, release notes: fix

#18536 Remove unenforced "absolute path" requirement; resolve relpaths
  bindings/pydrake/geometry_py_common.cc
  bindings/pydrake/test/geometry_common_test.py
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/test/shape_specification_test.cc
  geometry/test/shape_to_string_test.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/tree/test/geometry_spatial_inertia_test.cc
Labels: release notes: newly deprecated, release notes: fix

#18543 [multibody] Change a user-facing error to throw, not abort
  multibody/plant/tamsi_solver.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#18539 Suppress Valgrind false positive in mosek_solver_internal_test
  tools/dynamic_analysis/valgrind.supp
Labels: priority: medium, component: build system, release notes: none

#18535 NloptSolver supports setting algorithm
  bindings/pydrake/solvers/solvers_py_nlopt.cc
  bindings/pydrake/solvers/test/nlopt_solver_test.py
  solvers/nlopt_solver.cc
  solvers/nlopt_solver.h
  solvers/nlopt_solver_common.cc
  solvers/solver_options.h
  solvers/test/nlopt_solver_test.cc
Labels: release notes: feature

#18516 Upgrade Externals January 2023
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/package.BUILD.bazel
  tools/workspace/curl_internal/repository.bzl
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/petsc/repository.bzl
  tools/workspace/stable_baselines3_internal/repository.bzl
  tools/workspace/tinyobjloader/repository.bzl
  tools/workspace/usockets/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#18544 Add test for disallowed top-level imports
  bindings/pydrake/test/all_test.py
Labels: release notes: none

#18457 [workspace] Upgrade googlebenchmark to v1.7.1
  tools/workspace/default.bzl
  tools/workspace/googlebenchmark/repository.bzl
  tools/workspace/libpfm/BUILD.bazel
  tools/workspace/libpfm/package.BUILD.bazel
  tools/workspace/libpfm/repository.bzl
Labels: priority: low, release notes: fix

#18546 [skylark] Set num_threads for test concurrency control
  common/BUILD.bazel
  perception/BUILD.bazel
  tools/skylark/README.md
  tools/skylark/drake_cc.bzl
  tools/skylark/drake_py.bzl
  tools/skylark/kwargs.bzl
Labels: priority: high, release notes: none

#18505 [C-IRIS] Find C-space polytope through binary search.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18557 [doc] Fix pydrake custom stylesheet for Sphinx on Jammy
  doc/pydrake/_static/css/custom.css
Labels: priority: medium, status: single reviewer ok, release notes: none

#18560 [tools] Improve documentation of num_threads
  tools/skylark/README.md
Labels: priority: low, status: single reviewer ok, release notes: none

#18549 Remove deprecated code 2023-01
  bindings/pydrake/manipulation/planner_py.cc
  bindings/pydrake/manipulation/test/planner_test.py
  manipulation/planner/differential_inverse_kinematics.cc
  manipulation/planner/differential_inverse_kinematics.h
  manipulation/planner/test/differential_inverse_kinematics_test.cc
  math/BUILD.bazel
  math/saturate.h
  math/test/saturate_test.cc
Labels: status: single reviewer ok, release notes: removal of deprecated

#18561 Mark lcm_interface_system_test as Flaky
  systems/lcm/BUILD.bazel
Labels: priority: backlog, status: single reviewer ok, release notes: none

#18464 Support Gurobi 9.5.x
  CMakeLists.txt
  cmake/modules/FindGurobi.cmake
  doc/_pages/bazel.md
  doc/_pages/python_bindings.md
  tools/workspace/gurobi/package-macos.BUILD.bazel.in
  tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in
  tools/workspace/gurobi/repository.bzl
Labels: release notes: feature

#18563 [workspace] Hotfix for Gurobi path searching
  tools/workspace/gurobi/repository.bzl
Labels: priority: emergency, status: single reviewer ok, release notes: none

#18559 [workspace] Build msgpack privately from source
  geometry/BUILD.bazel
  geometry/meshcat.cc
  geometry/meshcat_types.h
  geometry/test/meshcat_test.cc
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/msgpack.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/msgpack/repository.bzl
  tools/workspace/msgpack_internal/BUILD.bazel
  tools/workspace/msgpack_internal/package.BUILD.bazel
  tools/workspace/msgpack_internal/patches/vendor.patch
  tools/workspace/msgpack_internal/repository.bzl
  tools/workspace/vendor_cxx.py
  tools/workspace/vendor_cxx_test.py
Labels: priority: medium, release notes: newly deprecated, release notes: fix

#18564 [pydrake] Begin adding typed (i.e., schema-based) YAML loading
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/yaml_test.py
  bindings/pydrake/common/test/yaml_typed_test.py
  bindings/pydrake/common/yaml.py
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_read_archive_test.cc
Labels: priority: medium, release notes: feature

#18548 Improve new_release script
  setup/ubuntu/source_distribution/packages-focal-maintainer-only.txt
  setup/ubuntu/source_distribution/packages-jammy-maintainer-only.txt
  tools/workspace/README.md
  tools/workspace/new_release.py
Labels: priority: low, release notes: none

#18575 Port to parser.AddModels, part 5
  manipulation/util/make_arm_controller_model.cc
Labels: status: single reviewer ok, release notes: none

#18576 Simplify Gurobi _find_latest
  tools/workspace/gurobi/repository.bzl
Labels: status: single reviewer ok, release notes: none

#18577 Port to parser.AddModels, part 6
  manipulation/util/test/make_arm_controller_model_test.cc
Labels: status: single reviewer ok, release notes: none

#18572 [pydrake] Add pybind11 support to yaml_load_typed
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/yaml_typed_test.py
  bindings/pydrake/common/yaml.py
Labels: priority: high, release notes: feature

#18550 [parsing] Implement parent model name for Sdformat
  multibody/parsing/detail_mujoco_parser.h
  multibody/parsing/detail_parsing_workspace.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_sdf_parser.h
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: release notes: none

#18556 [doc] Add release notes v1.12.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.12.0.md
Labels: status: squashing now, release notes: none

#18480 [geometry] Promote RenderEngineGltfClient to public
  geometry/render_gltf_client/BUILD.bazel
  tools/install/libdrake/build_components.bzl
  tools/workspace/curl_internal/package.BUILD.bazel
  tools/workspace/vtk/repository.bzl
Labels: release notes: feature

#18573 Reduce macOS console spam
  tools/workspace/pybind11/pybind_coverage_xml_parser.py
Labels: status: single reviewer ok, release notes: none

#18574 Update documentation to reflect switch to Jammy for documentation site
  doc/_pages/documentation_instructions.md
  doc/_pages/release_playbook.md
Labels: status: single reviewer ok, release notes: none

#18487 [tools] Update push_release script
  tools/release_engineering/dev/README.md
  tools/release_engineering/dev/push_release
Labels: status: single reviewer ok, release notes: none

#18571 [geometry] Add array-based getters and setters to Rgba
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry_py_common.cc
  bindings/pydrake/test/geometry_common_test.py
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/yaml_read_archive.h
  geometry/rgba.cc
  geometry/rgba.h
  geometry/test/rgba_test.cc
Labels: priority: medium, release notes: feature

#18565 [doc] Tidy up pip-related instructions
  doc/_pages/pip.md
Labels: priority: medium, release notes: none

#18558 [planning] Add CollisionChecker
  planning/BUILD.bazel
  planning/collision_checker.cc
  planning/collision_checker.h
  planning/edge_measure.h
  planning/test/collision_checker_test.cc
  planning/test/unimplemented_collision_checker_test.cc
  planning/unimplemented_collision_checker.cc
  planning/unimplemented_collision_checker.h
Labels: status: commits are properly curated, release notes: feature

#18567 [pydrake] Bind fixed-size DistributionVector classes
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/schema_py.cc
  bindings/pydrake/common/test/schema_test.py
  common/schema/stochastic.cc
  common/schema/stochastic.h
Labels: priority: high, status: single reviewer ok, release notes: fix

#18387 Add python binding for RenderEngineGltfClient
  bindings/pydrake/geometry_py_render.cc
  bindings/pydrake/test/geometry_render_test.py
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/render_engine_gltf_client_params.h
Labels: release notes: feature

#18585 [parsing] Simplify tests of deprecated AddModelFromString
  multibody/parsing/test/parser_test.cc
Labels: status: single reviewer ok, release notes: none

#18588 [pydrake] Fix RollPitchYaw repr for missing template annotation
  bindings/pydrake/_math_extra.py
  bindings/pydrake/test/math_test.py
Labels: priority: low, status: single reviewer ok, release notes: fix

#18589 [pydrake] Rename symbolic.FormulaKind.True and False
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
Labels: priority: low, status: single reviewer ok, release notes: breaking change

#18592 [pydrake] Fix docstring formatting for IiwaDriver.control_mode
  manipulation/kuka_iiwa/iiwa_driver.h
Labels: priority: low, status: single reviewer ok, release notes: none

#18410 RenderEngine can also consume non-uchar-channel textures
  geometry/render/BUILD.bazel
  geometry/render/test/meshes/box16u.png
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_texture_library.cc
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/factory.h
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  tools/workspace/vtk/repository.bzl
Labels: release notes: feature

#18586 Vendor gflags
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/gflags.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/gflags/BUILD.bazel
  tools/workspace/gflags/repository.bzl
Labels: status: squashing now, release notes: feature

#18578 [multibody] Clean up some Body comments
  bindings/pydrake/multibody/test/plant_test.py
  multibody/tree/body.h
Labels: priority: low, status: single reviewer ok, release notes: none

#18593 [multibody] Remove markup that destroys Python
  multibody/tree/geometry_spatial_inertia.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#18591 [pydrake] Fix AddContactMaterial parameter ordering
  bindings/pydrake/geometry_py_common.cc
  bindings/pydrake/test/geometry_common_test.py
Labels: priority: medium, status: single reviewer ok, release notes: fix

#18604 [pydrake] Add YAML parsing for variant/union
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/schema_serialization_test.py
  bindings/pydrake/common/test/serialize_test_util_py.cc
  bindings/pydrake/common/test/yaml_typed_test.py
  bindings/pydrake/common/yaml.py
Labels: priority: medium, release notes: feature

#18583 [C-IRIS] Re-implement non-polytopic collision geometry.
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/c_iris_test_utilities.cc
  geometry/optimization/dev/test/c_iris_test_utilities.h
  geometry/optimization/dev/test/collision_geometry_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18603 Avoid auto-diff for linear IPOPT constraints
  solvers/benchmarking/BUILD.bazel
  solvers/benchmarking/benchmark_ipopt_solver.cc
  solvers/ipopt_solver.cc
Labels: release notes: fix

#18610 [workspace] Deprecate the stduuid external
  geometry/BUILD.bazel
  geometry/meshcat.cc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/stduuid/package.BUILD.bazel
  tools/workspace/stduuid_internal/BUILD.bazel
  tools/workspace/stduuid_internal/package.BUILD.bazel
  tools/workspace/stduuid_internal/patches/vendor.patch
  tools/workspace/stduuid_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#18606 [pydrake] Add YAML parsing for schema.Transform
  bindings/pydrake/common/schema_py.cc
  bindings/pydrake/common/test/schema_serialization_test.py
  bindings/pydrake/common/test/schema_test.py
  bindings/pydrake/common/yaml.py
Labels: priority: medium, release notes: feature

#18483 Add more shapes to SpatialInertia factories
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/tree/BUILD.bazel
  multibody/tree/geometry_spatial_inertia.cc
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/geometry_spatial_inertia_test.cc
  multibody/tree/test/spatial_inertia_test.cc
  multibody/tree/test/unit_inertia_test.cc
  multibody/tree/unit_inertia.cc
  multibody/tree/unit_inertia.h
Labels: priority: medium, status: squashing now, release notes: feature

#18608 [planning] Add ComputeCollisionAvoidanceDisplacement
  planning/BUILD.bazel
  planning/collision_avoidance.cc
  planning/collision_avoidance.h
  planning/test/collision_avoidance_test.cc
Labels: priority: medium, status: commits are properly curated, release notes: none

#18605 ScsSolver adds quadratic cost directly.
  bindings/pydrake/solvers/test/scs_solver_test.py
  multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
  solvers/scs_solver.cc
Labels: release notes: feature

#18613 [C-IRIS] support cylinder geometry.
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/test/c_iris_test_utilities.cc
  geometry/optimization/dev/test/c_iris_test_utilities.h
  geometry/optimization/dev/test/collision_geometry_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18624 [planning] Hotfix unit test for ARM machine precision
  planning/test/collision_avoidance_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#18623 [C-IRIS] Speed up binary search.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
Labels: release notes: none

#18621 Disable cspace_free_polytope_test to appease CI
  geometry/optimization/dev/BUILD.bazel
Labels: priority: high, release notes: none

#18628 [planning] Fix malformed include statements
  planning/body_shape_description.cc
  planning/collision_checker_context.cc
  planning/test/body_shape_description_test.cc
  planning/test/collision_avoidance_test.cc
  planning/test/collision_checker_test.cc
  planning/test/robot_collision_type_test.cc
Labels: priority: low, status: single reviewer ok, release notes: fix

#18627 [C-IRIS] combine rational_for_point and rational_for_matrix_sos.
  geometry/optimization/dev/collision_geometry.cc
  geometry/optimization/dev/collision_geometry.h
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/collision_geometry_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
Labels: release notes: none

#18631 [tools] Upgrade benchmark_tool to Jammy
  tools/performance/benchmark_tool.py
Labels: status: single reviewer ok, release notes: none

#18633 [workspace] Upgrade gtest to latest release v1.13.0
  tools/workspace/gtest/repository.bzl
  tools/workspace/new_release.py
Labels: priority: low, status: single reviewer ok, release notes: fix

#18636 [py systems] Bind `DiagramBuilder.{already_built,IsConnectedOrExported}`
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
Labels: status: single reviewer ok, release notes: fix

#18637 [cmake] Set same bazel minimum version as WORKSPACE
  CMakeLists.txt
Labels: status: single reviewer ok, release notes: fix

#18545 Upgrade Bazel to 6.0.0
  .bazeliskrc
  doc/_pages/from_source.md
  setup/ubuntu/source_distribution/install_prereqs.sh
  tools/skylark/drake_cc.bzl
  tools/wheel/image/provision-base.sh
  tools/workspace/drake_visualizer/image/provision.sh
  tools/workspace/dreal/patches/pull18545.patch
  tools/workspace/dreal/repository.bzl
Labels: release notes: fix

#18626 [meldis] Avoid reloading when the scene hasn't changed
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: priority: low, release notes: feature

#18632 [C-IRIS] split cspace_free_polytope_test.
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/test/c_iris_test_utilities.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Labels: status: single reviewer ok, release notes: none

#18625 [parsing] Add model name prefix constructors to Parser
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/test/parser_test.cc
  multibody/rational/test/rational_forward_kinematics_test_utilities.cc
  multibody/test_utilities/add_fixed_objects_to_plant.h
  tutorials/rendering_multibody_plant.ipynb
Labels: release notes: feature

#18643 add Alexandre Amice to contributors
  doc/_pages/credits.md
Labels: status: single reviewer ok, release notes: none

#18641 fix small typo in polynomial.h
  common/symbolic/polynomial.h
Labels: status: single reviewer ok, release notes: none

#18644 Increase mypy timeout for glacial CI machines again
  tools/workspace/mypy_internal/patches/timeout.patch
Labels: release notes: fix

#18470 [multibody] Add 3-dof ball constraints to SAP
  multibody/plant/BUILD.bazel
  multibody/plant/constraint_specs.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/sap_driver_ball_constraints_test.cc
Labels: release notes: feature

#18587 [pydrake] Introduce name mangling for template classes
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
  bindings/pydrake/_math_extra.py
  bindings/pydrake/_trajectories_extra.py
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/__init__.py
  bindings/pydrake/common/_eigen_geometry_extra.py
  bindings/pydrake/common/cpp_param.py
  bindings/pydrake/common/cpp_template.py
  bindings/pydrake/common/cpp_template_pybind.h
  bindings/pydrake/common/eigen_geometry_py.cc
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/serialize_pybind.h
  bindings/pydrake/common/test/cpp_param_test.py
  bindings/pydrake/common/test/cpp_template_pybind_test.cc
  bindings/pydrake/common/test/cpp_template_test.py
  bindings/pydrake/common/test/eigen_geometry_test.py
  bindings/pydrake/common/test/serialize_pybind_test.py
  bindings/pydrake/common/test/serialize_test_util_py.cc
  bindings/pydrake/common/test/value_test.py
  bindings/pydrake/common/yaml.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/_math_extra.py
  bindings/pydrake/multibody/_plant_extra.py
  bindings/pydrake/multibody/_tree_extra.py
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/math_test.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/scalar_conversion.py
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/scalar_conversion_test.py
  bindings/pydrake/test/math_test.py
  bindings/pydrake/test/pyi_sanity_test.py
  bindings/pydrake/test/stubgen_test.py
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  doc/_pages/python_bindings.md
  doc/defs.py
  doc/pydrake/build.py
Labels: priority: medium, release notes: breaking change, release notes: feature

#18645 [pydrake] Bind all SceneGraph.RemoveRole overloads
  bindings/pydrake/geometry_py_scene_graph.cc
  bindings/pydrake/test/geometry_scene_graph_test.py
  geometry/scene_graph.h
Labels: priority: high, status: single reviewer ok, release notes: fix

#18600 Fix a bug in DiscreteLyapunovEquation
  math/discrete_lyapunov_equation.cc
  math/test/discrete_lyapunov_equation_test.cc
Labels: release notes: fix

#18562 Add bounding box or rotated lorentz cone constraint for small psd matrices
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
  solvers/test/mosek_solver_test.cc
Labels: release notes: feature

#18648 Revert "Add bounding box or rotated lorentz cone constraint for small psd matrices"
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
  solvers/test/mosek_solver_test.cc
Labels: priority: high, status: single reviewer ok, release notes: feature

#18629 [planning] Add SceneGraphCollisionChecker
  planning/BUILD.bazel
  planning/scene_graph_collision_checker.cc
  planning/scene_graph_collision_checker.h
  planning/test/collision_checker_test.cc
  planning/test/planning_test_helpers.cc
  planning/test/planning_test_helpers.h
  planning/test/scene_graph_collision_checker_test.cc
  planning/test_utilities/BUILD.bazel
  planning/test_utilities/collision_checker_abstract_test_suite.cc
  planning/test_utilities/collision_checker_abstract_test_suite.h
  planning/test_utilities/collision_ground_plane.sdf
Labels: priority: medium, status: commits are properly curated, release notes: feature

#18646 Port to parser.AddModels, part 7
  bindings/pydrake/visualization/test/meldis_test.py
  geometry/test/meshcat_visualizer_test.cc
  multibody/meshcat/test/contact_visualizer_test.cc
  multibody/meshcat/test/joint_sliders_test.cc
  multibody/plant/test/applied_generalized_force_test.cc
  multibody/plant/test/internal_geometry_names_test.cc
  multibody/plant/test/multibody_plant_introspection_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: release notes: none

#18630 Fix wheel build of libtiff
  tools/wheel/image/dependencies/projects/libtiff.cmake
Labels: release notes: none

#18651 [C-IRIS] fix a bug in the separating plane.
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/separating_plane.h
  geometry/optimization/dev/test/c_iris_test_utilities.cc
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
  geometry/optimization/dev/test/separating_plane_test.cc
Labels: release notes: none

#18652 [workspace] Upgrade stduuid_internal to latest release v1.2.3
  tools/workspace/stduuid_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#18658 [planning] Fix CollisionChecker test vs memcheck
  planning/test_utilities/collision_checker_abstract_test_suite.cc
  planning/test_utilities/collision_checker_abstract_test_suite.h
Labels: status: single reviewer ok, release notes: none

#18657 Setting optimization/dev test manual
  geometry/optimization/dev/BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#18650 [pydrake] Bind planning.RobotDiagram and related
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/all.py
  bindings/pydrake/planning/planning_py.cc
  bindings/pydrake/planning/planning_py.h
  bindings/pydrake/planning/planning_py_robot_diagram.cc
  bindings/pydrake/planning/test/robot_diagram_test.py
  bindings/pydrake/systems/framework_py_semantics.cc
Labels: priority: high, release notes: fix

#18661 [planning] Make EdgeMeasure DEFAULT_COPY
  planning/edge_measure.h
Labels: status: single reviewer ok, release notes: none

#18647 Consolidate contact results
  examples/multibody/inclined_plane_with_body/inclined_plane_with_body.cc
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/contact_jacobians.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/tamsi_driver.cc
  multibody/plant/tamsi_driver.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test_utilities/rigid_body_on_compliant_ground.h
Labels: type: cleanup, release notes: fix

#18662 Update new_release README
  tools/workspace/README.md
Labels: status: single reviewer ok, release notes: none

#18665 Deprecate `--with-maintainer-only` install flag on macOS
  setup/mac/install_prereqs.sh
  setup/mac/source_distribution/Brewfile-maintainer-only
  setup/mac/source_distribution/install_prereqs.sh
  setup/mac/source_distribution/requirements-maintainer-only.txt
Labels: release notes: newly deprecated

#18655 [py value] Ensure Value[object].SetFrom() deep copies the value
  bindings/pydrake/common/cpp_param_pybind.cc
  bindings/pydrake/common/cpp_param_pybind.h
  bindings/pydrake/common/test/value_test.py
  bindings/pydrake/common/value_py.cc
  bindings/pydrake/systems/test/custom_test.py
Labels: release notes: fix

#18667 [C-IRIS] include HPolyhedron {s | C*s<=d, s_lower <= s <= s_upper} in the result.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Labels: release notes: none

#18668 fix small typo in multibody plant documentation
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok, release notes: none

#18669 [setup] Automatically fix GCC 12 installation mistakes on Jammy
  setup/ubuntu/source_distribution/install_prereqs.sh
  tools/workspace/pybind11/mkdoc.py
Labels: priority: low, status: single reviewer ok, release notes: fix

#18676 make cost termination in cspace free polytope bilinear alternation a …
  geometry/optimization/dev/cspace_free_polytope.cc
Labels: release notes: none

#18671 [meldis] Fix deprecation warning spam
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: priority: low, status: single reviewer ok, release notes: fix

#18679 [doc] Fix some broken links
  bindings/pydrake/common/containers.py
  doc/_pages/doxygen_instructions.md
  doc/doxygen_cxx/doxygen.h
  doc/index.md
  multibody/benchmarks/free_body/free_body.h
  multibody/multibody_doxygen.h
  solvers/solver_options.h
  systems/systems.h
  tutorials/solver_parameters.ipynb
Labels: priority: backlog, status: single reviewer ok, release notes: none

#18683 [pydrake] Deprecate the pydrake.solvers.* submodules
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/all.py
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  bindings/pydrake/multibody/test/optimization_test.py
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/all.py
  bindings/pydrake/solvers/augmented_lagrangian.py
  bindings/pydrake/solvers/branch_and_bound.py
  bindings/pydrake/solvers/clp.py
  bindings/pydrake/solvers/csdp.py
  bindings/pydrake/solvers/gurobi.py
  bindings/pydrake/solvers/ipopt.py
  bindings/pydrake/solvers/mathematicalprogram.py
  bindings/pydrake/solvers/mixed_integer_optimization_util.py
  bindings/pydrake/solvers/mixed_integer_rotation_constraint.py
  bindings/pydrake/solvers/mosek.py
  bindings/pydrake/solvers/nlopt.py
  bindings/pydrake/solvers/osqp.py
  bindings/pydrake/solvers/scs.py
  bindings/pydrake/solvers/sdpa_free_format.py
  bindings/pydrake/solvers/snopt.py
  bindings/pydrake/solvers/test/augmented_lagrangian_test.py
  bindings/pydrake/solvers/test/branch_and_bound_test.py
  bindings/pydrake/solvers/test/clp_solver_test.py
  bindings/pydrake/solvers/test/csdp_solver_test.py
  bindings/pydrake/solvers/test/dreal_solver_test.py
  bindings/pydrake/solvers/test/gurobi_solver_test.py
  bindings/pydrake/solvers/test/ibex_solver_test.py
  bindings/pydrake/solvers/test/ipopt_solver_test.py
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py
  bindings/pydrake/solvers/test/mixed_integer_rotation_constraint_test.py
  bindings/pydrake/solvers/test/mosek_solver_test.py
  bindings/pydrake/solvers/test/nlopt_solver_test.py
  bindings/pydrake/solvers/test/noscipy_test.py
  bindings/pydrake/solvers/test/osqp_solver_test.py
  bindings/pydrake/solvers/test/scs_solver_test.py
  bindings/pydrake/solvers/test/sdpa_free_format_test.py
  bindings/pydrake/solvers/test/snopt_solver_test.py
  bindings/pydrake/stubgen.py
  bindings/pydrake/systems/test/trajectory_optimization_test.py
  bindings/pydrake/test/all_test.py
Labels: priority: medium, status: single reviewer ok, release notes: newly deprecated

#18684 [pydrake] Move geometry files into subdir
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/geometry/BUILD.bazel
  bindings/pydrake/geometry/_geometry_extra.py
  bindings/pydrake/geometry/geometry_py.cc
  bindings/pydrake/geometry/geometry_py.h
  bindings/pydrake/geometry/geometry_py_common.cc
  bindings/pydrake/geometry/geometry_py_hydro.cc
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/geometry_py_visualizers.cc
  bindings/pydrake/geometry/test/common_test.py
  bindings/pydrake/geometry/test/frame_id_test.py
  bindings/pydrake/geometry/test/hydro_test.py
  bindings/pydrake/geometry/test/optimization_test.py
  bindings/pydrake/geometry/test/render_engine_gl_test.py
  bindings/pydrake/geometry/test/render_engine_subclass_test.py
  bindings/pydrake/geometry/test/render_test.py
  bindings/pydrake/geometry/test/scene_graph_test.py
  bindings/pydrake/geometry/test/visualizers_test.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/visualization/BUILD.bazel
Labels: priority: medium, status: single reviewer ok, release notes: none

#18694 [workspace] Patch FCL for missing include statement
  tools/workspace/fcl_internal/patches/cassert.patch
  tools/workspace/fcl_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#18681 [doc] Add VS Code and Emacs integration tips
  doc/_pages/code_style_tools.md
  doc/_pages/developers.md
  doc/_pages/emacs.md
  doc/_pages/vscode.md
Labels: priority: medium, release notes: none

#18695 [workspace] Patch Conex for missing include statement
  tools/workspace/conex/patches/debug_macros.patch
Labels: priority: low, status: single reviewer ok, release notes: fix

#18674 [pydrake] Fix incompatibility with Mypy
  bindings/pydrake/test/stubgen_test.py
  common/symbolic/expression/formula.h
  multibody/tree/geometry_spatial_inertia.h
  tools/workspace/mypy_internal/patches/reject_double_colon.patch
  tools/workspace/mypy_internal/repository.bzl
Labels: priority: high, release notes: fix

#18664 [planning] Reorganize planning artifacts in planning (1 of 3)
  examples/kinova_jaco_arm/BUILD.bazel
  examples/kinova_jaco_arm/jaco_controller.cc
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/iiwa_controller.cc
  examples/kuka_iiwa_arm/lcm_plan_interpolator.cc
  examples/kuka_iiwa_arm/lcm_plan_interpolator.h
  manipulation/planner/BUILD.bazel
  manipulation/planner/stub/constraint_relaxing_ik.h
  manipulation/planner/stub/robot_plan_interpolator.h
  manipulation/planner/test/deprecation_test.cc
  manipulation/util/BUILD.bazel
  manipulation/util/move_ik_demo_base.cc
  manipulation/util/move_ik_demo_base.h
  manipulation/util/robot_plan_interpolator.cc
  manipulation/util/robot_plan_interpolator.h
  manipulation/util/test/robot_plan_interpolator_test.cc
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/constraint_relaxing_ik.cc
  multibody/inverse_kinematics/constraint_relaxing_ik.h
  multibody/inverse_kinematics/test/constraint_relaxing_ik_test.cc
Labels: status: commits are properly curated, release notes: newly deprecated

#18696 [py systems] Allow simulator monitor to return None
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
Labels: status: single reviewer ok, release notes: fix

#18698 [manipulation] Remove spurious deprecation warning output
  manipulation/planner/BUILD.bazel
Labels: priority: medium, status: single reviewer ok, release notes: none

#18693 [tools] Add linter for unnecessary iostream includes
  common/symbolic/test/codegen_test.cc
  common/symbolic/test/latex_test.cc
  common/symbolic/test/trigonometric_polynomial_test.cc
  common/test/eigen_types_test.cc
  common/trajectories/test/piecewise_polynomial_generation_test.cc
  examples/fibonacci/fibonacci_difference_equation.h
  examples/fibonacci/run_fibonacci.cc
  examples/pendulum/pendulum_parameters_derivatives.cc
  geometry/benchmarking/render_benchmark.cc
  geometry/proximity/mesh_to_vtk.cc
  manipulation/models/wsg_50_description/sdf/test/wsg_50_sdf_test.cc
  math/test/rotation_conversion_test.cc
  multibody/tree/body_node.cc
  perception/test/point_cloud_flags_test.cc
  tools/lint/drakelint.py
Labels: priority: low, release notes: none

#18706 [pydrake] Hotfix for moving geometry files into subdir
  tools/wheel/image/setup.py
Labels: priority: high, status: single reviewer ok, release notes: none

#18687 [framework] Add System::Clone
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/scalar_conversion_test.py
  systems/framework/BUILD.bazel
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/test/leaf_system_test.cc
Labels: priority: low, release notes: feature

#18708 [tutorials] Fix markup typo for link
  tutorials/_developers.md
Labels: status: single reviewer ok, release notes: none

#18707 CMake builds: Treat DrakeDeprecationWarning as a warning not an error
  CTestCustom.cmake.in
Labels: priority: emergency, configuration: cmake, status: single reviewer ok, release notes: none

#18699 [common] Remove vestigial Eigen version guards
  common/eigen_types.h
  common/symbolic/expression/formula.h
  common/symbolic/expression/test/expression_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#18685 [pydrake] Deprecate the pydrake.examples.* submodules
  bindings/pydrake/examples/acrobot.py
  bindings/pydrake/examples/compass_gait.py
  bindings/pydrake/examples/manipulation_station.py
  bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py
  bindings/pydrake/examples/pendulum.py
  bindings/pydrake/examples/quadrotor.py
  bindings/pydrake/examples/rimless_wheel.py
  bindings/pydrake/examples/test/acrobot_test.py
  bindings/pydrake/examples/test/compass_gait_test.py
  bindings/pydrake/examples/test/manipulation_station_test.py
  bindings/pydrake/examples/test/pendulum_test.py
  bindings/pydrake/examples/test/quadrotor_test.py
  bindings/pydrake/examples/test/rimless_wheel_test.py
  bindings/pydrake/examples/test/van_der_pol_test.py
  bindings/pydrake/examples/van_der_pol.py
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#18689 [parsing,sensors,visualization] Remove deprecated code 2023-02
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/plotting.py
  bindings/pydrake/visualization/test/meldis_test.py
  bindings/pydrake/visualization/test/plotting_test.py
  multibody/parsing/BUILD.bazel
  multibody/parsing/package_map.cc
  multibody/parsing/package_map.h
  multibody/parsing/test/package_map_test.cc
  systems/sensors/camera_config_functions.cc
  systems/sensors/camera_config_functions.h
  systems/sensors/test/camera_config_functions_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#18709 [planning] Add logging of OpenMP enablement in CollisionChecker
  planning/collision_checker.cc
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#18670 [pydrake] Bind planning.CollisionChecker and related
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py.cc
  bindings/pydrake/planning/planning_py.h
  bindings/pydrake/planning/planning_py_collision_checker.cc
  bindings/pydrake/planning/planning_py_collision_checker_interface_types.cc
  bindings/pydrake/planning/test/collision_checker_test.py
  planning/collision_checker.h
  planning/unimplemented_collision_checker.h
Labels: priority: medium, release notes: fix

#18690 [workspace] Deprecate public use of several externals
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-focal.txt
  setup/ubuntu/source_distribution/packages-jammy.txt
  solvers/BUILD.bazel
  tools/install/check_licenses.bzl
  tools/wheel/image/dependencies/patches/suitesparse/patch.cmake
  tools/wheel/image/dependencies/patches/suitesparse/patch.diff
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/suitesparse.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/osqp_internal/BUILD.bazel
  tools/workspace/osqp_internal/package.BUILD.bazel
  tools/workspace/osqp_internal/repository.bzl
  tools/workspace/qdldl_internal/BUILD.bazel
  tools/workspace/qdldl_internal/README.md
  tools/workspace/qdldl_internal/package.BUILD.bazel
  tools/workspace/qdldl_internal/repository.bzl
  tools/workspace/scs_internal/BUILD.bazel
  tools/workspace/scs_internal/package.BUILD.bazel
  tools/workspace/scs_internal/private.h.diff
  tools/workspace/scs_internal/repository.bzl
  tools/workspace/suitesparse/package.BUILD.bazel
  tools/workspace/suitesparse_internal/BUILD.bazel
  tools/workspace/suitesparse_internal/package.BUILD.bazel
  tools/workspace/suitesparse_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#18713 Consolidate out-of-support documentation
  doc/_release-notes/2015.md
  doc/_release-notes/2016.md
  doc/_release-notes/end_of_support.md
  doc/_release-notes/release_notes.md
Labels: release notes: none

#18710 [common] Adjust Expression for Eigen pre-3.5 compatibility
  common/symbolic/expression/formula.h
  common/symbolic/polynomial.cc
  common/symbolic/polynomial.h
  common/symbolic/rational_function.cc
  common/symbolic/rational_function.h
Labels: status: single reviewer ok, release notes: fix

#18268 [examples] manipulation_station exports `applied_spatial_force` port
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station.h
  examples/manipulation_station/test/manipulation_station_test.cc
Labels: release notes: breaking change, release notes: feature

#18582 Function that shifts a body's center of mass location and preserves its central unit inertia.
  multibody/tree/rigid_body.cc
  multibody/tree/rigid_body.h
  multibody/tree/test/rigid_body_test.cc
  multibody/tree/unit_inertia.h
Labels: priority: medium, status: squashing now, release notes: feature

#18618 Add tetrahedron to SpatialInertia and UnitInertia.
  multibody/tree/rotational_inertia.h
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/rigid_body_test.cc
  multibody/tree/test/spatial_inertia_test.cc
  multibody/tree/test/unit_inertia_test.cc
  multibody/tree/unit_inertia.cc
  multibody/tree/unit_inertia.h
Labels: priority: medium, status: squashing now, release notes: feature
