Repository RobotLocomotion/drake, pull requests merged in 2023-02, with the labels that each got.

#18716 Remove deprecated code 2023-02
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/test/symbolic_test.py
  common/symbolic/trigonometric_polynomial.h
  systems/framework/system.h
Labels: status: single reviewer ok, release notes: removal of deprecated

#18714 [py planning] Remove RobotBuilder const vs non-const distinction
  bindings/pydrake/planning/planning_py_robot_diagram.cc
  bindings/pydrake/planning/test/collision_checker_test.py
  bindings/pydrake/planning/test/robot_diagram_test.py
Labels: priority: high, release notes: none

#18721 [pydrake] Clean up binding code for trajectory_optimization_py.cc
  bindings/pydrake/systems/trajectory_optimization_py.cc
Labels: status: single reviewer ok, release notes: none

#18717 Add Clone support to SceneGraph and RobotDiagram
  geometry/BUILD.bazel
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/geometry_state_test.cc
  geometry/test/scene_graph_test.cc
  planning/robot_diagram.cc
  planning/test/robot_diagram_test.cc
  systems/framework/diagram.h
  systems/framework/system_scalar_conversion_doxygen.h
  systems/framework/test/diagram_test.cc
Labels: priority: medium, release notes: feature

#18718 [planning] Improve welded body check in CollisionChecker
  planning/collision_checker.cc
Labels: status: squashing now, release notes: fix

#18654 Remove Jammy APT packages warning from documentation
  doc/_pages/apt.md
Labels: type: documentation, status: squashing now, release notes: none

#18642 Ensure that the N matrix is consistent with MapVelocityToQdot() and MapQdotToVelocity().
  multibody/tree/test/planar_mobilizer_test.cc
  multibody/tree/test/prismatic_mobilizer_test.cc
  multibody/tree/test/quaternion_floating_mobilizer_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
  multibody/tree/test/screw_mobilizer_test.cc
  multibody/tree/test/space_xyz_floating_mobilizer_test.cc
  multibody/tree/test/space_xyz_mobilizer_test.cc
  multibody/tree/test/universal_mobilizer_test.cc
  multibody/tree/test/weld_mobilizer_test.cc
Labels: release notes: none

#18722 Add pip troubleshooting documentation
  doc/_pages/troubleshooting.md
Labels: release notes: none

#18725 SpatialInertia tetrahedron calculations always returns a valid spatial inertia.
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#18697 [planning] Reorganize planning artifacts in planning (2 of 3)
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py.cc
  bindings/pydrake/planning/planning_py.h
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/all.py
  bindings/pydrake/systems/test/trajectory_optimization_dep_test.py
  bindings/pydrake/systems/trajectory_optimization.py
  examples/acrobot/BUILD.bazel
  examples/acrobot/test/run_swing_up_traj_optimization.cc
  examples/pendulum/BUILD.bazel
  examples/pendulum/trajectory_optimization_simulation.cc
  planning/trajectory_optimization/BUILD.bazel
  planning/trajectory_optimization/direct_collocation.cc
  planning/trajectory_optimization/direct_collocation.h
  planning/trajectory_optimization/direct_transcription.cc
  planning/trajectory_optimization/direct_transcription.h
  planning/trajectory_optimization/integration_constraint.cc
  planning/trajectory_optimization/integration_constraint.h
  planning/trajectory_optimization/kinematic_trajectory_optimization.cc
  planning/trajectory_optimization/kinematic_trajectory_optimization.h
  planning/trajectory_optimization/multiple_shooting.cc
  planning/trajectory_optimization/multiple_shooting.h
  planning/trajectory_optimization/sequential_expression_manager.cc
  planning/trajectory_optimization/sequential_expression_manager.h
  planning/trajectory_optimization/test/direct_collocation_test.cc
  planning/trajectory_optimization/test/direct_transcription_test.cc
  planning/trajectory_optimization/test/integration_constraint_test.cc
  planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
  planning/trajectory_optimization/test/multiple_shooting_test.cc
  planning/trajectory_optimization/test/sequential_expression_manager_test.cc
  systems/controllers/BUILD.bazel
  systems/controllers/linear_model_predictive_controller.cc
  systems/trajectory_optimization/BUILD.bazel
  systems/trajectory_optimization/stub/direct_collocation.h
  systems/trajectory_optimization/stub/direct_transcription.h
  systems/trajectory_optimization/stub/integration_constraint.h
  systems/trajectory_optimization/stub/kinematic_trajectory_optimization.h
  systems/trajectory_optimization/stub/multiple_shooting.h
  systems/trajectory_optimization/stub/sequential_expression_manager.h
  systems/trajectory_optimization/test/deprecation_test.cc
  tools/install/libdrake/build_components.bzl
Labels: status: commits are properly curated, release notes: newly deprecated

#18733 [multibody] Update some TODOs in multibody_plant.h
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok, release notes: none

#18735 [parsing] Fix URDF planar joint support
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
Labels: status: single reviewer ok, release notes: fix

#18728 [parsing] Add support for URDF mimic element.
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
Labels: priority: medium, release notes: breaking change, release notes: feature

#18720 Check browser supports gamepads in meshcat
  geometry/meshcat.html
Labels: release notes: fix

#18446 [systems/framework] More verbose error message in DiagramBuilder
  systems/framework/diagram_builder.cc
  systems/framework/test/diagram_builder_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#18678 [workspace] Better hide ccd and fcl externals
  geometry/proximity/BUILD.bazel
  geometry/proximity/collisions_exist_callback.h
  geometry/proximity/distance_to_point_callback.h
  geometry/proximity/distance_to_shape_callback.h
  geometry/proximity/find_collision_candidates_callback.h
  geometry/proximity/hydroelastic_callback.h
  geometry/proximity/penetration_as_point_pair_callback.h
  geometry/proximity/proximity_utilities.h
  geometry/proximity/test/characterization_utilities.h
  geometry/proximity/test/collisions_exist_callback_test.cc
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/distance_to_point_callback_test.cc
  geometry/proximity/test/find_collision_candidates_callback_test.cc
  geometry/proximity/test/hydroelastic_callback_test.cc
  geometry/proximity/test/proximity_utilities_test.cc
  geometry/proximity_engine.cc
  geometry/test/proximity_engine_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/ccd/package.BUILD.bazel
  tools/workspace/ccd_internal/package.BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/fcl_internal/package.BUILD.bazel
  tools/workspace/fcl_internal/version-from-xml.sed
Labels: priority: low, release notes: none

#18736 [multibody] Allow opt out of adjacent body collision filters
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_config.h
  multibody/plant/multibody_plant_config_functions.cc
  multibody/plant/test/multibody_plant_config_functions_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: release notes: feature

#18739 [C-IRIS] bring InitializePolytopeSearchProgram to public.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Labels: release notes: none

#18747 Fix a bug in QuaternionToHopfCoordinate.
  math/hopf_coordinate.h
  math/test/hopf_coordinate_test.cc
  math/test/random_rotation_test.cc
Labels: release notes: fix

#18680 [tools] Improve compatibility with Ubuntu derivatives
  CMakeLists.txt
  tools/workspace/os.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#18737 Include underactuated and manipulation in "Search all of Drake"
  doc/_includes/header.html
  doc/doxygen_cxx/doxygen_extra.css
  doc/doxygen_cxx/header.html.patch
  doc/pydrake/searchbox.html
Labels: priority: medium, status: squashing now, release notes: none

#18742 [C-IRIS] add IsGeometrySeparable function.
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Labels: status: squashing now, release notes: none

#18663 Allow Gurobi tests to run in parallel in CI
  tools/skylark/test_tags.bzl
  tools/workspace/gurobi/repository.bzl
Labels: priority: low, release notes: none

#18734 Remove unused libyaml and libdl2 dependencies
  setup/mac/binary_distribution/Brewfile
  setup/ubuntu/binary_distribution/packages-focal.txt
  setup/ubuntu/binary_distribution/packages-jammy.txt
Labels: release notes: fix

#18755 Downgrade usockets/uwebsockets
  tools/workspace/usockets/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
Labels: priority: emergency, status: single reviewer ok, release notes: fix

#18715 [planning] Reorganize planning artifacts in planning (3 of 3)
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/all.py
  bindings/pydrake/manipulation/planner.py
  bindings/pydrake/manipulation/test/planner_deprecated_test.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/inverse_kinematics_py.h
  bindings/pydrake/multibody/inverse_kinematics_py_differential.cc
  bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py
  examples/manipulation_station/end_effector_teleop_dualshock4.py
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
  manipulation/planner/BUILD.bazel
  manipulation/planner/stub/constraint_relaxing_ik.h
  manipulation/planner/stub/differential_inverse_kinematics.h
  manipulation/planner/stub/differential_inverse_kinematics_integrator.h
  manipulation/planner/stub/robot_plan_interpolator.h
  manipulation/planner/test/deprecation_test.cc
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/differential_inverse_kinematics.cc
  multibody/inverse_kinematics/differential_inverse_kinematics.h
  multibody/inverse_kinematics/differential_inverse_kinematics_integrator.cc
  multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h
  multibody/inverse_kinematics/test/differential_inverse_kinematics_integrator_test.cc
  multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc
  tools/install/libdrake/build_components.bzl
Labels: status: commits are properly curated, release notes: newly deprecated

#18760 fix c_iris tests
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Labels: release notes: none

#18761 [workspace] Disable auto-upgrade for usockets,uwebsockets
  tools/workspace/new_release.py
Labels: priority: low, status: single reviewer ok, release notes: none

#18763 [workspace] Upgrade buildifier to latest release 6.0.1
  tools/workspace/buildifier/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#18770 Rename RobotDiagram::BuildDiagram() => Build()
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py_robot_diagram.cc
  bindings/pydrake/planning/test/collision_checker_test.py
  bindings/pydrake/planning/test/robot_diagram_test.py
  planning/robot_diagram_builder.cc
  planning/robot_diagram_builder.h
  planning/test/body_shape_description_test.cc
  planning/test/collision_avoidance_test.cc
  planning/test/collision_checker_context_test.cc
  planning/test/collision_checker_test.cc
  planning/test/planning_test_helpers.cc
  planning/test/robot_diagram_test.cc
  planning/test/scene_graph_collision_checker_test.cc
  planning/test/unimplemented_collision_checker_test.cc
Labels: priority: high, status: single reviewer ok, release notes: newly deprecated

#18744 Convert MultilayerPerceptron benchmark to googlebench
  systems/benchmarking/BUILD.bazel
  systems/benchmarking/README.md
  systems/benchmarking/multilayer_perceptron_benchmark.cc
  systems/benchmarking/multilayer_perceptron_performance.cc
Labels: priority: medium, release notes: none

#18738 [multibody] Adding time-varying constraints to two Toppra APIs
  bindings/pydrake/multibody/optimization_py.cc
  bindings/pydrake/multibody/test/optimization_test.py
  multibody/optimization/BUILD.bazel
  multibody/optimization/test/toppra_test.cc
  multibody/optimization/toppra.cc
  multibody/optimization/toppra.h
Labels: release notes: feature

#18767 [common] Remove SortedPair mutable structured bindings
  common/sorted_pair.h
  common/test/sorted_pair_test.cc
Labels: priority: low, release notes: breaking change

#18772 [planning] Simplify RobotDiagramBuilder function names
  bindings/pydrake/planning/planning_py_robot_diagram.cc
  bindings/pydrake/planning/test/robot_diagram_test.py
  planning/robot_diagram_builder.cc
  planning/robot_diagram_builder.h
  planning/test/body_shape_description_test.cc
  planning/test/collision_avoidance_test.cc
  planning/test/collision_checker_test.cc
  planning/test/planning_test_helpers.cc
  planning/test/robot_diagram_test.cc
  planning/test/scene_graph_collision_checker_test.cc
Labels: release notes: newly deprecated, release notes: fix

#18779 [toppra] Use larger unit test tolerance (for macOS arm64)
  multibody/optimization/test/toppra_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#18351 [parsing] Initial collision filter support in mujoco parser
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_tinyxml.cc
  multibody/parsing/detail_tinyxml.h
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: medium, release notes: feature

#18262 [workspace] Update macOS to python@3.11
  CMakeLists.txt
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  tools/install/install_test_helper.py
  tools/py_toolchain/interpreter_paths.bzl
  tools/release_engineering/download_release_candidate.py
  tools/wheel/image/setup.py
  tools/wheel/macos/build-wheel.sh
  tools/wheel/macos/provision-test-python.sh
  tools/workspace/python/repository.bzl
Labels: release notes: feature

#18777 [C-IRIS] bring back cspace_free_polytope_with_mosek_test.
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Labels: release notes: none

#18781 [C-IRIS] add CIris to CollisionGeometry and SeparatingPlane.
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/c_iris_collision_geometry.cc
  geometry/optimization/dev/c_iris_collision_geometry.h
  geometry/optimization/dev/c_iris_separating_plane.cc
  geometry/optimization/dev/c_iris_separating_plane.h
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/separating_plane.cc
  geometry/optimization/dev/test/c_iris_collision_geometry_test.cc
  geometry/optimization/dev/test/c_iris_separating_plane_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Labels: release notes: none

#18785 [workspace] Upgrade tinyobjloader to latest commit
  tools/workspace/tinyobjloader/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#18769 Adds `Authoring Leaf Systems` tutorial
  tutorials/BUILD.bazel
  tutorials/authoring_leaf_systems.ipynb
  tutorials/dynamical_systems.ipynb
  tutorials/index.ipynb
Labels: priority: high, release notes: feature

#18764 [install] Add shortcuts for meldis and model_visualizer
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/meldis.py
  bindings/pydrake/visualization/model_visualizer.py
  bindings/pydrake/visualization/run_installed_meldis.py.in
  bindings/pydrake/visualization/run_installed_model_visualizer.py.in
  bindings/pydrake/visualization/test/visualization_install_tests.py
  tools/workspace/drake_visualizer/drake_visualizer_disabled.py
Labels: priority: medium, release notes: feature

#18746 Cleanup of the EvalContactResults() workflow
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/compliant_contact_manager.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
Labels: type: cleanup, component: multibody plant, release notes: none

#18786 [macOS] Fix python 3.11 testing issues
  bindings/pydrake/common/test/deprecation_autocomplete_test.py
  tools/workspace/styleguide/BUILD.bazel
Labels: priority: emergency, release notes: fix

#18701 [planning] Opt-in to clang-format lint
  .clang-format
  bindings/pydrake/.clang-format
  lcm/drake_lcm.cc
  planning/BUILD.bazel
  planning/body_shape_description.cc
  planning/collision_checker.cc
  planning/collision_checker_params.h
  planning/robot_diagram.cc
  planning/robot_diagram.h
  planning/robot_diagram_builder.h
  planning/scene_graph_collision_checker.cc
  planning/test/collision_avoidance_test.cc
  planning/test/collision_checker_test.cc
  planning/test/planning_test_helpers.cc
  planning/test/planning_test_helpers.h
  planning/test/robot_diagram_test.cc
  planning/test/scene_graph_collision_checker_test.cc
  planning/test/unimplemented_collision_checker_test.cc
  planning/test_utilities/BUILD.bazel
  planning/test_utilities/collision_checker_abstract_test_suite.cc
  planning/test_utilities/collision_checker_abstract_test_suite.h
  planning/unimplemented_collision_checker.cc
Labels: release notes: none

#18723 [planning] Further improve welded body check
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  planning/collision_checker.cc
Labels: status: squashing now, release notes: fix

#18782 [doc] Add release notes v1.13.0
  doc/_config.yml
  doc/_pages/from_binary.md
  doc/_release-notes/v1.13.0.md
Labels: status: single reviewer ok, release notes: none

#18795 [parsing] Port to parser.AddModels, part 8
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station.h
  multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
Labels: status: single reviewer ok, release notes: none

#18771 [common] Add infrastructure for fmt without ostreams
  common/BUILD.bazel
  common/copyable_unique_ptr.h
  common/fmt.h
  common/test/copyable_unique_ptr_test.cc
  common/test/fmt_test.cc
  common/test_utilities/BUILD.bazel
  common/test_utilities/fmt_format_printer.h
  common/text_logging.h
  tools/workspace/gtest/package.BUILD.bazel
  tools/workspace/gtest/patches/add_printers.patch
  tools/workspace/gtest/repository.bzl
Labels: priority: medium, release notes: newly deprecated, release notes: feature

#18752 Substitute and expand polynomial
  common/symbolic/polynomial.cc
  common/symbolic/polynomial.h
  common/symbolic/test/polynomial_test.cc
Labels: status: squashing now, release notes: feature

#18776 [parsing] Allow models to be parsed into plant from obj files
  geometry/proximity/BUILD.bazel
  geometry/proximity/obj_to_surface_mesh.cc
  geometry/proximity/obj_to_surface_mesh.h
  geometry/proximity/test/obj_to_surface_mesh_test.cc
  geometry/render/test/meshes/box.obj
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_mesh_parser.cc
  multibody/parsing/detail_mesh_parser.h
  multibody/parsing/detail_select_parser.cc
  multibody/parsing/parser.h
  multibody/parsing/test/detail_mesh_parser_test.cc
  multibody/parsing/test/parser_test.cc
Labels: release notes: feature

#18750 [pydrake] Leave C++ logging sink intact (but no-op)
  bindings/pydrake/common/text_logging_pybind.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#18805 Canonicalize fmt include spellings
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/symbolic_py_unapply.cc
  common/find_runfiles.cc
  examples/pendulum/pendulum_parameters_derivatives.cc
  examples/simple_gripper/simple_gripper.cc
  geometry/benchmarking/mesh_intersection_benchmark.cc
  geometry/benchmarking/render_benchmark.cc
  geometry/geometry_properties.h
  multibody/contact_solvers/sap/partial_permutation.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  solvers/solver_options.cc
  systems/lcm/lcm_interface_system.cc
  systems/sensors/image_writer.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#18801 [common] Add infrastructure to opt-in to fmt via ostream
  common/BUILD.bazel
  common/fmt.h
  common/fmt_ostream.h
  common/test/fmt_ostream_test.cc
  math/rigid_transform.h
  math/roll_pitch_yaw.cc
  math/roll_pitch_yaw.h
  multibody/parsing/test/detail_sdf_geometry_test.cc
Labels: release notes: feature

#18799 Move the distal geometry for the Jaco arm to link 7
  manipulation/models/jaco_description/urdf/j2s7s300_arm_sphere_collision.urdf
Labels: release notes: fix

#18798 Ignore collision filter groups from model directives if there's no scene graph
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/test/process_model_directives_test.cc
Labels: release notes: fix

#18800 Increase sleep time in collision_checker_test
  planning/test/collision_checker_test.cc
Labels: release notes: none

#18788 [workspace] Fix cpplint vs Python 3.11
  tools/workspace/styleguide/BUILD.bazel
  tools/workspace/styleguide/patches/sre_deprecation.patch
  tools/workspace/styleguide/patches/test_paths.patch
  tools/workspace/styleguide/repository.bzl
Labels: priority: low, release notes: none

#18806 Add formatter specializations throughout the codebase
  common/ad/auto_diff.h
  common/ad/internal/standard_operations.h
  common/identifier.h
  common/polynomial.h
  common/sorted_pair.h
  common/symbolic/chebyshev_basis_element.h
  common/symbolic/chebyshev_polynomial.h
  common/symbolic/expression/environment.h
  common/symbolic/expression/expression.h
  common/symbolic/expression/formula.h
  common/symbolic/expression/variable.h
  common/symbolic/expression/variables.h
  common/symbolic/generic_polynomial.h
  common/symbolic/monomial.h
  common/symbolic/monomial_basis_element.h
  common/symbolic/polynomial.h
  common/symbolic/rational_function.h
  common/type_safe_index.h
  common/yaml/BUILD.bazel
  common/yaml/yaml_io_options.h
  common/yaml/yaml_node.h
  geometry/geometry_ids.h
  geometry/geometry_properties.h
  geometry/geometry_roles.h
  geometry/proximity_properties.h
  geometry/render/render_label.h
  geometry/shape_specification.h
  math/rigid_transform.h
  multibody/inverse_kinematics/differential_inverse_kinematics.h
  multibody/math/spatial_vector.h
  multibody/parsing/package_map.h
  multibody/tree/rotational_inertia.h
  multibody/tree/spatial_inertia.h
  perception/point_cloud_flags.h
  solvers/BUILD.bazel
  solvers/binding.h
  solvers/common_solver_option.h
  solvers/evaluator_base.h
  solvers/mathematical_program.h
  solvers/mixed_integer_optimization_util.h
  solvers/mixed_integer_rotation_constraint.h
  solvers/program_attribute.h
  solvers/solution_result.h
  solvers/solver_id.h
  solvers/solver_options.h
  systems/framework/context.h
  systems/framework/vector_base.h
  systems/sensors/color_palette.h
  tools/workspace/pybind11/mkdoc.py
Labels: priority: medium, status: single reviewer ok, release notes: feature

#18819 [solvers] Add GUROBI_NUM_THREADS environment variable
  multibody/inverse_kinematics/BUILD.bazel
  solvers/BUILD.bazel
  solvers/gurobi_solver.cc
  tools/skylark/kwargs.bzl
Labels: priority: medium, release notes: feature

#18673 Enforce external upgrades in "cohorts"
  tools/workspace/gz_math_internal/repository.bzl
  tools/workspace/gz_utils_internal/repository.bzl
  tools/workspace/mypy_extensions_internal/repository.bzl
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/new_release.py
  tools/workspace/sdformat_internal/repository.bzl
  tools/workspace/usockets/repository.bzl
  tools/workspace/uwebsockets/repository.bzl
Labels: status: single reviewer ok, release notes: none

#18812 [parsing] Integrate ParsingWorkspace into Mujoco parser
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_mujoco_parser.h
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: none

#18813 [py systems] Allow scalar conversion for subclassed diagrams
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/scalar_conversion.py
  bindings/pydrake/systems/test/scalar_conversion_test.py
Labels: release notes: feature

#18810 [multibody] Replace non-space character `<0x2009>` with space
  multibody/tree/rotational_inertia.h
Labels: release notes: none

#18823 [py symbolic] Enable matrix inversions
  bindings/pydrake/symbolic_types_pybind.h
  bindings/pydrake/test/symbolic_test.py
  common/symbolic/expression/test/expression_matrix_test.cc
Labels: release notes: fix

#18811 Add fmt_eigen and use throughout for logging and errors
  common/BUILD.bazel
  common/ad/auto_diff.h
  common/fmt_eigen.h
  common/symbolic/expression/formula_cell.cc
  common/symbolic/expression/test/variable_overloading_test.cc
  common/symbolic/test/polynomial_matrix_test.cc
  common/test/fmt_eigen_test.cc
  common/yaml/test/example_structs.h
  examples/acrobot/run_lqr_w_estimator.cc
  examples/kuka_iiwa_arm/kuka_plan_runner.cc
  examples/manipulation_station/proof_of_life.cc
  geometry/optimization/test/hpolyhedron_test.cc
  geometry/proximity/plane.h
  geometry/proximity/test/characterization_utilities.cc
  geometry/proximity/test/distance_sphere_to_shape_test.cc
  geometry/proximity/test/distance_to_point_callback_test.cc
  geometry/proximity/test/mesh_half_space_intersection_test.cc
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/render_gl/test/internal_shape_meshes_test.cc
  geometry/render_gltf_client/test/internal_render_client_test.cc
  geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc
  geometry/render_vtk/internal_render_engine_vtk_base.cc
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  geometry/test/proximity_engine_test.cc
  geometry/test/shape_specification_test.cc
  manipulation/util/move_ik_demo_base.cc
  manipulation/util/robot_plan_interpolator.cc
  math/test/autodiff_test.cc
  multibody/constraint/constraint_solver.h
  multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/tree/spatial_inertia.cc
  multibody/tree/test/body_node_test.cc
  multibody/tree/test/geometry_spatial_inertia_test.cc
  multibody/tree/unit_inertia.cc
  perception/test/point_cloud_test.cc
  planning/collision_checker.cc
  planning/scene_graph_collision_checker.cc
  solvers/mathematical_program.cc
  solvers/test/equality_constrained_qp_solver_test.cc
  solvers/test/moby_lcp_solver_test.cc
  systems/analysis/test/initial_value_problem_test.cc
  systems/framework/vector_base.h
  systems/primitives/first_order_low_pass_filter.cc
  systems/primitives/gain.cc
  systems/primitives/sine.cc
  systems/sensors/camera_info.cc
Labels: priority: medium, release notes: feature

#18825 [pydrake] Correct and unify examples in pydrake docstrings
  bindings/pydrake/common/containers.py
  bindings/pydrake/common/cpp_template.py
  bindings/pydrake/common/deprecation.py
  bindings/pydrake/systems/scalar_conversion.py
Labels: priority: low, status: single reviewer ok, release notes: none

#18826 [lcm] Add SubscribeMultichannel
  bindings/pydrake/lcm_py.cc
  bindings/pydrake/test/lcm_test.py
  lcm/BUILD.bazel
  lcm/drake_lcm.cc
  lcm/drake_lcm.h
  lcm/drake_lcm_interface.h
  lcm/drake_lcm_log.cc
  lcm/drake_lcm_log.h
  lcm/drake_lcm_params.h
  lcm/test/drake_lcm_test.cc
  systems/lcm/lcm_interface_system.cc
  systems/lcm/lcm_interface_system.h
Labels: priority: high, release notes: feature

#18831 [py containers] Add nuance on `np.asarray()` for namedview
  bindings/pydrake/common/containers.py
  bindings/pydrake/common/test/containers_test.py
Labels: release notes: none

#18832 Revert "[py systems] Allow scalar conversion for subclassed diagrams …
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/scalar_conversion.py
  bindings/pydrake/systems/test/scalar_conversion_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#18809 [tutorials] Adds an example of using `namedview` in authoring leaf systems
  bindings/pydrake/common/containers.py
  bindings/pydrake/common/test/containers_test.py
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  tutorials/authoring_leaf_systems.ipynb
Labels: priority: medium, release notes: fix

#18822 Improve defaults for AffineSystem and LinearSystem
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/affine_system.cc
  systems/primitives/affine_system.h
  systems/primitives/linear_system.cc
  systems/primitives/linear_system.h
  systems/primitives/test/affine_system_test.cc
Labels: priority: medium, release notes: feature

#18838 [tools] Keep bazel analysis phase intact
  tools/bazel.rc
  tools/dynamic_analysis/bazel.rc
  tools/lint/bazel.rc
Labels: status: single reviewer ok, release notes: none

#18840 [tools] Offer --config=packaging option to build a nightly release
  tools/bazel.rc
Labels: priority: medium, release notes: none

#18793 [multibody] const InverseKinematics no longer gives mutable access to members
  multibody/inverse_kinematics/inverse_kinematics.h
Labels: status: single reviewer ok, release notes: fix

#18843 [tools] Add all models to model_visualizer's runfiles
  BUILD.bazel
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/visualization/BUILD.bazel
  examples/hardware_sim/BUILD.bazel
  examples/hydroelastic/ball_plate/BUILD.bazel
  examples/hydroelastic/python_ball_paddle/BUILD.bazel
  examples/hydroelastic/python_nonconvex_mesh/BUILD.bazel
  examples/multibody/four_bar/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#18847 [lcm] Add DrakeLcmBase
  lcm/BUILD.bazel
  lcm/drake_lcm_base.cc
  lcm/drake_lcm_base.h
  lcm/drake_lcm_interface.h
  lcm/test/drake_lcm_base_test.cc
Labels: priority: low, status: single reviewer ok, release notes: feature

#18845 [planning] Clean up ZMPPlanner
  examples/zmp/zmp_example.cc
  systems/controllers/test/zmp_planner_test.cc
  systems/controllers/test/zmp_test_util.cc
  systems/controllers/test/zmp_test_util.h
  systems/controllers/zmp_planner.cc
  systems/controllers/zmp_planner.h
Labels: release notes: newly deprecated

#18848 [lcm] Add missing include in test
  lcm/test/drake_lcm_base_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#18817 [Inverse Kinematics] Add PointToLineDistanceConstraint.
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/test/inverse_kinematics_test.py
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/inverse_kinematics/point_to_line_distance_constraint.cc
  multibody/inverse_kinematics/point_to_line_distance_constraint.h
  multibody/inverse_kinematics/point_to_point_distance_constraint.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/point_to_line_distance_constraint_test.cc
Labels: release notes: feature

#18824 [C-IRIS] move c_iris_collision_geometry out of dev folder.
  geometry/optimization/BUILD.bazel
  geometry/optimization/c_iris_collision_geometry.cc
  geometry/optimization/c_iris_collision_geometry.h
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/c_iris_separating_plane.h
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/dev/test/c_iris_test_utilities.cc
  geometry/optimization/dev/test/c_iris_test_utilities.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
  geometry/optimization/test/c_iris_collision_geometry_test.cc
  geometry/optimization/test/c_iris_test_utilities.cc
  geometry/optimization/test/c_iris_test_utilities.h
  geometry/optimization/test/convex.mtl
  geometry/optimization/test/convex.obj
Labels: release notes: feature

#18855 [geometry] Fix some fmt_eigen() stragglers
  geometry/proximity/contact_surface_utility.cc
Labels: status: single reviewer ok, release notes: none

#18856 [common] Move non-inlined TypeSafeIndex functions to the cc file
  common/BUILD.bazel
  common/type_safe_index.cc
  common/type_safe_index.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#18854 [planning] Update algorithms/planning module documentation
  doc/doxygen_cxx/doxygen.h
  multibody/inverse_kinematics/constraint_relaxing_ik.h
  multibody/inverse_kinematics/differential_inverse_kinematics.h
  multibody/inverse_kinematics/global_inverse_kinematics.h
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/optimization/static_equilibrium_problem.h
  multibody/optimization/toppra.h
  planning/body_shape_description.h
  planning/collision_avoidance.h
  planning/collision_checker.h
  planning/collision_checker_context.h
  planning/collision_checker_params.h
  planning/edge_measure.h
  planning/planning_doxygen.h
  planning/robot_clearance.h
  planning/robot_collision_type.h
  planning/robot_diagram.h
  planning/robot_diagram_builder.h
  planning/scene_graph_collision_checker.h
  planning/trajectory_optimization/direct_collocation.h
  planning/trajectory_optimization/direct_transcription.h
  planning/trajectory_optimization/integration_constraint.h
  planning/trajectory_optimization/kinematic_trajectory_optimization.h
  planning/trajectory_optimization/multiple_shooting.h
  systems/controllers/zmp_planner.h
Labels: release notes: none

#18852 [C-IRIS] move c_iris_separating_plane out of dev.
  geometry/optimization/BUILD.bazel
  geometry/optimization/c_iris_collision_geometry.h
  geometry/optimization/c_iris_separating_plane.cc
  geometry/optimization/c_iris_separating_plane.h
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/c_iris_separating_plane.cc
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.h
  geometry/optimization/test/c_iris_separating_plane_test.cc
Labels: status: single reviewer ok, release notes: feature

#18858 [hotfix] Patch missing fmt_eigen usage in debug logging
  multibody/constraint/constraint_solver.h
  solvers/unrevised_lemke_solver.cc
  systems/analysis/implicit_euler_integrator.cc
  systems/analysis/implicit_integrator.cc
  systems/analysis/radau_integrator.cc
  systems/analysis/velocity_implicit_euler_integrator.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#18853 [doc] Clarify what "support" means a bit
  doc/_pages/from_source.md
  doc/_pages/installation.md
Labels: priority: low, release notes: none

#18851 [doc] Update packaging job names in the Release Playbook
  doc/_pages/release_playbook.md
Labels: type: documentation, status: single reviewer ok, release notes: none

#18850 [workspace] Remove opt-in to FMT_DEPRECATED_OSTREAM
  bindings/pydrake/math_py.cc
  bindings/pydrake/symbolic_py.cc
  bindings/pydrake/symbolic_py_unapply.cc
  common/BUILD.bazel
  common/ad/internal/partials.cc
  common/autodiffxd.h
  common/find_runfiles.cc
  common/fmt_ostream.h
  common/symbolic/decompose.cc
  common/symbolic/expression/expression.cc
  common/symbolic/expression/formula_cell.cc
  common/symbolic/expression/variable.h
  common/test/text_logging_ostream_test.cc
  common/test/text_logging_test.cc
  common/text_logging.h
  common/trajectories/path_parameterized_trajectory.cc
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_node_test.cc
  common/yaml/yaml_read_archive.cc
  examples/pendulum/pendulum_parameters_derivatives.cc
  examples/simple_gripper/simple_gripper.cc
  geometry/geometry_properties.h
  geometry/meshcat.cc
  geometry/proximity/contact_surface_utility.cc
  geometry/render_gl/internal_opengl_context.cc
  geometry/render_gltf_client/test/internal_render_client_test.cc
  geometry/rgba.cc
  geometry/test/proximity_engine_test.cc
  math/roll_pitch_yaw.cc
  math/roll_pitch_yaw.h
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/plant/coulomb_friction.cc
  perception/point_cloud.cc
  solvers/branch_and_bound.cc
  solvers/mathematical_program.cc
  solvers/solver_options.cc
  systems/analysis/dense_output.h
  systems/sensors/image_writer.cc
  tools/install/libdrake/header_lint.bzl
  tools/skylark/pybind.bzl
  tools/workspace/fmt/repository.bzl
Labels: priority: medium, release notes: fix

#18860 [C-IRIS] move cspace_free_polytope.h out of dev folder.
  geometry/optimization/BUILD.bazel
  geometry/optimization/cspace_free_polytope.h
  geometry/optimization/dev/BUILD.bazel
  geometry/optimization/dev/cspace_free_polytope.cc
  geometry/optimization/dev/test/c_iris_test_utilities.h
  geometry/optimization/dev/test/cspace_free_polytope_test.cc
  geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Labels: status: single reviewer ok, release notes: feature

#18857 [common] Deprecate unused constants and typedefs in :essential
  bindings/pydrake/common/test/eigen_geometry_test_util_py.cc
  common/constants.h
  common/eigen_types.h
  common/symbolic/expression/formula.h
  math/cross_product.h
  math/rotation_conversion_gradient.h
  multibody/fem/test/constitutive_model_test_utilities.cc
  solvers/mathematical_program.h
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#18861 Add a benchmark on trace(A*X) where X contains symbolic variables.
  common/benchmarking/BUILD.bazel
  common/benchmarking/benchmark_polynomial.cc
Labels: status: single reviewer ok, release notes: none

#18870 Add a benchmark on Q * X while Q is sparse.
  common/benchmarking/BUILD.bazel
  common/benchmarking/benchmark_polynomial.cc
Labels: status: single reviewer ok, release notes: none

#18872 [piecewise_polynomial] Replace broken link w/ wayback URL
  common/trajectories/piecewise_polynomial.h
Labels: priority: low, status: single reviewer ok, release notes: none

#18880 [solvers] Change SolverBase constructor to prefer SolverId directly
  solvers/BUILD.bazel
  solvers/clp_solver_common.cc
  solvers/csdp_solver_common.cc
  solvers/equality_constrained_qp_solver.cc
  solvers/gurobi_solver_common.cc
  solvers/ipopt_solver_common.cc
  solvers/linear_system_solver.cc
  solvers/moby_lcp_solver.cc
  solvers/mosek_solver_common.cc
  solvers/nlopt_solver_common.cc
  solvers/osqp_solver_common.cc
  solvers/scs_solver_common.cc
  solvers/snopt_solver_common.cc
  solvers/solver_base.cc
  solvers/solver_base.h
  solvers/solver_id.cc
  solvers/solver_id.h
  solvers/test/equality_constrained_qp_solver_test.cc
  solvers/test/snopt_solver_test.cc
  solvers/test/solver_base_test.cc
  solvers/test/solver_id_test.cc
  solvers/unrevised_lemke_solver.cc
Labels: priority: medium, status: single reviewer ok, release notes: newly deprecated

#18883 [planning] Clean up of planning module documentation
  multibody/inverse_kinematics/constraint_relaxing_ik.h
  multibody/inverse_kinematics/differential_inverse_kinematics.h
  multibody/inverse_kinematics/global_inverse_kinematics.h
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/optimization/static_equilibrium_problem.h
  planning/planning_doxygen.h
Labels: status: single reviewer ok, release notes: none

#18874 [solvers] Remove redundant options copying in IpoptSolver
  solvers/ipopt_solver.cc
Labels: priority: low, release notes: fix

#18885 Revert "[visualization] Meldis displays point cloud data"
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: release notes: none

#18784 [wheel builder] Add option to validate version against PEP 440
  tools/wheel/wheel_builder/common.py
  tools/wheel/wheel_builder/main.py
Labels: release notes: none

#18864 Add SpatialInertia::PointMass()
  multibody/benchmarks/pendulum/make_pendulum_plant.cc
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: priority: medium, status: squashing now, release notes: feature

#18863 [C-IRIS] move CspaceFreePolytope constructor out of dev folder.
  geometry/optimization/BUILD.bazel
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/dev/cspace_free_polytope.cc
Labels: status: single reviewer ok, release notes: feature

#18865 Add SpatialInertial::HollowSphereWithDensity()
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: priority: medium, status: squashing now, release notes: feature

#18879 Improve error message for MbP::GetModelInstanceByName()
  multibody/tree/multibody_tree.cc
  multibody/tree/test/multibody_tree_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#18893 Add @file tag to c_iris_seaparating_plane.h doc.
  geometry/optimization/c_iris_separating_plane.h
Labels: status: single reviewer ok, release notes: none

#18869 [symbolic] Speed up Add and Mul cell ctors
  common/symbolic/expression/expression.cc
  common/symbolic/expression/expression_cell.cc
  common/symbolic/expression/expression_cell.h
  common/symbolic/expression/variable.cc
  common/symbolic/expression/variable.h
Labels: priority: medium, release notes: fix

#18894 Remove fmt::formatter of internal types from Doxygen
  common/fmt_eigen.h
  common/fmt_ostream.h
  common/yaml/yaml_node.h
  geometry/geometry_ids.h
  geometry/proximity_properties.h
Labels: priority: low, status: single reviewer ok, release notes: none

#18892 [common] Deprecate SortedPair::operator<<
  common/sorted_pair.h
  common/test/sorted_pair_test.cc
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#18873 adds Diagram tutorial
  planning/robot_diagram.h
  tutorials/BUILD.bazel
  tutorials/authoring_leaf_systems.ipynb
  tutorials/dynamical_systems.ipynb
  tutorials/index.ipynb
  tutorials/working_with_diagrams.ipynb
Labels: priority: medium, release notes: feature

#18890 [solvers] Fix a bug in GurobiSolver with duplicated variables in second-order cone constraints.
  solvers/gurobi_solver.cc
  solvers/test/csdp_solver_test.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/scs_solver_test.cc
  solvers/test/second_order_cone_program_examples.cc
  solvers/test/second_order_cone_program_examples.h
Labels: release notes: fix

#18899 [geometry] Eliminate unnecessary heap allocation in Geometry_properties
  geometry/BUILD.bazel
  geometry/geometry_properties.h
  geometry/test/geometry_properties_test.cc
Labels: status: single reviewer ok, release notes: none

#18901 [symbolic] Speed up symbolic::Variable a little bit
  common/symbolic/expression/variable.cc
  common/symbolic/expression/variable.h
Labels: priority: low, release notes: fix

#18866 Add SpatialInertia::SolidCubeWithDensity()
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: priority: medium, status: squashing now, release notes: feature

#18895 [solvers] retrieve Mosek IPM solution if basis selection is disabled for LP
  solvers/mosek_solver.cc
  solvers/test/mosek_solver_test.cc
Labels: release notes: fix

#18906 Fix csdp_solver_test on mac.
  solvers/test/csdp_solver_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none
