Repository RobotLocomotion/drake, pull requests merged in 2024-05, with the labels that each got.

#21144 Products of Lorentz and Positive Orthant Constraints.
  solvers/BUILD.bazel
  solvers/semidefinite_relaxation_internal.cc
  solvers/semidefinite_relaxation_internal.h
  solvers/test/semidefinite_relaxation_internal_test.cc
Labels: status: squashing now, release notes: none

#21373 Remove deprecated code 2024-05
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/geometry/test/optimization_test.py
  common/schema/BUILD.bazel
  common/schema/transform.cc
  common/schema/transform.h
  geometry/render/BUILD.bazel
  geometry/render/color_deprecated.h
  geometry/render/render_engine.h
  geometry/render/test/render_engine_test.cc
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render_vtk/BUILD.bazel
  geometry/test_utilities/dummy_render_engine.h
  systems/analysis/monte_carlo.cc
  systems/analysis/monte_carlo.h
  systems/analysis/test/monte_carlo_test.cc
  systems/sensors/BUILD.bazel
  systems/sensors/color_palette.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#21378 Remove repack_deb --version
  tools/release_engineering/repack_deb.py
Labels: status: single reviewer ok, release notes: none

#21389 [workspace] Upgrade boost_internal from boost-1.84.0 to boost-1.85.0
  tools/workspace/boost_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#21391 [workspace] Upgrade rules_rust to latest
  tools/workspace/rules_rust/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#21390 [workspace] Upgrade sdformat_internal to latest
  tools/workspace/sdformat_internal/patches/console.patch
  tools/workspace/sdformat_internal/repository.bzl
Labels: priority: low, status: squashing now, status: single reviewer ok, release notes: fix

#21396 [workspace] Pin the version of boost
  tools/workspace/boost_internal/repository.bzl
  tools/workspace/github.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#21392 Add MathematicalProgram::RemoveDecisionVariable.
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  common/test_utilities/symbolic_test_util.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: status: squashing now, release notes: feature

#21398 [manipulation] Purge some obsolete tools
  manipulation/BUILD.bazel
  manipulation/__init__.py
  manipulation/util/BUILD.bazel
  manipulation/util/__init__.py
  manipulation/util/convert_to_visualize_collisions.py
  manipulation/util/meshlab_to_sdf.py
  manipulation/util/show_model.py
  manipulation/util/test/meshlab_to_sdf_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#21399 Add MathematicalProgram::RemoveVisualizationCallback
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: release notes: feature

#21401 [examples] Clean up visibility and paths
  BUILD.bazel
  bindings/pydrake/examples/multibody/BUILD.bazel
  bindings/pydrake/systems/BUILD.bazel
  examples/BUILD.bazel
  examples/acrobot/optimizer_demo.py
  examples/acrobot/spong_sim.py
  examples/acrobot/test/acrobot_io_test.py
  examples/acrobot/test/metrics_test.py
  examples/acrobot/test/spong_sim_lib_py_test.py
  examples/acrobot/test/spong_sim_main_test.py
  examples/allegro_hand/BUILD.bazel
  examples/allegro_hand/joint_control/BUILD.bazel
  examples/atlas/BUILD.bazel
  examples/bead_on_a_wire/BUILD.bazel
  examples/bouncing_ball/BUILD.bazel
  examples/cubic_polynomial/BUILD.bazel
  examples/fibonacci/BUILD.bazel
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/test/hardware_sim_cc_test.py
  examples/hardware_sim/test/hardware_sim_py_test.py
  examples/hardware_sim/test/robot_commander_test.py
  examples/hydroelastic/spatula_slip_control/BUILD.bazel
  examples/kinova_jaco_arm/BUILD.bazel
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/models/BUILD.bazel
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/end_effector_teleop_sliders.py
  examples/manipulation_station/joint_teleop.py
  examples/mass_spring_cloth/BUILD.bazel
  examples/multibody/acrobot/BUILD.bazel
  examples/multibody/cart_pole/BUILD.bazel
  examples/multibody/cylinder_with_multicontact/BUILD.bazel
  examples/multibody/deformable/BUILD.bazel
  examples/multibody/four_bar/BUILD.bazel
  examples/multibody/inclined_plane_with_body/BUILD.bazel
  examples/multibody/pendulum/BUILD.bazel
  examples/multibody/rolling_sphere/BUILD.bazel
  examples/multibody/strandbeest/BUILD.bazel
  examples/planar_gripper/BUILD.bazel
  examples/quadrotor/BUILD.bazel
  examples/rod2d/BUILD.bazel
  examples/scene_graph/BUILD.bazel
  examples/simple_gripper/BUILD.bazel
  examples/zmp/BUILD.bazel
  multibody/plant/BUILD.bazel
  multibody/test_utilities/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#21395 [py symbolic] Loosen test of np.tan
  bindings/pydrake/symbolic/test/symbolic_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#21407 [workspace] Fix OpenUSD namespace
  multibody/parsing/detail_usd_parser.cc
  tools/workspace/openusd_internal/patches/namespace.patch
  tools/workspace/openusd_internal/repository.bzl
Labels: priority: medium, status: single reviewer ok, release notes: none

#21382 Add comments to RotationMatrix constructor with AngleAxis argument.
  math/rotation_matrix.h
Labels: priority: low, status: single reviewer ok, release notes: none

#21400 Implement FemModel::Clone()
  multibody/fem/dirichlet_boundary_condition.cc
  multibody/fem/dirichlet_boundary_condition.h
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
  multibody/fem/fem_model_impl.h
  multibody/fem/fem_state.cc
  multibody/fem/fem_state.h
  multibody/fem/fem_state_system.cc
  multibody/fem/fem_state_system.h
  multibody/fem/test/dummy_model.h
  multibody/fem/test/fem_model_test.cc
  multibody/fem/test/volumetric_model_test.cc
  multibody/fem/volumetric_model.h
Labels: release notes: none

#21362 [geometry] Factor recording implementation out of Meshcat
  geometry/BUILD.bazel
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/meshcat_recording_internal.cc
  geometry/meshcat_recording_internal.h
  geometry/test/meshcat_recording_internal_test.cc
  geometry/test/meshcat_test.cc
Labels: priority: medium, release notes: none

#21393 [math] Add RigidTransform (etc) factory methods without checks
  bindings/pydrake/math/math_py_monolith.cc
  bindings/pydrake/math/test/math_test.py
  math/rigid_transform.h
  math/rotation_matrix.h
  math/test/rigid_transform_test.cc
  math/test/rotation_matrix_test.cc
Labels: priority: medium, release notes: fix

#21169 Deprecate QuaternionFloatingJoint::get_position(), set_position() for get_translation(), set_translation(), etc.
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  examples/manipulation_station/manipulation_station.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/floating_body_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/ball_rpy_joint.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/quaternion_floating_mobilizer.cc
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/rpy_ball_mobilizer.cc
  multibody/tree/rpy_ball_mobilizer.h
  multibody/tree/rpy_floating_joint.h
  multibody/tree/rpy_floating_mobilizer.cc
  multibody/tree/rpy_floating_mobilizer.h
  multibody/tree/test/linear_bushing_roll_pitch_yaw_test.cc
  multibody/tree/test/quaternion_floating_joint_test.cc
  multibody/tree/test/quaternion_floating_mobilizer_test.cc
  multibody/tree/test/rpy_ball_mobilizer_test.cc
  multibody/tree/test/rpy_floating_joint_test.cc
  multibody/tree/test/rpy_floating_mobilizer_test.cc
  multibody/tree/test/universal_mobilizer_test.cc
Labels: priority: medium, release notes: newly deprecated

#21410 [workspace] Upgrade drake_models to latest commit
  tools/workspace/drake_models/repository.bzl
Labels: release notes: fix

#21411 Fall Back To Indefinite Hessian when LDLT fails.
  solvers/constraint.cc
  solvers/test/constraint_test.cc
Labels: type: bug, priority: high, release notes: fix

#21408 [workspace] Fix OpenUSD plugin loading
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_usd_parser.cc
  multibody/parsing/test/detail_usd_parser_test.cc
  multibody/parsing/test/usd_parser_test/box_plane.usda
  tools/workspace/boost_internal/BUILD.bazel
  tools/workspace/boost_internal/repository.bzl
  tools/workspace/com_github_nelhage_rules_boost_internal/BUILD.bazel
  tools/workspace/com_github_nelhage_rules_boost_internal/patches/iostreams.patch
  tools/workspace/com_github_nelhage_rules_boost_internal/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/openusd_internal/defs.bzl
  tools/workspace/openusd_internal/lock/files.bzl
  tools/workspace/openusd_internal/patches/cmake_base_vt_noboost.patch
  tools/workspace/openusd_internal/patches/dlopen_forbidden.patch
  tools/workspace/openusd_internal/patches/stage_operatoreq_cxx20.patch
  tools/workspace/openusd_internal/patches/usd_sdf_noboost.patch
  tools/workspace/openusd_internal/patches/weakptrfacade_cxx20.patch
  tools/workspace/openusd_internal/repository.bzl
Labels: priority: medium, release notes: none

#21387 [workspace] Upgrade vtk_internal to latest commit
  tools/workspace/vtk_internal/patches/mr11117.patch
  tools/workspace/vtk_internal/repository.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#21409 DeformableModel allows scalar conversion
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/multibody/deformable/bubble_gripper.cc
  examples/multibody/deformable/deformable_torus.cc
  multibody/plant/BUILD.bazel
  multibody/plant/constraint_specs.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/dummy_physical_model.cc
  multibody/plant/dummy_physical_model.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/physical_model.cc
  multibody/plant/physical_model.h
  multibody/plant/test/deformable_boundary_condition_test.cc
  multibody/plant/test/deformable_collision_filter_test.cc
  multibody/plant/test/deformable_contact_results_test.cc
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/deformable_driver_contact_test.cc
  multibody/plant/test/deformable_driver_test.cc
  multibody/plant/test/deformable_fixed_constraint_test.cc
  multibody/plant/test/deformable_integration_test.cc
  multibody/plant/test/deformable_model_test.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/plant/test/physical_model_test.cc
Labels: release notes: none

#21419 Adds DRAKE_DECLARE_COPY_AND_MOVE_AND_ASSIGN macro.
  common/drake_copyable.h
  common/test/drake_copyable_test.cc
  doc/doxygen_cxx/Doxyfile_CXX.in
  multibody/parsing/package_map.h
  multibody/topology/link_joint_graph.h
  multibody/topology/spanning_forest.h
Labels: priority: medium, status: single reviewer ok, release notes: feature

#21422 [tools] Allow XAUTHORITY in tests
  tools/bazel.rc
Labels: status: single reviewer ok, release notes: none

#21397 [multibody] Adds RemoveJoint()
  bindings/pydrake/examples/gym/named_view_helpers.py
  bindings/pydrake/multibody/jupyter_widgets.py
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  manipulation/util/robot_plan_interpolator.cc
  manipulation/util/robot_plan_utils.cc
  manipulation/util/test/robot_plan_interpolator_test.cc
  multibody/inverse_kinematics/global_inverse_kinematics.cc
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/meshcat/joint_sliders.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/sap_driver.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/kuka_iiwa_model_tests.h
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/plant/test/multibody_plant_mass_matrix_test.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/plant/test/multibody_plant_reflected_inertia_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/sap_driver_joint_limits_test.cc
  multibody/plant/test/sap_driver_test.cc
  multibody/plant/test_utilities/multibody_plant_remodeling.cc
  multibody/plant/test_utilities/multibody_plant_remodeling.h
  multibody/topology/multibody_graph.cc
  multibody/topology/multibody_graph.h
  multibody/topology/test/multibody_graph_test.cc
  multibody/tree/joint.h
  multibody/tree/multibody_element.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.cc
  planning/collision_checker.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
Labels: priority: high, release notes: breaking change, release notes: feature

#21414 Refactors SAP solver implementation
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/sap_solver.h
  multibody/contact_solvers/sap/test/sap_solver_test.cc
Labels: priority: high, release notes: none

#21426 [pybind] Add MultibodyPlant::CalcRelativeRotationMatrix.
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok, release notes: fix

#21421 SapModel caches the Hessian factorization
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/dense_supernodal_solver.cc
  multibody/contact_solvers/sap/dense_supernodal_solver.h
  multibody/contact_solvers/sap/sap_model.cc
  multibody/contact_solvers/sap/sap_model.h
  multibody/contact_solvers/sap/test/dense_supernodal_solver_test.cc
  multibody/contact_solvers/sap/test/sap_model_test.cc
Labels: priority: high, release notes: none

#21417 Discard gradients in a SAP contact problem
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/block_3x3_sparse_matrix.h
  multibody/contact_solvers/contact_configuration.h
  multibody/contact_solvers/matrix_block.h
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/expect_equal.cc
  multibody/contact_solvers/sap/expect_equal.h
  multibody/contact_solvers/sap/sap_ball_constraint.cc
  multibody/contact_solvers/sap/sap_ball_constraint.h
  multibody/contact_solvers/sap/sap_constraint.h
  multibody/contact_solvers/sap/sap_constraint_jacobian.cc
  multibody/contact_solvers/sap/sap_constraint_jacobian.h
  multibody/contact_solvers/sap/sap_contact_problem.cc
  multibody/contact_solvers/sap/sap_contact_problem.h
  multibody/contact_solvers/sap/sap_coupler_constraint.cc
  multibody/contact_solvers/sap/sap_coupler_constraint.h
  multibody/contact_solvers/sap/sap_distance_constraint.cc
  multibody/contact_solvers/sap/sap_distance_constraint.h
  multibody/contact_solvers/sap/sap_fixed_constraint.h
  multibody/contact_solvers/sap/sap_friction_cone_constraint.cc
  multibody/contact_solvers/sap/sap_friction_cone_constraint.h
  multibody/contact_solvers/sap/sap_holonomic_constraint.cc
  multibody/contact_solvers/sap/sap_holonomic_constraint.h
  multibody/contact_solvers/sap/sap_hunt_crossley_constraint.cc
  multibody/contact_solvers/sap/sap_hunt_crossley_constraint.h
  multibody/contact_solvers/sap/sap_limit_constraint.cc
  multibody/contact_solvers/sap/sap_limit_constraint.h
  multibody/contact_solvers/sap/sap_pd_controller_constraint.cc
  multibody/contact_solvers/sap/sap_pd_controller_constraint.h
  multibody/contact_solvers/sap/sap_weld_constraint.cc
  multibody/contact_solvers/sap/sap_weld_constraint.h
  multibody/contact_solvers/sap/test/sap_ball_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc
  multibody/contact_solvers/sap/test/sap_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
  multibody/contact_solvers/sap/test/sap_coupler_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_distance_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_fixed_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_hunt_crossley_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_model_test.cc
  multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_solver_test.cc
  multibody/contact_solvers/sap/test/sap_weld_constraint_test.cc
  multibody/plant/test/sap_driver_contact_constraints_test.cc
  multibody/plant/test/sap_driver_pd_controller_constraints_test.cc
Labels: priority: high, release notes: none

#21430 [sap] Avoid factoring ununitialized memory
  multibody/contact_solvers/sap/dense_supernodal_solver.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#21349 [multibody] Adds loop-breaking to MbP topology
  multibody/topology/BUILD.bazel
  multibody/topology/link_joint_graph.cc
  multibody/topology/link_joint_graph.h
  multibody/topology/link_joint_graph_defs.h
  multibody/topology/link_joint_graph_inlines.h
  multibody/topology/link_joint_graph_joint.h
  multibody/topology/link_joint_graph_link.h
  multibody/topology/spanning_forest.cc
  multibody/topology/spanning_forest.h
  multibody/topology/spanning_forest_mobod.h
  multibody/topology/test/link_joint_graph_test.cc
  multibody/topology/test/spanning_forest_test.cc
Labels: priority: medium, release notes: none

#21433 [multibody] Allow setting DiffIK solver options
  bindings/pydrake/multibody/inverse_kinematics_py_differential.cc
  bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/differential_inverse_kinematics.cc
  multibody/inverse_kinematics/differential_inverse_kinematics.h
  multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc
Labels: priority: high, release notes: feature

#21432 [tools] Fix an import missed in porting to rules_python
  tools/performance/defs.bzl
Labels: status: single reviewer ok, release notes: none

#21406 [doc] Add release notes v1.29.0
  doc/_pages/from_binary.md
  doc/_release-notes/template.txt
  doc/_release-notes/v1.29.0.md
Labels: status: squashing now, release notes: none

#21434 [solvers] Put OsqpSolver in deterministic mode by default
  solvers/osqp_solver.cc
  solvers/osqp_solver.h
  solvers/test/osqp_solver_test.cc
Labels: priority: high, release notes: fix

#21366 [geometry, multibody] Integrate scene graph configuration
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/test/scene_graph_test.py
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/simple_gripper/simple_gripper.cc
  geometry/BUILD.bazel
  geometry/benchmarking/BUILD.bazel
  geometry/benchmarking/proximity_defaults_benchmark.cc
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/scene_graph_config.cc
  geometry/scene_graph_config.h
  geometry/test/scene_graph_test.cc
  multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
  multibody/plant/multibody_plant_config_functions.cc
  multibody/plant/multibody_plant_config_functions.h
  multibody/plant/test/multibody_plant_config_functions_test.cc
  tutorials/BUILD.bazel
Labels: release notes: feature

#21442 [workspace] Upgrade drake_models to latest commit (fix plate_8in.gltf)
  tools/workspace/drake_models/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#21448 [solvers] Document more CSDP return codes
  solvers/csdp_solver.h
Labels: priority: low, release notes: none

#21451 [tools] Fix buildifier_test to not scribble in runfiles
  tools/lint/test/buildifier_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#21452 [examples] Fix some smoke test path snafus
  examples/acrobot/BUILD.bazel
  examples/acrobot/test/optimizer_demo_smoke_test.sh
  examples/allegro_hand/joint_control/BUILD.bazel
  examples/allegro_hand/joint_control/test/run_twisting_mug_test.py
Labels: priority: backlog, status: single reviewer ok, release notes: none

#21455 [render_gl] Disable multithreaded tests on Ubuntu 24.04
  geometry/render_gl/BUILD.bazel
  systems/sensors/BUILD.bazel
  tools/BUILD.bazel
  tools/skylark/drake_cc.bzl
  tools/ubuntu-jammy.bazelrc
  tools/ubuntu-noble.bazelrc
Labels: priority: high, status: single reviewer ok, release notes: none

#21449 [solvers] CsdpSolver obeys SolverOptions
  solvers/csdp_solver.cc
  solvers/test/csdp_solver_test.cc
Labels: priority: high, release notes: feature

#21444 [doc] Minor update to Release Playbook
  doc/_pages/release_playbook.md
Labels: status: single reviewer ok, release notes: none

#21440 [sap] Use C++20 'requires' syntax for double-only functions
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/sap_solver.h
Labels: priority: low, release notes: none

#21457 [tools] Disable OpenUSD on Noble
  tools/ubuntu-noble.bazelrc
Labels: priority: high, status: single reviewer ok, release notes: none

#21438 [multibody] Change "InPlace" functions to return void
  multibody/contact_solvers/sap/test/sap_ball_constraint_test.cc
  multibody/contact_solvers/sap/test/sap_fixed_constraint_test.cc
  multibody/math/spatial_acceleration.h
  multibody/math/spatial_force.h
  multibody/math/spatial_momentum.h
  multibody/math/spatial_velocity.h
  multibody/tree/articulated_body_inertia.h
  multibody/tree/multibody_tree.cc
  multibody/tree/rotational_inertia.h
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/unit_inertia.cc
  multibody/tree/unit_inertia.h
Labels: release notes: breaking change

#21453 [doc,tools] Adjust imports and libraries in prep for bzlmod
  doc/build.py
  doc/doxygen_cxx/build.py
  doc/doxygen_cxx/test/system_doxygen_test.py
  doc/pages.py
  doc/pydrake/build.py
  doc/pydrake/pydrake_sphinx_extension.py
  doc/styleguide/build.py
  tools/BUILD.bazel
  tools/install/BUILD.bazel
  tools/install/dummy/BUILD.bazel
  tools/install/installer.py
  tools/install/test/install_meta_test.py
  tools/install/test/installer_test.py
  tools/jupyter/BUILD.bazel
  tools/jupyter/__init__.py
  tools/jupyter/example.ipynb
  tools/jupyter/jupyter_py.bzl
  tools/lcm_gen/BUILD.bazel
  tools/lcm_gen/test/lcm_gen_test.py
  tools/lint/BUILD.bazel
  tools/lint/buildifier.py
  tools/lint/clang_format_includes.py
  tools/lint/clang_format_lint.py
  tools/lint/drakelint.py
  tools/lint/formatter.py
  tools/lint/python_lint.bzl
  tools/lint/test/find_data_test.py
  tools/lint/test/formatter_test.py
  tools/lint/test/util_test.py
  tools/skylark/BUILD.bazel
  tools/wheel/BUILD.bazel
  tools/wheel/macos/change_lpath.py
  tools/wheel/macos/strip_rpath.py
  tools/wheel/wheel_builder/main.py
  tools/workspace/BUILD.bazel
  tools/workspace/mirror_to_s3.py
  tools/workspace/new_release.py
  tools/workspace/openusd_internal/BUILD.bazel
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/pybind11/mkdoc.py
  tools/workspace/pybind11/mkdoc_comment.py
  tools/workspace/pybind11/test/mkdoc_comment_test.py
  tools/workspace/vendor_cxx_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#21429 Update part of mobilizer API from snake_case to CamelCase.
  multibody/plant/test/floating_body_test.cc
  multibody/tree/ball_rpy_joint.h
  multibody/tree/mobilizer.h
  multibody/tree/mobilizer_impl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/planar_joint.h
  multibody/tree/planar_mobilizer.cc
  multibody/tree/planar_mobilizer.h
  multibody/tree/prismatic_joint.h
  multibody/tree/prismatic_mobilizer.cc
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/quaternion_floating_mobilizer.cc
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/revolute_joint.h
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/rpy_ball_mobilizer.cc
  multibody/tree/rpy_ball_mobilizer.h
  multibody/tree/rpy_floating_joint.h
  multibody/tree/rpy_floating_mobilizer.cc
  multibody/tree/rpy_floating_mobilizer.h
  multibody/tree/screw_joint.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/test/free_rotating_body_plant.cc
  multibody/tree/test/planar_mobilizer_test.cc
  multibody/tree/test/prismatic_mobilizer_test.cc
  multibody/tree/test/quaternion_floating_mobilizer_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
  multibody/tree/test/rpy_ball_mobilizer_test.cc
  multibody/tree/test/rpy_floating_mobilizer_test.cc
  multibody/tree/test/screw_mobilizer_test.cc
  multibody/tree/test/tree_from_mobilizers_test.cc
  multibody/tree/test/universal_mobilizer_test.cc
  multibody/tree/universal_joint.h
  multibody/tree/universal_mobilizer.cc
  multibody/tree/universal_mobilizer.h
Labels: priority: medium, release notes: none

#21394 Add support for parsing symbolic L2 norm costs
  bindings/pydrake/math/math_py_monolith.cc
  bindings/pydrake/math/test/math_test.py
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  bindings/pydrake/symbolic/symbolic_py_monolith.cc
  bindings/pydrake/symbolic/test/symbolic_test.py
  common/symbolic/BUILD.bazel
  common/symbolic/decompose.cc
  common/symbolic/decompose.h
  common/symbolic/test/decompose_test.cc
  math/matrix_util.h
  math/quadratic_form.cc
  math/quadratic_form.h
  math/test/quadratic_form_test.cc
  solvers/create_cost.cc
  solvers/create_cost.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: priority: medium, release notes: feature

#21465 [tools] On macOS add /usr/sbin and /sbin to $PATH
  tools/macos-arch-arm64.bazelrc
  tools/macos-arch-i386.bazelrc
  tools/workspace/execute.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#21466 Enforce uniqueness of render buffers between RenderEngineGl instances
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/test/internal_render_engine_gl_test.cc
Labels: status: single reviewer ok, release notes: fix

#21469 Remove temporary DRAKE_DEMANDs
  multibody/plant/sap_driver.cc
Labels: status: single reviewer ok, release notes: none

#21468 In internal code, change mobilizer set_angle() to SetAngle().
  multibody/tree/planar_joint.h
  multibody/tree/planar_mobilizer.cc
  multibody/tree/planar_mobilizer.h
  multibody/tree/revolute_joint.h
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/screw_joint.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/test/planar_mobilizer_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
  multibody/tree/test/screw_mobilizer_test.cc
  multibody/tree/test/tree_from_mobilizers_test.cc
Labels: priority: medium, release notes: none

#21459 [GcsTrajOpt] Add nonlinear derivative bounds
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  geometry/optimization/graph_of_convex_sets.h
  planning/trajectory_optimization/BUILD.bazel
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: feature

#21454 [setup] Prune some unused macOS dependencies
  setup/mac/binary_distribution/Brewfile
  setup/mac/source_distribution/Brewfile
Labels: priority: medium, status: single reviewer ok, release notes: fix

#21480 Added nonlinear continuity constraints
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: component: planning and control, release notes: feature

#21470 Exceptions with improved error messages in SapSolver
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/plant/sap_driver.cc
Labels: status: single reviewer ok, release notes: none

#21489 Don't use lsb_release in repack_deb
  tools/release_engineering/repack_deb.py
Labels: status: single reviewer ok, release notes: none

#21486 Factor out ipopt_solver_internal.
  solvers/BUILD.bazel
  solvers/ipopt_solver.cc
  solvers/ipopt_solver_internal.cc
  solvers/ipopt_solver_internal.h
Labels: status: single reviewer ok, release notes: none

#21494 [fix] Speedup continuity test
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#21441 Unit tests support matrix for discrete MultibodyPlant models
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/test_utilities/BUILD.bazel
  multibody/test_utilities/robot_model.cc
  multibody/test_utilities/robot_model.h
Labels: release notes: none

#21491 [setup,tools] Fix Noble missing deps and Python version typo
  setup/ubuntu/binary_distribution/packages-noble.txt
  tools/install/dockerhub/noble/Dockerfile
  tools/workspace/gfortran/package.BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#21474 [systems] Drop "instantaneous" from realtime rate calculator
  geometry/BUILD.bazel
  geometry/meshcat_visualizer.h
  systems/analysis/BUILD.bazel
  systems/analysis/realtime_rate_calculator.cc
  systems/analysis/realtime_rate_calculator.h
  systems/analysis/test/realtime_rate_calculator_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#21497 Fix the uninitialized status in IpoptSolver_NLP.
  solvers/ipopt_solver_internal.h
Labels: status: single reviewer ok, release notes: none

#21492 IpoptSolver sets the sparsity parttern of the linear constraints.
  solvers/BUILD.bazel
  solvers/ipopt_solver_internal.cc
  solvers/test/ipopt_solver_internal_test.cc
Labels: release notes: feature

#21499 Set IPOPT nonlinear constraint sparsity.
  solvers/ipopt_solver_internal.cc
  solvers/test/ipopt_solver_internal_test.cc
Labels: release notes: feature

#21478 Fix Python binding for LeafSystems::DeclareAbstractOutputPort().
  bindings/pydrake/systems/framework_py_systems.cc
  systems/framework/leaf_system.cc
  systems/framework/leaf_system.h
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: fix

#21490 [planning] Bump up gcs_trajectory_optimization_test shard count
  planning/trajectory_optimization/BUILD.bazel
Labels: status: single reviewer ok, release notes: none
