Repository RobotLocomotion/drake, pull requests merged in 2024-11, with the labels that each got.

#22108 [solvers] Fix Gurobi console logging obey our defaults again
  solvers/gurobi_solver.cc
Labels: priority: high, release notes: fix

#22111 [tools] Remove unsupported apple_debug configuration
  doc/_pages/bazel.md
  doc/_pages/profiling.md
  tools/cc_toolchain/BUILD.bazel
  tools/cc_toolchain/bazel.rc
  tools/skylark/drake_cc.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#21929 Improve exception message for bad geometry in .obj file.
  geometry/BUILD.bazel
  geometry/test/bad_geometry_volume_zero.obj
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_mesh_parser.cc
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mesh_parser_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/tree/geometry_spatial_inertia.cc
  multibody/tree/geometry_spatial_inertia.h
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/geometry_spatial_inertia_test.cc
Labels: priority: medium, status: squashing now, release notes: fix, release notes: feature

#22124 Alphabetize tutorials
  tutorials/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#22074 [experimental] Implicit Graphs of Convex Sets
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/implicit_graph_of_convex_sets.cc
  geometry/optimization/implicit_graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
  geometry/optimization/test/implicit_graph_of_convex_sets_test.cc
Labels: priority: medium, release notes: feature

#22128 Hotfix for bazelisk checksum
  setup/ubuntu/source_distribution/install_bazelisk.sh
Labels: status: single reviewer ok, release notes: none

#22127 [pydrake] Make controllers test harder to pass
  bindings/pydrake/systems/test/controllers_test.py
Labels: status: single reviewer ok, release notes: none

#22101 [solvers] Reflow option classes' comments to my preferred style
  solvers/common_solver_option.h
  solvers/solver_options.h
Labels: priority: medium, release notes: none

#22117 Fix Bug Where Infeasible HPolyhedron with Few Constraints is Tagged as Unbounded
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/test/hpolyhedron_test.cc
Labels: status: squashing now, release notes: fix

#22118 [workspace] Upgrade abseil_cpp_internal to latest commit
  tools/workspace/abseil_cpp_internal/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#22084 Parallelize the generic method for checking boundedness of a convex set.
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/affine_ball.cc
  geometry/optimization/affine_ball.h
  geometry/optimization/affine_subspace.h
  geometry/optimization/cartesian_product.cc
  geometry/optimization/cartesian_product.h
  geometry/optimization/convex_hull.cc
  geometry/optimization/convex_hull.h
  geometry/optimization/convex_set.cc
  geometry/optimization/convex_set.h
  geometry/optimization/hpolyhedron.h
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/hyperrectangle.cc
  geometry/optimization/hyperrectangle.h
  geometry/optimization/intersection.cc
  geometry/optimization/intersection.h
  geometry/optimization/minkowski_sum.cc
  geometry/optimization/minkowski_sum.h
  geometry/optimization/point.h
  geometry/optimization/spectrahedron.h
  geometry/optimization/test/convex_hull_test.cc
  geometry/optimization/test/intersection_test.cc
  geometry/optimization/test/minkowski_sum_test.cc
  geometry/optimization/test/spectrahedron_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: status: squashing now, release notes: fix, release notes: feature

#22126 [pydrake] Factor out actual_ref_count() for tests
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/ref_cycle_test.py
  bindings/pydrake/common/test_utilities/BUILD.bazel
  bindings/pydrake/common/test_utilities/memory_test_util.py
  bindings/pydrake/test/memory_leak_test.py
Labels: status: single reviewer ok, release notes: none

#22090 Fix a Bug in GCS When Passing in a Trivially-Infeasible Upper Bound
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: squashing now, release notes: fix

#22125 Set gradient sparsity pattern in LorentzConeConstraint and RotatedLorentzConeConstraint.
  solvers/constraint.cc
  solvers/constraint.h
  solvers/test/constraint_test.cc
Labels: release notes: feature

#21900 [drake_gym] Add info_handler callback
  bindings/pydrake/examples/gym/envs/cart_pole.py
  bindings/pydrake/gym/_drake_gym_env.py
Labels: status: squashing now, release notes: feature

#22112 [bindings] Re-enable some gym test cases on macOS
  bindings/pydrake/examples/gym/envs/cart_pole.py
  bindings/pydrake/examples/gym/play_cart_pole.py
  bindings/pydrake/gym/test/drake_gym_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#22134 [solvers] Fix Gurobi console logging config to happen first
  solvers/gurobi_solver.cc
Labels: priority: high, release notes: none

#22136 Move the warning on small-size PSD matrix to each solver backend.
  solvers/aggregate_costs_constraints.cc
  solvers/constraint.cc
  solvers/constraint.h
  solvers/mosek_solver_internal.cc
Labels: release notes: fix

#22113 [schema] Add Rotation::Sample
  common/schema/rotation.cc
  common/schema/rotation.h
  common/schema/test/rotation_test.cc
Labels: priority: low, release notes: feature

#22102 Update parsing infrastructure
  bindings/pydrake/geometry/geometry_py_common.cc
  bindings/pydrake/geometry/test/common_test.py
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  geometry/BUILD.bazel
  geometry/geometry_roles.cc
  geometry/geometry_roles.h
  geometry/test/geometry_roles_test.cc
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: release notes: feature

#22114 Add degenerate examples to SDP test.
  solvers/test/clarabel_solver_test.cc
  solvers/test/csdp_solver_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/scs_solver_test.cc
  solvers/test/semidefinite_program_examples.cc
  solvers/test/semidefinite_program_examples.h
Labels: release notes: none

#22097 [geometry] Add precomputed values to mesh/field types
  bindings/pydrake/geometry/geometry_py_meshes.cc
  bindings/pydrake/geometry/test/meshes_test.py
  geometry/proximity/mesh_field_linear.h
  geometry/proximity/test/mesh_field_linear_test.cc
  geometry/proximity/test/volume_mesh_test.cc
  geometry/proximity/volume_mesh.cc
  geometry/proximity/volume_mesh.h
Labels: release notes: feature

#21973 [multibody] Allow Rpy floating joints for free bodies
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/floating_body_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/joint.cc
  multibody/tree/joint.h
  multibody/tree/mobilizer.cc
  multibody/tree/mobilizer.h
  multibody/tree/mobilizer_impl.cc
  multibody/tree/mobilizer_impl.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_topology.cc
  multibody/tree/multibody_tree_topology.h
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/quaternion_floating_mobilizer.cc
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/rigid_body.h
  multibody/tree/rpy_floating_mobilizer.cc
  multibody/tree/rpy_floating_mobilizer.h
  multibody/tree/test/mobilizer_tester.h
  multibody/tree/test/quaternion_floating_mobilizer_test.cc
  multibody/tree/test/rpy_floating_mobilizer_test.cc
Labels: priority: medium, release notes: feature

#22130 [workspace] Upgrade nanoflann_internal to latest release v1.6.2
  tools/workspace/nanoflann_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22148 [py perception] Add bindings for PointCloud copy
  bindings/pydrake/perception_py.cc
  bindings/pydrake/test/perception_test.py
Labels: priority: low, status: single reviewer ok, release notes: fix

#22145 Add GetFreeVariables() overload to Expression
  bindings/pydrake/symbolic/symbolic_py_monolith.cc
  bindings/pydrake/symbolic/test/symbolic_test.py
  common/symbolic/expression/expression.h
  common/symbolic/expression/test/expression_test.cc
Labels: priority: medium, release notes: none

#22099 Trim PiecewisePolynomials
  common/polynomial.h
  common/trajectories/BUILD.bazel
  common/trajectories/piecewise_polynomial.cc
  common/trajectories/piecewise_polynomial.h
  common/trajectories/test/piecewise_polynomial_test.cc
Labels: status: squashing now, release notes: feature

#22151 Adds missing sparse UpdateCoefficient binding to LinearEqualityConstaint
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: release notes: fix

#22110 [cmake] Remove buggy color and verbosity support
  CMakeLists.txt
  cmake/bazel.rc.in
  tools/install/installer.py
Labels: priority: low, release notes: none

#22149 [tools] Disable binary-only solvers in sanitizer builds
  tools/dynamic_analysis/bazel.rc
  tools/dynamic_analysis/drd.supp
  tools/dynamic_analysis/helgrind.supp
  tools/dynamic_analysis/tsan.supp
  tools/dynamic_analysis/valgrind.supp
Labels: priority: low, release notes: none

#22146 [pydrake] Add function to make arbitrary ref cycles
  bindings/pydrake/common/ref_cycle_pybind.cc
  bindings/pydrake/common/ref_cycle_pybind.h
  bindings/pydrake/common/test/ref_cycle_test.py
  bindings/pydrake/common/test/ref_cycle_test_util_py.cc
Labels: release notes: none

#22091 Add Expression Costs and Formula Constraints to Subgraphs in GcsTrajectoryOptimization
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: status: squashing now, release notes: feature

#22129 [workspace] Upgrade rules_python to 0.36.0
  tools/workspace/rules_python/repository.bzl
Labels: priority: low, status: squashing now, status: single reviewer ok, release notes: fix

#22152 Update single entry of coefficients in LinearCost and QuadraticCost.
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/test/evaluators_test.py
  solvers/cost.cc
  solvers/cost.h
  solvers/test/cost_test.cc
Labels: release notes: feature

#22142 Parallelize the Pairwise Set Intersection Checking for GCS (with or without Continuous Revolute Joints)
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  geometry/optimization/BUILD.bazel
  geometry/optimization/geodesic_convexity.cc
  geometry/optimization/geodesic_convexity.h
  geometry/optimization/test/geodesic_convexity_test.cc
Labels: status: squashing now, release notes: feature

#21965 Parallelize the GCS Preprocessing Stage
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  geometry/optimization/BUILD.bazel
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: squashing now, release notes: feature

#22143 Add tests for small-size LMI.
  solvers/test/clarabel_solver_test.cc
  solvers/test/csdp_solver_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/scs_solver_test.cc
  solvers/test/semidefinite_program_examples.cc
  solvers/test/semidefinite_program_examples.h
Labels: release notes: none

#22098 [geometry] Add surface mesh, bvh, mapping and topology to SoftGeometry and SoftMesh
  geometry/proximity/BUILD.bazel
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/hydroelastic_internal.h
  geometry/proximity/test/hydroelastic_internal_test.cc
  geometry/proximity/volume_mesh_topology.cc
  geometry/proximity/volume_mesh_topology.h
  geometry/proximity/volume_to_surface_mesh.cc
  geometry/proximity/volume_to_surface_mesh.h
Labels: release notes: none

#22167 Only update individual coefficients of the cost in ConvexSet::IsBounded.
  geometry/optimization/convex_set.cc
Labels: release notes: none

#22132 [systems] Add diagram life support
  systems/framework/diagram.cc
  systems/framework/diagram.h
  systems/framework/diagram_builder.cc
  systems/framework/diagram_builder.h
  systems/framework/test/diagram_test.cc
Labels: release notes: none

#22172 [common] Work around linker error with clang 16+
  common/eigen_types.h
Labels: status: single reviewer ok, release notes: fix

#22147 Return dual solution for PSD constraint in SCS and Clarabel.
  solvers/aggregate_costs_constraints.cc
  solvers/aggregate_costs_constraints.h
  solvers/clarabel_solver.cc
  solvers/scs_clarabel_common.cc
  solvers/scs_clarabel_common.h
  solvers/scs_solver.cc
  solvers/test/aggregate_costs_constraints_test.cc
  solvers/test/clarabel_solver_test.cc
  solvers/test/scs_solver_test.cc
Labels: release notes: feature

#22156 Python bindings for methods of GcsTrajectoryOptimization::Subgraph for adding generic costs and constraints.
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
Labels: status: single reviewer ok, release notes: feature

#22154 [py solvers] Split options bindings into their own file
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py.cc
  bindings/pydrake/solvers/solvers_py.h
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/solvers_py_options.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22165 [setup] Upgrade Python venv (mac) to latest
  geometry/test/meshcat_websocket_client.py
  setup/mac/source_distribution/requirements-build.txt
  setup/mac/source_distribution/requirements-test.txt
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#22175 [parsing] Fix a shadowed variable error in dmd parser
  multibody/parsing/detail_dmd_parser.cc
Labels: status: single reviewer ok, release notes: fix

#22137 [doc] Add release notes v1.35.0
  doc/_pages/from_binary.md
  doc/_pages/release_playbook.md
  doc/_release-notes/v1.35.0.md
Labels: status: squashing now, release notes: none

#22150 [common] Add fmt_debug_string polyfill
  common/BUILD.bazel
  common/fmt.cc
  common/fmt.h
  common/test/fmt_test.cc
Labels: priority: low, release notes: feature

#22181 [doc] Release notes 1.35.0 tweaks
  doc/_pages/from_binary.md
  doc/_release-notes/v1.35.0.md
Labels: status: single reviewer ok, release notes: none

#22184 [tools] Add single point of control for rules_java
  tools/skylark/drake_java.bzl
  tools/skylark/java.bzl
  tools/workspace/java.bzl
  tools/workspace/lcm/lcm.bzl
  tools/workspace/lcm/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#22123 Deprecate SemidefiniteRelaxationOptions flag `preserve_convex_quadratic_constraints`
  bindings/pydrake/solvers/solvers_py_semidefinite_relaxation.cc
  bindings/pydrake/solvers/test/semidefinite_relaxation_test.py
  solvers/semidefinite_relaxation.cc
  solvers/semidefinite_relaxation.h
  solvers/semidefinite_relaxation_internal.cc
  solvers/semidefinite_relaxation_internal.h
  solvers/test/semidefinite_relaxation_internal_test.cc
  solvers/test/semidefinite_relaxation_test.cc
Labels: status: squashing now, release notes: newly deprecated, release notes: fix

#22191 [math] Remove obsolete compiler workaround
  math/test/jacobian_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22180 [py solvers] Add missing options bindings
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/solvers_py_options.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: priority: medium, status: single reviewer ok, release notes: fix

#22194 Revert "Implement SpGrid for MPM"
  multibody/mpm/BUILD.bazel
  multibody/mpm/spgrid.h
  multibody/mpm/test/spgrid_test.cc
Labels: status: single reviewer ok, release notes: none

#22187 [tools] Fix some skylark deprecations
  tools/skylark/drake_cc.bzl
  tools/workspace/metadata.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#22177 Python bindings for methods of GcsTrajectoryOptimization::EdgesBetweenSubgraphs for adding generic costs and constraints.
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
Labels: status: single reviewer ok, release notes: feature

#22188 [framework] Update scalar conversion test utility
  systems/framework/test_utilities/scalar_conversion.h
Labels: release notes: fix

#22198 Restore "Implement SpGrid for MPM (#22163)"
  multibody/mpm/BUILD.bazel
  multibody/mpm/spgrid.h
  multibody/mpm/test/spgrid_test.cc
Labels: status: single reviewer ok, release notes: none

#22205 [multibody] Remove dynamic_cast from snake_case inline functions
  multibody/tree/ball_rpy_joint.h
  multibody/tree/joint.h
  multibody/tree/planar_joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/revolute_joint.h
  multibody/tree/rpy_floating_joint.h
  multibody/tree/screw_joint.h
  multibody/tree/test/multibody_tree_creation_test.cc
  multibody/tree/test/tree_from_mobilizers_test.cc
  multibody/tree/universal_joint.h
  multibody/tree/weld_joint.h
Labels: priority: low, status: single reviewer ok, release notes: none

#22202 [doc] Abandon hope for homebrew packages
  doc/_pages/installation.md
Labels: priority: low, status: single reviewer ok, release notes: none

#22207 [multibody] Move Clone helper functions to cc file
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: priority: low, status: single reviewer ok, release notes: none

#22183 [workspace] Upgrade rules_cc to 0.0.16
  tools/workspace/rules_cc/patches/rm_protobuf.patch
  tools/workspace/rules_cc/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22122 [multibody] Allow reversed weld joints
  multibody/plant/multibody_plant.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/multibody_plant_test_reverse_weld.png
  multibody/tree/multibody_tree.cc
  multibody/tree/weld_joint.cc
  multibody/tree/weld_joint.h
Labels: priority: medium, release notes: feature

#22186 [tools] Port tests to use runfiles properly
  tools/lint/BUILD.bazel
  tools/lint/buildifier.py
  tools/lint/find_data.py
  tools/lint/test/find_data_test.py
  tools/lint/test/find_data_test.txt
  tools/workspace/bazelisk/BUILD.bazel
  tools/workspace/bazelisk/test/lint_test.py
  tools/workspace/ipopt_internal_fromsource/BUILD.bazel
  tools/workspace/ipopt_internal_fromsource/test/lint_test.py
  tools/workspace/rules_python/BUILD.bazel
  tools/workspace/rules_python/test/rules_python_internal_test.py
Labels: priority: low, release notes: none

#22193 [solvers] Clean up common options doc
  solvers/common_solver_option.h
Labels: priority: low, release notes: none

#22201 Improve ExtractAndAppendVariablesFromExpression.
  common/symbolic/decompose.cc
  common/symbolic/decompose.h
  common/symbolic/test/decompose_test.cc
Labels: release notes: newly deprecated, release notes: fix

#22178 Improve error message when MbP meets unknown geometries
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_driver.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: low, release notes: fix

#22185 [tools] Prepare glob changing default to allow_empty=False
  examples/scene_graph/BUILD.bazel
  multibody/benchmarks/acrobot/BUILD.bazel
  multibody/benchmarks/free_body/BUILD.bazel
  tools/lint/bazel_lint.bzl
  tools/lint/cpplint.bzl
  tools/workspace/gurobi/package-darwin.BUILD.bazel.in
  tools/workspace/gurobi/package-linux.BUILD.bazel.in
  tools/workspace/mosek/package.BUILD.bazel
  tools/workspace/pkg_config.bzl
  tools/workspace/vtk_internal/rules.bzl
Labels: priority: low, release notes: none

#22197 [setup] Update cloud packaging for EGL
  doc/_pages/release_playbook.md
  setup/BUILD.bazel
  setup/deepnote/README.md
  setup/deepnote/install_xvfb
  setup/deepnote/xvfb
  setup/ubuntu/binary_distribution/packages-jammy.txt
  setup/ubuntu/binary_distribution/packages-noble.txt
  tools/wheel/content/INSTALLATION
Labels: priority: low, release notes: fix

#22173 Fix a bug in MosekSolver with psd matrix containing repeated entries.
  solvers/mosek_solver_internal.cc
  solvers/test/clarabel_solver_test.cc
  solvers/test/mosek_solver_internal_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/scs_solver_test.cc
  solvers/test/semidefinite_program_examples.cc
  solvers/test/semidefinite_program_examples.h
Labels: release notes: fix

#21471 [geometry] ComputeSignedDistanceToPoint from meshes
  geometry/proximity/BUILD.bazel
  geometry/proximity/calc_signed_distance_to_surface_mesh.cc
  geometry/proximity/calc_signed_distance_to_surface_mesh.h
  geometry/proximity/distance_to_point_callback.cc
  geometry/proximity/distance_to_point_callback.h
  geometry/proximity/mesh_distance_boundary.cc
  geometry/proximity/mesh_distance_boundary.h
  geometry/proximity/test/calc_signed_distance_to_surface_mesh_test.cc
  geometry/proximity/test/characterization_utilities.cc
  geometry/proximity/test/characterization_utilities.h
  geometry/proximity/test/distance_to_point_callback_test.cc
  geometry/proximity/test/distance_to_point_characterize_test.cc
  geometry/proximity/test/distance_to_shape_characterize_test.cc
  geometry/proximity/test/mesh_distance_boundary_test.cc
  geometry/proximity/test/penetration_as_point_pair_characterize_test.cc
  geometry/proximity_engine.cc
  geometry/query_object.h
  geometry/shape_specification.h
Labels: release notes: feature

#22179 Add Generic Binding<Cost> and Binding<Constraint> to vertices and edges within a GcsTrajectoryOptimization::Subgraph
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: status: squashing now, release notes: feature

#22195 [py common] Fix GIL hazard in WrapDeprecated
  bindings/pydrake/common/deprecation_pybind.h
  bindings/pydrake/common/test/deprecation_example/cc_module_py.cc
  bindings/pydrake/common/test/deprecation_example/example_class.h
  bindings/pydrake/common/test/deprecation_utility_test.py
Labels: priority: low, release notes: none

#22200 SCS and Clarabel parses scalar PSD constraint as linear constraint.
  solvers/aggregate_costs_constraints.cc
  solvers/aggregate_costs_constraints.h
  solvers/clarabel_solver.cc
  solvers/scs_clarabel_common.cc
  solvers/scs_clarabel_common.h
  solvers/scs_solver.cc
  solvers/test/aggregate_costs_constraints_test.cc
Labels: release notes: feature

#22220 Compute Minimal Representation of Degenerate VPolytopes
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: status: squashing now, release notes: fix

#22013 Introduce sdformat semantics for Drake's visual roles
  geometry/render/BUILD.bazel
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  tools/workspace/sdformat_internal/patches/upstream/support_drake_visual.patch
  tools/workspace/sdformat_internal/repository.bzl
Labels: release notes: feature

#22211 Add MathematicalProgram::AddLinearMatrixInequalityConstraint for a matrix of symbolic expressions.
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: release notes: feature

#22224 [tools] Boost kcov timeouts
  tools/dynamic_analysis/bazel.rc
Labels: status: single reviewer ok, release notes: none

#22219 Scs and Clarabel parses 2x2 PSD/LMI constraints as second order cone constraints.
  solvers/aggregate_costs_constraints.cc
  solvers/aggregate_costs_constraints.h
  solvers/clarabel_solver.cc
  solvers/scs_clarabel_common.cc
  solvers/scs_clarabel_common.h
  solvers/scs_solver.cc
  solvers/test/aggregate_costs_constraints_test.cc
  solvers/test/clarabel_solver_test.cc
  solvers/test/scs_solver_test.cc
Labels: release notes: feature

#22236 [render] Hotfix missing glob in "Differentiate visual roles ..."
  geometry/render/BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#22237 [workspace] Use built-in rules_python for Bazel >= 8
  tools/workspace/rules_python/BUILD.bazel
  tools/workspace/rules_python/repository.bzl
Labels: priority: low, release notes: fix

#22235 [tools] Accept bzlmod's spelling of local_config_cc
  tools/workspace/cc/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22234 Discourage AddPositiveSemidefiniteConstraint() for a matrix of symbolic::Expression.
  geometry/optimization/spectrahedron.cc
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/rotation_constraint.cc
  solvers/test/clarabel_solver_test.cc
  solvers/test/exponential_cone_program_examples.cc
  solvers/test/get_program_type_test.cc
  solvers/test/mathematical_program_test.cc
  solvers/test/semidefinite_program_examples.cc
Labels: release notes: breaking change, release notes: feature

#22228 Add DRAKE_ASSERT statements to ensure programs being solved in parallel are actually threadsafe.
  geometry/optimization/convex_set.cc
  geometry/optimization/geodesic_convexity.cc
  geometry/optimization/graph_of_convex_sets.cc
Labels: release notes: none

#22239 Fixes bug in IrisFromCliqueCover edge case
  planning/iris/iris_from_clique_cover.cc
  planning/iris/test/iris_from_clique_cover_test.cc
Labels: status: squashing now, release notes: fix

#22238 Mosek uses imposes linear or rotated quadratic constraint for small-size LMI constraints.
  solvers/mosek_solver_internal.cc
  solvers/mosek_solver_internal.h
Labels: release notes: feature

#22208 [multibody] Remove dynamic_cast from private inline functions
  multibody/plant/BUILD.bazel
  multibody/plant/force_density_field.h
  multibody/plant/force_density_field_declare_system_resources.cc
  multibody/plant/multibody_element_getter.cc
  multibody/tree/multibody_element.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/test/ball_rpy_joint_test.cc
  multibody/tree/test/planar_joint_test.cc
  multibody/tree/test/planar_mobilizer_test.cc
  multibody/tree/test/prismatic_joint_test.cc
  multibody/tree/test/quaternion_floating_joint_test.cc
  multibody/tree/test/quaternion_floating_mobilizer_test.cc
  multibody/tree/test/revolute_joint_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
  multibody/tree/test/rpy_floating_joint_test.cc
  multibody/tree/test/rpy_floating_mobilizer_test.cc
  multibody/tree/test/screw_joint_test.cc
  multibody/tree/test/screw_mobilizer_test.cc
  multibody/tree/test/tree_from_mobilizers_test.cc
  multibody/tree/test/universal_joint_test.cc
  multibody/tree/test/universal_mobilizer_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22246 Fixes broadcasting bug in IrisInConfigurationSpaceFromCliqueCover
  planning/iris/iris_from_clique_cover.cc
Labels: status: single reviewer ok, release notes: fix
