Repository RobotLocomotion/drake, pull requests merged in 2024-06, with the labels that each got.

#21479 [tutorials] Update advice for inertia debugging
  tutorials/authoring_multibody_simulation.ipynb
Labels: release notes: none

#21450 Export Drake version in drake-config.cmake
  CMakeLists.txt
  cmake/bazel.rc.in
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake-config.cmake.in
  tools/install/libdrake/parse_version.py
  tools/workspace/cmake_configure_file.bzl
  tools/workspace/cmake_configure_file.py
Labels: release notes: feature

#21467 Consolidates Doxygen documentation on contact modeling
  doc/doxygen_cxx/doxygen.h
  examples/multibody/rolling_sphere/populate_ball_plant.h
  geometry/geometry_file_formats_doxygen.h
  geometry/scene_graph_config.h
  multibody/hydroelastics/hydroelastic_engine.h
  multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
  multibody/parsing/parsing_doxygen.h
  multibody/plant/compliant_contact_manager.h
  multibody/plant/contact_model_doxygen.h
  multibody/plant/images/simple_contact.png
  multibody/plant/images/simple_contact.svg
  multibody/plant/multibody_plant.h
  multibody/plant/simulation_and_solvers_doxygen.h
  planning/robot_diagram_builder.h
  tutorials/hydroelastic_contact_basics.ipynb
Labels: status: squashing now, release notes: none

#21513 Fix -Wpessimizing-move
  multibody/plant/slicing_and_indexing.cc
  tools/skylark/drake_cc.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#21515 [pydrake] Add repr for SpatialInertia.Zero
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: priority: low, release notes: fix

#21511 [geometry] Update default resolution hint
  geometry/scene_graph_config.h
Labels: status: single reviewer ok, release notes: fix

#21477 [openusd_internal] Hide symbols from GNU flex output
  tools/workspace/openusd_internal/patches/usd_sdf_flex_hidden.patch
  tools/workspace/openusd_internal/repository.bzl
Labels: release notes: none

#21518 [doc] Update Linux link for buildcop cache server check
  doc/_pages/buildcop.md
Labels: status: single reviewer ok, release notes: none

#21516 Move code in frame.h and rigid_body.h to frame.cc and rigid_body.cc
  multibody/tree/frame.cc
  multibody/tree/frame.h
  multibody/tree/rigid_body.cc
  multibody/tree/rigid_body.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#21481 [tutorials] Add hydro quick-start to a tutorial
  tutorials/authoring_multibody_simulation.ipynb
Labels: release notes: none

#21517 [pydrake] Add repr for Parallelism
  bindings/pydrake/common/module_py.cc
  bindings/pydrake/common/test/module_test.py
Labels: priority: low, release notes: fix

#21503 Remove deprecated code 2024-06
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  geometry/BUILD.bazel
  geometry/scene_graph_inspector.cc
  geometry/scene_graph_inspector.h
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/shape_to_string.cc
  geometry/shape_to_string.h
  geometry/test/shape_specification_test.cc
  geometry/test/shape_to_string_test.cc
  multibody/tree/ball_rpy_joint.h
  multibody/tree/joint.h
  multibody/tree/planar_joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/revolute_joint.h
  multibody/tree/rpy_floating_joint.h
  multibody/tree/screw_joint.h
  multibody/tree/test/ball_rpy_joint_test.cc
  multibody/tree/test/planar_joint_test.cc
  multibody/tree/test/prismatic_joint_test.cc
  multibody/tree/test/quaternion_floating_joint_test.cc
  multibody/tree/test/revolute_joint_test.cc
  multibody/tree/test/rpy_floating_joint_test.cc
  multibody/tree/test/screw_joint_test.cc
  multibody/tree/test/universal_joint_test.cc
  multibody/tree/universal_joint.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#21509 [tutorials] Clarify that glTF is our preferred mesh format
  tutorials/authoring_multibody_simulation.ipynb
Labels: priority: low, release notes: none

#21527 change hpolyhedron to vpolytope linear solver
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
Labels: priority: high, status: squashing now, release notes: fix

#21525 Speed up affine hull computation.
  geometry/optimization/affine_subspace.cc
Labels: status: squashing now, release notes: feature

#21521 Bring tinygltf in as a dependency
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/tinygltf_internal/BUILD.bazel
  tools/workspace/tinygltf_internal/package.BUILD.bazel
  tools/workspace/tinygltf_internal/patches/function_pointer.patch
  tools/workspace/tinygltf_internal/patches/json.patch
  tools/workspace/tinygltf_internal/repository.bzl
Labels: release notes: feature

#21531 [examples] Fix bad habit in manipulation station
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station.h
Labels: priority: low, status: single reviewer ok, release notes: none

#21532 Strip leading zeroes from version
  tools/install/libdrake/generate_version.cmake
Labels: status: single reviewer ok, release notes: none

#21502 Add tutorial on specifying custom gradients
  tutorials/BUILD.bazel
  tutorials/custom_gradients.ipynb
  tutorials/index.ipynb
Labels: status: squashing now, release notes: feature

#21536 Bind the tolerance argument when constructing a VPolytope from an HPolyhedron.
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
Labels: status: single reviewer ok, release notes: fix

#21544 [workspace] Upgrade curl_internal to latest release 8.8.0
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/package.BUILD.bazel
  tools/workspace/curl_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#21539 [multibody] Use ContactResults for hydro forces in discrete plant unit test.
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: priority: high, release notes: none

#21548 [py visualization] Add model visualizer option for hydro type
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/_model_visualizer.py
  bindings/pydrake/visualization/model_visualizer.py
  bindings/pydrake/visualization/test/model_visualizer_test.py
Labels: priority: medium, release notes: feature

#21556 Removes the GCS trajectory optimization test from kcov builds
  planning/trajectory_optimization/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#21559 [multibody] Deny set_contact_surface_representation post-Finalize
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: priority: high, release notes: breaking change

#21384 Lower bound in GcsTrajectoryOptimization subspace constraint should be -inf.
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
Labels: status: squashing now, release notes: fix

#21540 Mute Gurobi's warning on small coefficients.
  solvers/gurobi_solver_internal.cc
Labels: release notes: feature

#21537 External upgrades - June 2024
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/bazel_skylib/repository.bzl
  tools/workspace/bazelisk/repository.bzl
  tools/workspace/buildifier/repository.bzl
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/googlebenchmark/repository.bzl
  tools/workspace/rules_python/repository.bzl
  tools/workspace/sympy_py_internal/repository.bzl
  tools/workspace/typing_extensions_internal/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#21483 Implements MultibodyPlant::GetConstraintIds()
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: medium, release notes: feature

#21558 [examples] Add bell pepper to hardware_sim
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/example_scenarios.yaml
Labels: release notes: none

#21562 [parsing] Deprecate parser.collision_filter_groups() API
  multibody/parsing/parser.h
  multibody/parsing/test/parser_manual_test.cc
  multibody/parsing/test/process_model_directives_test.cc
Labels: status: single reviewer ok, release notes: newly deprecated

#21542 [workspace] Upgrade vtk_internal to latest commit
  tools/workspace/vtk_internal/patches/nerf_pegtl.patch
  tools/workspace/vtk_internal/repository.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#21545 [workspace] Upgrade rust_toolchain, rust_rules to latest
  tools/workspace/default.bzl
  tools/workspace/rules_cc/BUILD.bazel
  tools/workspace/rules_cc/repository.bzl
  tools/workspace/rules_rust/repository.bzl
  tools/workspace/rust_toolchain/lock/archives.bzl
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: fix

#21522 Generalize RenderEngineGl's geometries and instances
  geometry/render_gl/internal_opengl_geometry.h
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/internal_shader_program.cc
  geometry/render_gl/internal_shader_program.h
  geometry/render_gl/test/internal_opengl_geometry_test.cc
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/render_gl/test/internal_shader_program_test.cc
Labels: release notes: none

#21533 [multibody] Clean up internal plant continuous time naming
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/tamsi_driver.cc
  multibody/plant/test/joint_locking_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: priority: high, release notes: none

#21564 [workspace] Upgrade rules_python to latest release 0.33.0
  tools/workspace/rules_python/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#21563 [multibody] Add MultibodyPlant::EvalSceneGraphInspector
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/contact_solvers/test/multibody_sim_driver.cc
  multibody/plant/deformable_driver.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/hydroelastic_traction_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: medium, release notes: feature

#21567 [parsing] Fix hazard in deprecated API
  multibody/parsing/parser.h
Labels: status: single reviewer ok, release notes: none

#21546 Move boxes_overlap tests from obb_test to boxes_overlap_test
  common/test_utilities/maybe_pause_for_user.cc
  common/test_utilities/maybe_pause_for_user.h
  common/test_utilities/test/maybe_pause_for_user_manual_test.cc
  common/test_utilities/test/maybe_pause_for_user_test.cc
  geometry/proximity/BUILD.bazel
  geometry/proximity/boxes_overlap.cc
  geometry/proximity/test/boxes_overlap_test.cc
  geometry/proximity/test/obb_test.cc
Labels: release notes: none

#21524 [doc] Add release notes v1.30.0
  doc/_pages/apt.md
  doc/_pages/docker.md
  doc/_pages/from_binary.md
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_pages/release_playbook.md
  doc/_release-notes/template.txt
  doc/_release-notes/v1.30.0.md
  tools/release_engineering/download_release_candidate.py
  tools/wheel/content/INSTALLATION
Labels: release notes: none

#21582 [wheel] Pin numpy to 1.x
  setup/mac/binary_distribution/requirements.txt
  tools/wheel/image/provision-python.sh
  tools/wheel/image/setup.py
Labels: priority: high, status: squashing now, status: single reviewer ok, release notes: fix

#21586 Add noble to push_release script
  tools/release_engineering/dev/push_release
Labels: status: single reviewer ok, release notes: none

#21575 [doc] Add most open source dependencies to website credits
  doc/_pages/credits.md
  tools/workspace/README.md
Labels: priority: low, status: single reviewer ok, release notes: none

#21585 [solvers] Hoist semidefinite relaxation code from anon to internal
  solvers/BUILD.bazel
  solvers/semidefinite_relaxation.cc
  solvers/semidefinite_relaxation_internal.cc
  solvers/semidefinite_relaxation_internal.h
Labels: status: squashing now, status: single reviewer ok, release notes: none

#21584 [workspace] Upgrade pybind11 to latest commit
  tools/workspace/pybind11/package.BUILD.bazel
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#21583 Use DRAKE_THROW_UNLESS for quadratic cost size check.
  solvers/cost.h
Labels: priority: high, status: single reviewer ok, release notes: fix

#21504 [GcsTrajOpt] Add Edges accessor to EdgesBetweenSubgraphs
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: priority: medium, release notes: feature

#21505 [GcsTrajOpt] Support symbolic eval of nonconvex derivative constraints
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: priority: low, release notes: feature

#21579 [solvers] Fix parsing bugs in OsqpSolver and MosekSolver
  solvers/mosek_solver_internal.cc
  solvers/osqp_solver.cc
  solvers/test/clarabel_solver_test.cc
  solvers/test/clp_solver_test.cc
  solvers/test/gurobi_solver_test.cc
  solvers/test/ipopt_solver_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/osqp_solver_test.cc
  solvers/test/quadratic_program_examples.cc
  solvers/test/quadratic_program_examples.h
  solvers/test/scs_solver_test.cc
  solvers/test/snopt_solver_test.cc
Labels: priority: high, status: squashing now, release notes: fix

#21595 [multibody] Remove some dead code during MbP time stepping
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/plant/test/sap_driver_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#21570 Enhance multibody_plant_kinematics_test.cc for subsequent PRs.
  multibody/plant/test/multibody_plant_kinematics_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#21506 [GCS] Support passing an initial_guess to SolveConvexRestriction
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: priority: medium, release notes: feature

#21529 [parsing] Fix name clash of collision filter groups
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  multibody/parsing/BUILD.bazel
  multibody/parsing/collision_filter_groups.cc
  multibody/parsing/collision_filter_groups.h
  multibody/parsing/detail_collision_filter_group_resolver.cc
  multibody/parsing/detail_collision_filter_group_resolver.h
  multibody/parsing/detail_collision_filter_groups_impl.cc
  multibody/parsing/detail_collision_filter_groups_impl.h
  multibody/parsing/detail_composite_parse.cc
  multibody/parsing/detail_composite_parse.h
  multibody/parsing/detail_instanced_name.cc
  multibody/parsing/detail_instanced_name.h
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/process_model_directives.cc
  multibody/parsing/test/collision_filter_groups_test.cc
  multibody/parsing/test/detail_collision_filter_group_resolver_test.cc
  multibody/parsing/test/detail_dmd_parser_test.cc
  multibody/parsing/test/detail_instanced_name_test.cc
  multibody/parsing/test/detail_make_model_name_test.cc
  multibody/parsing/test/detail_mesh_parser_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_select_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/detail_usd_parser_test.cc
  multibody/parsing/test/parser_manual_test.cc
  multibody/parsing/test/parser_test.cc
Labels: release notes: fix

#21587 Adds Energy Cost to KinematicTrajectoryOptimization
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/kinematic_trajectory_optimization.cc
  planning/trajectory_optimization/kinematic_trajectory_optimization.h
  planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Labels: status: squashing now, release notes: feature

#21601 Improve docstring for KinematicTrajectoryOptimization velocity constraints
  planning/trajectory_optimization/kinematic_trajectory_optimization.h
Labels: priority: low, status: single reviewer ok, release notes: none

#21610 Add bindings for systems/estimators and acrobot w/ encoders example
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/examples/examples_py_acrobot.cc
  bindings/pydrake/examples/test/acrobot_test.py
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/all.py
  bindings/pydrake/systems/estimators_py.cc
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/sensors_py.h
  bindings/pydrake/systems/sensors_py_rotary_encoders.cc
  bindings/pydrake/systems/test/estimators_test.py
  bindings/pydrake/systems/test/sensors_test.py
  systems/estimators/kalman_filter.h
  systems/estimators/luenberger_observer.h
  systems/primitives/pass_through.h
  systems/sensors/rotary_encoders.cc
  systems/sensors/rotary_encoders.h
Labels: priority: low, release notes: feature

#21602 Improve docstring for GcsOptions tribools.
  geometry/optimization/graph_of_convex_sets.h
Labels: priority: low, status: squashing now, release notes: none

#21614 [doc] Add reminder for build cops to check the build queue status
  doc/_pages/buildcop.md
Labels: status: single reviewer ok, release notes: none

#21606 [multibody] Make MbP port bookeeping boring again
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: priority: high, status: single reviewer ok, release notes: none

#21608 [multibody] Consolidate MbP geometry contact caching
  multibody/plant/BUILD.bazel
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/geometry_contact_data.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/compliant_contact_manager_tester.h
  multibody/plant/test/joint_locking_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: high, release notes: newly deprecated

#21600 [math] Use highway instead of intrinsics
  math/BUILD.bazel
  math/fast_pose_composition_functions_avx2_fma.cc
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/highway_internal/BUILD.bazel
  tools/workspace/highway_internal/patches/linkstatic.patch
  tools/workspace/highway_internal/repository.bzl
Labels: priority: high, release notes: none

#21618 [multibody] HydroelasticContactInfo<Expression> is empty
  bindings/pydrake/multibody/plant_py.cc
  geometry/proximity/polygon_surface_mesh.cc
  geometry/proximity/polygon_surface_mesh.h
  geometry/proximity/triangle_surface_mesh.cc
  geometry/proximity/triangle_surface_mesh.h
  geometry/query_results/contact_surface.cc
  geometry/query_results/contact_surface.h
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/geometry_contact_data.h
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/multibody_plant.cc
  multibody/plant/tamsi_driver.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
Labels: priority: high, release notes: breaking change

#21621 [math] Rename fast_pose_composition sources for git history
  math/BUILD.bazel
  math/fast_pose_composition_functions_wrapper.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#21609 [multibody] Rename MbP output calc functions for uniformity
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/manipulation_station/manipulation_station.cc
  examples/multibody/acrobot/passive_simulation.cc
  examples/multibody/pendulum/passive_simulation.cc
  geometry/optimization/test/c_iris_test_utilities.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/frame_kinematics_test.cc
  multibody/plant/test/multibody_plant_query_object_connect_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/plant/test/multibody_plant_test.cc
  systems/rendering/multibody_position_to_geometry_pose.cc
  visualization/inertia_visualizer.cc
Labels: priority: high, release notes: newly deprecated

#21596 [geometry] Add benchmark for internal::BoxesOverlap
  geometry/benchmarking/BUILD.bazel
  geometry/benchmarking/boxes_overlap_benchmark.cc
  geometry/proximity/BUILD.bazel
  geometry/proximity/test/boxes_overlap_test.cc
  geometry/test_utilities/BUILD.bazel
  geometry/test_utilities/boxes_overlap_transforms.cc
  geometry/test_utilities/boxes_overlap_transforms.h
Labels: release notes: none

#21590 Make prereq tickets in MbTS more precise
  multibody/tree/multibody_tree_system.cc
Labels: status: squashing now, release notes: fix

#21520 RenderEngineGl can consume glTF files
  geometry/geometry_file_formats_doxygen.h
  geometry/render/render_material.cc
  geometry/render/render_material.h
  geometry/render/render_mesh.cc
  geometry/render/test/meshes/fully_textured_pyramid_base_color.base64
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/internal_texture_library.cc
  geometry/render_gl/internal_texture_library.h
  geometry/render_gl/test/gl_fully_textured_pyramid_rendered.png
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/render_gl/test/internal_texture_library_test.cc
  geometry/render_vtk/internal_render_engine_vtk.cc
Labels: release notes: feature

#21357 MultibodyPlant adds DeformableModel by default
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/multibody/deformable/bubble_gripper.cc
  examples/multibody/deformable/deformable_torus.cc
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/dummy_physical_model.cc
  multibody/plant/dummy_physical_model.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/physical_model.cc
  multibody/plant/physical_model.h
  multibody/plant/physical_model_collection.cc
  multibody/plant/physical_model_collection.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/deformable_boundary_condition_test.cc
  multibody/plant/test/deformable_collision_filter_test.cc
  multibody/plant/test/deformable_contact_results_test.cc
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/deformable_driver_contact_test.cc
  multibody/plant/test/deformable_driver_test.cc
  multibody/plant/test/deformable_fixed_constraint_test.cc
  multibody/plant/test/deformable_integration_test.cc
  multibody/plant/test/deformable_model_test.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/plant/test/physical_model_collection_test.cc
  multibody/plant/test/physical_model_test.cc
Labels: release notes: none

#21627 [render_gl] Fix reading past end of glTF buffer
  geometry/render_gl/internal_render_engine_gl.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#21622 Add Python bindings for UnwrapToContinousTrajectory.
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
Labels: status: single reviewer ok, release notes: fix

#21628 Fix the test failure on TestSocpDuplicatedVariable3
  solvers/test/gurobi_solver_test.cc
Labels: status: single reviewer ok, release notes: none

#21569 [workspace] Upgrade tinygltf to latest release v2.8.23
  tools/workspace/tinygltf_internal/patches/function_pointer.patch
  tools/workspace/tinygltf_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#21625 [multibody] Remove unnecessary MbP includes
  multibody/plant/deformable_driver.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#21631 [framework] Offer warn_deprecated=false option on port getters
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
  systems/framework/system.h
  systems/framework/test/system_test.cc
Labels: priority: high, status: single reviewer ok, release notes: feature

#21620 [tools] Skip kcov for non-small tests
  doc/_pages/bazel.md
  tools/skylark/drake_cc.bzl
  tools/skylark/drake_py.bzl
Labels: release notes: none

#21619 [multibody] GeometryContactData takes over deformable caching
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/discrete_update_manager.h
  multibody/plant/geometry_contact_data.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: priority: medium, release notes: none

#21634 Don't (yet) require semicolons on statement-like macros
  common/default_scalars.h
  common/drake_copyable.h
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#21629 Add tolerance argument to UnwrapToContinousTrajectory.
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: fix

#21635 Add more tags to ignore to the new_release script
  tools/workspace/new_release.py
Labels: release notes: none

#21630 [geometry] Avoid slowdown of SceneGraph::GetDirectFeedthroughs()
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/scene_graph_test.cc
Labels: release notes: fix

#21589 Improve accuracy of prereq tickets in MbP
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/deformable_driver.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/sap_driver.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
  multibody/plant/test/multibody_plant_test.cc
Labels: release notes: fix

#21607 Adds CommonSolverOption::kStandaloneReproductionFileName
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/BUILD.bazel
  solvers/clarabel_solver.cc
  solvers/common_solver_option.cc
  solvers/common_solver_option.h
  solvers/solver_options.cc
  solvers/solver_options.h
  solvers/test/clarabel_solver_test.cc
  solvers/test/solver_options_test.cc
Labels: priority: medium, release notes: feature

#21612 Parse Lorentz cone constraints from formula
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  common/symbolic/decompose.cc
  common/symbolic/decompose.h
  common/symbolic/test/decompose_test.cc
  solvers/create_constraint.cc
  solvers/create_constraint.h
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/create_constraint_test.cc
  solvers/test/mathematical_program_test.cc
Labels: priority: low, release notes: feature

#21638 [multibody] Refactor MbP direct feedthrough test for usability
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#21639 [multibody] Adjust MbP declaration helpers for uniformity
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#21637 [geometry] Exempt a long test from kcov
  geometry/optimization/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#21640 [tools] Permit benchmark experiments without boost control
  tools/performance/benchmark_tool.py
Labels: priority: low, status: single reviewer ok, release notes: none
