Repository RobotLocomotion/drake, pull requests merged in 2024-10, with the labels that each got.

#21942 More Reasonable Behavior for IRIS Boundedness Check when an Initial Region is Provided
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/iris.cc
  geometry/optimization/iris.h
  geometry/optimization/test/iris_in_configuration_space_test.cc
  geometry/optimization/test/iris_test.cc
Labels: release notes: feature

#21946 Adjust GcsTrajectoryOptimization methods AddEdges and AddRegions to automatically compute edge offsets if they're not provided.
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: feature

#21951 [pydrake] Add example of memory leaks
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/memory_leak_test.py
Labels: priority: medium, release notes: none

#21980 [trajopt] Add missing bounds checks
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#21918 [py examples] Fix signatures to use Python types (not C++)
  bindings/pydrake/examples/examples_py_acrobot.cc
  bindings/pydrake/examples/examples_py_pendulum.cc
  bindings/pydrake/examples/examples_py_rimless_wheel.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#21975 Derivative Boundary conditions in Toppra::SolvePathParameterization
  bindings/pydrake/multibody/optimization_py.cc
  bindings/pydrake/multibody/test/optimization_test.py
  multibody/optimization/test/toppra_test.cc
  multibody/optimization/toppra.cc
  multibody/optimization/toppra.h
Labels: status: squashing now, release notes: feature

#21960 [multibody] Move almost all code from BodyNode to templatized BodyNodeImpl
  multibody/tree/body_node.cc
  multibody/tree/body_node.h
  multibody/tree/body_node_impl.cc
  multibody/tree/body_node_impl.h
  multibody/tree/body_node_world.h
  multibody/tree/multibody_tree.cc
  multibody/tree/test/body_node_test.cc
Labels: type: cleanup, priority: medium, release notes: none

#21983 [doc] Move Mac examples from Ventura to Sonoma
  doc/_pages/buildcop.md
  doc/_pages/code_review_checklist.md
  doc/_pages/getting_help.md
  doc/_pages/jenkins.md
Labels: status: single reviewer ok, release notes: none

#21967 [MuJoCo parser] Support "gear", "armature", and "position"
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: priority: medium, release notes: feature

#21986 [pydrake] Add more examples of memory leaks
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/memory_leak_test.py
Labels: priority: medium, release notes: none

#21990 [pydrake] Hotfix debug timeout for memory_leak_test
  bindings/pydrake/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok, release notes: none

#21970 [Mujoco Parser] Support equality "connect" constraints.
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/multibody/strandbeest/run_with_motor.cc
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/plant/constraint_specs.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/sap_driver.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/sap_driver_ball_constraints_test.cc
Labels: priority: medium, release notes: feature

#21997 [setup] Upgrade Bazel to latest release 7.3.2
  .bazeliskrc
  doc/_pages/from_source.md
Labels: status: single reviewer ok, release notes: fix

#21985 Add Hyperellipsoid::Scale() functionality
  geometry/optimization/hyperellipsoid.cc
  geometry/optimization/hyperellipsoid.h
  geometry/optimization/test/hyperellipsoid_test.cc
Labels: status: squashing now, release notes: feature

#22000 Add issue component for graphs of convex sets
  doc/_pages/issues.md
Labels: priority: medium, release notes: none, component: planning and control

#21994 [workspace] Upgrade libtiff_internal to latest release v4.7.0
  tools/workspace/libtiff_internal/package.BUILD.bazel
  tools/workspace/libtiff_internal/repository.bzl
Labels: priority: low, status: squashing now, status: single reviewer ok, release notes: fix

#21995 [workspace] Upgrade sdformat_internal, gz_utils_internal, gz_math_internal to latest
  tools/workspace/gz_math_internal/package.BUILD.bazel
  tools/workspace/gz_math_internal/repository.bzl
  tools/workspace/gz_utils_internal/repository.bzl
  tools/workspace/sdformat_internal/package.BUILD.bazel
  tools/workspace/sdformat_internal/patches/no_global_config.patch
  tools/workspace/sdformat_internal/patches/no_share_path.path
  tools/workspace/sdformat_internal/repository.bzl
  tools/workspace/sdformat_internal/test/gz_sdf_test.py
Labels: priority: low, status: squashing now, status: single reviewer ok, release notes: fix

#22002 [py multibody] Fix signatures to use Python types (not C++)
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/manipulation_py.cc
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/math_py.cc
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/tree_py.cc
Labels: priority: low, status: single reviewer ok, release notes: fix

#21953 RenderEngineGl supports in-memory meshes
  geometry/mesh_source.cc
  geometry/mesh_source.h
  geometry/render/render_material.h
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/internal_texture_library.cc
  geometry/render_gl/internal_texture_library.h
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/test/mesh_source_test.cc
Labels: release notes: feature

#21996 [workspace] Upgrade rust_toolchain, rules_rust to latest
  tools/workspace/rules_rust/repository.bzl
  tools/workspace/rust_toolchain/lock/archives.bzl
  tools/workspace/rust_toolchain/upgrade/rules_rust_tracing.patch
Labels: priority: low, status: squashing now, status: single reviewer ok, release notes: fix

#21988 Implements fail fast in DoPointInSet for VPolytopes
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
Labels: status: squashing now, release notes: fix

#21999 [workspace] Refactor python rule for maintainability
  tools/workspace/python/package.BUILD.bazel
  tools/workspace/python/repository.bzl
Labels: priority: medium, release notes: none

#21984 Move Mac packaging and wheel jobs to Sonoma
  doc/_pages/jenkins.md
  doc/_pages/release_playbook.md
  tools/release_engineering/download_release_candidate.py
Labels: release notes: none

#21993 [workspace] Upgrade curl_internal to latest release curl-8_10_1
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/repository.bzl
Labels: release notes: feature

#22001 Alphabetize issue components
  doc/_pages/issues.md
Labels: status: single reviewer ok, release notes: none

#22006 [skylark] Skip kcov on add_test_rule tests
  tools/skylark/drake_cc.bzl
  tools/skylark/drake_py.bzl
Labels: priority: low, release notes: none

#21952 Illustration supports in-memory meshes
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
  examples/scene_graph/BUILD.bazel
  examples/scene_graph/solar_system.cc
  examples/scene_graph/solar_system_run_dynamics.cc
  geometry/BUILD.bazel
  geometry/drake_visualizer.cc
  geometry/meshcat.cc
  geometry/meshcat_internal.cc
  geometry/meshcat_internal.h
  geometry/test/drake_visualizer_test.cc
  geometry/test/meshcat_internal_test.cc
  geometry/test/meshcat_manual_test.cc
  geometry/test/meshcat_test.cc
  lcmtypes/lcmt_viewer_geometry_data.lcm
Labels: release notes: feature

#21950 Planar scene graph visualizer updated
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
Labels: release notes: feature

#22010 [trajectories] Add GSG-required out-of-line destructors
  common/trajectories/bezier_curve.cc
  common/trajectories/bezier_curve.h
  common/trajectories/bspline_trajectory.cc
  common/trajectories/bspline_trajectory.h
  common/trajectories/composite_trajectory.cc
  common/trajectories/composite_trajectory.h
  common/trajectories/discrete_time_trajectory.cc
  common/trajectories/discrete_time_trajectory.h
  common/trajectories/exponential_plus_piecewise_polynomial.cc
  common/trajectories/exponential_plus_piecewise_polynomial.h
  common/trajectories/path_parameterized_trajectory.cc
  common/trajectories/path_parameterized_trajectory.h
  common/trajectories/piecewise_polynomial.cc
  common/trajectories/piecewise_polynomial.h
  common/trajectories/piecewise_pose.cc
  common/trajectories/piecewise_pose.h
  common/trajectories/piecewise_quaternion.cc
  common/trajectories/piecewise_quaternion.h
  common/trajectories/piecewise_trajectory.cc
  common/trajectories/piecewise_trajectory.h
  common/trajectories/trajectory.cc
  common/trajectories/trajectory.h
Labels: priority: low, status: single reviewer ok, release notes: fix

#22008 [render_gltf_client] Actually test something in the acceptance test
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/test/acceptance_test.py
  geometry/render_gltf_client/test/client_demo.cc
Labels: priority: high, release notes: none

#22011 [render_gltf_client] Fix defective glTF input in acceptance test
  geometry/render_gltf_client/test/acceptance_test.py
  tools/workspace/vtk_internal/patches/io_geometry_gltf_default_scene.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#21954 RenderEngineVtk (and GltfClient) support in-memory meshes
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_merge_gltf.cc
  geometry/render_gltf_client/internal_merge_gltf.h
  geometry/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render_gltf_client/internal_render_engine_gltf_client.h
  geometry/render_gltf_client/test/internal_merge_gltf_test.cc
  geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  tools/workspace/vtk_internal/patches/gltf_importer_from_stream.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: release notes: feature

#22004 [doc] Remove official support of macOS 13 (Ventura)
  .github/ISSUE_TEMPLATE/BUG.yml
  doc/_pages/from_source.md
  doc/_pages/installation.md
  tools/wheel/wheel_builder/macos.py
Labels: release notes: fix

#22018 Remove inline destructor in solvers folder.
  solvers/constraint.cc
  solvers/constraint.h
  solvers/cost.cc
  solvers/cost.h
  solvers/evaluator_base.cc
  solvers/evaluator_base.h
  solvers/ipopt_solver_internal.cc
  solvers/ipopt_solver_internal.h
  solvers/minimum_value_constraint.cc
  solvers/minimum_value_constraint.h
Labels: status: single reviewer ok, release notes: fix

#22012 [cmake] Use new mode to find python for pybind11
  tools/workspace/pybind11/package.BUILD.bazel
  tools/workspace/pybind11/pybind11-config.cmake
Labels: status: single reviewer ok, release notes: fix

#22003 [multibody] Move mass matrix computation to body_node_impl for speed
  multibody/tree/BUILD.bazel
  multibody/tree/body_node.cc
  multibody/tree/body_node.h
  multibody/tree/body_node_impl.cc
  multibody/tree/body_node_impl.h
  multibody/tree/body_node_impl_mass_matrix.cc
  multibody/tree/body_node_world.h
  multibody/tree/multibody_tree.cc
  multibody/tree/test/body_node_test.cc
Labels: priority: medium, type: performance, release notes: none

#22005 Added method to set x(n) in the context for vector-valued ZeroOrderHold
  bindings/pydrake/systems/primitives_py.cc
  systems/primitives/test/zero_order_hold_test.cc
  systems/primitives/zero_order_hold.cc
  systems/primitives/zero_order_hold.h
Labels: release notes: feature

#22023 Move AddPositiveSemidefiniteConstraint implementation to cc file.
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
Labels: status: single reviewer ok, release notes: none

#21881 Deprecate Mesh and Convex::filename() method (in favor of source())
  bindings/pydrake/geometry/geometry_py_common.cc
  bindings/pydrake/geometry/test/common_test.py
  geometry/shape_specification.h
  geometry/test/geometry_state_test.cc
  geometry/test/proximity_engine_test.cc
  geometry/test/shape_specification_test.cc
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/tree/geometry_spatial_inertia.cc
Labels: priority: medium, release notes: newly deprecated, release notes: feature

#22021 Do not convert an int to a bool in Python binding of Meshcat::SetProperty
  bindings/pydrake/geometry/geometry_py_visualizers.cc
  bindings/pydrake/geometry/test/visualizers_test.py
Labels: status: single reviewer ok, release notes: fix

#22034 Add new GCS tag to platform reviewer checklist
  doc/_pages/platform_reviewer_checklist.md
Labels: status: single reviewer ok, release notes: none

#22020 [multibody] Fix NaN in body_spatial_acceleration output
  multibody/plant/multibody_plant.cc
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
Labels: release notes: fix

#21894 [workspace] Upgrade vtk_internal to latest commit
  geometry/render_gltf_client/test/server_vtk_backend.cc
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/internal_make_render_window.cc
  geometry/render_vtk/internal_make_render_window.h
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/test/internal_render_engine_vtk_no_display_test.cc
  tools/dynamic_analysis/valgrind.supp
  tools/workspace/vtk_internal/gen/README.md
  tools/workspace/vtk_internal/gen/vtkRenderingOpenGL2ObjectFactory.cxx
  tools/workspace/vtk_internal/gen/vtkRenderingOpenGL2ObjectFactory.h
  tools/workspace/vtk_internal/package.BUILD.bazel
  tools/workspace/vtk_internal/patches/disable_static_destructors.patch
  tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch
  tools/workspace/vtk_internal/patches/mr11117.patch
  tools/workspace/vtk_internal/patches/rendering_opengl2_no_factory.patch
  tools/workspace/vtk_internal/patches/vtkglew_hidden.patch
  tools/workspace/vtk_internal/repository.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: high, release notes: fix

#22028 [visualization] Fix meshcat control deletion paths
  bindings/pydrake/geometry/geometry_py_visualizers.cc
  bindings/pydrake/geometry/test/visualizers_test.py
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/test/meshcat_test.cc
  multibody/meshcat/joint_sliders.cc
  visualization/meshcat_pose_sliders.cc
Labels: release notes: fix, release notes: feature

#22025 [render_vtk] New option to choose EGL instead of GLX
  geometry/render_gltf_client/test/server_vtk_backend.cc
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/internal_make_render_window.cc
  geometry/render_vtk/internal_make_render_window.h
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/render_engine_vtk_params.cc
  geometry/render_vtk/render_engine_vtk_params.h
  geometry/render_vtk/test/internal_render_engine_vtk_no_display_test.cc
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  geometry/render_vtk/test/render_engine_vtk_params_test.cc
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: high, release notes: feature

#22037 [pydrake] Add dynamic_attr support to cpp_template_pybind
  bindings/pydrake/common/cpp_template_pybind.h
  bindings/pydrake/common/test/cpp_template_pybind_test.cc
Labels: priority: medium, release notes: none

#21987 Doxygen on how to estimate hydroelastic forces and parameters
  multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
  multibody/plant/contact_model_doxygen.h
  multibody/plant/hydroelastic_parameters_doxygen.h
  multibody/plant/images/elastic_foundation.svg
  multibody/plant/images/hydro_analytic.svg
Labels: release notes: none

#22035 Remove an obsolete test from GCS.
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: status: squashing now, release notes: none

#22036 Use venv for Python dependencies (macOS)
  cmake/WORKSPACE.in
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/binary_distribution/requirements.txt
  setup/mac/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  setup/mac/source_distribution/requirements-build.in
  setup/mac/source_distribution/requirements-build.txt
  setup/mac/source_distribution/requirements-test-only.txt
  setup/mac/source_distribution/requirements-test.in
  setup/mac/source_distribution/requirements-test.txt
  setup/mac/source_distribution/requirements.txt
  tools/install/BUILD.bazel
  tools/install/install_test.py
  tools/jupyter/BUILD.bazel
  tools/jupyter/test/jupyter_notebook_test.py
  tools/skylark/py.bzl
  tools/wheel/macos/build-wheel.sh
  tools/workspace/python/package.BUILD.bazel
  tools/workspace/python/repository.bzl
  tools/workspace/python/venv_expunge
  tools/workspace/python/venv_sync
  tools/workspace/python/venv_upgrade
Labels: priority: high, release notes: feature

#21956 [doc] Add release notes v1.34.0
  doc/_pages/from_binary.md
  doc/_pages/installation.md
  doc/_pages/stable.md
  doc/_release-notes/end_of_support.md
  doc/_release-notes/v1.34.0.md
Labels: status: single reviewer ok, release notes: none

#22047 Silence erroneous VTK warning
  tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch
Labels: status: single reviewer ok, release notes: none

#22056 [doc] Adjust deepnote deployment instructions
  doc/_pages/release_playbook.md
Labels: priority: low, status: single reviewer ok, release notes: none

#22050 Teach venv_upgrade to commit changes
  tools/workspace/new_release.py
  tools/workspace/python/venv_upgrade
Labels: release notes: none

#22058 Clarify VTK shadow documentation
  geometry/render_vtk/render_engine_vtk_params.h
Labels: status: single reviewer ok, release notes: none

#22057 Bug fixes for holonomic and weld constraints
  multibody/contact_solvers/sap/sap_holonomic_constraint.cc
  multibody/plant/sap_driver.cc
  multibody/plant/test/sap_driver_weld_constraints_test.cc
Labels: status: squashing now, release notes: fix

#22063 [workspace] Force-disable CoinUtils debugging hooks
  tools/workspace/coinutils_internal/defs.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#22062 [solvers] Throw when IpoptSolver options are invalid
  solvers/BUILD.bazel
  solvers/ipopt_solver.cc
  solvers/test/ipopt_solver_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#22043 [solvers] Add SpecificOptions sugar for solvers to map their options
  solvers/BUILD.bazel
  solvers/common_solver_option.h
  solvers/specific_options.cc
  solvers/specific_options.h
  solvers/test/specific_options_test.cc
Labels: priority: low, release notes: none

#22014 [multibody] Speed up inverse dynamics by exploiting new templatized code
  multibody/tree/body_node.cc
  multibody/tree/body_node.h
  multibody/tree/body_node_impl.cc
  multibody/tree/body_node_impl.h
  multibody/tree/body_node_world.h
  multibody/tree/mobilizer_impl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/planar_mobilizer.cc
  multibody/tree/planar_mobilizer.h
  multibody/tree/prismatic_mobilizer.cc
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/quaternion_floating_mobilizer.cc
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/rpy_ball_mobilizer.cc
  multibody/tree/rpy_ball_mobilizer.h
  multibody/tree/rpy_floating_mobilizer.cc
  multibody/tree/rpy_floating_mobilizer.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/test/body_node_test.cc
  multibody/tree/universal_mobilizer.cc
  multibody/tree/universal_mobilizer.h
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: type: cleanup, priority: medium, type: performance, release notes: none

#22053 Restore RenderEngineVtk MultiMaterialObject test for EGL
  geometry/render/test/meshes/rainbow_stripes.png
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  geometry/render_vtk/test/multi_material_mesh.png
Labels: release notes: none

#22067 Cross references margin documentation in DefaultProximityProperties
  geometry/scene_graph_config.h
Labels: status: single reviewer ok, release notes: none

#22066 [setup] Upgrade Bazel to latest release 7.4.0
  .bazeliskrc
  doc/_pages/from_source.md
Labels: priority: low, status: single reviewer ok, release notes: fix

#22059 [bindings] Update memory leak test
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/memory_leak_test.py
Labels: priority: high, release notes: none

#21093 Implements FunctionHandleTrajectory
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/BUILD.bazel
  common/trajectories/function_handle_trajectory.cc
  common/trajectories/function_handle_trajectory.h
  common/trajectories/test/function_handle_trajectory_test.cc
Labels: priority: low, status: do not review, release notes: feature

#22072 [multibody] Templatize internal types QVector, VVector, HMatrix
  multibody/tree/body_node_impl.cc
  multibody/tree/body_node_impl.h
  multibody/tree/mobilizer_impl.h
  multibody/tree/planar_mobilizer.h
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/quaternion_floating_mobilizer.cc
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/revolute_mobilizer.h
  multibody/tree/rpy_ball_mobilizer.h
  multibody/tree/rpy_floating_mobilizer.h
  multibody/tree/screw_mobilizer.h
  multibody/tree/universal_mobilizer.h
  multibody/tree/weld_mobilizer.h
Labels: type: cleanup, priority: medium, status: single reviewer ok, release notes: none

#21345 [solvers] Port solver back-ends to use SpecificOptions
  solvers/BUILD.bazel
  solvers/clarabel_solver.cc
  solvers/clarabel_solver.h
  solvers/clp_solver.cc
  solvers/clp_solver.h
  solvers/csdp_solver.cc
  solvers/csdp_solver.h
  solvers/equality_constrained_qp_solver.cc
  solvers/equality_constrained_qp_solver.h
  solvers/gurobi_solver.cc
  solvers/gurobi_solver.h
  solvers/ipopt_solver.cc
  solvers/ipopt_solver.h
  solvers/mosek_solver.cc
  solvers/mosek_solver.h
  solvers/mosek_solver_internal.cc
  solvers/mosek_solver_internal.h
  solvers/nlopt_solver.cc
  solvers/nlopt_solver.h
  solvers/no_clarabel.cc
  solvers/no_clp.cc
  solvers/no_csdp.cc
  solvers/no_gurobi.cc
  solvers/no_ipopt.cc
  solvers/no_mosek.cc
  solvers/no_nlopt.cc
  solvers/no_osqp.cc
  solvers/no_scs.cc
  solvers/no_snopt.cc
  solvers/osqp_solver.cc
  solvers/osqp_solver.h
  solvers/scs_solver.cc
  solvers/scs_solver.h
  solvers/snopt_solver.cc
  solvers/snopt_solver.h
  solvers/solver_base.cc
  solvers/solver_base.h
  solvers/test/clarabel_solver_test.cc
  solvers/test/csdp_solver_test.cc
  solvers/test/equality_constrained_qp_solver_test.cc
  solvers/test/mosek_solver_test.cc
  solvers/test/snopt_solver_test.cc
  solvers/test/solver_base_test.cc
Labels: priority: medium, release notes: none

#21957 Solve mathematical programs in parallel
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/BUILD.bazel
  solvers/ipopt_solver.h
  solvers/solve.cc
  solvers/solve.h
  solvers/test/optimization_examples.cc
  solvers/test/solve_in_parallel_test.cc
Labels: status: squashing now, release notes: feature

#22079 [solvers] Add CommonSolverOption::to_string
  solvers/common_solver_option.cc
  solvers/common_solver_option.h
  solvers/test/solver_options_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: newly deprecated, release notes: feature

#22080 [solvers] Hotfix for fmt errors
  solvers/mosek_solver_internal.cc
  solvers/nlopt_solver.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#22068 [bindings] Add custom ref_cycle annotation
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/ref_cycle_pybind.cc
  bindings/pydrake/common/ref_cycle_pybind.h
  bindings/pydrake/common/test/ref_cycle_test.py
  bindings/pydrake/common/test/ref_cycle_test_util_py.cc
Labels: release notes: none

#22071 Remove the 2x2 psd matrix constraint with larger psd matrix.
  solvers/test/mosek_solver_test.cc
  solvers/test/semidefinite_program_examples.cc
  solvers/test/semidefinite_program_examples.h
Labels: release notes: none

#22081 [render_vtk] Use EGL by default on Ubuntu
  bindings/pydrake/geometry/BUILD.bazel
  bindings/pydrake/visualization/test/multicam_scenario.yaml
  common/test_utilities/BUILD.bazel
  examples/kuka_iiwa_arm/BUILD.bazel
  geometry/benchmarking/BUILD.bazel
  geometry/render/render_camera.h
  geometry/render_gl/BUILD.bazel
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/factory.h
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/render_engine_vtk_params.cc
  geometry/render_vtk/render_engine_vtk_params.h
  geometry/render_vtk/test/render_engine_vtk_params_test.cc
  systems/sensors/BUILD.bazel
  systems/sensors/camera_config.h
  tools/bazel.rc
  tools/lint/BUILD.bazel
  tools/performance/defs.bzl
  tools/skylark/README.md
  tools/skylark/drake_cc.bzl
  tools/skylark/drake_py.bzl
  tools/skylark/drake_sh.bzl
  tools/skylark/kwargs.bzl
Labels: priority: low, release notes: fix

#22082 [workspace] Upgrade openusd_internal to latest release 24.11
  tools/workspace/openusd_internal/lock/files.bzl
  tools/workspace/openusd_internal/package.BUILD.bazel
  tools/workspace/openusd_internal/patches/nanocolor_namespace.patch
  tools/workspace/openusd_internal/patches/upstream/nanocolor_namespace.patch
  tools/workspace/openusd_internal/patches/upstream/usd_utils_include.patch
  tools/workspace/openusd_internal/patches/usd_sdf_flex_hidden.patch
  tools/workspace/openusd_internal/repository.bzl
  tools/workspace/openusd_internal/upgrade.py
Labels: priority: low, release notes: fix

#22094 [math] Add requires clause to RigidTransform and RotationMatrix cast
  common/default_scalars.h
  geometry/render_gl/internal_render_engine_gl.cc
  math/rigid_transform.h
  math/rotation_matrix.h
  perception/depth_image_to_point_cloud.cc
Labels: priority: low, release notes: fix

#22077 Use the preprocessing solver options even if a specific preprocessing solver is not specified.
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: fix

#22096 [solvers] Opt-in to clang-format-lint
  solvers/BUILD.bazel
  solvers/create_constraint.cc
  solvers/create_cost.h
  solvers/evaluator_base.cc
  solvers/mathematical_program.h
  solvers/solver_base.h
  solvers/test/clarabel_solver_test.cc
  solvers/test/cost_test.cc
  solvers/test/create_constraint_test.cc
  solvers/test/osqp_solver_test.cc
  solvers/test/semidefinite_relaxation_internal_test.cc
  solvers/test/snopt_solver_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22092 Correct VTK header generation from binary files
  tools/workspace/vtk_internal/BUILD.bazel
  tools/workspace/vtk_internal/data_to_header.py
  tools/workspace/vtk_internal/package.BUILD.bazel
  tools/workspace/vtk_internal/rules.bzl
  tools/workspace/vtk_internal/test/data_to_header_test.cc
Labels: release notes: none

#22086 Remove deprecated code 2024-11 🎃
  bindings/pydrake/geometry/geometry_py_visualizers.cc
  bindings/pydrake/geometry/test/visualizers_test.py
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  geometry/meshcat_visualizer.h
  geometry/test/meshcat_visualizer_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_driver.cc
  multibody/plant/hydroelastic_contact_info.cc
  multibody/plant/hydroelastic_contact_info.h
  multibody/tree/geometry_spatial_inertia.h
  systems/framework/test/vector_system_test.cc
  systems/framework/vector_system.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#22103 [workspace] Upgrade drake_models to latest commit
  tools/workspace/drake_models/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22095 [common] Simplify fmt_eigen implementation
  common/fmt_eigen.cc
  common/fmt_eigen.h
  common/test/fmt_eigen_test.cc
  common/test_utilities/eigen_printer.h
Labels: release notes: none

#22106 [geometry] Fix refine_mesh for cwd-relative paths
  geometry/proximity/refine_mesh.cc
Labels: priority: low, status: single reviewer ok, release notes: fix
