Repository RobotLocomotion/drake, pull requests merged in 2024-07, with the labels that each got.

#21652 [tools] Disable code coverage on benchmarks
  tools/performance/defs.bzl
Labels: priority: medium, status: single reviewer ok, release notes: none

#21633 [geometry] Add more detail to a diffuse_map warning message
  geometry/geometry_state.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#21616 Implement USD Rigidbody Parser
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_select_parser.cc
  multibody/parsing/detail_usd_geometry.cc
  multibody/parsing/detail_usd_geometry.h
  multibody/parsing/detail_usd_parser.cc
  multibody/parsing/detail_usd_parser.h
  multibody/parsing/detail_usd_parser_off.cc
  multibody/parsing/test/detail_usd_parser_test.cc
  multibody/parsing/test/usd_parser_test/box_plane.usda
  multibody/parsing/test/usd_parser_test/invalid/invalid_file.usd
  multibody/parsing/test/usd_parser_test/simple_geometries.usda
  tools/install/libdrake/test/exported_symbols_test.py
  tools/workspace/openusd_internal/lock/files.bzl
  tools/workspace/openusd_internal/package.BUILD.bazel
  tools/workspace/openusd_internal/patches/00_work_thread_limits_namespace.patch
  tools/workspace/openusd_internal/patches/pegtl_namespace.patch
  tools/workspace/openusd_internal/repository.bzl
  tools/workspace/openusd_internal/upgrade.py
Labels: release notes: none

#21649 Add mujoco_menagerie as a test-only dependency
  multibody/parsing/BUILD.bazel
  multibody/parsing/test/detail_mujoco_parser_test.cc
  tools/workspace/default.bzl
  tools/workspace/mujoco_menagerie_internal/BUILD.bazel
  tools/workspace/mujoco_menagerie_internal/package.BUILD.bazel
  tools/workspace/mujoco_menagerie_internal/repository.bzl
Labels: priority: medium, status: single reviewer ok, release notes: fix

#21658 Fix Segmentation Fault in GcsTrajectoryOptimization::AddRegions
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: priority: high, release notes: fix

#21641 Specify Separate Solver and SolverOptions for GCS Preprocessing
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/BUILD.bazel
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: feature

#21642 [geometry] Exempt a long test from kcov
  geometry/optimization/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#21654 Use DRAKE_THROW_UNLESS in cost/constraint
  solvers/constraint.cc
  solvers/constraint.h
  solvers/cost.cc
  solvers/cost.h
Labels: status: single reviewer ok, release notes: none

#21651 Remove deprecated code 2024-07
  BUILD.bazel
  tools/install/bazel/BUILD.bazel
  tools/install/bazel/README.md
  tools/install/bazel/drake.BUILD.bazel
  tools/install/bazel/drake__bindings__pydrake.BUILD.bazel
  tools/install/bazel/drake__common.BUILD.bazel
  tools/install/bazel/drake__examples.BUILD.bazel
  tools/install/bazel/drake__geometry.BUILD.bazel
  tools/install/bazel/drake__manipulation.BUILD.bazel
  tools/install/bazel/drake__multibody.BUILD.bazel
  tools/install/bazel/generate_installed_files_manifest.bzl
  tools/install/bazel/repo_gen.py
  tools/install/bazel/repo_template.bzl
  tools/install/bazel/test/drake_bazel_installed_test.py
  tools/workspace/mosek/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#21626 [math] Use dynamic dispatch for highway SIMD
  common/BUILD.bazel
  common/hwy_dynamic.cc
  common/hwy_dynamic.h
  common/hwy_dynamic_impl.h
  common/test/hwy_dynamic_test.cc
  common/test/hwy_dynamic_test_array_mul.cc
  common/test/hwy_dynamic_test_array_mul.h
  math/BUILD.bazel
  math/fast_pose_composition_functions.h
  math/fast_pose_composition_functions_avx2_fma.cc
  math/fast_pose_composition_functions_avx2_fma.h
  math/fast_pose_composition_functions_wrapper.cc
  math/test/fast_pose_composition_functions_test.cc
  multibody/plant/test/multibody_plant_mass_matrix_test.cc
  tools/skylark/drake_cc.bzl
  tools/workspace/highway_internal/patches/linkstatic.patch
  tools/workspace/highway_internal/patches/target_update_noinline.patch
  tools/workspace/highway_internal/repository.bzl
Labels: priority: low, release notes: none

#21664 [framework] Add ExecuteForcedEvents() to System API
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  systems/framework/system.cc
  systems/framework/system.h
  systems/framework/test/leaf_system_test.cc
Labels: priority: medium, release notes: feature

#21650 [GCS] Support use_in_transcription in AddCost.
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: priority: medium, release notes: feature

#21679 [DiffIkIntegrator] Update docstring port name X_WE => X_AE.
  multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#21665 [Mujoco parser] Don't call CalcSpatialInertia unless needed
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  tools/workspace/mujoco_menagerie_internal/package.BUILD.bazel
Labels: priority: medium, release notes: fix

#21680 [multibody] Avoid per-function template specialization
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#21660 [multibody] Clarify some docs, and other cleanups
  multibody/plant/multibody_plant.cc
  multibody/tree/joint_actuator.h
  multibody/tree/mobilizer.h
Labels: priority: low, status: single reviewer ok, release notes: none

#21685 [multibody] Add ContactResults non-default constructor
  bindings/pydrake/multibody/plant_py.cc
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/test/contact_results_test.cc
Labels: priority: high, status: single reviewer ok, release notes: feature

#21690 [pydrake] Remove vestigial build details
  bindings/pydrake/examples/gym/BUILD.bazel
  bindings/pydrake/gym/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#21689 [multibody] Adjust contact results targets for uniformity
  multibody/plant/BUILD.bazel
  multibody/plant/test/hydroelastic_contact_info_test.cc
  multibody/plant/test/hydroelastic_traction_calculator_test.cc
Labels: priority: high, status: single reviewer ok, release notes: newly deprecated

#21688 [planning] Improve direct transcription error messages
  planning/trajectory_optimization/BUILD.bazel
  planning/trajectory_optimization/direct_transcription.cc
  planning/trajectory_optimization/test/direct_transcription_test.cc
Labels: priority: medium, release notes: none

#21683 [multibody] ContactResults no longer reports quadrature data
  lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm
  multibody/plant/contact_results_to_lcm.cc
  multibody/plant/discrete_update_manager.cc
  multibody/plant/hydroelastic_contact_info.cc
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/hydroelastic_quadrature_point_data.h
  multibody/plant/hydroelastic_traction_calculator.cc
  multibody/plant/hydroelastic_traction_calculator.h
  multibody/plant/multibody_plant.cc
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/contact_results_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/hydroelastic_contact_info_test.cc
  multibody/plant/test/hydroelastic_traction_calculator_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: priority: high, release notes: breaking change, release notes: newly deprecated

#21692 [multibody] Clean up some helper file structure
  multibody/plant/BUILD.bazel
  multibody/plant/geometry_contact_data.cc
  multibody/plant/geometry_contact_data.h
  multibody/plant/hydroelastic_contact_forces_continuous_cache_data.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#21599 Add RigidBody::CalcCenterOfMassTranslationalAccelerationInWorld().
  multibody/plant/test/multibody_plant_kinematics_test.cc
  multibody/tree/rigid_body.cc
  multibody/tree/rigid_body.h
Labels: priority: medium, status: squashing now, release notes: none

#21657 Warn the user if the psd constraint has 1 or 2 rows.
  solvers/constraint.cc
  solvers/constraint.h
Labels: release notes: feature

#21670 July external upgrades
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/mujoco_menagerie_internal/repository.bzl
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/pycodestyle/repository.bzl
  tools/workspace/ros_xacro_internal/repository.bzl
  tools/workspace/rules_python/repository.bzl
  tools/workspace/tinygltf_internal/repository.bzl
  tools/workspace/typing_extensions_internal/repository.bzl
  tools/workspace/vtk_internal/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#21676 [setup] Upgrade Bazel to latest release 7.2.1
  .bazeliskrc
  doc/_pages/from_source.md
Labels: status: single reviewer ok, release notes: fix

#21684 Add support for numpy 2.0
  bindings/pydrake/common/containers.py
  bindings/pydrake/common/test/containers_test.py
  bindings/pydrake/examples/gym/play_cart_pole.py
  bindings/pydrake/gym/test/drake_gym_test.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/test/trajectories_test.py
  examples/acrobot/optimizer_demo.py
  setup/mac/binary_distribution/requirements.txt
  tools/wheel/image/provision-python.sh
  tools/wheel/image/setup.py
  tools/workspace/pybind11/pybind11-config-version.cmake
  tools/workspace/pybind11/pybind11-config.cmake
  tools/workspace/pybind11/repository.bzl
Labels: priority: high, status: do not merge, release notes: fix

#21645 [planning] Revise CollisionChecker parallel edge checks
  planning/collision_checker.cc
  planning/edge_measure.h
Labels: status: squashing now, release notes: fix

#21698 Sort the result of ComputeSignedDistancePairwiseClosestPoints.
  geometry/proximity_engine.cc
  geometry/query_object.h
  geometry/test/proximity_engine_test.cc
Labels: release notes: fix

#21674 Upgrade gz_math_internal and sdformat_internal to latest
  tools/workspace/gz_math_internal/package.BUILD.bazel
  tools/workspace/gz_math_internal/repository.bzl
Labels: status: squashing now, release notes: fix

#21701 [tools] Switch to bazel's deps vs implementation_deps semantics
  common/BUILD.bazel
  common/proto/BUILD.bazel
  common/symbolic/BUILD.bazel
  common/symbolic/expression/BUILD.bazel
  examples/hardware_sim/BUILD.bazel
  geometry/BUILD.bazel
  geometry/optimization/BUILD.bazel
  geometry/proximity/BUILD.bazel
  geometry/render/BUILD.bazel
  geometry/render_gl/BUILD.bazel
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_vtk/BUILD.bazel
  lcm/BUILD.bazel
  manipulation/kuka_iiwa/BUILD.bazel
  manipulation/util/BUILD.bazel
  math/BUILD.bazel
  multibody/contact_solvers/BUILD.bazel
  multibody/parsing/BUILD.bazel
  perception/BUILD.bazel
  planning/BUILD.bazel
  planning/iris/BUILD.bazel
  solvers/BUILD.bazel
  solvers/defs.bzl
  systems/analysis/BUILD.bazel
  systems/framework/BUILD.bazel
  systems/lcm/BUILD.bazel
  systems/primitives/BUILD.bazel
  systems/sensors/BUILD.bazel
  tools/install/libdrake/header_lint.bzl
  tools/lint/buildifier-tables.json
  tools/skylark/drake_cc.bzl
  visualization/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#21694 [multibody] Rework ContactResults for performance and safety
  multibody/plant/BUILD.bazel
  multibody/plant/contact_results.cc
  multibody/plant/contact_results.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/geometry_contact_data.cc
  multibody/plant/geometry_contact_data.h
  multibody/plant/hydroelastic_contact_forces_continuous_cache_data.h
  multibody/plant/hydroelastic_contact_info.cc
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/contact_results_test.cc
  multibody/plant/test/contact_results_to_lcm_test.cc
  multibody/plant/test/hydroelastic_contact_info_test.cc
Labels: priority: high, release notes: newly deprecated

#21702 [planning] Remove duplicate sort from SceneGraphCollisionChecker
  planning/scene_graph_collision_checker.cc
Labels: release notes: fix

#21647 [wheel] Add an option for --snopt-path
  tools/wheel/Dockerfile
  tools/wheel/image/build-drake.sh
  tools/wheel/image/known_hosts
  tools/wheel/image/packages-jammy
  tools/wheel/image/provision-base.sh
  tools/wheel/macos/build-wheel.sh
  tools/wheel/wheel_builder/common.py
  tools/wheel/wheel_builder/linux.py
  tools/wheel/wheel_builder/macos.py
  tools/workspace/snopt/repository.bzl
Labels: priority: low, release notes: none

#21703 Enhance documentation and tests for center of mass functions; clarify relationship to forward dynamics
  multibody/plant/test/multibody_plant_com_test.cc
  multibody/plant/test/multibody_plant_kinematics_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/rigid_body.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#21707 [systems] Fix VectorSystem terrible computational performance
  bindings/pydrake/multibody/jupyter_widgets.py
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/_resample_log_interp1d_test.py
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/pyplot_visualizer_test.py
  examples/cubic_polynomial/backward_reachability.cc
  examples/cubic_polynomial/region_of_attraction.cc
  manipulation/schunk_wsg/schunk_wsg_constants.h
  systems/analysis/test/lyapunov_test.cc
  systems/analysis/test/monte_carlo_test.cc
  systems/framework/test/thread_sanitizer_test.cc
  systems/framework/test/vector_system_test.cc
  systems/framework/vector_system.h
  systems/primitives/BUILD.bazel
  systems/primitives/barycentric_system.cc
  systems/primitives/first_order_low_pass_filter.cc
  systems/primitives/gain.cc
  systems/primitives/integrator.cc
  systems/primitives/test/first_order_low_pass_filter_test.cc
  systems/sensors/rotary_encoders.cc
Labels: priority: high, release notes: newly deprecated, release notes: fix

#21691 [geometry] Speed up ClipPolygonbyHalfSpace
  geometry/proximity/mesh_intersection.cc
Labels: priority: low, release notes: none

#21697 new_release now prompts to check if Bazel needs to be upgraded
  tools/workspace/new_release.py
Labels: release notes: none

#21686 Implement USD geometry parsing tests (#17833)
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_usd_geometry.cc
  multibody/parsing/test/detail_usd_geometry_test.cc
Labels: status: squashing now, release notes: none

#21667 Fix UniformSample for Zero-Measure HPolyhedron
  bindings/pydrake/geometry/geometry_py_optimization.cc
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hpolyhedron.h
  geometry/optimization/test/hpolyhedron_test.cc
Labels: release notes: fix

#21553 Improve the warning message when the Hessian type is indefinite.
  solvers/constraint.cc
Labels: release notes: feature

#21403 Implement support for slack variables on edges in GraphOfConvexSets
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: release notes: feature

#21709 sort the result of ComputeSignedDistanceToPoint.
  geometry/proximity_engine.cc
  geometry/query_object.h
  geometry/test/proximity_engine_test.cc
Labels: release notes: fix

#21717 Fix HPolyhedron::UniformSample Test Failure on Mac Builds.
  geometry/optimization/test/hpolyhedron_test.cc
Labels: priority: high, release notes: none

#21593 Option to Leverage Axis-Aligned Bounding Boxes when Computing Pairwise Intersections for GCS
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/geodesic_convexity.cc
  geometry/optimization/geodesic_convexity.h
Labels: status: squashing now, release notes: feature

#21713 Relaxed tolerance on tests to pass on ARM
  geometry/optimization/test/affine_subspace_test.cc
  geometry/optimization/test/hyperrectangle_test.cc
  geometry/proximity/test/contact_surface_utility_test.cc
  geometry/proximity/test/distance_to_point_callback_test.cc
  geometry/render_gl/test/internal_shape_meshes_test.cc
  math/test/linear_solve_test.cc
  multibody/math/spatial_vector.h
  multibody/tree/test/geometry_spatial_inertia_test.cc
  multibody/tree/test/quaternion_floating_joint_test.cc
  multibody/tree/test/rotational_inertia_test.cc
  solvers/unrevised_lemke_solver.h
  systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Labels: release notes: fix

#21712 Adds patch to prevent UB when running on ARM
  multibody/math/spatial_acceleration.h
  multibody/math/spatial_force.h
  multibody/math/spatial_momentum.h
  multibody/math/spatial_vector.h
  multibody/math/spatial_velocity.h
Labels: release notes: none

#21655 Implements margin for convex hulls
  geometry/proximity/make_convex_hull_mesh_impl.cc
  geometry/proximity/make_convex_hull_mesh_impl.h
  geometry/proximity/test/make_convex_hull_mesh_impl_test.cc
Labels: release notes: fix

#21623 [multibody] Discrete MultibodyPlant uses sampled output ports
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/visualization/_model_visualizer.py
  bindings/pydrake/visualization/test/meldis_test.py
  multibody/meshcat/test/contact_visualizer_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/compliant_contact_manager.cc
  multibody/plant/discrete_step_memory.cc
  multibody/plant/discrete_step_memory.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_config.h
  multibody/plant/multibody_plant_config_functions.cc
  multibody/plant/sap_driver.cc
  multibody/plant/tamsi_driver.cc
  multibody/plant/test/actuated_models_test.cc
  multibody/plant/test/box_test.cc
  multibody/plant/test/compliant_contact_manager_test.cc
  multibody/plant/test/deformable_contact_results_test.cc
  multibody/plant/test/deformable_integration_test.cc
  multibody/plant/test/discrete_step_memory_test.cc
  multibody/plant/test/discrete_update_manager_test.cc
  multibody/plant/test/inclined_plane_test.cc
  multibody/plant/test/joint_locking_test.cc
  multibody/plant/test/multibody_plant_config_functions_test.cc
  multibody/plant/test/multibody_plant_forward_dynamics_test.cc
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
  multibody/plant/test/multibody_plant_query_object_connect_test.cc
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/plant/test/multibody_plant_scalar_conversion_test.cc
  multibody/plant/test/multibody_plant_test.cc
  planning/test/collision_checker_context_test.cc
  planning/trajectory_optimization/direct_transcription.cc
  planning/trajectory_optimization/test/direct_transcription_test.cc
Labels: priority: high, release notes: breaking change

#21693 CalcSpatialInertia handles Convex correctly
  multibody/parsing/detail_mujoco_parser.cc
  multibody/tree/BUILD.bazel
  multibody/tree/geometry_spatial_inertia.cc
  multibody/tree/geometry_spatial_inertia.h
  multibody/tree/test/geometry_spatial_inertia_test.cc
Labels: release notes: fix

#21720 [benchmark] Increase test size for homecart benchmark
  multibody/benchmarking/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#21710 Create MultibodyPlant::CalcCenterOfMassTranslationalAccelerationInWorld().
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_com_test.cc
  multibody/plant/test/multibody_plant_kinematics_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: priority: medium, status: squashing now, release notes: feature

#21695 [multibody topology] Update to support MbP's RemoveJoint feature
  multibody/topology/link_joint_graph.cc
  multibody/topology/link_joint_graph.h
  multibody/topology/link_joint_graph_defs.h
  multibody/topology/link_joint_graph_inlines.h
  multibody/topology/link_joint_graph_joint.h
  multibody/topology/link_joint_graph_link.h
  multibody/topology/spanning_forest.cc
  multibody/topology/spanning_forest.h
  multibody/topology/spanning_forest_inlines.h
  multibody/topology/spanning_forest_mobod.cc
  multibody/topology/spanning_forest_mobod.h
  multibody/topology/test/link_joint_graph_test.cc
  multibody/topology/test/spanning_forest_test.cc
Labels: priority: medium, release notes: none

#21730 Python bind CalcCenterOfMassTranslationalVelocity/Acceleration()
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: priority: medium, status: squashing now, release notes: feature

#21732 [workspace] Fix "gfortran not found" error reporting
  tools/workspace/gfortran/repository.bzl
Labels: priority: backlog, status: single reviewer ok, release notes: none

#21672 [workspace] Improve new_release script to handle rust_toolchain
  tools/workspace/new_release.py
  tools/workspace/rust_toolchain/upgrade.py
Labels: release notes: none

#21530 Improve GCS graphviz
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
Labels: status: squashing now, release notes: breaking change, release notes: feature

#21534 Reduce the noise in meshcat visualizer realtime rate reports
  bindings/pydrake/geometry/geometry_py_visualizers.cc
  bindings/pydrake/geometry/test/visualizers_test.py
  bindings/pydrake/visualization/_meldis.py
  common/timer.cc
  common/timer.h
  geometry/BUILD.bazel
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/meshcat.html
  geometry/meshcat_params.h
  geometry/meshcat_visualizer.cc
  geometry/meshcat_visualizer.h
  geometry/test/meshcat_test.cc
  geometry/test/meshcat_visualizer_test.cc
  systems/analysis/realtime_rate_calculator.cc
  systems/analysis/realtime_rate_calculator.h
  systems/analysis/test/realtime_rate_calculator_test.cc
Labels: release notes: newly deprecated, release notes: feature

#21739 [math] Remove unnecessary textual_hdrs line
  common/BUILD.bazel
  math/BUILD.bazel
  tools/skylark/drake_cc.bzl
Labels: release notes: none

#21737 [multibody] Clarify some implementation docs
  multibody/plant/contact_results.h
Labels: priority: backlog, status: single reviewer ok, release notes: none

#21735 [multibody] Deprecate some private helper structs
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_contact_info.cc
  multibody/plant/deformable_contact_info.h
  multibody/plant/deformable_driver.cc
  multibody/plant/hydroelastic_contact_info.cc
  multibody/plant/hydroelastic_contact_info.h
  multibody/plant/hydroelastic_quadrature_point_data.h
  multibody/plant/test/contact_results_test.cc
  multibody/plant/test/deformable_contact_info_test.cc
Labels: priority: backlog, status: single reviewer ok, release notes: newly deprecated

#21731 Adds careful handling of massless links to avoid singular forests
  multibody/topology/link_joint_graph.h
  multibody/topology/spanning_forest.cc
  multibody/topology/test/spanning_forest_test.cc
Labels: priority: medium, release notes: none

#21741 [multibody] Allow implicit PD gain tweaks post-finalize
  multibody/tree/joint_actuator.cc
  multibody/tree/joint_actuator.h
  multibody/tree/test/joint_actuator_test.cc
Labels: priority: medium, release notes: fix

#21723 Option to manually specify edges (and offsets) in GcsTrajectoryOptimization::AddEdges.
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: feature

#21742 [geometry] Introduce CompliantCompliant intersection benchmark.
  geometry/benchmarking/BUILD.bazel
  geometry/benchmarking/compliant_mesh_intersection_benchmark.cc
  geometry/proximity/BUILD.bazel
Labels: release notes: none

#21745 OBJ files for proximity can have multiple objects
  geometry/BUILD.bazel
  geometry/read_obj.cc
  geometry/read_obj.h
  geometry/test/forbidden_two_cubes.obj
  geometry/test/proximity_engine_test.cc
  geometry/test/read_obj_test.cc
  geometry/test/two_cube_objects.obj
Labels: release notes: fix

#21636 Remove experimental caveat on convex set
  geometry/optimization/convex_set.h
Labels: status: single reviewer ok, release notes: none

#21748 [pydrake] Remove workaround for bazel#4594
  bindings/BUILD.bazel
  bindings/bazel_workaround_4594_libdrake.bzl
  bindings/bazel_workaround_4594_libdrake_py.cc
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/__init__.py
Labels: status: single reviewer ok, release notes: none

#21733 Reimplement OBB box overlap test using highway (simd)
  geometry/proximity/BUILD.bazel
  geometry/proximity/boxes_overlap.cc
  geometry/proximity/boxes_overlap.h
Labels: release notes: fix

#21752 [doc] Remove mentions of weekly CI jobs
  doc/_pages/buildcop.md
  doc/_pages/jenkins.md
Labels: status: single reviewer ok, release notes: none

#21743 Implements mesh inflation for non-convex meshes
  geometry/proximity/BUILD.bazel
  geometry/proximity/inflate_mesh.cc
  geometry/proximity/inflate_mesh.h
  geometry/proximity/test/inflate_mesh_test.cc
  geometry/proximity/test/make_mesh_field_test.cc
  geometry/proximity/test/make_mesh_from_vtk_test.cc
  geometry/test/non_convex_mesh.vtk
Labels: priority: high, release notes: none

#21751 [highway_internal] Patch crash bug in debug builds
  geometry/proximity/BUILD.bazel
  tools/workspace/highway_internal/patches/target_get_index_inline_always.patch
  tools/workspace/highway_internal/repository.bzl
Labels: release notes: none

#21738 Remove/deprecate default value in CalcSpatialInertia(TriangleSurfaceMesh, density = 1).
  multibody/parsing/detail_mesh_parser.cc
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mesh_parser_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/tree/geometry_spatial_inertia.h
  multibody/tree/test/geometry_spatial_inertia_test.cc
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: newly deprecated

#21726 Incorporates margin in the compuation of hydroelastic fields
  geometry/proximity/BUILD.bazel
  geometry/proximity/make_box_field.cc
  geometry/proximity/make_box_field.h
  geometry/proximity/make_capsule_field.h
  geometry/proximity/make_cylinder_field.cc
  geometry/proximity/make_cylinder_field.h
  geometry/proximity/make_ellipsoid_field.h
  geometry/proximity/make_mesh_field.cc
  geometry/proximity/make_mesh_field.h
  geometry/proximity/make_sphere_field.h
  geometry/proximity/mesh_half_space_intersection.cc
  geometry/proximity/mesh_half_space_intersection.h
  geometry/proximity/test/make_box_field_test.cc
  geometry/proximity/test/make_capsule_field_test.cc
  geometry/proximity/test/make_cylinder_field_test.cc
  geometry/proximity/test/make_ellipsoid_field_test.cc
  geometry/proximity/test/make_mesh_field_test.cc
  geometry/proximity/test/make_sphere_field_test.cc
  geometry/proximity/test/mesh_half_space_intersection_test.cc
  geometry/proximity/test/pressure_field_invariants.cc
  geometry/proximity/test/pressure_field_invariants.h
Labels: priority: high, release notes: none
