Repository RobotLocomotion/drake, pull requests merged in 2024-08, with the labels that each got.

#21762 [multibody topology] Use std::swap() instead of bespoke Swap()
  multibody/topology/spanning_forest.cc
  multibody/topology/spanning_forest_mobod.cc
  multibody/topology/spanning_forest_mobod.h
Labels: priority: high, status: single reviewer ok, release notes: none

#21757 Remove deprecated code 2024-08
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/test/evaluators_test.py
  geometry/optimization/affine_subspace.cc
  geometry/optimization/affine_subspace.h
  geometry/optimization/test/affine_subspace_test.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/rpy_floating_joint.h
  multibody/tree/test/quaternion_floating_joint_test.cc
  multibody/tree/test/rpy_floating_joint_test.cc
  solvers/cost.h
  solvers/test/cost_test.cc
  systems/controllers/BUILD.bazel
  systems/controllers/stub/zmp_planner.h
  systems/controllers/test/deprecated_zmp_planner_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#21760 Promote -Wunqualified-std-cast-call to an error
  common/test/copyable_unique_ptr_test.cc
  common/test_utilities/test/is_memcpy_movable_test.cc
  tools/skylark/drake_cc.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#21754 Mathematical program additional bindings
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py.cc
  bindings/pydrake/solvers/solvers_py.h
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/solvers_py_program_attribute.cc
  bindings/pydrake/solvers/test/evaluators_test.py
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  bindings/pydrake/solvers/test/program_attribute_test.py
Labels: status: squashing now, release notes: fix

#21749 [gcs] Use pointers for optional arguments
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: breaking change, release notes: newly deprecated

#21769 [workspace] Upgrade scs_internal to latest release 3.2.6
  tools/workspace/scs_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#21771 Revert "[workspace] Upgrade scs_internal to latest release 3.2.6"
  tools/workspace/scs_internal/repository.bzl
Labels: status: single reviewer ok, release notes: none

#21755 [multibody topology] Handle merged composites
  multibody/topology/link_joint_graph.cc
  multibody/topology/link_joint_graph.h
  multibody/topology/link_joint_graph_defs.h
  multibody/topology/link_joint_graph_inlines.h
  multibody/topology/link_joint_graph_link.h
  multibody/topology/spanning_forest.cc
  multibody/topology/spanning_forest.h
  multibody/topology/spanning_forest_mobod.h
  multibody/topology/test/link_joint_graph_test.cc
  multibody/topology/test/spanning_forest_test.cc
Labels: priority: medium, release notes: none

#21750 [geometry] Reorganize contact result code to expose parallelism
  geometry/BUILD.bazel
  geometry/benchmarking/BUILD.bazel
  geometry/benchmarking/compliant_mesh_intersection_benchmark.cc
  geometry/proximity/BUILD.bazel
  geometry/proximity/hydroelastic_calculator.cc
  geometry/proximity/hydroelastic_calculator.h
  geometry/proximity/hydroelastic_callback.h
  geometry/proximity/penetration_as_point_pair_callback.cc
  geometry/proximity/penetration_as_point_pair_callback.h
  geometry/proximity/test/hydroelastic_calculator_test.cc
  geometry/proximity_engine.cc
  geometry/test/proximity_engine_test.cc
Labels: status: squashing now, release notes: none

#21740 Add model_instances to CalcBiasCenterOfMassTranslationalAcceleration()
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_com_test.cc
  multibody/plant/test/multibody_plant_jacobians_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
Labels: priority: medium, status: squashing now, release notes: feature

#21746 [proximity] Adds VolumeMeshTopology
  geometry/proximity/BUILD.bazel
  geometry/proximity/test/volume_mesh_topology_test.cc
  geometry/proximity/volume_mesh_topology.cc
  geometry/proximity/volume_mesh_topology.h
Labels: release notes: none

#21774 [workspace] Upgrade build_bazel_apple_support to latest release 1.16.0
  tools/workspace/build_bazel_apple_support/patches/no_bazel_features.patch
  tools/workspace/build_bazel_apple_support/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#21767 [workspace] Upgrade curl_internal to latest release curl-8_9_1
  geometry/render_gltf_client/test/internal_http_service_curl_test.cc
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/repository.bzl
Labels: priority: low, status: squashing now, release notes: fix

#21783 [planning] RobotDiagramBuilder skips deprecated ports
  planning/robot_diagram_builder.cc
  planning/test/robot_diagram_test.cc
  systems/framework/system.cc
Labels: priority: medium, status: single reviewer ok, release notes: fix

#21781 SnoptSolverDetails report solving time.
  bindings/pydrake/solvers/solvers_py_snopt.cc
  bindings/pydrake/solvers/test/snopt_solver_test.py
  solvers/snopt_solver.cc
  solvers/snopt_solver.h
  solvers/test/snopt_solver_test.cc
Labels: release notes: feature

#21776 Update openJDK installation to temurin
  setup/mac/binary_distribution/Brewfile
Labels: release notes: none

#21777 Updates hydroelastic field computation for the ellipsoid and meshes.
  geometry/proximity/make_ellipsoid_field.h
  geometry/proximity/make_mesh_field.cc
  geometry/proximity/make_mesh_field.h
  geometry/proximity/test/make_ellipsoid_field_test.cc
  geometry/proximity/test/make_mesh_field_test.cc
Labels: priority: high, release notes: none

#21779 Always use the convex hull for Convex shapes
  geometry/BUILD.bazel
  geometry/proximity/BUILD.bazel
  geometry/proximity/make_convex_mesh.cc
  geometry/proximity/test/make_convex_mesh_test.cc
  geometry/shape_specification.cc
  geometry/test/shape_specification_test.cc
Labels: release notes: fix

#21785 Fix a bug in computing OrientationCost.
  multibody/inverse_kinematics/orientation_cost.cc
  multibody/inverse_kinematics/test/inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/orientation_cost_test.cc
Labels: release notes: fix

#21780 [geometry] Split infeasible vertices in MakeInflatedMesh()
  geometry/BUILD.bazel
  geometry/proximity/inflate_mesh.cc
  geometry/proximity/inflate_mesh.h
  geometry/proximity/test/inflate_mesh_test.cc
  geometry/proximity/volume_to_surface_mesh.cc
  geometry/proximity/volume_to_surface_mesh.h
  geometry/test/inflation_infeasible_vertex.vtk
Labels: priority: high, status: squashing now, release notes: none

#21787 [wheel] Update metadata for 3.10 lower bound
  tools/wheel/image/setup.py
Labels: priority: low, status: single reviewer ok, release notes: none

#21718 Option to specify AABBs when calculating pairwise intersections for GCS.
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/geodesic_convexity.cc
  geometry/optimization/geodesic_convexity.h
  geometry/optimization/test/geodesic_convexity_test.cc
Labels: release notes: feature

#21784 Consolidate documentation for CalcBias functions into one group.
  multibody/plant/multibody_plant.h
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: none

#21773 Incorporates margin in the compuation of hydroelastic fields.
  geometry/geometry_state.cc
  geometry/proximity/BUILD.bazel
  geometry/proximity/hydroelastic_calculator.cc
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/hydroelastic_internal.h
  geometry/proximity_engine.cc
  geometry/proximity_properties.cc
  geometry/proximity_properties.h
  geometry/scene_graph_config.h
  geometry/test/geometry_state_test.cc
  geometry/test/proximity_engine_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/test/multibody_plant_hydroelastic_test.cc
Labels: priority: high, release notes: feature

#21794 Copy/paste documentation to avoid subgroup in @name System matrix computations
  multibody/plant/multibody_plant.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#21789 [RgbdSensor] Expose `X_PB_` via a const getter function
  bindings/pydrake/systems/sensors_py_rgbd.cc
  bindings/pydrake/systems/test/sensors_test.py
  systems/sensors/rgbd_sensor.h
Labels: release notes: feature

#21791 [geometry] Clarify some implementation details in proximity engine
  geometry/proximity_engine.cc
Labels: release notes: none

#21768 [workspace] Upgrade openusd_internal to latest release v24.08
  tools/workspace/openusd_internal/lock/files.bzl
  tools/workspace/openusd_internal/patches/00_work_thread_limits_namespace.patch
  tools/workspace/openusd_internal/patches/cmake_base_vt_noboost.patch
  tools/workspace/openusd_internal/patches/cmake_gf.patch
  tools/workspace/openusd_internal/patches/nanocolor_namespace.patch
  tools/workspace/openusd_internal/patches/onetbb.patch
  tools/workspace/openusd_internal/patches/pegtl_namespace.patch
  tools/workspace/openusd_internal/patches/pegtl_workaround.patch
  tools/workspace/openusd_internal/patches/usd_sdf_noboost.patch
  tools/workspace/openusd_internal/repository.bzl
  tools/workspace/openusd_internal/upgrade.py
Labels: priority: low, status: squashing now, release notes: fix

#21796 Simple copy/paste to separate Jacobian and system matrix documentation
  multibody/plant/multibody_plant.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#21764 improve the error message when attempting to solve GCS problems with convex quadratic constraints
  geometry/optimization/graph_of_convex_sets.cc
Labels: status: squashing now, release notes: none

#21793 Consolidate documentation for Jacobian functions into one group.
  multibody/plant/multibody_plant.h
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: none

#21800 [multibody topology] Added Graphviz visualization
  multibody/topology/BUILD.bazel
  multibody/topology/link_joint_graph.h
  multibody/topology/link_joint_graph_debug.cc
  multibody/topology/spanning_forest.cc
  multibody/topology/spanning_forest.h
  multibody/topology/spanning_forest_debug.cc
  multibody/topology/spanning_forest_mobod.h
  multibody/topology/test/spanning_forest_test.cc
Labels: priority: medium, release notes: none

#21798 [workspace] Upgrade sdformat_internal to latest
  multibody/parsing/detail_sdf_geometry.cc
  tools/workspace/sdformat_internal/package.BUILD.bazel
  tools/workspace/sdformat_internal/repository.bzl
Labels: status: squashing now, release notes: fix

#21804 Update drake CMake config files for DEE
  tools/install/libdrake/drake-config.cmake.in
  tools/workspace/lcm/lcm-config.cmake
  tools/workspace/pybind11/pybind11-config.cmake
Labels: release notes: none

#21805 [multibody topology] Removed some stub code that is no longer needed
  multibody/topology/spanning_forest.cc
  multibody/topology/spanning_forest.h
  multibody/topology/test/spanning_forest_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#21594 Convex hulls of multiple convex sets
  geometry/optimization/BUILD.bazel
  geometry/optimization/convex_hull.cc
  geometry/optimization/convex_hull.h
  geometry/optimization/test/convex_hull_test.cc
Labels: status: squashing now, release notes: feature

#21811 [multibody topology] Replace BodyIndex with LinkIndex alias
  multibody/topology/link_joint_graph.cc
  multibody/topology/link_joint_graph.h
  multibody/topology/link_joint_graph_debug.cc
  multibody/topology/link_joint_graph_defs.h
  multibody/topology/link_joint_graph_inlines.h
  multibody/topology/link_joint_graph_joint.h
  multibody/topology/link_joint_graph_link.h
  multibody/topology/link_joint_graph_loop_constraint.h
  multibody/topology/spanning_forest.cc
  multibody/topology/spanning_forest.h
  multibody/topology/test/link_joint_graph_test.cc
  multibody/topology/test/spanning_forest_test.cc
  multibody/tree/multibody_tree_indexes.h
Labels: priority: medium, status: single reviewer ok, release notes: feature

#21734 Better error message for zero-duration trajectory segments in GcsTrajectoryOptimization.
  planning/trajectory_optimization/BUILD.bazel
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: fix

#21803 [doc] Add release notes v1.32.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.32.0.md
Labels: status: squashing now, status: single reviewer ok, release notes: none

#21814 Adds @ingroup geometry_optimization tag to Hyperrectangle
  geometry/optimization/hyperrectangle.h
Labels: status: single reviewer ok, release notes: none

#21812 [workspace] Bump CRU and VGT 2024-08-14
  tools/workspace/common_robotics_utilities/repository.bzl
  tools/workspace/voxelized_geometry_tools/repository.bzl
Labels: release notes: fix

#21817 Fix GCS GetGraphvizString bindings to accept default `active_path`
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
Labels: status: single reviewer ok, release notes: fix

#21806 [multibody topology] Adds misc algorithms over graph and forest
  multibody/topology/link_joint_graph.cc
  multibody/topology/link_joint_graph.h
  multibody/topology/spanning_forest.cc
  multibody/topology/spanning_forest.h
  multibody/topology/test/link_joint_graph_test.cc
  multibody/topology/test/spanning_forest_test.cc
Labels: priority: medium, release notes: none

#21818 [multibody topology] Adds a sanity checker for graph & forest
  multibody/topology/spanning_forest.cc
  multibody/topology/spanning_forest.h
  multibody/topology/spanning_forest_debug.cc
  multibody/topology/test/link_joint_graph_test.cc
  multibody/topology/test/spanning_forest_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#21810 PathEnergyCost for GCSTrajectoryOptimization
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: status: squashing now, release notes: feature

#21826 Create new doxygen group for the geodesic convexity functions, nested under geometry_optimization.
  geometry/optimization/geodesic_convexity.h
Labels: status: single reviewer ok, release notes: none

#21829 Pin mac binary numpy version to 2.0.1
  setup/mac/binary_distribution/requirements.txt
  tools/wheel/image/setup.py
Labels: status: single reviewer ok, release notes: none

#21815 Fix a typo found in tutorial update
  tutorials/updating_costs_and_constraints.ipynb
Labels: priority: backlog, status: single reviewer ok, release notes: none

#21840 [multibody topology] Replace Doxygen /** with /* for internal API
  multibody/topology/forest.h
  multibody/topology/graph.h
  multibody/topology/link_joint_graph.h
  multibody/topology/link_joint_graph_defs.h
  multibody/topology/link_joint_graph_joint.h
  multibody/topology/link_joint_graph_link.h
  multibody/topology/link_joint_graph_loop_constraint.h
  multibody/topology/spanning_forest.h
  multibody/topology/spanning_forest_loop_constraint.h
  multibody/topology/spanning_forest_mobod.h
  multibody/topology/spanning_forest_tree.h
Labels: priority: low, status: single reviewer ok, release notes: none

#21799 [workspace] Upgrade vtk_internal to latest commit
  systems/sensors/image_io_load.cc
  tools/workspace/vtk_internal/patches/camera_copy.patch
  tools/workspace/vtk_internal/patches/gltf_parser.patch
  tools/workspace/vtk_internal/patches/gltf_quiet_image_errors.patch
  tools/workspace/vtk_internal/repository.bzl
  tools/workspace/vtk_internal/rules.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#21841 [topology] Tidy up bazel library spelling
  multibody/plant/BUILD.bazel
  multibody/topology/BUILD.bazel
  multibody/tree/BUILD.bazel
  tools/install/libdrake/build_components.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#21833 [GCS] Resolve inconsistencies in results from shortest path vs convex restriction
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
Labels: priority: medium, release notes: breaking change, release notes: fix

#21797 [workspace] Upgrade scs_internal to latest release 3.2.7
  tools/workspace/scs_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#21656 Static constructor for CompositeTrajectory that automatically aligns segment timings.
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/BUILD.bazel
  common/trajectories/composite_trajectory.cc
  common/trajectories/composite_trajectory.h
  common/trajectories/test/composite_trajectory_test.cc
Labels: release notes: feature

#21845 [setup] Adjust macOS pip dependencies
  setup/mac/binary_distribution/requirements.txt
  tools/wheel/image/setup.py
  tools/wheel/wheel_builder/macos.py
Labels: priority: high, status: single reviewer ok, release notes: none

#21848 [tools] Clarify implementation deps vocabulary
  tools/skylark/drake_cc.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#21790 [fem] Remove quadrature template from constitutive models
  multibody/fem/constitutive_model.h
  multibody/fem/corotated_model.cc
  multibody/fem/corotated_model.h
  multibody/fem/corotated_model_data.cc
  multibody/fem/corotated_model_data.h
  multibody/fem/deformation_gradient_data.h
  multibody/fem/linear_constitutive_model.cc
  multibody/fem/linear_constitutive_model.h
  multibody/fem/linear_constitutive_model_data.cc
  multibody/fem/linear_constitutive_model_data.h
  multibody/fem/linear_corotated_model.cc
  multibody/fem/linear_corotated_model.h
  multibody/fem/linear_corotated_model_data.cc
  multibody/fem/linear_corotated_model_data.h
  multibody/fem/test/constitutive_model_test.cc
  multibody/fem/test/constitutive_model_test_utilities.cc
  multibody/fem/test/constitutive_model_test_utilities.h
  multibody/fem/test/corotated_model_data_test.cc
  multibody/fem/test/corotated_model_test.cc
  multibody/fem/test/deformation_gradient_data_test.cc
  multibody/fem/test/dummy_element.h
  multibody/fem/test/fem_model_test.cc
  multibody/fem/test/linear_constitutive_model_data_test.cc
  multibody/fem/test/linear_constitutive_model_test.cc
  multibody/fem/test/linear_corotated_model_data_test.cc
  multibody/fem/test/linear_corotated_model_test.cc
  multibody/fem/test/volumetric_element_test.cc
  multibody/fem/test/volumetric_model_test.cc
  multibody/fem/volumetric_element.h
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
Labels: release notes: none

#21808 Correct MultibodyPlant free body documentation to reflect current implementations
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/parsing/model_directives.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/rigid_body.h
Labels: release notes: newly deprecated, release notes: fix

#21827 CartesianProduct Getters for A and b Properties
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/cartesian_product.h
  geometry/optimization/test/cartesian_product_test.cc
Labels: status: squashing now, release notes: feature

#21837 Handle Continuous Revolute Joints in IrisInConfigurationSpace
  geometry/optimization/iris.cc
  geometry/optimization/iris.h
  geometry/optimization/test/iris_in_configuration_space_test.cc
Labels: status: squashing now, release notes: feature

#21842 Consolidate .obj parsing
  bindings/pydrake/geometry/geometry_py_meshes.cc
  bindings/pydrake/multibody/test/mesh_to_model_test.py
  geometry/BUILD.bazel
  geometry/proximity/BUILD.bazel
  geometry/proximity/obj_to_surface_mesh.cc
  geometry/proximity/obj_to_surface_mesh.h
  geometry/proximity/test/obj_to_surface_mesh_test.cc
  geometry/read_obj.cc
  geometry/read_obj.h
  geometry/test/proximity_engine_test.cc
  geometry/test/shape_specification_test.cc
  multibody/parsing/detail_mesh_parser.cc
  multibody/parsing/test/detail_mesh_parser_test.cc
  tools/workspace/tinyobjloader_internal/patches/silence_materials.patch
  tools/workspace/tinyobjloader_internal/repository.bzl
Labels: release notes: none

#21856 Usages of fmt::join made compatible with fmt v11
  common/yaml/test/yaml_doxygen_test.cc
  common/yaml/yaml_read_archive.cc
  geometry/geometry_state.cc
  geometry/meshcat.cc
  geometry/optimization/vpolytope.cc
  geometry/render/render_material.cc
  geometry/render_gltf_client/internal_http_service.cc
  multibody/plant/internal_geometry_names.cc
  multibody/plant/multibody_plant.cc
  multibody/tree/multibody_tree.cc
  solvers/clarabel_solver.cc
  systems/framework/diagram.cc
  systems/framework/system.cc
  systems/framework/system_base.cc
  systems/framework/test/diagram_test.cc
  systems/lcm/test/lcm_system_graphviz_test.cc
Labels: priority: high, status: single reviewer ok, release notes: fix

#21854 [multibody] Fix dmd default_free_body_pose vs offset frames
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/test/detail_dmd_parser_test.cc
Labels: priority: high, release notes: fix

#21853 [multibody] Simplify frames in MultibodyPlant
  multibody/tree/BUILD.bazel
  multibody/tree/body_node.h
  multibody/tree/frame.h
  multibody/tree/frame_base.cc
  multibody/tree/frame_base.h
  multibody/tree/frame_body_pose_cache.cc
  multibody/tree/frame_body_pose_cache.h
  multibody/tree/mobilizer.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/multibody_tree_system.cc
  multibody/tree/multibody_tree_system.h
  multibody/tree/position_kinematics_cache.h
  multibody/tree/test/frames_test.cc
Labels: priority: medium, type: performance, release notes: breaking change

#21859 [tools] Fix kcov_tool to work with Bazel 7
  tools/dynamic_analysis/kcov_tool
Labels: status: single reviewer ok, release notes: none

#21863 [setup] Satisfy bazel_tools implicit zip dependency
  setup/ubuntu/source_distribution/packages-jammy-test-only.txt
  setup/ubuntu/source_distribution/packages-noble-test-only.txt
Labels: status: single reviewer ok, release notes: none
