Repository RobotLocomotion/drake, pull requests merged in 2025-09, with the labels that each got.

#23352 Remove deprecated code 2025-09
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc
  bindings/pydrake/manipulation/test/kuka_iiwa_test.py
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/multibody/tree_py_inertia.cc
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/solvers_py_options.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  manipulation/kuka_iiwa/build_iiwa_control.cc
  manipulation/kuka_iiwa/build_iiwa_control.h
  manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
  multibody/tree/revolute_spring.h
  multibody/tree/test/revolute_spring_test.cc
  solvers/mathematical_program.h
  solvers/solver_options.cc
  solvers/solver_options.h
  solvers/test/mathematical_program_test.cc
  solvers/test/solver_options_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#23375 [workspace] Upgrade ipopt_internal to latest release 3.14.19
  tools/workspace/ipopt_internal/package.BUILD.bazel
  tools/workspace/ipopt_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#23351 [geometry] Remove obscure constant
  geometry/proximity/bvh.cc
  geometry/proximity/bvh.h
  geometry/proximity/bvh_updater.h
Labels: priority: low, status: single reviewer ok, release notes: none

#23378 Disable render_gl test under LSAN
  geometry/render_gl/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#23386 [cpplint] Fix iwyu lint (6/5)
  bindings/pydrake/common/text_logging_pybind.cc
  bindings/pydrake/common/value_py.cc
  bindings/pydrake/geometry/geometry_py_bounding_box.cc
  bindings/pydrake/geometry/geometry_py_common.cc
  bindings/pydrake/geometry/geometry_py_meshes.cc
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/geometry_py_visualizers.cc
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/multibody/inverse_kinematics_py_differential.cc
  bindings/pydrake/multibody/tree_py.cc
  bindings/pydrake/planning/planning_py_collision_checker.cc
  bindings/pydrake/planning/planning_py_collision_checker_interface_types.cc
  bindings/pydrake/planning/planning_py_dof_mask.cc
  bindings/pydrake/planning/planning_py_graph_algorithms.cc
  bindings/pydrake/planning/planning_py_iris_common.cc
  bindings/pydrake/planning/planning_py_iris_from_clique_cover.cc
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/solvers_py_ids.cc
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/solvers_py_mixed_integer_optimization_util.cc
  bindings/pydrake/solvers/solvers_py_options.cc
  bindings/pydrake/solvers/solvers_py_semidefinite_relaxation.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/sensors_py_image.cc
  bindings/pydrake/systems/sensors_py_image_io.cc
  bindings/pydrake/systems/sensors_py_lcm.cc
  bindings/pydrake/systems/sensors_py_rgbd.cc
  bindings/pydrake/systems/sensors_py_rotary_encoders.cc
  bindings/pydrake/systems/value_producer_pybind.cc
  bindings/pydrake/visualization/visualization_py_sliders.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#23384 [tools] Remove polyfill of implementation_deps
  tools/skylark/drake_cc.bzl
Labels: priority: medium, status: single reviewer ok, release notes: none

#23385 [doc] Rename #buildcop Slack to #ci
  doc/_pages/buildcop.md
Labels: release notes: none

#23388 [doc] New component owner for geometry/general
  doc/_pages/issues.md
Labels: status: single reviewer ok, release notes: none

#23393 [workspace] Deprecate the styleguide external
  MODULE.bazel
  doc/styleguide/BUILD.bazel
  doc/styleguide/build.py
  tools/workspace/default.bzl
  tools/workspace/styleguide/package-deprecated.BUILD.bazel
  tools/workspace/styleguide/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#23339 [doc] Document supported native CMake options
  CMakeLists.txt
  doc/_pages/from_source.md
Labels: priority: low, release notes: fix

#23372 Use cron syntax for Renovate scheduler
  .github/renovate.json
Labels: status: single reviewer ok, release notes: none

#23383 [tools] Modernize more bazel module dependencies
  MODULE.bazel
  common/test_utilities/BUILD.bazel
  geometry/optimization/BUILD.bazel
  geometry/optimization/dev/BUILD.bazel
  geometry/proximity/BUILD.bazel
  geometry/test_utilities/BUILD.bazel
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/inverse_kinematics/BUILD.bazel
  multibody/plant/test_utilities/BUILD.bazel
  multibody/rational/BUILD.bazel
  planning/dev/BUILD.bazel
  planning/test_utilities/BUILD.bazel
  solvers/BUILD.bazel
  solvers/test_utilities/BUILD.bazel
  systems/optimization/BUILD.bazel
  systems/sensors/BUILD.bazel
  systems/sensors/test_utilities/BUILD.bazel
  tools/lint/BUILD.bazel
  tools/lint/buildifier.py
  tools/lint/python_lint.bzl
  tools/skylark/drake_cc.bzl
  tools/workspace/buildifier/package.BUILD.bazel
  tools/workspace/common_robotics_utilities_internal/package.BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/gflags/patches/deprecation.patch
  tools/workspace/gflags/repository.bzl
  tools/workspace/googletest/BUILD.bazel
  tools/workspace/googletest/patches/add_printers.patch
  tools/workspace/googletest/patches/add_printers_deps.patch
  tools/workspace/googletest/patches/defines.patch
  tools/workspace/gtest/package.BUILD.bazel
  tools/workspace/gtest/repository.bzl
  tools/workspace/new_release.py
  tools/workspace/pycodestyle/package.BUILD.bazel
  tools/workspace/pycodestyle_internal/BUILD.bazel
  tools/workspace/pycodestyle_internal/package.BUILD.bazel
  tools/workspace/pycodestyle_internal/repository.bzl
  tools/workspace/voxelized_geometry_tools_internal/package.BUILD.bazel
Labels: priority: low, release notes: newly deprecated, release notes: fix

#23387 [Jenkins] Clean up workspace before builds
  .jenkins/Jenkinsfile-experimental
  .jenkins/Jenkinsfile-external-examples
  .jenkins/Jenkinsfile-production
  .jenkins/Jenkinsfile-staging
  .jenkins/templates/Jenkinsfile-experimental.in
  .jenkins/templates/Jenkinsfile-production.in
  .jenkins/templates/Jenkinsfile-staging.in
  .jenkins/utils/utils.groovy
Labels: release notes: none

#23402 [workspace] Adjust new_release for downloading from tag vs commit
  tools/workspace/new_release.py
Labels: priority: low, release notes: none

#23408 Fix bug in IrisNp2 where all but the last hyperplane was being used when there are additional constraints.
  planning/iris/iris_np2.cc
Labels: release notes: fix

#23413 [workspare] Remove unused nasm_repository
  setup/mac/source_distribution/Brewfile
  setup/ubuntu/source_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-noble.txt
  tools/workspace/default.bzl
  tools/workspace/nasm/BUILD.bazel
  tools/workspace/nasm/repository.bzl
  tools/workspace/which.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#23430 [workspace] Group internal_repositories by category, with comments
  MODULE.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#23411 [doc] Add release notes v1.45.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.45.0.md
Labels: status: squashing now, status: single reviewer ok, release notes: none

#23448 [tools] Mark xmlrunner_py 'internal' for new_release
  tools/workspace/new_release.py
Labels: release notes: none

#23454 Revert "Speed up IrisNp2 test cases."
  planning/iris/test/iris_np2_test.cc
Labels: status: single reviewer ok, release notes: none

#23449 Disable memcheck for the IrisNp2 tests
  planning/iris/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#23451 Reviewable ignores diffs of generated_docstrings
  .gitattributes
Labels: priority: low, status: single reviewer ok, release notes: none

#23452 [tools] Remove unused python_lint_ignore customization
  tools/lint/BUILD.bazel
  tools/lint/lint.bzl
  tools/lint/python_lint.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#23453 [workspace] Patch msgpack_internal for Xcode 26.0
  tools/workspace/msgpack_internal/patches/upstream/type_traits_remove_volatile.patch
  tools/workspace/msgpack_internal/repository.bzl
Labels: status: single reviewer ok, release notes: none

#23457 [workspace] Fix a little more highway symbol leakage
  tools/workspace/highway_internal/patches/target_get_index_inline_always.patch
Labels: priority: medium, status: single reviewer ok, release notes: none

#23460 [workspace] Provide Python installation opt-out
  BUILD.bazel
  CMakeLists.txt
  bindings/pydrake/BUILD.bazel
  doc/_pages/from_source.md
  lcmtypes/BUILD.bazel
  tools/flags/BUILD.bazel
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake-config.cmake.in
  tools/workspace/BUILD.bazel
Labels: release notes: feature

#23458 [tools] Remove unused code for installing java binaries
  lcmtypes/BUILD.bazel
  tools/install/install.bzl
  tools/skylark/drake_java.bzl
  tools/workspace/lcm/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#23466 [tools] Fix spdlog flag level in bazelrc
  tools/bazel.rc
Labels: priority: low, status: single reviewer ok, release notes: none

#23467 [lcmtypes] Deprecate fine-grained C++ libraries
  common/proto/BUILD.bazel
  examples/acrobot/BUILD.bazel
  examples/allegro_hand/BUILD.bazel
  examples/allegro_hand/joint_control/BUILD.bazel
  examples/kinova_jaco_arm/BUILD.bazel
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/planar_gripper/BUILD.bazel
  examples/scene_graph/BUILD.bazel
  geometry/BUILD.bazel
  geometry/profiling/BUILD.bazel
  lcm/BUILD.bazel
  lcmtypes/BUILD.bazel
  manipulation/schunk_wsg/BUILD.bazel
  manipulation/util/BUILD.bazel
  multibody/plant/BUILD.bazel
  perception/BUILD.bazel
  systems/lcm/BUILD.bazel
  systems/sensors/BUILD.bazel
Labels: priority: medium, release notes: newly deprecated

#23473 [workspace] Use lcm-spy from lcm_internal external (not lcm)
  MODULE.bazel
  lcm/BUILD.bazel
  lcmtypes/BUILD.bazel
  tools/workspace/lcm/BUILD.bazel
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/lcm/test/import_lcm_test.py
Labels: priority: low, release notes: none

#23461 [doc] Drop support for macOS Sonoma
  .github/ISSUE_TEMPLATE/BUG.yml
  CMakeLists.txt
  doc/_pages/buildcop.md
  doc/_pages/code_review_checklist.md
  doc/_pages/from_source.md
  doc/_pages/getting_help.md
  doc/_pages/installation.md
  doc/_pages/jenkins.md
  doc/_pages/release_playbook.md
Labels: release notes: breaking change

#23298 [build] Optionally install a static `libdrake.a`
  BUILD.bazel
  CMakeLists.txt
  common/BUILD.bazel
  doc/_pages/from_source.md
  third_party/BUILD.bazel
  third_party/com_github_bazelbuild_rules_cc/cc_static_libary.bzl
  third_party/com_github_bazelbuild_rules_cc/find_cc_toolchain.bzl
  third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl
  tools/flags/BUILD.bazel
  tools/install/install.bzl
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/drake-config.cmake.in
  tools/install/libdrake/test/find_package_drake_install_test.py
Labels: release notes: fix

#23474 [workspace] Use LCM runtime from lcm_internal (not lcm)
  lcm/BUILD.bazel
  lcm/drake_lcm_log.cc
  lcm/test/drake_lcm_test.cc
  lcm/test/drake_lcm_thread_test.cc
  tools/install/libdrake/BUILD.bazel
  tools/workspace/BUILD.bazel
  tools/workspace/lcm/BUILD.bazel
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/lcm_internal/BUILD.bazel
  tools/workspace/lcm_internal/patches/copts.patch
  tools/workspace/lcm_internal/patches/vendor_namespace.patch
  tools/workspace/lcm_internal/repository.bzl
Labels: priority: low, release notes: none

#23480 [workspace] Amend tsan.supp for new drake_vendor_lcm symbol prefix
  tools/dynamic_analysis/tsan.supp
Labels: priority: high, status: single reviewer ok, release notes: none

#23481 [pydrake] Stop relying on a deprecated internal pybind11 name
  bindings/pydrake/common/eigen_pybind.h
  bindings/pydrake/common/sorted_pair_pybind.h
Labels: status: single reviewer ok, release notes: none

#23497 [workspace] fix variable rename in metadata script
  tools/workspace/metadata.py
Labels: status: single reviewer ok

#23505 Amend docstrings for "Fix IrisZo bug ..."
  bindings/generated_docstrings/planning_iris.h
Labels: priority: emergency, status: single reviewer ok, release notes: none
