Repository RobotLocomotion/drake, pull requests merged in 2025-10, with the labels that each got.

#23443 [wheel] Refactor HOMEBREW_PREFIX computation in image/build-wheel.sh
  tools/wheel/image/build-wheel.sh
Labels: priority: low, release notes: none

#23498 Upgrade externals October 2025
  tools/workspace/dm_control_internal/repository.bzl
  tools/workspace/gymnasium_py_internal/repository.bzl
  tools/workspace/mujoco_menagerie_internal/repository.bzl
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/ros_xacro_internal/repository.bzl
  tools/workspace/spral_internal/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#23532 [doc] Add note on wait time for job requests
  doc/_pages/jenkins.md
Labels: release notes: none

#23512 [setup] Remove curl from test prereqs
  bindings/pydrake/geometry/test/visualizers_test.py
  geometry/test/meshcat_test.cc
  setup/ubuntu/source_distribution/packages-jammy-test-only.txt
  setup/ubuntu/source_distribution/packages-noble-test-only.txt
  tools/dynamic_analysis/drd.sh
  tools/dynamic_analysis/helgrind.sh
  tools/dynamic_analysis/valgrind.sh
Labels: priority: low, release notes: none

#23536 [ruff] Format examples/acrobot
  examples/acrobot/BUILD.bazel
  examples/acrobot/acrobot_io.py
  examples/acrobot/metrics.py
  examples/acrobot/optimizer_demo.py
  examples/acrobot/spong_sim.py
  examples/acrobot/test/acrobot_io_test.py
  examples/acrobot/test/metrics_test.py
  examples/acrobot/test/spong_sim_lib_py_test.py
  examples/acrobot/test/spong_sim_main_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23526 Fix Eigen-related constructor snafus in tests
  examples/multibody/cart_pole/test/cart_pole_test.cc
  math/test/rigid_transform_test.cc
  math/test/rotation_matrix_test.cc
  solvers/mixed_integer_rotation_constraint.cc
  solvers/test/mathematical_program_test.cc
  systems/primitives/test/affine_system_test.cc
  systems/primitives/test/multilayer_perceptron_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#23546 [ruff] Format multibody/parsing
  multibody/parsing/BUILD.bazel
  multibody/parsing/package_downloader.py
  multibody/parsing/test/package_downloader_stress_test.py
  multibody/parsing/test/package_downloader_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23552 [ruff] Format tools/install
  tools/install/BUILD.bazel
  tools/install/install_test.py
  tools/install/install_test_helper.py
  tools/install/installer.py
  tools/install/otool.py
  tools/install/test/install_meta_test.py
  tools/install/test/install_test_helper_test.py
  tools/install/test/installer_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23555 [ruff] Format tools/lint
  tools/lint/BUILD.bazel
  tools/lint/buildifier.py
  tools/lint/clang_format.py
  tools/lint/clang_format_lint.py
  tools/lint/drakelint.py
  tools/lint/install_lint_reporter.py
  tools/lint/library_lint_reporter.py
  tools/lint/test/buildifier_test.py
  tools/lint/test/util_test.py
  tools/lint/util.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23562 [ruff] Format tools/workspace/mkdoc_internal
  tools/workspace/mkdoc_internal/BUILD.bazel
  tools/workspace/mkdoc_internal/libclang_setup.py
  tools/workspace/mkdoc_internal/mkdoc.py
  tools/workspace/mkdoc_internal/mkdoc_comment.py
  tools/workspace/mkdoc_internal/test/mkdoc_comment_test.py
  tools/workspace/mkdoc_internal/test/sample_header_documentation_py_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23547 [ruff] Format multibody/plant/images
  multibody/plant/images/BUILD.bazel
  multibody/plant/images/ideal_stiction.py
  multibody/plant/images/stiction.py
  multibody/plant/images/test/scripts_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23550 [ruff] Format tools/clion
  tools/clion/BUILD.bazel
  tools/clion/test/bazel_wrapper_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23538 [ruff] Format examples/hardware_sim
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/hardware_sim.py
  examples/hardware_sim/test/hardware_sim_test_common.py
  examples/hardware_sim/test/robot_commander_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23543 [ruff] Format geometry/proximity
  geometry/proximity/BUILD.bazel
  geometry/proximity/test/refine_mesh_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23535 [ruff] Format doc
  doc/BUILD.bazel
  doc/build.py
  doc/defs.py
  doc/doxygen_cxx/BUILD.bazel
  doc/doxygen_cxx/build.py
  doc/doxygen_cxx/system_doxygen.py
  doc/doxygen_cxx/test/system_doxygen_test.py
  doc/pages.py
  doc/pydrake/BUILD.bazel
  doc/pydrake/build.py
  doc/pydrake/conf.py
  doc/pydrake/pydrake_sphinx_extension.py
  doc/styleguide/BUILD.bazel
  doc/styleguide/build.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23539 [ruff] Format examples/hydroelastic
  examples/hydroelastic/python_ball_paddle/BUILD.bazel
  examples/hydroelastic/python_ball_paddle/contact_sim_demo.py
  examples/hydroelastic/python_nonconvex_mesh/BUILD.bazel
  examples/hydroelastic/python_nonconvex_mesh/drop_pepper.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23542 [ruff] Format geometry
  geometry/BUILD.bazel
  geometry/test/meshcat_websocket_client.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23541 [ruff] Format examples/van_der_pol
  examples/van_der_pol/BUILD.bazel
  examples/van_der_pol/plot_limit_cycle.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23544 [ruff] Format geometry/render_gltf_client
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/test/acceptance_test.py
  geometry/render_gltf_client/test/integration_test.py
  geometry/render_gltf_client/test/server_demo.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23523 [setup] Remove diff and file as source prereqs
  common/BUILD.bazel
  common/resource_tool.cc
  setup/ubuntu/source_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-noble.txt
  tools/install/installer.py
  tools/lint/clang_format_lint.py
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated, release notes: fix

#23527 [geometry] Move CalcBarycentric to be non-inline
  bindings/generated_docstrings/geometry_proximity.h
  geometry/proximity/mesh_field_linear.h
  geometry/proximity/polygon_surface_mesh.cc
  geometry/proximity/polygon_surface_mesh.h
  geometry/proximity/triangle_surface_mesh.cc
  geometry/proximity/triangle_surface_mesh.h
  geometry/proximity/volume_mesh.cc
  geometry/proximity/volume_mesh.h
Labels: priority: low, status: single reviewer ok, release notes: none

#23561 [ruff] Format tools/workspace
  tools/workspace/BUILD.bazel
  tools/workspace/bzlmod_sync_test.py
  tools/workspace/cmake_configure_file.py
  tools/workspace/metadata.py
  tools/workspace/mirror_to_s3.py
  tools/workspace/new_release.py
  tools/workspace/vendor_cxx.py
  tools/workspace/vendor_cxx_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23533 [ruff] Format common
  common/BUILD.bazel
  common/test/cpu_capabilities_test.py
  common/test/drake_cc_googletest_main_test.py
  common/test/find_runfiles_subprocess_test.py
  common/test/resource_tool_installed_test.py
  common/test/resource_tool_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23534 [ruff] Format common/proto
  common/proto/BUILD.bazel
  common/proto/call_python_client.py
  common/proto/test/call_python_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23553 [ruff] Format tools/install/libdrake
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/build_components_refresh.py
  tools/install/libdrake/parse_version.py
  tools/install/libdrake/test/drake_python_dir_install_test.py
  tools/install/libdrake/test/exported_symbols_test.py
  tools/install/libdrake/test/header_dependency_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23557 [ruff] Format tools/release_engineering
  tools/release_engineering/BUILD.bazel
  tools/release_engineering/download_release_candidate.py
  tools/release_engineering/relnotes.py
  tools/release_engineering/repack_deb.py
Labels: priority: low, status: single reviewer ok, release notes: none

#23560 [ruff] Format tools/wheel
  tools/wheel/BUILD.bazel
  tools/wheel/macos/change_lpath.py
  tools/wheel/macos/strip_rpath.py
  tools/wheel/wheel_builder/common.py
  tools/wheel/wheel_builder/linux.py
  tools/wheel/wheel_builder/linux_types.py
  tools/wheel/wheel_builder/macos.py
  tools/wheel/wheel_builder/macos_types.py
  tools/wheel/wheel_builder/main.py
Labels: priority: low, status: single reviewer ok, release notes: none
