Repository RobotLocomotion/drake, pull requests merged in 2025-05, with the labels that each got.

#22955 [multibody] Add tests to show issues 9939 & 17429 are closed
  multibody/plant/test/multibody_plant_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#22956 [setup] Add explicit requirement for `lsb_release` on Linux wheel builds
  tools/wheel/image/packages-almalinux
Labels: priority: high, status: single reviewer ok, release notes: none

#22946 [fem] Support multiple BCs
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h
  multibody/fem/dirichlet_boundary_condition.cc
  multibody/fem/dirichlet_boundary_condition.h
  multibody/fem/fem_model.h
  multibody/fem/test/dirichlet_boundary_condition_test.cc
  multibody/plant/deformable_model.cc
Labels: priority: low, release notes: none

#22957 [solvers] Fix data races in IpoptSolver
  tools/workspace/ipopt_internal/patches/upstream/atomic.patch
  tools/workspace/ipopt_internal/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: none

#22952 Remove inverted elements from contact
  geometry/geometry_state.cc
  geometry/proximity/deformable_contact_geometries.cc
  geometry/proximity/deformable_contact_geometries.h
  geometry/proximity/deformable_contact_internal.cc
  geometry/proximity/deformable_contact_internal.h
  geometry/proximity/deformable_mesh_intersection.cc
  geometry/proximity/deformable_mesh_intersection.h
  geometry/proximity/test/deformable_contact_geometries_test.cc
  geometry/proximity/test/deformable_contact_internal_test.cc
  geometry/proximity/test/deformable_mesh_intersection_test.cc
  geometry/proximity/volume_to_surface_mesh.cc
  geometry/proximity/volume_to_surface_mesh.h
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/query_results/deformable_contact.cc
  geometry/query_results/deformable_contact.h
  geometry/query_results/test/deformable_contact_test.cc
  geometry/test/proximity_engine_test.cc
  multibody/plant/deformable_driver.cc
Labels: priority: high, release notes: none

#22916 [manipulation] Add more IiwaDriver config options
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc
  bindings/pydrake/manipulation/test/kuka_iiwa_test.py
  manipulation/kuka_iiwa/BUILD.bazel
  manipulation/kuka_iiwa/build_iiwa_control.cc
  manipulation/kuka_iiwa/build_iiwa_control.h
  manipulation/kuka_iiwa/iiwa_constants.cc
  manipulation/kuka_iiwa/iiwa_constants.h
  manipulation/kuka_iiwa/iiwa_driver.h
  manipulation/kuka_iiwa/iiwa_driver_functions.cc
  manipulation/kuka_iiwa/sim_iiwa_driver.cc
  manipulation/kuka_iiwa/sim_iiwa_driver.h
  manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
  manipulation/kuka_iiwa/test/iiwa7_wsg_renamed_weld_frames.dmd.yaml
  manipulation/kuka_iiwa/test/iiwa_driver_functions_test.cc
  manipulation/kuka_iiwa/test/sim_iiwa_driver_test.cc
Labels: release notes: newly deprecated, release notes: feature

#22965 [workspace] Upgrade curl_internal to latest release 8.13.0
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/package.BUILD.bazel
  tools/workspace/curl_internal/patches/upstream/49701094fcc8fc510af97e439ad46415342d367f.patch
  tools/workspace/curl_internal/patches/upstream/8f496d05b681f112225c839c8907b83aeebbf89b.patch
  tools/workspace/curl_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22940 [py common] Remove deprecated yaml features 2025-05
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/yaml_typed_test.py
  bindings/pydrake/common/yaml.py
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#22971 [workspace] Bump CRU with continuous joint math fixes
  tools/workspace/common_robotics_utilities_internal/package.BUILD.bazel
  tools/workspace/common_robotics_utilities_internal/repository.bzl
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#22962 [fem] Parallelize element computation
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/fem/BUILD.bazel
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
  multibody/fem/fem_model_impl.h
  multibody/fem/test/fem_model_test.cc
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/test/deformable_model_test.cc
Labels: release notes: none

#22931 Perform wheel builds in a unique directory
  tools/wheel/Dockerfile
  tools/wheel/README.rst
  tools/wheel/image/build-drake.sh
  tools/wheel/image/build-python.sh
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/provision-build.sh
  tools/wheel/image/provision-python.sh
  tools/wheel/macos/build-wheel.sh
  tools/wheel/macos/provision-test-python.sh
  tools/wheel/test/install-wheel.sh
  tools/wheel/test/provision.sh
  tools/wheel/test/test-wheel.sh
  tools/wheel/test/tests/hermetic/import-error-test.sh
  tools/wheel/wheel_builder/common.py
  tools/wheel/wheel_builder/linux.py
  tools/wheel/wheel_builder/macos.py
Labels: release notes: none

#22958 Test Fixtures and Cleanup for IrisZo (Part 3)
  planning/iris/test/iris_test_utilities.cc
  planning/iris/test/iris_test_utilities.h
  planning/iris/test/iris_zo_test.cc
Labels: release notes: none

#22961 Implement CalcNDotMatrix() for more mobilizers.
  multibody/tree/curvilinear_mobilizer.cc
  multibody/tree/curvilinear_mobilizer.h
  multibody/tree/planar_mobilizer.cc
  multibody/tree/planar_mobilizer.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/test/curvilinear_mobilizer_test.cc
  multibody/tree/test/planar_mobilizer_test.cc
  multibody/tree/test/quaternion_floating_mobilizer_test.cc
  multibody/tree/test/screw_mobilizer_test.cc
  multibody/tree/test/universal_mobilizer_test.cc
  multibody/tree/test/weld_mobilizer_test.cc
  multibody/tree/universal_mobilizer.cc
  multibody/tree/universal_mobilizer.h
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: priority: medium, status: squashing now, release notes: none

#22975 Fix meshcat capsule parsing
  geometry/meshcat.cc
  geometry/meshcat_types_internal.h
Labels: priority: high, status: single reviewer ok, release notes: none

#22980 Give deformable integration test more time
  multibody/plant/BUILD.bazel
Labels: status: single reviewer ok, release notes: none

#22972 [workspace] Upgrade gtest to latest release v1.17.0
  geometry/proximity/test/mesh_plane_intersection_test.cc
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  tools/workspace/gtest/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22914 Deformable parsing
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  examples/multibody/deformable/bubble_gripper.cc
  examples/multibody/deformable/deformable_torus.cc
  examples/multibody/deformable/models/bubbles.sdf
  examples/multibody/deformable/models/deformable_teddy.sdf
  examples/multibody/deformable/models/deformable_torus.sdf
  geometry/render/render_engine.cc
  geometry/render/render_engine.h
  geometry/render/test/render_engine_test.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/test/proximity_engine_test.cc
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/test/detail_dmd_parser_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/single_tet.vtk
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/test/deformable_model_test.cc
Labels: priority: high, release notes: none

#22983 Use NVI to consolidate code in MapAccelerationToQDDot().
  multibody/tree/mobilizer.cc
  multibody/tree/mobilizer.h
  multibody/tree/planar_mobilizer.cc
  multibody/tree/planar_mobilizer.h
  multibody/tree/prismatic_mobilizer.cc
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#22947 Implement a General Projected Gradient Descent Solver Interface
  solvers/BUILD.bazel
  solvers/projected_gradient_descent_solver.cc
  solvers/projected_gradient_descent_solver.h
  solvers/test/projected_gradient_descent_solver_test.cc
Labels: status: squashing now, release notes: feature

#22968 [fem] Add NeoHookean model
  bindings/pydrake/multibody/fem_py.cc
  bindings/pydrake/multibody/test/fem_test.py
  multibody/fem/BUILD.bazel
  multibody/fem/constitutive_model.h
  multibody/fem/deformable_body_config.h
  multibody/fem/linear_constitutive_model.cc
  multibody/fem/linear_constitutive_model.h
  multibody/fem/linear_corotated_model.cc
  multibody/fem/linear_corotated_model.h
  multibody/fem/matrix_utilities.cc
  multibody/fem/matrix_utilities.h
  multibody/fem/neohookean_model.cc
  multibody/fem/neohookean_model.h
  multibody/fem/neohookean_model_data.cc
  multibody/fem/neohookean_model_data.h
  multibody/fem/test/constitutive_model_test_utilities.cc
  multibody/fem/test/constitutive_model_test_utilities.h
  multibody/fem/test/corotated_model_test.cc
  multibody/fem/test/linear_constitutive_model_test.cc
  multibody/fem/test/linear_corotated_model_test.cc
  multibody/fem/test/matrix_utilities_test.cc
  multibody/fem/test/neohookean_model_data_test.cc
  multibody/fem/test/neohookean_model_test.cc
  multibody/fem/test/volumetric_element_test.cc
  multibody/fem/volumetric_element.h
  multibody/mpm/particle_data.cc
  multibody/mpm/particle_data.h
  multibody/plant/deformable_model.cc
Labels: status: squashing now, release notes: none

#22979 Use unique directory for macOS wheel tests
  tools/wheel/README.rst
  tools/wheel/image/provision-build.sh
  tools/wheel/macos/build-wheel.sh
  tools/wheel/macos/provision-test-python.sh
  tools/wheel/wheel_builder/common.py
  tools/wheel/wheel_builder/macos.py
Labels: release notes: none

#22987 ProjectedGradientDescentSolver Bugfix where the Wrong Projection Solver is Selected
  solvers/projected_gradient_descent_solver.cc
  solvers/test/projected_gradient_descent_solver_test.cc
  solvers/test/quadratic_program_examples.cc
  solvers/test/quadratic_program_examples.h
Labels: status: single reviewer ok, release notes: none

#22988 [tools] Remove ClpSolver memcheck suppressions
  tools/dynamic_analysis/valgrind.supp
Labels: status: single reviewer ok, release notes: none

#22976 [manipulation] Improve IiwaDriver wiring
  manipulation/kuka_iiwa/BUILD.bazel
  manipulation/kuka_iiwa/sim_iiwa_driver.cc
  manipulation/kuka_iiwa/test/sim_iiwa_driver_test.cc
Labels: priority: high, release notes: none

#22986 Python bindings for ProjectedGradientDescentSolver.
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py.cc
  bindings/pydrake/solvers/solvers_py.h
  bindings/pydrake/solvers/solvers_py_projected_gradient_descent.cc
  bindings/pydrake/solvers/test/projected_gradient_descent_solver_test.py
Labels: release notes: feature

#22982 Factor Out Common Options Between IRIS-ZO and IRIS-NP2
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py.cc
  bindings/pydrake/planning/planning_py.h
  bindings/pydrake/planning/planning_py_iris_common.cc
  bindings/pydrake/planning/planning_py_iris_zo.cc
  bindings/pydrake/planning/test/iris_test.py
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  planning/iris/BUILD.bazel
  planning/iris/iris_common.cc
  planning/iris/iris_common.h
  planning/iris/iris_zo.cc
  planning/iris/iris_zo.h
  planning/iris/test/iris_zo_test.cc
Labels: status: squashing now, release notes: fix, release notes: feature

#22984 [setup] Upgrade python venv (mac) to latest
  setup/python/pdm.lock
  setup/python/requirements.txt
  tools/workspace/python/venv_upgrade
Labels: priority: low, release notes: fix

#22989 Add EigenBlock3x3SparseSymmetricMatrix
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h
  multibody/contact_solvers/eigen_block_3x3_sparse_symmetric_matrix.cc
  multibody/contact_solvers/eigen_block_3x3_sparse_symmetric_matrix.h
  multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
  multibody/contact_solvers/test/eigen_block_3x3_sparse_symmetric_matrix_test.cc
Labels: release notes: none

#22992 Support Approximate Minimum Degree (AMD) ordering
  multibody/contact_solvers/minimum_degree_ordering.cc
  multibody/contact_solvers/minimum_degree_ordering.h
  multibody/contact_solvers/test/minimum_degree_ordering_test.cc
Labels: release notes: none

#22990 [fem] Parallel residual and tangent matrix computation
  multibody/fem/acceleration_newmark_scheme.cc
  multibody/fem/acceleration_newmark_scheme.h
  multibody/fem/discrete_time_integrator.cc
  multibody/fem/discrete_time_integrator.h
  multibody/fem/fem_element.h
  multibody/fem/fem_model.cc
  multibody/fem/fem_model.h
  multibody/fem/fem_model_impl.h
  multibody/fem/fem_solver.cc
  multibody/fem/test/discrete_time_integrator_test.cc
  multibody/fem/test/dummy_element.h
  multibody/fem/test/dummy_model.h
  multibody/fem/test/fem_element_test.cc
  multibody/fem/test/fem_model_test.cc
  multibody/fem/test/fem_solver_test.cc
  multibody/fem/test/volumetric_element_test.cc
  multibody/fem/test/volumetric_model_test.cc
  multibody/fem/velocity_newmark_scheme.cc
  multibody/fem/velocity_newmark_scheme.h
  multibody/fem/volumetric_element.h
  multibody/fem/volumetric_model.h
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/test/deformable_driver_contact_test.cc
Labels: priority: high, release notes: none

#23003 [deformable] Parse NeoHookean model
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: status: single reviewer ok, release notes: none

#22991 Use NVI to consolidate code in MapVelocityToQDot().
  multibody/tree/curvilinear_mobilizer.cc
  multibody/tree/curvilinear_mobilizer.h
  multibody/tree/mobilizer.h
  multibody/tree/planar_mobilizer.cc
  multibody/tree/planar_mobilizer.h
  multibody/tree/prismatic_mobilizer.cc
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/quaternion_floating_mobilizer.cc
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/rpy_ball_mobilizer.cc
  multibody/tree/rpy_ball_mobilizer.h
  multibody/tree/rpy_floating_mobilizer.cc
  multibody/tree/rpy_floating_mobilizer.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/universal_mobilizer.cc
  multibody/tree/universal_mobilizer.h
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#23007 [pydrake] Add python binding for DeformableModel::GetBodyIds
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
Labels: status: single reviewer ok, release notes: none

#23000 Move joint limits
  planning/BUILD.bazel
  planning/joint_limits.cc
  planning/joint_limits.h
  planning/test/joint_limits_test.cc
Labels: status: commits are properly curated, release notes: feature

#23004 GetBodiesKinematicallyAffectedBy no longer throws on welds
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: status: single reviewer ok, release notes: fix

#23002 [pydrake] Add binding for GeometryConfigurationVector.
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/test/scene_graph_test.py
Labels: status: single reviewer ok, release notes: none

#23006 Correct and improve rpy_ball_mobilizer documentation, replace E matrix with standard N matrix.
  multibody/tree/rpy_ball_mobilizer.cc
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: none

#23008 [pydrake] Add bindings for drake::planning::JointLimits
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py.cc
  bindings/pydrake/planning/planning_py.h
  bindings/pydrake/planning/planning_py_joint_limits.cc
  bindings/pydrake/planning/test/joint_limits_test.py
Labels: release notes: none

#23015 [py solvers] Partially revert "Remove deprecated API 2025-05"
  bindings/pydrake/solvers/solvers_py_options.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#23011 [pydrake] Add python binding for QueryObject::GetConfigurationsInWorld
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/test/scene_graph_test.py
Labels: status: single reviewer ok, release notes: feature

#23012 [fem] Use CG for linear solves
  examples/multibody/deformable/deformable_torus.cc
  examples/multibody/deformable/models/deformable_torus.sdf
  multibody/fem/BUILD.bazel
  multibody/fem/fem_solver.cc
  multibody/fem/fem_solver.h
  multibody/fem/test/fem_solver_test.cc
Labels: release notes: none

#23021 [doc] Fix typos in release notes
  doc/_release-notes/v1.41.0.md
Labels: priority: low, status: single reviewer ok, release notes: none

#23027 Fix symbolic mass matrix computation
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/parameter_conversion.h
  multibody/tree/spatial_inertia.cc
Labels: priority: high, release notes: fix

#23026 [deformable] Report reaction force for rigid bodies
  multibody/plant/BUILD.bazel
  multibody/plant/multibody_plant.cc
  multibody/plant/sap_driver.cc
  multibody/plant/test/deformable_box.sdf
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
Labels: status: squashing now, release notes: none

#22923 [tools] Push an official source code archive to GitHub releases
  .github/ISSUE_TEMPLATE/POST_RELEASE_ACTIONS.yml
  doc/_pages/from_source.md
  doc/_pages/release_playbook.md
  tools/release_engineering/dev/README.md
  tools/release_engineering/dev/push_release.py
Labels: release notes: fix

#23022 [doc] Update the release playbook
  doc/_pages/release_playbook.md
Labels: priority: low, status: single reviewer ok, release notes: none

#23033 [fem] Refactor ForceDensityField
  examples/multibody/deformable/point_source_force_field.cc
  examples/multibody/deformable/point_source_force_field.h
  multibody/fem/BUILD.bazel
  multibody/fem/fem_plant_data.h
  multibody/fem/force_density_field_base.cc
  multibody/fem/force_density_field_base.h
  multibody/fem/test/dummy_element.h
  multibody/fem/test/fem_element_test.cc
  multibody/fem/test/fem_model_test.cc
  multibody/fem/test/force_density_field_base_test.cc
  multibody/fem/test/volumetric_element_test.cc
  multibody/fem/volumetric_element.h
  multibody/plant/BUILD.bazel
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/force_density_field_declare_system_resources.cc
  multibody/plant/test/deformable_model_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/force_density_field.cc
  multibody/tree/force_density_field.h
  multibody/tree/multibody_tree_system.cc
  multibody/tree/multibody_tree_system.h
Labels: release notes: none

#23039 [solvers] SnoptSolver honors user requests to allocate extra memory
  solvers/csdp_solver.cc
  solvers/gurobi_solver.cc
  solvers/snopt_solver.cc
  solvers/test/snopt_solver_test.cc
Labels: priority: medium, release notes: fix

#23045 Add start_time to SimulatorConfig.
  systems/analysis/simulator_config.h
  systems/analysis/simulator_config_functions.cc
  systems/analysis/simulator_config_functions.h
  systems/analysis/simulator_gflags.cc
  systems/analysis/test/simulator_config_functions_test.cc
Labels: release notes: feature

#23047 [planning] Add JointLimits active DoF selecting constructor
  bindings/pydrake/planning/planning_py.cc
  bindings/pydrake/planning/planning_py_joint_limits.cc
  bindings/pydrake/planning/test/joint_limits_test.py
  planning/BUILD.bazel
  planning/joint_limits.cc
  planning/joint_limits.h
  planning/test/joint_limits_test.cc
Labels: release notes: feature

#23049 Fix errors flagged by Clang 20
  bindings/pydrake/geometry/geometry_py_meshes.cc
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/proof_of_life.cc
  examples/scene_graph/bouncing_ball_run_dynamics.cc
  geometry/proximity/test/make_cylinder_mesh_test.cc
  geometry/render_gl/test/multithread_safety_test.cc
  geometry/render_gl/test/thread_test.cc
  geometry/render_gltf_client/test/client_demo.cc
  manipulation/schunk_wsg/build_schunk_wsg_control.cc
  multibody/plant/test/tamsi_solver_test_util.h
  perception/test/point_cloud_test.cc
  systems/controllers/pid_controlled_system.cc
Labels: priority: low, status: single reviewer ok, release notes: fix

#23028 OSQP always reports primal and dual values regardless of the solver status.
  solvers/osqp_solver.cc
  solvers/osqp_solver.h
  solvers/test/mathematical_program_result_test.cc
  solvers/test/osqp_solver_test.cc
Labels: release notes: feature

#23038 [workspace] Upgrade vtk_internal to latest commit
  tools/workspace/vtk_internal/patches/upstream/io_import_errors.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: release notes: fix

#23054 [setup] Add missing Clang library on Noble
  setup/ubuntu/source_distribution/packages-noble-clang.txt
Labels: priority: medium, status: single reviewer ok, release notes: none
