Repository RobotLocomotion/drake, pull requests merged in 2025-01, with the labels that each got.

#22366 Touchup doc string for InverseDynamicsController
  systems/controllers/inverse_dynamics_controller.h
Labels: type: documentation, status: single reviewer ok, release notes: none

#22368 Remove deprecated code 2025-01
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/sensors_py_rgbd.cc
  bindings/pydrake/systems/test/sensors_test.py
  geometry/proximity/obj_to_surface_mesh.cc
  geometry/proximity/obj_to_surface_mesh.h
  geometry/proximity/test/obj_to_surface_mesh_test.cc
  manipulation/util/BUILD.bazel
  manipulation/util/meshlab_to_sdf.py
  manipulation/util/show_model.py
  multibody/tree/BUILD.bazel
  multibody/tree/frame.h
  multibody/tree/frame_base.cc
  multibody/tree/frame_base.h
  systems/sensors/rgbd_sensor.cc
  systems/sensors/rgbd_sensor.h
  systems/sensors/test/rgbd_sensor_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#22364 [setup] Remove dead code from macOS install_prereqs
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  tools/macos-arch-i386.bazelrc
Labels: priority: low, release notes: none

#22355 [build] Remove python venv_bin filegroup
  tools/install/BUILD.bazel
  tools/install/install_test.py
  tools/jupyter/BUILD.bazel
  tools/jupyter/test/jupyter_notebook_test.py
  tools/jupyter/test/jupyter_prereqs_test.py
  tools/workspace/python/package.BUILD.bazel
  tools/workspace/python/repository.bzl
Labels: priority: medium, release notes: none

#22352 [pydrake] Adjust RegisterGeometry bindings to avoid unique_ptr
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22354 [build] Adjust py_toolchain to directly depend on requirements
  tools/skylark/py.bzl
  tools/workspace/python/package.BUILD.bazel
  tools/workspace/python/repository.bzl
  tools/workspace/python/venv_sync
Labels: priority: medium, release notes: none

#22345 [pydrake] Remove some gratuitous uses of python repo constants
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/run_installed_fix_inertia.py
  bindings/pydrake/multibody/run_installed_mesh_to_model.py
  bindings/pydrake/visualization/BUILD.bazel
  bindings/pydrake/visualization/run_installed_meldis.py
  bindings/pydrake/visualization/run_installed_model_visualizer.py
  tools/workspace/stable_baselines3_internal/BUILD.bazel
Labels: priority: medium, status: single reviewer ok, release notes: none

#22351 [systems] LuenbergerObserver and KalmanFilter use shared_ptr
  bindings/pydrake/systems/estimators_py.cc
  systems/estimators/kalman_filter.cc
  systems/estimators/kalman_filter.h
  systems/estimators/luenberger_observer.cc
  systems/estimators/luenberger_observer.h
  systems/estimators/test/kalman_filter_test.cc
  systems/estimators/test/luenberger_observer_test.cc
Labels: priority: low, release notes: feature

#22357 [build] Remove two constants from python's version.bzl
  bindings/pydrake/BUILD.bazel
  tools/install/install.bzl
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake-config.cmake.in
  tools/skylark/pybind.bzl
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/python/repository.bzl
Labels: priority: medium, status: single reviewer ok, release notes: none

#22331 [workspace] Build IPOPT from source on macOS
  solvers/BUILD.bazel
  solvers/ipopt_solver.h
  solvers/solve.cc
  solvers/test/ipopt_solver_internal_test.cc
  solvers/test/solve_in_parallel_test.cc
  tools/install/libdrake/BUILD.bazel
  tools/wheel/image/dependencies/patches/mumps/patch.cmake
  tools/wheel/image/dependencies/patches/mumps/patch.diff
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/ipopt.cmake
  tools/wheel/image/dependencies/projects/mumps.cmake
  tools/workspace/BUILD.bazel
  tools/workspace/clp_internal/package.BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/ipopt/package.BUILD.bazel
  tools/workspace/ipopt/repository.bzl
  tools/workspace/ipopt_internal/BUILD.bazel
  tools/workspace/ipopt_internal/package.BUILD.bazel
  tools/workspace/ipopt_internal/repository.bzl
  tools/workspace/ipopt_internal/test/lint_test.py
  tools/workspace/ipopt_internal_pkgconfig/BUILD.bazel
  tools/workspace/ipopt_internal_pkgconfig/repository.bzl
  tools/workspace/mumps_internal/package-enabled.BUILD.bazel
  tools/workspace/mumps_internal/package-error.BUILD.bazel
  tools/workspace/mumps_internal/repository.bzl
Labels: priority: low, release notes: fix

#22335 [build] Modernize Bazel spelling for selecting compiler flags
  CMakeLists.txt
  cmake/bazel.rc.in
  tools/BUILD.bazel
  tools/cc_toolchain/BUILD.bazel
  tools/cc_toolchain/bazel.rc
  tools/lint/library_lint.bzl
  tools/skylark/drake_cc.bzl
  tools/skylark/pybind.bzl
  tools/ubuntu-noble.bazelrc
  tools/workspace/cc/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/fcl_internal/package.BUILD.bazel
Labels: priority: medium, release notes: newly deprecated

#22376 [workspace] Upgrade curl_internal to latest release curl-8_11_1
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22370 Add remaining menagerie models
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_examples_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  tools/workspace/mujoco_menagerie_internal/package.BUILD.bazel
  tools/workspace/mujoco_menagerie_internal/repository.bzl
Labels: release notes: none

#22385 [solvers] Ipopt uses SPRAL (not MUMPS) by default
  solvers/BUILD.bazel
  solvers/benchmarking/BUILD.bazel
  solvers/benchmarking/benchmark_ipopt_solver.cc
  solvers/ipopt_solver.h
  solvers/ipopt_solver_internal.cc
  solvers/solve.cc
  solvers/test/ipopt_solver_internal_test.cc
  tools/wheel/image/build-dependencies.sh
  tools/wheel/image/packages-jammy
  tools/workspace/default.bzl
Labels: priority: low, release notes: newly deprecated, release notes: fix

#22391 [wheel] Speed up local rebuilds
  tools/wheel/wheel_builder/common.py
Labels: priority: low, status: single reviewer ok, release notes: none

#22387 Fix "more than one orientation" error in mujoco parser
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_examples_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: fix

#22389 Mujoco parser: improve error message for "size from mesh"
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_examples_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: fix

#22395 [trajectories] Deprecate overriding public virtual functions
  bindings/pydrake/BUILD.bazel
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/BUILD.bazel
  common/trajectories/bezier_curve.cc
  common/trajectories/bezier_curve.h
  common/trajectories/bspline_trajectory.cc
  common/trajectories/bspline_trajectory.h
  common/trajectories/composite_trajectory.cc
  common/trajectories/composite_trajectory.h
  common/trajectories/derivative_trajectory.cc
  common/trajectories/derivative_trajectory.h
  common/trajectories/discrete_time_trajectory.cc
  common/trajectories/discrete_time_trajectory.h
  common/trajectories/exponential_plus_piecewise_polynomial.cc
  common/trajectories/exponential_plus_piecewise_polynomial.h
  common/trajectories/function_handle_trajectory.cc
  common/trajectories/function_handle_trajectory.h
  common/trajectories/path_parameterized_trajectory.cc
  common/trajectories/path_parameterized_trajectory.h
  common/trajectories/piecewise_constant_curvature_trajectory.cc
  common/trajectories/piecewise_constant_curvature_trajectory.h
  common/trajectories/piecewise_polynomial.cc
  common/trajectories/piecewise_polynomial.h
  common/trajectories/piecewise_pose.cc
  common/trajectories/piecewise_pose.h
  common/trajectories/piecewise_quaternion.cc
  common/trajectories/piecewise_quaternion.h
  common/trajectories/piecewise_trajectory.cc
  common/trajectories/piecewise_trajectory.h
  common/trajectories/stacked_trajectory.cc
  common/trajectories/stacked_trajectory.h
  common/trajectories/trajectory.cc
  common/trajectories/trajectory.h
Labels: priority: medium, status: single reviewer ok, release notes: newly deprecated

#22400 [workspace] Fix undefined behavior in spral LDLT
  tools/workspace/spral_internal/patches/upstream/pointer_math_undefined_behavior.patch
  tools/workspace/spral_internal/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: none

#22367 Clarify coordinates of MultibodyPlant's actuation input ports
  multibody/plant/multibody_plant.h
Labels: type: documentation, release notes: none

#22381 [setup] Upgrade Python venv (mac) to latest
  setup/python/pdm.lock
Labels: status: single reviewer ok, release notes: fix

#22402 fix: DiagnosticPolicy was going out of range if records were empty
  common/test_utilities/diagnostic_policy_test_base.h
Labels: status: single reviewer ok, release notes: none

#22388 [workspace] Upgrade ipopt_internal to latest release 3.14.17
  tools/workspace/ipopt_internal/package.BUILD.bazel
  tools/workspace/ipopt_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22392 [wheel] Remove vendored libcrypt
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/libxcrypt.cmake
  tools/workspace/python/repository.bzl
Labels: priority: low, release notes: fix

#22384 [workspace] Upgrade vtk_internal to latest commit
  geometry/render_vtk/internal_render_engine_vtk_base.cc
  tools/workspace/vtk_internal/patches/upstream/gltf_importer_from_stream.patch
  tools/workspace/vtk_internal/patches/vtkpugixml_hidden.patch
  tools/workspace/vtk_internal/repository.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22397 [multibody] Deprecate subclassing of MultibodyPlant
  multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/floating_body_test.cc
  multibody/test_utilities/floating_body_plant.cc
  multibody/test_utilities/floating_body_plant.h
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#22394 [pydrake] Fix yaml_dump_typed for Union on str
  bindings/pydrake/common/test/yaml_typed_test.py
  bindings/pydrake/common/yaml.py
Labels: priority: high, status: single reviewer ok, release notes: fix

#22318 Drake application yaml logic handles !!binary tag
  bindings/pydrake/common/test/yaml_typed_test.py
  bindings/pydrake/common/yaml.py
  common/yaml/test/example_structs.h
  common/yaml/test/json_test.cc
  common/yaml/test/yaml_read_archive_test.cc
  common/yaml/test/yaml_write_archive_test.cc
  common/yaml/yaml_node.h
  common/yaml/yaml_read_archive.cc
  common/yaml/yaml_read_archive.h
  common/yaml/yaml_write_archive.cc
  common/yaml/yaml_write_archive.h
  tools/workspace/yaml_cpp_internal/patches/upstream/b64_decode_failure_is_empty.patch
  tools/workspace/yaml_cpp_internal/repository.bzl
Labels: release notes: feature

#22406 [yaml] Hotfix for binary decoding error message
  common/yaml/yaml_read_archive.cc
Labels: priority: emergency, status: single reviewer ok, release notes: none

#22363 [workspace] Cherry-pick various patches from upstreams
  tools/workspace/abseil_cpp_internal/patches/upstream/civil_time_linkopts.patch
  tools/workspace/abseil_cpp_internal/patches/upstream/specific_iostream_includes.patch
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/clarabel_cpp_internal/patches/upstream/pr52.patch
  tools/workspace/clarabel_cpp_internal/repository.bzl
  tools/workspace/gz_math_internal/package.BUILD.bazel
  tools/workspace/gz_math_internal/patches/upstream/pr656.patch
  tools/workspace/gz_math_internal/repository.bzl
  tools/workspace/nlopt_internal/patches/upstream/pr582.patch
  tools/workspace/nlopt_internal/repository.bzl
  tools/workspace/sdformat_internal/patches/upstream/pr1522.patch
  tools/workspace/sdformat_internal/patches/upstream/pr1523.patch
  tools/workspace/sdformat_internal/patches/upstream/pr1524.patch
  tools/workspace/sdformat_internal/patches/upstream/support_drake_visual.patch
  tools/workspace/sdformat_internal/repository.bzl
  tools/workspace/uwebsockets_internal/patches/upstream/pr1828.patch
  tools/workspace/uwebsockets_internal/repository.bzl
  tools/workspace/yaml_cpp_internal/patches/upstream/pr1303.patch
  tools/workspace/yaml_cpp_internal/patches/upstream/pr1336.patch
  tools/workspace/yaml_cpp_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#22398 [workspace] Factor to single point of control for Fortran
  tools/workspace/gfortran/BUILD.bazel
  tools/workspace/gfortran/fortran.bzl
  tools/workspace/snopt/package.BUILD.bazel
  tools/workspace/snopt/repository.bzl
  tools/workspace/spral_internal/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#22078 [solvers] SolverOptions is serializable
  bindings/pydrake/common/serialize_pybind.h
  bindings/pydrake/geometry/test/optimization_test.py
  bindings/pydrake/planning/test/graph_algorithms_test.py
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/solvers_py_options.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc
  solvers/BUILD.bazel
  solvers/mathematical_program.h
  solvers/solver_options.cc
  solvers/solver_options.h
  solvers/specific_options.cc
  solvers/specific_options.h
  solvers/test/mathematical_program_test.cc
  solvers/test/solver_base_test.cc
  solvers/test/solver_options_test.cc
  solvers/test/specific_options_test.cc
Labels: priority: medium, release notes: newly deprecated, release notes: feature

#22410 [py yaml] Deprecate certain implicit primitive conversions
  bindings/pydrake/common/BUILD.bazel
  bindings/pydrake/common/test/yaml_typed_test.py
  bindings/pydrake/common/yaml.py
  common/yaml/test/example_structs.h
  common/yaml/test/yaml_read_archive_test.cc
Labels: status: single reviewer ok, release notes: newly deprecated

#22401 [mujoco parser] Fix debug throw from RotationalInertia
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_examples_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/tree/geometry_spatial_inertia.cc
Labels: release notes: fix

#22346 [build] Use py_cc_toolchain for configuring pybind11
  CMakeLists.txt
  MODULE.bazel
  cmake/WORKSPACE.bzlmod.in
  cmake/bazel.rc.in
  tools/bazel.rc
  tools/install/install.bzl
  tools/install/libdrake/BUILD.bazel
  tools/py_toolchain/BUILD.bazel
  tools/skylark/pybind.bzl
  tools/workspace/default.bzl
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/pybind11/package.BUILD.bazel
  tools/workspace/python/BUILD.bazel
  tools/workspace/python/defs.bzl
  tools/workspace/python/package.BUILD.bazel
  tools/workspace/python/repository.bzl
Labels: priority: medium, release notes: newly deprecated, release notes: fix

#22407 [solvers] Change solver names to upstream's preferred case
  bindings/pydrake/solvers/test/clp_solver_test.py
  bindings/pydrake/solvers/test/ipopt_solver_test.py
  solvers/clp_solver_common.cc
  solvers/ipopt_solver_common.cc
  solvers/mosek_solver_common.cc
Labels: priority: high, release notes: fix

#22278 Unify RotationalInertia validity tests and exception messages.
  multibody/tree/rotational_inertia.cc
  multibody/tree/rotational_inertia.h
  multibody/tree/test/rotational_inertia_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#22404 DiagnosticPolicyTestBase cleanups
  common/test_utilities/diagnostic_policy_test_base.h
Labels: status: single reviewer ok, release notes: none

#22393 [build] Use modern spelling for Bazel config options
  bindings/pydrake/solvers/BUILD.bazel
  doc/_pages/stable.md
  solvers/BUILD.bazel
  solvers/defs.bzl
  solvers/test/disabled_solvers_test.cc
  tools/BUILD.bazel
  tools/bazel.rc
  tools/dynamic_analysis/bazel.rc
  tools/flags/BUILD.bazel
  tools/install/libdrake/BUILD.bazel
  tools/skylark/drake_cc.bzl
  tools/workspace/BUILD.bazel
  tools/workspace/clarabel_cpp_internal/BUILD.bazel
  tools/workspace/clp_internal/BUILD.bazel
  tools/workspace/csdp_internal/BUILD.bazel
  tools/workspace/gurobi/BUILD.bazel
  tools/workspace/ipopt_internal/BUILD.bazel
  tools/workspace/mosek/BUILD.bazel
  tools/workspace/nlopt_internal/BUILD.bazel
  tools/workspace/osqp_internal/BUILD.bazel
  tools/workspace/scs_internal/BUILD.bazel
  tools/workspace/snopt/BUILD.bazel
Labels: priority: low, release notes: fix

#22417 [workspace] Refresh our patch to spral_internal
  tools/workspace/spral_internal/patches/upstream/pointer_math_undefined_behavior.patch
  tools/workspace/spral_internal/patches/upstream/pr222.patch
  tools/workspace/spral_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#22069 [geometry] Adds new CompliantCompliant intersection algorithm
  geometry/proximity/BUILD.bazel
  geometry/proximity/field_intersection.cc
  geometry/proximity/field_intersection.h
  geometry/proximity/hydroelastic_calculator.cc
  geometry/proximity/mesh_plane_intersection.cc
  geometry/proximity/mesh_plane_intersection.h
  geometry/proximity/test/field_intersection_test.cc
  geometry/proximity/test/hydroelastic_calculator_test.cc
Labels: release notes: none

#22418 [parsing] Delete FormatFirstError; fix call sites
  common/test_utilities/diagnostic_policy_test_base.h
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: status: single reviewer ok, release notes: none

#22411 [workspace] Upgrade abseil_cpp_internal to latest commit
  tools/workspace/abseil_cpp_internal/patches/upstream/civil_time_linkopts.patch
  tools/workspace/abseil_cpp_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22416 Mujoco examples skip slow debug only
  multibody/parsing/test/detail_mujoco_parser_examples_test.cc
Labels: release notes: none

#22414 Mujoco bad inertia test case
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/parsing/test/neg_volume.obj
Labels: release notes: none

#22422 [workspace] Fix typo in deprecation.bzl
  tools/workspace/deprecation.bzl
Labels: priority: medium, status: single reviewer ok, release notes: none

#22353 [geometry] Add RenderEngine support for shared_ptr
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/test/render_engine_subclass_test.py
  bindings/pydrake/geometry/test/render_test.py
  geometry/geometry_state.cc
  geometry/geometry_state.h
  geometry/render/render_engine.cc
  geometry/render/render_engine.h
  geometry/render/test/render_engine_test.cc
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/geometry_state_test.cc
  geometry/test/scene_graph_test.cc
Labels: priority: low, release notes: breaking change, release notes: feature

#22399 [py trajectories] Adjust Clone and MakeDerivative for unique_ptr
  bindings/pydrake/_trajectories_extra.py
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/BUILD.bazel
  common/trajectories/test/wrapped_trajectory_test.cc
  common/trajectories/wrapped_trajectory.cc
  common/trajectories/wrapped_trajectory.h
Labels: priority: low, release notes: none

#22338 [build] Use MODULE.bazel for all dependencies
  CMakeLists.txt
  MODULE.bazel
  WORKSPACE.bzlmod
  cmake/MODULE.bazel.in
  cmake/WORKSPACE.bzlmod.in
  cmake/bazel.rc.in
  doc/_pages/stable.md
  tools/bazel.rc
  tools/clion/bazel_wrapper
  tools/clion/test/bazel_wrapper_test.py
  tools/install/install.bzl
  tools/install/libdrake/header_lint.bzl
  tools/skylark/pybind.bzl
  tools/wheel/wheel_builder/common.py
  tools/workspace/crate_universe/upgrade.sh
  tools/workspace/default.bzl
  tools/workspace/drake_models/test/parse_test.py
  tools/workspace/java.bzl
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/lcm/test/no_lcm_warnings_test.py
  tools/workspace/pkg_config.BUILD.tpl
  tools/workspace/pkg_config.bzl
  tools/workspace/pybind11/BUILD.bazel
  tools/workspace/workspace_bzlmod_sync_test.py
Labels: priority: medium, release notes: feature

#22429 [build] Hotfix doc builds for MODULE.bazel respelling
  doc/styleguide/build.py
Labels: priority: emergency, status: single reviewer ok, release notes: none

#22430 [build] Hotfix CTest regex for MODULE.bazel build output
  CTestCustom.cmake.in
Labels: priority: emergency, status: single reviewer ok, release notes: none

#22428 [build] Hotfix wheel builds for MODULE.bazel respelling
  tools/wheel/wheel_builder/common.py
Labels: priority: high, status: single reviewer ok, release notes: none

#22424 Adds MathematicalProgram::AddQuadraticCost w*|x-x_d|^2
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: release notes: feature

#22433 [build] Hotfix CMake builds for MODULE.bazel respelling
  CMakeLists.txt
Labels: priority: high, status: single reviewer ok, release notes: none

#22435 [build] Hotfix macOS CMake builds for MODULE.bazel
  cmake/MODULE.bazel.in
Labels: priority: high, status: single reviewer ok, release notes: none

#22420 [build] Change how CMake details are printed
  CMakeLists.txt
  cmake/bazel.rc.in
Labels: priority: medium, release notes: none

#22423 [common] Enable AVX512 when available
  common/BUILD.bazel
  common/cpu_capabilities.cc
  common/cpu_capabilities.h
  common/hwy_dynamic_impl.h
  common/test/cpu_capabilities_test.py
  common/test/cpu_capabilities_test_device.cc
  doc/doxygen_cxx/doxygen.h
Labels: priority: medium, release notes: feature

#22359 [solvers] Fix MobyLCPSolver to use Drake logging not cerr
  solvers/moby_lcp_solver.cc
  solvers/moby_lcp_solver.h
  solvers/test/moby_lcp_solver_test.cc
Labels: priority: low, status: single reviewer ok, release notes: newly deprecated

#22379 [workspace] Upgrade lcm to latest release v1.5.1
  tools/workspace/lcm/lcm-config-version.cmake
  tools/workspace/lcm/lcm-config.cmake
  tools/workspace/lcm/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22431 [build] Silence console spam from the snopt repository rule
  tools/workspace/snopt/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#22439 [build] Hotfix macOS wheel builds for MODULE.bazel
  tools/wheel/macos/build-wheel.sh
Labels: priority: high, status: single reviewer ok, release notes: none

#22408 Update drake_models to get atlas w/ textures
  tools/workspace/drake_models/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22421 [build] CMake prefers find_package over pkg-config
  CMakeLists.txt
  tools/wheel/image/build-drake.sh
Labels: priority: medium, release notes: fix

#22390 Add functionality to create Convex shapes from vertices
  geometry/optimization/test/vpolytope_test.cc
  geometry/optimization/vpolytope.cc
  geometry/optimization/vpolytope.h
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/test/shape_specification_test.cc
Labels: status: squashing now, release notes: feature

#22426 Relax the tolerance in IpoptSolver.
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
  solvers/ipopt_solver.cc
  solvers/test/ipopt_solver_test.cc
  solvers/test/optimization_examples.cc
Labels: release notes: fix

#22434 Add mujoco to parsing docs; parsing to troubleshooting.html
  doc/_config.yml
  doc/_pages/troubleshooting.md
  multibody/parsing/parsing_doxygen.h
  tutorials/authoring_multibody_simulation.ipynb
Labels: type: documentation, release notes: none

#22451 [py parsing] Fix signatures to use Python types (not C++)
  bindings/pydrake/multibody/parsing_py.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#22447 Revert "[workspace] Upgrade lcm to latest release v1.5.1"
  tools/workspace/lcm/lcm-config-version.cmake
  tools/workspace/lcm/lcm-config.cmake
  tools/workspace/lcm/repository.bzl
Labels: status: single reviewer ok, release notes: none

#22453 [py framework] Fix signatures to use Python types (not C++)
  bindings/pydrake/systems/framework_py_semantics.cc
Labels: priority: medium, release notes: none

#22443 [build] Fix github local_repository_override for bzlmod
  tools/workspace/github.bzl
Labels: priority: medium, status: single reviewer ok, release notes: none

#22442 Add bindings for Convex construction from points
  bindings/pydrake/geometry/geometry_py_common.cc
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/common_test.py
  bindings/pydrake/geometry/test/optimization_test.py
Labels: status: single reviewer ok, release notes: fix

#22446 [mujoco parser] implement "ref" attribute for joints
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: priority: medium, release notes: feature

#22452 [py solvers] Fix signatures to use Python types (not C++)
  bindings/pydrake/solvers/BUILD.bazel
  bindings/pydrake/solvers/solvers_py.cc
  bindings/pydrake/solvers/solvers_py.h
  bindings/pydrake/solvers/solvers_py_ids.cc
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#22449 Update MathematicalProgram::AddExponentialConeConstraint Documentation…
  solvers/mathematical_program.h
Labels: release notes: none

#22378 Improve how we manage which PDM to use
  setup/BUILD.bazel
  setup/python/pyproject.toml
  setup/python/requirements.txt
  setup/python/requirements.txt.in
  tools/workspace/python/repository.bzl
  tools/workspace/python/venv_sync
  tools/workspace/python/venv_upgrade
Labels: release notes: none

#22409 Update styleguide commit and sha256
  tools/workspace/styleguide/repository.bzl
Labels: release notes: fix

#22458 [workspace] Upgrade lcm to latest release v1.5.1
  tools/workspace/lcm/lcm-config-version.cmake
  tools/workspace/lcm/lcm-config.cmake
  tools/workspace/lcm/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22459 [tools] Disable ASLR during TSan
  tools/dynamic_analysis/tsan.sh
Labels: priority: high, status: single reviewer ok, release notes: none

#22432 [build] Use eigen, fmt, spdlog from bzlmod
  CMakeLists.txt
  MODULE.bazel
  bindings/pydrake/common/text_logging_pybind.cc
  cmake/bazel.rc.in
  cmake/external/workspace/eigen/BUILD.bazel.in
  cmake/external/workspace/eigen/MODULE.bazel.in
  cmake/external/workspace/fmt/BUILD.bazel.in
  cmake/external/workspace/fmt/MODULE.bazel.in
  cmake/external/workspace/spdlog/BUILD.bazel.in
  cmake/external/workspace/spdlog/MODULE.bazel.in
  tools/bazel.rc
  tools/flags/BUILD.bazel
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/header_lint.bzl
  tools/skylark/drake_cc.bzl
  tools/wheel/image/build-drake.sh
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/eigen.cmake
  tools/wheel/macos/build-wheel.sh
  tools/workspace/BUILD.bazel
  tools/workspace/alias.bzl
  tools/workspace/default.bzl
  tools/workspace/eigen/BUILD.bazel
  tools/workspace/eigen/repository.bzl
  tools/workspace/fmt/BUILD.bazel
  tools/workspace/fmt/fmt-config-version.cmake
  tools/workspace/fmt/fmt-config.cmake
  tools/workspace/fmt/package.BUILD.bazel
  tools/workspace/fmt/repository.bzl
  tools/workspace/os.bzl
  tools/workspace/pkg_config.bzl
  tools/workspace/rules_cc/repository.bzl
  tools/workspace/spdlog/BUILD.bazel
  tools/workspace/spdlog/package.BUILD.bazel
  tools/workspace/spdlog/repository.bzl
  tools/workspace/workspace_bzlmod_sync_test.py
Labels: priority: medium, release notes: feature

#22456 [workspace] Disable unwanted highway targets globally
  common/BUILD.bazel
  common/test/hwy_dynamic_test.cc
  geometry/proximity/BUILD.bazel
  geometry/proximity/test/boxes_overlap_test.cc
  math/BUILD.bazel
  math/fast_pose_composition_functions.cc
  math/test/fast_pose_composition_functions_test.cc
  tools/workspace/highway_internal/patches/disabled_targets.patch
  tools/workspace/highway_internal/repository.bzl
Labels: priority: low, release notes: none

#22465 [build] Hotfix for legacy downstreams that reuse our spdlog
  tools/workspace/spdlog/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: none

#22466 Move RotationalInertia code from .h file to .cc file.
  multibody/tree/rotational_inertia.cc
  multibody/tree/rotational_inertia.h
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: none

#22467 [build] Hotfix for drake_cmake_external
  cmake/bazel.rc.in
  tools/install/libdrake/BUILD.bazel
  tools/wheel/image/build-drake.sh
  tools/wheel/macos/build-wheel.sh
Labels: priority: high, status: single reviewer ok, release notes: none

#22455 [py framework] Setting context values now clones instead of owns
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
Labels: priority: low, release notes: fix

#22350 [multibody] Add CurvilinearJoint (#22196)
  common/trajectories/BUILD.bazel
  common/trajectories/piecewise_constant_curvature_trajectory.cc
  common/trajectories/piecewise_constant_curvature_trajectory.h
  common/trajectories/test/piecewise_constant_curvature_trajectory_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/body_node_impl.cc
  multibody/tree/body_node_impl_mass_matrix.cc
  multibody/tree/curvilinear_joint.cc
  multibody/tree/curvilinear_joint.h
  multibody/tree/curvilinear_mobilizer.cc
  multibody/tree/curvilinear_mobilizer.h
  multibody/tree/test/curvilinear_joint_test.cc
  multibody/tree/test/curvilinear_mobilizer_test.cc
Labels: status: squashing now, release notes: feature

#22468 Avoid spdlog in inlined header functions
  common/scoped_singleton.h
  common/symbolic/expression/test/expression_matrix_test.cc
  common/test_utilities/eigen_matrix_compare.h
  examples/planar_gripper/planar_gripper_common.cc
  geometry/optimization/convex_set.cc
  geometry/optimization/cspace_free_internal.cc
  geometry/optimization/cspace_free_polytope.cc
  geometry/optimization/cspace_free_polytope_base.cc
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/hpolyhedron.cc
  geometry/optimization/hyperrectangle.cc
  geometry/optimization/iris.cc
  geometry/optimization/test/graph_of_convex_sets_test.cc
  geometry/optimization/test/iris_in_configuration_space_test.cc
  geometry/proximity/deformable_contact_geometries.h
  geometry/proximity/deformable_contact_internal.cc
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/hydroelastic_internal.h
  geometry/render_gl/test/thread_test.cc
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  geometry/scene_graph.cc
  manipulation/util/make_arm_controller_model.cc
  manipulation/util/move_ik_demo_base.cc
  manipulation/util/robot_plan_utils.cc
  multibody/contact_solvers/newton_with_bisection.h
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc
  multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc
  multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc
  multibody/meshcat/joint_sliders.cc
  multibody/optimization/toppra.cc
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_usd_parser.cc
  multibody/parsing/model_directives.cc
  multibody/parsing/model_directives.h
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/parser_manual_test.cc
  multibody/parsing/test/process_model_directives_test.cc
  multibody/tree/spatial_inertia.h
  planning/collision_checker.cc
  planning/iris/iris_from_clique_cover.cc
  planning/iris/iris_zo.cc
  planning/iris/test/iris_zo_test.cc
  planning/scene_graph_collision_checker.cc
  planning/test/scene_graph_collision_checker_test.cc
  planning/test_utilities/collision_checker_abstract_test_suite.cc
  planning/visibility_graph.cc
  solvers/test/mathematical_program_test.cc
  systems/analysis/integrator_base.cc
  systems/analysis/integrator_base.h
  systems/analysis/test/lyapunov_test.cc
  systems/framework/dependency_tracker.cc
  systems/framework/dependency_tracker.h
  systems/framework/system.cc
  systems/framework/system_base.cc
  systems/lcm/lcm_config_functions.cc
  visualization/meshcat_pose_sliders.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22450 [pydrake] Fail-fast when C++ types infect function signatures
  bindings/pydrake/common/test/ref_cycle_test_util_py.cc
  bindings/pydrake/common/test/serialize_import_failure_test.py
  tools/skylark/pybind.bzl
  tools/workspace/pybind11/patches/check_signature_infection.patch
  tools/workspace/pybind11/repository.bzl
Labels: priority: low, release notes: none

#22472 Clang formats some of the files in multibody/parsing
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: type: cleanup, status: single reviewer ok, release notes: none

#22413 [doc] Add release notes v1.37.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.37.0.md
  tools/release_engineering/relnotes.py
Labels: status: squashing now, release notes: none

#22369 Makes GCS clonable and implements ImplicitGcsFromExplicit
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/test/optimization_test.py
  geometry/optimization/graph_of_convex_sets.cc
  geometry/optimization/graph_of_convex_sets.h
  geometry/optimization/implicit_graph_of_convex_sets.cc
  geometry/optimization/implicit_graph_of_convex_sets.h
  geometry/optimization/test/graph_of_convex_sets_test.cc
  geometry/optimization/test/implicit_graph_of_convex_sets_test.cc
Labels: release notes: feature

#22473 Use separate project to manage PDM
  setup/python/pyproject.toml
  tools/workspace/python/venv_upgrade
Labels: release notes: none

#22463 [py lcm] Adjust CreateDefaultValue to avoid unique_ptr
  bindings/pydrake/systems/lcm_py.cc
Labels: priority: low, release notes: none

#21561 [planning] Add voxelized environment collision checker and supporting tools to planning/dev
  planning/BUILD.bazel
  planning/dev/BUILD.bazel
  planning/dev/mbp_environment_collision_checker.cc
  planning/dev/mbp_environment_collision_checker.h
  planning/dev/sphere_robot_model_collision_checker.cc
  planning/dev/sphere_robot_model_collision_checker.h
  planning/dev/test/mbp_environment_collision_checker_test.cc
  planning/dev/test/sphere_robot_model_collision_checker_abstract_test_suite.cc
  planning/dev/test/sphere_robot_model_collision_checker_abstract_test_suite.h
  planning/dev/test/voxel_self_filter_test.cc
  planning/dev/test/voxel_test1.sdf
  planning/dev/test/voxel_test2.sdf
  planning/dev/test/voxelized_environment_builder_test.cc
  planning/dev/test/voxelized_environment_collision_checker_test.cc
  planning/dev/voxel_collision_map.cc
  planning/dev/voxel_collision_map.h
  planning/dev/voxel_collision_map_internal.cc
  planning/dev/voxel_collision_map_internal.h
  planning/dev/voxel_grid_internal.h
  planning/dev/voxel_self_filter.cc
  planning/dev/voxel_self_filter.h
  planning/dev/voxel_self_filter_internal.h
  planning/dev/voxel_signed_distance_field.cc
  planning/dev/voxel_signed_distance_field.h
  planning/dev/voxel_signed_distance_field_internal.cc
  planning/dev/voxel_signed_distance_field_internal.h
  planning/dev/voxel_tagged_object_collision_map.cc
  planning/dev/voxel_tagged_object_collision_map.h
  planning/dev/voxel_tagged_object_collision_map_internal.cc
  planning/dev/voxel_tagged_object_collision_map_internal.h
  planning/dev/voxelized_environment_builder.cc
  planning/dev/voxelized_environment_builder.h
  planning/dev/voxelized_environment_builder_internal.h
  planning/dev/voxelized_environment_collision_checker.cc
  planning/dev/voxelized_environment_collision_checker.h
Labels: status: squashing now, release notes: none

#22437 Use PDM to manage macOS wheel dependencies
  setup/python/pdm.lock
  setup/python/pyproject.toml
  tools/wheel/image/provision-python.sh
  tools/wheel/macos/build-wheel.sh
  tools/wheel/wheel_builder/macos.py
  tools/workspace/python/repository.bzl
Labels: release notes: none

#22470 [py systems] Change how ValueProducer callbacks work
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/value_producer_pybind.cc
  bindings/pydrake/systems/value_producer_pybind.h
  systems/framework/leaf_system.h
  systems/framework/value_producer.h
Labels: priority: low, release notes: none

#22479 [systems] Clarify doc that AllocateContext is a trap
  systems/framework/system.h
Labels: priority: low, status: single reviewer ok, release notes: none

#22486 Disable TSAN on voxel_self_filter_test
  planning/dev/BUILD.bazel
Labels: priority: high, status: single reviewer ok, release notes: none

#22427 Parameterize RgbdSensorAsync
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/sensors_py_rgbd.cc
  bindings/pydrake/systems/test/sensors_test.py
  systems/sensors/BUILD.bazel
  systems/sensors/rgbd_sensor_async.cc
  systems/sensors/rgbd_sensor_async.h
  systems/sensors/test/rgbd_sensor_async_test.cc
Labels: release notes: newly deprecated, release notes: feature

#22485 [planning] Fix GetParam-based gtest names
  planning/dev/BUILD.bazel
  planning/dev/test/mbp_environment_collision_checker_test.cc
  planning/dev/test/sphere_robot_model_collision_checker_abstract_test_suite.cc
  planning/dev/test/sphere_robot_model_collision_checker_abstract_test_suite.h
  planning/dev/test/voxelized_environment_collision_checker_test.cc
  planning/test_utilities/BUILD.bazel
  planning/test_utilities/collision_checker_abstract_test_suite.cc
Labels: priority: high, release notes: none

#22481 [mujoco parser] upgrade unsupported mesh to error
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_examples_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  tools/workspace/mujoco_menagerie_internal/package.BUILD.bazel
Labels: release notes: fix

#22487 Improve meshcat mtl processing
  geometry/meshcat.cc
  geometry/test/meshcat_test.cc
Labels: status: single reviewer ok, release notes: fix

#22492 Fix model_visualizer --show_rgbd_sensor on Ubuntu
  bindings/pydrake/visualization/_model_visualizer.py
Labels: priority: medium, status: single reviewer ok, release notes: fix

#22503 [setup] Upgrade Python venv (mac) to latest
  setup/python/pdm.lock
  setup/python/requirements.txt
Labels: priority: low, status: single reviewer ok, release notes: fix

#22501 [multibody/meshcat] Enable clang-format-lint
  multibody/meshcat/BUILD.bazel
  multibody/meshcat/contact_visualizer.h
  multibody/meshcat/hydroelastic_contact_visualizer.h
  multibody/meshcat/joint_sliders.cc
  multibody/meshcat/point_contact_visualizer.cc
  multibody/meshcat/test/contact_visualizer_test.cc
  multibody/meshcat/test/hydroelastic_contact_visualizer_test.cc
  multibody/meshcat/test/joint_sliders_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#22478 [pydrake] Factor out make_shared_ptr_from_py_object for reuse
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/pydrake_pybind.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#22425 [planning] Deprecate MaxCliqueSolverBase::Clone
  bindings/pydrake/planning/planning_py_graph_algorithms.cc
  planning/graph_algorithms/max_clique_solver_base.cc
  planning/graph_algorithms/max_clique_solver_base.h
  planning/graph_algorithms/min_clique_cover_solver_base.cc
  planning/graph_algorithms/min_clique_cover_solver_base.h
  planning/graph_algorithms/min_clique_cover_solver_via_greedy.cc
  planning/graph_algorithms/min_clique_cover_solver_via_greedy.h
  planning/graph_algorithms/test/max_clique_solver_via_greedy_test.cc
  planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc
  planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc
Labels: priority: low, release notes: breaking change, release notes: newly deprecated

#22333 Find correct python3 version in pybind11-config
  tools/workspace/pybind11/pybind11-config.cmake
Labels: release notes: none

#22495 Meschat AddSlider and SetSliderValue return rounded/truncated value
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/test/meshcat_test.cc
Labels: release notes: feature

#22502 [inverse_kinematics] Fix plant lifetime in AddMultibodyPlantConstraints
  bindings/pydrake/multibody/inverse_kinematics_py.cc
  multibody/inverse_kinematics/add_multibody_plant_constraints.cc
  multibody/inverse_kinematics/add_multibody_plant_constraints.h
  multibody/inverse_kinematics/inverse_kinematics.cc
  multibody/inverse_kinematics/test/add_multibody_plant_constraints_test.cc
Labels: priority: medium, release notes: fix

#22461 [doc] Streamline Drake build instructions
  doc/_pages/bazel.md
  doc/_pages/developers.md
  doc/_pages/documentation_instructions.md
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/defs.bzl
  doc/pydrake/build.py
  setup/install_prereqs
  setup/mac/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs.sh
Labels: priority: medium, release notes: fix

#22499 [wheel] Remove JDK from dependencies
  tools/wheel/image/build-drake.sh
  tools/wheel/image/packages-jammy
Labels: priority: low, status: single reviewer ok, release notes: none

#22454 [workspace] Upgrade drake_models to latest commit
  tools/workspace/drake_models/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22490 [framework] Fix diagram scalar conversion losing external constraints
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/scalar_conversion_test.py
  systems/framework/diagram.cc
  systems/framework/system.h
  systems/framework/system_scalar_conversion_doxygen.h
  systems/framework/test/diagram_test.cc
Labels: priority: medium, release notes: fix

#22506 [workspace] Tweak glob in pybind11 rules
  tools/workspace/pybind11/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#22482 [build] Adjust new_release for bzlmod spellings
  MODULE.bazel
  tools/workspace/metadata.bzl
  tools/workspace/metadata.py
Labels: priority: medium, release notes: none

#22494 [build] Dynamically load GL/GLX/EGL/OpenGL
  MODULE.bazel
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/troubleshooting.md
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_loaders.cc
  geometry/render_gl/internal_loaders.h
  geometry/render_gl/internal_opengl_context.cc
  geometry/render_gl/internal_opengl_includes.h
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/internal_make_render_window.cc
  geometry/render_vtk/test/internal_render_engine_vtk_no_display_test.cc
  tools/wheel/content/INSTALLATION
  tools/wheel/image/packages-jammy
  tools/workspace/default.bzl
  tools/workspace/glx/repository.bzl
  tools/workspace/opengl/package.BUILD.bazel
  tools/workspace/opengl/repository.bzl
  tools/workspace/vtk_internal/settings.bzl
Labels: priority: medium, release notes: newly deprecated, release notes: fix

#22480 [lcmtypes] Add benchmark
  lcmtypes/benchmarking/BUILD.bazel
  lcmtypes/benchmarking/benchmark.cc
  tools/performance/BUILD.bazel
Labels: priority: low, release notes: none

#22507 [render_vtk] Use source_location in test
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22497 Fix "ref" attribute handling in mujoco parser
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: fix

#22513 [meldis] Fix bug in deformable channels
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
Labels: priority: low, status: single reviewer ok, release notes: none

#22491 [py systems] Adjust scalar conversion to avoid unique_ptr
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/scalar_conversion.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/scalar_conversion_test.py
  systems/framework/BUILD.bazel
  systems/framework/diagram.cc
  systems/framework/system_base.cc
  systems/framework/system_base.h
  systems/framework/test/diagram_test.cc
  systems/framework/test/wrapped_system_test.cc
  systems/framework/wrapped_system.cc
  systems/framework/wrapped_system.h
  systems/framework/wrapped_system_builder.cc
Labels: priority: low, release notes: none

#22489 [wheel] Remove MUMPS, and other assorted repairs
  setup/mac/binary_distribution/Brewfile
  tools/wheel/image/build-dependencies.sh
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/lapack.cmake
  tools/wheel/image/packages-jammy
  tools/wheel/image/packages-macos
  tools/wheel/test/tests/libs-test.py
  tools/workspace/default.bzl
  tools/workspace/mumps_internal/repository.bzl
Labels: priority: medium, status: single reviewer ok, release notes: breaking change

#22518 [build] Don't link X11 on macOS
  geometry/render_gl/BUILD.bazel
  tools/wheel/image/build-drake.sh
  tools/wheel/macos/build-wheel.sh
  tools/wheel/test/tests/libs-test.py
Labels: priority: high, status: single reviewer ok, release notes: none

#22521 [build] Move installed lcmtypes into the main Drake library
  lcmtypes/BUILD.bazel
  tools/install/libdrake/drake-config.cmake.in
Labels: priority: low, status: single reviewer ok, release notes: fix

#22522 [analysis] Cleanup simulator_test
  systems/analysis/test/simulator_test.cc
Labels: status: single reviewer ok, release notes: none

#22524 Correct parsing for multiple materials
  geometry/render/test/render_mesh_test.cc
  tools/workspace/tinyobjloader_internal/patches/upstream/reset_default_kd.patch
  tools/workspace/tinyobjloader_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22516 [render_client] Re-enable integration tests on Mac
  geometry/render_gltf_client/test/integration_test.py
Labels: status: single reviewer ok, release notes: none

#22457 [mpm] Add ParticleSorter
  multibody/mpm/BUILD.bazel
  multibody/mpm/grid_data.h
  multibody/mpm/particle_sorter.cc
  multibody/mpm/particle_sorter.h
  multibody/mpm/spgrid.h
  multibody/mpm/spgrid_flags.h
  multibody/mpm/test/grid_data_test.cc
  multibody/mpm/test/particle_sorter_test.cc
  multibody/mpm/test/spgrid_test.cc
Labels: status: squashing now, release notes: none

#22471 Rename .deb files to skip per-distro subdirectories in S3
  tools/release_engineering/dev/README.md
  tools/release_engineering/dev/push_release
  tools/release_engineering/dev/push_release.py
Labels: priority: low, status: squashing now, release notes: none

#22505 Use @python to provide Linux wheel dependencies
  setup/python/pdm.lock
  setup/python/pyproject.toml
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/packages-jammy
  tools/wheel/image/provision-python.sh
  tools/wheel/macos/build-wheel.sh
  tools/workspace/python/repository.bzl
  tools/workspace/python/venv_sync
Labels: priority: high, release notes: none

#22493 [Mujoco parser] Silently ignore some attributes/elements.
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/parsing_doxygen.h
Labels: release notes: fix

#22528 [analysis] Use shared_ptr for MonteCarlo simulator factory
  bindings/pydrake/systems/analysis_py.cc
  systems/analysis/monte_carlo.cc
  systems/analysis/monte_carlo.h
  systems/analysis/test/monte_carlo_test.cc
Labels: priority: medium, release notes: newly deprecated

#22477 Modify install_prereqs to create a venv
  doc/_pages/from_binary.md
  setup/BUILD.bazel
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/binary_distribution/requirements.txt
  setup/python/pdm.lock
  setup/python/pyproject.toml
Labels: priority: high, release notes: feature

#22526 plot_graphviz uses ipython display with svg in notebooks
  bindings/pydrake/systems/drawing.py
  tutorials/dynamical_systems.ipynb
  tutorials/working_with_diagrams.ipynb
Labels: priority: low, release notes: fix

#22523 [build] CMake checks for DRAKE_CI_ENABLE_PACKAGING
  CMakeLists.txt
Labels: priority: medium, release notes: none

#22541 The test passed erroneously
  geometry/render/test/render_mesh_test.cc
Labels: status: single reviewer ok, release notes: none

#22520 [build] CMake installs eigen,fmt,spdlog when not user-supplied
  CMakeLists.txt
  MODULE.bazel
  cmake/bazel.rc.in
  doc/_pages/from_source.md
  tools/install/install.bzl
  tools/install/libdrake/BUILD.bazel
  tools/install/libdrake/drake-config.cmake.in
  tools/wheel/image/build-drake.sh
  tools/wheel/macos/build-wheel.sh
  tools/workspace/README.md
  tools/workspace/eigen/BUILD.bazel
  tools/workspace/fmt/BUILD.bazel
  tools/workspace/spdlog/BUILD.bazel
Labels: priority: medium, release notes: fix

#22527 [lcm_gen] Fix bounds checking in legacy API
  tools/lcm_gen/__init__.py
  tools/lcm_gen/test/functional_test.cc
  tools/lcm_gen/test/goal/lima.hpp
  tools/lcm_gen/test/goal/mike.hpp
  tools/lcm_gen/test/goal/november.hpp
Labels: priority: low, status: single reviewer ok, release notes: none

#22546 Hotfix for 22526
  bindings/pydrake/systems/drawing.py
Labels: priority: high, status: single reviewer ok, release notes: none

#22525 [lcm_gen] Optimize encoding and decoding of arrays
  tools/lcm_gen/__init__.py
  tools/lcm_gen/test/goal/lima.hpp
  tools/lcm_gen/test/goal/mike.hpp
  tools/lcm_gen/test/goal/november.hpp
Labels: priority: low, release notes: none

#22548 [hotfix] SpGrid reserves smaller memory span in tests
  multibody/mpm/test/particle_sorter_test.cc
Labels: priority: high, status: single reviewer ok, release notes: none

#22514 Adds M-frame methods for curvilinear mobilizer.
  common/trajectories/piecewise_constant_curvature_trajectory.cc
  common/trajectories/piecewise_constant_curvature_trajectory.h
  common/trajectories/test/piecewise_constant_curvature_trajectory_test.cc
  multibody/tree/curvilinear_joint.h
  multibody/tree/curvilinear_mobilizer.cc
  multibody/tree/curvilinear_mobilizer.h
  multibody/tree/mobilizer_impl.h
  multibody/tree/test/curvilinear_mobilizer_test.cc
Labels: priority: medium, release notes: none

#22535 Implement Bspline "linear in control points" logic
  bindings/pydrake/math/math_py_monolith.cc
  bindings/pydrake/math/test/math_test.py
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/bezier_curve.h
  common/trajectories/bspline_trajectory.cc
  common/trajectories/bspline_trajectory.h
  common/trajectories/test/bspline_trajectory_test.cc
  math/bspline_basis.cc
  math/bspline_basis.h
  math/test/bspline_basis_test.cc
Labels: release notes: feature

#22504 [build] Use clang-format from bzlmod
  MODULE.bazel
  doc/_pages/clion.md
  doc/_pages/code_style_tools.md
  doc/_pages/emacs.md
  doc/_pages/vscode.md
  setup/BUILD.bazel
  setup/mac/source_distribution/Brewfile-test-only
  setup/mac/source_distribution/install_prereqs.sh
  setup/ubuntu/source_distribution/packages-jammy-test-only.txt
  setup/ubuntu/source_distribution/packages-noble-test-only.txt
  tools/lint/BUILD.bazel
  tools/lint/clang_format.py
  tools/lint/clang_format_lint.py
  tools/workspace/default.bzl
  tools/workspace/workspace_bzlmod_sync_test.py
Labels: priority: low, release notes: fix

#22538 [build] Upgrade bazel to latest release 8.0.1
  .bazeliskrc
  .bazelversion
Labels: priority: low, status: single reviewer ok, release notes: fix

#22549 Fix py_env_runner
  tools/skylark/py_env_runner.py
Labels: priority: high, status: single reviewer ok, release notes: none

#22550 [py visualization] Avoid writing to const contexts
  bindings/pydrake/visualization/_model_visualizer.py
Labels: priority: medium, status: single reviewer ok, release notes: none

#22551 prefer get_as_sparse() in L2NormCost
  solvers/cost.cc
Labels: type: cleanup, status: single reviewer ok, release notes: none

#22555 [build] Switch bzlmod clang-format to use_repo_rule
  MODULE.bazel
  tools/lint/BUILD.bazel
  tools/lint/clang_format.py
Labels: priority: high, status: single reviewer ok, release notes: none

#22554 [workspace] Upgrade clang-format to release 19.1.3
  MODULE.bazel
  bindings/pydrake/common/test/ref_cycle_test_util_py.cc
  bindings/pydrake/common/wrap_pybind.h
  bindings/pydrake/math_operators_pybind.h
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/systems/framework_py_semantics.cc
  common/symbolic/expression/test/expression_test.cc
  common/symbolic/test/generic_polynomial_test.cc
  geometry/optimization/convex_set.h
  geometry/optimization/graph_of_convex_sets.cc
  geometry/proximity/make_box_mesh.cc
  geometry/proximity/volume_to_surface_mesh.cc
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  manipulation/kuka_iiwa/iiwa_status_receiver.cc
  math/autodiff.h
  math/compute_numerical_gradient.h
  multibody/contact_solvers/pgs_solver.cc
  multibody/contact_solvers/sap/sap_limit_constraint.h
  multibody/contact_solvers/sap/sap_model.h
  multibody/contact_solvers/sap/sap_solver.h
  multibody/plant/tamsi_solver.h
  multibody/tree/test/tree_from_mobilizers_test.cc
Labels: priority: low, status: single reviewer ok, release notes: fix
