Repository RobotLocomotion/drake, pull requests merged in 2025-07, with the labels that each got.

#23136 Add setter and getter for deformable velocities
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  bindings/pydrake/multibody/tree_py.cc
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/test/deformable_model_test.cc
  multibody/tree/deformable_body.cc
  multibody/tree/deformable_body.h
  multibody/tree/test/deformable_body_test.cc
Labels: release notes: none

#23009 Add `Jenkinsfile`s
  .jenkins/Jenkinsfile-cache-server-health-check
  .jenkins/Jenkinsfile-experimental
  .jenkins/Jenkinsfile-external-examples
  .jenkins/Jenkinsfile-production
  .jenkins/Jenkinsfile-staging
  .jenkins/utils/utils.groovy
  doc/_pages/jenkins.md
Labels: release notes: none

#23157 Overload of MathematicalProgram::AddLinearEqualityConstraint for vector of formulas.
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
  solvers/mathematical_program.cc
  solvers/mathematical_program.h
  solvers/test/mathematical_program_test.cc
Labels: release notes: feature

#23155 [doc] Update issue management: component leads
  doc/_pages/issues.md
Labels: release notes: none

#23117 [build] Pass a more specific compiler from CMake to Bazel
  CMakeLists.txt
  tools/cc_toolchain/BUILD.bazel
  tools/skylark/drake_cc.bzl
  tools/skylark/pybind.bzl
Labels: release notes: fix

#23166 [workspace] Upgrade bazel externals in preparation for bazel 8.3.1
  MODULE.bazel
  tools/workspace/platforms/repository.bzl
  tools/workspace/rules_cc/repository.bzl
  tools/workspace/rules_java/repository.bzl
Labels: priority: medium, status: single reviewer ok, release notes: fix

#23167 [doc] Fix links to pull request jobs for external examples
  doc/_pages/jenkins.md
Labels: priority: low, release notes: none

#23147 [tools] Default to C++23 on Noble
  doc/_pages/installation.md
  tools/ubuntu-noble.bazelrc
  tools/workspace/vtk_internal/patches/upstream/common_executionmodel_vtkalgorithm_ternary.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#23164 [setup] Upgrade bazel to latest release 8.3.1
  .bazelversion
Labels: status: do not review, status: single reviewer ok, release notes: fix

#23092 MapQDDotToAcceleration() and MapAccelerationToQDDot() for rpy mobilizer.
  multibody/tree/rpy_ball_mobilizer.cc
  multibody/tree/rpy_ball_mobilizer.h
  multibody/tree/test/rpy_ball_mobilizer_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#23175 Add DiffIk(System & Controller)
  multibody/inverse_kinematics/BUILD.bazel
  multibody/inverse_kinematics/differential_inverse_kinematics_controller.cc
  multibody/inverse_kinematics/differential_inverse_kinematics_controller.h
  multibody/inverse_kinematics/differential_inverse_kinematics_system.cc
  multibody/inverse_kinematics/differential_inverse_kinematics_system.h
  multibody/inverse_kinematics/test/differential_inverse_kinematics_controller_test.cc
  multibody/inverse_kinematics/test/differential_inverse_kinematics_system_test.cc
Labels: status: commits are properly curated, release notes: feature

#23178 Add python bindings for DifferentialIK framework systems
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/inverse_kinematics_py_differential.cc
  bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py
Labels: priority: high, release notes: feature

#23116 Enable IrisNp2 to Handle Additional User-Specified Constraints
  geometry/optimization/iris.cc
  geometry/optimization/iris_internal.cc
  geometry/optimization/iris_internal.h
  planning/iris/iris_common.cc
  planning/iris/iris_common.h
  planning/iris/iris_np2.cc
  planning/iris/iris_np2.h
  planning/iris/iris_zo.cc
  planning/iris/test/iris_np2_test.cc
Labels: release notes: feature

#23182 [examples] Remove manipulation_station C++ and bindings
  bindings/pydrake/examples/BUILD.bazel
  bindings/pydrake/examples/_examples_extra.py
  bindings/pydrake/examples/examples_py.cc
  bindings/pydrake/examples/examples_py.h
  bindings/pydrake/examples/examples_py_manipulation_station.cc
  bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py
  bindings/pydrake/examples/test/manipulation_station_test.py
  bindings/pydrake/manipulation/BUILD.bazel
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/test/parse_models_test.py
  bindings/pydrake/visualization/BUILD.bazel
  examples/manipulation_station/BUILD.bazel
  examples/manipulation_station/README.md
  examples/manipulation_station/end_effector_teleop_dualshock4.py
  examples/manipulation_station/end_effector_teleop_mouse.py
  examples/manipulation_station/end_effector_teleop_sliders.py
  examples/manipulation_station/joint_teleop.py
  examples/manipulation_station/manipulation_station.cc
  examples/manipulation_station/manipulation_station.h
  examples/manipulation_station/manipulation_station_hardware_interface.cc
  examples/manipulation_station/manipulation_station_hardware_interface.h
  examples/manipulation_station/mock_station_simulation.cc
  examples/manipulation_station/print_station_context.py
  examples/manipulation_station/proof_of_life.cc
  examples/manipulation_station/schunk_wsg_buttons.py
  examples/manipulation_station/test/manipulation_station_hardware_interface_test.cc
  examples/manipulation_station/test/manipulation_station_test.cc
  setup/ubuntu/source_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-noble.txt
  tools/install/libdrake/build_components.bzl
  tools/install/libdrake/build_components_refresh.py
  tutorials/BUILD.bazel
Labels: priority: medium, status: single reviewer ok, release notes: fix

#23177 [tools] Default to C++23 on macOS
  doc/_pages/installation.md
  tools/bazel.rc
  tools/lcm_gen/__init__.py
  tools/lcm_gen/test/goal/lima.hpp
  tools/lcm_gen/test/goal/mike.hpp
  tools/lcm_gen/test/goal/november.hpp
  tools/ubuntu-jammy.bazelrc
  tools/ubuntu-noble.bazelrc
  tools/workspace/vtk_internal/patches/upstream/common_datamodel_vtkdatasetattributes_iterator.patch
  tools/workspace/vtk_internal/patches/upstream/rendering_core_vtkcomposite_exception.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: release notes: fix

#23171 [pydrake] Fix a RobotDiagramBuilder memory leak
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py_robot_diagram.cc
  bindings/pydrake/planning/test/robot_diagram_test.py
  planning/robot_diagram.cc
  planning/robot_diagram.h
  planning/robot_diagram_builder.cc
  planning/robot_diagram_builder.h
Labels: release notes: fix

#23199 Warn when solving a QP with CLP.
  solvers/clp_solver.cc
  solvers/test/clp_solver_test.cc
Labels: status: single reviewer ok, release notes: none

#23185 [doc] Add release notes v1.43.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.43.0.md
Labels: status: squashing now, release notes: none

#23208 Replace sample link with valid link
  doc/_pages/buildcop.md
Labels: status: single reviewer ok, release notes: none

#23215 [Jenkins] Fix errors from production deployment
  .jenkins/Jenkinsfile-continuous
  .jenkins/Jenkinsfile-nightly
Labels: release notes: none

#23214 [multibody] Expose the JointOrdinal type and use it instead of a raw int.
  multibody/plant/test/multibody_plant_reaction_forces_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/topology/link_joint_graph_defs.h
  multibody/tree/joint.h
  multibody/tree/multibody_element.h
  multibody/tree/multibody_tree_indexes.h
Labels: priority: low, release notes: breaking change

#23221 Add a getter for `parent_frame` in FixedOffsetFrame
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/fixed_offset_frame.h
Labels: status: single reviewer ok, release notes: feature

#23227 [doc] Update Jenkins sign in instructions
  doc/_pages/jenkins.md
Labels: release notes: none

#23232 [Jenkins] Remove properties for non-experimental jobs
  .jenkins/Jenkinsfile-continuous
  .jenkins/Jenkinsfile-experimental
  .jenkins/Jenkinsfile-external-examples
  .jenkins/Jenkinsfile-production
  .jenkins/Jenkinsfile-staging
Labels: status: commits are properly curated, release notes: none

#23234 Can specify max time for NLopt.
  bindings/pydrake/solvers/solvers_py_nlopt.cc
  bindings/pydrake/solvers/test/nlopt_solver_test.py
  solvers/nlopt_solver.cc
  solvers/nlopt_solver.h
  solvers/nlopt_solver_common.cc
  solvers/test/nlopt_solver_test.cc
Labels: release notes: feature

#23202 [tools] Minor updates to release documentation
  tools/release_engineering/dev/README.md
Labels: release notes: none

#23223 [trajectories] Remove deprecated code 2025-08
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/BUILD.bazel
  common/trajectories/bezier_curve.h
  common/trajectories/bspline_trajectory.h
  common/trajectories/composite_trajectory.h
  common/trajectories/discrete_time_trajectory.h
  common/trajectories/path_parameterized_trajectory.h
  common/trajectories/piecewise_constant_curvature_trajectory.h
  common/trajectories/piecewise_polynomial.h
  common/trajectories/test/piecewise_trajectory_test.cc
  common/trajectories/test/trajectory_test.cc
  common/trajectories/trajectory.cc
  common/trajectories/trajectory.h
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#23224 [systems] Remove deprecated code 2025-08
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/all.py
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/analysis/discrete_time_approximation.cc
  systems/primitives/linear_system.cc
  systems/primitives/linear_system.h
  systems/primitives/test/linear_system_test.cc
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated
