Repository RobotLocomotion/drake, pull requests merged in 2025-02, with the labels that each got.

#22578 [ik] Allow non-world floating joints without crashing
  multibody/inverse_kinematics/add_multibody_plant_constraints.cc
  multibody/inverse_kinematics/test/add_multibody_plant_constraints_test.cc
Labels: priority: medium, release notes: fix

#22553 [meshcat] Simplify JointSliders now that all positions have joints
  multibody/meshcat/joint_sliders.cc
  multibody/meshcat/joint_sliders.h
Labels: priority: medium, release notes: none

#22570 [setup] Upgrade Python venv (mac) to lastest
  setup/python/pdm.lock
  setup/python/requirements.txt
Labels: status: single reviewer ok, release notes: fix

#22577 [build] Document the new "spdlog disabled" flag as experimental
  tools/flags/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: fix

#22511 [analysis] Avoid unique_ptr in simulator context bindings
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/general_test.py
  systems/analysis/simulator.cc
  systems/analysis/simulator.h
  systems/analysis/test/simulator_test.cc
Labels: release notes: none

#20761 [tools] Switch to Python reimplementation of lcm_gen
  geometry/drake_visualizer.cc
  tools/install/libdrake/drake-config.cmake.in
  tools/skylark/drake_lcm.bzl
  tools/workspace/lcm/lcm-config-version.cmake
  tools/workspace/lcm/lcm-config.cmake
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/lcm/repository.bzl
Labels: priority: medium, release notes: breaking change, release notes: newly deprecated, release notes: feature

#22529 [build] Optionally build blas and lapack from source
  CMakeLists.txt
  MODULE.bazel
  cmake/bazel.rc.in
  cmake/external/workspace/blas/BUILD.bazel.in
  cmake/external/workspace/blas/MODULE.bazel.in
  cmake/external/workspace/lapack/BUILD.bazel.in
  cmake/external/workspace/lapack/MODULE.bazel.in
  doc/_pages/from_source.md
  tools/bazel.rc
  tools/flags/BUILD.bazel
  tools/install/check_is_cc_import.bzl
  tools/wheel/image/build-drake.sh
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/packages-jammy
  tools/wheel/macos/build-wheel.sh
  tools/wheel/test/tests/libs-test.py
  tools/workspace/BUILD.bazel
  tools/workspace/blas/BUILD.bazel
  tools/workspace/blas/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/lapack/BUILD.bazel
  tools/workspace/lapack/repository.bzl
  tools/workspace/lapack_internal/BUILD.bazel
  tools/workspace/lapack_internal/lock/sources.bzl
  tools/workspace/lapack_internal/package.BUILD.bazel
  tools/workspace/lapack_internal/repository.bzl
  tools/workspace/lapack_internal/sources_gen.py
  tools/workspace/libblas/repository.bzl
  tools/workspace/liblapack/repository.bzl
  tools/workspace/spral_internal/package.BUILD.bazel
Labels: priority: medium, release notes: newly deprecated, release notes: feature

#22552 Convert kintrajopt to use AsLinearInControlPoints
  planning/trajectory_optimization/kinematic_trajectory_optimization.cc
  planning/trajectory_optimization/kinematic_trajectory_optimization.h
  planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Labels: release notes: breaking change

#22584 Tweak some yaml serialization documentation
  common/memory_file.h
  geometry/rgba.h
Labels: release notes: none

#22575 Skip Bazel prefetch in prerequisite installation
  setup/ubuntu/install_prereqs.sh
  setup/ubuntu/source_distribution/install_prereqs_user_environment.sh
Labels: status: single reviewer ok, release notes: fix

#22572 Re-enable hardware_sim test on macOS Sequoia and add documentation
  doc/_pages/troubleshooting.md
  examples/hardware_sim/test/hardware_sim_test_common.py
  lcm/drake_lcm.h
Labels: status: single reviewer ok, release notes: none

#22579 Effort limits for Kinematic Trajectory Optimization
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/BUILD.bazel
  planning/trajectory_optimization/kinematic_trajectory_optimization.cc
  planning/trajectory_optimization/kinematic_trajectory_optimization.h
  planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Labels: release notes: feature

#22595 [pydrake] Avoid unique_ptr in "add plant" functions
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/lifetime_test.py
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: release notes: none

#22592 SceneGraph protects itself from non-finite values on its inputs
  geometry/kinematics_vector.cc
  geometry/kinematics_vector.h
  geometry/scene_graph.cc
  geometry/test/kinematics_vector_test.cc
  geometry/test/scene_graph_test.cc
Labels: release notes: fix

#22607 Use separate venv for installation PDM
  setup/mac/binary_distribution/install_prereqs.sh
Labels: status: single reviewer ok, release notes: none

#22610 fix typos: indentifier => identifier
  common/identifier.h
  common/type_safe_index.h
Labels: status: single reviewer ok, release notes: none

#22606 [doc] Cleanup extraneous Doxygen files
  doc/doxygen_cxx/build.py
Labels: status: single reviewer ok, release notes: none

#22612 [build] Add missing clang-format for linux-aarch64
  MODULE.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#22613 [multibody] Clang-format parsing non-test code
  multibody/parsing/detail_collision_filter_group_resolver.cc
  multibody/parsing/detail_collision_filter_group_resolver.h
  multibody/parsing/detail_common.cc
  multibody/parsing/detail_common.h
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/detail_ignition.cc
  multibody/parsing/detail_make_model_name.cc
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_parsing_workspace.h
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/detail_path_utils.h
  multibody/parsing/detail_sdf_diagnostic.cc
  multibody/parsing/detail_sdf_diagnostic.h
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_select_parser.cc
  multibody/parsing/detail_strongly_connected_components.h
  multibody/parsing/detail_tinyxml.cc
  multibody/parsing/detail_tinyxml2_diagnostic.cc
  multibody/parsing/detail_tinyxml2_diagnostic.h
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/detail_urdf_parser.h
  multibody/parsing/detail_usd_geometry.cc
  multibody/parsing/detail_usd_geometry.h
  multibody/parsing/detail_usd_parser.cc
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/process_model_directives.cc
  multibody/parsing/process_model_directives.h
  multibody/parsing/scoped_names.cc
Labels: priority: medium, status: single reviewer ok, release notes: none

#22588 [build] Optionally build zlib from source
  CMakeLists.txt
  MODULE.bazel
  cmake/external/workspace/zlib/BUILD.bazel.in
  cmake/external/workspace/zlib/MODULE.bazel.in
  doc/_pages/from_source.md
  systems/sensors/BUILD.bazel
  tools/flags/BUILD.bazel
  tools/wheel/Dockerfile
  tools/wheel/README.rst
  tools/wheel/image/build-dependencies.sh
  tools/wheel/image/build-drake.sh
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/dependencies/CMakeLists.txt
  tools/wheel/image/dependencies/patches/zlib/patch.cmake
  tools/wheel/image/dependencies/patches/zlib/patch.diff
  tools/wheel/image/dependencies/projects.cmake
  tools/wheel/image/dependencies/projects/zlib.cmake
  tools/wheel/image/packages-jammy
  tools/wheel/image/packages-macos
  tools/wheel/macos/build-dependencies.sh
  tools/wheel/macos/build-wheel.sh
  tools/wheel/wheel_builder/linux.py
  tools/wheel/wheel_builder/macos.py
  tools/workspace/BUILD.bazel
  tools/workspace/default.bzl
  tools/workspace/pkg_config.bzl
  tools/workspace/workspace_bzlmod_sync_test.py
  tools/workspace/zlib/BUILD.bazel
  tools/workspace/zlib/package.BUILD.bazel
  tools/workspace/zlib/repository.bzl
Labels: release notes: fix

#22585 Make GetContinuousRevoluteJointIndices Include UniversalJoint and BallRpyJoint
  planning/trajectory_optimization/gcs_trajectory_optimization.cc
  planning/trajectory_optimization/gcs_trajectory_optimization.h
  planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Labels: release notes: feature

#22604 [tools] Finish up some lcm_gen nits
  lcmtypes/BUILD.bazel
  lcmtypes/test/test_message_test.cc
  tools/lcm_gen/BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: none

#22600 [parsing] Enhance ResolveUri to return non-existent paths
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/detail_path_utils.cc
  multibody/parsing/detail_path_utils.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/package_map.cc
  multibody/parsing/parser.cc
  multibody/parsing/process_model_directives.cc
  multibody/parsing/test/detail_path_utils_test.cc
Labels: priority: low, release notes: none

#22608 [multibody] Eliminate unneeded BluePrint class
  multibody/plant/test/sap_driver_multidof_joints_test.cc
  multibody/tree/ball_rpy_joint.cc
  multibody/tree/ball_rpy_joint.h
  multibody/tree/curvilinear_joint.cc
  multibody/tree/curvilinear_joint.h
  multibody/tree/joint.h
  multibody/tree/multibody_tree.cc
  multibody/tree/planar_joint.cc
  multibody/tree/planar_joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/quaternion_floating_joint.cc
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_joint.h
  multibody/tree/rpy_floating_joint.cc
  multibody/tree/rpy_floating_joint.h
  multibody/tree/screw_joint.cc
  multibody/tree/screw_joint.h
  multibody/tree/universal_joint.cc
  multibody/tree/universal_joint.h
  multibody/tree/weld_joint.cc
  multibody/tree/weld_joint.h
Labels: priority: medium, release notes: none

#22596 Make ModelVisualizer show a .gltf file directly
  bindings/pydrake/visualization/_model_visualizer.py
  bindings/pydrake/visualization/model_visualizer.py
  bindings/pydrake/visualization/test/model_visualizer_reload_test.py
  bindings/pydrake/visualization/test/model_visualizer_test.py
Labels: release notes: feature

#22614 [multibody] Clang-format all remaining parsing code
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_sdf_geometry.h
  multibody/parsing/detail_urdf_geometry.h
  multibody/parsing/test/acrobot_parser_test.cc
  multibody/parsing/test/collision_filter_groups_test.cc
  multibody/parsing/test/common_parser_test.cc
  multibody/parsing/test/detail_collision_filter_group_resolver_test.cc
  multibody/parsing/test/detail_common_test.cc
  multibody/parsing/test/detail_dmd_parser_test.cc
  multibody/parsing/test/detail_make_model_name_test.cc
  multibody/parsing/test/detail_mesh_parser_test.cc
  multibody/parsing/test/detail_mujoco_parser_examples_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/parsing/test/detail_path_utils_test.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_select_parser_test.cc
  multibody/parsing/test/detail_tinyxml2_diagnostic_test.cc
  multibody/parsing/test/detail_tinyxml_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/detail_usd_geometry_test.cc
  multibody/parsing/test/detail_usd_parser_test.cc
  multibody/parsing/test/drake_manifest_resolution_test.cc
  multibody/parsing/test/package_map_test.cc
  multibody/parsing/test/parser_manual_test.cc
  multibody/parsing/test/parser_test.cc
  multibody/parsing/test/process_model_directives_test.cc
  multibody/parsing/test/test_loaders.cc
  multibody/parsing/test/test_loaders.h
Labels: priority: medium, status: single reviewer ok, release notes: none

#22599 KinematicTrajectoryOptimization adds velocity linear constraint.
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  planning/trajectory_optimization/kinematic_trajectory_optimization.cc
  planning/trajectory_optimization/kinematic_trajectory_optimization.h
  planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Labels: release notes: feature

#22558 Growing IRIS-ZO Regions Along a Parametrized Subspace
  planning/iris/iris_zo.cc
  planning/iris/iris_zo.h
  planning/iris/test/iris_zo_test.cc
Labels: status: squashing now, release notes: feature

#22594 MultibodyPlant hinders writing user non-finite values to context
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/test/multibody_plant_test.cc
Labels: release notes: fix

#22601 Implement continuous- to discrete-time conversion for linear systems
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/primitives/linear_system.cc
  systems/primitives/linear_system.h
  systems/primitives/test/linear_system_test.cc
Labels: release notes: feature

#22593 Collision checker protects itself from user-provided NaN
  planning/collision_checker.cc
  planning/collision_checker.h
  planning/distance_and_interpolation_provider.cc
  planning/distance_and_interpolation_provider.h
  planning/test/collision_checker_test.cc
  planning/test/distance_and_interpolation_provider_test.cc
Labels: release notes: fix

#22171 Clarify upgrade advice for bazelisk
  tools/workspace/README.md
  tools/workspace/bazelisk/repository.bzl
Labels: release notes: none

#22625 Generalize mujoco defaults parsing
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
Labels: release notes: feature

#22556 [doc] Add release notes v1.38.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.38.0.md
Labels: status: squashing now, status: single reviewer ok, release notes: none

#22619 [pydrake] avoid unique_ptr in CollisionChecker API
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py_collision_checker.cc
  bindings/pydrake/planning/planning_py_collision_checker_interface_types.cc
  bindings/pydrake/planning/test/collision_checker_test.py
  planning/collision_checker_params.h
Labels: release notes: breaking change

#22644 [multibody] Add GetScopedFrameByName overloads on scalar type
  bindings/pydrake/multibody/BUILD.bazel
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  multibody/parsing/scoped_names.cc
  multibody/parsing/scoped_names.h
  multibody/parsing/test/scoped_names_test.cc
  multibody/plant/multibody_plant.h
Labels: status: single reviewer ok, release notes: feature

#22531 Parse cameras from mujoco
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  multibody/parsing/BUILD.bazel
  multibody/parsing/detail_composite_parse.cc
  multibody/parsing/detail_dmd_parser.cc
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_parsing_workspace.h
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/parser.cc
  multibody/parsing/parser.h
  multibody/parsing/parsing_doxygen.h
  multibody/parsing/test/detail_dmd_parser_test.cc
  multibody/parsing/test/detail_make_model_name_test.cc
  multibody/parsing/test/detail_mesh_parser_test.cc
  multibody/parsing/test/detail_mujoco_parser_examples_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_select_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
  multibody/parsing/test/detail_usd_parser_test.cc
  multibody/parsing/test/parser_test.cc
Labels: release notes: feature

#22650 Add missing bindings from MeshcatAnimation
  bindings/pydrake/geometry/geometry_py_visualizers.cc
  bindings/pydrake/geometry/test/visualizers_test.py
Labels: status: single reviewer ok, release notes: feature

#22640 Implements hydro box mesh with faces split into four triangles
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/make_box_mesh.cc
  geometry/proximity/make_box_mesh.h
  geometry/proximity/test/hydroelastic_internal_test.cc
  geometry/proximity/test/make_box_mesh_test.cc
  multibody/plant/test/deformable_integration_test.cc
Labels: priority: high, component: geometry proximity, release notes: feature

#22609 Implement discrete-time finite-horizon LQR
  doc/_pages/credits.md
  systems/controllers/finite_horizon_linear_quadratic_regulator.cc
  systems/controllers/finite_horizon_linear_quadratic_regulator.h
  systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Labels: release notes: feature

#22656 push_release: Fix-up error in creating apt packages
  tools/release_engineering/dev/push_release
Labels: release notes: none

#22642 Check RotationalInertia moments/products with IsFinite() instead of IsNaN().
  multibody/tree/rotational_inertia.cc
  multibody/tree/rotational_inertia.h
  multibody/tree/test/rotational_inertia_test.cc
Labels: priority: medium, status: squashing now, status: single reviewer ok, release notes: none

#22647 [framework] Clang-format all remaining code
  systems/framework/BUILD.bazel
  systems/framework/cache.h
  systems/framework/diagram_builder.cc
  systems/framework/diagram_context.cc
  systems/framework/input_port.h
  systems/framework/input_port_base.h
  systems/framework/output_port.h
  systems/framework/output_port_base.h
  systems/framework/system.h
  systems/framework/system_scalar_converter.cc
  systems/framework/test/basic_vector_test.cc
  systems/framework/test/cache_entry_test.cc
  systems/framework/test/cache_test.cc
  systems/framework/test/continuous_state_test.cc
  systems/framework/test/dependency_tracker_test.cc
  systems/framework/test/diagram_builder_test.cc
  systems/framework/test/diagram_context_test.cc
  systems/framework/test/diagram_test.cc
  systems/framework/test/discrete_values_limit_malloc_test.cc
  systems/framework/test/discrete_values_test.cc
  systems/framework/test/event_status_test.cc
  systems/framework/test/fixed_input_port_value_test.cc
  systems/framework/test/leaf_context_test.cc
  systems/framework/test/leaf_system_deprecation_test.cc
  systems/framework/test/leaf_system_test.cc
  systems/framework/test/output_port_test.cc
  systems/framework/test/single_output_vector_source_test.cc
  systems/framework/test/subvector_test.cc
  systems/framework/test/supervector_test.cc
  systems/framework/test/system_constraint_test.cc
  systems/framework/test/system_output_test.cc
  systems/framework/test/system_scalar_converter_test.cc
  systems/framework/test/system_symbolic_inspector_test.cc
  systems/framework/test/system_test.cc
  systems/framework/test/thread_sanitizer_test.cc
  systems/framework/test/value_checker_test.cc
  systems/framework/test/value_producer_test.cc
  systems/framework/test/vector_system_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22661 [pydrake] Fix annotation typo
  bindings/pydrake/systems/analysis_py.cc
Labels: status: single reviewer ok, release notes: none

#22629 Correct VTK's image-based lighting diffuse calculation
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  geometry/render_vtk/test/whole_image_custom_color.png
  tools/workspace/vtk_internal/patches/upstream/scaled_albedo_for_ibl.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: priority: high, release notes: breaking change, release notes: fix

#22632 Preserve direct light specular reflections for smooth materials
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  tools/workspace/vtk_internal/patches/preserve_direct_light_specular_reflections.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: priority: high, release notes: fix

#22635 [primitives] Add Selector primitive system
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  manipulation/schunk_wsg/schunk_wsg_plain_controller.cc
  systems/primitives/BUILD.bazel
  systems/primitives/selector.cc
  systems/primitives/selector.h
  systems/primitives/selector_internal.h
  systems/primitives/test/selector_test.cc
  tools/workspace/pybind11/mkdoc_comment.py
Labels: priority: medium, release notes: feature

#22626 [build] CMake options for solver opt-out
  CMakeLists.txt
  bindings/pydrake/solvers/BUILD.bazel
  doc/_pages/from_source.md
Labels: release notes: feature

#22591 Add CurvilinearJoint URDF/SDF parsing documentation (#22196)
  multibody/parsing/parsing_doxygen.h
Labels: status: squashing now, release notes: feature

#22668 [pydrake] Rebind StopDenseIntegration for vanilla pybind11
  bindings/pydrake/systems/analysis_py.cc
Labels: status: single reviewer ok, release notes: none

#22474 Unify validity tests and messages for SpatialInertia class.
  multibody/parsing/detail_mujoco_parser.cc
  multibody/tree/geometry_spatial_inertia.cc
  multibody/tree/spatial_inertia.cc
  multibody/tree/spatial_inertia.h
  multibody/tree/test/spatial_inertia_test.cc
Labels: priority: medium, status: squashing now, release notes: none, release notes: newly deprecated

#22667 Clarify render engine backed and show_rgb
  geometry/render_vtk/render_engine_vtk_params.h
  systems/sensors/camera_config.h
Labels: release notes: none

#22649 [multibody] MakeMobilizerForJoint() can now create Frames
  multibody/plant/multibody_plant.cc
  multibody/plant/test/sap_driver_multidof_joints_test.cc
  multibody/rational/rational_forward_kinematics.cc
  multibody/rational/rational_forward_kinematics.h
  multibody/tree/ball_rpy_joint.cc
  multibody/tree/ball_rpy_joint.h
  multibody/tree/curvilinear_joint.cc
  multibody/tree/curvilinear_joint.h
  multibody/tree/joint.cc
  multibody/tree/joint.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/planar_joint.cc
  multibody/tree/planar_joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/quaternion_floating_joint.cc
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_joint.h
  multibody/tree/rpy_floating_joint.cc
  multibody/tree/rpy_floating_joint.h
  multibody/tree/screw_joint.cc
  multibody/tree/screw_joint.h
  multibody/tree/test/weld_joint_test.cc
  multibody/tree/universal_joint.cc
  multibody/tree/universal_joint.h
  multibody/tree/weld_joint.cc
  multibody/tree/weld_joint.h
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: priority: medium, release notes: breaking change

#22674 [parsing] Parsed mesh geometries use default proximity props
  multibody/parsing/detail_mesh_parser.cc
  multibody/parsing/test/detail_mesh_parser_test.cc
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
Labels: release notes: fix
