Repository RobotLocomotion/drake, pull requests merged in 2025-03, with the labels that each got.

#22685 [pybdrake] Rebind render factories for vanilla pybind11
  bindings/pydrake/geometry/geometry_py_render.cc
Labels: status: single reviewer ok, release notes: none

#22677 [workspace] Upgrade curl_internal to latest release 8.12.1
  tools/workspace/curl_internal/cmakedefines.bzl
  tools/workspace/curl_internal/package.BUILD.bazel
  tools/workspace/curl_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22678 [workspace] Upgrade nlopt_internal to latest release v2.10.0
  tools/workspace/nlopt_internal/patches/gen_enums.patch
  tools/workspace/nlopt_internal/patches/upstream/pr582.patch
  tools/workspace/nlopt_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22680 [workspace] Upgrade sdformat to latest
  tools/workspace/sdformat_internal/patches/upstream/pr1523.patch
  tools/workspace/sdformat_internal/patches/upstream/pr1524.patch
  tools/workspace/sdformat_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22688 Revert "[multibody] MakeMobilizerForJoint() can now create Frames"
  multibody/plant/multibody_plant.cc
  multibody/plant/test/sap_driver_multidof_joints_test.cc
  multibody/rational/rational_forward_kinematics.cc
  multibody/rational/rational_forward_kinematics.h
  multibody/tree/ball_rpy_joint.cc
  multibody/tree/ball_rpy_joint.h
  multibody/tree/curvilinear_joint.cc
  multibody/tree/curvilinear_joint.h
  multibody/tree/joint.cc
  multibody/tree/joint.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/planar_joint.cc
  multibody/tree/planar_joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/quaternion_floating_joint.cc
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_joint.h
  multibody/tree/rpy_floating_joint.cc
  multibody/tree/rpy_floating_joint.h
  multibody/tree/screw_joint.cc
  multibody/tree/screw_joint.h
  multibody/tree/test/weld_joint_test.cc
  multibody/tree/universal_joint.cc
  multibody/tree/universal_joint.h
  multibody/tree/weld_joint.cc
  multibody/tree/weld_joint.h
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: priority: high, status: single reviewer ok, release notes: none

#22670 March external upgrades
  tools/workspace/abseil_cpp_internal/repository.bzl
  tools/workspace/buildifier/repository.bzl
  tools/workspace/drake_models/repository.bzl
  tools/workspace/gtest/repository.bzl
  tools/workspace/gymnasium_py/repository.bzl
  tools/workspace/libpng_internal/repository.bzl
  tools/workspace/mujoco_menagerie_internal/repository.bzl
  tools/workspace/mypy_internal/repository.bzl
  tools/workspace/nanoflann_internal/repository.bzl
  tools/workspace/openusd_internal/repository.bzl
  tools/workspace/suitesparse_internal/repository.bzl
Labels: status: commits are properly curated, status: single reviewer ok, release notes: fix

#22696 [multibody] Fix and unit test Clone functions for Frames
  multibody/tree/fixed_offset_frame.cc
  multibody/tree/fixed_offset_frame.h
  multibody/tree/test/frames_test.cc
Labels: priority: high, status: single reviewer ok, release notes: fix

#22693 [workspace] Upgrade spral_internal to latest release v2025.03.03
  tools/workspace/spral_internal/package.BUILD.bazel
  tools/workspace/spral_internal/repository.bzl
Labels: priority: low, status: squashing now, status: single reviewer ok, release notes: fix

#22697 [pydrake] Add missing bindings for CameraConfig helper structs
  bindings/pydrake/systems/sensors_py_camera_config.cc
  bindings/pydrake/systems/test/sensors_test.py
Labels: priority: medium, status: single reviewer ok, release notes: fix

#22690 [setup] Upgrade Bazel to latest release 8.1.1
  .bazelversion
  doc/_pages/from_source.md
  tools/install/libdrake/test/exported_symbols_test.py
Labels: status: single reviewer ok, release notes: fix

#22704 Replaced brew bundle `--no-lock` option with env variable
  setup/mac/binary_distribution/install_prereqs.sh
  setup/mac/source_distribution/install_prereqs.sh
  tools/wheel/wheel_builder/macos.py
Labels: priority: high, status: single reviewer ok, release notes: fix

#22653 Python bindings for DiscreteTimeTrajectory class
  bindings/pydrake/test/trajectories_test.py
  bindings/pydrake/trajectories_py.cc
  common/trajectories/discrete_time_trajectory.cc
  common/trajectories/discrete_time_trajectory.h
Labels: status: single reviewer ok, release notes: fix

#22692 [setup] Upgrade Python venv (mac) to latest
  setup/python/pdm.lock
  setup/python/requirements.txt
Labels: status: single reviewer ok, release notes: fix

#22618 Implement Python Bindings for IRIS-ZO Parameterization Function
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py.cc
  bindings/pydrake/planning/planning_py_iris_zo.cc
  bindings/pydrake/planning/test/iris_zo_test.py
  planning/iris/BUILD.bazel
  planning/iris/iris_zo.cc
  planning/iris/iris_zo.h
  planning/iris/test/iris_zo_test.cc
Labels: status: squashing now, release notes: feature

#22710 [doc] Add recently-added externals to credits
  doc/_pages/credits.md
Labels: priority: low, status: single reviewer ok, release notes: none

#22682 [primitives] Allow an initial value to be specified for Integrator
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  systems/framework/vector_system.h
  systems/primitives/BUILD.bazel
  systems/primitives/integrator.cc
  systems/primitives/integrator.h
  systems/primitives/test/integrator_test.cc
Labels: priority: medium, release notes: feature

#22709 [geometry] Speed up VolumeMeshRefiner with local search
  geometry/proximity/volume_mesh_refiner.cc
  geometry/proximity/volume_mesh_refiner.h
Labels: release notes: feature

#22713 [workspace] Upgrade spral_internal to latest release v2025.03.06
  tools/workspace/spral_internal/package.BUILD.bazel
  tools/workspace/spral_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22583 IRIS-ZO with Additional Constraints
  bindings/pydrake/planning/BUILD.bazel
  bindings/pydrake/planning/planning_py_iris_zo.cc
  bindings/pydrake/planning/test/iris_zo_test.py
  planning/iris/BUILD.bazel
  planning/iris/iris_zo.cc
  planning/iris/iris_zo.h
  planning/iris/test/iris_zo_test.cc
Labels: status: squashing now, release notes: feature

#22542 Desired state input ports are no longer required to be connected
  multibody/plant/BUILD.bazel
  multibody/plant/desired_state_input.cc
  multibody/plant/desired_state_input.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/test/actuated_models_test.cc
  multibody/plant/test/sap_driver_pd_controller_constraints_test.cc
  multibody/tree/joint_actuator.h
Labels: priority: medium, release notes: fix

#22540 [mpm] Add SparseGrid
  multibody/mpm/BUILD.bazel
  multibody/mpm/grid_data.h
  multibody/mpm/mass_and_momentum.h
  multibody/mpm/sparse_grid.cc
  multibody/mpm/sparse_grid.h
  multibody/mpm/spgrid.h
  multibody/mpm/test/grid_data_test.cc
  multibody/mpm/test/particle_sorter_test.cc
  multibody/mpm/test/sparse_grid_test.cc
Labels: release notes: none

#22716 [mpm] Streamline valgrind fix for SpGrid
  multibody/mpm/BUILD.bazel
  multibody/mpm/sparse_grid.cc
  multibody/mpm/sparse_grid.h
  multibody/mpm/spgrid.h
  multibody/mpm/test/particle_sorter_test.cc
  multibody/mpm/test/sparse_grid_test.cc
  multibody/mpm/test/spgrid_test.cc
Labels: status: single reviewer ok, release notes: none

#22706 Expression Parameterization for IRIS-ZO
  bindings/pydrake/planning/planning_py_iris_zo.cc
  bindings/pydrake/planning/test/iris_zo_test.py
  planning/iris/BUILD.bazel
  planning/iris/iris_zo.cc
  planning/iris/iris_zo.h
  planning/iris/test/iris_zo_test.cc
Labels: release notes: feature

#22698 MapQDDotToAcceleration() and MapAccelerationToQDDot() for simple mobilizers
  multibody/tree/mobilizer.cc
  multibody/tree/mobilizer.h
  multibody/tree/planar_mobilizer.cc
  multibody/tree/planar_mobilizer.h
  multibody/tree/prismatic_mobilizer.cc
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/test/planar_mobilizer_test.cc
  multibody/tree/test/prismatic_mobilizer_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
  multibody/tree/test/screw_mobilizer_test.cc
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: priority: medium, status: squashing now, release notes: none

#22727 Revert "[workspace] Upgrade libpng_internal to latest release v1.6.47"
  tools/workspace/libpng_internal/repository.bzl
Labels: priority: high, status: single reviewer ok, release notes: fix

#22722 Fix or suppress lint in anticipation of cpplint upgrade
  common/hash.h
  common/identifier.h
  common/sorted_pair.h
  common/symbolic/chebyshev_basis_element.h
  common/symbolic/chebyshev_polynomial.h
  common/symbolic/expression/expression.h
  common/symbolic/expression/formula.h
  common/symbolic/expression/variable.h
  common/symbolic/expression/variables.h
  common/symbolic/generic_polynomial.h
  common/symbolic/monomial.h
  common/symbolic/monomial_basis_element.h
  common/symbolic/polynomial.h
  common/type_safe_index.h
  geometry/render/render_label.h
  geometry/render_gl/internal_buffer_dim.h
  math/rigid_transform.h
  math/roll_pitch_yaw.h
  math/rotation_matrix.h
  multibody/mpm/particle_sorter.cc
  multibody/mpm/particle_sorter.h
  multibody/mpm/sparse_grid.cc
  solvers/binding.h
  solvers/evaluator_base.h
  solvers/solver_id.h
Labels: release notes: none

#22734 [pydrake] Rewrite DefClone() helper for vanilla pybind11
  bindings/pydrake/pydrake_pybind.h
Labels: status: single reviewer ok, release notes: none

#22736 [common] Fix typo in include path
  common/timer.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22679 [framework] Introduce BusCreator, BusSelector, BusValue
  bindings/pydrake/systems/framework_py_values.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/primitives_test.py
  bindings/pydrake/systems/test/value_test.py
  multibody/plant/multibody_plant.h
  systems/framework/BUILD.bazel
  systems/framework/bus_value.cc
  systems/framework/bus_value.h
  systems/framework/test/bus_value_test.cc
  systems/primitives/BUILD.bazel
  systems/primitives/bus_creator.cc
  systems/primitives/bus_creator.h
  systems/primitives/bus_selector.cc
  systems/primitives/bus_selector.h
  systems/primitives/test/bus_creator_test.cc
  systems/primitives/test/bus_selector_test.cc
Labels: priority: medium, release notes: feature

#22735 [multibody] MakeMobilizerForJoint() can now create Frames. Example in Weld.
  multibody/plant/multibody_plant.cc
  multibody/plant/test/sap_driver_multidof_joints_test.cc
  multibody/rational/rational_forward_kinematics.cc
  multibody/rational/rational_forward_kinematics.h
  multibody/tree/ball_rpy_joint.cc
  multibody/tree/ball_rpy_joint.h
  multibody/tree/curvilinear_joint.cc
  multibody/tree/curvilinear_joint.h
  multibody/tree/joint.cc
  multibody/tree/joint.h
  multibody/tree/multibody_tree-inl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/multibody_tree.h
  multibody/tree/planar_joint.cc
  multibody/tree/planar_joint.h
  multibody/tree/prismatic_joint.h
  multibody/tree/quaternion_floating_joint.cc
  multibody/tree/quaternion_floating_joint.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_joint.h
  multibody/tree/rpy_floating_joint.cc
  multibody/tree/rpy_floating_joint.h
  multibody/tree/screw_joint.cc
  multibody/tree/screw_joint.h
  multibody/tree/test/weld_joint_test.cc
  multibody/tree/universal_joint.cc
  multibody/tree/universal_joint.h
  multibody/tree/weld_joint.cc
  multibody/tree/weld_joint.h
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: priority: medium, release notes: feature

#22737 IrisZo: Better Handle Cases when the Center of the Ellipsoid is In-Collision
  planning/iris/iris_zo.cc
  planning/iris/iris_zo.h
  planning/iris/test/iris_zo_test.cc
Labels: release notes: fix

#22739 Removes ConexSuperNodalSolver along with Drake's dependency on Conex
  MODULE.bazel
  multibody/contact_solvers/BUILD.bazel
  multibody/contact_solvers/block_sparse_supernodal_solver.cc
  multibody/contact_solvers/block_sparse_supernodal_solver.h
  multibody/contact_solvers/conex_supernodal_solver.cc
  multibody/contact_solvers/conex_supernodal_solver.h
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_model.cc
  multibody/contact_solvers/sap/sap_model.h
  multibody/contact_solvers/sap/sap_solver.cc
  multibody/contact_solvers/sap/sap_solver.h
  multibody/contact_solvers/sap/test/sap_solver_test.cc
  multibody/contact_solvers/test/supernodal_solver_test.cc
  tools/workspace/BUILD.bazel
  tools/workspace/conex_internal/BUILD.bazel
  tools/workspace/conex_internal/package.BUILD.bazel
  tools/workspace/conex_internal/patches/no_eigen_io.patch
  tools/workspace/conex_internal/patches/upstream/debug_macros.patch
  tools/workspace/conex_internal/patches/upstream/eigen_namespace_pollution.patch
  tools/workspace/conex_internal/patches/vendor.patch
  tools/workspace/conex_internal/repository.bzl
  tools/workspace/conex_internal/vendor.bzl
  tools/workspace/default.bzl
Labels: release notes: none

#22749 [doc] Remove Conex
  doc/_pages/credits.md
Labels: priority: low, status: single reviewer ok, release notes: none

#22751 Document SemiExplicitEulerIntegrator to support Expression scalar type
  systems/analysis/semi_explicit_euler_integrator.cc
  systems/analysis/semi_explicit_euler_integrator.h
  systems/analysis/test/semi_explicit_euler_integrator_test.cc
Labels: status: single reviewer ok, release notes: feature

#22743 Avoid accessing nullptr in SemiExplicitEulerIntegrator constructor
  systems/analysis/semi_explicit_euler_integrator.h
  systems/analysis/test/semi_explicit_euler_integrator_test.cc
Labels: status: single reviewer ok, release notes: fix

#22731 [multibody] Add PackageMap overloads for filesystem and pathlib
  bindings/pydrake/multibody/parsing_py.cc
  multibody/parsing/package_map.cc
  multibody/parsing/package_map.h
  multibody/parsing/test/package_map_test.cc
Labels: priority: low, release notes: feature

#22715 [multibody] Remove all temporal setup limitations on PD gains
  multibody/tree/joint_actuator.cc
  multibody/tree/joint_actuator.h
  multibody/tree/test/joint_actuator_test.cc
Labels: release notes: feature

#22724 [examples] Port to always use DrakeLcm API
  examples/allegro_hand/joint_control/BUILD.bazel
  examples/allegro_hand/joint_control/run_twisting_mug.cc
  examples/kinova_jaco_arm/BUILD.bazel
  examples/kinova_jaco_arm/move_jaco_ee.cc
  examples/kuka_iiwa_arm/BUILD.bazel
  examples/kuka_iiwa_arm/kuka_plan_runner.cc
  examples/kuka_iiwa_arm/move_iiwa_ee.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22484 [workspace,planning/dev] Update CRU & VGT, re-enable TSAN on voxel self-filter
  planning/dev/BUILD.bazel
  planning/dev/test/voxel_self_filter_test.cc
  tools/workspace/common_robotics_utilities_internal/repository.bzl
  tools/workspace/voxelized_geometry_tools_internal/repository.bzl
Labels: status: squashing now, release notes: fix

#22740 [deformable] Support RenderEngineVtk
  examples/multibody/deformable/BUILD.bazel
  examples/multibody/deformable/bubble_gripper.cc
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
Labels: release notes: none

#22708 [doc] Add release notes v1.39.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.39.0.md
Labels: status: squashing now, status: single reviewer ok, release notes: none

#22738 [pybind11] Switch back to vanilla pybind11
  tools/workspace/pybind11/package.BUILD.bazel
  tools/workspace/pybind11/patches/eigen_object_matrices.patch
  tools/workspace/pybind11/patches/no_op_wrapper_type.patch
  tools/workspace/pybind11/patches/shared_ptr_lifetime.patch
  tools/workspace/pybind11/pybind11-config-version.cmake
  tools/workspace/pybind11/pybind11-config.cmake
  tools/workspace/pybind11/repository.bzl
Labels: release notes: fix

#22745 Always build Python for wheels
  tools/wheel/image/build-python.sh
  tools/wheel/image/packages-jammy
  tools/wheel/image/provision-base.sh
  tools/wheel/wheel_builder/linux.py
Labels: status: single reviewer ok, release notes: none

#22756 Remove inline destructor in /systems/analysis folder
  systems/analysis/bogacki_shampine3_integrator.cc
  systems/analysis/bogacki_shampine3_integrator.h
  systems/analysis/dense_output.cc
  systems/analysis/dense_output.h
  systems/analysis/explicit_euler_integrator.cc
  systems/analysis/explicit_euler_integrator.h
  systems/analysis/implicit_euler_integrator.cc
  systems/analysis/implicit_euler_integrator.h
  systems/analysis/implicit_integrator.cc
  systems/analysis/implicit_integrator.h
  systems/analysis/integrator_base.cc
  systems/analysis/integrator_base.h
  systems/analysis/radau_integrator.cc
  systems/analysis/radau_integrator.h
  systems/analysis/runge_kutta2_integrator.cc
  systems/analysis/runge_kutta2_integrator.h
  systems/analysis/runge_kutta3_integrator.cc
  systems/analysis/runge_kutta3_integrator.h
  systems/analysis/runge_kutta5_integrator.cc
  systems/analysis/runge_kutta5_integrator.h
  systems/analysis/scalar_dense_output.cc
  systems/analysis/scalar_dense_output.h
  systems/analysis/semi_explicit_euler_integrator.cc
  systems/analysis/semi_explicit_euler_integrator.h
  systems/analysis/stepwise_dense_output.cc
  systems/analysis/stepwise_dense_output.h
  systems/analysis/velocity_implicit_euler_integrator.cc
  systems/analysis/velocity_implicit_euler_integrator.h
Labels: status: single reviewer ok, release notes: none

#22580 [build] Publish linux wheels for Python 3.13
  doc/_pages/installation.md
  doc/_pages/release_playbook.md
  tools/release_engineering/download_release_candidate.py
  tools/wheel/wheel_builder/linux.py
Labels: priority: medium, release notes: fix

#22759 [workspace] Adjust to renamed upstream and checksum
  tools/workspace/poisson_disk_sampling_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#22764 Remove inline destructor in /systems and /planning folder
  planning/trajectory_optimization/direct_collocation.cc
  planning/trajectory_optimization/direct_collocation.h
  planning/trajectory_optimization/direct_transcription.cc
  planning/trajectory_optimization/direct_transcription.h
  planning/trajectory_optimization/integration_constraint.cc
  planning/trajectory_optimization/integration_constraint.h
  planning/trajectory_optimization/multiple_shooting.cc
  planning/trajectory_optimization/multiple_shooting.h
  systems/framework/diagram_discrete_values.cc
  systems/framework/diagram_discrete_values.h
  systems/framework/diagram_output_port.cc
  systems/framework/diagram_output_port.h
  systems/framework/discrete_values.cc
  systems/framework/discrete_values.h
  systems/framework/leaf_output_port.cc
  systems/framework/leaf_output_port.h
  systems/framework/output_port.cc
  systems/framework/output_port.h
  systems/framework/parameters.cc
  systems/framework/parameters.h
  systems/framework/single_output_vector_source.cc
  systems/framework/single_output_vector_source.h
  systems/framework/vector_base.cc
  systems/framework/vector_base.h
  systems/framework/vector_system.cc
  systems/framework/vector_system.h
  systems/optimization/system_constraint_wrapper.cc
  systems/optimization/system_constraint_wrapper.h
  systems/primitives/discrete_time_delay.cc
  systems/primitives/discrete_time_delay.h
  systems/primitives/pass_through.cc
  systems/primitives/pass_through.h
  systems/primitives/symbolic_vector_system.cc
  systems/primitives/symbolic_vector_system.h
  systems/primitives/trajectory_source.cc
  systems/primitives/trajectory_source.h
  systems/primitives/zero_order_hold.cc
  systems/primitives/zero_order_hold.h
  systems/rendering/multibody_position_to_geometry_pose.cc
  systems/rendering/multibody_position_to_geometry_pose.h
Labels: status: single reviewer ok, release notes: none

#22765 [visualization] Fix divide-by-zero in ColorizeDepthImage
  visualization/colorize_depth_image.cc
  visualization/test/colorize_depth_image_test.cc
Labels: priority: high, status: single reviewer ok, release notes: fix

#22766 Fix CMake dependencies
  CMakeLists.txt
Labels: release notes: none

#22662 Switch non-test code to use Parser(builder)
  bindings/pydrake/examples/gym/envs/cart_pole.py
  bindings/pydrake/examples/multibody/cart_pole_passive_simulation.py
  bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py
  bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py
  bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb
  bindings/pydrake/systems/drawing_graphviz_example.py
  bindings/pydrake/systems/jupyter_widgets_examples.ipynb
  doc/_pages/python_bindings.md
  examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
  examples/allegro_hand/run_allegro_constant_load_demo.cc
  examples/atlas/atlas_run_dynamics.cc
  examples/hydroelastic/python_ball_paddle/contact_sim_demo.py
  examples/hydroelastic/python_nonconvex_mesh/drop_pepper.py
  examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc
  examples/kinova_jaco_arm/jaco_simulation.cc
  examples/kuka_iiwa_arm/kuka_simulation.cc
  examples/multibody/acrobot/run_lqr.cc
  examples/multibody/cart_pole/cart_pole_passive_simulation.cc
  examples/multibody/deformable/bubble_gripper.cc
  examples/multibody/four_bar/passive_simulation.cc
  examples/multibody/strandbeest/run_with_motor.cc
  examples/planar_gripper/gripper_brick.cc
  examples/planar_gripper/planar_gripper_simulation.cc
  examples/quadrotor/run_quadrotor_dynamics.cc
  examples/simple_gripper/simple_gripper.cc
  multibody/inverse_kinematics/inverse_kinematics.h
  multibody/test_utilities/robot_model.cc
  planning/robot_diagram_builder.cc
  planning/test/robot_diagram_test.cc
  tutorials/authoring_multibody_simulation.ipynb
  tutorials/hydroelastic_contact_basics.ipynb
  tutorials/hydroelastic_contact_nonconvex_mesh.ipynb
  tutorials/pyplot_animation_multibody_plant.ipynb
  tutorials/rendering_multibody_plant.ipynb
Labels: release notes: none

#22753 [sap] Remove bogus assertion on Kp > 0
  multibody/contact_solvers/sap/sap_pd_controller_constraint.cc
  multibody/plant/test/sap_driver_pd_controller_constraints_test.cc
Labels: priority: low, release notes: fix

#22767 Fix Drake's ssize wrapper
  common/ssize.h
Labels: status: single reviewer ok, release notes: none

#22768 [controllers] Enable clang-format-lint
  systems/controllers/BUILD.bazel
  systems/controllers/dynamic_programming.h
  systems/controllers/inverse_dynamics_controller.cc
  systems/controllers/inverse_dynamics_controller.h
  systems/controllers/joint_stiffness_controller.cc
  systems/controllers/joint_stiffness_controller.h
  systems/controllers/linear_quadratic_regulator.cc
  systems/controllers/pid_controlled_system.cc
  systems/controllers/pid_controlled_system.h
  systems/controllers/state_feedback_controller_interface.h
  systems/controllers/test/dynamic_programming_test.cc
  systems/controllers/test/linear_quadratic_regulator_test.cc
  systems/controllers/test/pid_controlled_system_test.cc
  systems/controllers/test/setpoint_test.cc
  systems/controllers/test_utilities/BUILD.bazel
  systems/controllers/test_utilities/compute_torque.h
Labels: priority: low, status: single reviewer ok, release notes: none

#22686 Support x'Nu term in discrete-time LQR
  bindings/pydrake/systems/controllers_py.cc
  bindings/pydrake/systems/test/controllers_test.py
  systems/controllers/linear_quadratic_regulator.cc
  systems/controllers/linear_quadratic_regulator.h
  systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
  systems/controllers/test/linear_quadratic_regulator_test.cc
Labels: release notes: feature

#22719 [mpm] Add grid-particle iterate function
  multibody/mpm/BUILD.bazel
  multibody/mpm/particle_sorter.h
  multibody/mpm/sparse_grid.h
  multibody/mpm/test/particle_sorter_test.cc
Labels: release notes: none

#22711 [multibody] Adds SapFixedTendonConstraint
  multibody/contact_solvers/sap/BUILD.bazel
  multibody/contact_solvers/sap/sap_tendon_constraint.cc
  multibody/contact_solvers/sap/sap_tendon_constraint.h
  multibody/contact_solvers/sap/test/sap_tendon_constraint_test.cc
Labels: release notes: none

#22763 Set gradient sparsity pattern in KinTrajOpt AddVelocityConstraint
  planning/trajectory_optimization/BUILD.bazel
  planning/trajectory_optimization/kinematic_trajectory_optimization.cc
  planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
  solvers/test_utilities/BUILD.bazel
  solvers/test_utilities/check_gradient_sparsity_pattern.cc
  solvers/test_utilities/check_gradient_sparsity_pattern.h
Labels: release notes: fix

#22781 [pydrake] Fix a bug in the Simulator constructor
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/general_test.py
Labels: release notes: fix

#22760 MakeSemidefiniteRelaxation parse quadratic equality constraints in linear equality constraints instead of two linear inequalities.
  solvers/semidefinite_relaxation_internal.cc
  solvers/test/semidefinite_relaxation_internal_test.cc
Labels: status: squashing now, release notes: none

#22784 [webpage] Binary links were incomplete
  doc/_pages/from_binary.md
Labels: status: single reviewer ok, release notes: none

#22772 [geometry] Introduce 3D scale in mesh processing algorithms
  bindings/pydrake/geometry/geometry_py_meshes.cc
  bindings/pydrake/geometry/test/meshes_test.py
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/make_convex_hull_mesh.cc
  geometry/proximity/make_convex_hull_mesh_impl.cc
  geometry/proximity/make_convex_hull_mesh_impl.h
  geometry/proximity/make_mesh_from_vtk.cc
  geometry/proximity/obj_to_surface_mesh.cc
  geometry/proximity/obj_to_surface_mesh.h
  geometry/proximity/test/make_convex_hull_mesh_impl_test.cc
  geometry/proximity/test/obj_to_surface_mesh_test.cc
  geometry/proximity/test/vtk_to_volume_mesh_test.cc
  geometry/proximity/vtk_to_volume_mesh.cc
  geometry/proximity/vtk_to_volume_mesh.h
  geometry/read_obj.cc
  geometry/read_obj.h
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/test/read_obj_test.cc
  multibody/parsing/detail_mesh_parser.cc
Labels: release notes: feature

#22786 Fix doxygen error in obj_to_surface_mesh.h
  geometry/proximity/obj_to_surface_mesh.h
Labels: status: single reviewer ok, release notes: none

#22702 [workspace] Upgrade vtk_internal to latest commit
  geometry/proximity/make_convex_hull_mesh_impl.cc
  geometry/render_vtk/internal_render_engine_vtk.cc
  tools/workspace/vtk_internal/patches/gltf_scenes_vector.patch
  tools/workspace/vtk_internal/patches/upstream/fix_illumination_bugs.patch
  tools/workspace/vtk_internal/patches/upstream/gltf_importer_from_stream.patch
  tools/workspace/vtk_internal/patches/upstream/gltf_selected_load.patch
  tools/workspace/vtk_internal/patches/upstream/io_geometry_gltf_default_scene.patch
  tools/workspace/vtk_internal/patches/vtkiohdf_newline.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#22771 Fix improper use of QDLDL by SCS
  tools/workspace/scs_internal/patches/upstream/fix_arg.patch
  tools/workspace/scs_internal/repository.bzl
Labels: status: single reviewer ok, release notes: none

#22780 [mpm] Add MockSparseGrid
  multibody/mpm/BUILD.bazel
  multibody/mpm/grid_data.h
  multibody/mpm/mock_sparse_grid.cc
  multibody/mpm/mock_sparse_grid.h
  multibody/mpm/sparse_grid.h
  multibody/mpm/test/particle_sorter_test.cc
  multibody/mpm/test/sparse_grid_test.cc
Labels: release notes: none

#22787 Patch brittle `visualization_install_tests` for macOS
  bindings/pydrake/visualization/test/visualization_install_tests.py
Labels: release notes: none

#22717 [multibody] Adds MultibodyPlant::AddTendonConstraint()
  multibody/plant/BUILD.bazel
  multibody/plant/constraint_specs.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/sap_driver_tendon_constraints_test.cc
Labels: release notes: feature

#22794 [hotfix] Fix test-time SpGrid out-of-bound issue
  multibody/mpm/test/sparse_grid_test.cc
Labels: status: single reviewer ok, release notes: none

#22801 Revert "[multibody] Adds MultibodyPlant::AddTendonConstraint()"
  multibody/plant/BUILD.bazel
  multibody/plant/constraint_specs.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/sap_driver_tendon_constraints_test.cc
Labels: status: single reviewer ok, release notes: feature

#22762 Avoid rejecting system with floating abstract input port in FiniteHorizonLinearQuadraticRegulator
  systems/controllers/BUILD.bazel
  systems/controllers/finite_horizon_linear_quadratic_regulator.cc
  systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Labels: release notes: fix

#22802 [workspace] Fix vtk_internal module file parsing
  tools/workspace/vtk_internal/patches/vtkiohdf_newline.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#22803 [multibody] Adds MultibodyPlant::AddTendonConstraint()
  multibody/plant/BUILD.bazel
  multibody/plant/constraint_specs.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/sap_driver.h
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/sap_driver_tendon_constraints_test.cc
Labels: status: squashing now, release notes: feature

#22806 [meshcat] Add `GetButtonNames()`
  bindings/pydrake/geometry/geometry_py_visualizers.cc
  bindings/pydrake/geometry/test/visualizers_test.py
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/test/meshcat_test.cc
Labels: status: single reviewer ok, release notes: feature

#22810 [py yaml] Alphabetize imports
  bindings/pydrake/common/yaml.py
Labels: priority: low, status: single reviewer ok, release notes: none

#22811 [py sensors] ApplyCameraConfig overloaded on LcmInterfaceSystem
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/sensors_py.cc
  bindings/pydrake/systems/sensors_py_camera_config.cc
  bindings/pydrake/systems/test/sensors_test.py
Labels: priority: high, status: single reviewer ok, release notes: fix

#22779 Build wheels on AlmaLinux instead of Ubuntu
  tools/wheel/.dockerignore
  tools/wheel/Dockerfile
  tools/wheel/image/build-wheel.sh
  tools/wheel/image/packages-almalinux
  tools/wheel/image/provision-base.sh
  tools/wheel/image/provision-python.sh
  tools/wheel/licenses/gcc/copyright
  tools/wheel/wheel_builder/linux.py
  tools/workspace/pybind11/libclang_setup.py
Labels: release notes: feature

#22805 [workspace] Rename patches per convention
  tools/workspace/vtk_internal/patches/common_datamodel_no_pegtl.patch
  tools/workspace/vtk_internal/patches/common_executionmodel_disable_static_destructors.patch
  tools/workspace/vtk_internal/patches/rendering_opengl2_preserve_direct_light_specular_reflections.patch
  tools/workspace/vtk_internal/patches/upstream/io_geometry_gltf_default_scene.patch
  tools/workspace/vtk_internal/patches/upstream/rendering_opengl2_scaled_albedo_for_ibl.patch
  tools/workspace/vtk_internal/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: none

#22773 Add cloning functionality for IntegratorBase
  bindings/pydrake/systems/analysis_py.cc
  systems/analysis/BUILD.bazel
  systems/analysis/bogacki_shampine3_integrator.cc
  systems/analysis/bogacki_shampine3_integrator.h
  systems/analysis/explicit_euler_integrator.cc
  systems/analysis/explicit_euler_integrator.h
  systems/analysis/implicit_euler_integrator.cc
  systems/analysis/implicit_euler_integrator.h
  systems/analysis/implicit_integrator.cc
  systems/analysis/implicit_integrator.h
  systems/analysis/integrator_base.cc
  systems/analysis/integrator_base.h
  systems/analysis/radau_integrator.cc
  systems/analysis/radau_integrator.h
  systems/analysis/runge_kutta2_integrator.cc
  systems/analysis/runge_kutta2_integrator.h
  systems/analysis/runge_kutta3_integrator.cc
  systems/analysis/runge_kutta3_integrator.h
  systems/analysis/runge_kutta5_integrator.cc
  systems/analysis/runge_kutta5_integrator.h
  systems/analysis/semi_explicit_euler_integrator.cc
  systems/analysis/semi_explicit_euler_integrator.h
  systems/analysis/test/implicit_integrator_test.cc
  systems/analysis/test/integrator_base_test.cc
  systems/analysis/velocity_implicit_euler_integrator.cc
  systems/analysis/velocity_implicit_euler_integrator.h
Labels: release notes: feature

#22795 [pydrake] Fix costs and constraints memory hazards
  bindings/pydrake/planning/planning_py_trajectory_optimization.cc
  bindings/pydrake/planning/test/trajectory_optimization_test.py
  bindings/pydrake/solvers/solvers_py_evaluators.cc
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/solvers/test/evaluators_test.py
  bindings/pydrake/solvers/test/mathematicalprogram_test.py
Labels: release notes: fix

#22775 [pydrake] Avoid lifetime hazards with port references
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/test/custom_test.py
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test_utilities/BUILD.bazel
  bindings/pydrake/systems/test_utilities/__init__.py
  bindings/pydrake/systems/test_utilities/framework_test_util.py
  bindings/pydrake/test/memory_leak_test.py
Labels: release notes: fix

#22832 [pydrake] Retire no-op py::wrapper
  bindings/pydrake/geometry/geometry_py_optimization.cc
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/planning/planning_py_graph_algorithms.cc
  bindings/pydrake/pydrake_doxygen.h
  bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/lcm_py.cc
  bindings/pydrake/trajectories_py.cc
  tools/workspace/pybind11/patches/no_op_wrapper_type.patch
  tools/workspace/pybind11/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22831 [analysis] Enable clang-format-lint
  systems/analysis/BUILD.bazel
  systems/analysis/batch_eval.h
  systems/analysis/bogacki_shampine3_integrator.cc
  systems/analysis/bogacki_shampine3_integrator.h
  systems/analysis/dense_output.h
  systems/analysis/explicit_euler_integrator.h
  systems/analysis/hermitian_dense_output.h
  systems/analysis/implicit_euler_integrator.cc
  systems/analysis/implicit_euler_integrator.h
  systems/analysis/implicit_integrator.cc
  systems/analysis/implicit_integrator.h
  systems/analysis/integrator_base.cc
  systems/analysis/integrator_base.h
  systems/analysis/lyapunov.cc
  systems/analysis/monte_carlo.cc
  systems/analysis/radau_integrator.cc
  systems/analysis/radau_integrator.h
  systems/analysis/runge_kutta2_integrator.h
  systems/analysis/runge_kutta3_integrator.cc
  systems/analysis/runge_kutta5_integrator.cc
  systems/analysis/runge_kutta5_integrator.h
  systems/analysis/scalar_dense_output.h
  systems/analysis/scalar_view_dense_output.h
  systems/analysis/simulator.cc
  systems/analysis/simulator.h
  systems/analysis/simulator_config_functions.cc
  systems/analysis/simulator_config_functions.h
  systems/analysis/simulator_gflags.cc
  systems/analysis/simulator_print_stats.cc
  systems/analysis/simulator_python_internal.h
  systems/analysis/simulator_status.cc
  systems/analysis/simulator_status.h
  systems/analysis/test/antiderivative_function_test.cc
  systems/analysis/test/bogacki_shampine3_integrator_test.cc
  systems/analysis/test/explicit_euler_integrator_test.cc
  systems/analysis/test/hermitian_dense_output_test.cc
  systems/analysis/test/implicit_integrator_test.cc
  systems/analysis/test/initial_value_problem_test.cc
  systems/analysis/test/lyapunov_test.cc
  systems/analysis/test/monte_carlo_test.cc
  systems/analysis/test/radau_integrator_test.cc
  systems/analysis/test/realtime_rate_calculator_test.cc
  systems/analysis/test/runge_kutta2_integrator_test.cc
  systems/analysis/test/runge_kutta3_integrator_test.cc
  systems/analysis/test/runge_kutta5_integrator_test.cc
  systems/analysis/test/scalar_initial_value_problem_test.cc
  systems/analysis/test/scalar_view_dense_output_test.cc
  systems/analysis/test/semi_explicit_euler_integrator_test.cc
  systems/analysis/test/simulator_config_functions_test.cc
  systems/analysis/test/simulator_denorm_test.cc
  systems/analysis/test/simulator_print_stats_test.cc
  systems/analysis/test/simulator_python_internal_test.cc
  systems/analysis/test/simulator_test.cc
  systems/analysis/velocity_implicit_euler_integrator.cc
  systems/analysis/velocity_implicit_euler_integrator.h
Labels: priority: low, status: single reviewer ok, release notes: none

#22837 [doc] Bump copyright year to 2025
  LICENSE.TXT
Labels: priority: low, status: single reviewer ok, release notes: none

#22829 [perception] Enable clang-format-lint
  perception/BUILD.bazel
  perception/depth_image_to_point_cloud.cc
  perception/point_cloud.cc
  perception/point_cloud.h
  perception/point_cloud_flags.cc
  perception/point_cloud_flags.h
  perception/point_cloud_to_lcm.cc
  perception/test/depth_image_to_point_cloud_test.cc
  perception/test/point_cloud_test.cc
  perception/test/point_cloud_to_lcm_test.cc
Labels: priority: low, status: single reviewer ok, release notes: none

#22839 [parsing] Drop FQNs for MatchesRegex in sdf parser test
  multibody/parsing/test/detail_sdf_parser_test.cc
Labels: status: single reviewer ok, release notes: none

#22841 [tutorials] Disable hydroelastic_contact_basics test
  tools/jupyter/jupyter_py.bzl
  tutorials/BUILD.bazel
Labels: priority: emergency, status: single reviewer ok, release notes: none

#22828 [workspace] Disable monthly upgrades of rust_toolchain
  tools/workspace/metadata.py
  tools/workspace/new_release.py
Labels: priority: low, release notes: none
