Repository RobotLocomotion/drake, pull requests merged in 2025-04, with the labels that each got.

#22821 [multibody] Fix crash on frame elements not added to a plant
  multibody/tree/BUILD.bazel
  multibody/tree/frame.h
  multibody/tree/multibody_element.h
  multibody/tree/test/frames_test.cc
Labels: priority: medium, release notes: fix

#22830 [doc] Update Jenkins links in release playbook
  doc/_pages/release_playbook.md
Labels: release notes: none

#22833 [pydrake] Update the technical note
  bindings/pydrake/pydrake_doxygen.h
Labels: release notes: none

#22840 [parsing] Fix parsing of erroneous curvilinear joint input
  multibody/parsing/detail_sdf_parser.cc
  multibody/parsing/detail_urdf_parser.cc
  multibody/parsing/test/detail_sdf_parser_test.cc
  multibody/parsing/test/detail_urdf_parser_test.cc
Labels: status: single reviewer ok, release notes: fix

#22778 Implements distance constraints parameters
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/inverse_kinematics/add_multibody_plant_constraints.cc
  multibody/plant/BUILD.bazel
  multibody/plant/constraint_specs.h
  multibody/plant/discrete_update_manager.cc
  multibody/plant/discrete_update_manager.h
  multibody/plant/distance_constraint_params.cc
  multibody/plant/distance_constraint_params.h
  multibody/plant/multibody_plant.cc
  multibody/plant/multibody_plant.h
  multibody/plant/multibody_plant_discrete_update_manager_attorney.h
  multibody/plant/sap_driver.cc
  multibody/plant/test/distance_constraint_params_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/plant/test/sap_driver_ball_constraints_test.cc
  multibody/plant/test/sap_driver_distance_constraints_test.cc
  multibody/plant/test/sap_driver_tendon_constraints_test.cc
  multibody/plant/test/sap_driver_weld_constraints_test.cc
  multibody/tree/multibody_tree.h
Labels: release notes: feature

#22687 Add discrete-time steady-state Kalman filter
  bindings/pydrake/systems/estimators_py.cc
  bindings/pydrake/systems/test/estimators_test.py
  systems/estimators/BUILD.bazel
  systems/estimators/kalman_filter.cc
  systems/estimators/kalman_filter.h
  systems/estimators/luenberger_observer.cc
  systems/estimators/luenberger_observer.h
  systems/estimators/test/kalman_filter_test.cc
  systems/estimators/test/luenberger_observer_test.cc
Labels: release notes: feature

#22847 Apply named positions move
  manipulation/util/BUILD.bazel
  manipulation/util/named_positions_functions.cc
  manipulation/util/named_positions_functions.h
  manipulation/util/test/named_positions_functions_test.cc
Labels: status: commits are properly curated, release notes: feature

#22842 drake/geometry opts back into clang-format linting
  .clang-format
  CPPLINT.cfg
  bindings/pydrake/.clang-format
  geometry/BUILD.bazel
  geometry/collision_filter_manager.h
  geometry/drake_visualizer.h
  geometry/geometry_state.cc
  geometry/kinematics_vector.cc
  geometry/kinematics_vector.h
  geometry/mesh_source.cc
  geometry/meshcat.cc
  geometry/meshcat.h
  geometry/meshcat_file_storage_internal.h
  geometry/meshcat_internal.cc
  geometry/meshcat_internal.h
  geometry/meshcat_types_internal.h
  geometry/meshcat_visualizer.cc
  geometry/proximity_properties.cc
  geometry/proximity_properties.h
  geometry/query_object.h
  geometry/read_gltf_to_memory.cc
  geometry/read_obj.cc
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/scene_graph_config.cc
  geometry/shape_specification.cc
  geometry/shape_specification.h
  geometry/test/geometry_state_test.cc
  geometry/test/kinematics_vector_test.cc
  geometry/test/mesh_deformation_interpolator_test.cc
  geometry/test/meshcat_internal_test.cc
  geometry/test/meshcat_manual_test.cc
  geometry/test/meshcat_params_test.cc
  geometry/test/meshcat_test.cc
  geometry/test/meshcat_visualizer_test.cc
  geometry/test/proximity_engine_test.cc
  geometry/test/read_obj_test.cc
  geometry/test/scene_graph_test.cc
  geometry/test/shape_specification_test.cc
  geometry/test/shape_specification_thread_test.cc
Labels: status: single reviewer ok, release notes: none

#22838 Implement create IntegratorBase from integration scheme
  systems/analysis/BUILD.bazel
  systems/analysis/simulator_config_functions.cc
  systems/analysis/simulator_config_functions.h
  systems/analysis/simulator_gflags.cc
  systems/analysis/test/simulator_config_functions_test.cc
Labels: release notes: feature

#22800 Add sparsity pattern when KinematicTrajectoryOptimization imposes bounds on acceleration and jerk.
  planning/trajectory_optimization/kinematic_trajectory_optimization.cc
  planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Labels: release notes: fix

#22852 [setup] Upgrade Python venv (mac) to latest
  setup/python/pdm.lock
  setup/python/requirements.txt
Labels: status: single reviewer ok, release notes: fix

#22853 Clean up float format in proximity engine tests
  geometry/test/proximity_engine_test.cc
Labels: status: single reviewer ok, release notes: none

#22859 [examples] Disable test case on macOS
  examples/allegro_hand/joint_control/test/run_twisting_mug_test.py
Labels: status: single reviewer ok, release notes: none

#22824 Proxmity and Parsing use non-uniform scale
  geometry/proximity/hydroelastic_internal.cc
  geometry/proximity/make_mesh_from_vtk.cc
  geometry/proximity/test/hydroelastic_internal_test.cc
  geometry/proximity_engine.cc
  geometry/proximity_engine.h
  geometry/test/geometry_state_test.cc
  geometry/test/proximity_engine_test.cc
  multibody/parsing/detail_mujoco_parser.cc
  multibody/parsing/detail_sdf_geometry.cc
  multibody/parsing/detail_urdf_geometry.cc
  multibody/parsing/detail_usd_geometry.cc
  multibody/parsing/detail_usd_geometry.h
  multibody/parsing/test/detail_mujoco_parser_examples_test.cc
  multibody/parsing/test/detail_mujoco_parser_test.cc
  multibody/parsing/test/detail_sdf_geometry_test.cc
  multibody/parsing/test/detail_urdf_geometry_test.cc
  multibody/parsing/test/detail_usd_geometry_test.cc
  multibody/tree/geometry_spatial_inertia.cc
  multibody/tree/test/geometry_spatial_inertia_test.cc
Labels: release notes: feature

#22823 Adapt visualizers to non-uniform scale
  bindings/pydrake/systems/planar_scenegraph_visualizer.py
  bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
  bindings/pydrake/visualization/_meldis.py
  bindings/pydrake/visualization/test/meldis_test.py
  geometry/drake_visualizer.cc
  geometry/meshcat.cc
  geometry/test/drake_visualizer_test.cc
  geometry/test/meshcat_test.cc
Labels: release notes: feature

#22746 [doc] Overhaul installation documentation
  doc/_config.yml
  doc/_pages/apt.md
  doc/_pages/developers.md
  doc/_pages/docker.md
  doc/_pages/from_binary.md
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/pip.md
  doc/_pages/python_bindings.md
Labels: status: squashing now, release notes: none

#22850 [multibody] Improve set_default_positions() error message
  manipulation/util/named_positions_functions.cc
  manipulation/util/test/named_positions_functions_test.cc
  multibody/tree/BUILD.bazel
  multibody/tree/joint.cc
  multibody/tree/test/quaternion_floating_joint_test.cc
Labels: status: single reviewer ok, release notes: fix

#22796 Added gh issue template for post-release actions
  .github/ISSUE_TEMPLATE/POST_RELEASE_ACTIONS.yml
  doc/_pages/release_playbook.md
Labels: release notes: none

#22857 [workspace] Upgrade vtk_internal to latest commit
  tools/workspace/vtk_internal/gen/vtkRenderingOpenGL2ObjectFactory.cxx
  tools/workspace/vtk_internal/gen/vtkRenderingOpenGL2ObjectFactory.h
  tools/workspace/vtk_internal/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22854 [workspace] Upgrade googlebenchmark to latest release v1.9.2
  tools/workspace/googlebenchmark/patches/console_allocs.patch
  tools/workspace/googlebenchmark/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22867 [systems] Move DiscreteTimeApproximation into analysis
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/all.py
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/framework_py_systems.cc
  bindings/pydrake/systems/primitives_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  bindings/pydrake/systems/test/primitives_test.py
  systems/analysis/BUILD.bazel
  systems/analysis/discrete_time_approximation.cc
  systems/analysis/discrete_time_approximation.h
  systems/analysis/test/discrete_time_approximation_test.cc
  systems/primitives/linear_system.h
  systems/primitives/test/linear_system_test.cc
Labels: priority: medium, status: single reviewer ok, release notes: newly deprecated

#22861 Suppress benign eXIf warnings from libpng 1.6.47
  tools/workspace/libpng_internal/png_drake_vendor.h
  tools/workspace/libpng_internal/repository.bzl
Labels: status: squashing now, release notes: fix

#22864 [examples] Demonstrate ApplyNamedPositionsAsDefaults
  examples/hardware_sim/BUILD.bazel
  examples/hardware_sim/example_scenarios.yaml
  examples/hardware_sim/hardware_sim.cc
  examples/hardware_sim/hardware_sim.py
  examples/hardware_sim/scenario.h
  examples/hardware_sim/test/robot_commander_test.py
Labels: release notes: none

#22827 Upgrade macOS to Python3.13
  CMakeLists.txt
  bindings/pydrake/common/test/deprecation_autocomplete_test.py
  bindings/pydrake/common/test/yaml_typed_test.py
  doc/_pages/from_source.md
  doc/_pages/installation.md
  doc/_pages/release_playbook.md
  doc/_release-notes/end_of_support.md
  setup/mac/binary_distribution/Brewfile
  setup/mac/binary_distribution/install_prereqs.sh
  tools/release_engineering/download_release_candidate.py
  tools/wheel/wheel_builder/macos.py
  tools/workspace/python/repository.bzl
Labels: status: squashing now, release notes: fix

#22814 [math] Add axial rotation and transform functions
  math/rigid_transform.h
  math/rotation_matrix.cc
  math/rotation_matrix.h
  math/test/rigid_transform_test.cc
  math/test/rotation_matrix_test.cc
Labels: priority: medium, release notes: none

#22860 [geometry] Don't hard-code ClarabelSolver
  geometry/proximity/BUILD.bazel
  geometry/proximity/inflate_mesh.cc
  geometry/proximity/test/inflate_mesh_test.cc
Labels: priority: low, release notes: none

#22868 [pydrake] Bind DeformableContactInfo and ContactResults access
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/deformable_contact_info.h
  multibody/plant/test/deformable_contact_info_test.cc
Labels: release notes: fix

#22851 Support scalar conversion for LuenbergerObserver
  bindings/pydrake/systems/BUILD.bazel
  bindings/pydrake/systems/estimators_py.cc
  bindings/pydrake/systems/test/estimators_test.py
  systems/estimators/BUILD.bazel
  systems/estimators/luenberger_observer.cc
  systems/estimators/luenberger_observer.h
  systems/estimators/test/luenberger_observer_test.cc
Labels: release notes: feature

#22876 [workspace] Upgrade drake_models to latest version
  tools/workspace/drake_models/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22807 [mpm] Add Transfer
  common/extract_double.h
  common/test/extract_double_test.cc
  multibody/mpm/BUILD.bazel
  multibody/mpm/mock_sparse_grid.cc
  multibody/mpm/mock_sparse_grid.h
  multibody/mpm/particle_data.cc
  multibody/mpm/particle_data.h
  multibody/mpm/sparse_grid.cc
  multibody/mpm/sparse_grid.h
  multibody/mpm/test/particle_data_test.cc
  multibody/mpm/test/particle_sorter_test.cc
  multibody/mpm/test/sparse_grid_test.cc
  multibody/mpm/test/transfer_test.cc
  multibody/mpm/transfer.cc
  multibody/mpm/transfer.h
Labels: status: squashing now, release notes: none

#22875 Install macOS wheel builder deps with `--developer` flag
  setup/mac/source_distribution/Brewfile-developer
  setup/mac/source_distribution/install_prereqs.sh
Labels: release notes: fix

#21077 [manipulation] Add coarse notes for torque conventions
  lcmtypes/lcmt_iiwa_status.lcm
  lcmtypes/lcmt_jaco_status.lcm
  lcmtypes/lcmt_panda_status.lcm
  manipulation/README.md
  manipulation/kuka_iiwa/build_iiwa_control.cc
  manipulation/kuka_iiwa/build_iiwa_control.h
Labels: release notes: none

#22878 [workspace] Upgrade styleguide to latest commit
  bindings/pydrake/common/text_logging_pybind.cc
  common/hwy_dynamic_impl.h
  common/overloaded.h
  examples/pendulum/pendulum_parameters_derivatives.cc
  tools/workspace/styleguide/repository.bzl
Labels: priority: low, status: single reviewer ok, release notes: fix

#22877 Host tutorials images on Drake's website
  doc/doxygen_cxx/build.py
  tutorials/images/README.md
  tutorials/images/env_color_room_in_situ.png
  tutorials/images/final_robot.jpg
  tutorials/images/light_types.png
  tutorials/images/publish_images_via_doxygen.h
  tutorials/images/shadow_map_registration_directional.png
  tutorials/images/shadow_map_registration_spot.png
  tutorials/images/shadow_map_resolution.png
  tutorials/images/simple_reflection.png
  tutorials/images/sources/light_types.svg
  tutorials/images/sources/shadow_map_registration.svg
  tutorials/images/sources/shadow_map_resolution.svg
  tutorials/images/sources/simple_reflection.svg
Labels: status: single reviewer ok, release notes: none

#22872 Add VertexPartialPermutation
  geometry/proximity/test/deformable_field_intersection_test.cc
  geometry/query_results/deformable_contact.cc
  geometry/query_results/deformable_contact.h
  geometry/query_results/test/deformable_contact_test.cc
  multibody/contact_solvers/sap/partial_permutation.cc
  multibody/contact_solvers/sap/partial_permutation.h
  multibody/contact_solvers/sap/test/partial_permutation_test.cc
  multibody/plant/deformable_driver.cc
  multibody/plant/deformable_driver.h
  multibody/plant/test/deformable_driver_contact_kinematics_test.cc
  multibody/plant/test/deformable_driver_contact_test.cc
Labels: release notes: none

#22879 [pydrake] Add some missing SceneGraph/Inspector bindings
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/test/scene_graph_test.py
Labels: release notes: fix

#22871 Compare RenderEngineParams with existing RenderEngine instances
  bindings/pydrake/geometry/geometry_py_render.cc
  bindings/pydrake/geometry/geometry_py_scene_graph.cc
  bindings/pydrake/geometry/test/render_test.py
  bindings/pydrake/geometry/test/scene_graph_test.py
  geometry/render/render_engine.cc
  geometry/render/render_engine.h
  geometry/render_gl/BUILD.bazel
  geometry/render_gl/internal_render_engine_gl.cc
  geometry/render_gl/internal_render_engine_gl.h
  geometry/render_gl/test/internal_render_engine_gl_test.cc
  geometry/render_gltf_client/BUILD.bazel
  geometry/render_gltf_client/internal_render_engine_gltf_client.cc
  geometry/render_gltf_client/internal_render_engine_gltf_client.h
  geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc
  geometry/render_vtk/BUILD.bazel
  geometry/render_vtk/internal_render_engine_vtk.cc
  geometry/render_vtk/internal_render_engine_vtk.h
  geometry/render_vtk/test/internal_render_engine_vtk_test.cc
  geometry/scene_graph.cc
  geometry/scene_graph.h
  geometry/test/scene_graph_test.cc
  geometry/test_utilities/dummy_render_engine.h
  systems/sensors/BUILD.bazel
  systems/sensors/camera_config.h
  systems/sensors/camera_config_functions.cc
  systems/sensors/test/camera_config_functions_test.cc
Labels: release notes: feature

#22881 fix a bug where prefered solvers were not being used in IrizZo
  planning/iris/BUILD.bazel
  planning/iris/iris_zo.cc
  planning/iris/iris_zo.h
Labels: status: squashing now, release notes: none

#22884 [pydrake] Fix DiagramBuilder AddSystem return value policy
  bindings/pydrake/systems/framework_py_semantics.cc
  bindings/pydrake/systems/test/general_test.py
  bindings/pydrake/systems/test/test_util_py.cc
Labels: release notes: fix

#22888 [workspace] Upgrade toolchains_llvm to latest release 1.4.0
  MODULE.bazel
Labels: priority: medium, status: single reviewer ok, release notes: fix

#22631 Add a tutorial teaching about lighting in Drake
  geometry/meshcat.html
  tutorials/BUILD.bazel
  tutorials/configuring_rendering_lighting.ipynb
  tutorials/index.ipynb
Labels: release notes: feature

#22835 [doc] Add release notes v1.40.0
  doc/_pages/from_binary.md
  doc/_release-notes/v1.40.0.md
Labels: status: single reviewer ok, release notes: none

#22892 [tools] Update release tooling post-1.40.0
  doc/_pages/release_playbook.md
  tools/release_engineering/download_release_candidate.py
  tools/release_engineering/relnotes.py
Labels: priority: low, status: single reviewer ok, release notes: none

#22721 [doc] Add documentation for running drake-external-examples CI jobs on Drake PRs
  doc/_pages/developers.md
  doc/_pages/downstream_testing.md
  doc/_pages/jenkins.md
Labels: status: squashing now, release notes: none

#22893 [doc] Drop support for macOS for Python 3.11 wheels
  doc/_pages/installation.md
  doc/_pages/release_playbook.md
  doc/_release-notes/end_of_support.md
  setup/mac/source_distribution/Brewfile-developer
  tools/release_engineering/download_release_candidate.py
  tools/wheel/wheel_builder/macos.py
Labels: priority: low, release notes: removal of deprecated

#22895 Overload `ExtractValue` and `ExtractGradient` to allow preallocated output matrix
  math/BUILD.bazel
  math/autodiff.h
  math/autodiff_gradient.h
  math/test/autodiff_test.cc
Labels: release notes: feature

#22899 [tutorials] Tidy up lighting tutorial
  tutorials/configuring_rendering_lighting.ipynb
Labels: status: squashing now, status: single reviewer ok, release notes: none

#22900 Add pydrake binding for SchunkWsgTrajectoryGenerator
  bindings/pydrake/manipulation/manipulation_py_schunk_wsg.cc
  bindings/pydrake/manipulation/test/schunk_wsg_test.py
Labels: status: single reviewer ok, release notes: fix

#22901 [build] Use our bazelversion pin in CMake builds also
  CMakeLists.txt
Labels: priority: medium, status: single reviewer ok, release notes: fix

#22886 [doc] Purge MacStadium and macOS cache server refs from buildcop docs
  doc/_pages/buildcop.md
Labels: release notes: none

#22903 Add explicit requirement for diffutils
  setup/ubuntu/source_distribution/packages-jammy.txt
  setup/ubuntu/source_distribution/packages-noble.txt
  tools/wheel/image/packages-almalinux
Labels: status: single reviewer ok, release notes: none

#22652 Add DiscreteTimeApproximation for general continuous-time systems
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  systems/analysis/BUILD.bazel
  systems/analysis/discrete_time_approximation.cc
  systems/analysis/discrete_time_approximation.h
  systems/analysis/test/discrete_time_approximation_test.cc
Labels: release notes: feature

#22882 Add MpmModel and SolverState
  multibody/mpm/BUILD.bazel
  multibody/mpm/mock_sparse_grid.cc
  multibody/mpm/mock_sparse_grid.h
  multibody/mpm/mpm_model.cc
  multibody/mpm/mpm_model.h
  multibody/mpm/particle_data.h
  multibody/mpm/particle_sorter.h
  multibody/mpm/solver_state.cc
  multibody/mpm/solver_state.h
  multibody/mpm/sparse_grid.cc
  multibody/mpm/sparse_grid.h
  multibody/mpm/spgrid.h
  multibody/mpm/test/mpm_model_test.cc
  multibody/mpm/test/particle_sorter_test.cc
  multibody/mpm/test/sparse_grid_test.cc
  multibody/mpm/test/spgrid_test.cc
  multibody/mpm/transfer.h
Labels: status: squashing now, release notes: none

#22911 Add position getter and setters for deformables
  bindings/pydrake/multibody/plant_py.cc
  bindings/pydrake/multibody/test/plant_test.py
  multibody/plant/deformable_model.cc
  multibody/plant/deformable_model.h
  multibody/plant/test/deformable_model_test.cc
Labels: priority: high, release notes: none

#22904 Don't fail wheel build if symlink exists
  tools/wheel/wheel_builder/macos.py
Labels: release notes: none

#22902 [doc] Remove links & references to macOS unprovisioned jobs
  doc/_pages/jenkins.md
  doc/_pages/release_playbook.md
Labels: status: squashing now, release notes: none

#22909 Add retries for possibly flaky `MeshcatTest` on macOS
  geometry/BUILD.bazel
Labels: release notes: none

#22898 Update CMake versioning policies on for Drake source and installation
  CMakeLists.txt
  doc/_pages/from_source.md
  tools/install/libdrake/drake-config.cmake.in
  tools/install/libdrake/test/drake_python_dir_install_test.py
  tools/install/libdrake/test/find_package_drake_install_test.py
Labels: release notes: fix

#22918 [workspace] Upgrade bzlmod eigen to 3.4.0.bcr.3
  MODULE.bazel
Labels: priority: high, status: single reviewer ok, release notes: fix

#22912 Set sparsity pattern for KinematicTrajectoryOptimization effort bounds.
  planning/trajectory_optimization/kinematic_trajectory_optimization.cc
  planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Labels: release notes: feature

#22873 [multibody] Use specialized transforms for revolute joint performance
  math/rigid_transform.h
  math/rotation_matrix.h
  math/test/rigid_transform_test.cc
  math/test/rotation_matrix_test.cc
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/body_node.cc
  multibody/tree/body_node.h
  multibody/tree/body_node_impl.cc
  multibody/tree/body_node_impl.h
  multibody/tree/body_node_impl_mass_matrix.cc
  multibody/tree/curvilinear_mobilizer.h
  multibody/tree/frame.h
  multibody/tree/frame_body_pose_cache.h
  multibody/tree/joint.h
  multibody/tree/mobilizer_impl.h
  multibody/tree/multibody_tree.cc
  multibody/tree/planar_mobilizer.cc
  multibody/tree/planar_mobilizer.h
  multibody/tree/prismatic_mobilizer.cc
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/quaternion_floating_mobilizer.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/rpy_ball_mobilizer.cc
  multibody/tree/rpy_ball_mobilizer.h
  multibody/tree/rpy_floating_mobilizer.cc
  multibody/tree/rpy_floating_mobilizer.h
  multibody/tree/screw_mobilizer.cc
  multibody/tree/screw_mobilizer.h
  multibody/tree/test/body_node_test.cc
  multibody/tree/test/planar_mobilizer_test.cc
  multibody/tree/test/prismatic_mobilizer_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
  multibody/tree/test/weld_mobilizer_test.cc
  multibody/tree/universal_mobilizer.cc
  multibody/tree/universal_mobilizer.h
  multibody/tree/weld_joint.cc
  multibody/tree/weld_mobilizer.cc
  multibody/tree/weld_mobilizer.h
Labels: priority: medium, status: squashing now, release notes: none

#22920 [multibody] Add missing mobilizer tests
  multibody/tree/test/curvilinear_mobilizer_test.cc
  multibody/tree/test/mobilizer_tester.h
  multibody/tree/test/planar_mobilizer_test.cc
  multibody/tree/test/prismatic_mobilizer_test.cc
  multibody/tree/test/quaternion_floating_mobilizer_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
  multibody/tree/test/rpy_ball_mobilizer_test.cc
  multibody/tree/test/rpy_floating_mobilizer_test.cc
  multibody/tree/test/screw_mobilizer_test.cc
  multibody/tree/test/universal_mobilizer_test.cc
  multibody/tree/test/weld_mobilizer_test.cc
Labels: priority: medium, release notes: none

#22922 [hotfix] Fix doxygen
  math/rigid_transform.h
Labels: status: single reviewer ok, release notes: none

#22913 Support symbolic scalar type integrators in DiscreteTimeApproximation
  bindings/pydrake/systems/analysis_py.cc
  bindings/pydrake/systems/test/analysis_test.py
  systems/analysis/BUILD.bazel
  systems/analysis/discrete_time_approximation.cc
  systems/analysis/discrete_time_approximation.h
  systems/analysis/simulator_config_functions.cc
  systems/analysis/simulator_config_functions.h
  systems/analysis/test/discrete_time_approximation_test.cc
  systems/analysis/test/simulator_config_functions_test.cc
Labels: priority: medium, release notes: feature

#22924 [render_vtk] Re-enable tests on macOS
  geometry/render_vtk/BUILD.bazel
Labels: release notes: none

#22929 [setup] Upgrade Bazel to latest release 8.2.1
  .bazelversion
  MODULE.bazel
  doc/_pages/from_source.md
  tools/workspace/rules_java/repository.bzl
Labels: status: single reviewer ok, release notes: fix

#22932 [workspace] Upgrade meshcat to latest commit
  tools/workspace/meshcat/repository.bzl
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#22933 [workspace] Bump CRU and VGT with voxel access check fixes
  tools/workspace/common_robotics_utilities_internal/repository.bzl
  tools/workspace/voxelized_geometry_tools_internal/repository.bzl
Labels: status: squashing now, status: single reviewer ok, release notes: fix

#22883 [multibody] Allow reversed revolute joints
  doc/_pages/troubleshooting.md
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree.cc
  multibody/tree/test/multibody_tree_creation_test.cc
Labels: priority: medium, release notes: feature

#22927 [solvers] IpoptSolver accepts integers for floating-point options
  solvers/ipopt_solver.cc
  solvers/test/ipopt_solver_test.cc
Labels: release notes: fix

#22936 [py parsing] Accept pathlib.Path for paths
  bindings/pydrake/multibody/parsing_py.cc
  bindings/pydrake/multibody/test/parsing_test.py
  multibody/parsing/process_model_directives.cc
  multibody/parsing/process_model_directives.h
Labels: priority: low, status: single reviewer ok, release notes: fix

#22925 [multibody] Optimize F & M frames for prismatic joint's mobilizer.
  math/rigid_transform.h
  math/test/rigid_transform_test.cc
  multibody/tree/body_node_impl.cc
  multibody/tree/body_node_impl_mass_matrix.cc
  multibody/tree/joint.cc
  multibody/tree/joint.h
  multibody/tree/mobilizer_impl.h
  multibody/tree/prismatic_joint.cc
  multibody/tree/prismatic_joint.h
  multibody/tree/prismatic_mobilizer.cc
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/revolute_joint.cc
  multibody/tree/revolute_joint.h
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/test/body_node_test.cc
  multibody/tree/test/multibody_tree_test.cc
  multibody/tree/test/prismatic_mobilizer_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
  multibody/tree/weld_joint.cc
Labels: priority: medium, release notes: none

#22945 Test Fixtures and Cleanup for IrisZo (Part 1)
  planning/iris/BUILD.bazel
  planning/iris/test/iris_test_utilities.cc
  planning/iris/test/iris_test_utilities.h
  planning/iris/test/iris_zo_test.cc
Labels: status: squashing now, release notes: none

#22941 [workspace] Remove deprecated externals 2025-05
  tools/performance/BUILD.bazel
  tools/workspace/cc/BUILD.bazel
  tools/workspace/cc/identify_compiler.cc
  tools/workspace/cc/repository.bzl
  tools/workspace/default.bzl
  tools/workspace/glx/repository.bzl
  tools/workspace/liblapack/BUILD.bazel
  tools/workspace/metadata.py
  tools/workspace/opengl/BUILD.bazel
  tools/workspace/opengl/package.BUILD.bazel
  tools/workspace/opengl/repository.bzl
  tools/workspace/pkgconfig_blas_internal/BUILD.bazel
  tools/workspace/pkgconfig_blas_internal/repository.bzl
  tools/workspace/pkgconfig_lapack_internal/BUILD.bazel
  tools/workspace/pkgconfig_lapack_internal/repository.bzl
  tools/workspace/python/package.BUILD.bazel
Labels: priority: low, status: single reviewer ok, release notes: removal of deprecated

#22939 [workspace] Remove deprecated LCM install 2025-05
  lcmtypes/BUILD.bazel
  lcmtypes/test/drake-lcm-spy_install_test.py
  tools/workspace/lcm/BUILD.bazel
  tools/workspace/lcm/lcm-config-version.cmake
  tools/workspace/lcm/lcm-config.cmake
  tools/workspace/lcm/package.BUILD.bazel
  tools/workspace/lcm/test/install_test.py
  tools/workspace/lcm/test/lcm-gen_install_test.py
Labels: priority: medium, status: single reviewer ok, release notes: removal of deprecated

#22908 [systems] Add testing utilities for estimators
  systems/estimators/test_utilities/BUILD.bazel
  systems/estimators/test_utilities/stochastic_linear_system.cc
  systems/estimators/test_utilities/stochastic_linear_system.h
  systems/estimators/test_utilities/sum_matrix_columns_system.cc
  systems/estimators/test_utilities/sum_matrix_columns_system.h
  systems/estimators/test_utilities/test/stochastic_linear_system_test.cc
  systems/estimators/test_utilities/test/sum_matrix_columns_system_test.cc
Labels: release notes: none

#22949 [multibody] Allow reversed prismatic joints
  multibody/plant/test/multibody_plant_test.cc
  multibody/tree/multibody_tree.cc
Labels: priority: medium, release notes: feature

#22950 Create mobilizer functions CalcNDotMatrix() and CalcNplusDotMatrix().
  multibody/tree/mobilizer.cc
  multibody/tree/mobilizer.h
  multibody/tree/prismatic_mobilizer.cc
  multibody/tree/prismatic_mobilizer.h
  multibody/tree/revolute_mobilizer.cc
  multibody/tree/revolute_mobilizer.h
  multibody/tree/test/prismatic_mobilizer_test.cc
  multibody/tree/test/revolute_mobilizer_test.cc
Labels: priority: medium, status: squashing now, release notes: none

#22954 Test Fixtures and Cleanup for IrisZo (Part 2)
  planning/iris/BUILD.bazel
  planning/iris/test/iris_test_utilities.cc
  planning/iris/test/iris_test_utilities.h
  planning/iris/test/iris_zo_test.cc
Labels: status: squashing now, release notes: none
